// ===== Account: sign-in (Claude account / email) + send by email =====
ST.profile=ST.profile||null;
const UX7={acct:T("My account","حسابي"),signin:T("Sign in","تسجيل الدخول"),signout:T("Sign out","تسجيل الخروج"),send:T("Send by email","ابعت بالإيميل"),gmail:T("Send with Gmail","ابعت بـ Gmail")};
function mailBtns(subject,body){const s=encodeURIComponent(subject),b=encodeURIComponent(body.length>1800?body.slice(0,1800)+'\n…':body);const to=encodeURIComponent((ST.profile&&ST.profile.sendTo)||'');
return `<a class="tbtn" href="mailto:${to}?subject=${s}&body=${b}" target="_blank" rel="noopener">✉ ${L(UX7.send)}</a><a class="tbtn" href="https://mail.google.com/mail/?view=cm&fs=1&to=${to}&su=${s}&body=${b}" target="_blank" rel="noopener">✉ ${L(UX7.gmail)}</a>`}
function progressText(){const s=stats();const ar=LANG==='ar';const nm=(ST.profile&&ST.profile.name)||ST.name||'';return ar?`تقرير تقدّم — Claude Mastery\nالمتدرب: ${nm}\nالإنجاز: ${s.pct}% (${s.lessons} درس)\nمتوسط الاختبارات: ${s.quizAvg}%\nالنقط: ${s.xp} · أيام متتالية: ${s.streak}\nالمنصة: ${PLATFORM_URL}`:`Progress report — Claude Mastery\nLearner: ${nm}\nCompletion: ${s.pct}% (${s.lessons} lessons)\nQuiz average: ${s.quizAvg}%\nXP: ${s.xp} · streak: ${s.streak}\nPlatform: ${PLATFORM_URL}`}
async function claudeSignIn(){const note=document.getElementById('acctnote');try{const u=window.claude&&window.claude.use?await window.claude.use('user'):null;if(!u){if(note)note.textContent=LANG==='ar'?'الدخول بحساب Claude متاح لما المنصة تتفتح جوه claude.ai لحد ليه صلاحية عليها. استخدم الدخول بالإيميل.':'Claude sign-in works when the platform is opened on claude.ai by someone it is shared with. Use email sign-in instead.';return}
const me=await u.me();const name=me.name||'';const email=me.email||'';ST.profile={name:name||ST.name||'',email,method:'claude',since:new Date().toISOString().slice(0,10)};if(ST.profile.name)ST.name=ST.profile.name;saveST();addXP(5);render()}catch(e){if(note)note.textContent=LANG==='ar'?'معرفناش نجيب بيانات الحساب — جرّب الدخول بالإيميل.':'Could not read your account — try email sign-in.'}}
function vAcct(){crumb(L(UX7.acct));const ar=LANG==='ar';const p=ST.profile;
if(!p)return `<section class="cdash"><div class="cd-l"><div class="sig">Claude Mastery</div><h1>${L(UX7.signin)}</h1><p>${ar?'سجّل علشان اسمك يظهر على الشهادة والكارت وتقرير التقدّم، وتقدر تبعت تقدّمك بالإيميل.':'Sign in so your name appears on your certificate, card and progress report, and so you can send your progress by email.'}</p></div><div class="cd-r"><div class="qr" style="width:120px">${QR_PLATFORM}</div></div></section>
<div class="twocol"><div class="abpane"><h3>${ar?'بحساب Claude':'With your Claude account'}</h3><p class="note">${ar?'بيستخدم نفس الحساب اللي فاتح بيه claude.ai — سواء دخلت بـ Google أو بالإيميل.':'Uses the account you are signed in to on claude.ai — whether you joined with Google or with email.'}</p><button class="btn-gold gbtn" data-acct="claude"><span class="g">G</span> ${ar?'كمّل بحساب Claude (Google أو إيميل)':'Continue with Claude account (Google or email)'}</button><p class="note" id="acctnote"></p></div>
<div class="abpane"><h3>${ar?'بالإيميل':'With email'}</h3><label class="pbf"><b>${ar?'الاسم':'Name'}</b><input class="search" id="lgname" value="${esc(ST.name||'')}"></label><label class="pbf"><b>${ar?'الإيميل':'Email'}</b><input class="search" id="lgemail" type="email" placeholder="name@company.com" dir="ltr"></label><button class="btn-gold" data-acct="email">${L(UX7.signin)}</button><p class="note">${ar?'بيتحفظ على الجهاز ده بس — مفيش كلمة سر ومفيش سيرفر.':'Saved on this device only — no password and no server.'}</p></div></div>`;
const s=stats();
return `<section class="cdash"><div class="cd-l"><div class="sig">${p.method==='claude'?(ar?'متصل بحساب Claude':'Signed in with Claude account'):(ar?'متصل بالإيميل':'Signed in with email')}</div><h1>${esc(p.name||(ar?'متدرب':'Learner'))}</h1>${p.email?`<p dir="ltr" style="text-align:start">${esc(p.email)}</p>`:`<p><input class="search" id="addemail" type="email" dir="ltr" placeholder="${ar?'ضيف إيميلك':'Add your email'}" style="max-width:320px"></p>`}<div class="hcta"><button class="btn-ghost" data-acct="out">${L(UX7.signout)}</button></div></div><div class="cd-r"><div class="cd-ring">${ring(s.pct)}</div><div class="cd-kpi"><div><b>${s.lessons}</b>${ar?'درس':'lessons'}</div><div><b>${s.quizAvg}%</b>${ar?'اختبارات':'quizzes'}</div><div><b>${s.xp}</b>XP</div><div><b>${s.streak}🔥</b>${ar?'أيام':'days'}</div></div></div></section>
<div class="twocol"><div class="abpane"><h3>✉ ${ar?'ابعت تقدّمك':'Send your progress'}</h3><label class="pbf"><b>${ar?'لمين (إيميل المدرّب أو المدير)':'To (instructor or manager email)'}</b><input class="search" id="sendto" type="email" dir="ltr" value="${esc(p.sendTo||'')}" placeholder="trainer@company.com"></label><pre class="testout" dir="auto">${esc(progressText())}</pre><div class="row-btns">${mailBtns('Claude Mastery — progress',progressText())}</div></div>
<div class="abpane"><h3>${ar?'اختصارات':'Shortcuts'}</h3><div class="chips"><button class="chip" data-go="cert">🎓 ${L(UX.cert)}</button><button class="chip" data-go="card">🏅 ${L(UX6.card)}</button><button class="chip" data-go="cohort">👥 ${L(UX6.cohort)}</button><button class="chip" data-go="wb">✎ ${L(UX4.wb)}</button><button class="chip" data-go="prog">🏅 ${L(UX.prog)}</button></div></div></div>`}
function acctClick(e){const x=e.target.closest('[data-acct]');if(!x)return false;const a=x.dataset.acct;
if(a==='claude')claudeSignIn();
if(a==='email'){const n=document.getElementById('lgname').value.trim(),m=document.getElementById('lgemail').value.trim();if(!n||!/^\S+@\S+\.\S+$/.test(m)){alert(LANG==='ar'?'اكتب اسمك وإيميل صحيح.':'Enter your name and a valid email.');return true}ST.profile={name:n,email:m,method:'email',since:new Date().toISOString().slice(0,10)};ST.name=n;saveST();addXP(5);render()}
if(a==='out'){ST.profile=null;saveST();render()}return true}
document.addEventListener('input',e=>{if(e.target.id==='sendto'&&ST.profile){ST.profile.sendTo=e.target.value;saveST()}});
document.addEventListener('change',e=>{if(e.target.id==='sendto')render();if(e.target.id==='addemail'&&ST.profile&&/^\S+@\S+\.\S+$/.test(e.target.value)){ST.profile.email=e.target.value.trim();saveST();render()}});
