const AGENT_STEPS=[
["🎯",T("Define ONE job","حدد مهمة واحدة"),T("Start with one focused outcome — research, sales, content, support, finance analysis. Don't build a general agent; solve one specific problem.","ابدأ بنتيجة واحدة محددة — بحث، مبيعات، محتوى، دعم، تحليل مالي. متبنيش وكيل عام؛ حل مشكلة واحدة محددة.")],
["🧠",T("Give it a brain","ادّيله عقل"),T("A system prompt with role + goal + rules + constraints. This is the agent's job description.","System prompt فيه الدور + الهدف + القواعد + القيود. ده الوصف الوظيفي للوكيل.")],
["🛠️",T("Add tools","ضيف أدوات"),T("Web search, web fetch, code execution, files, browser/computer, databases, your business APIs. Claude decides when to call a tool; your application or runtime executes it and returns the result.","بحث ويب، قراءة صفحات، تنفيذ كود، ملفات، متصفح/كمبيوتر، قواعد بيانات، APIs شغلك. Claude بيقرر إمتى ينادي الأداة؛ وتطبيقك أو بيئة التشغيل بتنفّذها وترجّع النتيجة.")],
["🔄",T("Build the agentic loop","ابني الحلقة الوكيلية"),T("Goal → Plan → Tool → Result → Review → Repeat → Deliver. Claude calls tools, receives results and keeps working until the task is complete.","الهدف ← الخطة ← الأداة ← النتيجة ← المراجعة ← التكرار ← التسليم. Claude بينادي الأدوات ويستلم النتايج ويكمّل لحد ما المهمة تخلص.")],
["📚",T("Add knowledge + memory","ضيف المعرفة والذاكرة"),T("Your files, data, previous work, SOPs, brand guidelines and business context — so the agent never starts from zero.","ملفاتك وبياناتك وشغلك السابق والإجراءات ودليل البراند وسياق البيزنس — علشان الوكيل ميبدأش من الصفر.")],
["🔌",T("Add MCP","ضيف MCP"),T("Connect external services and data — Google Drive, Gmail, Slack, Calendar, GitHub, Notion, CRM, databases — through a standard protocol, with your permissions.","وصّل الخدمات والبيانات الخارجية — Google Drive و Gmail و Slack و Calendar و GitHub و Notion والـ CRM وقواعد البيانات — ببروتوكول قياسي وبصلاحياتك.")],
["🧩",T("Add Skills","ضيف Skills"),T("Turn repeatable expertise into reusable capabilities: research, writing, data analysis, fact-checking, your own workflow. If you repeat the same instructions, make them a Skill.","حوّل الخبرة المتكررة لقدرات قابلة لإعادة الاستخدام: بحث، كتابة، تحليل بيانات، تدقيق حقايق، طريقتك الخاصة. لو بتكرر نفس التعليمات، اعملها Skill.")],
["🛡️",T("Keep human approval","خلي موافقة الإنسان"),T("The agent prepares important actions; you approve before it sends, posts, pays or changes anything. Start with approval on every external action and automate later.","الوكيل بيجهّز الإجراءات المهمة؛ وإنت بتوافق قبل ما يبعت أو ينشر أو يدفع أو يغيّر أي حاجة. ابدأ بموافقة على كل إجراء خارجي وأتمت بعدين.")]];
const BUILD_ORDER=[[T("Prompt","البرومبت"),T("get good at prompting","اتقن البرومبت")],[T("Context","السياق"),T("add files & info","ضيف ملفات ومعلومات")],[T("Tool","الأداة"),T("add one tool","ضيف أداة واحدة")],[T("Tool loop","حلقة الأدوات"),T("build the loop","ابني الحلقة")],[T("Skills","Skills"),T("reusable workflows","طرق قابلة للتكرار")],[T("MCP","MCP"),T("connect services","وصّل الخدمات")],[T("Memory","الذاكرة"),T("persistent knowledge","معرفة دائمة")],[T("Approval","الموافقة"),T("human in the loop","إنسان في الحلقة")],[T("Production","الإنتاج"),T("full agent","وكيل كامل")]];
const AB=(t,ta,en,ar)=>CM(t,ta,"Agent blueprint","","",["Copy the system prompt","Attach knowledge files","Enable the listed tools/connectors","Run on one real task","Approve outputs; refine rules"],["انسخ الـ system prompt","ارفع ملفات المعرفة","فعّل الأدوات/الـ Connectors المذكورة","شغّله على مهمة حقيقية واحدة","وافق على المخرجات وظبّط القواعد"],en,ar);
DEEP.agentbuild={icon:"🤖",t:T("Build a real AI agent — 8 steps","ابني وكيل AI حقيقي — 8 خطوات"),sub:T("Don't build a chatbot that answers. Build an agent that completes a job.","متبنيش شات بوت بيجاوب. ابني وكيل بيخلّص شغلانة."),
sections:[
{h:T("A real Claude agent needs more than a good prompt","الوكيل الحقيقي محتاج أكتر من برومبت حلو"),b:{en:'@@STEPS_EN@@',ar:'@@STEPS_AR@@'}},
{h:T("The architecture","المعمارية"),b:T(`<div class="flow"><span>GOAL</span>→<span class="hl">CLAUDE</span>→<span>TOOLS + KNOWLEDGE + SKILLS + MCP</span>→<span>AGENTIC LOOP</span>→<span>REVIEW</span>→<span class="ok">RESULT</span></div><p>You don't have to build all the infrastructure yourself. <b>Claude Managed Agents</b> (public beta) host the agent for you — a reusable configuration of model, system prompt, tools, MCP servers and Skills, with sandboxing, checkpoints, scoped permissions and tracing. Inside the Claude app, <b>Cowork</b> plus Projects, Skills, Plugins and Connectors gives you a no-code agent today.</p>`,`<div class="flow"><span>الهدف</span>←<span class="hl">CLAUDE</span>←<span>الأدوات + المعرفة + Skills + MCP</span>←<span>الحلقة الوكيلية</span>←<span>المراجعة</span>←<span class="ok">النتيجة</span></div><p>مش لازم تبني كل البنية التحتية بنفسك. <b>Claude Managed Agents</b> (بيتا عامة) بتستضيف الوكيل ليك — إعداد قابل لإعادة الاستخدام فيه الموديل والـ system prompt والأدوات وسيرفرات MCP والـ Skills، مع بيئة معزولة ونقاط حفظ وصلاحيات محددة وتتبع. وجوه تطبيق Claude، <b>Cowork</b> مع الـ Projects والـ Skills والـ Plugins والـ Connectors بيدّيك وكيل من غير كود النهارده.</p>`)},
{h:T("Chatbot vs agent","شات بوت مقابل وكيل"),b:T(`<div class="vs"><div class="bad"><b>Chatbot — just answers</b><p>You ask a question → Claude → answer.</p></div><div class="good"><b>Agent — completes real work</b><p>Goal (you give a task) → Plan (Claude breaks it down) → Use tools (search, fetch, code…) → Get results & analyse → Review (human approval) → Deliver final output.</p></div></div>`,`<div class="vs"><div class="bad"><b>شات بوت — بيجاوب بس</b><p>بتسأل ← Claude ← إجابة.</p></div><div class="good"><b>وكيل — بيخلّص شغل حقيقي</b><p>الهدف (بتديله مهمة) ← الخطة (Claude بيقسّمها) ← الأدوات (بحث، قراءة، كود…) ← النتايج والتحليل ← المراجعة (موافقة بشرية) ← المخرج النهائي.</p></div></div>`)},
{h:T("Build in this order","ابني بالترتيب ده"),b:{en:'@@ORDER_EN@@',ar:'@@ORDER_AR@@'}},
{h:T("Where to build it","تبنيه فين"),b:T(`<table><tr><th>Level</th><th>Where</th><th>Best for</th></tr><tr><td>No-code</td><td>Claude app: Project + Skills + Connectors + Cowork schedule</td><td>Personal and team agents</td></tr><tr><td>Low-code</td><td>Claude Code + CLAUDE.md + subagents + hooks + MCP</td><td>Automations and internal tools</td></tr><tr><td>Hosted</td><td>Managed Agents</td><td>Production agents without running infrastructure</td></tr><tr><td>Full control</td><td>Agent SDK / Messages API with tool use</td><td>Agents embedded in your products</td></tr></table>`,`<table><tr><th>المستوى</th><th>فين</th><th>الأنسب لـ</th></tr><tr><td>من غير كود</td><td>تطبيق Claude: Project + Skills + Connectors + جدول Cowork</td><td>وكلاء شخصية وللفريق</td></tr><tr><td>كود قليل</td><td>Claude Code + CLAUDE.md + subagents + hooks + MCP</td><td>الأتمتة والأدوات الداخلية</td></tr><tr><td>مستضاف</td><td>Managed Agents</td><td>وكلاء إنتاجية من غير تشغيل بنية تحتية</td></tr><tr><td>تحكم كامل</td><td>Agent SDK / Messages API باستخدام الأدوات</td><td>وكلاء جوه منتجاتك</td></tr></table>`)}
],
cases:[
AB("Content agent — Dr. Sara Salem brand","وكيل المحتوى — براند د. سارة سالم",
["Content agent for 'Dr. Sara Salem — AI Finance Expert'","Research AI-for-finance topics and draft LinkedIn posts and carousels in my voice","- Knowledge: brand voice Skill, 20 best past posts, audience (finance professionals in Egypt & the Gulf), CTA and hashtag rules\n- Tools: web search, web fetch, Drive (content database)\n- Skills: research, writing, hook generation, fact-checking\n- Workflow: topic → research → insights → 3 hooks → post → fact check → QA → final","I want consistent, accurate posts without spending my evenings writing","- Every claim has a source; no invented statistics\n- 3 hook options + 1 final post + carousel slide text\n- Nothing is published — drafts for my approval","Draft folder per post: post.md (Arabic Egyptian + English), carousel.md, sources.md."],
["وكيل محتوى لبراند 'د. سارة سالم — خبيرة AI في المالية'","ابحث في مواضيع الـ AI للمالية واكتب مسودات بوستات وكاروسيل لينكدإن بصوتي","- المعرفة: Skill صوت البراند، أحسن 20 بوست، الجمهور (محترفي المالية في مصر والخليج)، قواعد الدعوة والهاشتاجات\n- الأدوات: بحث ويب، قراءة صفحات، Drive (قاعدة المحتوى)\n- Skills: بحث، كتابة، توليد Hooks، تدقيق حقايق\n- سير العمل: الموضوع ← البحث ← الأفكار ← 3 Hooks ← البوست ← التدقيق ← المراجعة ← النهائي","عايزة بوستات ثابتة ودقيقة من غير ما أقضي الليل في الكتابة","- كل معلومة ليها مصدر؛ مفيش إحصائيات متألّفة\n- 3 Hooks + بوست نهائي + نص شرائح الكاروسيل\n- مفيش نشر — مسودات لموافقتي","فولدر مسودة لكل بوست: post.md (عامية مصرية + إنجليزي)، carousel.md، sources.md."]),
AB("Finance analyst agent","وكيل المحلل المالي",
["Finance analyst agent for a CFO office","Every month, analyse results and prepare the management pack","- Knowledge: chart of accounts, budget, last 3 packs, reporting rules (Project)\n- Tools: ERP read via MCP, code execution, file creation\n- Skills: variance-analysis, finance-report-arabic\n- Loop: pull data → reconcile totals → analyse variances → draft commentary → build deck → self-check","Management decisions within 3 days of close","- Numbers reconcile to the trial balance\n- Every variance >10% explained or marked [ASK]\n- CFO approves before distribution","Variance.xlsx, Pack.pptx, Commentary.docx + a check log."],
["وكيل محلل مالي لمكتب المدير المالي","كل شهر، حلّل النتايج وجهّز حزمة الإدارة","- المعرفة: دليل الحسابات، الموازنة، آخر 3 حزم، قواعد التقارير (Project)\n- الأدوات: قراءة الـ ERP عبر MCP، تنفيذ الكود، إنشاء الملفات\n- Skills: variance-analysis و finance-report-arabic\n- الحلقة: سحب البيانات ← مطابقة الإجماليات ← تحليل الانحرافات ← كتابة التعليق ← بناء العرض ← مراجعة ذاتية","قرارات الإدارة خلال 3 أيام من الإقفال","- الأرقام مطابقة لميزان المراجعة\n- كل انحراف > 10% مشروح أو متعلّم [اسأل]\n- المدير المالي يعتمد قبل التوزيع","Variance.xlsx و Pack.pptx و Commentary.docx + سجل مراجعة."]),
AB("Sales research agent","وكيل أبحاث المبيعات",
["B2B sales research agent","Find and qualify 20 prospects per week for corporate AI-finance training","- ICP: finance teams of 30+ in Egypt, KSA, UAE; banks, FMCG, real estate\n- Tools: web search, web fetch, CRM via MCP (read + draft only)\n- Skills: account-research, draft-outreach","Fill the pipeline with qualified meetings","- Each prospect: why now, decision maker role, fit score, source links\n- Personalised first message (Arabic/English)\n- CRM records created as drafts; I approve sending","Prospects table + outreach drafts + CRM draft list."],
["وكيل أبحاث مبيعات B2B","لاقي وقيّم 20 عميل محتمل كل أسبوع لتدريب الـ AI المالي للشركات","- العميل المثالي: فرق مالية 30+ في مصر والسعودية والإمارات؛ بنوك وسلع استهلاكية وعقارات\n- الأدوات: بحث ويب، قراءة صفحات، CRM عبر MCP (قراءة + مسودات بس)\n- Skills: account-research و draft-outreach","نملا الـ Pipeline باجتماعات مؤهلة","- كل عميل: ليه دلوقتي، دور صاحب القرار، درجة التوافق، روابط المصادر\n- أول رسالة مخصصة (عربي/إنجليزي)\n- سجلات CRM كمسودات؛ وأنا اللي بوافق على الإرسال","جدول العملاء + مسودات التواصل + قائمة مسودات CRM."]),
AB("Customer support agent","وكيل دعم العملاء",
["Customer support agent for an online academy","Answer learner questions from our documentation and escalate the rest","- Knowledge: FAQ, refund policy, course catalogue, certificate rules (RAG with citations)\n- Tools: ticket creation; enrolment status (read-only)\n- Arabic (Egyptian) and English","Answer most questions instantly with the right policy","- Every answer cites the policy\n- Refunds, complaints and anything not in the docs are escalated\n- Never promises exceptions","System prompt + escalation rules + 20 test conversations."],
["وكيل دعم عملاء لأكاديمية أونلاين","جاوب أسئلة المتعلمين من الوثائق وصعّد الباقي","- المعرفة: الأسئلة الشائعة، سياسة الاسترداد، كتالوج الكورسات، قواعد الشهادات (RAG باستشهادات)\n- الأدوات: فتح تذكرة؛ حالة التسجيل (قراءة بس)\n- عربي (مصري) وإنجليزي","نجاوب معظم الأسئلة فوراً بالسياسة الصح","- كل إجابة بتذكر السياسة\n- الاسترداد والشكاوى وأي حاجة مش في الوثائق بتتصعّد\n- عمره ما يوعد باستثناءات","System prompt + قواعد التصعيد + 20 محادثة اختبار."])
]};
(function(){const s=AGENT_STEPS;const cards=l=>`<div class="steps8">`+s.map((x,i)=>`<div class="s8"><div class="n">${i+1}</div><div class="e">${x[0]}</div><b>${x[1][l]}</b><p>${x[2][l]}</p></div>`).join('')+`</div>`;
const order=l=>`<div class="order">`+BUILD_ORDER.map((x,i)=>`<div><b>${i+1}. ${x[0][l]}</b><span>${x[1][l]}</span></div>`).join('')+`</div>`;
DEEP.agentbuild.sections[0].b={en:cards('en'),ar:cards('ar')};DEEP.agentbuild.sections[3].b={en:order('en')+'<p class="note">Start simple and gradually add capabilities.</p>',ar:order('ar')+'<p class="note">ابدأ بسيط وزوّد القدرات بالتدريج.</p>'};})();
// Mastery map (inspired by the complete Claude mastery map)
const MAP=[
{n:"01",t:T("Foundation","الأساس"),d:T("Master the basics and learn how to work effectively with Claude.","اتقن الأساسيات واتعلم تشتغل بفعالية مع Claude."),items:[[T("Claude fundamentals","أساسيات Claude"),"day/1/1.1"],[T("Prompt engineering: role + context + goal + constraints + output","هندسة البرومبت: دور + سياق + هدف + قيود + مخرج"),"day/1/1.4"],[T("Context engineering","هندسة السياق"),"day/2/2.4"],[T("Few-shot prompting","البرومبت بالأمثلة"),"day/1/1.5"],[T("Styles & personalisation","الأساليب والتخصيص"),"day/2/2.5"]]},
{n:"02",t:T("Workflow","سير العمل"),d:T("Go beyond single prompts and build consistent workflows.","اتخطى البرومبت الواحد وابني سير عمل ثابت."),items:[[T("Projects","Projects"),"day/2/2.2"],[T("Prompt chaining: research → analyse → create → review → refine","تسلسل البرومبتات: بحث ← تحليل ← إنشاء ← مراجعة ← تحسين"),"deep/prompting"],[T("Deep research","البحث المعمّق"),"day/2/2.1"],[T("Data analysis","تحليل البيانات"),"lab"],[T("Artifacts","Artifacts"),"day/3/3.1"]]},
{n:"03",t:T("Power features","المميزات القوية"),d:T("Unlock advanced capabilities and connect your tools and data.","افتح القدرات المتقدمة ووصّل أدواتك وبياناتك."),items:[[T("Skills","Skills"),"day/4/4.1"],[T("Connectors","Connectors"),"day/4/4.3"],[T("MCP & security controls","MCP وضوابط الأمان"),"deep/mcpsec"],[T("Claude Code","Claude Code"),"day/7/7.1"],[T("CLAUDE.md","CLAUDE.md"),"day/7/7.1"]]},
{n:"04",t:T("Agents","الوكلاء"),d:T("Move from chatbot to agents that use tools and complete real work.","انتقل من الشات بوت لوكلاء بيستخدموا أدوات ويخلّصوا شغل حقيقي."),items:[[T("Tool use","استخدام الأدوات"),"deep/agentbuild"],[T("Agentic loops","الحلقات الوكيلية"),"deep/agentbuild"],[T("Subagents","الوكلاء الفرعيين"),"deep/integration"],[T("Agent skills","Skills للوكلاء"),"skills"],[T("Human in the loop","إنسان في الحلقة"),"day/9/9.2"]]},
{n:"05",t:T("Claude Code mastery","إتقان Claude Code"),d:T("Use Claude as a coding partner to build real applications.","استخدم Claude كشريك برمجة تبني تطبيقات حقيقية."),items:[[T("Basics, CLAUDE.md, commands","الأساسيات و CLAUDE.md والأوامر"),"day/7/7.1"],[T("Skills, hooks, subagents, plugins","Skills و hooks و subagents و plugins"),"deep/playbook"],[T("MCP servers","سيرفرات MCP"),"deep/integration"],[T("Git & testing","Git والاختبارات"),"day/7/7.1"],[T("Multi-agent development","تطوير بوكلاء متعددين"),"deep/integration"]]},
{n:"06",t:T("Build AI employees","ابني موظفين AI"),d:T("Specialised AI workers for each role in your business.","موظفين AI متخصصين لكل دور في البيزنس."),items:[[T("Research agent","وكيل أبحاث"),"deep/agentbuild"],[T("Content agent","وكيل محتوى"),"deep/agentbuild"],[T("Sales agent","وكيل مبيعات"),"deep/agentbuild"],[T("Support agent","وكيل دعم"),"deep/agentbuild"],[T("Finance & data agent","وكيل مالي وبيانات"),"deep/agentbuild"]]},
{n:"07",t:T("Build with Claude","ابني بـ Claude"),d:T("Turn skills into real systems, products and business workflows.","حوّل المهارات لأنظمة ومنتجات وسير عمل حقيقي."),items:[[T("AI sales & CRM systems","أنظمة مبيعات و CRM"),"lab"],[T("AI customer support","دعم عملاء بالـ AI"),"cases"],[T("Mini-ERP & integrations","Mini-ERP والتكامل"),"deep/integration"],[T("AI SaaS products & websites","منتجات SaaS ومواقع"),"day/7/7.3"],[T("Multi-agent systems","أنظمة وكلاء متعددين"),"deep/agentic"]]}];
const JOURNEY=[[T("Beginner","مبتدئ"),T("\"Claude, write this.\"","\"Claude، اكتب ده.\"")],[T("Intermediate","متوسط"),T("\"Claude, analyse this and create this.\"","\"Claude، حلّل ده واعمل ده.\"")],[T("Advanced","متقدم"),T("\"Claude, follow this workflow.\"","\"Claude، امشي على سير العمل ده.\"")],[T("Power user","مستخدم محترف"),T("\"Claude, use these tools and complete this task.\"","\"Claude، استخدم الأدوات دي وخلّص المهمة.\"")],[T("Agent builder","باني وكلاء"),T("\"Claude, here's the goal. Plan, execute, review and deliver.\"","\"Claude، ده الهدف. خطّط ونفّذ وراجع وسلّم.\"")],[T("Mastery","الإتقان"),T("Systems where Claude repeatedly delivers valuable work with the right tools, knowledge and oversight.","أنظمة Claude بيسلّم فيها شغل قيّم بشكل متكرر بالأدوات والمعرفة والإشراف الصح.")]];
const LADDER=["Prompt","Context","Project","Skill","Connector","Claude Code","Tools","Agentic loop","AI employees","AI business systems"];
const PLATFORM_URL="https://claude.ai/artifact/SWKveDA1ZfXuaeRLhm1mu5";
