let AS={open:false,msgs:[],busy:false};
const ASK_SUG=T(["How do I build a sales forecast with Claude?","Build me a mini-ERP — where do I start?","Secure an MCP connector for our ERP","Automate month-end close with Cowork"],["إزاي أعمل توقع مبيعات بـ Claude؟","عايز أبني Mini-ERP — أبدأ منين؟","أأمّن Connector MCP للـ ERP إزاي؟","أأتمت إقفال الشهر بـ Cowork"]);
function asGuess(q){q=q.toLowerCase();const has=(...w)=>w.some(x=>q.includes(x));
let what='ask';if(has('excel','اكسل','إكسيل','sheet','نموذج','model','dcf','forecast','توقع'))what='excel';if(has('pdf','file','ملف','analy','حلل','تحليل','data','بيانات'))what=what==='ask'?'files':what;if(has('dashboard','داشبورد','website','موقع','deck','عرض','design','تصميم','app','تطبيق','landing'))what='deliver';if(has('gmail','drive','crm','erp','connector','mcp','hubspot','notion','ربط','وصّل'))what='data';if(has('folder','فولدر','automate','أتمت','schedule','جدول','cowork','close','إقفال'))what='multi';if(has('script','code','كود','claude code','build','ابني','mini-erp','rag'))what='code';if(has('api','agent','وكيل','sdk','integration','تكامل'))what='system';
const role=has('sales','مبيعات','crm')?['Sales operations analyst','محلل عمليات مبيعات']:has('hr','موارد','cv','توظيف')?['HR business partner','شريك موارد بشرية']:has('market','تسويق','content','محتوى')?['Marketing and content lead','مسؤول تسويق ومحتوى']:has('audit','مراجعة','risk','مخاطر')?['Internal auditor','مراجع داخلي']:has('code','api','mcp','erp','build','ابني')?['Senior solutions engineer','مهندس حلول أول']:['Senior finance and business analyst','محلل مالي وبيزنس أول'];
return {what,role}}
function asOffline(q){const g=asGuess(q);const R=pickRec({what:g.what,rep:'once',team:'me'})[0];if(!IDX)buildIdx();const terms=q.toLowerCase().split(/\s+/).filter(w=>w.length>2);
const rel=IDX.map(x=>({x,s:terms.reduce((a,t)=>a+(x.txt.includes(t)?1:0),0)})).filter(r=>r.s>0).sort((a,b)=>b.s-a.s).slice(0,4);
const en=MPen(g.role[0],q,"- Files/data: [attach or describe]\n- Period, currency, audience: [..]\n- Constraints: [..]","[The decision or outcome this supports]","- [Checklist of what done looks like]\n- Numbers traced to sources","[Table / memo / xlsx / deck / app], [language], [length]");
const ar=MPar(g.role[1],q,"- الملفات/البيانات: [ارفع أو اوصف]\n- الفترة والعملة والجمهور: [..]\n- القيود: [..]","[القرار أو النتيجة اللي بيدعمها]","- [قائمة شكل الانتهاء]\n- الأرقام ليها مصادر","[جدول / مذكرة / xlsx / عرض / تطبيق]، [اللغة]، [الطول]");
const steps=LANG==='ar'?[`استخدم: ${R.tool}`,'جهّز الملفات والسياق (أو Project)','الصق البرومبت الماستر واملا الأقواس','خليه يسألك أسئلة توضيحية الأول','راجع الناتج على شروط التوقف','احفظ البرومبت أو حوّله Skill لو هيتكرر']:[`Use: ${R.tool}`,'Prepare files and context (or a Project)','Paste the master prompt and fill the brackets','Let Claude ask clarifying questions first','Review the output against the stop conditions','Save the prompt, or turn it into a Skill if it repeats'];
return {kind:'offline',why:L(R.why),route:R.route,steps,en,ar,rel}}
function asRender(){let b=document.getElementById('asbox');if(!b){b=document.createElement('div');b.id='asbox';document.body.appendChild(b)}const ar=LANG==='ar';
if(!AS.open){b.innerHTML=`<button class="asfab" data-as="open" aria-label="Assistant">💬<span>${ar?'اسأل المساعد':'Ask the assistant'}</span></button>`;return}
const msg=m=>{if(m.role==='user')return `<div class="msg user">${esc(m.text)}</div>`;if(m.kind==='offline'){const ie=PSTORE.push(m.en)-1,ia=PSTORE.push(m.ar)-1;return `<div class="msg assistant"><b>${ar?'الأداة المقترحة':'Suggested tool'}:</b> ${esc(m.why)} <a href="#${m.route}">${ar?'الدرس':'Lesson'} →</a><ol>${m.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="asp"><div class="ph"><b>Master prompt (EN)</b><button class="copy" data-i="${ie}">${L(UI.copy)}</button></div><pre dir="ltr">${esc(m.en)}</pre></div><div class="asp"><div class="ph"><b>البرومبت الماستر (عربي)</b><button class="copy" data-i="${ia}">${L(UI.copy)}</button></div><pre dir="rtl">${esc(m.ar)}</pre></div>${m.rel.length?`<div class="k">${ar?'من المنصة':'From the platform'}: ${m.rel.map(r=>`<a href="#${r.x.r}">${esc(L(r.x.t))}</a>`).join(' · ')}</div>`:''}</div>`}
return `<div class="msg assistant">${fmtMD(m.text)}${m.prompts?m.prompts.map(p=>{const i=PSTORE.push(p)-1;return `<button class="copy" data-i="${i}" style="margin:4px 4px 0 0">${L(UI.copy)} ${p.match(/[\u0600-\u06FF]/)?'(AR)':'(EN)'}</button>`}).join(''):''}</div>`};
b.innerHTML=`<div class="aspanel"><div class="ashead"><b>💬 ${ar?'مساعد البناء':'Build assistant'}</b><span class="k">${ar?'اسأل عن أي حاجة تبنيها — خطوات + برومبت ماستر عربي وإنجليزي':'Ask about anything you want to build — steps + master prompt in English and Arabic'}</span><button class="tbtn" data-as="close">✕</button></div><div class="asmsgs" id="asmsgs">${AS.msgs.length?AS.msgs.map(msg).join(''):`<div class="chips">${L(ASK_SUG).map((s,i)=>`<button class="chip" data-assug="${i}">${esc(s)}</button>`).join('')}</div>`}${AS.busy?'<div class="msg assistant" id="aslive">…</div>':''}</div><div class="ask"><textarea id="asq" rows="2" placeholder="${ar?'عايز تبني إيه؟':'What do you want to build?'}"></textarea><button class="dlbtn" data-as="send" ${AS.busy?'disabled':''}>${ar?'اسأل':'Ask'}</button></div></div>`;
const mm=document.getElementById('asmsgs');if(mm)mm.scrollTop=mm.scrollHeight}
async function asAsk(q){if(!q.trim()||AS.busy)return;AS.msgs.push({role:'user',text:q});const sample=await tutorSample();
if(!sample){AS.msgs.push(asOffline(q));asRender();return}
AS.busy=true;asRender();const toc=DAYS.map(d=>d.units.map(u=>u.id+' '+u.t.en).join('; ')).join('\n');
const sys=`You are the build assistant of the "Claude Mastery" platform by Dr. Sara Salem (finance & business professionals, Egypt and the Gulf). For ANY question, reply in this exact structure:\n1) One-paragraph answer: which Claude surface to use and why (Chat/Projects, Skills, Connectors/MCP, Cowork, Claude for Excel, Artifacts/Design, Claude Code, API/Agents).\n2) Numbered steps (5–8).\n3) A full master prompt in ENGLISH inside a fenced code block, using XML tags: <role>, <task>, <context>, <reasoning>, <stop_when>, <output_format>, ending with: ask up to 3 clarifying questions, label assumptions, verify numbers, mark items for human review.\n4) The same master prompt in ARABIC (Egyptian-friendly) inside a second fenced code block.\n5) One line pointing to the relevant lesson id from: \n${toc}\nWrite the explanation in ${LANG==='ar'?'Egyptian Arabic':'English'}. Never invent product features; if unsure, say so.`;
try{const {text}=await sample([{role:'user',content:sys},{role:'assistant',content:'OK.'},...AS.msgs.filter(m=>m.role==='user'||m.text).slice(-6).map(m=>({role:m.role,content:m.role==='user'?m.text:m.text}))],{cache:false,modelTier:'default',onText:({text})=>{const l=document.getElementById('aslive');if(l)l.innerHTML=fmtMD(text)}});
const prompts=[...text.matchAll(/```[a-z]*\n([\s\S]*?)```/g)].map(x=>x[1].trim());AS.msgs.push({role:'assistant',text,prompts})}
catch(e){AS.msgs.push(Object.assign(asOffline(q),{}))}
AS.busy=false;asRender()}
document.addEventListener('click',e=>{const x=e.target.closest('[data-as],[data-assug]');if(!x)return;if(x.dataset.assug!==undefined){asAsk(L(ASK_SUG)[+x.dataset.assug]);return}const a=x.dataset.as;if(a==='open'){AS.open=true;asRender();setTimeout(()=>{const t=document.getElementById('asq');t&&t.focus()},50)}if(a==='close'){AS.open=false;asRender()}if(a==='send'){const t=document.getElementById('asq');asAsk(t.value)}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&e.target.id==='asq'){e.preventDefault();asAsk(e.target.value)}});
