CASES.push(
{k:"legal",icon:"§",t:T("Legal & contracts","القانوني والعقود"),items:[
CM("Contract risk review","مراجعة مخاطر عقد","Project · Docs","Supplier agreement before signing.","عقد مورد قبل التوقيع.",["Upload contract + playbook","Run review","Lawyer confirms"],["ارفع العقد ودليل التفاوض","شغّل المراجعة","المحامي يأكد"],
["Senior commercial-contracts reviewer for an Egyptian company (not a substitute for a licensed lawyer)","Review the attached supply agreement against our negotiation playbook","- Governing law: Egyptian\n- Our position: buyer\n- Red lines: liability cap ≥ contract value, payment 60 days, termination for convenience\n- Playbook attached","Management signs next week and needs to know what to push back on","- Every clause compared to the playbook\n- Each deviation rated High/Medium/Low\n- Fallback wording proposed for every High item","Table: Clause | Current text (short) | Playbook position | Risk | Proposed wording. Then a 5-line summary for the CEO. Mark items needing a lawyer's review."],
["مراجع عقود تجارية أول لشركة مصرية (مش بديل عن محامي مرخّص)","راجع عقد التوريد المرفق مقابل دليل التفاوض بتاعنا","- القانون الحاكم: المصري\n- موقفنا: مشتري\n- الخطوط الحمرا: سقف المسؤولية ≥ قيمة العقد، الدفع 60 يوم، حق الإنهاء للملاءمة\n- الدليل مرفق","الإدارة هتوقّع الأسبوع الجاي ومحتاجة تعرف تعترض على إيه","- كل بند متقارن بالدليل\n- كل انحراف متقيّم عالي/متوسط/منخفض\n- صياغة بديلة لكل بند عالي الخطورة","جدول: البند | النص الحالي (مختصر) | موقف الدليل | الخطورة | الصياغة المقترحة. وبعدين ملخص 5 سطور للمدير التنفيذي. علّم على اللي محتاج مراجعة محامي."]),
CM("NDA first draft","مسودة اتفاقية سرية","Docs","Mutual NDA for a partnership.","اتفاقية سرية متبادلة لشراكة.",["Facts","Draft","Legal review"],["الحقايق","المسودة","مراجعة قانونية"],
["Commercial lawyer's drafting assistant","Draft a mutual NDA","- Parties: [A] Egypt, [B] UAE\n- Purpose: evaluating a training partnership\n- Term: 2 years, confidentiality survives 3 years\n- Governing law: [to choose]","We need a clean first draft for counsel to edit","- Standard clauses present: definition, exclusions, obligations, return/destruction, remedies, term, law and jurisdiction\n- Placeholders for every missing fact","Word-ready text in English with an Arabic translation side by side, clause numbers, placeholders in [BRACKETS]. Flag clauses counsel must check."],
["مساعد صياغة لمحامي تجاري","اكتب مسودة اتفاقية سرية متبادلة","- الأطراف: [أ] مصر، [ب] الإمارات\n- الغرض: تقييم شراكة تدريب\n- المدة: سنتين والسرية مستمرة 3 سنين\n- القانون الحاكم: [يُحدد]","محتاجين مسودة أولى نضيفة المستشار يعدّل عليها","- البنود الأساسية موجودة: التعريف، الاستثناءات، الالتزامات، الإرجاع/الإتلاف، الجزاءات، المدة، القانون والاختصاص\n- أماكن فاضية لأي معلومة ناقصة","نص جاهز لـ Word بالإنجليزي مع ترجمة عربي جنبه، ترقيم للبنود، والفراغات بين [أقواس]. علّم على البنود اللي لازم المستشار يراجعها."])]},
{k:"ops",icon:"⚙",t:T("Operations & supply chain","العمليات وسلاسل الإمداد"),items:[
CM("Inventory health & reorder","صحة المخزون وإعادة الطلب","Excel · Cowork","Stock-outs and dead stock at the same time.","نفاد مخزون ومخزون راكد في نفس الوقت.",["Export stock + sales","Run analysis","Approve reorder list"],["صدّر المخزون والمبيعات","شغّل التحليل","وافق على قائمة الطلب"],
["Supply-chain analyst for an Egyptian distributor","Analyse inventory and propose a reorder plan","- Files: stock.xlsx (SKU, qty, cost), sales_12m.xlsx, lead_times.xlsx\n- Service level target 95%\n- Import lead times 45–90 days; FX exposure in USD","Cash is tight and we can't afford both stock-outs and dead stock","- ABC/XYZ classification done\n- Safety stock and reorder point per SKU\n- Dead stock (no sale 180 days) listed with value","xlsx: Classification, Reorder (SKU, ROP, order qty, cost), Dead stock. Plus a 1-page memo with cash impact in EGP."],
["محلل سلاسل إمداد لموزّع مصري","حلّل المخزون واقترح خطة إعادة طلب","- الملفات: stock.xlsx (الصنف، الكمية، التكلفة)، sales_12m.xlsx، lead_times.xlsx\n- مستوى خدمة مستهدف 95%\n- مدة الاستيراد 45–90 يوم؛ تعرّض للدولار","السيولة ضيقة ومش قادرين على نفاد ومخزون راكد مع بعض","- تصنيف ABC/XYZ\n- مخزون أمان ونقطة إعادة طلب لكل صنف\n- المخزون الراكد (مفيش بيع 180 يوم) بقيمته","xlsx: التصنيف، إعادة الطلب (الصنف، النقطة، الكمية، التكلفة)، الراكد. ومذكرة صفحة بالأثر النقدي بالجنيه."]),
CM("Shipment & LC timeline tracker","متابعة الشحنات والاعتمادات","Artifact","Import shipments tied to LC expiry dates.","شحنات استيراد مربوطة بتواريخ انتهاء الاعتمادات.",["Fields","Build tracker","Share with team"],["الحقول","ابني المتابع","شاركه مع الفريق"],
["Trade-operations product designer","Build an interactive import tracker","- Fields: PO, supplier, LC no., latest shipment date, expiry, ETA, port, docs status, clearance status\n- Alerts: shipment date within 10 days, expiry within 15 days\n- Arabic/English, RTL","Late shipments under an LC create discrepancies and demurrage costs","- Add/edit/filter works\n- Alerts are colour-coded\n- CSV export works","Single-page HTML artifact, navy/gold, with sample data for 8 shipments."],
["مصمم منتجات لعمليات التجارة","ابني متابع استيراد تفاعلي","- الحقول: أمر الشراء، المورد، رقم الاعتماد، آخر موعد شحن، الانتهاء، الوصول المتوقع، الميناء، حالة المستندات، حالة الإفراج\n- تنبيهات: موعد الشحن خلال 10 أيام، الانتهاء خلال 15 يوم\n- عربي/إنجليزي، RTL","الشحن المتأخر تحت اعتماد بيعمل مخالفات وأرضيات","- الإضافة والتعديل والفلترة شغالين\n- التنبيهات ملونة\n- التصدير CSV شغال","Artifact صفحة HTML واحدة، كحلي/دهبي، ببيانات تجريبية لـ 8 شحنات."])]},
{k:"procurement",icon:"⇄",t:T("Procurement","المشتريات"),items:[
CM("Supplier comparison & award","مقارنة الموردين والترسية","Excel · Docs","Three quotes for packaging material.","3 عروض لمواد تغليف.",["Upload quotes","Weighted scoring","Award memo"],["ارفع العروض","تقييم مرجّح","مذكرة ترسية"],
["Procurement manager","Compare supplier quotes and recommend an award","- 3 quotes attached (prices in USD/EUR/EGP)\n- Criteria: total landed cost 40%, quality 25%, lead time 15%, payment terms 10%, supplier risk 10%\n- FX: use rates in rates.csv","The committee needs a defensible, auditable decision","- All quotes converted to EGP landed cost\n- Scores shown with evidence\n- Sensitivity: does the winner change if FX moves 10%?","xlsx scoring sheet + 1-page award memo in Arabic with an English summary."],
["مدير مشتريات","قارن عروض الموردين واقترح الترسية","- 3 عروض مرفقة (أسعار بالدولار واليورو والجنيه)\n- المعايير: التكلفة الواصلة 40%، الجودة 25%، مدة التوريد 15%، شروط الدفع 10%، مخاطر المورد 10%\n- أسعار الصرف من rates.csv","اللجنة محتاجة قرار قابل للدفاع والمراجعة","- كل العروض محوّلة لتكلفة واصلة بالجنيه\n- الدرجات بأدلة\n- حساسية: الفائز يتغير لو الصرف اتحرك 10%؟","شيت تقييم xlsx + مذكرة ترسية صفحة بالعربي مع ملخص إنجليزي."])]},
{k:"cs",icon:"☏",t:T("Customer service","خدمة العملاء"),items:[
CM("Complaint triage & replies","فرز الشكاوى والردود","Cowork · Gmail","100+ complaints a week.","أكتر من 100 شكوى في الأسبوع.",["Connect inbox","Classify","Drafts for approval"],["وصّل البريد","صنّف","مسودات للموافقة"],
["Customer-experience lead","Triage this week's complaints and draft replies","- Source: support inbox (Gmail connector)\n- Categories: billing, delivery, quality, staff, other\n- Tone: warm, accountable, Egyptian Arabic for Arabic senders\n- Compensation policy attached","Faster, consistent answers reduce churn","- Every email categorised with urgency\n- Draft reply for each, nothing sent\n- Top 3 root causes with counts","Table + drafts saved in the inbox as drafts. Weekly root-cause summary for operations."],
["مسؤول تجربة العملاء","افرز شكاوى الأسبوع ده واكتب مسودات ردود","- المصدر: بريد الدعم (Gmail connector)\n- الفئات: الفواتير، التوصيل، الجودة، الموظفين، أخرى\n- النبرة: دافية ومسؤولة، عامية مصرية للي بيكتب عربي\n- سياسة التعويض مرفقة","الردود الأسرع والمتسقة بتقلل خسارة العملاء","- كل إيميل متصنّف بأولوية\n- مسودة رد لكل واحد ومفيش حاجة تتبعت\n- أكبر 3 أسباب جذرية بالأعداد","جدول + مسودات محفوظة في البريد كمسودات. وملخص أسبوعي للأسباب الجذرية للعمليات."])]},
{k:"risk",icon:"⚖",t:T("Risk, audit & compliance","المخاطر والمراجعة والالتزام"),items:[
CM("Internal audit work programme","برنامج عمل مراجعة داخلية","Project · audit-support","Auditing the procure-to-pay cycle.","مراجعة دورة الشراء حتى الدفع.",["Upload policy + process","Risk & control matrix","Test plan"],["ارفع السياسة والإجراء","مصفوفة المخاطر والضوابط","خطة الاختبار"],
["Internal audit manager (IIA standards)","Build a risk-based audit programme for procure-to-pay","- Policy and process map attached\n- ERP: [name]; 1,800 POs last year\n- Prior findings: split POs, late approvals","The audit committee wants assurance on fraud and leakage risk","- Risk & control matrix complete\n- Test steps and sample sizes per control\n- Data analytics tests listed (duplicates, split POs, weekend postings)","xlsx RCM + Word programme + list of analytics with the fields needed from the ERP."],
["مدير مراجعة داخلية (معايير IIA)","ابني برنامج مراجعة مبني على المخاطر لدورة الشراء حتى الدفع","- السياسة وخريطة الإجراءات مرفقين\n- الـ ERP: [الاسم]؛ 1800 أمر شراء السنة اللي فاتت\n- ملاحظات سابقة: تجزئة أوامر الشراء، تأخير الموافقات","لجنة المراجعة عايزة تأكيد على مخاطر الغش والتسرب","- مصفوفة المخاطر والضوابط كاملة\n- خطوات الاختبار وحجم العينة لكل ضابط\n- اختبارات تحليل بيانات (التكرار، التجزئة، القيود في الإجازات)","مصفوفة xlsx + برنامج Word + قائمة التحليلات بالحقول المطلوبة من الـ ERP."]),
CM("AML/KYC file review (first pass)","مراجعة ملف KYC (مرحلة أولى)","Project · Skill","Corporate onboarding pack.","ملف تأسيس عميل شركة.",["Upload pack","Checklist review","Compliance decides"],["ارفع الملف","مراجعة القائمة","الالتزام يقرر"],
["KYC analyst assistant (first pass only)","Review the onboarding pack against our KYC checklist","- Documents: commercial register, tax card, IDs of signatories, UBO declaration, bank reference\n- Checklist attached; high-risk countries list attached","Speed up onboarding without lowering standards","- Every checklist item marked present/missing/expired\n- Inconsistencies between documents listed\n- Red flags listed with evidence","Table + a note 'for compliance officer decision'. Never conclude approve/reject."],
["مساعد محلل KYC (مرحلة أولى بس)","راجع ملف تأسيس العميل على قائمة KYC بتاعتنا","- المستندات: السجل التجاري، البطاقة الضريبية، بطاقات المفوضين، إقرار المستفيد الحقيقي، خطاب مرجعي من بنك\n- القائمة مرفقة وقائمة الدول عالية المخاطر","نسرّع التأسيس من غير ما نقلل المعايير","- كل بند متعلّم موجود/ناقص/منتهي\n- التعارضات بين المستندات\n- الإشارات الحمرا بالأدلة","جدول + ملاحظة 'لقرار مسؤول الالتزام'. متوصلش أبداً لموافقة أو رفض."])]},
{k:"banking",icon:"🏦",t:T("Banking & treasury","البنوك والخزينة"),items:[
CM("Credit memo","مذكرة ائتمان","Excel · Docs · Skill","EGP 50M working-capital facility.","تسهيل رأس مال عامل 50 مليون جنيه.",["Spread financials","Ratios & covenants","Memo"],["حلل القوائم","النسب والتعهدات","المذكرة"],
["Senior credit analyst at an Egyptian bank","Write a credit memo for a working-capital facility","- 3 years audited statements + 9-month management accounts\n- Request: EGP 50M revolving, 12 months\n- Bank limits: DSCR ≥1.25, Debt/EBITDA ≤3.5, current ratio ≥1.2\n- Collateral: receivables assignment","The credit committee meets Thursday","- Spreading complete with ratios and trends\n- Covenant headroom and stress (sales −20%, EGP −15%)\n- Risks and mitigants","Word memo: summary, company, industry, financial analysis, stress test, risks/mitigants, recommendation with conditions. Appendix tables from Excel."],
["محلل ائتمان أول في بنك مصري","اكتب مذكرة ائتمان لتسهيل رأس مال عامل","- قوائم مراجعة 3 سنين + حسابات إدارية 9 شهور\n- الطلب: 50 مليون جنيه متجدد لمدة 12 شهر\n- حدود البنك: DSCR ≥ 1.25، الدين/EBITDA ≤ 3.5، التداول ≥ 1.2\n- الضمان: حوالة حق للعملاء","لجنة الائتمان يوم الخميس","- التحليل كامل بالنسب والاتجاهات\n- هامش التعهدات والضغط (مبيعات −20%، الجنيه −15%)\n- المخاطر والمخففات","مذكرة Word: ملخص، الشركة، القطاع، التحليل المالي، اختبار الضغط، المخاطر والمخففات، التوصية بالشروط. وجداول ملحق من Excel."]),
CM("FX exposure & hedging","التعرض لسعر الصرف والتحوط","Excel · Opus","Importer with USD payables.","مستورد عليه التزامات بالدولار.",["Map exposures","Scenarios","Hedge options"],["حدد التعرضات","السيناريوهات","خيارات التحوط"],
["Treasury adviser specialising in emerging-market FX","Measure FX exposure and compare hedging options","- USD payables schedule (12 months) attached\n- USD receivables small\n- Available tools: forwards (if offered), natural hedging, LC usance, pricing clauses","Management must decide a hedging policy for next year","- Net exposure by month\n- P&L and cash impact at +10/+20/+30% USD\n- Pros/cons and cost of each tool, Egypt-specific constraints noted","xlsx exposure model + 2-page policy recommendation."],
["مستشار خزينة متخصص في عملات الأسواق الناشئة","قيس التعرض لسعر الصرف وقارن خيارات التحوط","- جدول الالتزامات بالدولار (12 شهر) مرفق\n- المستحقات بالدولار قليلة\n- الأدوات المتاحة: العقود الآجلة (لو متاحة)، التحوط الطبيعي، الاعتماد الآجل، بنود التسعير","الإدارة لازم تقرر سياسة تحوط للسنة الجاية","- صافي التعرض بالشهر\n- الأثر على الربح والنقدية عند +10/+20/+30% للدولار\n- مزايا وعيوب وتكلفة كل أداة مع قيود السوق المصري","نموذج تعرض xlsx + توصية سياسة صفحتين."])]},
{k:"pm",icon:"▦",t:T("Project management","إدارة المشروعات"),items:[
CM("Project charter + WBS","ميثاق المشروع وهيكل العمل","Docs · Excel","ERP rollout in 6 months.","تطبيق ERP في 6 شهور.",["Goals","WBS + schedule","Risks & RACI"],["الأهداف","هيكل العمل والجدول","المخاطر و RACI"],
["PMP-certified project manager","Create the project charter, WBS and schedule","- Project: ERP finance module rollout, 3 entities\n- Budget EGP 4M, go-live in 6 months\n- Team: 1 PM, 2 finance key users, vendor team of 4","The steering committee approves the plan on Sunday","- Charter: objectives, scope in/out, success criteria\n- WBS to level 3 with durations and dependencies\n- RACI and top 10 risks with responses","Docs charter + xlsx Gantt-style schedule + risk register."],
["مدير مشروعات معتمد PMP","اعمل ميثاق المشروع وهيكل تقسيم العمل والجدول","- المشروع: تطبيق موديول المالية في ERP لـ 3 شركات\n- الميزانية 4 مليون جنيه، والتشغيل خلال 6 شهور\n- الفريق: مدير مشروع، 2 مستخدمين رئيسيين من المالية، فريق المورد 4","لجنة التوجيه هتعتمد الخطة يوم الأحد","- الميثاق: الأهداف، النطاق داخل/خارج، معايير النجاح\n- هيكل العمل لمستوى 3 بالمدد والاعتماديات\n- RACI وأهم 10 مخاطر بالاستجابة","ميثاق Docs + جدول xlsx بشكل Gantt + سجل مخاطر."]),
CM("Weekly status report","تقرير الحالة الأسبوعي","Cowork schedule","PM spends 3 hours on status every week.","مدير المشروع بيقضي 3 ساعات في تقرير الحالة كل أسبوع.",["Connect tracker","Template","Schedule"],["وصّل المتابع","القالب","الجدولة"],
["Project management office analyst","Produce the weekly status report","- Sources: task tracker export, risk register, budget sheet, last week's report\n- RAG rules: schedule slip >5 days = amber, >10 = red; budget >5% = amber","Leaders want a consistent 1-page view","- Overall RAG with reason\n- Milestones done/next\n- Top risks and decisions needed","One-page docx in the PMO template, saved as Status_[date].docx; draft email to sponsors (not sent)."],
["محلل مكتب إدارة المشروعات","طلّع تقرير الحالة الأسبوعي","- المصادر: تصدير متابع المهام، سجل المخاطر، شيت الميزانية، تقرير الأسبوع اللي فات\n- قواعد الألوان: تأخير > 5 أيام = أصفر، > 10 = أحمر؛ الميزانية > 5% = أصفر","القيادات عايزة صفحة واحدة ثابتة","- اللون العام بالسبب\n- المراحل اللي خلصت والجاية\n- أهم المخاطر والقرارات المطلوبة","docx صفحة بقالب مكتب المشروعات، محفوظ Status_[التاريخ].docx؛ ومسودة إيميل للرعاة (من غير إرسال)."])]},
{k:"data",icon:"▥",t:T("Data analysis","تحليل البيانات"),items:[
CM("Sales deep-dive","تحليل مبيعات متعمق","Chat · code execution","Why did Q3 sales drop?","ليه مبيعات الربع التالت نزلت؟",["Upload data","Hypothesis tree","Charts & answer"],["ارفع البيانات","شجرة الفروض","رسوم وإجابة"],
["Senior data analyst","Explain the Q3 sales decline","- sales.csv: date, region, channel, product, customer, qty, price\n- Q3 down 11% vs Q2\n- Known events: price increase in July, new competitor in Alexandria","Management wants the real drivers, not guesses","- Data quality checked (nulls, duplicates)\n- Decomposition by region, channel, product, price vs volume\n- Mix effects checked (Simpson's paradox)","Top 3 drivers with numbers, 4 charts, the code used, and a confidence level for each conclusion."],
["محلل بيانات أول","فسّر نزول مبيعات الربع التالت","- sales.csv: التاريخ، المنطقة، القناة، المنتج، العميل، الكمية، السعر\n- الربع التالت أقل 11% عن التاني\n- أحداث معروفة: زيادة سعر في يوليو، منافس جديد في إسكندرية","الإدارة عايزة الأسباب الحقيقية مش تخمينات","- فحص جودة البيانات (الفاضي، التكرار)\n- تفكيك حسب المنطقة والقناة والمنتج والسعر مقابل الكمية\n- فحص أثر المزيج","أهم 3 أسباب بالأرقام، 4 رسوم، الكود المستخدم، ومستوى ثقة لكل استنتاج."]),
CM("Customer segmentation (RFM)","تقسيم العملاء (RFM)","Code execution · Artifact","Marketing wants targeted offers.","التسويق عايز عروض موجهة.",["Transactions","RFM scoring","Segment actions"],["المعاملات","تقييم RFM","إجراء لكل شريحة"],
["Customer analytics specialist","Segment customers with RFM and recommend actions","- transactions.csv (customer_id, date, amount), 24 months\n- 18,000 customers","We have budget for 3 campaigns only","- RFM quintiles and 6–8 named segments\n- Size and revenue share per segment\n- One action and offer per segment","Segment table, interactive dashboard artifact, and a CSV of customer_id → segment."],
["متخصص تحليلات عملاء","قسّم العملاء بـ RFM واقترح إجراءات","- transactions.csv (رقم العميل، التاريخ، المبلغ)، 24 شهر\n- 18 ألف عميل","معانا ميزانية 3 حملات بس","- خمسيات RFM و 6–8 شرائح بأسماء\n- الحجم ونسبة الإيراد لكل شريحة\n- إجراء وعرض لكل شريحة","جدول الشرائح، Artifact داشبورد تفاعلي، و CSV فيه رقم العميل ← الشريحة."])]},
{k:"workflow",icon:"⇢",t:T("Workflow design","تصميم سير العمل"),items:[
CM("Approval workflow redesign","إعادة تصميم دورة الموافقات","Chat · Docs","Capex approvals take 3 weeks.","موافقات الاستثمارات بتاخد 3 أسابيع.",["Map current","Design target","Controls"],["ارسم الحالي","صمّم المستهدف","الضوابط"],
["Finance process-improvement consultant","Redesign the capex approval workflow","- Current: paper form → 5 signatures → finance → CEO\n- Thresholds: <EGP 250K, 250K–2M, >2M\n- Tools: email, SharePoint, Slack","Cut cycle time without weakening control","- Current vs target flow (Mermaid)\n- Digital form fields and validation rules\n- Approval matrix and SLA per step; audit trail","Docs SOP + Mermaid diagrams + approval matrix table + KPI list."],
["استشاري تحسين عمليات مالية","اعد تصميم دورة موافقات الاستثمارات","- الحالي: نموذج ورقي ← 5 توقيعات ← المالية ← المدير التنفيذي\n- الحدود: أقل من 250 ألف، 250 ألف–2 مليون، أكتر من 2 مليون\n- الأدوات: إيميل، SharePoint، Slack","نقلل الوقت من غير ما نضعف الرقابة","- الحالي مقابل المستهدف (Mermaid)\n- حقول النموذج الرقمي وقواعد التحقق\n- مصفوفة الموافقات ومدة كل خطوة؛ سجل تدقيق","SOP على Docs + مخططات Mermaid + جدول مصفوفة الموافقات + قائمة المؤشرات."])]},
{k:"rag",icon:"⌕",t:T("RAG & knowledge assistants","RAG ومساعدي المعرفة"),items:[
CM("Policy assistant — no-code RAG","مساعد السياسات — RAG بدون كود","Project","Staff ask finance-policy questions.","الموظفين بيسألوا عن السياسات المالية.",["Upload policies","Grounding instructions","Test 20 questions"],["ارفع السياسات","تعليمات الالتزام بالمصدر","اختبر 20 سؤال"],
["Finance policy assistant","Answer questions strictly from the uploaded policies","- Knowledge: travel, expense, procurement, delegation-of-authority policies\n- Users: all staff, Arabic and English","A Project is the simplest RAG: retrieval over your files without code","- Every answer quotes the policy and section\n- If not in the files: say so and direct to finance\n- No outside knowledge","Short answer + quoted source + section. Use these as Project instructions."],
["مساعد السياسات المالية","جاوب الأسئلة من السياسات المرفوعة بس","- المعرفة: سياسات السفر والمصروفات والمشتريات وتفويض الصلاحيات\n- المستخدمين: كل الموظفين، عربي وإنجليزي","الـ Project هو أبسط RAG: استرجاع من ملفاتك من غير كود","- كل إجابة بتقتبس السياسة والبند\n- لو مش موجود في الملفات قول كده ووجّه للمالية\n- مفيش معلومات من برّه","إجابة قصيرة + اقتباس المصدر + البند. استخدم ده كتعليمات الـ Project."]),
CM("RAG app with the API","تطبيق RAG بالـ API","Claude Code · API","Searchable knowledge base of 2,000 circulars.","قاعدة معرفة بحث في 2000 تعميم.",["Ingest & chunk","Embeddings + vector store","Claude answers with citations"],["الإدخال والتقطيع","Embeddings وقاعدة متجهات","Claude يجاوب باستشهادات"],
["Senior AI engineer","Build a RAG service over regulatory circulars","- 2,000 PDFs (Arabic and English)\n- Stack: Python, FastAPI, an embeddings provider of your choice (Anthropic doesn't offer embeddings), a vector DB (e.g. pgvector), Claude via the Messages API with the citations feature\n- Hybrid search (BM25 + vectors)","Compliance needs answers grounded in the exact circular","- Ingestion with Arabic normalisation and chunking with overlap\n- Retrieval eval on 30 test questions\n- Answers cite document and page; refuse when evidence is missing","/plan first, then code with tests, README, and a CLAUDE.md. Report retrieval accuracy."],
["مهندس AI أول","ابني خدمة RAG على التعليمات الرقابية","- 2000 ملف PDF (عربي وإنجليزي)\n- التقنيات: Python و FastAPI ومزوّد Embeddings تختاره (Anthropic مش بتقدم Embeddings) وقاعدة متجهات (زي pgvector) و Claude عبر Messages API بخاصية الاستشهادات\n- بحث هجين (BM25 + متجهات)","الالتزام محتاج إجابات مستندة للتعميم بالظبط","- إدخال بتوحيد العربي وتقطيع بتداخل\n- تقييم الاسترجاع على 30 سؤال اختبار\n- الإجابات بتذكر المستند والصفحة؛ وترفض لو مفيش دليل","/plan الأول، وبعدين الكود بالاختبارات و README و CLAUDE.md. اعرض دقة الاسترجاع."])]},
{k:"games",icon:"◈",t:T("Games & gamified learning","الألعاب والتعلم باللعب"),items:[
CM("Finance quiz game","لعبة اختبار مالية","Artifact","Make a course module fun.","خلي وحدة الكورس ممتعة.",["Content","Game mechanics","Publish"],["المحتوى","آليات اللعبة","النشر"],
["Game designer for adult learning","Build a browser quiz game on financial ratios","- 30 questions (easy/medium/hard), Arabic and English\n- Mechanics: timer, streak bonus, 3 lives, leaderboard on this device\n- Brand: navy/gold","Learners retain more when they play","- Works on mobile\n- Explanation after each answer\n- Score summary with weak topics","Single HTML artifact, accessible, with sound off by default."],
["مصمم ألعاب لتعليم الكبار","ابني لعبة اختبار في المتصفح عن النسب المالية","- 30 سؤال (سهل/متوسط/صعب)، عربي وإنجليزي\n- الآليات: مؤقت، مكافأة سلسلة، 3 أرواح، لوحة صدارة على نفس الجهاز\n- البراند: كحلي/دهبي","المتعلم بيفتكر أكتر لما بيلعب","- شغالة على الموبايل\n- شرح بعد كل إجابة\n- ملخص الدرجة بالمواضيع الضعيفة","Artifact HTML واحد، سهل الوصول، والصوت مقفول افتراضياً."]),
CM("Business simulation game","لعبة محاكاة بيزنس","Artifact · Claude Code","CFO simulation for trainees.","محاكاة مدير مالي للمتدربين.",["Rules & model","Rounds","Debrief"],["القواعد والنموذج","الجولات","التقييم"],
["Serious-game designer and FP&A expert","Build a 6-round CFO simulation","- Each round: choose price, marketing spend, inventory, financing\n- Random events: FX shock, supplier delay, demand spike\n- Model: simple P&L, cash and balance sheet each round","Trainees learn trade-offs between profit, cash and risk","- Financial statements balance every round\n- Events logged and explained\n- Final debrief scores profit, cash, risk","HTML artifact with charts per round; then offer a Claude Code version with a backend."],
["مصمم ألعاب جادة وخبير FP&A","ابني محاكاة مدير مالي 6 جولات","- كل جولة: السعر، مصروف التسويق، المخزون، التمويل\n- أحداث عشوائية: صدمة صرف، تأخير مورد، قفزة طلب\n- النموذج: قائمة دخل ونقدية وميزانية بسيطة كل جولة","المتدرب يتعلم الموازنة بين الربح والنقدية والمخاطر","- القوائم متوازنة كل جولة\n- الأحداث مسجلة ومشروحة\n- تقييم نهائي للربح والنقدية والمخاطر","Artifact HTML برسوم لكل جولة؛ وبعدين اعرض نسخة Claude Code بباك إند."])]},
{k:"apps",icon:"▢",t:T("Applications","التطبيقات"),items:[
CM("Expense app with receipt scanning","تطبيق مصاريف بقراءة الإيصالات","Claude Code · API","Field staff submit paper receipts.","الموظفين في الميدان بيقدموا إيصالات ورق.",["Design","Build","Test & deploy"],["التصميم","البناء","الاختبار والنشر"],
["Full-stack engineer","Build an expense app","- Web app (mobile-first), Arabic/English\n- Photo of receipt → Claude vision extracts date, vendor, amount, VAT, category (structured outputs)\n- Approval by manager; export to accounting CSV","Cut reimbursement time from 2 weeks to 2 days","- Extraction accuracy checked on 20 sample receipts\n- Role-based access; no API key in the frontend\n- Tests and README","/plan, then code (FastAPI + React or similar), CLAUDE.md, and a short deployment guide."],
["مطوّر Full-stack","ابني تطبيق مصاريف","- تطبيق ويب (موبايل أولاً)، عربي/إنجليزي\n- صورة الإيصال ← رؤية Claude تطلّع التاريخ والمورد والمبلغ والضريبة والفئة (مخرجات مهيكلة)\n- موافقة المدير؛ تصدير CSV للمحاسبة","نقلل وقت الاسترداد من أسبوعين ليومين","- دقة الاستخراج متجربة على 20 إيصال\n- صلاحيات حسب الدور؛ ومفيش API key في الواجهة\n- اختبارات و README","/plan، وبعدين الكود (FastAPI و React أو شبههم)، CLAUDE.md، ودليل نشر قصير."])]},
{k:"erp",icon:"▤",t:T("Mini-ERP & system integration","Mini-ERP وتكامل الأنظمة"),items:[
CM("Mini-ERP as an artifact","Mini-ERP كـ Artifact","Artifact","Small trading company without an ERP.","شركة تجارية صغيرة من غير ERP.",["Modules","Data model","Build & test"],["الموديولات","نموذج البيانات","البناء والاختبار"],
["ERP solution architect and accountant","Build a mini-ERP for a small trading company","- Modules: items & inventory (weighted average cost), customers & sales invoices, suppliers & purchase invoices, receipts & payments, automatic journal entries, trial balance, AR/AP aging\n- VAT 14%, currency EGP, Arabic/English\n- Persist data in the artifact's storage","Show how far a no-code Claude build can go before buying an ERP","- Every invoice posts a balanced journal\n- Trial balance always balances\n- Inventory never goes negative without a warning","Single-file HTML app with sample data, a 'Reset demo' button and a guide tab."],
["مهندس حلول ERP ومحاسب","ابني Mini-ERP لشركة تجارية صغيرة","- الموديولات: الأصناف والمخزون (متوسط مرجح)، العملاء وفواتير البيع، الموردين وفواتير الشراء، المقبوضات والمدفوعات، قيود تلقائية، ميزان مراجعة، أعمار العملاء والموردين\n- ضريبة قيمة مضافة 14%، العملة جنيه، عربي/إنجليزي\n- حفظ البيانات في تخزين الـ Artifact","نوري لحد فين ممكن نبني بـ Claude من غير كود قبل شراء ERP","- كل فاتورة بترحّل قيد متوازن\n- ميزان المراجعة متوازن دايماً\n- المخزون ميبقاش سالب من غير تحذير","تطبيق HTML ملف واحد ببيانات تجريبية وزرار 'إعادة الديمو' وتبويب دليل."]),
CM("Connect the mini-ERP to Claude with MCP","توصيل الـ Mini-ERP بـ Claude عبر MCP","Claude Code · MCP","Ask Claude questions about live ERP data.","تسأل Claude عن بيانات الـ ERP الحية.",["API layer","MCP server","Connect & test"],["طبقة API","سيرفر MCP","الربط والاختبار"],
["Integration engineer","Expose the mini-ERP to Claude through an MCP server","- Database: SQLite/Postgres with items, invoices, journals\n- Tools to expose (read-only first): get_trial_balance(period), get_aging(type, as_of), search_invoices(filters), get_item_stock(sku)\n- Later write tool: create_draft_invoice (needs human approval)\n- Remote MCP over HTTPS with OAuth","The CFO wants to ask 'What's overdue over 90 days?' in plain language","- Each tool has a clear title and readOnlyHint/destructiveHint\n- Tested in MCP Inspector\n- Added to Claude as a custom connector","/plan, then TypeScript or Python MCP server with tests, README, and a connector setup guide."],
["مهندس تكامل أنظمة","اعرض الـ Mini-ERP لـ Claude عبر سيرفر MCP","- قاعدة البيانات: SQLite/Postgres فيها الأصناف والفواتير والقيود\n- الأدوات (قراءة فقط الأول): get_trial_balance(period)، get_aging(type, as_of)، search_invoices(filters)، get_item_stock(sku)\n- أداة كتابة بعدين: create_draft_invoice (محتاجة موافقة بشرية)\n- MCP عن بُعد على HTTPS بـ OAuth","المدير المالي عايز يسأل 'إيه المتأخر أكتر من 90 يوم؟' بلغة عادية","- كل أداة ليها عنوان واضح و readOnlyHint/destructiveHint\n- متجربة في MCP Inspector\n- متضافة لـ Claude كـ Connector مخصص","/plan، وبعدين سيرفر MCP بـ TypeScript أو Python باختبارات و README ودليل إعداد الـ Connector."])]},
{k:"content2",icon:"✍",t:T("Content creation systems","أنظمة صناعة المحتوى"),items:[
CM("Content operating system","نظام تشغيل المحتوى","Project · Skill · Cowork","Creator posting 5×/week across 3 platforms.","صانع محتوى بينشر 5 مرات في الأسبوع على 3 منصات.",["Voice & pillars","Calendar","Batch production"],["الصوت والمحاور","الخطة","الإنتاج بالجملة"],
["Head of content for a finance-education brand","Set up a monthly content system and produce week 1","- Brand: Dr. Sara Salem — AI Finance Expert\n- Pillars: AI tools, FP&A, trade finance, careers\n- Platforms: LinkedIn (EN/AR), Instagram (Egyptian Arabic), YouTube (long-form)\n- Samples of best posts attached","Consistency and quality beat volume","- Monthly calendar by pillar and format\n- Week 1 fully written: 5 posts, 2 carousels (slide text), 1 video outline\n- Each piece has hook, value, CTA","Calendar table + week-1 drafts + a SKILL.md capturing the brand voice for future weeks."],
["رئيس محتوى لبراند تعليم مالي","جهّز نظام محتوى شهري وطلّع الأسبوع الأول","- البراند: د. سارة سالم — خبيرة AI في المالية\n- المحاور: أدوات AI، FP&A، التمويل التجاري، المسار المهني\n- المنصات: لينكدإن (إنجليزي/عربي)، إنستجرام (عامية مصرية)، يوتيوب (طويل)\n- عينات من أحسن البوستات مرفقة","الاستمرارية والجودة أهم من الكمية","- خطة شهرية بالمحاور والأشكال\n- الأسبوع الأول مكتوب كامل: 5 بوستات، 2 كاروسيل (نص الشرائح)، مخطط فيديو\n- كل قطعة فيها Hook وقيمة ودعوة","جدول الخطة + مسودات الأسبوع الأول + ملف SKILL.md بيمسك صوت البراند للأسابيع الجاية."])]}
);
