// ===== 7. PROMPT CHAINS: one linked chain per field; each step feeds the next =====
const CHAINS={};
function CH(k,ten,tar,steps){CHAINS[k]={t:T(ten,tar),steps:steps.map(s=>({t:T(s[0],s[1]),p:T(MPen(...ENR(s[2])),MPar(...ENR(s[3],1)))}))}}
const O1='[output of step 1]',O2='[output of step 2]',A1='[مخرج الخطوة 1]',A2='[مخرج الخطوة 2]';

CH('sales','From CRM export to Monday decisions','من تصدير CRM لقرارات الاتنين',[
['Clean the data','نضّف البيانات',["Sales operations analyst","List data-quality issues in the CRM export","- Attached: crm_deals.csv","Decisions need clean data","- Each issue counted by rep\n- No deal deleted","Issue table by rep."],["محلل عمليات مبيعات","طلّع مشاكل جودة البيانات في تصدير CRM","- مرفق: crm_deals.csv","القرارات محتاجة بيانات نضيفة","- كل مشكلة متعدّة لكل مندوب\n- مفيش صفقة تتمسح","جدول المشاكل حسب المندوب."]],
['Score the pipeline','قيّم الـ pipeline',["Sales analyst","Score every open deal for risk using the cleaned view","- Issues found: "+O1+"\n- Risk rules: 21+ days silent, past close date, no decision maker","The director needs a ranked risk list","- Weighted value per rep\n- Risk reason per deal","Ranked risk table."],["محلل مبيعات","قيّم كل صفقة مفتوحة من ناحية الخطر بعد التنضيف","- المشاكل اللي لقيناها: "+A1+"\n- قواعد الخطر: 21+ يوم سكوت، تاريخ إقفال فات، مفيش صاحب قرار","المدير محتاج قائمة خطر مترتبة","- القيمة المرجّحة لكل مندوب\n- سبب الخطر لكل صفقة","جدول خطر مترتب."]],
['Write the meeting brief','اكتب ملخص الاجتماع',["Sales director’s chief of staff","Turn the risk list into Monday’s meeting brief","- Risk list: "+O2,"The meeting must end with owners and dates","- Three decisions with owners\n- One question per rep","One-page brief."],["مدير مكتب مدير المبيعات","حوّل قائمة الخطر لملخص اجتماع الاتنين","- قائمة الخطر: "+A2,"الاجتماع لازم يخلص بمسؤولين ومواعيد","- 3 قرارات بمسؤولين\n- سؤال لكل مندوب","ملخص في صفحة."]]]);
CH('finance','From trial balance to board commentary','من ميزان المراجعة لشرح المجلس',[
['Find the variances','طلّع الانحرافات',["Finance analyst","Compute budget-vs-actual variances and flag material lines","- Attached: bva.csv\n- Materiality: EGP 250k or 5%","Only material lines go forward","- Every line computed; material ones flagged","Variance table."],["محلل مالي","احسب انحرافات الموازنة مقابل الفعلي وعلّم البنود المهمة","- مرفق: bva.csv\n- الأهمية: 250 ألف جنيه أو 5%","البنود المهمة بس هي اللي تكمل","- كل بند محسوب؛ والمهم متعلّم","جدول الانحرافات."]],
['Explain the drivers','اشرح الأسباب',["FP&A business partner","Explain each material variance with its driver","- Material lines: "+O1+"\n- Notes from budget owners: [paste]","The CFO needs causes, not numbers","- Driver per line (price, volume, timing, one-off)\n- Lines without explanation flagged","Explanation table + questions for owners."],["شريك أعمال FP&A","اشرح كل انحراف مهم بسببه","- البنود المهمة: "+A1+"\n- ملاحظات مسؤولي الموازنة: [الصق]","المدير المالي محتاج الأسباب مش الأرقام","- السبب لكل بند (سعر، كمية، توقيت، حدث لمرة)\n- البنود من غير شرح متعلّمة","جدول الشرح + أسئلة للمسؤولين."]],
['Draft the board text','اكتب نص المجلس',["CFO","Write the board commentary from the explanations","- Explanations: "+O2,"Board members read it in five minutes","- Three messages: performance, risks, outlook\n- Numbers match the table","Half-page commentary."],["المدير المالي","اكتب شرح المجلس من التفسيرات","- التفسيرات: "+A2,"أعضاء المجلس بيقروه في 5 دقايق","- 3 رسايل: الأداء، المخاطر، التوقعات\n- الأرقام زي الجدول","شرح في نص صفحة."]]]);
CH('banking','From borrower file to credit memo','من ملف العميل لمذكرة الائتمان',[
['Check completeness','راجع الاكتمال',["Credit analyst","Check the credit file against the bank checklist","- Checklist and documents: [attach]","Committee time is wasted on incomplete files","- Present / missing / unclear per item","Checklist table + requests."],["محلل ائتمان","راجع ملف الائتمان مقابل قائمة البنك","- القائمة والمستندات: [ارفع]","وقت اللجنة بيضيع على الملفات الناقصة","- موجود / ناقص / مش واضح لكل بند","جدول القائمة + الطلبات."]],
['Analyse financials','حلل القوائم المالية',["Credit analyst","Analyse three years of financials","- Attached: credit_fin.csv\n- File status: "+O1,"The risk view must be evidence-based","- Ratios with formulas\n- Trends and red flags","Ratio table + red flags."],["محلل ائتمان","حلل قوائم 3 سنين","- مرفق: credit_fin.csv\n- حالة الملف: "+A1,"رأي الخطر لازم يكون بالأدلة","- النسب بالمعادلات\n- الاتجاهات والعلامات الحمرا","جدول النسب + العلامات الحمرا."]],
['Draft the memo','اكتب المذكرة',["Senior credit analyst","Draft the credit memo","- Analysis: "+O2+"\n- Facility requested: [paste]","The committee decides","- Recommendation framed for committee judgement\n- Conditions and covenants proposed","Credit memo."],["محلل ائتمان أول","اكتب مسودة مذكرة الائتمان","- التحليل: "+A2+"\n- التسهيل المطلوب: [الصق]","اللجنة هي اللي بتقرر","- التوصية لحكم اللجنة\n- الشروط والتعهدات المقترحة","مذكرة ائتمان."]]]);
CH('audit','From population to findings','من المجتمع للملاحظات',[
['Plan the test','خطط للاختبار',["Internal auditor","Design the test steps for the control","- Control description and policy: [paste]","The test must be reproducible","- Steps tied to the control\n- Sampling method documented","Test plan."],["مراجع داخلي","صمّم خطوات اختبار الضابط","- وصف الضابط والسياسة: [الصق]","الاختبار لازم يكون قابل للتكرار","- الخطوات مربوطة بالضابط\n- طريقة العينة موثقة","خطة الاختبار."]],
['Run the test','نفّذ الاختبار',["Internal auditor","Apply the test plan to the sample","- Plan: "+O1+"\n- Sample: [attach]","Exceptions must be evidenced","- Result per item with evidence reference\n- Exceptions listed","Results table + exceptions."],["مراجع داخلي","طبّق خطة الاختبار على العينة","- الخطة: "+A1+"\n- العينة: [ارفع]","الاستثناءات لازم تكون بالدليل","- النتيجة لكل بند بمرجع الدليل\n- الاستثناءات متسجلة","جدول النتايج + الاستثناءات."]],
['Write the findings','اكتب الملاحظات',["Audit senior","Draft findings from the exceptions","- Exceptions: "+O2,"Management must agree actions","- Condition, criteria, cause, effect, recommendation\n- Severity rating","Findings draft."],["سينيور مراجعة","اكتب مسودة الملاحظات من الاستثناءات","- الاستثناءات: "+A2,"الإدارة لازم توافق على الإجراءات","- الوضع، المعيار، السبب، الأثر، التوصية\n- تقييم الخطورة","مسودة الملاحظات."]]]);
CH('tradefin','From LC terms to presentation','من شروط الاعتماد للتقديم',[
['Extract LC terms','استخرج شروط الاعتماد',["Trade finance officer","Extract the key terms from the LC","- LC (MT700): [paste]","Every document will be checked against these terms","- Amounts, dates, documents required, special conditions","Terms checklist."],["مسؤول تمويل تجارة","استخرج الشروط الأساسية من الاعتماد","- الاعتماد (MT700): [الصق]","كل مستند هيتراجع مقابل الشروط دي","- المبالغ والمواعيد والمستندات المطلوبة والشروط الخاصة","قائمة الشروط."]],
['Check the documents','افحص المستندات',["Document checker","Check the documents against the terms","- Terms: "+O1+"\n- Documents: lc.csv","Discrepancies must be found before presentation","- Each discrepancy quoted with article reference","Discrepancy table."],["فاحص مستندات","افحص المستندات مقابل الشروط","- الشروط: "+A1+"\n- المستندات: lc.csv","المخالفات لازم تتكشف قبل التقديم","- كل مخالفة مقتبسة بمرجع المادة","جدول المخالفات."]],
['Draft the client notice','اكتب إخطار العميل',["Trade relationship manager","Write the discrepancy notice to the client","- Discrepancies: "+O2,"The client must fix or waive quickly","- Plain language, options (amend, waive, correct)\n- Bilingual","Notice in English and Arabic."],["مدير علاقة تمويل تجارة","اكتب إخطار المخالفات للعميل","- المخالفات: "+A2,"العميل لازم يصلّح أو يتنازل بسرعة","- لغة بسيطة واختيارات (تعديل، تنازل، تصحيح)\n- باللغتين","إخطار بالإنجليزي والعربي."]]]);
CH('hr','From vacancy to offer','من الشاغر للعرض',[
['Write the job description','اكتب الوصف الوظيفي',["HR business partner","Write the job description from the manager’s notes","- Notes: [paste]\n- Grade and band: [..]","Good hires start with clear must-haves","- Must-haves vs nice-to-haves\n- Inclusive language","Job description."],["شريك أعمال موارد بشرية","اكتب الوصف الوظيفي من ملاحظات المدير","- الملاحظات: [الصق]\n- الدرجة والشريحة: [..]","التعيين الكويس بيبدأ بأساسيات واضحة","- الأساسيات مقابل الإضافات\n- لغة شاملة","الوصف الوظيفي."]],
['Screen candidates','افرز المرشحين',["Talent acquisition specialist","Screen CVs against the job description","- Job description: "+O1+"\n- CVs: [attach, anonymised]","Managers interview only strong fits","- Evidence quoted per must-have\n- No personal characteristics considered","Shortlist + interview questions."],["أخصائي استقطاب","افرز السير الذاتية مقابل الوصف","- الوصف: "+A1+"\n- السير الذاتية: [ارفع، من غير أسماء]","المديرين يقابلوا المناسبين بس","- دليل مقتبس لكل أساسي\n- من غير اعتبار للصفات الشخصية","القائمة المختصرة + أسئلة المقابلة."]],
['Prepare the offer','جهّز العرض',["Compensation specialist","Prepare the offer for the chosen candidate","- Shortlist and interview notes: "+O2+"\n- Salary band and policy: [paste]","The offer must be fair and within band","- Salary within band with rationale\n- Offer letter draft","Offer summary + letter."],["متخصص تعويضات","جهّز العرض للمرشح المختار","- القائمة وملاحظات المقابلة: "+A2+"\n- شريحة المرتب والسياسة: [الصق]","العرض لازم يكون عادل وجوه الشريحة","- مرتب جوه الشريحة بالمبرر\n- مسودة خطاب العرض","ملخص العرض + الخطاب."]]]);
CH('marketing','From results to next month’s plan','من النتايج لخطة الشهر الجاي',[
['Analyse results','حلل النتايج',["Marketing analyst","Analyse last month’s campaign results","- Attached: campaigns.csv","Budget must follow performance","- CPL and ROAS per campaign\n- Winners and losers","Results table."],["محلل تسويق","حلل نتايج حملات الشهر اللي فات","- مرفق: campaigns.csv","الميزانية لازم تمشي ورا الأداء","- تكلفة العميل والعائد لكل حملة\n- الكسبانين والخسرانين","جدول النتايج."]],
['Reallocate budget','وزّع الميزانية',["Performance marketer","Propose next month’s budget split","- Results: "+O1+"\n- Total budget: EGP [x]","Spend should move to what works","- Moves limited to ±25% per channel\n- Test budget kept at 10%","Budget table."],["مسوّق أداء","اقترح تقسيم ميزانية الشهر الجاي","- النتايج: "+A1+"\n- الميزانية الكلية: [x] جنيه","الصرف لازم يروح للي شغال","- التحريك في حدود ±25% لكل قناة\n- ميزانية التجارب 10%","جدول الميزانية."]],
['Brief the creatives','اكتب تكليف الإبداع',["Marketing lead","Write the creative brief for next month","- Budget plan: "+O2+"\n- Brand guide: [paste]","The agency needs one clear brief","- Audience, message, channels, deliverables, dates","Creative brief."],["رئيس التسويق","اكتب تكليف الإبداع للشهر الجاي","- خطة الميزانية: "+A2+"\n- دليل البراند: [الصق]","الوكالة محتاجة تكليف واحد واضح","- الجمهور والرسالة والقنوات والمخرجات والمواعيد","تكليف الإبداع."]]]);
CH('content','From one article to a week of content','من مقال واحد لأسبوع محتوى',[
['Extract ideas','طلّع الأفكار',["Content strategist","Pull the 5 strongest ideas from the article","- Article: [paste]","One article should feed a week","- Each idea with the supporting quote","Idea list."],["استراتيجي محتوى","طلّع أقوى 5 أفكار من المقال","- المقال: [الصق]","مقال واحد لازم يغذّي أسبوع","- كل فكرة بالاقتباس اللي يدعمها","قائمة الأفكار."]],
['Write the posts','اكتب البوستات',["Social editor","Write one post per idea","- Ideas: "+O1+"\n- Platforms: LinkedIn, Instagram","Each post must stand alone","- Under 150 words\n- Hook and question","5 posts."],["محرر سوشيال","اكتب بوست لكل فكرة","- الأفكار: "+A1+"\n- المنصات: لينكدإن، إنستجرام","كل بوست لازم يقف لوحده","- أقل من 150 كلمة\n- جملة جذب وسؤال","5 بوستات."]],
['Schedule and measure','جدول وقيس',["Content manager","Build the posting schedule and what to measure","- Posts: "+O2,"We learn from every week","- Day, time, platform\n- Metric per post","Schedule table."],["مدير محتوى","اعمل جدول النشر وإيه اللي نقيسه","- البوستات: "+A2,"بنتعلم من كل أسبوع","- اليوم والوقت والمنصة\n- مؤشر لكل بوست","جدول النشر."]]]);
CH('operations','From stock data to purchase orders','من بيانات المخزون لأوامر الشراء',[
['Find the risks','حدد المخاطر',["Supply planner","Find SKUs at risk of stock-out","- Attached: inventory.csv","Customers must not be affected","- Days of cover vs lead time","At-risk list."],["مخطط إمداد","حدد الأصناف المعرضة للنفاد","- مرفق: inventory.csv","العملاء ميتأثروش","- أيام التغطية مقابل مدة التوريد","قائمة المعرّض للخطر."]],
['Size the orders','احسب الكميات',["Inventory planner","Calculate order quantities for the at-risk SKUs","- At-risk list: "+O1+"\n- Safety stock rule and MOQ: [paste]","Orders must be right-sized","- Formula shown per SKU\n- Total value","Order proposal."],["مخطط مخزون","احسب كميات الطلب للأصناف المعرضة للخطر","- القائمة: "+A1+"\n- قاعدة مخزون الأمان وأقل كمية: [الصق]","الطلبات لازم تكون بالحجم الصح","- المعادلة لكل صنف\n- القيمة الإجمالية","مقترح الطلب."]],
['Draft supplier emails','اكتب إيميلات الموردين',["Purchasing officer","Draft the purchase order emails","- Orders: "+O2+"\n- Supplier contacts: [paste]","Suppliers confirm today","- One email per supplier\n- Ask for confirmation of date","Email drafts."],["مسؤول شراء","اكتب إيميلات أوامر الشراء","- الطلبات: "+A2+"\n- بيانات الموردين: [الصق]","الموردين يأكدوا النهارده","- إيميل لكل مورد\n- طلب تأكيد الميعاد","مسودات الإيميلات."]]]);
CH('procurement','From request to award','من الطلب للترسية',[
['Write the RFQ','اكتب طلب العروض',["Category buyer","Write the RFQ from the purchase request","- Request and specs: [paste]","Suppliers must quote on the same basis","- Specs, volumes, terms, evaluation criteria","RFQ."],["مشتري فئة","اكتب طلب العروض من طلب الشراء","- الطلب والمواصفات: [الصق]","الموردين يسعّروا على نفس الأساس","- المواصفات والكميات والشروط ومعايير التقييم","طلب العروض."]],
['Score the quotes','قيّم العروض',["Category buyer","Score the quotes received","- RFQ: "+O1+"\n- Quotes: suppliers.csv","The award must be defensible","- Weighted score with formula\n- Risks per supplier","Scoring table."],["مشتري فئة","قيّم العروض اللي وصلت","- طلب العروض: "+A1+"\n- العروض: suppliers.csv","الترسية لازم تكون مبررة","- درجة مرجّحة بالمعادلة\n- مخاطر كل مورد","جدول التقييم."]],
['Write the award memo','اكتب مذكرة الترسية',["Procurement manager","Draft the award memo for the committee","- Scoring: "+O2,"The committee approves","- Recommendation, runner-up, savings, risks","Award memo."],["مدير مشتريات","اكتب مذكرة الترسية للجنة","- التقييم: "+A2,"اللجنة هتعتمد","- التوصية والبديل والتوفير والمخاطر","مذكرة الترسية."]]]);
CH('cs','From tickets to fixes','من التذاكر للحلول',[
['Classify tickets','صنّف التذاكر',["Customer service lead","Classify this week’s tickets","- Attached: tickets.csv","Patterns hide in volume","- Category, urgency, language","Classification table."],["قائد خدمة عملاء","صنّف تذاكر الأسبوع ده","- مرفق: tickets.csv","الأنماط بتستخبى في الكمية","- الفئة والاستعجال واللغة","جدول التصنيف."]],
['Find root causes','دوّر على الأسباب الجذرية',["Customer experience analyst","Find root causes for the top categories","- Classification: "+O1,"Fixing causes reduces tickets","- Top 5 with evidence quotes\n- Owning team","Root-cause table."],["محلل تجربة عملاء","دوّر على الأسباب الجذرية لأهم الفئات","- التصنيف: "+A1,"حل الأسباب بيقلل التذاكر","- أهم 5 بمقتطفات\n- الفريق المسؤول","جدول الأسباب."]],
['Write the fix plan and replies','اكتب خطة الحل والردود',["Head of customer service","Write the fix plan and updated quick replies","- Root causes: "+O2,"Customers feel the difference next week","- One fix per cause with owner and date\n- Updated replies in Arabic and English","Plan + replies."],["رئيس خدمة العملاء","اكتب خطة الحل والردود السريعة المحدّثة","- الأسباب: "+A2,"العملاء يحسّوا بالفرق الأسبوع الجاي","- حل لكل سبب بمسؤول وميعاد\n- ردود محدّثة بالعربي والإنجليزي","الخطة + الردود."]]]);
CH('pm','From kickoff to status report','من البداية لتقرير الحالة',[
['Build the plan','ابني الخطة',["Project manager","Turn the charter into a task plan","- Charter: [paste]","The team needs owners and dates","- Tasks, owners, dates, dependencies","Task plan."],["مدير مشروع","حوّل وثيقة المشروع لخطة مهام","- الوثيقة: [الصق]","الفريق محتاج مسؤولين ومواعيد","- المهام والمسؤولين والمواعيد والاعتماديات","خطة المهام."]],
['Find the risks','حدد المخاطر',["Risk lead","Identify risks in the plan","- Plan: "+O1,"Risks must be owned early","- Probability, impact, mitigation, owner","Risk register."],["مسؤول مخاطر","حدد المخاطر في الخطة","- الخطة: "+A1,"المخاطر لازم يكون ليها مسؤول بدري","- الاحتمال والأثر والتخفيف والمسؤول","سجل المخاطر."]],
['Write the status report','اكتب تقرير الحالة',["Project manager","Write this week’s status from the plan and risks","- Plan progress: project.csv\n- Risks: "+O2,"The sponsor decides on escalations","- RAG with reasons\n- Decisions needed","Status report."],["مدير مشروع","اكتب حالة الأسبوع من الخطة والمخاطر","- تقدم الخطة: project.csv\n- المخاطر: "+A2,"الراعي بيقرر التصعيدات","- الحالة بالأسباب\n- القرارات المطلوبة","تقرير الحالة."]]]);
CH('ceo','From data to decisions','من البيانات للقرارات',[
['Summarise the week','لخّص الأسبوع',["Chief of staff","Summarise the week’s KPIs and events","- KPIs: kpis.csv\n- Events: [paste]","The CEO sees what matters","- Exceptions only","Half-page summary."],["مدير مكتب","لخّص مؤشرات وأحداث الأسبوع","- المؤشرات: kpis.csv\n- الأحداث: [الصق]","الرئيس يشوف المهم","- الاستثناءات بس","ملخص نص صفحة."]],
['Frame the decisions','صيغ القرارات',["Strategy adviser","Turn the exceptions into decision questions with options","- Summary: "+O1,"Meetings should decide, not discuss","- 2–3 options per decision with trade-offs","Decision papers."],["مستشار استراتيجي","حوّل الاستثناءات لأسئلة قرار باختيارات","- الملخص: "+A1,"الاجتماعات لازم تقرر مش تتناقش","- 2–3 اختيارات لكل قرار بالمفاضلات","أوراق القرار."]],
['Communicate decisions','بلّغ القرارات',["Internal communications lead","Write the leadership note announcing the decisions","- Decisions taken: "+O2,"Everyone knows what changes and why","- What, why, who, when\n- Under 200 words","Leadership note."],["مسؤول تواصل داخلي","اكتب رسالة القيادة اللي بتعلن القرارات","- القرارات: "+A2,"الكل يعرف إيه اللي اتغير وليه","- إيه وليه ومين وامتى\n- أقل من 200 كلمة","رسالة القيادة."]]]);
CH('legal','From contract to signature','من العقد للتوقيع',[
['Review the contract','راجع العقد',["In-house lawyer","Review the contract against our playbook","- Contract: [attach]\n- Playbook: [paste]","Risky clauses must be found first","- Deviations quoted with risk level","Deviation table."],["محامي داخلي","راجع العقد مقابل دليلنا","- العقد: [ارفع]\n- الدليل: [الصق]","البنود الخطرة لازم تتكشف الأول","- الاختلافات مقتبسة بمستوى الخطر","جدول الاختلافات."]],
['Draft the redlines','اكتب التعديلات',["In-house lawyer","Draft redlines and a negotiation note","- Deviations: "+O1,"We negotiate from clear positions","- Redline text per clause\n- Fallback positions","Redlines + note."],["محامي داخلي","اكتب التعديلات وملاحظة التفاوض","- الاختلافات: "+A1,"بنتفاوض من مواقف واضحة","- نص التعديل لكل بند\n- مواقف بديلة","التعديلات + الملاحظة."]],
['Brief the business','بلّغ الإدارة',["General counsel","Write the summary for the business owner before signature","- Final positions: "+O2,"The owner signs knowing the risks","- Key obligations, risks accepted, dates to track","One-page summary."],["المستشار القانوني","اكتب الملخص لصاحب القرار قبل التوقيع","- المواقف النهائية: "+A2,"صاحب القرار يوقّع وهو عارف المخاطر","- الالتزامات والمخاطر المقبولة والمواعيد","ملخص صفحة."]]]);
CH('trainer','From needs to a full session','من الاحتياج لجلسة كاملة',[
['Define outcomes','حدد النواتج',["Learning designer","Define learning outcomes from the needs","- Needs and audience: [paste]","Everything follows the outcomes","- 3–5 measurable outcomes","Outcome list."],["مصمم تعلّم","حدد نواتج التعلم من الاحتياج","- الاحتياج والجمهور: [الصق]","كل حاجة بتمشي ورا النواتج","- 3–5 نواتج قابلة للقياس","قائمة النواتج."]],
['Design the session','صمّم الجلسة',["Corporate trainer","Design the 90-minute session","- Outcomes: "+O1,"At least half the time is practice","- Timed agenda and exercises","Session plan."],["مدرّب شركات","صمّم جلسة 90 دقيقة","- النواتج: "+A1,"نص الوقت على الأقل تطبيق","- أجندة بالوقت وتمارين","خطة الجلسة."]],
['Write the assessment','اكتب التقييم',["Assessment designer","Write the end-of-session assessment","- Session plan: "+O2,"We prove the outcomes were met","- 8 scenario questions mapped to outcomes","Questions + answer key."],["مصمم تقييم","اكتب تقييم آخر الجلسة","- خطة الجلسة: "+A2,"نثبت إن النواتج اتحققت","- 8 أسئلة سيناريو مربوطة بالنواتج","الأسئلة + المفتاح."]]]);
CH('product','From feedback to roadmap','من الآراء لخارطة الطريق',[
['Cluster feedback','جمّع الآراء',["Product manager","Cluster customer feedback by theme","- Feedback: [paste]","Themes guide priorities","- Counts and quotes per theme","Theme table."],["مدير منتج","جمّع آراء العملاء حسب الموضوع","- الآراء: [الصق]","المواضيع بتوجّه الأولويات","- العدد والمقتطفات لكل موضوع","جدول المواضيع."]],
['Score opportunities','قيّم الفرص',["Product manager","Score the themes as opportunities","- Themes: "+O1+"\n- Effort estimates: [paste]","We build what moves goals","- RICE score per opportunity","Scored table."],["مدير منتج","قيّم المواضيع كفرص","- المواضيع: "+A1+"\n- تقديرات المجهود: [الصق]","نبني اللي بيحرّك الأهداف","- درجة RICE لكل فرصة","جدول التقييم."]],
['Write the roadmap update','اكتب تحديث الخارطة',["Head of product","Write the roadmap update for stakeholders","- Scores: "+O2,"Stakeholders understand trade-offs","- Now, next, later\n- What we will not do","Roadmap note."],["رئيس المنتج","اكتب تحديث خارطة الطريق للأطراف المعنية","- التقييمات: "+A2,"الكل يفهم المفاضلات","- دلوقتي، بعدين، بعد كده\n- اللي مش هنعمله","ملاحظة الخارطة."]]]);
CH('academic','From papers to a literature review section','من الأبحاث لجزء المراجعة الأدبية',[
['Summarise papers','لخّص الأبحاث',["Research assistant","Summarise each paper in a fixed format","- Papers: [attach]","Notes must be comparable","- Question, method, findings, limits, page-cited quotes","Notes table."],["مساعد بحثي","لخّص كل بحث بشكل ثابت","- الأبحاث: [ارفع]","الملاحظات لازم تتقارن","- السؤال والمنهج والنتايج والقيود والاقتباسات بالصفحة","جدول الملاحظات."]],
['Find themes and gaps','طلّع المحاور والفجوات',["Research methods adviser","Find themes, agreements and gaps across the notes","- Notes: "+O1,"The review must lead to my research question","- Themes with supporting papers\n- Gaps stated carefully","Theme map."],["مستشار مناهج","طلّع المحاور والاتفاقات والفجوات من الملاحظات","- الملاحظات: "+A1,"المراجعة لازم توصل لسؤال بحثي","- المحاور بالأبحاث الداعمة\n- الفجوات بحذر","خريطة المحاور."]],
['Draft the section','اكتب الجزء',["Academic writing coach","Draft the literature review section","- Theme map: "+O2+"\n- Style: APA","My supervisor reviews it next week","- Every claim cited\n- Ends with the gap my study fills","Draft section."],["مدرّب كتابة أكاديمية","اكتب مسودة جزء المراجعة الأدبية","- خريطة المحاور: "+A2+"\n- الأسلوب: APA","مشرفي هيراجعه الأسبوع الجاي","- كل ادعاء بمرجع\n- يخلص بالفجوة اللي دراستي بتسدها","مسودة الجزء."]]]);
CH('cfo','From forecast to funding decision','من التوقع لقرار التمويل',[
['Update the cash forecast','حدّث توقع الكاش',["Treasury analyst","Update the 13-week cash forecast","- Last forecast and actuals: [attach]","Funding decisions need a reliable view","- Weekly in, out, closing balance","Forecast table."],["محلل خزينة","حدّث توقع الكاش 13 أسبوع","- التوقع السابق والفعلي: [ارفع]","قرارات التمويل محتاجة صورة موثوقة","- الداخل والخارج والرصيد كل أسبوع","جدول التوقع."]],
['Test scenarios','اختبر السيناريوهات',["FP&A manager","Stress the forecast with scenarios","- Forecast: "+O1+"\n- Scenarios: sales −15%, FX +10%","We prepare before problems arrive","- Lowest balance per scenario\n- Covenant impact","Scenario table."],["مدير FP&A","اختبر التوقع بسيناريوهات ضغط","- التوقع: "+A1+"\n- السيناريوهات: المبيعات −15%، الدولار +10%","نستعد قبل المشاكل","- أقل رصيد في كل سيناريو\n- الأثر على التعهدات","جدول السيناريوهات."]],
['Recommend funding','اقترح التمويل',["CFO","Recommend the funding action","- Scenarios: "+O2+"\n- Available lines: [paste]","The committee approves today","- Options with cost and risk\n- Recommendation framed for approval","Decision note."],["المدير المالي","اقترح إجراء التمويل","- السيناريوهات: "+A2+"\n- الخطوط المتاحة: [الصق]","اللجنة هتعتمد النهارده","- اختيارات بالتكلفة والخطر\n- التوصية للاعتماد","ملاحظة القرار."]]]);
CH('ea','From inbox to a clear week','من صندوق الوارد لأسبوع واضح',[
['Triage the inbox','افرز الإيميل',["Executive assistant to a general manager","Triage the inbox","- Emails: [paste]\n- My manager’s priorities: [list]","My manager focuses on what matters","- Act, delegate, file\n- Draft replies for routine ones","Triage list."],["مساعد تنفيذي لمدير عام","افرز الإيميل","- الإيميلات: [الصق]\n- أولويات مديري: [قائمة]","مديري يركّز على المهم","- يتعمل، يتفوّض، يتحفظ\n- ردود مقترحة للروتيني","قائمة الفرز."]],
['Plan the week','خطط للأسبوع',["Executive assistant","Turn the action items into a weekly plan","- Actions: "+O1+"\n- Calendar: [paste]","Big rocks go first","- Time blocks for actions\n- Conflicts flagged","Weekly plan."],["مساعد تنفيذي","حوّل الإجراءات لخطة أسبوع","- الإجراءات: "+A1+"\n- الأجندة: [الصق]","الحاجات الكبيرة الأول","- أوقات للإجراءات\n- التعارضات متعلّمة","خطة الأسبوع."]],
['Prepare briefs','جهّز الملخصات',["Executive assistant","Write meeting briefs for the week","- Plan: "+O2,"No meeting starts unprepared","- Purpose, attendees, open items, ask","Briefs."],["مساعد تنفيذي","اكتب ملخصات اجتماعات الأسبوع","- الخطة: "+A2,"مفيش اجتماع يبدأ من غير تحضير","- الهدف والحضور والبنود المفتوحة والطلب","الملخصات."]]]);
CH('accounting','From bank to close','من البنك للإقفال',[
['Match the bank','طابق البنك',["Accountant","Match bank lines to the ledger","- Attached: bank_gl.csv","Clean cash first","- Matched and unmatched with reasons","Matching table."],["محاسب","طابق حركات البنك مع الدفاتر","- مرفق: bank_gl.csv","نضّف الكاش الأول","- المطابق وغير المطابق بالأسباب","جدول المطابقة."]],
['Propose journals','اقترح القيود',["Senior accountant","Propose journals for the reconciling items","- Unmatched items: "+O1,"The ledger must be complete before close","- Journal per item with accounts\n- Approval required","Journal proposals."],["محاسب أول","اقترح قيود لبنود التسوية","- البنود غير المطابقة: "+A1,"الدفاتر لازم تكمل قبل الإقفال","- قيد لكل بند بالحسابات\n- يحتاج اعتماد","مقترحات القيود."]],
['Update the close tracker','حدّث متابعة الإقفال',["Chief accountant","Update the close tracker","- Journals posted: "+O2+"\n- Checklist: [paste]","The close finishes on day 5","- Status per task\n- Blockers with owners","Close tracker."],["رئيس الحسابات","حدّث متابعة الإقفال","- القيود المسجلة: "+A2+"\n- القائمة: [الصق]","الإقفال يخلص اليوم الخامس","- الحالة لكل مهمة\n- المعوقات بمسؤوليها","متابعة الإقفال."]]]);
CH('fpa','From actuals to reforecast','من الفعلي لإعادة التوقع',[
['Analyse actuals','حلل الفعلي',["FP&A analyst","Analyse year-to-date actuals vs plan","- Attached: bva.csv, sales_monthly.csv","The reforecast starts from facts","- Variance by driver","Variance table."],["محلل FP&A","حلل الفعلي من أول السنة مقابل الخطة","- مرفق: bva.csv و sales_monthly.csv","إعادة التوقع بتبدأ من الحقايق","- الانحراف حسب المحرك","جدول الانحرافات."]],
['Build the reforecast','ابني إعادة التوقع',["FP&A manager","Build the full-year reforecast","- Variances: "+O1+"\n- Known events: [paste]","Leaders commit to a landing","- Method stated\n- Range best/base/worst","Reforecast table."],["مدير FP&A","ابني إعادة التوقع للسنة","- الانحرافات: "+A1+"\n- الأحداث المعروفة: [الصق]","القيادة تلتزم بنهاية متوقعة","- الطريقة متوضحة\n- مدى أفضل/أساسي/أسوأ","جدول إعادة التوقع."]],
['Write the CFO note','اكتب ملاحظة المدير المالي',["FP&A lead","Write the reforecast note for the CFO","- Reforecast: "+O2,"The CFO presents to the board","- Bridge from budget to reforecast\n- Actions to close the gap","CFO note."],["مسؤول FP&A","اكتب ملاحظة إعادة التوقع للمدير المالي","- إعادة التوقع: "+A2,"المدير المالي هيعرض على المجلس","- الجسر من الموازنة لإعادة التوقع\n- إجراءات لسد الفجوة","ملاحظة المدير المالي."]]]);
CH('treasury','From positions to hedges','من المراكز للتحوط',[
['Map exposures','ارسم التعرض',["Treasury analyst","Map FX exposures by currency and month","- Payables and receivables: ap_aging.csv, ar_aging.csv","Hedging starts with the right exposure","- Net exposure per currency and month","Exposure table."],["محلل خزينة","ارسم التعرض للعملة حسب العملة والشهر","- الدائنين والمدينين: ap_aging.csv و ar_aging.csv","التحوط بيبدأ بالتعرض الصح","- صافي التعرض لكل عملة وشهر","جدول التعرض."]],
['Check policy','راجع السياسة',["Treasury risk analyst","Compare hedge ratios with policy","- Exposures: "+O1+"\n- Hedge book and policy: [paste]","Breaches must be fixed","- Ratio per currency vs policy\n- Breaches flagged","Policy check."],["محلل مخاطر خزينة","قارن نسب التحوط بالسياسة","- التعرض: "+A1+"\n- عقود التحوط والسياسة: [الصق]","المخالفات لازم تتصلّح","- النسبة لكل عملة مقابل السياسة\n- المخالفات متعلّمة","مراجعة السياسة."]],
['Propose trades','اقترح الصفقات',["Treasury manager","Propose hedge trades for committee approval","- Policy check: "+O2+"\n- Bank quotes: [paste]","The committee approves today","- Trade per currency with cost\n- Remaining exposure","Trade proposal."],["مدير خزينة","اقترح صفقات تحوط لاعتماد اللجنة","- مراجعة السياسة: "+A2+"\n- عروض البنوك: [الصق]","اللجنة هتعتمد النهارده","- صفقة لكل عملة بتكلفتها\n- التعرض المتبقي","مقترح الصفقات."]]]);
CH('compliance','From regulation to control','من اللائحة للضابط',[
['Summarise the rule','لخّص القاعدة',["Compliance analyst","Summarise the new regulation","- Official text: [paste]","We must know what changed","- Requirements quoted with article numbers\n- Effective date from the text","Requirement list."],["محلل امتثال","لخّص اللائحة الجديدة","- النص الرسمي: [الصق]","لازم نعرف إيه اللي اتغير","- المتطلبات مقتبسة بأرقام المواد\n- تاريخ السريان من النص","قائمة المتطلبات."]],
['Map gaps','طابق الفجوات',["Compliance officer","Map each requirement to our current controls","- Requirements: "+O1+"\n- Policies and controls: [attach]","Gaps need owners","- Covered / partly / gap per requirement","Gap table."],["مسؤول امتثال","طابق كل متطلب مع الضوابط الحالية","- المتطلبات: "+A1+"\n- السياسات والضوابط: [ارفع]","الفجوات محتاجة مسؤولين","- مغطى / جزئي / فجوة لكل متطلب","جدول الفجوات."]],
['Design controls','صمّم الضوابط',["Head of compliance","Design controls and an action plan for the gaps","- Gaps: "+O2,"The committee approves the plan","- Control, owner, frequency, evidence, deadline","Action plan."],["رئيس الامتثال","صمّم ضوابط وخطة إجراءات للفجوات","- الفجوات: "+A2,"اللجنة هتعتمد الخطة","- الضابط والمسؤول والتكرار والدليل والميعاد","خطة الإجراءات."]]]);
