// ===== ANTHROPIC COMMUNITY: searchable references, community hub, get-involved checklist, MENA spotlight, share your work, lesson 8.2 =====
const COMM_CHECKED='2026-10-02';COMMUNITY.forEach(g=>g.chk=COMM_CHECKED);
const COMMKEYS=['join','events','programs','follow','news'];COMMUNITY.forEach((g,k)=>g.k=COMMKEYS[k]);
const SUBMIT_BUILD='https://support.claude.com/en/articles/15485501-submit-your-build-how-it-works-and-what-you-re-agreeing-to';
const UX9={comm:T('Anthropic community','مجتمع Anthropic'),hub:T('Community hub','مركز المجتمع')};
let CMQ='',CMG='all';
if(!ST.comm)ST.comm=[];if(!ST.evs)ST.evs=[];
let EVF=Object.assign({name:'',city:'Cairo',date:'',link:'',notes:''},ST.evf||{});
const fmtDate=d=>{try{return new Date(d+'T00:00:00').toLocaleDateString(LANG==='ar'?'ar-EG':'en-GB',{day:'numeric',month:'long',year:'numeric'})}catch(e){return d}};

function commCards(withFilter){const ar=LANG==='ar';const q=CMQ.toLowerCase();let total=0;
const groups=COMMUNITY.filter(g=>CMG==='all'||g.k===CMG).map(g=>({g,items:g.items.filter(i=>!q||(i[0]+' '+i[1]+' '+i[2].en+' '+i[2].ar+' '+g.g.en+' '+g.g.ar).toLowerCase().includes(q))})).filter(x=>x.items.length);
groups.forEach(x=>total+=x.items.length);
let h='';if(withFilter)h+=`<div class="cfil" style="grid-template-columns:1fr"><input class="search" id="cmq" value="${esc(CMQ)}" placeholder="${ar?'ابحث في المجتمع… (ديسكورد، فعاليات، يوتيوب…)':'Search the community… (Discord, events, YouTube…)'}"></div><div class="chips">${[['all',T('All','الكل'),'✦']].concat(COMMUNITY.map(g=>[g.k,g.g,g.i])).map(c=>`<button class="chip ${CMG===c[0]?'on':''}" data-cmg="${c[0]}">${c[2]} ${L(c[1])}</button>`).join('')}</div><p class="note">${total} ${ar?'رابط':'links'}</p>`;
if(!groups.length)return h+`<div class="empty">${ar?'مفيش نتايج — جرّب كلمة تانية.':'No matches — try another word.'}</div>`;
return h+`<div class="grid">`+groups.map(({g,items})=>`<div class="card" style="padding:0"><h3 style="padding:12px 12px 4px">${g.i} ${L(g.g)}</h3><div class="reflist commlist">${items.map(i=>`<a href="${i[1]}" target="_blank" rel="noopener"><b>${i[0]} ↗</b><span>${L(i[2])}</span></a>`).join('')}</div><div class="commchk">✓ ${ar?'اتراجعت':'Checked'} ${fmtDate(g.chk)}</div></div>`).join('')+`</div>`}

// References page: community (searchable) + official sources; visual library removed
function vGallery(){crumb(L(UI.gallery));if(location.hash.slice(1).includes('/'))history.replaceState(null,'','#gallery');const ar=LANG==='ar';
let h=`<h1>▣ ${L(UI.gallery)}</h1><p class="lede">${ar?'مجتمع Anthropic و Claude الرسمي — اتكلم واحضر فعاليات وتابع الجديد — وتحته المصادر الرسمية للتعلم والتوثيق.':'The official Anthropic & Claude community — talk, meet up and stay current — followed by official learning and documentation sources.'}</p>`;
h+=`<h2>${L(UX9.comm)}</h2><div class="commbanner"><div><b>🤝 ${L(UX9.hub)}</b><span>${ar?'قائمة "شارك" بـ XP، فعاليات مصر والشرق الأوسط، وإزاي تشارك شغلك.':'Get-involved checklist with XP, Egypt & MENA events, and how to share your work.'}</span></div><button class="btn-gold" data-go="community">${ar?'افتح المركز':'Open the hub'} →</button></div>`+commCards(true);
h+=`<h2>${ar?'المصادر الرسمية':'Official sources'}</h2><div class="grid">`+REFS.map(g=>`<div class="card" style="padding:0"><h3 style="padding:12px 12px 4px">${L(g.g)}</h3><div class="reflist">${g.items.map(i=>`<a href="${i[1]}" target="_blank" rel="noopener">${i[0]} ↗</a>`).join('')}</div></div>`).join('')+`</div><p class="note" style="margin-top:14px">${ar?'المصادر الرسمية متراجعة آخر سبتمبر 2026؛ روابط المجتمع متراجعة '+fmtDate(COMM_CHECKED)+'.':'Official sources checked end of September 2026; community links checked '+fmtDate(COMM_CHECKED)+'.'}</p>`;
return h}

// ---- get involved ----
const INVOLVE=[
['discord','💬',T('Join the Claude Discord','انضم لديسكورد Claude'),'https://discord.com/invite/6PPFFzqPDZ'],
['follow','📣',T('Follow Claude on one channel (YouTube, X or LinkedIn)','تابع Claude على قناة واحدة (يوتيوب أو X أو لينكدإن)'),'https://www.youtube.com/@anthropic-ai'],
['meetup','📅',T('Find a community event and RSVP','دوّر على فعالية للمجتمع واحجز مكانك'),'https://luma.com/claudecommunity'],
['read','📰',T('Read one post on the Anthropic engineering blog','اقرا مقال واحد في مدونة Anthropic الهندسية'),'https://www.anthropic.com/engineering'],
['share','🚀',T('Share something you built with Claude','شارك حاجة بنيتها بـ Claude'),SUBMIT_BUILD],
['ambassador','🎓',T('Explore the Community Ambassadors program','اتعرّف على برنامج سفراء المجتمع'),'https://claude.com/community/ambassadors']];
const commDone=()=>INVOLVE.filter(s=>ST.comm.includes(s[0])).length;

function vCommunity(){crumb(L(UX9.hub));const ar=LANG==='ar';const done=commDone();const p=Math.round(100*done/INVOLVE.length);
let h=`<section class="cdash labhero"><div class="cd-l"><div class="sig">${L(UX9.comm)}</div><h1>🤝 ${L(UX9.hub)}</h1><p>${ar?'اتعلم مع الناس: انضم للنقاش، احضر فعاليات، وشارك اللي بتبنيه مع مجتمع Claude.':'Learn with others: join the conversation, attend events and share what you build with the Claude community.'}</p></div><div class="cd-r"><div class="hring">${ring(p)}<span>${done}/${INVOLVE.length} ${ar?'خطوات':'steps'}</span></div></div></section>`;
// checklist
h+=`<h2>✅ ${ar?'شارك في المجتمع':'Get involved'}</h2><p class="note">${ar?'كل خطوة بـ 10 XP. افتح الرابط وبعدين علّم إنك خلصتها.':'Each step earns 10 XP. Open the link, then tick it off.'}</p><div class="invlist">`+INVOLVE.map(s=>{const on=ST.comm.includes(s[0]);return `<div class="invrow ${on?'on':''}"><label><input type="checkbox" data-inv="${s[0]}" ${on?'checked':''}> <span>${s[1]} ${L(s[2])}</span></label><a class="tbtn" href="${s[3]}" target="_blank" rel="noopener">${ar?'افتح':'Open'} ↗</a></div>`}).join('')+`</div>`;
if(done===INVOLVE.length)h+=`<div class="tips2 ok">🏅 ${ar?'برافو! إنت دلوقتي عضو نشيط في مجتمع Claude.':'Well done — you are now an active member of the Claude community.'}</div>`;
// MENA spotlight
h+=`<h2>🇪🇬 ${ar?'مصر والشرق الأوسط':'Egypt & MENA spotlight'}</h2><div class="twocol"><div class="abpane"><h3>${ar?'لاقي فعاليات قريبة منك':'Find events near you'}</h3><p>${ar?'بنعرض بس الفعاليات المتأكدين منها. دوّر على مدينتك في التقويم الرسمي للمجتمع، أو نظّم واحدة كسفير.':'We only list events we have verified. Search for your city in the official community calendar, or host one as an ambassador.'}</p><div class="row-btns"><a class="btn-gold" href="https://luma.com/claudecommunity" target="_blank" rel="noopener">📅 ${ar?'فعاليات المجتمع (Luma)':'Community events (Luma)'} ↗</a><a class="tbtn" href="https://www.anthropic.com/events" target="_blank" rel="noopener">${ar?'فعاليات Anthropic':'Anthropic events'} ↗</a><a class="tbtn" href="https://claude.com/community/ambassadors" target="_blank" rel="noopener">🎓 ${ar?'نظّم فعالية':'Host an event'} ↗</a></div></div>
<div class="abpane"><h3>${ar?'اقترح فعالية':'Suggest an event'}</h3>
<label class="pbf"><b>${ar?'اسم الفعالية':'Event name'}</b><input class="search" data-evf="name" value="${esc(EVF.name)}" placeholder="${ar?'لقاء Claude للمحاسبين':'Claude meetup for accountants'}"></label>
<div class="pkgrid3"><label class="pbf"><b>${ar?'المدينة':'City'}</b><input class="search" data-evf="city" value="${esc(EVF.city)}"></label><label class="pbf"><b>${ar?'التاريخ':'Date'}</b><input class="search" type="date" data-evf="date" value="${esc(EVF.date)}"></label><label class="pbf"><b>${ar?'رابط':'Link'}</b><input class="search" data-evf="link" value="${esc(EVF.link)}" placeholder="https://"></label></div>
<label class="pbf"><b>${ar?'تفاصيل':'Details'}</b><textarea class="search" rows="2" data-evf="notes" dir="auto">${esc(EVF.notes)}</textarea></label>
<button class="btn-gold" data-ev="add">＋ ${ar?'ضيف للقائمة':'Add to my list'}</button><p class="note" id="evnote">${ar?'الاقتراحات بتتحفظ في المتصفح ده بس — انسخها أو نزّلها وابعتها للمدرّبة أو لمجتمعك.':'Suggestions are saved in this browser only — copy or download them and send them to your instructor or community.'}</p></div></div>`;
if(ST.evs.length){h+=`<div class="tablewrap"><table><tr><th>${ar?'الفعالية':'Event'}</th><th>${ar?'المدينة':'City'}</th><th>${ar?'التاريخ':'Date'}</th><th></th></tr>${ST.evs.map((v,k)=>`<tr><td dir="auto"><b>${esc(v.name)}</b>${v.notes?`<div class="k" style="font-size:12.5px">${esc(v.notes)}</div>`:''}${v.link?`<div><a href="${esc(v.link)}" target="_blank" rel="noopener">${esc(v.link)}</a></div>`:''}</td><td>${esc(v.city)}</td><td>${v.date?fmtDate(v.date):''}</td><td><button class="tbtn" data-ev="del:${k}">✕</button></td></tr>`).join('')}</table></div><div class="row-btns"><button class="tbtn" data-ev="copy">⧉ ${ar?'انسخ كرسالة':'Copy as message'}</button><button class="tbtn" data-ev="md">⤓ .md</button><button class="tbtn" data-ev="json">⤓ .json</button></div>`}
// share your work
h+=`<h2>🚀 ${ar?'شارك شغلك مع المجتمع':'Share your work with the community'}</h2><div class="twocol"><div class="abpane"><h3>${ar?'قبل ما تنشر':'Before you post'}</h3><ol class="steps">${(ar?['شيل أي بيانات عملاء أو أرقام سرية.','اشرح المشكلة والنتيجة في سطرين.','حط سكرين شوت أو لينك للـ artifact.','قول استخدمت أنهي ميزة في Claude.','اقرا شروط "Submit your build" قبل ما ترفع.']:['Remove client data and confidential numbers.','Explain the problem and the result in two lines.','Add a screenshot or the artifact link.','Say which Claude features you used.','Read the “Submit your build” terms before you submit.']).map(s=>`<li>${s}</li>`).join('')}</ol><div class="row-btns"><a class="btn-gold" href="${SUBMIT_BUILD}" target="_blank" rel="noopener">${ar?'Submit your build — إزاي بيشتغل':'Submit your build — how it works'} ↗</a><a class="tbtn" href="https://discord.com/invite/6PPFFzqPDZ" target="_blank" rel="noopener">💬 Discord ↗</a></div></div><div>`+promptBox({t:T('Master prompt — community showcase post','البرومبت الماستر — بوست عرض للمجتمع'),p:T(
MPen('Community manager and technical writer','Turn my Claude build into a short showcase post for the Claude community','- What I built: [name + one line]\n- Problem it solves: [..]\n- Claude features used: [e.g. Projects, Skills, Cowork, Artifacts]\n- Result: [time saved, quality, numbers]\n- Link or screenshot: [..]','Clear, honest showcases help others learn and get feedback','- Under 150 words; no client or confidential data\n- One concrete result with a number\n- Ends with a question that invites feedback','Post text + a one-line title + 3 hashtags.'),
MPar('مدير مجتمع وكاتب تقني','حوّل اللي بنيته بـ Claude لبوست قصير يعرضه لمجتمع Claude','- اللي بنيته: [الاسم + سطر]\n- المشكلة اللي بيحلها: [..]\n- مميزات Claude المستخدمة: [مثلاً Projects، Skills، Cowork، Artifacts]\n- النتيجة: [وقت اتوفّر، جودة، أرقام]\n- لينك أو سكرين شوت: [..]','العرض الواضح والصادق بيساعد غيرك يتعلم ويجيبلك آراء','- أقل من 150 كلمة؛ من غير بيانات عملاء أو سرية\n- نتيجة واحدة ملموسة برقم\n- يخلص بسؤال يفتح النقاش','نص البوست + عنوان في سطر + 3 هاشتاج.'))})+`</div></div>`;
h+=`<h2>🔗 ${ar?'كل روابط المجتمع':'All community links'}</h2>`+commCards(false)+`<p class="row-btns" style="margin-top:12px"><button class="tbtn" data-go="day/8/8.2">📘 ${ar?'درس 8.2 — المجتمع':'Lesson 8.2 — community'}</button><button class="tbtn" data-go="quiz/8">🧠 ${L(UX.quiz)}</button><button class="tbtn" data-go="showcase">🖼 ${L(UX10.wall)}</button><button class="tbtn" data-go="gallery">▣ ${L(UI.gallery)}</button></p>`;
return h}
function evText(){return ST.evs.map(v=>`• ${v.name} — ${v.city}${v.date?' — '+v.date:''}${v.link?'\n  '+v.link:''}${v.notes?'\n  '+v.notes:''}`).join('\n')}

document.addEventListener('click',e=>{const g=s=>e.target.closest(s);let x;
if(x=g('[data-cmg]')){CMG=x.dataset.cmg;render();return}
if(x=g('[data-ev]')){const a=x.dataset.ev;const ar=LANG==='ar';
if(a==='add'){if(!EVF.name.trim()){const n=document.getElementById('evnote');if(n)n.textContent=ar?'اكتب اسم الفعالية الأول.':'Add the event name first.';return}ST.evs.push(Object.assign({},EVF));EVF=Object.assign(EVF,{name:'',date:'',link:'',notes:''});ST.evf=EVF;saveST();addXP(5);render();return}
if(a.startsWith('del:')){ST.evs.splice(+a.slice(4),1);saveST();render();return}
if(a==='copy'){const t=(ar?'فعاليات Claude مقترحة:\n':'Suggested Claude events:\n')+evText();(navigator.clipboard?navigator.clipboard.writeText(t):Promise.reject()).then(()=>{x.textContent='✓'},()=>{x.textContent=ar?'مقدرتش أنسخ':'Copy failed'});return}
if(a==='md'){saveFile('Suggested-Claude-events.md','# Suggested Claude events\n\n'+ST.evs.map(v=>`## ${v.name}\n\n- City: ${v.city}\n- Date: ${v.date||'TBD'}\n- Link: ${v.link||'-'}\n\n${v.notes||''}\n`).join('\n'));return}
if(a==='json'){saveFile('Suggested-Claude-events.json',JSON.stringify({type:'claude-mastery-event-suggestions',created:new Date().toISOString(),events:ST.evs},null,1));return}}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset&&t.dataset.inv){const k=t.dataset.inv;if(!ST.commXP)ST.commXP=[];if(t.checked&&!ST.comm.includes(k)){ST.comm.push(k);if(!ST.commXP.includes(k)){ST.commXP.push(k);addXP(10)}}else if(!t.checked)ST.comm=ST.comm.filter(y=>y!==k);saveST();render()}});
document.addEventListener('input',e=>{const t=e.target;
if(t.id==='cmq'){CMQ=t.value;const pos=t.selectionStart;render();const el=document.getElementById('cmq');if(el){el.focus();el.setSelectionRange(pos,pos)}}
if(t.dataset&&t.dataset.evf){EVF[t.dataset.evf]=t.value;ST.evf=EVF;saveST()}});

// ---- lesson 8.2 + quiz question ----
DAYS[7].units.push({id:"8.2",tag:"practical",dur:"20",t:T("Join the Anthropic community","انضم لمجتمع Anthropic"),
body:T(`<p>Learning Claude does not stop at the course. The official Claude community runs a Discord, local meetups and build days, an Ambassadors program, and channels where Anthropic shares news, research and engineering write-ups. Use them to get help, see how others work, and show what you have built.</p><p><button class="dlbtn" data-go="community">🤝 Open the community hub</button></p><ol><li>Join the Discord and introduce yourself and your field.</li><li>Follow one channel so new features reach you.</li><li>Find an event on the community calendar — or host one as an ambassador.</li><li>Share one build, without confidential data.</li></ol>`,`<p>تعلّم Claude مش بيخلص بالكورس. مجتمع Claude الرسمي عنده ديسكورد، ولقاءات محلية وأيام بناء، وبرنامج سفراء، وقنوات بتنشر فيها Anthropic الأخبار والأبحاث والمقالات الهندسية. استخدمها علشان تاخد مساعدة، وتشوف غيرك بيشتغل إزاي، وتعرض اللي بنيته.</p><p><button class="dlbtn" data-go="community">🤝 افتح مركز المجتمع</button></p><ol><li>ادخل الديسكورد وعرّف بنفسك وبمجالك.</li><li>تابع قناة واحدة علشان المميزات الجديدة توصلك.</li><li>دوّر على فعالية في تقويم المجتمع — أو نظّم واحدة كسفير.</li><li>شارك حاجة بنيتها، من غير بيانات سرية.</li></ol>`),
steps:T(["Open the community hub","Join the Discord","Follow one channel","RSVP to an event","Share one build"],["افتح مركز المجتمع","ادخل الديسكورد","تابع قناة واحدة","احجز في فعالية","شارك حاجة بنيتها"]),
tips:T(["Ask specific questions with what you tried — you will get better answers.","Never post client data or confidential numbers."],["اسأل أسئلة محددة واذكر جرّبت إيه — هتاخد إجابات أحسن.","متنشرش بيانات عملاء أو أرقام سرية أبداً."]),
cases:[{t:T("A finance team learns from peers","فريق مالية بيتعلم من زمايله"),d:T("An FP&A analyst shares a month-end variance prompt in the Discord, gets two suggestions on stop conditions, and the team adopts the improved version as a Skill.","محلل FP&A شارك برومبت تحليل انحرافات الإقفال في الديسكورد، خد اقتراحين على شروط التوقف، والفريق اعتمد النسخة المحسّنة كـ Skill.")}],
prompts:[{t:T("Master prompt — community showcase post","البرومبت الماستر — بوست عرض للمجتمع"),p:T(MPen('Community manager and technical writer','Turn my Claude build into a short showcase post for the Claude community','- What I built: [name + one line]\n- Problem it solves: [..]\n- Claude features used: [..]\n- Result: [time saved, quality, numbers]','Clear, honest showcases help others learn and get feedback','- Under 150 words; no client or confidential data\n- One concrete result with a number','Post text + a one-line title + 3 hashtags.'),MPar('مدير مجتمع وكاتب تقني','حوّل اللي بنيته بـ Claude لبوست قصير يعرضه لمجتمع Claude','- اللي بنيته: [..]\n- المشكلة اللي بيحلها: [..]\n- مميزات Claude المستخدمة: [..]\n- النتيجة: [وقت اتوفّر، جودة، أرقام]','العرض الواضح والصادق بيساعد غيرك يتعلم ويجيبلك آراء','- أقل من 150 كلمة؛ من غير بيانات سرية\n- نتيجة واحدة ملموسة برقم','نص البوست + عنوان في سطر + 3 هاشتاج.')),master:true}],doc:""});
FEAT["8.2"]="Community, Discord, events, Ambassadors";CEO["8.2"]=T("Teams that learn in the open adopt good practices faster — and spot risks earlier.","الفرق اللي بتتعلم في العلن بتتبنى الممارسات الكويسة أسرع — وبتشوف المخاطر بدري.");
QUIZ[8].push(Q("What should you remove before sharing a Claude build with the community?","لازم تشيل إيه قبل ما تشارك حاجة بنيتها بـ Claude مع المجتمع؟",[["The prompt","البرومبت"],["Client data and confidential numbers","بيانات العملاء والأرقام السرية"],["The screenshot","السكرين شوت"],["The result","النتيجة"]],1,"Share the method and the result — never client or confidential data.","شارك الطريقة والنتيجة — وعمرك ما تشارك بيانات عملاء أو أرقام سرية."));
