// ---------- Module 3 extension: Claude Design deep-dive (3.4-3.7), extra cases for 3.1-3.3, quiz ----------
const D3x=DAYS.find(d=>d.n===3);
D3x.units.push(
{id:"3.4",tag:"core",dur:"40",t:T("Claude Design setup & your brand design system","إعداد Claude Design والـ Design System بتاع البراند"),
body:T(`<p>Unit 3.3 showed what Claude Design is. This unit sets it up properly, so every asset your team makes is on-brand from the first draft. As of Sept 2026, Claude Design is an Anthropic Labs product released on 17 Apr 2026 and still in beta (research preview) on Pro, Max, Team and Enterprise plans. It is on by default on Pro, Max and Team. On Enterprise it stays off until an owner turns it on, and admins manage publishing, defaults and deletion permissions.</p>
<p><b>Ways in:</b> the standalone workspace at claude.ai/design; a normal conversation (ask Claude for a design, or choose Output &gt; Design in the message box); the Design template in the Artifacts tab; Claude Code; and the mobile apps.</p>
<p><b>Build the design system first.</b> Projects inherit your organization's design system, so you build it once and everyone benefits. You can build or import it from brand files, slide decks, design files, GitHub repos or local codebases (in Claude Code via /design-sync). After that, colors, typography and components are applied automatically to new designs.</p>
<ol><li>Collect the brand pack: logo files, the official colour list, the Arabic and Latin fonts, and two or three approved decks or flyers.</li><li>Create or import the design system from those files.</li><li>Open a test project and ask for a simple bilingual one-pager.</li><li>Compare the result with the brand guide: colours, fonts, logo spacing, Arabic shaping and numerals.</li><li>When something is wrong, fix the design system, not each design.</li></ol>
<p><b>Human check:</b> the brand owner (marketing or the CEO office) approves the design system before the team uses it, and IT or the plan owner confirms who may publish and delete. Usage counts toward the same Claude usage limits as chat, and complex projects use more, so start with small, clear requests and keep the heavy work for real deliverables.</p>`,
`<p>في وحدة 3.3 عرفنا Claude Design هو إيه. الوحدة دي بتجهّزه صح، علشان أي تصميم الفريق يعمله يطلع على البراند من أول مسودة. لحد سبتمبر 2026، Claude Design منتج من Anthropic Labs اتطلق يوم 17 أبريل 2026 ولسه بيتا (research preview) على خطط Pro و Max و Team و Enterprise. بيبقى شغال تلقائي على Pro و Max و Team. أما في Enterprise فبيفضل مقفول لحد ما الـ owner يشغّله، والأدمنز بيتحكموا في صلاحيات النشر والإعدادات الافتراضية والحذف.</p>
<p><b>تدخل منين:</b> المساحة المستقلة على claude.ai/design؛ أو من محادثة عادية (اطلب من Claude تصميم، أو اختار Output &gt; Design من صندوق الرسالة)؛ أو قالب Design في تبويب Artifacts؛ أو Claude Code؛ أو تطبيقات الموبايل.</p>
<p><b>ابني الـ Design System الأول.</b> المشاريع بتورث الـ Design System بتاع الشركة، يعني تبنيه مرة والكل يستفيد. تقدر تبنيه أو تستورده من ملفات البراند، أو عروض شرائح، أو ملفات تصميم، أو GitHub repos، أو أكواد على جهازك (في Claude Code بأمر /design-sync). بعد كده الألوان والخطوط والـ components بتتطبق تلقائي على التصميمات الجديدة.</p>
<ol><li>جمّع ملف البراند: ملفات اللوجو، قائمة الألوان الرسمية، الخطوط العربي واللاتيني، واتنين أو تلاتة عروض أو فلايرز معتمدة.</li><li>اعمل أو استورد الـ Design System من الملفات دي.</li><li>افتح مشروع تجربة واطلب صفحة واحدة بسيطة بلغتين.</li><li>قارن النتيجة بدليل البراند: الألوان، الخطوط، المسافة حوالين اللوجو، شكل الحروف العربي والأرقام.</li><li>لو في حاجة غلط، صلّح الـ Design System نفسه، مش كل تصميم لوحده.</li></ol>
<p><b>المراجعة البشرية:</b> صاحب البراند (التسويق أو مكتب الـ CEO) يعتمد الـ Design System قبل ما الفريق يستخدمه، والـ IT أو صاحب الخطة يأكد مين مسموحله ينشر ويمسح. الاستخدام بيتحسب من نفس حدود استخدام Claude، والمشاريع المعقدة بتستهلك أكتر، فابدأ بطلبات صغيرة وواضحة وخلّي الشغل التقيل للمخرجات الحقيقية.</p>`),
steps:T(["Confirm access: plan, and on Enterprise ask the owner to turn it on","Collect logo, colours, fonts and 2-3 approved files","Build or import the design system (or /design-sync in Claude Code)","Test with one bilingual one-pager","Get brand-owner approval, then share with the team"],["اتأكد من الصلاحية: الخطة، وفي Enterprise اطلب من الـ owner يشغّله","جمّع اللوجو والألوان والخطوط و2-3 ملفات معتمدة","ابني أو استورد الـ Design System (أو /design-sync في Claude Code)","جرّب بصفحة واحدة بلغتين","خد موافقة صاحب البراند وبعدين شاركه مع الفريق"]),
tips:T(["Feed approved, final brand files only; old logos and drafts teach the wrong style.","Write down which fonts support Arabic before you start; it saves rework later.","Keep one person as the design-system owner so changes are not made by everyone."],["ادّيله ملفات البراند النهائية المعتمدة بس؛ اللوجوهات القديمة والمسودات بتعلّمه ستايل غلط.","اكتب الخطوط اللي بتدعم العربي قبل ما تبدأ؛ ده بيوفر إعادة شغل بعدين.","خلّي شخص واحد مسؤول عن الـ Design System علشان التعديلات متبقاش من كل الناس."]),
cases:[{t:T("A finance team gets its own brand kit","فريق مالية بيعمل البراند كيت بتاعه"),d:T("The FP&A lead imported the group's approved board deck and brand guide as the design system. The first test one-pager came out with the right navy and gold, but the Arabic font was wrong; she fixed it once in the design system and every later design used the right font.","مسؤولة الـ FP&A استوردت عرض المجلس المعتمد ودليل البراند كـ Design System. أول صفحة تجربة طلعت بالكحلي والدهبي الصح، بس الخط العربي كان غلط؛ صلّحته مرة واحدة في الـ Design System وكل التصميمات بعد كده طلعت بالخط الصح.")},{t:T("Enterprise roll-out with clear permissions","تشغيل في Enterprise بصلاحيات واضحة"),d:T("On an Enterprise plan the owner turned Claude Design on for marketing and finance only, and admins limited publishing to two people. The team wrote a one-paragraph rule: drafts stay private, external designs need the brand owner's sign-off.","على خطة Enterprise الـ owner شغّل Claude Design للتسويق والمالية بس، والأدمنز خلّوا النشر لشخصين بس. الفريق كتب قاعدة في فقرة: المسودات تفضل خاصة، والتصميمات اللي طالعة برا محتاجة توقيع صاحب البراند.")}],
prompts:[
PR("Master prompt — brand design-system brief","البرومبت الماستر — بريف الـ Design System للبراند",["Brand and design lead preparing a company design system in Claude Design for a bilingual Arabic/English team","Review the attached brand files and propose the design-system settings: colours, typography, components and usage rules","- Brand files attached: [logo, brand guide, 2-3 approved decks or flyers]\n- Official colours: [names and hex codes from the brand guide]\n- Fonts: [Latin font] and [Arabic font]; Arabic must be right-to-left\n- Main assets we will make: [one-pagers, decks, social posts, ..]","A design system built once saves every team from re-styling each asset, but only if it matches the approved brand exactly","- Use only colours and fonts that appear in the files; list anything missing as [MISSING]\n- Max 1 page of rules, max 8 components\n- Do not apply anything yet; the brand owner approves first","A table with columns: Element, Value from brand files, Source file, Rule for use, Open question. Then a 5-line note for the brand owner in [English/Arabic]."],["مسؤول براند وتصميم بيجهّز Design System للشركة في Claude Design لفريق بيشتغل عربي وإنجليزي","راجع ملفات البراند المرفقة واقترح إعدادات الـ Design System: الألوان والخطوط والـ components وقواعد الاستخدام","- ملفات البراند المرفقة: [اللوجو، دليل البراند، 2-3 عروض أو فلايرز معتمدة]\n- الألوان الرسمية: [الأسامي وأكواد الـ hex من دليل البراند]\n- الخطوط: [الخط اللاتيني] و [الخط العربي]؛ والعربي لازم من اليمين للشمال\n- أهم التصميمات اللي هنعملها: [صفحات واحدة، عروض، بوستات سوشيال، ..]","الـ Design System اللي بيتبني مرة بيوفّر على كل فريق إعادة التنسيق، بس بشرط يطابق البراند المعتمد بالظبط","- استخدم بس الألوان والخطوط اللي موجودة في الملفات؛ وأي حاجة ناقصة اكتبها [MISSING]\n- صفحة واحدة بالكتير للقواعد، و8 components بالكتير\n- متطبقش حاجة دلوقتي؛ صاحب البراند يعتمد الأول","جدول بأعمدة: العنصر، القيمة من ملفات البراند، الملف المصدر، قاعدة الاستخدام، سؤال مفتوح. وبعده ملاحظة 5 سطور لصاحب البراند بالـ [عربي/إنجليزي]."]),
PR("Master prompt — design-system acceptance test","البرومبت الماستر — اختبار قبول الـ Design System",["Quality reviewer testing a new Claude Design design system before the whole team starts using it","Create 3 small test designs with the design system and then list every place they differ from the brand guide","- Design system: [name], built from [files]\n- Test designs: a bilingual one-pager, a 3-slide deck, one square social post\n- Text to use: [paste exact approved text; no placeholder numbers]","Testing on three formats finds font, colour and RTL problems before they reach clients","- Exactly 3 test designs, each with real approved text only\n- Every difference linked to a brand-guide rule\n- No numbers or claims beyond the pasted text","A checklist table with columns: Test design, Check (colour, font, logo, RTL, numerals, contrast), Pass or Fail, Fix in design system. A human reviewer signs off at the end."],["مراجع جودة بيختبر Design System جديد في Claude Design قبل ما الفريق كله يبدأ يستخدمه","اعمل 3 تصميمات تجربة صغيرة بالـ Design System وبعدين اكتب كل مكان بيختلفوا فيه عن دليل البراند","- الـ Design System: [الاسم]، معمول من [الملفات]\n- تصميمات التجربة: صفحة واحدة بلغتين، عرض 3 شرائح، بوست سوشيال مربع\n- النص المستخدم: [الصق النص المعتمد بالظبط؛ من غير أرقام وهمية]","التجربة على 3 أشكال بتطلّع مشاكل الخط واللون والـ RTL قبل ما توصل للعملاء","- 3 تصميمات تجربة بالظبط، وكل واحد بالنص المعتمد الحقيقي بس\n- كل اختلاف مربوط بقاعدة من دليل البراند\n- مفيش أرقام أو ادعاءات غير النص اللي اتلصق","جدول checklist بأعمدة: تصميم التجربة، البند (اللون، الخط، اللوجو، RTL، الأرقام، التباين)، نجح أو فشل، التصليح في الـ Design System. ومراجع بشري يوقّع في الآخر."])],doc:""},

{id:"3.5",tag:"practical",dur:"45",t:T("Refining on the canvas: chat, inline comments and direct edits","التعديل على اللوحة: الشات والتعليقات والتعديل المباشر"),
body:T(`<p>A good first draft comes from a good brief; a finished design comes from smart refining. As of Sept 2026, Claude Design gives you three ways to refine, and choosing the right one saves time and usage.</p>
<table><tr><th>Method</th><th>Use it for</th><th>Example</th></tr><tr><td>Chat</td><td>Broad changes to the whole design</td><td>Make it more formal and move the numbers to the top</td></tr><tr><td>Inline comments</td><td>Targeted, component-level changes</td><td>On this chart: label the bars in Arabic</td></tr><tr><td>Direct canvas editing</td><td>Small layout fixes you can do faster yourself</td><td>Drag, resize and align elements with layout controls</td></tr></table>
<p><b>Feed it the right inputs.</b> Claude Design accepts screenshots and images of existing designs, competitor references, wireframes, visual inspiration, slide decks and documents, codebases and design files. Give it the real content too: the approved text and the numbers from your own file, never placeholders that someone might forget to replace.</p>
<p><b>The design brief pattern</b> (eight lines): audience; format and size; the one message; exact content (text and numbers pasted); brand (use our design system); language and direction (Arabic RTL, Latin numerals or Arabic-Indic); references (attached inputs); output (export type).</p>
<ol><li>Write the brief and attach the inputs.</li><li>Review the first draft as a whole; use chat for big direction changes.</li><li>Switch to inline comments for each component that needs work.</li><li>Finish small alignment and spacing fixes directly on the canvas.</li><li>Before export, read every word and check every number against the source.</li></ol>
<p><b>Human check:</b> Claude can lay out a chart beautifully with a wrong number. The person who owns the data checks the figures; the brand owner checks the look.</p>`,
`<p>المسودة الأولى الكويسة بتيجي من بريف كويس؛ والتصميم الخلصان بييجي من تعديل ذكي. لحد سبتمبر 2026، Claude Design بيديك 3 طرق للتعديل، واختيار الطريقة الصح بيوفر وقت واستخدام.</p>
<table><tr><th>الطريقة</th><th>تستخدمها في</th><th>مثال</th></tr><tr><td>الشات</td><td>تغييرات عامة على التصميم كله</td><td>خليه رسمي أكتر وطلّع الأرقام لفوق</td></tr><tr><td>التعليقات على العناصر (inline comments)</td><td>تغيير محدد على component واحد</td><td>على الرسم ده: اكتب أسامي الأعمدة بالعربي</td></tr><tr><td>التعديل المباشر على اللوحة</td><td>تظبيطات صغيرة في الترتيب أسرع لو عملتها بنفسك</td><td>اسحب وكبّر وصغّر وظبّط محاذاة العناصر بأدوات الـ layout</td></tr></table>
<p><b>ادّيله المدخلات الصح.</b> Claude Design بيقبل screenshots وصور لتصميمات موجودة، ومراجع من المنافسين، و wireframes، وصور للإلهام، وعروض شرائح ومستندات، وأكواد وملفات تصميم. وادّيله المحتوى الحقيقي كمان: النص المعتمد والأرقام من ملفك إنت، مش أرقام مؤقتة حد ممكن ينسى يغيّرها.</p>
<p><b>قالب بريف التصميم</b> (8 سطور): الجمهور؛ الشكل والمقاس؛ الرسالة الواحدة؛ المحتوى بالظبط (النص والأرقام ملصوقين)؛ البراند (استخدم الـ Design System بتاعنا)؛ اللغة والاتجاه (عربي RTL، أرقام لاتيني ولا هندي)؛ المراجع (المدخلات المرفقة)؛ المخرج (نوع التصدير).</p>
<ol><li>اكتب البريف وارفق المدخلات.</li><li>بص على المسودة الأولى ككل؛ واستخدم الشات للتغييرات الكبيرة في الاتجاه.</li><li>اقلب على التعليقات لكل component محتاج شغل.</li><li>خلّص تظبيطات المحاذاة والمسافات الصغيرة بإيدك على اللوحة.</li><li>قبل التصدير، اقرا كل كلمة وراجع كل رقم على المصدر.</li></ol>
<p><b>المراجعة البشرية:</b> Claude ممكن يرسم chart شكله تحفة برقم غلط. صاحب البيانات يراجع الأرقام؛ وصاحب البراند يراجع الشكل.</p>`),
steps:T(["Write the 8-line design brief","Attach inputs: screenshots, references, wireframes, files","Use chat for broad direction changes","Use inline comments for each component","Finish with direct canvas edits and a full proofread"],["اكتب بريف التصميم في 8 سطور","ارفق المدخلات: screenshots، مراجع، wireframes، ملفات","استخدم الشات لتغييرات الاتجاه الكبيرة","استخدم التعليقات لكل component","خلّص بالتعديل المباشر على اللوحة ومراجعة كاملة"]),
tips:T(["One comment, one change: short targeted comments are easier to check than long chat messages.","Paste numbers from the approved file; never let a design invent a statistic to fill space.","Do tiny moves yourself on the canvas; asking in chat for a 2-pixel shift wastes usage."],["تعليق واحد = تغيير واحد: التعليقات القصيرة المحددة أسهل في المراجعة من رسايل شات طويلة.","الصق الأرقام من الملف المعتمد؛ ومتسيبش التصميم يألّف إحصائية علشان يملا مكان.","الحركات الصغيرة اعملها بإيدك على اللوحة؛ إنك تطلب في الشات تحريك 2 بكسل بيضيّع استخدام."]),
cases:[{t:T("Fixing a sales one-pager in 20 minutes","تصليح صفحة مبيعات في 20 دقيقة"),d:T("A sales manager used chat once to change the tone, then 6 inline comments for the price table, the icons and the Arabic headline, and finished by aligning the footer on the canvas. The product manager checked every price against the approved list before export.","مدير مبيعات استخدم الشات مرة واحدة يغيّر النبرة، وبعدين 6 تعليقات على جدول الأسعار والأيقونات والعنوان العربي، وخلّص بمحاذاة الفوتر على اللوحة. مدير المنتج راجع كل سعر على القائمة المعتمدة قبل التصدير.")},{t:T("From a whiteboard photo to a clean process graphic","من صورة سبورة لرسم عملية نضيف"),d:T("The operations team uploaded a photo of a whiteboard wireframe of the purchase-approval steps. Claude Design turned it into a clean bilingual process graphic; the team corrected two step names with inline comments.","فريق العمليات رفع صورة wireframe على السبورة لخطوات اعتماد المشتريات. Claude Design حوّلها لرسم عملية نضيف بلغتين؛ والفريق صحّح اسم خطوتين بالتعليقات.")}],
prompts:[
PR("Master prompt — 8-line design brief","البرومبت الماستر — بريف تصميم في 8 سطور",["Marketing and finance communications lead briefing Claude Design on a business asset for Egypt and the Gulf","Create the first draft of [asset type] using our design system and only the content I paste below","- Audience: [who] — Format and size: [A4 one-pager / 16:9 deck / square post]\n- The one message: [one sentence]\n- Exact content: [paste approved text and numbers with their source]\n- Language and direction: [Arabic RTL / English / both]; numerals: [Latin / Arabic-Indic]\n- References attached: [screenshots, wireframe, old version]","A precise brief gives a usable first draft and fewer rounds of changes","- Use only the pasted text and numbers; mark gaps as [MISSING]\n- Max [3] key points on the page\n- A person approves the final before anything is shared","One draft design plus a short list of 3 questions or assumptions for me to confirm, in [English/Arabic]."],["مسؤول تواصل تسويقي ومالي بيدي Claude Design بريف لتصميم شغل في مصر والخليج","اعمل أول مسودة لـ [نوع التصميم] بالـ Design System بتاعنا وبالمحتوى اللي هلصقه تحت بس","- الجمهور: [مين] — الشكل والمقاس: [صفحة A4 / عرض 16:9 / بوست مربع]\n- الرسالة الواحدة: [جملة واحدة]\n- المحتوى بالظبط: [الصق النص والأرقام المعتمدة ومصدرها]\n- اللغة والاتجاه: [عربي RTL / إنجليزي / الاتنين]؛ الأرقام: [لاتيني / هندي]\n- المراجع المرفقة: [screenshots، wireframe، نسخة قديمة]","البريف الدقيق بيدي مسودة أولى تنفع وجولات تعديل أقل","- استخدم النص والأرقام الملصوقة بس؛ وأي نقص اكتبه [MISSING]\n- [3] نقط أساسية بالكتير في الصفحة\n- شخص يعتمد النسخة النهائية قبل أي مشاركة","مسودة تصميم واحدة + قائمة قصيرة فيها 3 أسئلة أو افتراضات أأكدها، بالـ [عربي/إنجليزي]."]),
PR("Master prompt — refinement plan for a draft design","البرومبت الماستر — خطة تعديل لمسودة تصميم",["Senior designer reviewing a Claude Design draft and planning the cheapest way to finish it","Review the current draft and sort every change I need into chat, inline comment or direct canvas edit","- Draft: [name of the design]\n- My change list: [paste all the changes you want]\n- Must not change: [logo, approved numbers, legal line]","Using the right refinement method keeps changes precise and saves usage","- Every change assigned to exactly 1 method\n- Max 2 chat messages; the rest as comments or direct edits\n- Flag any change that would alter a number or claim for human approval","A table with columns: Change, Method (chat / inline comment / canvas), Exact wording of the comment or message, Needs approval (yes/no)."],["مصمم كبير بيراجع مسودة من Claude Design وبيخطط لأرخص طريقة يخلّصها","راجع المسودة الحالية ووزّع كل تعديل محتاجه على الشات أو التعليقات أو التعديل المباشر على اللوحة","- المسودة: [اسم التصميم]\n- قائمة التعديلات: [الصق كل التعديلات اللي عايزها]\n- ممنوع يتغير: [اللوجو، الأرقام المعتمدة، السطر القانوني]","استخدام طريقة التعديل الصح بيخلّي التغييرات دقيقة وبيوفر استخدام","- كل تعديل ليه طريقة واحدة بالظبط\n- 2 رسالة شات بالكتير؛ والباقي تعليقات أو تعديل مباشر\n- علّم أي تعديل بيغيّر رقم أو ادعاء علشان يتعتمد من شخص","جدول بأعمدة: التعديل، الطريقة (شات / تعليق / لوحة)، نص التعليق أو الرسالة بالظبط، محتاج اعتماد (أيوه/لأ)."])],doc:""},

{id:"3.6",tag:"practical",dur:"40",t:T("Export, share and hand off — with a review checklist","التصدير والمشاركة والتسليم — مع checklist للمراجعة"),
body:T(`<p>A design is only useful when it reaches the right people in the right format. As of Sept 2026, Claude Design designs start <b>private</b>. The Share button sets who can view, comment or edit, so you can invite a reviewer to comment without letting them change the file.</p>
<table><tr><th>Export</th><th>Best for</th></tr><tr><td>PDF</td><td>Printing, email attachments, board packs</td></tr><tr><td>PPTX</td><td>Decks that colleagues will edit in PowerPoint</td></tr><tr><td>Standalone HTML</td><td>A page that opens in any browser</td></tr><tr><td>ZIP</td><td>All files of the project in one package</td></tr><tr><td>Canva</td><td>Editable designs (not flattened) for the marketing team</td></tr><tr><td>Adobe, Miro, Netlify, Vercel</td><td>Teams already working in those tools</td></tr><tr><td>Handoff to Claude Code</td><td>A handoff bundle so a prototype can be implemented</td></tr></table>
<p><b>Review checklist before anything leaves the company:</b></p>
<ol><li><b>Brand:</b> logo, colours and fonts match the design system; no old logo.</li><li><b>Accessibility:</b> text has enough contrast with its background, font sizes are readable, charts do not rely on colour alone.</li><li><b>Arabic:</b> right-to-left layout, correct letter shaping, the approved Arabic font, numerals consistent, punctuation and brackets the right way round.</li><li><b>Numbers:</b> every figure checked against the approved source file by the person who owns it.</li><li><b>Sharing:</b> correct view, comment or edit rights; drafts never shared with clients.</li></ol>
<p>Export to the format your audience really uses: a board wants PDF, a sales team wants PPTX, marketing wants Canva, developers want the Claude Code handoff. A human signs off the checklist; Claude can help you check, but it does not approve.</p>`,
`<p>التصميم بيبقى مفيد لما يوصل للناس الصح بالشكل الصح. لحد سبتمبر 2026، تصميمات Claude Design بتبدأ <b>خاصة (private)</b>. زرار Share بيحدد مين يشوف أو يعلّق أو يعدّل، فتقدر تعزم مراجع يعلّق من غير ما يقدر يغيّر في الملف.</p>
<table><tr><th>التصدير</th><th>أحسن استخدام</th></tr><tr><td>PDF</td><td>الطباعة، مرفقات الإيميل، ملفات المجلس</td></tr><tr><td>PPTX</td><td>عروض الزملاء هيعدّلوا فيها على PowerPoint</td></tr><tr><td>HTML مستقل</td><td>صفحة بتفتح في أي متصفح</td></tr><tr><td>ZIP</td><td>كل ملفات المشروع في باكدج واحدة</td></tr><tr><td>Canva</td><td>تصميمات قابلة للتعديل (مش متسطّحة) لفريق التسويق</td></tr><tr><td>Adobe و Miro و Netlify و Vercel</td><td>للفرق اللي شغالة أصلاً على الأدوات دي</td></tr><tr><td>Handoff لـ Claude Code</td><td>handoff bundle علشان النموذج الأولي يتنفّذ</td></tr></table>
<p><b>Checklist المراجعة قبل ما أي حاجة تطلع برا الشركة:</b></p>
<ol><li><b>البراند:</b> اللوجو والألوان والخطوط مطابقة للـ Design System؛ ومفيش لوجو قديم.</li><li><b>سهولة القراءة (Accessibility):</b> الكلام واضح على الخلفية (contrast كفاية)، والخط مقاسه مقروء، والرسوم مش معتمدة على اللون بس.</li><li><b>العربي:</b> اتجاه من اليمين للشمال، الحروف متشبكة صح، الخط العربي المعتمد، الأرقام بشكل واحد، وعلامات الترقيم والأقواس في اتجاهها الصح.</li><li><b>الأرقام:</b> كل رقم اتراجع على الملف المصدر المعتمد من صاحبه.</li><li><b>المشاركة:</b> صلاحيات المشاهدة أو التعليق أو التعديل صح؛ والمسودات عمرها ما تتبعت لعملاء.</li></ol>
<p>صدّر بالشكل اللي جمهورك بيستخدمه فعلاً: المجلس عايز PDF، المبيعات عايزين PPTX، التسويق عايز Canva، والمطورين عايزين الـ handoff لـ Claude Code. شخص هو اللي يوقّع على الـ checklist؛ Claude يساعدك تراجع، بس هو مش اللي بيعتمد.</p>`),
steps:T(["Set sharing: view, comment or edit","Collect reviewer comments","Run the 5-point checklist: brand, accessibility, Arabic, numbers, sharing","Export in the format the audience uses","Hand off to Claude Code if a prototype must be built"],["ظبّط المشاركة: مشاهدة أو تعليق أو تعديل","لم تعليقات المراجعين","طبّق الـ checklist الخماسي: البراند، القراءة، العربي، الأرقام، المشاركة","صدّر بالشكل اللي الجمهور بيستخدمه","سلّم لـ Claude Code لو في نموذج أولي هيتبني"]),
tips:T(["Give reviewers comment rights, not edit rights, so the owner keeps control.","Open the exported PDF or PPTX and check the Arabic again; check it in the exported file too, not only on the canvas."],["ادّي المراجعين صلاحية تعليق مش تعديل، علشان صاحب التصميم يفضل متحكم.","افتح الـ PDF أو الـ PPTX بعد التصدير وراجع العربي تاني؛ راجعه في الملف المصدّر كمان، مش على اللوحة بس."]),
cases:[{t:T("Board pack cover and summary page","غلاف وصفحة ملخص ملف المجلس"),d:T("The CFO office designed the quarterly board-pack cover and a one-page summary, shared it with the CFO for comments only, ran the checklist, and exported to PDF. The controller ticked every number against the approved management accounts.","مكتب المدير المالي صمّم غلاف ملف المجلس الربع سنوي وصفحة ملخص، وشاركه مع المدير المالي بصلاحية تعليق بس، وطبّق الـ checklist، وصدّره PDF. الـ controller علّم على كل رقم قدام الحسابات الإدارية المعتمدة.")},{t:T("Campaign handed to marketing in Canva","حملة اتسلّمت للتسويق على Canva"),d:T("Finance designed a savings-product carousel and exported it to Canva, where it stayed editable, so the marketing team could adjust sizes for each platform without redrawing it.","المالية صممت كاروسيل لمنتج ادخار وصدّرته لـ Canva وفضل قابل للتعديل، فالتسويق قدر يغيّر المقاسات لكل منصة من غير ما يرسمه من الأول.")}],
prompts:[
PR("Master prompt — pre-export review checklist","البرومبت الماستر — checklist مراجعة قبل التصدير",["Brand, accessibility and Arabic-language reviewer checking a Claude Design deliverable before it leaves the company","Check this design against our 5-point checklist and list every issue with a suggested fix","- Design: [name] — audience: [board / clients / staff]\n- Approved source for numbers: [file name and sheet]\n- Brand rules: [design system name or paste rules]\n- Languages: [Arabic RTL / English / both]","A structured check before export prevents brand, readability and number errors from reaching outsiders","- Check all 5 areas: brand, accessibility and contrast, Arabic RTL and fonts, numbers, sharing\n- Every number marked Matches source, Differs or [NOT FOUND]; do not correct numbers yourself\n- Final approval stays with [reviewer name]","A table with columns: Area, Item, Status (OK / Issue), Suggested fix, Owner. End with a one-line go or no-go recommendation for the human approver."],["مراجع براند وسهولة قراءة ولغة عربية بيراجع تصميم من Claude Design قبل ما يطلع برا الشركة","راجع التصميم ده على الـ checklist الخماسي بتاعنا واكتب كل مشكلة مع اقتراح التصليح","- التصميم: [الاسم] — الجمهور: [المجلس / العملاء / الموظفين]\n- المصدر المعتمد للأرقام: [اسم الملف والشيت]\n- قواعد البراند: [اسم الـ Design System أو الصق القواعد]\n- اللغات: [عربي RTL / إنجليزي / الاتنين]","المراجعة المنظمة قبل التصدير بتمنع أخطاء البراند والقراءة والأرقام إنها توصل لحد برا","- راجع الـ 5 مناطق كلهم: البراند، القراءة والتباين، العربي RTL والخطوط، الأرقام، المشاركة\n- كل رقم يتعلّم: مطابق للمصدر، مختلف، أو [NOT FOUND]؛ ومتصلّحش أرقام بنفسك\n- الاعتماد النهائي عند [اسم المراجع]","جدول بأعمدة: المنطقة، البند، الحالة (تمام / مشكلة)، التصليح المقترح، المسؤول. واختم بسطر واحد توصية تطلع ولا لأ للشخص اللي هيعتمد."]),
PR("Master prompt — export and handoff plan","البرومبت الماستر — خطة التصدير والتسليم",["Project coordinator deciding how a finished Claude Design project is exported, shared and handed off to each team","For each audience below, recommend the export format and sharing level, and prepare the handoff note","- Audiences: [board, sales team, marketing, developers]\n- Assets in the project: [one-pager, deck, prototype, ..]\n- Tools they use: [PowerPoint, Canva, browser, Claude Code]","Each team works faster when it receives the format it already uses, with the right rights","- Choose only from: PDF, PPTX, standalone HTML, ZIP, Canva, Adobe, Miro, Netlify, Vercel, Handoff to Claude Code\n- Max 1 recommended format per audience, with a 1-line reason\n- Clients get view-only; final sharing is approved by [owner]","A table with columns: Audience, Asset, Export format, Share right (view / comment / edit), Reason. Then a 6-line handoff note for the developer if a prototype goes to Claude Code."],["منسق مشروع بيقرر مشروع Claude Design الخلصان هيتصدّر ويتشارك ويتسلّم إزاي لكل فريق","لكل جمهور تحت، اقترح شكل التصدير ومستوى المشاركة، وجهّز ملاحظة التسليم","- الجمهور: [المجلس، فريق المبيعات، التسويق، المطورين]\n- التصميمات اللي في المشروع: [صفحة واحدة، عرض، نموذج أولي، ..]\n- الأدوات اللي بيستخدموها: [PowerPoint، Canva، المتصفح، Claude Code]","كل فريق بيشتغل أسرع لما يستلم الشكل اللي بيستخدمه أصلاً، بالصلاحيات الصح","- اختار من دول بس: PDF، PPTX، HTML مستقل، ZIP، Canva، Adobe، Miro، Netlify، Vercel، Handoff لـ Claude Code\n- شكل واحد (1) مقترح لكل جمهور، مع سبب في سطر واحد (1)\n- العملاء ياخدوا مشاهدة بس؛ والمشاركة النهائية يعتمدها [المسؤول]","جدول بأعمدة: الجمهور، التصميم، شكل التصدير، صلاحية المشاركة (مشاهدة / تعليق / تعديل)، السبب. وبعده ملاحظة تسليم 6 سطور للمطور لو في نموذج أولي رايح لـ Claude Code."])],doc:""},

{id:"3.7",tag:"advanced",dur:"50",t:T("Claude Design case lab for business","معمل حالات Claude Design للبيزنس"),
body:T(`<p>This lab turns the last three units into six repeatable business jobs. For each case you bring real content (approved text, numbers from your own files), use your design system, refine with the right method, and run the review checklist before export. Features are as of Sept 2026.</p>
<table><tr><th>Case</th><th>Inputs you bring</th><th>In Claude Design</th><th>Export / handoff</th><th>Human check</th></tr>
<tr><td>Bilingual product one-pager</td><td>Product sheet, approved prices, logo</td><td>Arabic and English versions, one message, 3 benefits</td><td>PDF</td><td>Product owner checks prices and claims</td></tr>
<tr><td>Investor pitch deck</td><td>Business plan, approved financials</td><td>10-12 slides from the plan; inline comments per slide</td><td>PPTX and PDF</td><td>CFO ties every number to the model</td></tr>
<tr><td>Monthly KPI infographic</td><td>The month's KPI table from finance</td><td>One page, 5-6 KPIs, trend arrows</td><td>PDF or Canva</td><td>Data owner checks each KPI</td></tr>
<tr><td>Social carousel</td><td>Campaign message, brand rules</td><td>6-8 square slides, Arabic RTL</td><td>Canva (editable)</td><td>Marketing and compliance review wording</td></tr>
<tr><td>Training course cover + slides</td><td>Course outline, trainer notes</td><td>Cover plus a short deck in the same style</td><td>PPTX and PDF</td><td>Trainer checks content accuracy</td></tr>
<tr><td>Landing-page prototype</td><td>Wireframe, copy, reference screenshots</td><td>Clickable page design, refined on the canvas</td><td>Handoff to Claude Code</td><td>Developer and owner review the build</td></tr></table>
<ol><li>Pick one case that your team needs this month.</li><li>Gather the inputs listed and paste real numbers only.</li><li>Brief with the 8-line pattern from Unit 3.5.</li><li>Refine: chat for direction, comments for components, canvas for layout.</li><li>Run the 5-point checklist from Unit 3.6, then export in the audience's format.</li></ol>
<p>Remember that complex projects use more of your usage limits, so finish one case well before starting the next, and save your best briefs in a Project for reuse.</p>`,
`<p>المعمل ده بيحوّل الـ 3 وحدات اللي فاتوا لـ 6 شغلانات بيزنس تتكرر. في كل حالة بتجيب محتوى حقيقي (نص معتمد، أرقام من ملفاتك)، وتستخدم الـ Design System بتاعك، وتعدّل بالطريقة الصح، وتطبّق الـ checklist قبل التصدير. المميزات حسب الوضع لحد سبتمبر 2026.</p>
<table><tr><th>الحالة</th><th>المدخلات اللي تجيبها</th><th>في Claude Design</th><th>التصدير / التسليم</th><th>المراجعة البشرية</th></tr>
<tr><td>صفحة منتج بلغتين</td><td>ورقة المنتج، الأسعار المعتمدة، اللوجو</td><td>نسخة عربي ونسخة إنجليزي، رسالة واحدة، 3 مميزات</td><td>PDF</td><td>مدير المنتج يراجع الأسعار والادعاءات</td></tr>
<tr><td>عرض للمستثمرين</td><td>خطة البيزنس، الأرقام المالية المعتمدة</td><td>10-12 شريحة من الخطة؛ تعليقات على كل شريحة</td><td>PPTX و PDF</td><td>المدير المالي يربط كل رقم بالنموذج</td></tr>
<tr><td>إنفوجرافيك مؤشرات الشهر</td><td>جدول الـ KPIs بتاع الشهر من المالية</td><td>صفحة واحدة، 5-6 مؤشرات، أسهم اتجاه</td><td>PDF أو Canva</td><td>صاحب البيانات يراجع كل مؤشر</td></tr>
<tr><td>كاروسيل سوشيال</td><td>رسالة الحملة، قواعد البراند</td><td>6-8 شرائح مربعة، عربي RTL</td><td>Canva (قابل للتعديل)</td><td>التسويق والـ compliance يراجعوا الصياغة</td></tr>
<tr><td>غلاف كورس تدريبي + شرائح</td><td>محتوى الكورس، ملاحظات المدرب</td><td>غلاف وعرض قصير بنفس الستايل</td><td>PPTX و PDF</td><td>المدرب يراجع دقة المحتوى</td></tr>
<tr><td>نموذج أولي لـ landing page</td><td>wireframe، النصوص، screenshots مرجعية</td><td>تصميم صفحة تفاعلي، متظبط على اللوحة</td><td>Handoff لـ Claude Code</td><td>المطور وصاحب المشروع يراجعوا التنفيذ</td></tr></table>
<ol><li>اختار حالة واحدة فريقك محتاجها الشهر ده.</li><li>جمّع المدخلات اللي في الجدول والصق أرقام حقيقية بس.</li><li>اكتب البريف بقالب الـ 8 سطور من وحدة 3.5.</li><li>عدّل: الشات للاتجاه، التعليقات للـ components، اللوحة للترتيب.</li><li>طبّق الـ checklist الخماسي من وحدة 3.6، وبعدين صدّر بالشكل اللي الجمهور بيستخدمه.</li></ol>
<p>افتكر إن المشاريع المعقدة بتستهلك من حدود الاستخدام أكتر، فخلّص حالة واحدة كويس قبل ما تبدأ اللي بعدها، واحفظ أحسن البريفات في Project علشان تستخدمها تاني.</p>`),
steps:T(["Pick one of the 6 cases","Gather real inputs and approved numbers","Brief with the 8-line pattern","Refine with chat, comments and canvas","Run the checklist and export or hand off"],["اختار حالة من الـ 6","جمّع المدخلات الحقيقية والأرقام المعتمدة","اكتب البريف بقالب الـ 8 سطور","عدّل بالشات والتعليقات واللوحة","طبّق الـ checklist وصدّر أو سلّم"]),
tips:T(["Save each successful brief as a template so the next month takes minutes.","For investor and board material, the CFO signs off numbers before design review even starts."],["احفظ كل بريف نجح كقالب علشان الشهر الجاي ياخد دقايق.","في مواد المستثمرين والمجلس، المدير المالي يعتمد الأرقام قبل ما مراجعة التصميم تبدأ أصلاً."]),
cases:[{t:T("Monthly KPI infographic becomes a routine","إنفوجرافيك المؤشرات الشهري بقى روتين"),d:T("A finance team pastes the approved KPI table each month into a saved brief. Claude Design produces the one-page infographic in the brand style; the data owner checks the 6 KPIs and it is exported to PDF for the management meeting.","فريق مالية بيلصق جدول الـ KPIs المعتمد كل شهر في بريف محفوظ. Claude Design بيطلّع الإنفوجرافيك في صفحة واحدة بستايل البراند؛ وصاحب البيانات يراجع الـ 6 مؤشرات ويتصدّر PDF لاجتماع الإدارة.")},{t:T("Landing page from design to build","Landing page من التصميم للتنفيذ"),d:T("A training company designed a course landing page from a wireframe and two reference screenshots, refined it on the canvas, and used Handoff to Claude Code. The developer received the handoff bundle and built the page; the owner reviewed it before going live.","شركة تدريب صممت landing page لكورس من wireframe و2 screenshots مرجعية، وظبطتها على اللوحة، واستخدمت Handoff لـ Claude Code. المطور استلم الـ handoff bundle وبنى الصفحة؛ وصاحب الشركة راجعها قبل ما تنزل.")}],
prompts:[
PR("Master prompt — investor pitch deck in Claude Design","البرومبت الماستر — عرض مستثمرين في Claude Design",["Investor-relations and FP&A lead turning an approved business plan into a pitch deck in Claude Design","Design a [10-12]-slide investor pitch deck from the attached business plan and approved financial summary, in our design system","- Business plan: [attached file]\n- Approved financials: [file and version], approved by [CFO name]\n- Audience: [investor type]; language: [English / Arabic RTL / both]\n- Slide list: [problem, solution, market, model, traction, financials, team, ask]","Investors judge clarity and credibility; every number must be traceable to the approved model","- Use only numbers from the approved file; any missing figure shown as [MISSING]\n- Max [12] slides and max 30 words of body text per slide\n- No forecasts or market sizes that are not in the files; the CFO approves before sharing","The deck in Claude Design plus a table with columns: Slide, Key number, Source cell or page, Status (checked / to check). Export PPTX and PDF only after approval."],["مسؤول علاقات مستثمرين و FP&A بيحوّل خطة بيزنس معتمدة لعرض مستثمرين في Claude Design","صمّم عرض مستثمرين [10-12] شريحة من خطة البيزنس والملخص المالي المعتمد المرفقين، بالـ Design System بتاعنا","- خطة البيزنس: [الملف المرفق]\n- الأرقام المالية المعتمدة: [الملف والنسخة]، معتمدة من [اسم المدير المالي]\n- الجمهور: [نوع المستثمر]؛ اللغة: [إنجليزي / عربي RTL / الاتنين]\n- قائمة الشرائح: [المشكلة، الحل، السوق، نموذج الربح، الإنجازات، الأرقام، الفريق، المطلوب]","المستثمرين بيحكموا على الوضوح والمصداقية؛ وكل رقم لازم يرجع للنموذج المعتمد","- استخدم أرقام الملف المعتمد بس؛ وأي رقم ناقص يظهر [MISSING]\n- [12] شريحة بالكتير و30 كلمة بالكتير في كل شريحة\n- مفيش توقعات أو أحجام سوق مش موجودة في الملفات؛ والمدير المالي يعتمد قبل المشاركة","العرض في Claude Design + جدول بأعمدة: الشريحة، الرقم الأساسي، الخلية أو الصفحة المصدر، الحالة (اتراجع / محتاج مراجعة). وصدّر PPTX و PDF بعد الاعتماد بس."]),
PR("Master prompt — landing-page prototype with handoff","البرومبت الماستر — نموذج landing page مع التسليم",["Product owner designing a bilingual landing-page prototype in Claude Design to hand off to Claude Code","Design a landing-page prototype from my wireframe and copy, then prepare it for Handoff to Claude Code","- Wireframe and reference screenshots: [attached]\n- Approved copy: [paste text in Arabic and English]\n- Sections: [hero, benefits, pricing, FAQ, contact form]\n- Prices and offers: [paste approved values only]","A clear prototype and handoff bundle let a developer build the page without guessing","- Use only the pasted copy and prices; mark gaps as [MISSING]\n- Max [6] sections; Arabic version fully RTL\n- Nothing goes live until [owner] approves the built page","The prototype in Claude Design, then a handoff summary with columns: Section, Content source, Interaction, Open question. Use Handoff to Claude Code only after I confirm."],["صاحب منتج بيصمم نموذج أولي لـ landing page بلغتين في Claude Design علشان يسلّمه لـ Claude Code","صمّم نموذج landing page من الـ wireframe والنصوص بتوعي، وبعدين جهّزه لـ Handoff لـ Claude Code","- الـ wireframe و screenshots مرجعية: [مرفقين]\n- النصوص المعتمدة: [الصق النص بالعربي والإنجليزي]\n- الأقسام: [hero، المميزات، الأسعار، الأسئلة الشائعة، فورم التواصل]\n- الأسعار والعروض: [الصق القيم المعتمدة بس]","النموذج الواضح والـ handoff bundle بيخلّوا المطور يبني الصفحة من غير تخمين","- استخدم النصوص والأسعار الملصوقة بس؛ وأي نقص اكتبه [MISSING]\n- [6] أقسام بالكتير؛ والنسخة العربي RTL بالكامل\n- مفيش حاجة تنزل أونلاين قبل ما [المسؤول] يعتمد الصفحة بعد بنائها","النموذج في Claude Design، وبعده ملخص تسليم بأعمدة: القسم، مصدر المحتوى، التفاعل، سؤال مفتوح. استخدم Handoff لـ Claude Code بعد ما أأكد بس."])],doc:""}
);

const U=id=>D3x.units.find(u=>u.id===id);
U("3.1").cases.push(
{t:T("Interactive KPI dashboard from a CSV","داشبورد KPIs تفاعلي من ملف CSV"),d:T("A sales controller uploaded the monthly sales CSV and asked for an artifact with filters by region and product, KPI cards and a 12-month trend. Before sharing, she checked three totals against the ERP report and removed customer names.","مسؤولة رقابة مبيعات رفعت ملف CSV المبيعات الشهري وطلبت Artifact فيه فلاتر بالمنطقة والمنتج، وكروت KPIs، واتجاه 12 شهر. قبل ما تشاركه راجعت 3 إجماليات على تقرير الـ ERP وشالت أسامي العملاء.")},
{t:T("Compliance quiz for new staff","اختبار compliance للموظفين الجداد"),d:T("HR pasted the approved code-of-conduct text and asked for a 10-question bilingual quiz artifact with instant feedback. The compliance officer reviewed every question and answer before the link was sent to new joiners.","الـ HR لصقوا نص ميثاق السلوك المعتمد وطلبوا Artifact اختبار 10 أسئلة بلغتين مع تصحيح فوري. مسؤول الـ compliance راجع كل سؤال وإجابة قبل ما اللينك يتبعت للموظفين الجداد.")});
U("3.2").cases.push(
{t:T("Board pack: Word paper plus deck","ملف المجلس: ورقة Word + عرض"),d:T("From the approved quarterly accounts, the CFO office asked one conversation for a docx board paper and a matching 8-slide deck. The company secretary checked the format and the controller checked every figure against the accounts.","من الحسابات الربع سنوية المعتمدة، مكتب المدير المالي طلب من محادثة واحدة ورقة مجلس docx وعرض 8 شرائح متطابق معاها. سكرتير الشركة راجع الشكل والـ controller راجع كل رقم على الحسابات.")},
{t:T("Expense policy drafted in Claude Docs","سياسة المصروفات اتكتبت في Claude Docs"),d:T("The finance manager drafted a travel and expense policy in Claude Docs from the old policy and the team's questions, then shared it for comments. Legal and HR commented in the document, and the final version was approved by the CFO.","المدير المالي كتب سياسة السفر والمصروفات في Claude Docs من السياسة القديمة وأسئلة الفريق، وبعدين شاركها للتعليقات. القانوني والـ HR علّقوا في المستند، والنسخة النهائية اتعتمدت من المدير المالي.")});
U("3.3").cases.push(
{t:T("Ramadan campaign visuals","تصميمات حملة رمضان"),d:T("A retail team designed a set of Ramadan offer visuals in Arabic and English with the brand design system: one poster, one square post and one story size. Marketing confirmed the offer terms and prices before export.","فريق ريتيل صمم مجموعة تصميمات لعروض رمضان بالعربي والإنجليزي بالـ Design System بتاع البراند: بوستر، وبوست مربع، ومقاس ستوري. التسويق أكد شروط العرض والأسعار قبل التصدير.")},
{t:T("Client event invitation","دعوة لحدث العملاء"),d:T("The CEO office designed a bilingual invitation for a client breakfast seminar, with date, venue and an RSVP line pasted from the approved event sheet. The office manager checked names and timing, then exported a PDF for email.","مكتب الـ CEO صمم دعوة بلغتين لندوة فطار للعملاء، بالتاريخ والمكان وسطر تأكيد الحضور ملصوقين من ورقة الحدث المعتمدة. مدير المكتب راجع الأسامي والمواعيد، وبعدين اتصدّرت PDF للإيميل.")});

FEAT["3.4"]="Access, plans, brand design system, /design-sync";FEAT["3.5"]="Chat, inline comments, canvas edits, 8-line brief";FEAT["3.6"]="Share rights, PDF/PPTX/Canva/HTML, Claude Code handoff, checklist";FEAT["3.7"]="Six business design cases end to end";
CEO["3.4"]=T("Build the brand design system once, approve it, and every asset starts on-brand.","ابني الـ Design System مرة واعتمده، وكل تصميم هيبدأ على البراند.");CEO["3.5"]=T("The right refinement method turns a draft into a finished design faster and cheaper.","طريقة التعديل الصح بتحوّل المسودة لتصميم خلصان أسرع وأرخص.");CEO["3.6"]=T("Nothing leaves the company until a human has checked brand, readability, Arabic and every number.","مفيش حاجة تطلع برا الشركة قبل ما شخص يراجع البراند والقراءة والعربي وكل رقم.");CEO["3.7"]=T("Six repeatable design jobs can move from weeks of back-and-forth to a reviewed draft in a day.","6 شغلانات تصميم متكررة ممكن تتحول من أسابيع رايح جاي لمسودة متراجعة في يوم.");

QUIZ[3].push(
Q("As of Sept 2026, how is Claude Design enabled on an Enterprise plan?","لحد سبتمبر 2026، Claude Design بيشتغل إزاي على خطة Enterprise؟",[["It is on by default for everyone","شغال تلقائي للكل"],["It is not available on Enterprise","مش متاح في Enterprise"],["It is off until an owner turns it on","مقفول لحد ما الـ owner يشغّله"],["Each user installs it separately","كل مستخدم بينزّله لوحده"]],2,"It is on by default on Pro, Max and Team; on Enterprise an owner must turn it on.","بيبقى شغال تلقائي على Pro و Max و Team؛ وفي Enterprise لازم الـ owner يشغّله."),
Q("Which refinement method fits a targeted change to one chart?","أنهي طريقة تعديل تناسب تغيير محدد في chart واحد؟",[["An inline comment on that component","تعليق على الـ component ده"],["Starting a new project","تبدأ مشروع جديد"],["Rebuilding the design system","تعيد بناء الـ Design System"],["Exporting to ZIP","تصدّر ZIP"]],0,"Inline comments are for targeted, component-level changes; chat is for broad ones.","التعليقات للتغييرات المحددة على component؛ والشات للتغييرات العامة."),
Q("How can a team build its design system from a local codebase?","الفريق يقدر يبني الـ Design System من كود على الجهاز إزاي؟",[["By emailing the code to support","يبعت الكود بالإيميل للدعم"],["It cannot; only logos are accepted","مينفعش؛ اللوجوهات بس"],["By pasting colours into every prompt","يلصق الألوان في كل برومبت"],["In Claude Code via /design-sync","من Claude Code بأمر /design-sync"]],3,"A design system can be built from brand files, decks, design files, GitHub repos or local codebases via /design-sync.","الـ Design System يتبني من ملفات البراند أو العروض أو ملفات التصميم أو GitHub repos أو الأكواد عن طريق /design-sync."),
Q("What happens when a design is exported to Canva?","إيه اللي بيحصل لما التصميم يتصدّر لـ Canva؟",[["It becomes a flat image only","بيبقى صورة مسطّحة بس"],["It stays editable, not flattened","بيفضل قابل للتعديل، مش متسطّح"],["It is published publicly","بيتنشر للعامة"],["It is deleted from Claude Design","بيتمسح من Claude Design"]],1,"The Canva export keeps the design editable.","التصدير لـ Canva بيخلّي التصميم قابل للتعديل."),
Q("Who can see a new Claude Design design by default?","مين يقدر يشوف تصميم جديد في Claude Design افتراضياً؟",[["Anyone with the link","أي حد معاه اللينك"],["The whole organization","الشركة كلها"],["Only you; designs start private until you use Share","إنت بس؛ التصميمات بتبدأ خاصة لحد ما تستخدم Share"],["Anthropic reviewers","مراجعين من Anthropic"]],2,"Designs start private; Share sets who can view, comment or edit.","التصميمات بتبدأ خاصة؛ و Share بيحدد مين يشوف أو يعلّق أو يعدّل."));
