// ===== CURRICULUM 5: 4.4 one job six tools, 9.6 Egypt & GCC regulations pack, Module 11 family business & SMEs, module projects =====
const ENR=(a,ar)=>{const x=a.slice();if(x[0].length<40&&!/Egypt|Gulf|Saudi|UAE|مصر|الخليج|السعودية|الإمارات/.test(x[0]))x[0]+=ar?' لشركة في مصر أو الخليج':' at a company in Egypt or the Gulf';x[2]+=ar?'\n- اللغة والعملة: [عربي / إنجليزي]؛ بالجنيه المصري إلا لو الملف قال غير كده':'\n- Language and currency: [Arabic / English]; EGP unless the file says otherwise';x[4]+=ar?'\n- الافتراضات متعلّمة؛ ومفيش حاجة متألفة':'\n- Assumptions labelled; nothing invented';return x};
const MPB=(en,ar)=>({p:T(MPen(...ENR(en)),MPar(...ENR(ar,1))),master:true});
const PR=(ten,tar,en,ar)=>Object.assign({t:T(ten,tar)},MPB(en,ar));

// ---------- 4.4 One job, six Claude tools ----------
const SIX=[
['chat',T('Chat','الشات'),T('One-off, a few files, you are at the keyboard.','مرة واحدة، شوية ملفات، وإنت قاعد قدام الجهاز.')],
['project',T('Project','Project'),T('The same job every month with the same reference files and instructions.','نفس الشغلانة كل شهر بنفس الملفات المرجعية والتعليمات.')],
['skill',T('Skill','Skill'),T('A method you want to reuse anywhere — chat, Cowork or Code — and share with the team.','طريقة عايز تكررها في أي مكان — الشات أو Cowork أو Code — وتشاركها مع الفريق.')],
['cowork',T('Cowork','Cowork'),T('Many steps across files and folders that you hand over and review at the end.','خطوات كتير على ملفات وفولدرات بتسلّمها وتراجعها في الآخر.')],
['excel',T('Claude in Excel','Claude في Excel'),T('The work lives in a workbook and you want answers and formulas next to the data.','الشغل جوه ملف Excel وعايز إجابات ومعادلات جنب البيانات.')],
['api',T('API','الـ API'),T('It must run on a schedule or inside another system, without someone opening Claude.','لازم يشتغل بجدول أو جوه سيستم تاني من غير ما حد يفتح Claude.')]];
const close6=[
PR('Close variances — Chat','انحرافات الإقفال — الشات',["FP&A analyst","Explain the material budget-vs-actual variances for this month","- Attached: bva.csv (line, month, budget, actual, last year — EGP k)\n- Materiality: over EGP 250k or 5%","The CFO reviews the close pack tomorrow","- Every material line explained or marked NEEDS OWNER INPUT\n- Figures traced to the file","Table + 5 bullet insights."],["محلل FP&A","اشرح انحرافات الموازنة مقابل الفعلي المهمة للشهر ده","- مرفق: bva.csv (البند، الشهر، الموازنة، الفعلي، السنة اللي فاتت — ألف جنيه)\n- الأهمية: فوق 250 ألف جنيه أو 5%","المدير المالي هيراجع ملف الإقفال بكرة","- كل بند مهم متشرح أو متعلّم «محتاج رأي المسؤول»\n- الأرقام متتبعة للملف","جدول + 5 ملاحظات."]),
PR('Close variances — Project instructions','انحرافات الإقفال — تعليمات الـ Project',["FP&A analyst for [company] working inside the Month-end close Project","Each month, when I upload the new bva file, produce the variance commentary in our standard format","- Project knowledge: chart of accounts, last 3 close packs, materiality policy, owner list\n- New each month: bva.csv for the month","Consistency month to month matters more than speed","- Use the owner list to address each question\n- Compare with last month’s commentary and note repeats\n- Follow the house style in the last pack","Same layout as the last pack: summary, variance table, questions for owners."],["محلل FP&A لـ [الشركة] جوه Project الإقفال الشهري","كل شهر لما أرفع ملف bva الجديد، طلّع شرح الانحرافات بالشكل المعتاد","- معرفة الـ Project: دليل الحسابات، آخر 3 ملفات إقفال، سياسة الأهمية، قائمة المسؤولين\n- الجديد كل شهر: bva.csv للشهر","الثبات من شهر للتاني أهم من السرعة","- استخدم قائمة المسؤولين لتوجيه كل سؤال\n- قارن بشرح الشهر اللي فات وعلّم المتكرر\n- امشي على ستايل آخر ملف","نفس ترتيب آخر ملف: ملخص، جدول الانحرافات، أسئلة للمسؤولين."]),
PR('Close variances — Skill','انحرافات الإقفال — Skill',["Author of a reusable Skill","Write the SKILL.md instructions for a variance-commentary Skill the whole finance team can use","- Inputs the Skill should expect: a budget-vs-actual table in any layout\n- Our materiality rule and commentary style: [paste]\n- Where it will be used: chat, Cowork, Excel","One method for everyone instead of many personal prompts","- Clear name and a description that says when to use it\n- Step-by-step method, materiality rule, output template\n- What to do when data is missing","SKILL.md content (name, description, instructions, output template)."],["كاتب Skill قابلة لإعادة الاستخدام","اكتب تعليمات SKILL.md لـ Skill شرح الانحرافات يستخدمها فريق المالية كله","- المدخلات المتوقعة: جدول موازنة مقابل فعلي بأي شكل\n- قاعدة الأهمية وستايل الشرح: [الصق]\n- هتستخدم فين: الشات، Cowork، Excel","طريقة واحدة للكل بدل برومبتات شخصية كتير","- اسم واضح ووصف بيقول تستخدمها امتى\n- طريقة خطوة بخطوة، قاعدة الأهمية، قالب المخرج\n- تعمل إيه لو البيانات ناقصة","محتوى SKILL.md (الاسم، الوصف، التعليمات، قالب المخرج)."]),
PR('Close variances — Cowork task','انحرافات الإقفال — مهمة Cowork',["Finance operations assistant","Prepare the month-end variance pack from the files in the Close folder","- Folder: [path] with bva.csv, GL export, last month’s pack\n- Steps: reconcile totals to the GL, compute variances, draft commentary, build the summary file\n- Do not email or upload anything","I review the full pack once, at the end","- Totals reconcile to the GL or the gap is reported\n- One summary file and one questions list saved to the folder\n- A log of each step taken","Files saved in the folder + a short log of what was done and what needs my review."],["مساعد عمليات مالية","جهّز ملف انحرافات الإقفال من الملفات اللي في فولدر الإقفال","- الفولدر: [المسار] فيه bva.csv، تصدير الأستاذ العام، ملف الشهر اللي فات\n- الخطوات: طابق الإجماليات مع الأستاذ العام، احسب الانحرافات، اكتب الشرح، اعمل ملف الملخص\n- متبعتش إيميل ومترفعش أي حاجة","هراجع الملف كله مرة واحدة في الآخر","- الإجماليات مطابقة للأستاذ العام أو الفرق متوضح\n- ملف ملخص وقائمة أسئلة متحفوظين في الفولدر\n- سجل بكل خطوة اتعملت","ملفات متحفوظة في الفولدر + سجل قصير باللي اتعمل واللي محتاج مراجعتي."]),
PR('Close variances — Claude in Excel','انحرافات الإقفال — Claude في Excel',["Excel-savvy FP&A analyst working in this workbook","Add variance columns and a commentary column to the BvA sheet","- Sheet BvA: columns Line, Budget, Actual (EGP k)\n- Materiality: over 250 or 5%\n- Keep the original columns unchanged","The workbook is the close file the CFO opens","- Variance and % formulas, not typed values\n- Conditional format for material lines\n- Commentary only on material lines, max 20 words each","Updated sheet + a note listing the formulas used."],["محلل FP&A شاطر في Excel شغال في الملف ده","ضيف أعمدة الانحراف وعمود شرح لشيت BvA","- شيت BvA: أعمدة البند، الموازنة، الفعلي (ألف جنيه)\n- الأهمية: فوق 250 أو 5%\n- الأعمدة الأصلية متتغيرش","الملف ده هو ملف الإقفال اللي المدير المالي بيفتحه","- معادلات للانحراف والنسبة مش أرقام مكتوبة\n- تنسيق شرطي للبنود المهمة\n- شرح على البنود المهمة بس، 20 كلمة بالكتير","الشيت متحدّث + ملاحظة بالمعادلات المستخدمة."]),
PR('Close variances — API (scheduled)','انحرافات الإقفال — الـ API (بجدول)',["System prompt for a scheduled variance-commentary job","Given the JSON budget-vs-actual rows in the user message, return variance commentary as JSON","- Input: array of {line, budget, actual, last_year} in EGP k\n- Materiality: over 250 or 5%\n- Runs on working day 3 after month end; output goes to the reporting database","No human sees the raw output before it is stored, so it must be strictly structured","- Valid JSON only, matching the schema\n- material: true/false per line; comment only when material\n- Never invent lines or numbers","JSON: {\"lines\":[{\"line\":\"\",\"variance\":0,\"pct\":0,\"material\":false,\"comment\":\"\"}],\"summary\":\"\"}"],["System prompt لمهمة شرح انحرافات بتشتغل بجدول","من صفوف الموازنة مقابل الفعلي (JSON) اللي في رسالة المستخدم، رجّع شرح الانحرافات كـ JSON","- المدخل: مصفوفة {line, budget, actual, last_year} بالألف جنيه\n- الأهمية: فوق 250 أو 5%\n- بتشتغل تالت يوم عمل بعد آخر الشهر؛ والناتج بيتحفظ في قاعدة بيانات التقارير","مفيش حد بيشوف الناتج قبل ما يتحفظ، فلازم يكون منظم بدقة","- JSON صحيح بس، مطابق للشكل\n- material: true/false لكل بند؛ وشرح للمهم بس\n- عمرك ما تخترع بنود أو أرقام","JSON: {\"lines\":[{\"line\":\"\",\"variance\":0,\"pct\":0,\"material\":false,\"comment\":\"\"}],\"summary\":\"\"}"])];
const pipe6=[
PR('Pipeline review — Chat','مراجعة الـ pipeline — الشات',["Sales operations analyst","Review this week’s pipeline and list the deals at risk","- Attached: crm_deals.csv\n- At risk: no activity in 21+ days, close date passed, or decision maker not met","The sales director runs the Monday meeting","- Every at-risk deal with its reason\n- Total value at risk in EGP","Table of at-risk deals + 3 actions."],["محلل عمليات مبيعات","راجع الـ pipeline بتاع الأسبوع ده وطلّع الصفقات المعرضة للخطر","- مرفق: crm_deals.csv\n- المعرضة للخطر: مفيش نشاط من 21+ يوم، أو تاريخ الإقفال فات، أو صاحب القرار متقابلش","مدير المبيعات بيدير اجتماع الاتنين","- كل صفقة معرضة للخطر بسببها\n- إجمالي القيمة المعرضة للخطر بالجنيه","جدول الصفقات المعرضة للخطر + 3 إجراءات."]),
PR('Pipeline review — Project instructions','مراجعة الـ pipeline — تعليمات الـ Project',["Sales operations analyst inside the Weekly pipeline Project","Each Monday, compare the new CRM export with last week’s and report changes","- Project knowledge: stage definitions, territory list, last 4 weekly reports\n- New each week: crm_deals.csv","The director wants movement, not a static list","- New, won, lost and slipped deals since last week\n- Same layout every week","One-page report: movement table, at-risk list, 3 questions per rep."],["محلل عمليات مبيعات جوه Project الـ pipeline الأسبوعي","كل اتنين، قارن تصدير CRM الجديد بالأسبوع اللي فات وطلّع التغييرات","- معرفة الـ Project: تعريفات المراحل، قائمة المناطق، آخر 4 تقارير أسبوعية\n- الجديد كل أسبوع: crm_deals.csv","المدير عايز الحركة، مش قائمة ثابتة","- الصفقات الجديدة والمكسوبة والخسرانة والمتأخرة من الأسبوع اللي فات\n- نفس الشكل كل أسبوع","تقرير صفحة: جدول الحركة، قائمة الخطر، 3 أسئلة لكل مندوب."]),
PR('Pipeline review — Skill','مراجعة الـ pipeline — Skill',["Author of a reusable Skill","Write SKILL.md for a pipeline-health Skill any sales manager can use","- Inputs: any CRM export with stage, amount, close date, last activity\n- Our risk rules: [paste]","Every manager reviews deals the same way","- When to use it in the description\n- Risk rules, scoring, output template\n- Handling of missing columns","SKILL.md content."],["كاتب Skill قابلة لإعادة الاستخدام","اكتب SKILL.md لـ Skill صحة الـ pipeline يستخدمها أي مدير مبيعات","- المدخلات: أي تصدير CRM فيه المرحلة والمبلغ وتاريخ الإقفال وآخر نشاط\n- قواعد الخطر عندنا: [الصق]","كل مدير يراجع الصفقات بنفس الطريقة","- امتى تستخدمها في الوصف\n- قواعد الخطر، التقييم، قالب المخرج\n- التعامل مع الأعمدة الناقصة","محتوى SKILL.md."]),
PR('Pipeline review — Cowork task','مراجعة الـ pipeline — مهمة Cowork',["Sales operations assistant","Prepare one Monday pack per rep from the CRM export in the Pipeline folder","- Folder: [path] with crm_deals.csv and crm_activities.csv\n- One file per rep with their at-risk deals and suggested next steps\n- Do not contact customers","Reps get a focused list before the meeting","- One file per rep saved to the folder\n- Next steps based on the activity notes\n- A summary file for the director","Files in the folder + a short log."],["مساعد عمليات مبيعات","جهّز ملف اتنين لكل مندوب من تصدير CRM اللي في فولدر الـ Pipeline","- الفولدر: [المسار] فيه crm_deals.csv و crm_activities.csv\n- ملف لكل مندوب فيه صفقاته المعرضة للخطر والخطوة الجاية المقترحة\n- متتواصلش مع أي عميل","كل مندوب ياخد قائمة مركزة قبل الاجتماع","- ملف لكل مندوب متحفوظ في الفولدر\n- الخطوات الجاية مبنية على ملاحظات النشاط\n- ملف ملخص للمدير","ملفات في الفولدر + سجل قصير."]),
PR('Pipeline review — Claude in Excel','مراجعة الـ pipeline — Claude في Excel',["Excel-savvy sales analyst working in this workbook","Add a risk flag and a weighted value to the Deals sheet","- Columns: stage, amount_egp, close_date, last_activity_days, decision_maker_met\n- Stage probabilities: [paste]","The director filters the sheet in the meeting","- Formulas, not typed values\n- Risk reason column in plain words\n- A pivot of weighted pipeline by rep","Updated sheet + pivot + list of formulas."],["محلل مبيعات شاطر في Excel شغال في الملف ده","ضيف علامة خطر وقيمة مرجّحة لشيت الصفقات","- الأعمدة: المرحلة، المبلغ، تاريخ الإقفال، أيام من آخر نشاط، قابلنا صاحب القرار\n- احتمالات المراحل: [الصق]","المدير بيفلتر الشيت في الاجتماع","- معادلات مش أرقام مكتوبة\n- عمود سبب الخطر بكلام بسيط\n- Pivot للـ pipeline المرجّح لكل مندوب","الشيت متحدّث + Pivot + قائمة المعادلات."]),
PR('Pipeline review — API (scheduled)','مراجعة الـ pipeline — الـ API (بجدول)',["System prompt for a weekly pipeline-risk job","Classify each deal in the user message and return JSON","- Input: array of deals with stage, amount, close_date, last_activity_days, decision_maker_met\n- Runs every Monday 7:00; results are posted to the sales dashboard","Output is stored without review, so it must follow the schema","- Valid JSON only\n- risk: low/medium/high with one reason\n- Do not invent deals or fields","JSON: {\"deals\":[{\"id\":\"\",\"risk\":\"low\",\"reason\":\"\"}],\"total_at_risk_egp\":0}"],["System prompt لمهمة خطر الـ pipeline الأسبوعية","صنّف كل صفقة في رسالة المستخدم ورجّع JSON","- المدخل: مصفوفة صفقات فيها المرحلة والمبلغ وتاريخ الإقفال وأيام آخر نشاط ومقابلة صاحب القرار\n- بتشتغل كل اتنين الساعة 7؛ والنتايج بتتنشر على داشبورد المبيعات","الناتج بيتحفظ من غير مراجعة، فلازم يمشي على الشكل","- JSON صحيح بس\n- risk: low/medium/high بسبب واحد\n- متخترعش صفقات أو حقول","JSON: {\"deals\":[{\"id\":\"\",\"risk\":\"low\",\"reason\":\"\"}],\"total_at_risk_egp\":0}"])];
DAYS[3].units.push({id:"4.4",tag:"mastery",dur:"50",t:T("One job, six Claude tools","شغلانة واحدة بست أدوات في Claude"),
body:T(`<p>The same job can be done in six different places in Claude. The prompt changes with the tool: in chat it carries everything; in a Project the reference material moves to project knowledge; in a Skill it becomes a reusable method; in Cowork it becomes a multi-step brief with limits; in Excel it works on the sheet; with the API it becomes a strict system prompt with a JSON schema.</p><div class="tablewrap"><table><tr><th>Tool</th><th>Use it when</th></tr>${SIX.map(s=>`<tr><td><b>${s[1].en}</b></td><td>${s[2].en}</td></tr>`).join('')}</table></div><p>Two worked jobs follow in the Prompts tab — the month-end close variance commentary and the weekly sales pipeline review — each written six ways. Compare them side by side and notice what moves where.</p>`,
`<p>نفس الشغلانة ممكن تتعمل في 6 أماكن مختلفة في Claude. البرومبت بيتغير مع الأداة: في الشات بيشيل كل حاجة؛ في الـ Project المراجع بتتنقل لمعرفة المشروع؛ في الـ Skill بيبقى طريقة قابلة للتكرار؛ في Cowork بيبقى تكليف متعدد الخطوات بحدود؛ في Excel بيشتغل على الشيت؛ ومع الـ API بيبقى System prompt صارم بشكل JSON.</p><div class="tablewrap"><table><tr><th>الأداة</th><th>استخدمها لما</th></tr>${SIX.map(s=>`<tr><td><b>${s[1].ar}</b></td><td>${s[2].ar}</td></tr>`).join('')}</table></div><p>في تبويب البرومبتات فيه شغلانتين متحلولين — شرح انحرافات الإقفال الشهري ومراجعة الـ pipeline الأسبوعية — كل واحدة مكتوبة بالست طرق. قارنهم جنب بعض ولاحظ إيه اللي بيتنقل فين.</p>`),
steps:T(["Describe the job and how often it repeats","Pick the tool with the table","Move stable material to the right place (Project knowledge, Skill, folder)","Adapt the prompt to the tool","Test once and save"],["اوصف الشغلانة وبتتكرر قد إيه","اختار الأداة من الجدول","انقل الحاجات الثابتة لمكانها (معرفة الـ Project، الـ Skill، الفولدر)","كيّف البرومبت للأداة","اختبر مرة واحفظ"]),
tips:T(["Start in chat; move to a Project or Skill the second time you repeat a job.","Cowork and API prompts need explicit limits: what not to send, change or delete."],["ابدأ في الشات؛ وانقل لـ Project أو Skill تاني مرة تكرر فيها الشغلانة.","برومبتات Cowork والـ API محتاجة حدود صريحة: إيه اللي متبعتهوش أو تغيره أو تمسحه."]),
cases:[{t:T("From chat to API in one quarter","من الشات للـ API في ربع سنة"),d:T("A finance team started the close commentary in chat in July, moved it to a Project in August, packaged it as a Skill in September, and connected a scheduled API job in October that writes draft commentary into the reporting database on working day 3.","فريق مالية بدأ شرح الإقفال في الشات في يوليو، ونقله لـ Project في أغسطس، وعمله Skill في سبتمبر، وربط مهمة API بجدول في أكتوبر بتكتب مسودة الشرح في قاعدة بيانات التقارير تالت يوم عمل.")}],
prompts:close6.concat(pipe6),doc:""});
FEAT["4.4"]="Chat vs Project vs Skill vs Cowork vs Excel vs API";CEO["4.4"]=T("Choosing the right Claude tool per job is where most of the time savings come from.","اختيار أداة Claude المناسبة لكل شغلانة هو مصدر أغلب توفير الوقت.");

// ---------- 9.6 Egypt & GCC regulations pack ----------
const REGNOTE=['- Paste the current official text below; do not rely on memory for rates, dates or thresholds\n- Cite article or clause numbers from the pasted text only\n- Anything the pasted text does not cover: write NOT IN PROVIDED TEXT','- الصق النص الرسمي الحالي تحت؛ متعتمدش على الذاكرة في النسب والمواعيد والحدود\n- اذكر أرقام المواد أو البنود من النص الملصوق بس\n- أي حاجة النص مش مغطيها: اكتب «مش موجود في النص المرفق»'];
const REG=(ten,tar,role,roleA,task,taskA,ctx,ctxA,why,whyA,stop,stopA,out,outA)=>PR(ten,tar,[role,task,ctx+'\n'+REGNOTE[0]+'\n- Official text: [paste]',why,stop+'\n- Not legal or tax advice; items for a qualified adviser flagged',out],[roleA,taskA,ctxA+'\n'+REGNOTE[1]+'\n- النص الرسمي: [الصق]',whyA,stopA+'\n- مش استشارة قانونية أو ضريبية؛ والبنود اللي محتاجة مستشار متعلّمة',outA]);
const REGS=[
REG('Egypt e-invoice & e-receipt readiness (ETA)','جاهزية الفاتورة والإيصال الإلكتروني في مصر (مصلحة الضرائب)','Tax technology consultant in Egypt','مستشار تكنولوجيا ضرائب في مصر','Assess our readiness for the Egyptian Tax Authority e-invoice and e-receipt systems','قيّم جاهزيتنا لمنظومة الفاتورة والإيصال الإلكتروني في مصلحة الضرائب المصرية','- Our billing process and systems: [describe]\n- Sample invoice fields: [paste]','- عملية الفوترة والأنظمة عندنا: [اوصف]\n- حقول فاتورة نموذجية: [الصق]','Management must approve a remediation budget','الإدارة لازم تعتمد ميزانية التصحيح','- Each requirement mapped to our current state\n- Gaps ranked by deadline and effort','- كل متطلب مربوط بوضعنا الحالي\n- الفجوات مترتبة حسب الموعد والمجهود','Readiness table + gap list with owners + open questions.','جدول الجاهزية + قائمة الفجوات بالمسؤولين + الأسئلة المفتوحة.'),
REG('VAT return review (Egypt / KSA / UAE)','مراجعة إقرار ضريبة القيمة المضافة (مصر / السعودية / الإمارات)','Indirect tax specialist','متخصص ضرائب غير مباشرة','Review the draft VAT return against the ledger and the pasted rules','راجع مسودة إقرار القيمة المضافة مقابل الدفاتر والقواعد الملصوقة','- Country: [Egypt / KSA / UAE]\n- Draft return: [attach]\n- Sales and purchase ledgers: [attach]','- البلد: [مصر / السعودية / الإمارات]\n- مسودة الإقرار: [ارفع]\n- دفاتر المبيعات والمشتريات: [ارفع]','The return is filed this week','الإقرار هيتقدم الأسبوع ده','- Every box reconciled to the ledgers or the difference explained\n- Unusual items (exempt, zero-rated, reverse charge) listed','- كل خانة متطابقة مع الدفاتر أو الفرق متشرح\n- البنود غير العادية (معفى، صفري، احتساب عكسي) متسجلة','Reconciliation table + exceptions + questions for the tax adviser.','جدول المطابقة + الاستثناءات + أسئلة للمستشار الضريبي.'),
REG('KSA e-invoicing readiness (ZATCA)','جاهزية الفوترة الإلكترونية في السعودية (هيئة الزكاة والضريبة والجمارك)','E-invoicing consultant in Saudi Arabia','مستشار فوترة إلكترونية في السعودية','Check our invoices and process against the pasted ZATCA e-invoicing requirements','راجع فواتيرنا وطريقة شغلنا مقابل متطلبات الفوترة الإلكترونية الملصوقة من الهيئة','- Invoice samples: [attach]\n- ERP / billing system: [name]','- نماذج فواتير: [ارفع]\n- نظام ERP / الفوترة: [الاسم]','We must avoid rejected invoices and penalties','لازم نتفادى رفض الفواتير والغرامات','- Each required field checked on each sample\n- Process gaps separated from data gaps','- كل حقل مطلوب متراجع في كل نموذج\n- فجوات العملية منفصلة عن فجوات البيانات','Field checklist per invoice + gap list + next steps.','قائمة الحقول لكل فاتورة + قائمة الفجوات + الخطوات الجاية.'),
REG('Zakat computation review (KSA)','مراجعة حساب الزكاة (السعودية)','Zakat specialist','متخصص زكاة','Review our draft zakat base computation against the pasted rules','راجع مسودة حساب وعاء الزكاة مقابل القواعد الملصوقة','- Draft computation: [attach]\n- Financial statements: [attach]','- مسودة الحساب: [ارفع]\n- القوائم المالية: [ارفع]','The computation supports the annual filing','الحساب ده أساس الإقرار السنوي','- Each addition and deduction tied to the statements and a pasted rule\n- Judgement areas listed for the adviser','- كل إضافة وخصم مربوط بالقوائم وبقاعدة ملصوقة\n- المناطق اللي محتاجة حكم متسجلة للمستشار','Review table + list of judgement areas.','جدول المراجعة + قائمة المناطق اللي محتاجة حكم.'),
REG('UAE corporate tax readiness','جاهزية ضريبة الشركات في الإمارات','UAE corporate tax adviser','مستشار ضريبة شركات في الإمارات','Map our group structure and income against the pasted corporate tax rules','طابق هيكل المجموعة والدخل بتاعنا مع قواعد ضريبة الشركات الملصوقة','- Group entities and activities: [list]\n- Free zone status: [..]\n- Latest financials: [attach]','- كيانات المجموعة وأنشطتها: [القائمة]\n- وضع المنطقة الحرة: [..]\n- آخر قوائم مالية: [ارفع]','The board wants a readiness view before the next filing','المجلس عايز صورة الجاهزية قبل الإقرار الجاي','- Each entity’s likely treatment with the clause relied on\n- Registration and record-keeping actions listed','- المعاملة المتوقعة لكل كيان بالبند المعتمد عليه\n- إجراءات التسجيل وحفظ السجلات متسجلة','Entity table + action list + adviser questions.','جدول الكيانات + قائمة الإجراءات + أسئلة للمستشار.'),
REG('HR policy vs labour law (Egypt / KSA / UAE)','سياسة الموارد البشرية مقابل قانون العمل (مصر / السعودية / الإمارات)','HR compliance specialist','متخصص امتثال موارد بشرية','Compare our HR policy with the pasted labour law articles','قارن سياسة الموارد البشرية بتاعتنا بمواد قانون العمل الملصوقة','- Country: [..]\n- Our policy sections: leave, working hours, end of service, termination [attach]','- البلد: [..]\n- أجزاء سياستنا: الإجازات، ساعات العمل، نهاية الخدمة، إنهاء العقد [ارفع]','We must fix gaps before the policy is re-issued','لازم نصلّح الفجوات قبل ما السياسة تتعاد إصدارها','- Each policy clause compared with the pasted article\n- Clauses less favourable than the law flagged first','- كل بند في السياسة متقارن بالمادة الملصوقة\n- البنود الأقل من القانون متعلّمة الأول','Gap table + redline suggestions.','جدول الفجوات + اقتراحات التعديل.'),
REG('Central bank circular impact memo (CBE / SAMA / CBUAE)','مذكرة أثر منشور البنك المركزي (المصري / ساما / الإماراتي)','Bank compliance officer','مسؤول امتثال في بنك','Summarise the pasted circular and assess its impact on our products and processes','لخّص المنشور الملصوق وقيّم أثره على منتجاتنا وعملياتنا','- Circular: [paste, number, date]\n- Affected products and policies: [list or attach]','- المنشور: [الصق، الرقم، التاريخ]\n- المنتجات والسياسات المتأثرة: [قائمة أو ارفع]','The compliance committee assigns owners and deadlines','لجنة الامتثال هتحدد مسؤولين ومواعيد','- Every requirement quoted with its paragraph\n- Impact per product: none / change / new control\n- Effective dates taken from the text only','- كل متطلب مقتبس بالفقرة\n- الأثر لكل منتج: مفيش / تعديل / ضابط جديد\n- مواعيد السريان من النص بس','One-page memo + impact table + owner list.','مذكرة صفحة + جدول الأثر + قائمة المسؤولين.'),
REG('Personal data protection check (Egypt / KSA / UAE)','مراجعة حماية البيانات الشخصية (مصر / السعودية / الإمارات)','Data protection officer','مسؤول حماية بيانات','Check a planned AI use case against the pasted data protection law','راجع حالة استخدام AI مخططة مقابل قانون حماية البيانات الملصوق','- Use case: [describe data, purpose, who sees it]\n- Claude plan and data settings we use: [describe]','- حالة الاستخدام: [اوصف البيانات والغرض ومين بيشوفها]\n- خطة Claude وإعدادات البيانات اللي بنستخدمها: [اوصف]','The use case needs approval before launch','حالة الاستخدام محتاجة موافقة قبل الإطلاق','- Lawful basis, consent, retention and cross-border points checked against the text\n- Controls proposed for each risk','- الأساس القانوني والموافقة والاحتفاظ ونقل البيانات للخارج متراجعين مقابل النص\n- ضوابط مقترحة لكل خطر','Assessment table + required controls + approval questions.','جدول التقييم + الضوابط المطلوبة + أسئلة الموافقة.')];
DAYS[8].units.push({id:"9.6",tag:"practical",dur:"40",t:T("Egypt & GCC regulations pack","حزمة لوائح مصر والخليج"),
body:T(`<p>Tax and regulatory rules change often, so never ask Claude to recall them from memory. These eight master prompts are templates: you paste the <b>current official text</b> (law, executive regulation, circular or authority guide), and Claude compares your documents and processes against that text only, cites the article numbers, and flags anything the text does not cover.</p><ul><li>Egypt: Egyptian Tax Authority e-invoice and e-receipt, VAT, labour law, Central Bank of Egypt circulars, personal data protection.</li><li>Saudi Arabia: ZATCA e-invoicing, zakat, VAT, SAMA circulars, labour law, personal data protection.</li><li>UAE: VAT and corporate tax (Federal Tax Authority), CBUAE circulars, labour law, personal data protection.</li></ul><p>The output is a working paper for your tax, legal or compliance adviser — not advice.</p>`,
`<p>قواعد الضرايب واللوائح بتتغير كتير، فعمرك ما تطلب من Claude يفتكرها من دماغه. البرومبتات الماستر التمانية دي قوالب: بتلصق <b>النص الرسمي الحالي</b> (القانون، اللائحة التنفيذية، المنشور، أو دليل الجهة)، وClaude بيقارن مستنداتك وعملياتك بالنص ده بس، وبيذكر أرقام المواد، وبيعلّم أي حاجة النص مش مغطيها.</p><ul><li>مصر: الفاتورة والإيصال الإلكتروني في مصلحة الضرائب، القيمة المضافة، قانون العمل، منشورات البنك المركزي المصري، حماية البيانات الشخصية.</li><li>السعودية: الفوترة الإلكترونية في هيئة الزكاة والضريبة والجمارك، الزكاة، القيمة المضافة، منشورات ساما، نظام العمل، حماية البيانات الشخصية.</li><li>الإمارات: القيمة المضافة وضريبة الشركات (الهيئة الاتحادية للضرائب)، منشورات المصرف المركزي، قانون العمل، حماية البيانات الشخصية.</li></ul><p>الناتج ورقة عمل لمستشارك الضريبي أو القانوني أو الامتثال — مش استشارة.</p>`),
steps:T(["Download the current official text from the authority","Paste it with your documents","Run the matching master prompt","Review gaps and judgement areas","Send to your adviser with the sources"],["نزّل النص الرسمي الحالي من الجهة","الصقه مع مستنداتك","شغّل البرومبت الماستر المناسب","راجع الفجوات والمناطق اللي محتاجة حكم","ابعته لمستشارك مع المصادر"]),
tips:T(["Keep the official texts in a Project and note the version date on each.","Ask Claude to quote, not paraphrase, every requirement it relies on."],["حط النصوص الرسمية في Project واكتب تاريخ الإصدار على كل واحد.","اطلب من Claude يقتبس، مش يعيد صياغة، كل متطلب بيعتمد عليه."]),
cases:[{t:T("E-invoice readiness in two weeks","جاهزية الفاتورة الإلكترونية في أسبوعين"),d:T("A distributor pasted the authority’s current guide and 20 sample invoices. Claude mapped every required field and found 3 missing data points in the ERP; the IT team fixed them before the go-live date.","موزع لصق الدليل الحالي للجهة و20 فاتورة نموذجية. Claude طابق كل حقل مطلوب ولقى 3 بيانات ناقصة في الـ ERP؛ وفريق IT صلّحهم قبل ميعاد التشغيل.")}],
prompts:REGS,doc:""});
FEAT["9.6"]="E-invoicing, VAT/zakat, labour law, circulars, data protection";CEO["9.6"]=T("Pasting the official text keeps AI-assisted compliance current and auditable.","لصق النص الرسمي بيخلي الامتثال بمساعدة الـ AI محدّث وقابل للمراجعة.");

// ---------- Module 11: Family business & SMEs ----------
DAYS.push({n:11,icon:'🏪',t:T("Family business & SMEs","الشركات العائلية والصغيرة"),sub:T("Practical Claude for small teams without IT support — from setup to cash, governance and sales.","Claude عملي للفرق الصغيرة اللي ملهاش IT — من الإعداد للكاش والحوكمة والمبيعات."),units:[
{id:"11.1",tag:"core",dur:"35",t:T("Claude for a small team without IT","Claude لفريق صغير من غير IT"),
body:T(`<p>A small team can get most of the value with a simple setup: one shared plan suitable for business data, a Project per recurring job (accounts, sales, HR), a short list of approved uses, and one person who owns templates. Write a one-page AI policy: what data may go in, who reviews outputs before they leave the company, and where prompts are saved.</p><ol><li>Pick the plan that fits your team size and data rules.</li><li>Create 3 Projects for your most repeated jobs.</li><li>Save the best prompts as templates or Skills.</li><li>Review once a month: what saved time, what went wrong.</li></ol>`,
`<p>الفريق الصغير يقدر ياخد أغلب القيمة بإعداد بسيط: خطة مشتركة مناسبة لبيانات الشغل، Project لكل شغلانة متكررة (الحسابات، المبيعات، الموارد البشرية)، قائمة قصيرة بالاستخدامات المسموحة، وشخص واحد مسؤول عن القوالب. اكتب سياسة AI في صفحة: إيه البيانات المسموح تدخل، مين يراجع المخرجات قبل ما تخرج من الشركة، والبرومبتات بتتحفظ فين.</p><ol><li>اختار الخطة المناسبة لحجم الفريق وقواعد البيانات.</li><li>اعمل 3 Projects لأكتر شغلانات بتتكرر.</li><li>احفظ أحسن البرومبتات كقوالب أو Skills.</li><li>راجع مرة في الشهر: إيه اللي وفّر وقت، وإيه اللي غلط.</li></ol>`),
steps:T(["Choose the plan","Write a one-page AI policy","Create 3 Projects","Name a template owner","Monthly review"],["اختار الخطة","اكتب سياسة AI في صفحة","اعمل 3 Projects","حدد مسؤول القوالب","مراجعة شهرية"]),
tips:T(["Start with one job that wastes the most time every week.","Keep customer and salary data out until the policy is agreed."],["ابدأ بشغلانة واحدة بتضيّع أكبر وقت كل أسبوع.","خلي بيانات العملاء والمرتبات برا لحد ما السياسة تتفق عليها."]),
cases:[{t:T("A 12-person trading company","شركة تجارة فيها 12 شخص"),d:T("The owner set up three Projects (quotations, collections, supplier emails) and a one-page policy. After two months the team estimated 9 hours saved per week, mostly on quotations.","صاحب الشركة عمل 3 Projects (عروض الأسعار، التحصيل، إيميلات الموردين) وسياسة في صفحة. بعد شهرين الفريق قدّر توفير 9 ساعات في الأسبوع، أغلبها في عروض الأسعار.")}],
prompts:[PR("Master prompt — one-page AI policy for a small team","البرومبت الماستر — سياسة AI في صفحة لفريق صغير",["Operations manager for a small [industry] company in [country]","Draft a one-page AI use policy for our team of [N] people","- Tools: Claude [plan]\n- Data we handle: [customers, prices, salaries, ..]\n- Who approves external documents: [..]","Staff need clear, simple rules they will actually follow","- Allowed, not allowed, needs approval — each with examples\n- Who reviews outputs and where prompts are saved\n- Plain language, no legal jargon","One page in [Arabic/English] with three sections + a 5-line summary for WhatsApp."],["مدير عمليات في شركة [المجال] صغيرة في [البلد]","اكتب سياسة استخدام AI في صفحة لفريقنا اللي فيه [العدد] شخص","- الأدوات: Claude [الخطة]\n- البيانات اللي بنتعامل معاها: [عملاء، أسعار، مرتبات، ..]\n- مين يعتمد المستندات الخارجية: [..]","الموظفين محتاجين قواعد بسيطة وواضحة هيمشوا عليها فعلاً","- مسموح، ممنوع، محتاج موافقة — كل واحد بأمثلة\n- مين يراجع المخرجات والبرومبتات بتتحفظ فين\n- لغة بسيطة من غير مصطلحات قانونية","صفحة بالـ [عربي/إنجليزي] فيها 3 أجزاء + ملخص 5 سطور للواتساب."])],doc:""},
{id:"11.2",tag:"practical",dur:"40",t:T("Family business governance","حوكمة الشركات العائلية"),
body:T(`<p>Family businesses often run on trust and memory. Claude can help turn that into documents the family can discuss: a family charter draft, board meeting agendas and minutes, a conflict-of-interest register, a succession plan outline and role descriptions for family members. The family and its advisers decide; Claude drafts options, asks the right questions and keeps the language neutral.</p>`,
`<p>الشركات العائلية غالباً ماشية بالثقة والذاكرة. Claude يقدر يساعد يحوّل ده لمستندات العيلة تتناقش فيها: مسودة ميثاق عائلي، جداول أعمال ومحاضر اجتماعات مجلس الإدارة، سجل تعارض المصالح، إطار خطة التعاقب، ووصف أدوار لأفراد العيلة. القرار للعيلة ومستشاريها؛ وClaude بيكتب اختيارات، ويسأل الأسئلة الصح، ويخلي اللغة محايدة.</p>`),
steps:T(["List decisions the family argues about","Draft the charter sections as options","Set a board calendar and minutes template","Outline succession with criteria","Review with an adviser"],["اكتب القرارات اللي العيلة بتختلف عليها","اكتب أجزاء الميثاق كاختيارات","اعمل جدول اجتماعات وقالب محضر","حط إطار التعاقب بمعايير","راجع مع مستشار"]),
tips:T(["Ask for options with pros and cons, not one answer — it keeps discussions calm.","Never put private family disputes in a shared Project."],["اطلب اختيارات بمميزات وعيوب، مش إجابة واحدة — ده بيهدّي النقاش.","عمرك ما تحط خلافات عائلية خاصة في Project مشترك."]),
cases:[{t:T("Second-generation handover","التسليم للجيل التاني"),d:T("A manufacturing family used Claude to draft three succession options with criteria (experience, performance, family vote). The family chose a hybrid and an external adviser finalised the charter.","عيلة صاحبة مصنع استخدمت Claude تكتب 3 اختيارات للتعاقب بمعايير (الخبرة، الأداء، تصويت العيلة). العيلة اختارت مزيج ومستشار خارجي قفل الميثاق.")}],
prompts:[PR("Master prompt — family charter options","البرومبت الماستر — اختيارات الميثاق العائلي",["Family business governance adviser","Draft options for the key sections of our family charter","- Business: [industry, size, generations involved]\n- Topics: family employment, dividends, decision rights, conflict resolution, succession\n- What the family already agrees on: [..]","The family will discuss the options at its next meeting","- 2–3 options per topic with pros and cons\n- Neutral language; no option presented as the right one\n- Questions the family must answer listed","Options document by topic + discussion questions."],["مستشار حوكمة شركات عائلية","اكتب اختيارات لأهم أجزاء الميثاق العائلي بتاعنا","- الشغل: [المجال، الحجم، الأجيال المشاركة]\n- المواضيع: توظيف أفراد العيلة، الأرباح، صلاحيات القرار، حل الخلافات، التعاقب\n- اللي العيلة متفقة عليه: [..]","العيلة هتناقش الاختيارات في الاجتماع الجاي","- 2–3 اختيارات لكل موضوع بمميزات وعيوب\n- لغة محايدة؛ ومفيش اختيار متقدم إنه الصح\n- الأسئلة اللي العيلة لازم تجاوبها متسجلة","مستند اختيارات حسب الموضوع + أسئلة للنقاش."])],doc:""},
{id:"11.3",tag:"practical",dur:"40",t:T("SME money: cash, invoices and pricing","فلوس الشركات الصغيرة: الكاش والفواتير والتسعير"),
body:T(`<p>Cash is the first problem in most small companies. Use Claude for a simple 13-week cash view from your bank statement and open invoices, polite collection messages by customer type, and a pricing check that compares your margins after discounts. Keep the numbers in a spreadsheet you own; ask Claude to explain, flag and draft — and check every figure before you act.</p>`,
`<p>الكاش هو أول مشكلة في أغلب الشركات الصغيرة. استخدم Claude لنظرة كاش 13 أسبوع بسيطة من كشف البنك والفواتير المفتوحة، ورسايل تحصيل محترمة حسب نوع العميل، ومراجعة تسعير بتقارن الهامش بعد الخصومات. خلي الأرقام في شيت إنت مسؤول عنه؛ واطلب من Claude يشرح ويعلّم ويكتب — وراجع كل رقم قبل ما تتصرف.</p>`),
steps:T(["Export bank and open invoices","Build the 13-week view","Rank customers to chase","Draft collection messages","Check prices and discounts"],["صدّر البنك والفواتير المفتوحة","اعمل نظرة الـ 13 أسبوع","رتّب العملاء اللي هتحصّل منهم","اكتب رسايل التحصيل","راجع الأسعار والخصومات"]),
tips:T(["Ask for the week the cash goes lowest — that is the decision point.","Send collection messages yourself; let Claude draft them."],["اسأل عن الأسبوع اللي الكاش بيوصل فيه لأقل حاجة — ده وقت القرار.","ابعت رسايل التحصيل بنفسك؛ وخلي Claude يكتبها."]),
cases:[{t:T("A café chain avoids a cash gap","سلسلة كافيهات بتتفادى عجز كاش"),d:T("A 4-branch café chain built a 13-week view in an hour and saw a gap in week 7 caused by rent and an equipment payment. They moved the equipment payment by three weeks with the supplier’s agreement.","سلسلة كافيهات فيها 4 فروع عملت نظرة 13 أسبوع في ساعة وشافت عجز في الأسبوع 7 بسبب الإيجار وقسط معدات. أجّلوا قسط المعدات 3 أسابيع بموافقة المورد.")}],
prompts:[PR("Master prompt — 13-week cash view for a small business","البرومبت الماستر — نظرة كاش 13 أسبوع لشركة صغيرة",["Finance adviser to small businesses in [country]","Build a simple 13-week cash view from my bank balance, open invoices and fixed payments","- Opening bank balance: [EGP]\n- Open customer invoices: [attach]\n- Fixed payments (rent, salaries, loans): [list with dates]\n- Expected sales per week: [..]","I need to see early if I will run short of cash","- Weekly in, out and closing balance\n- Lowest week highlighted with the cause\n- Assumptions listed; nothing invented","Week-by-week table + 3 actions to protect cash, in [Arabic/English]."],["مستشار مالي للشركات الصغيرة في [البلد]","اعمل نظرة كاش بسيطة لـ 13 أسبوع من رصيد البنك والفواتير المفتوحة والمدفوعات الثابتة","- رصيد البنك الافتتاحي: [جنيه]\n- فواتير العملاء المفتوحة: [ارفع]\n- المدفوعات الثابتة (إيجار، مرتبات، قروض): [قائمة بالمواعيد]\n- المبيعات المتوقعة في الأسبوع: [..]","محتاج أشوف بدري لو الكاش هيخلص","- الداخل والخارج والرصيد كل أسبوع\n- أقل أسبوع متعلّم بالسبب\n- الافتراضات متسجلة؛ ومفيش حاجة متألفة","جدول أسبوع بأسبوع + 3 إجراءات تحمي الكاش، بالـ [عربي/إنجليزي]."])],doc:""},
{id:"11.4",tag:"practical",dur:"35",t:T("Selling and marketing on a small budget","البيع والتسويق بميزانية صغيرة"),
body:T(`<p>Small businesses sell through WhatsApp, Instagram, Facebook and word of mouth. Claude can draft product descriptions for your catalogue, a month of social posts in your customers’ dialect, quick replies to common questions, and simple offers you can test. Give it your real products, prices and customer questions, and ask for short texts you can post as they are — then track which ones bring orders.</p>`,
`<p>الشركات الصغيرة بتبيع من خلال واتساب وإنستجرام وفيسبوك والكلام بين الناس. Claude يقدر يكتب وصف المنتجات للكتالوج، وبوستات شهر كامل بلهجة عملائك، وردود سريعة على الأسئلة المتكررة، وعروض بسيطة تجربها. اديله منتجاتك وأسعارك وأسئلة عملائك الحقيقية، واطلب نصوص قصيرة تنزلها زي ما هي — وبعدين تابع أنهي واحدة بتجيب طلبات.</p>`),
steps:T(["List products, prices and top 10 customer questions","Draft catalogue descriptions","Plan a month of posts","Write quick replies","Test one offer and track orders"],["اكتب المنتجات والأسعار وأكتر 10 أسئلة من العملاء","اكتب وصف الكتالوج","خطط لبوستات شهر","اكتب الردود السريعة","جرّب عرض واحد وتابع الطلبات"]),
tips:T(["Ask for 3 versions of each post and keep the one that sounds like you.","Never promise delivery times or prices you have not confirmed."],["اطلب 3 نسخ من كل بوست وخد اللي شبهك.","عمرك ما توعد بمواعيد توصيل أو أسعار مش متأكد منها."]),
cases:[{t:T("A home bakery doubles repeat orders","مخبز بيتي بيضاعف الطلبات المتكررة"),d:T("A home bakery in Alexandria used Claude for weekly posts and quick replies in Egyptian Arabic. Repeat orders rose from 20 to 41 a month over three months, tracked in a simple sheet.","مخبز بيتي في إسكندرية استخدم Claude لبوستات أسبوعية وردود سريعة بالمصري. الطلبات المتكررة زادت من 20 لـ 41 في الشهر خلال 3 شهور، متسجلة في شيت بسيط.")}],
prompts:[PR("Master prompt — a month of posts and quick replies","البرومبت الماستر — بوستات شهر وردود سريعة",["Social media marketer for small businesses in [city/country]","Create a 4-week post plan and 10 quick replies for my business","- Business: [what we sell, prices, area we deliver to]\n- Customers: [who they are; dialect: Egyptian / Gulf]\n- Top customer questions: [list]\n- Channels: [WhatsApp, Instagram, Facebook]","I have no marketing team and need ready-to-post texts","- 3 posts a week, each under 60 words, with one clear call to action\n- Replies polite, short, in the customers’ dialect\n- No promises on prices or delivery not in the input","Weekly table (day, channel, post text, idea for photo) + quick replies list."],["مسوّق سوشيال ميديا للشركات الصغيرة في [المدينة/البلد]","اعمل خطة بوستات 4 أسابيع و10 ردود سريعة لشغلي","- الشغل: [بنبيع إيه، الأسعار، بنوصّل فين]\n- العملاء: [مين؛ اللهجة: مصري / خليجي]\n- أكتر أسئلة العملاء: [قائمة]\n- القنوات: [واتساب، إنستجرام، فيسبوك]","معنديش فريق تسويق ومحتاج نصوص جاهزة أنزلها","- 3 بوستات في الأسبوع، كل واحد أقل من 60 كلمة، فيه طلب واضح واحد\n- الردود محترمة وقصيرة وبلهجة العملاء\n- مفيش وعود بأسعار أو توصيل مش في المدخلات","جدول أسبوعي (اليوم، القناة، نص البوست، فكرة الصورة) + قائمة الردود السريعة."])],doc:""}]});
FEAT["11.1"]="Plans, Projects, one-page policy";FEAT["11.2"]="Family charter, board, succession";FEAT["11.3"]="13-week cash, collections, pricing";FEAT["11.4"]="Catalogue, posts, quick replies";
CEO["11.1"]=T("Small teams win with a simple setup and one owner for templates.","الفرق الصغيرة بتكسب بإعداد بسيط وشخص واحد مسؤول عن القوالب.");CEO["11.2"]=T("Written options reduce family conflict and speed up decisions.","الاختيارات المكتوبة بتقلل خلافات العيلة وبتسرّع القرار.");CEO["11.3"]=T("A 13-week cash view is the cheapest early-warning system a small business can have.","نظرة الكاش 13 أسبوع أرخص نظام إنذار مبكر لأي شركة صغيرة.");CEO["11.4"]=T("Consistent, local-dialect content builds repeat customers on a small budget.","المحتوى المنتظم باللهجة المحلية بيبني عملاء متكررين بميزانية صغيرة.");
QUIZ[11]=[
Q("What is the first thing a small team should write?","إيه أول حاجة الفريق الصغير يكتبها؟",[["A 50-page AI strategy","استراتيجية AI في 50 صفحة"],["A one-page AI use policy","سياسة استخدام AI في صفحة"],["A press release","بيان صحفي"],["Nothing","ولا حاجة"]],1,"Simple rules people follow beat long documents nobody reads.","القواعد البسيطة اللي الناس بتمشي عليها أحسن من مستندات طويلة محدش بيقراها."),
Q("In family governance, what should Claude produce?","في حوكمة الشركات العائلية، Claude يطلّع إيه؟",[["The final decision","القرار النهائي"],["Options with pros and cons for the family to decide","اختيارات بمميزات وعيوب والعيلة تقرر"],["A legal judgement","حكم قانوني"],["A vote result","نتيجة تصويت"]],1,"The family and its advisers decide.","العيلة ومستشاريها هما اللي بيقرروا."),
Q("In a 13-week cash view, which week matters most?","في نظرة الكاش 13 أسبوع، أنهي أسبوع أهم؟",[["The first","الأول"],["The week with the lowest closing balance","الأسبوع اللي فيه أقل رصيد"],["The last","الأخير"],["Any week","أي أسبوع"]],1,"That is when you must act.","ده الوقت اللي لازم تتصرف فيه."),
Q("Who should send collection messages?","مين يبعت رسايل التحصيل؟",[["Claude automatically","Claude لوحده"],["You, after reviewing Claude’s draft","إنت بعد ما تراجع مسودة Claude"],["Nobody","محدش"],["The customer","العميل"]],1,"Claude drafts; you send.","Claude يكتب؛ وإنت تبعت."),
Q("What makes small-business posts work?","إيه اللي بيخلي بوستات الشركات الصغيرة تنجح؟",[["Long formal Arabic","فصحى طويلة"],["Short texts in the customers’ dialect with one call to action","نصوص قصيرة بلهجة العملاء وفيها طلب واحد واضح"],["Many hashtags","هاشتاجات كتير"],["Prices you have not confirmed","أسعار مش متأكد منها"]],1,"Short, local and clear.","قصير ومحلي وواضح.")];

// ---------- 12. Module projects ----------
const PJ=(n,ten,tar,ben,bar,den,dar,rub)=>({n,t:T(ten,tar),brief:T(ben,bar),deliv:T(den,dar),rub:rub.map(r=>({k:r[0],t:T(r[1],r[2])}))});
const PROJECTS=[
PJ(1,'Your master prompt library','مكتبة البرومبتات الماستر بتاعتك','Write three master prompts for real tasks from your own job, using all six blocks and the controls.','اكتب 3 برومبتات ماستر لمهام حقيقية من شغلك، بالبلوكات الستة والضوابط.','Paste the three prompts and one line each on the task they serve.','الصق التلات برومبتات وسطر لكل واحد عن المهمة اللي بيخدمها.',[['blocks','All six blocks specific to a real task','البلوكات الستة محددة لمهمة حقيقية'],['context','Context has real facts, period, currency, files','السياق فيه حقايق وفترة وعملة وملفات'],['stop','Stop conditions are checkable','شروط التوقف قابلة للمراجعة'],['controls','Accuracy controls (ask first, verify, label assumptions)','ضوابط الدقة (اسأل الأول، راجع، علّم الافتراضات)']]),
PJ(2,'A working Project','Project شغال','Design a Project for one recurring job: instructions, knowledge files and a first test.','صمّم Project لشغلانة متكررة: التعليمات، ملفات المعرفة، وأول اختبار.','Paste the project instructions, the list of knowledge files and what the first test produced.','الصق تعليمات الـ Project وقائمة ملفات المعرفة وناتج أول اختبار.',[['scope','Clear scope and audience','نطاق وجمهور واضحين'],['instructions','Instructions are specific and reusable','التعليمات محددة وقابلة للتكرار'],['knowledge','Knowledge files are stable references, not one-offs','ملفات المعرفة مراجع ثابتة مش حاجات لمرة واحدة'],['test','The test shows the Project works','الاختبار بيثبت إن الـ Project شغال']]),
PJ(3,'A real deliverable','مخرج حقيقي','Produce one deliverable your manager would use: a memo, slides, a document or an artifact.','اعمل مخرج واحد مديرك هيستخدمه: مذكرة أو عرض أو مستند أو artifact.','Describe the deliverable, paste the prompt and the key part of the output, and add a link if you have one.','اوصف المخرج، والصق البرومبت وأهم جزء من الناتج، وضيف لينك لو موجود.',[['fit','Fits a real audience and decision','مناسب لجمهور وقرار حقيقي'],['quality','Clear structure and accurate content','هيكل واضح ومحتوى دقيق'],['prompt','Prompt names format, audience and limits','البرومبت بيحدد الشكل والجمهور والحدود'],['review','Shows how you checked it','بيوضح إزاي راجعته']]),
PJ(4,'Your first Skill','أول Skill ليك','Write a Skill for a method your team repeats, and test it on two different inputs.','اكتب Skill لطريقة فريقك بيكررها، واختبرها على مدخلين مختلفين.','Paste the SKILL.md content and a short note on both tests.','الصق محتوى SKILL.md وملاحظة قصيرة عن الاختبارين.',[['trigger','Name and description say when to use it','الاسم والوصف بيقولوا تستخدمها امتى'],['method','Step-by-step method and output template','طريقة خطوة بخطوة وقالب مخرج'],['edge','Handles missing or messy inputs','بتتعامل مع المدخلات الناقصة أو المتلخبطة'],['tested','Tested on two inputs with results noted','متجربة على مدخلين والنتايج متسجلة']]),
PJ(5,'Claude where you work','Claude في مكان شغلك','Use Claude inside Excel, PowerPoint, Word, Chrome or Slack on one real task.','استخدم Claude جوه Excel أو PowerPoint أو Word أو Chrome أو Slack في مهمة حقيقية.','Name the tool, paste the prompt, and describe the before and after.','سمّي الأداة، والصق البرومبت، واوصف قبل وبعد.',[['tool','Right tool for the task','الأداة المناسبة للمهمة'],['prompt','Prompt adapted to the tool','البرومبت متكيّف للأداة'],['result','Measurable result (time, errors, quality)','نتيجة قابلة للقياس (وقت، أخطاء، جودة)'],['check','Output checked before use','المخرج اتراجع قبل الاستخدام']]),
PJ(6,'A Cowork brief','تكليف Cowork','Write a Cowork brief for a multi-step job with clear limits and a review point.','اكتب تكليف Cowork لشغلانة متعددة الخطوات بحدود واضحة ونقطة مراجعة.','Paste the brief and describe what Cowork produced and what you changed.','الصق التكليف واوصف Cowork طلّع إيه وإنت غيرت إيه.',[['steps','Steps and files are explicit','الخطوات والملفات واضحة'],['limits','Limits: what not to send, change or delete','الحدود: اللي ميتبعتش أو يتغير أو يتمسح'],['review','A human review point before anything leaves','نقطة مراجعة بشرية قبل ما أي حاجة تخرج'],['log','Asks for a log of actions','بيطلب سجل بالإجراءات']]),
PJ(7,'A small build','بناء صغير','Build a small tool with Claude Code or the API: a script, an artifact or an integration.','ابني أداة صغيرة بـ Claude Code أو الـ API: سكريبت أو artifact أو ربط.','Describe what it does, paste the key prompt or system prompt, and link it if possible.','اوصف بتعمل إيه، والصق البرومبت أو الـ System prompt الأساسي، وحط لينك لو ممكن.',[['problem','Solves a real problem','بتحل مشكلة حقيقية'],['spec','Clear spec and structured output','مواصفات واضحة ومخرج منظم'],['safety','Handles errors and data safely','بتتعامل مع الأخطاء والبيانات بأمان'],['demo','Shows it working','بتوضح إنها شغالة']]),
PJ(8,'Capstone and 90-day plan','المشروع الختامي وخطة 90 يوم','Pick one use case for your team, show a pilot result and write a 90-day rollout plan.','اختار حالة استخدام لفريقك، ووري نتيجة تجربة، واكتب خطة تطبيق 90 يوم.','Paste the use case, the pilot result and the plan.','الصق حالة الاستخدام ونتيجة التجربة والخطة.',[['value','Clear business value with numbers','قيمة بيزنس واضحة بالأرقام'],['pilot','Pilot evidence','دليل من التجربة'],['plan','Realistic 90-day plan with owners','خطة 90 يوم واقعية بمسؤولين'],['risk','Risks and controls named','المخاطر والضوابط متحددة']]),
PJ(9,'An AI governance pack','ملف حوكمة AI','Write the AI policy, a use-case register entry and a review checklist for one use case.','اكتب سياسة الـ AI، وقيد في سجل حالات الاستخدام، وقائمة مراجعة لحالة واحدة.','Paste the three items.','الصق التلات حاجات.',[['policy','Policy is clear and enforceable','السياسة واضحة وقابلة للتطبيق'],['register','Register entry has owner, data and risk tier','قيد السجل فيه المسؤول والبيانات ومستوى الخطر'],['checklist','Checklist is practical','قائمة المراجعة عملية'],['law','Data protection and sector rules considered','حماية البيانات وقواعد القطاع متراعية']]),
PJ(10,'An Arabic content set','مجموعة محتوى عربي','Produce one Arabic piece in MSA and one in dialect, plus a translation with a glossary and a QA review.','اعمل قطعة عربي فصحى وقطعة بلهجة، وترجمة بقاموس ومراجعة جودة.','Paste the texts, the glossary used and the QA issues table.','الصق النصوص والقاموس المستخدم وجدول مشاكل المراجعة.',[['register','Correct register and dialect','المستوى واللهجة صح'],['terms','Glossary followed; terms consistent','القاموس متبع؛ والمصطلحات ثابتة'],['qa','QA checklist applied','قائمة المراجعة متطبقة'],['native','Reads naturally for the audience','بيتقري طبيعي للجمهور']]),
PJ(11,'A small-business toolkit','عدة شغل لشركة صغيرة','Set up Claude for a small business: policy, one Project, a 13-week cash view and a month of posts.','جهّز Claude لشركة صغيرة: سياسة، Project واحد، نظرة كاش 13 أسبوع، وبوستات شهر.','Paste the policy, the project instructions, the cash table summary and three sample posts.','الصق السياسة، وتعليمات الـ Project، وملخص جدول الكاش، و3 بوستات نموذجية.',[['setup','Simple, safe setup','إعداد بسيط وآمن'],['cash','Cash view finds the lowest week','نظرة الكاش بتلاقي أقل أسبوع'],['sales','Posts fit the customers and channel','البوستات مناسبة للعملاء والقناة'],['owner','Clear owner and review routine','مسؤول واضح وروتين مراجعة']])];
