// ===== CURRICULUM 4: Module 10 (Arabic content), 1.9 prompt failures clinic, 9.5 audit & compliance =====
const U4=(o)=>Object.assign({cases:[],prompts:[],doc:'',tips:T([],[])},o);

// ---------- 1.9 Prompt failures clinic ----------
const FAILS=[
[T('Made-up numbers','أرقام متألفة'),T('Totals or ratios that are not in the file','إجماليات أو نسب مش موجودة في الملف'),T('The prompt asked for analysis but never said “only use the attached data”','البرومبت طلب تحليل ومقالش "استخدم البيانات المرفقة بس"'),T('Add: “Use only the attached file. Cite the sheet and row for every number. If a figure is missing, write MISSING.”','ضيف: "استخدم الملف المرفق بس. اذكر الشيت والصف لكل رقم. ولو رقم ناقص اكتب ناقص."')],
[T('Missed constraint','قيد اتنسى'),T('The answer is 900 words when you asked for 200','الرد 900 كلمة وإنت طالب 200'),T('The limit was buried in the middle of a long paragraph','الحد كان مدفون في نص فقرة طويلة'),T('Put limits in <stop_when> as a checklist and repeat the hardest one in <output_format>.','حط الحدود في <stop_when> كقائمة وكرر أصعب واحد في <output_format>.')],
[T('Wrong format','شكل غلط'),T('Prose when you needed a table, or JSON that will not parse','كلام إنشائي وإنت محتاج جدول، أو JSON مش بيتقري'),T('No example of the exact shape','مفيش مثال للشكل بالظبط'),T('Show one example row or a JSON skeleton and say “return only this shape”.','ورّي صف مثال أو هيكل JSON وقول «رجّع الشكل ده بس».')],
[T('Ignored part of the file','تجاهل جزء من الملف'),T('The summary covers pages 1–10 of a 40-page contract','الملخص غطّى صفحات 1–10 من عقد 40 صفحة'),T('The question came before the document, or the task never said “every section”','السؤال جه قبل المستند، أو المهمة مقالتش "كل الأجزاء"'),T('Put long documents first and the question last; ask for a list of every section with one line each before the summary.','حط المستندات الطويلة الأول والسؤال في الآخر؛ واطلب قائمة بكل جزء بسطر قبل الملخص.')],
[T('Over-confident advice','نصيحة واثقة زيادة'),T('A firm legal or tax conclusion with no caveats','استنتاج قانوني أو ضريبي قاطع من غير تحفظات'),T('The prompt asked for “the answer” and no human review','البرومبت طلب «الإجابة» ومفيش مراجعة بشرية'),T('Ask for options with risks, mark what needs a qualified reviewer, and list open questions.','اطلب اختيارات بمخاطرها، وعلّم اللي محتاج مراجع متخصص، واطلب قائمة بالأسئلة المفتوحة.')],
[T('Stale facts','معلومات قديمة'),T('Old prices, rates or product names stated as current','أسعار أو نسب أو أسماء منتجات قديمة متقالة كأنها حالية'),T('Date-sensitive facts with no date or source','معلومات مرتبطة بتاريخ من غير تاريخ أو مصدر'),T('Give the date and the source, or ask Claude to search and cite; label anything it cannot confirm.','اديله التاريخ والمصدر، أو اطلب منه يبحث ويذكر المصدر؛ وعلّم أي حاجة مش متأكد منها.')],
[T('Language drift','اللغة بتتغير'),T('You asked in Arabic and got English halfway through','سألت بالعربي والرد اتحول إنجليزي في النص'),T('Language and dialect were never stated; the files were in English','اللغة واللهجة متحددوش؛ والملفات كانت إنجليزي'),T('State language, dialect and which terms stay in English in <output_format>.','حدد اللغة واللهجة والمصطلحات اللي تفضل إنجليزي في <output_format>.')]];
DAYS[0].units.push(U4({id:"1.9",tag:"critical",dur:"30",t:T("Prompt failures clinic","عيادة أخطاء البرومبت"),
body:T(`<p>Most bad answers come from a handful of prompt mistakes. Learn to recognise the symptom, find the cause in the prompt, and apply the fix — then practise in <a href="#rescue">Prompt rescue</a> and <a href="#spot">Spot the hallucination</a>.</p><div class="tablewrap"><table><tr><th>Failure</th><th>Symptom</th><th>Cause in the prompt</th><th>Fix</th></tr>${FAILS.map(f=>`<tr><td><b>${f[0].en}</b></td><td>${f[1].en}</td><td>${f[2].en}</td><td>${f[3].en.replace(/</g,'&lt;')}</td></tr>`).join('')}</table></div><p>Rule of thumb: when an answer is wrong, change the prompt before you change the model.</p>`,
`<p>أغلب الردود الوحشة جاية من شوية أخطاء معروفة في البرومبت. اتعلم تعرف العَرَض، وتلاقي السبب في البرومبت، وتطبّق العلاج — وبعدين اتمرن في <a href="#rescue">إنقاذ البرومبت</a> و<a href="#spot">اكتشف الهلوسة</a>.</p><div class="tablewrap"><table><tr><th>الخطأ</th><th>العَرَض</th><th>السبب في البرومبت</th><th>العلاج</th></tr>${FAILS.map(f=>`<tr><td><b>${f[0].ar}</b></td><td>${f[1].ar}</td><td>${f[2].ar}</td><td>${f[3].ar.replace(/</g,'&lt;')}</td></tr>`).join('')}</table></div><p>القاعدة: لما الرد يطلع غلط، غيّر البرومبت قبل ما تغيّر الموديل.</p>`),
steps:T(["Copy the bad answer next to the prompt","Name the symptom from the table","Find the cause in the prompt","Apply the fix and re-run","Save the fixed prompt to your pack"],["حط الرد الغلط جنب البرومبت","سمّي العَرَض من الجدول","دوّر على السبب في البرومبت","طبّق العلاج وشغّل تاني","احفظ البرومبت المتصلّح في حزمتك"]),
tips:T(["Fix one thing at a time so you know what worked.","Keep a “failures log” — the same three mistakes usually repeat."],["صلّح حاجة واحدة كل مرة علشان تعرف إيه اللي نفع.","اعمل سجل أخطاء — غالباً نفس التلات أخطاء بيتكرروا."]),
cases:[{t:T("The 13-week cash forecast that invented a loan","توقع الكاش 13 أسبوع اللي اخترع قرض"),d:T("A treasury analyst got a forecast that included a EGP 5M facility drawdown nobody had agreed. Cause: “assume normal financing”. Fix: “use only the facilities listed in sheet Debt; flag any gap as FUNDING NEED”. The rerun showed a week-9 gap instead of hiding it.","محلل خزينة طلعله توقع فيه سحب 5 مليون جنيه من تسهيل محدش وافق عليه. السبب: «افترض تمويل طبيعي». العلاج: «استخدم التسهيلات اللي في شيت الديون بس؛ وعلّم أي عجز كاحتياج تمويل». التشغيل التاني وضّح عجز في الأسبوع 9 بدل ما يخبيه.")},
{t:T("A board summary in the wrong language","ملخص مجلس باللغة الغلط"),d:T("An Arabic board pack came back half in English because the source files were English. Adding “Arabic (MSA) for the board; keep IFRS terms in English in brackets” fixed it in one run.","ملف مجلس عربي رجع نصه إنجليزي علشان ملفات المصدر كانت إنجليزي. إضافة «عربي فصحى للمجلس؛ ومصطلحات IFRS بالإنجليزي بين قوسين» حلّها من أول مرة.")}],
prompts:[{t:T("Master prompt — diagnose a failed prompt","البرومبت الماستر — شخّص برومبت فشل"),p:T(MPen("Prompt engineer and reviewer","Diagnose why the prompt below produced a bad answer and rewrite it","- Prompt: [paste]\n- The answer I got: [paste]\n- What I expected: [..]\n- Failure types to check: made-up numbers, missed constraint, wrong format, ignored file part, over-confident advice, stale facts, language drift","I need a prompt I can reuse without checking every line","- Each failure named with the exact words in the prompt that caused it\n- Rewritten prompt in the six blocks\n- One test I can run to confirm the fix","Table of failures (symptom, cause, fix) + the rewritten prompt in a code block."),MPar("مهندس ومراجع برومبتات","شخّص ليه البرومبت اللي تحت طلّع رد وحش وأعد كتابته","- البرومبت: [الصق]\n- الرد اللي جالي: [الصق]\n- اللي كنت متوقعه: [..]\n- أنواع الأخطاء: أرقام متألفة، قيد اتنسى، شكل غلط، جزء من الملف اتجاهل، نصيحة واثقة زيادة، معلومات قديمة، اللغة اتغيرت","محتاج برومبت أعيد استخدامه من غير ما أراجع كل سطر","- كل خطأ متسمّي بالكلام اللي في البرومبت اللي سببه\n- البرومبت متكتب تاني بالبلوكات الستة\n- اختبار واحد أشغّله أتأكد إن العلاج نفع","جدول الأخطاء (العَرَض، السبب، العلاج) + البرومبت الجديد في بلوك.")),master:true}]}));
FEAT["1.9"]="Failure patterns, diagnosis, fixes";CEO["1.9"]=T("Most AI quality problems are prompt problems — a shared failures checklist cuts rework fast.","أغلب مشاكل جودة الـ AI مشاكل برومبت — قائمة أخطاء مشتركة بتقلل إعادة الشغل بسرعة.");

// ---------- 9.5 Claude for audit & compliance ----------
DAYS[8].units.push(U4({id:"9.5",tag:"advanced",dur:"45",t:T("Claude for audit and compliance","Claude للمراجعة والامتثال"),
body:T(`<p>Claude can speed up audit and compliance work — reading policies, building test worksheets, proposing samples, drafting findings — but the auditor keeps the judgement and the sign-off. Design every workflow around three things:</p><ol><li><b>Evidence trail.</b> Every statement points to a document, sheet and row. Ask Claude to quote the source and to write “NOT FOUND” rather than infer.</li><li><b>Sampling.</b> Claude can propose a risk-based sampling approach and explain it; the actual selection is done with a documented method (for example a random function in Excel) so it can be reproduced.</li><li><b>Review sign-off.</b> A named person reviews each output, records what changed, and signs off. Claude's draft is a working paper, not the conclusion.</li></ol><p>Use your organisation's approved Claude plan and data rules for client or regulated data, and keep the prompts, files and outputs with the working papers.</p>`,
`<p>Claude يقدر يسرّع شغل المراجعة والامتثال — يقرا السياسات، يبني أوراق اختبار، يقترح عينات، ويكتب مسودة الملاحظات — بس المراجع هو اللي بيحكم وبيوقّع. صمّم أي سير شغل حوالين 3 حاجات:</p><ol><li><b>أثر الأدلة.</b> كل جملة ليها مستند وشيت وصف. اطلب من Claude يقتبس المصدر ويكتب «مش موجود» بدل ما يستنتج.</li><li><b>العينات.</b> Claude يقترح منهج عينة مبني على المخاطر ويشرحه؛ أما الاختيار نفسه فبيتعمل بطريقة موثقة (زي دالة عشوائية في Excel) علشان يتكرر.</li><li><b>اعتماد المراجعة.</b> شخص محدد بيراجع كل مخرج، ويسجل اللي اتغير، ويعتمد. مسودة Claude ورقة عمل، مش الاستنتاج النهائي.</li></ol><p>استخدم خطة Claude المعتمدة في شركتك وقواعد البيانات بتاعتها مع بيانات العملاء أو البيانات الخاضعة للرقابة، واحفظ البرومبتات والملفات والمخرجات مع أوراق العمل.</p>`),
steps:T(["Load the policy or control description","Ask for a test worksheet with sources","Agree the sampling method and document it","Run tests and record exceptions","Draft findings with evidence references","Reviewer signs off and logs changes"],["ارفع السياسة أو وصف الضابط","اطلب ورقة اختبار بمصادرها","اتفق على طريقة العينة ووثّقها","نفّذ الاختبارات وسجّل الاستثناءات","اكتب مسودة الملاحظات بمراجع الأدلة","المراجع يعتمد ويسجل التعديلات"]),
tips:T(["Never let Claude select the sample from memory — reproducibility matters.","Ask for “exceptions only” on large populations, then review the full list yourself."],["متخليش Claude يختار العينة من دماغه — إمكانية التكرار مهمة.","اطلب «الاستثناءات بس» في المجتمعات الكبيرة، وبعدين راجع القائمة كاملة بنفسك."]),
cases:[{t:T("Expense claims control test","اختبار ضابط مصروفات الموظفين"),d:T("Internal audit tested 1,240 expense claims against policy. Claude built the test worksheet and flagged 37 exceptions with row references; auditors confirmed 31, rejected 6 as policy-allowed, and documented each decision. Fieldwork time fell from 5 days to 2.","المراجعة الداخلية اختبرت 1,240 مطالبة مصروفات مقابل السياسة. Claude بنى ورقة الاختبار وعلّم 37 استثناء بأرقام الصفوف؛ المراجعين أكدوا 31 ورفضوا 6 لأنهم مسموحين في السياسة، ووثّقوا كل قرار. وقت العمل الميداني نزل من 5 أيام ليومين.")},
{t:T("Regulatory circular gap analysis","تحليل فجوة لمنشور رقابي"),d:T("A compliance officer compared a new central-bank circular with the bank's KYC policy. Claude produced a clause-by-clause gap table with quotes from both documents; the officer added owners and deadlines before it went to the committee.","مسؤول امتثال قارن منشور جديد من البنك المركزي بسياسة اعرف عميلك في البنك. Claude طلّع جدول فجوات بند ببند بالاقتباسات من المستندين؛ والمسؤول ضاف المسؤولين والمواعيد قبل ما يروح للجنة.")}],
prompts:[
{t:T("Master prompt — control test worksheet","البرومبت الماستر — ورقة اختبار ضابط"),p:T(MPen("Internal auditor experienced in financial controls","Build a test worksheet for the control described below and test the attached population","- Control: [description, owner, frequency]\n- Policy: [attach]\n- Population: [file, period, number of items]\n- Materiality / thresholds: [..]","The audit committee relies on this test; it must be reproducible","- Each test step mapped to a policy clause (quoted)\n- Exceptions listed with file, sheet and row\n- No conclusion on the control — leave it for the reviewer\n- Anything unclear marked NEEDS AUDITOR JUDGEMENT","Worksheet table (step, clause, procedure, result, evidence ref) + exceptions table + open questions."),MPar("مراجع داخلي خبرة في الضوابط المالية","ابني ورقة اختبار للضابط اللي تحت واختبر المجتمع المرفق","- الضابط: [الوصف، المسؤول، التكرار]\n- السياسة: [ارفع]\n- المجتمع: [الملف، الفترة، عدد البنود]\n- الأهمية النسبية / الحدود: [..]","لجنة المراجعة بتعتمد على الاختبار ده؛ لازم يكون قابل للتكرار","- كل خطوة اختبار مربوطة ببند في السياسة (مقتبس)\n- الاستثناءات متسجلة بالملف والشيت والصف\n- من غير استنتاج عن الضابط — سيبه للمراجع\n- أي حاجة مش واضحة متعلّمة «محتاج حكم المراجع»","جدول ورقة العمل (الخطوة، البند، الإجراء، النتيجة، مرجع الدليل) + جدول الاستثناءات + الأسئلة المفتوحة.")),master:true},
{t:T("Master prompt — sampling rationale","البرومبت الماستر — مبررات العينة"),p:T(MPen("Audit methodology specialist","Propose and document a risk-based sampling approach for the population below","- Population: [description, size, value]\n- Risk factors: [e.g. new vendors, round amounts, weekend postings]\n- Required confidence / firm methodology: [..]","The sample must be defensible to the regulator and reproducible by another auditor","- Strata and sizes with the reason for each\n- Exact, reproducible selection steps (e.g. Excel RAND with a recorded seed list)\n- Claude does not pick the items itself","Sampling memo: approach, strata table, selection steps, limitations."),MPar("متخصص منهجية مراجعة","اقترح ووثّق منهج عينة مبني على المخاطر للمجتمع اللي تحت","- المجتمع: [الوصف، الحجم، القيمة]\n- عوامل الخطر: [مثلاً موردين جداد، مبالغ مقرّبة، قيود في الإجازات]\n- درجة الثقة / منهجية الشركة: [..]","العينة لازم تكون مبررة قدام الرقابة وقابلة للتكرار من مراجع تاني","- الطبقات وأحجامها وسبب كل واحدة\n- خطوات اختيار دقيقة وقابلة للتكرار (زي RAND في Excel مع تسجيل القائمة)\n- Claude مش هو اللي بيختار البنود","مذكرة العينة: المنهج، جدول الطبقات، خطوات الاختيار، القيود.")),master:true},
{t:T("Master prompt — regulatory gap analysis","البرومبت الماستر — تحليل فجوة رقابية"),p:T(MPen("Compliance officer","Compare the new regulation with our current policy and list every gap","- Regulation: [attach, date]\n- Our policy: [attach, version]\n- Scope: [business lines]","The compliance committee assigns owners and deadlines from this table","- Every requirement quoted with its clause number\n- Status: covered / partly / gap, with the policy quote\n- Nothing presented as a legal opinion","Gap table (requirement, clause, policy quote, status, suggested action) + summary of top 5 gaps."),MPar("مسؤول امتثال","قارن اللائحة الجديدة بسياستنا الحالية وطلّع كل الفجوات","- اللائحة: [ارفع، التاريخ]\n- سياستنا: [ارفع، الإصدار]\n- النطاق: [خطوط الأعمال]","لجنة الامتثال هتحدد مسؤولين ومواعيد من الجدول ده","- كل متطلب مقتبس برقم البند\n- الحالة: مغطى / جزئي / فجوة، مع اقتباس السياسة\n- مفيش حاجة متقدمة كرأي قانوني","جدول الفجوات (المتطلب، البند، اقتباس السياسة، الحالة، الإجراء المقترح) + ملخص أهم 5 فجوات.")),master:true}]}));
FEAT["9.5"]="Evidence trails, sampling, control tests, sign-off";CEO["9.5"]=T("AI can halve fieldwork time, but only with evidence references and a named human sign-off on every output.","الـ AI يقدر ينص وقت العمل الميداني، بس بشرط مراجع أدلة واعتماد بشري باسم على كل مخرج.");

// ---------- Module 10: Claude for Arabic content ----------
DAYS.push({n:10,icon:'ع',t:T("Claude for Arabic content","Claude للمحتوى العربي"),sub:T("Write, translate and check Arabic outputs — MSA, Egyptian and Gulf — that read as if a native professional wrote them.","اكتب وترجم وراجع مخرجات عربي — فصحى ومصري وخليجي — تتقري كأن محترف عربي كتبها."),units:[
U4({id:"10.1",tag:"core",dur:"40",t:T("Writing in Arabic: register and dialect","الكتابة بالعربي: المستوى واللهجة"),
body:T(`<p>Arabic output goes wrong mostly because the prompt never says <b>which Arabic</b>. Decide three things every time:</p><ul><li><b>Register:</b> Modern Standard Arabic (MSA) for boards, regulators, contracts and anything printed; dialect for social posts, training, chat and internal messages.</li><li><b>Dialect:</b> Egyptian (“إيه رأيك نعمل الخطة دي الأسبوع الجاي؟”) or Gulf (“وش رايك نسوي الخطة الأسبوع الجاي؟”). Say which, and give one example sentence in that voice.</li><li><b>Terms and numbers:</b> which technical terms stay in English (EBITDA, IFRS 16, KPI), Western (123) or Arabic-Indic (١٢٣) digits, and currency style (EGP 1.2M / 1.2 مليون جنيه).</li></ul><p>Then add the audience and tone, and ask Claude to keep sentences short — long MSA sentences are the main readability problem in business Arabic.</p>`,
`<p>المخرجات العربي بتبوظ غالباً علشان البرومبت مقالش <b>أنهي عربي</b>. حدد 3 حاجات كل مرة:</p><ul><li><b>المستوى:</b> فصحى للمجالس والرقابة والعقود وأي حاجة مطبوعة؛ ولهجة للسوشيال والتدريب والشات والرسايل الداخلية.</li><li><b>اللهجة:</b> مصري ("إيه رأيك نعمل الخطة دي الأسبوع الجاي؟") ولا خليجي ("وش رايك نسوي الخطة الأسبوع الجاي؟"). قول أنهي واحدة واديله جملة مثال بنفس الصوت.</li><li><b>المصطلحات والأرقام:</b> أنهي مصطلحات تفضل إنجليزي (EBITDA، IFRS 16، KPI)، أرقام عادية (123) ولا هندية (١٢٣)، وشكل العملة (EGP 1.2M / 1.2 مليون جنيه).</li></ul><p>وبعدين ضيف الجمهور والنبرة، واطلب جمل قصيرة — الجمل الفصحى الطويلة هي أكبر مشكلة في قراية العربي في البيزنس.</p>`),
steps:T(["Pick the register (MSA or dialect)","Name the dialect and give one example sentence","List terms that stay in English","Choose digits and currency style","Set audience, tone and sentence length"],["اختار المستوى (فصحى ولا لهجة)","سمّي اللهجة واديله جملة مثال","اكتب المصطلحات اللي تفضل إنجليزي","اختار شكل الأرقام والعملة","حدد الجمهور والنبرة وطول الجملة"]),
tips:T(["One example sentence in the target voice beats a paragraph of description.","For Gulf audiences, say the country — Saudi and Emirati usage differ."],["جملة مثال واحدة بالصوت المطلوب أحسن من فقرة وصف.","للجمهور الخليجي، قول البلد — السعودي والإماراتي بيختلفوا."]),
cases:[{t:T("One campaign, two dialects","حملة واحدة بلهجتين"),d:T("A fintech launched the same savings feature in Cairo and Riyadh. One master prompt with a dialect switch produced Egyptian and Saudi versions; local reviewers changed fewer than 10% of the words.","شركة فنتك أطلقت نفس ميزة الادخار في القاهرة والرياض. برومبت ماستر واحد بمفتاح للهجة طلّع نسخة مصري ونسخة سعودي؛ والمراجعين المحليين غيّروا أقل من 10% من الكلام.")}],
prompts:[{t:T("Master prompt — Arabic business writing","البرومبت الماستر — كتابة بيزنس بالعربي"),p:T(MPen("Senior Arabic business writer for [Egypt / Saudi Arabia / UAE]","Write [the piece] in Arabic for [audience]","- Register: [MSA / Egyptian / Gulf — country]\n- Example sentence in the target voice: [..]\n- Terms that stay in English: [EBITDA, KPI, ..]\n- Digits: [Western 123 / Arabic-Indic ١٢٣]; currency: [EGP / SAR / AED style]\n- Source notes: [paste]","The reader should feel it was written by a native professional, not translated","- No sentence over 25 words\n- Consistent register; no mixing MSA and dialect\n- Numbers and names exactly as in the source","Final Arabic text + a 3-line note on choices (register, terms, digits)."),MPar("كاتب بيزنس عربي أول لـ [مصر / السعودية / الإمارات]","اكتب [القطعة] بالعربي لـ [الجمهور]","- المستوى: [فصحى / مصري / خليجي — البلد]\n- جملة مثال بالصوت المطلوب: [..]\n- مصطلحات تفضل إنجليزي: [EBITDA، KPI، ..]\n- الأرقام: [عادية 123 / هندية ١٢٣]؛ العملة: [جنيه / ريال / درهم]\n- ملاحظات المصدر: [الصق]","القارئ لازم يحس إن محترف عربي كتبها، مش مترجمة","- مفيش جملة أطول من 25 كلمة\n- مستوى ثابت؛ من غير خلط فصحى ولهجة\n- الأرقام والأسماء زي المصدر بالظبط","النص العربي النهائي + ملاحظة 3 سطور عن الاختيارات (المستوى، المصطلحات، الأرقام).")),master:true}]}),
U4({id:"10.2",tag:"practical",dur:"40",t:T("Translating and localising","الترجمة والتوطين"),
body:T(`<p><b>Translation</b> keeps the meaning; <b>localisation</b> adapts examples, units, tone and references to the reader. Finance and legal content needs a locked glossary so the same English term always gets the same Arabic term (for example “impairment” → “اضمحلال القيمة”, “going concern” → “الاستمرارية”).</p><ol><li>Give Claude the glossary as a two-column table and say “use these exactly”.</li><li>Ask for a terms table at the end listing every glossary term used and any new term it had to choose.</li><li>For important documents, run a <b>back-translation</b>: a fresh chat translates the Arabic back to English, and you compare meaning, not wording.</li></ol><p>Keep proper names, figures, dates and clause numbers untouched, and say whether the Arabic should follow the English layout or read naturally.</p>`,
`<p><b>الترجمة</b> بتحافظ على المعنى؛ و<b>التوطين</b> بيكيّف الأمثلة والوحدات والنبرة والمراجع للقارئ. المحتوى المالي والقانوني محتاج قاموس مقفول علشان نفس المصطلح الإنجليزي ياخد دايماً نفس المصطلح العربي (مثلاً impairment ← «اضمحلال القيمة»، going concern ← «الاستمرارية»).</p><ol><li>ادّي Claude القاموس كجدول عمودين وقول «استخدمهم بالظبط».</li><li>اطلب جدول مصطلحات في الآخر بكل مصطلح استخدمه من القاموس وأي مصطلح جديد اضطر يختاره.</li><li>في المستندات المهمة اعمل <b>ترجمة عكسية</b>: محادثة جديدة تترجم العربي للإنجليزي، وإنت تقارن المعنى مش الكلمات.</li></ol><p>سيب الأسماء والأرقام والتواريخ وأرقام البنود زي ما هي، وقول العربي يمشي على ترتيب الإنجليزي ولا يتقري طبيعي.</p>`),
steps:T(["Decide translate or localise","Attach the locked glossary","Mark what must not change","Translate and get the terms table","Back-translate important documents","Human reviewer signs off"],["حدد ترجمة ولا توطين","ارفع القاموس المقفول","علّم اللي ممنوع يتغير","ترجم وخد جدول المصطلحات","اعمل ترجمة عكسية للمستندات المهمة","مراجع بشري يعتمد"]),
tips:T(["Back-translate in a new chat so Claude does not remember the original.","Keep your glossary in a Project so every translation uses it."],["اعمل الترجمة العكسية في محادثة جديدة علشان Claude ميفتكرش الأصل.","حط القاموس في Project علشان كل ترجمة تستخدمه."]),
cases:[{t:T("Annual report notes in Arabic","إيضاحات التقرير السنوي بالعربي"),d:T("A listed company translated 60 pages of IFRS notes with a 140-term glossary in a Project. The terms table caught 4 places where a new term was used; back-translation of the going-concern note confirmed the meaning before filing.","شركة مقيدة ترجمت 60 صفحة إيضاحات IFRS بقاموس 140 مصطلح في Project. جدول المصطلحات كشف 4 أماكن اتستخدم فيها مصطلح جديد؛ والترجمة العكسية لإيضاح الاستمرارية أكدت المعنى قبل الإيداع.")}],
prompts:[{t:T("Master prompt — glossary-locked translation","البرومبت الماستر — ترجمة بقاموس مقفول"),p:T(MPen("Certified financial translator (English ↔ Arabic)","Translate the attached document into [MSA Arabic] for [audience]","- Glossary (use exactly): [attach two-column table]\n- Keep unchanged: names, figures, dates, clause numbers\n- Layout: [follow source / natural Arabic order]\n- Localise: [none / examples and units for Egypt or Gulf]","The translation will be filed or published; terminology must be consistent","- Every glossary term used exactly as given\n- No figure, date or name changed\n- Unclear source sentences flagged, not guessed","Translated text + terms table (English, Arabic, from glossary? yes/no) + flagged sentences."),MPar("مترجم مالي معتمد (إنجليزي ↔ عربي)","ترجم المستند المرفق لـ [عربي فصحى] لـ [الجمهور]","- القاموس (استخدمه بالظبط): [ارفع جدول عمودين]\n- يفضل زي ما هو: الأسماء والأرقام والتواريخ وأرقام البنود\n- الترتيب: [زي المصدر / ترتيب عربي طبيعي]\n- التوطين: [مفيش / الأمثلة والوحدات لمصر أو الخليج]","الترجمة هتتودع أو تتنشر؛ المصطلحات لازم تكون ثابتة","- كل مصطلح من القاموس مستخدم زي ما هو\n- مفيش رقم أو تاريخ أو اسم اتغير\n- الجمل المش واضحة في المصدر متعلّمة، مش متخمنة","النص المترجم + جدول المصطلحات (إنجليزي، عربي، من القاموس؟ أيوه/لأ) + الجمل المتعلّمة.")),master:true}]}),
U4({id:"10.3",tag:"critical",dur:"35",t:T("Checking Arabic outputs","مراجعة المخرجات العربي"),
body:T(`<p>Arabic errors are easy to miss when you skim. Check every important output against this list — or ask Claude to run it as a self-review in a new chat:</p><ul><li><b>Agreement:</b> gender and number agreement between nouns, verbs and adjectives.</li><li><b>Numbers and dates:</b> digits copied exactly; dates and currency in the agreed style; no swapped thousands separators.</li><li><b>Mixed direction:</b> English terms, codes and numbers inside Arabic lines display in the right order (check in the final file, not only in chat).</li><li><b>Names:</b> people, companies and places spelled the way they spell themselves.</li><li><b>Register drift:</b> no dialect words inside MSA and no MSA stiffness in a casual post.</li><li><b>Invented terms:</b> technical words that look Arabic but nobody uses — compare with your glossary.</li></ul><p>A native reviewer still signs off anything external.</p>`,
`<p>أخطاء العربي سهل تفوتها وإنت بتقرا بسرعة. راجع أي مخرج مهم على القائمة دي — أو اطلب من Claude يعملها كمراجعة ذاتية في محادثة جديدة:</p><ul><li><b>المطابقة:</b> التذكير والتأنيث والإفراد والجمع بين الأسماء والأفعال والصفات.</li><li><b>الأرقام والتواريخ:</b> الأرقام متنقولة بالظبط؛ والتواريخ والعملة بالشكل المتفق عليه؛ ومفيش فواصل آلاف متلخبطة.</li><li><b>الاتجاه المختلط:</b> المصطلحات الإنجليزي والأكواد والأرقام جوه السطر العربي بتظهر بالترتيب الصح (راجع في الملف النهائي مش في الشات بس).</li><li><b>الأسماء:</b> الأشخاص والشركات والأماكن مكتوبين زي ما أصحابهم بيكتبوهم.</li><li><b>تغيّر المستوى:</b> مفيش كلام عامي جوه الفصحى ولا تقل فصحى في بوست خفيف.</li><li><b>مصطلحات متألفة:</b> كلمات تقنية شكلها عربي بس محدش بيستخدمها — قارنها بالقاموس.</li></ul><p>ولازم مراجع عربي يعتمد أي حاجة خارجية.</p>`),
steps:T(["Run the checklist on the output","Open the final file and check direction","Compare terms with the glossary","Ask a new chat for a self-review","Native reviewer signs off"],["طبّق القائمة على المخرج","افتح الملف النهائي وراجع الاتجاه","قارن المصطلحات بالقاموس","اطلب مراجعة ذاتية في محادثة جديدة","مراجع عربي يعتمد"]),
tips:T(["Mixed-direction problems often appear only after export to Word, PDF or slides.","Ask Claude to list issues, not to rewrite — then decide each fix yourself."],["مشاكل الاتجاه المختلط غالباً بتظهر بعد التصدير لـ Word أو PDF أو العرض.","اطلب من Claude يطلّع المشاكل مش يعيد الكتابة — وبعدين قرر كل تصليح بنفسك."]),
cases:[{t:T("A price list that reversed","قائمة أسعار اتقلبت"),d:T("A retailer's Arabic price list showed “SKU-1042” as “1042-SKU” after export to PDF. The checklist step “check direction in the final file” caught it before printing 5,000 copies.","قائمة أسعار عربي لمحل ظهر فيها «SKU-1042» كـ «1042-SKU» بعد التصدير لـ PDF. خطوة «راجع الاتجاه في الملف النهائي» كشفتها قبل طباعة 5,000 نسخة.")}],
prompts:[{t:T("Master prompt — Arabic quality review","البرومبت الماستر — مراجعة جودة العربي"),p:T(MPen("Arabic editor and proofreader for business documents","Review the Arabic text below and list every issue; do not rewrite it","- Text: [paste]\n- Register expected: [MSA / Egyptian / Gulf]\n- Glossary: [attach or none]\n- Source (if translated): [paste]","The text goes to [audience] and errors damage credibility","- Checks: agreement, numbers and dates vs source, mixed-direction lines, names, register drift, invented terms\n- Each issue quoted with its line\n- Severity high / medium / low","Issues table (line, quote, issue type, suggested fix, severity) + overall verdict in one line."),MPar("محرر ومدقق لغوي عربي لمستندات البيزنس","راجع النص العربي اللي تحت وطلّع كل مشكلة؛ متعيدش كتابته","- النص: [الصق]\n- المستوى المتوقع: [فصحى / مصري / خليجي]\n- القاموس: [ارفع أو مفيش]\n- المصدر (لو مترجم): [الصق]","النص رايح لـ [الجمهور] والأخطاء بتضر المصداقية","- المراجعة: المطابقة، الأرقام والتواريخ مقابل المصدر، السطور مختلطة الاتجاه، الأسماء، تغيّر المستوى، المصطلحات المتألفة\n- كل مشكلة مقتبسة بسطرها\n- الخطورة عالية / متوسطة / قليلة","جدول المشاكل (السطر، الاقتباس، نوع المشكلة، التصليح المقترح، الخطورة) + الحكم العام في سطر.")),master:true}]}),
U4({id:"10.4",tag:"practical",dur:"35",t:T("Arabic documents, files and layouts","المستندات والملفات والتنسيق بالعربي"),
body:T(`<p>Arabic work often starts from scanned PDFs, mixed Arabic-English spreadsheets or slide decks, and ends in a file someone will print. Plan the input and the output:</p><ul><li><b>Input:</b> say which language each file is in, whether it is scanned, and ask Claude to quote the Arabic it read before analysing it, so you can catch reading errors early.</li><li><b>Tables:</b> ask for right-to-left column order when the table is for Arabic readers, and keep numbers in their own column.</li><li><b>Output files:</b> when Claude creates a document, slides or a web page, ask for right-to-left layout and an Arabic-friendly font, then open the file and check headings, bullets and tables.</li><li><b>Bilingual documents:</b> decide side-by-side columns or Arabic-then-English sections before you start.</li></ul>`,
`<p>شغل العربي غالباً بيبدأ من PDF متصوّر، أو شيتات فيها عربي وإنجليزي، أو عروض، وبيخلص بملف حد هيطبعه. خطط للمدخل والمخرج:</p><ul><li><b>المدخل:</b> قول كل ملف بأنهي لغة، ومتصوّر ولا لأ، واطلب من Claude يقتبس العربي اللي قراه قبل ما يحلل، علشان تكشف أخطاء القراية بدري.</li><li><b>الجداول:</b> اطلب ترتيب الأعمدة من اليمين للشمال لو الجدول لقارئ عربي، وخلي الأرقام في عمود لوحدها.</li><li><b>ملفات المخرج:</b> لما Claude يعمل مستند أو عرض أو صفحة ويب، اطلب اتجاه من اليمين للشمال وخط مناسب للعربي، وبعدين افتح الملف وراجع العناوين والنقط والجداول.</li><li><b>المستندات ثنائية اللغة:</b> قرر أعمدة جنب بعض ولا أجزاء عربي بعدها إنجليزي قبل ما تبدأ.</li></ul>`),
steps:T(["Describe each input file","Ask Claude to quote what it read","Agree table direction and number columns","Request RTL layout and font for outputs","Open and check the final file"],["اوصف كل ملف مدخل","اطلب من Claude يقتبس اللي قراه","اتفق على اتجاه الجدول وعمود الأرقام","اطلب اتجاه يمين لشمال وخط للمخرجات","افتح الملف النهائي وراجعه"]),
tips:T(["Scanned Arabic with stamps and handwriting needs a human check of key fields.","Keep one bilingual template and reuse it — layout problems get solved once."],["العربي المتصوّر اللي فيه أختام وخط إيد محتاج مراجعة بشرية للحقول المهمة.","خلّي عندك قالب واحد ثنائي اللغة وكرره — مشاكل التنسيق بتتحل مرة واحدة."]),
cases:[{t:T("Bilingual board pack","ملف مجلس ثنائي اللغة"),d:T("A family business moved its board pack to a bilingual template: Arabic right column, English left, numbers in the middle. Claude fills both from one data file each quarter; preparation time fell from two days to half a day.","شركة عائلية نقلت ملف المجلس لقالب ثنائي اللغة: العربي في العمود اليمين، والإنجليزي الشمال، والأرقام في النص. Claude بيملا الاتنين من ملف بيانات واحد كل ربع؛ ووقت التجهيز نزل من يومين لنص يوم.")}],
prompts:[{t:T("Master prompt — bilingual document from data","البرومبت الماستر — مستند ثنائي اللغة من بيانات"),p:T(MPen("Bilingual report designer","Create a bilingual (Arabic + English) [report / slides] from the attached data","- Data: [attach]\n- Layout: [side-by-side columns / Arabic then English]\n- Arabic register: [MSA]; terms that stay in English: [..]\n- Output file: [document / slides / web page] with right-to-left Arabic and an Arabic-friendly font","Readers in both languages must see the same numbers and message","- Every figure identical in both languages\n- Tables right-to-left in the Arabic part\n- Headings and bullets aligned correctly in the final file","The file + a checklist of layout points I should verify after opening it."),MPar("مصمم تقارير ثنائية اللغة","اعمل [تقرير / عرض] ثنائي اللغة (عربي + إنجليزي) من البيانات المرفقة","- البيانات: [ارفع]\n- الترتيب: [أعمدة جنب بعض / عربي بعده إنجليزي]\n- المستوى العربي: [فصحى]؛ مصطلحات تفضل إنجليزي: [..]\n- ملف المخرج: [مستند / عرض / صفحة ويب] بعربي من اليمين للشمال وخط مناسب للعربي","القراء باللغتين لازم يشوفوا نفس الأرقام ونفس الرسالة","- كل رقم متطابق في اللغتين\n- الجداول من اليمين للشمال في الجزء العربي\n- العناوين والنقط متظبطة في الملف النهائي","الملف + قائمة بنقط التنسيق اللي أراجعها بعد ما أفتحه.")),master:true}]})]});
FEAT["10.1"]="Register, dialect, terms, digits";FEAT["10.2"]="Glossary-locked translation, localisation, back-translation";FEAT["10.3"]="Arabic QA checklist, self-review";FEAT["10.4"]="Arabic files, RTL tables and layouts";
CEO["10.1"]=T("Customers trust content in their own voice — specify the Arabic you want, every time.","العملاء بيثقوا في المحتوى اللي بصوتهم — حدد العربي اللي عايزه كل مرة.");CEO["10.2"]=T("A locked glossary turns translation from a risk into a repeatable process.","القاموس المقفول بيحوّل الترجمة من خطر لعملية متكررة.");CEO["10.3"]=T("One checklist and a native sign-off protect the brand in every Arabic document.","قائمة مراجعة واحدة واعتماد مراجع عربي بيحموا البراند في كل مستند عربي.");CEO["10.4"]=T("Bilingual templates save hours every reporting cycle.","القوالب ثنائية اللغة بتوفّر ساعات في كل دورة تقارير.");
QUIZ[10]=[
Q("Which register suits a board paper?","أنهي مستوى مناسب لورقة مجلس إدارة؟",[["Egyptian dialect","لهجة مصري"],["Modern Standard Arabic","الفصحى"],["Gulf dialect","لهجة خليجي"],["Arabizi (Latin letters)","فرانكو"]],1,"MSA is the default for boards, regulators and printed documents.","الفصحى هي الأساس للمجالس والرقابة والمستندات المطبوعة."),
Q("What keeps financial terms consistent across translations?","إيه اللي بيخلي المصطلحات المالية ثابتة في كل الترجمات؟",[["A longer prompt","برومبت أطول"],["A locked glossary Claude must use exactly","قاموس مقفول لازم Claude يستخدمه بالظبط"],["Translating twice","الترجمة مرتين"],["Using dialect","استخدام اللهجة"]],1,"Give the glossary and ask for a terms table at the end.","اديله القاموس واطلب جدول مصطلحات في الآخر."),
Q("What is a back-translation check?","يعني إيه مراجعة الترجمة العكسية؟",[["Translating from Arabic to English in a new chat to compare meaning","ترجمة العربي للإنجليزي في محادثة جديدة ومقارنة المعنى"],["Reading the text backwards","قراية النص بالعكس"],["Asking Claude to repeat the translation","تطلب من Claude يكرر الترجمة"],["Counting words","عدّ الكلمات"]],0,"It checks meaning, not wording.","بتراجع المعنى، مش الكلمات."),
Q("Where do mixed-direction problems usually show up?","مشاكل الاتجاه المختلط بتظهر فين غالباً؟",[["In the prompt","في البرومبت"],["In the final exported file","في الملف النهائي بعد التصدير"],["In the glossary","في القاموس"],["Never","عمرها ما بتظهر"]],1,"Always open the final Word, PDF or slides and check.","افتح دايماً ملف Word أو PDF أو العرض النهائي وراجع."),
Q("Best way to get the right dialect?","أحسن طريقة تاخد بيها اللهجة الصح؟",[["Say “write in Arabic”","تقول «اكتب بالعربي»"],["Name the dialect and give one example sentence in that voice","تسمّي اللهجة وتدي جملة مثال بنفس الصوت"],["Use English","تكتب بالإنجليزي"],["Ask for MSA then edit","تطلب فصحى وبعدين تعدّل"]],1,"An example sentence is the strongest signal.","جملة المثال هي أقوى إشارة.")];
QUIZ[1].push(Q("A forecast includes a loan nobody agreed. Which failure is it?","توقع فيه قرض محدش وافق عليه. ده أنهي خطأ؟",[["Wrong format","شكل غلط"],["Made-up numbers","أرقام متألفة"],["Language drift","اللغة اتغيرت"],["Missed constraint","قيد اتنسى"]],1,"Fix: use only listed facilities and flag gaps.","العلاج: استخدم التسهيلات المذكورة بس وعلّم العجز."));
QUIZ[9].push(Q("Who should select an audit sample?","مين اللي يختار عينة المراجعة؟",[["Claude, from memory","Claude من دماغه"],["A documented, reproducible method, with Claude explaining the approach","طريقة موثقة وقابلة للتكرار، وClaude يشرح المنهج"],["Whoever is fastest","أسرع حد"],["Nobody — test everything","محدش — اختبر كله"]],1,"Reproducibility is what makes a sample defensible.","إمكانية التكرار هي اللي بتخلي العينة مبررة."));
