const XL=(en,ar,se,sa,pe,pa)=>({t:T(en,ar),steps:T(se,sa),p:T(pe,pa)});
const DEEP={
excel:{icon:"▦",t:T("Excel with AI","Excel بالذكاء الاصطناعي"),sub:T("Claude for Excel, step by step, with 14 finance use cases.","Claude for Excel خطوة بخطوة، مع 14 حالة مالية."),
 sections:[
 {h:T("What it does","بيعمل إيه"),b:T(`<ul><li>Reads every tab and explains any number with <b>cell citations</b> (e.g. "EBITDA in Summary!F12 comes from P&L!F40 minus…").</li><li>Builds models from scratch: 3-statement, DCF, budget, 13-week cash, headcount.</li><li>Changes assumptions <b>without breaking formula links</b>.</li><li>Finds and fixes #REF!, #VALUE!, circular references and hard-codes.</li><li>Cleans messy data (split names, dates, Arabic-Indic digits, duplicates).</li><li>Creates pivots, charts and sensitivity tables.</li><li>Shares context with PowerPoint/Word so a deck can be built from the open workbook.</li></ul>`,`<ul><li>بيقرا كل الشيتات ويشرح أي رقم <b>بالإشارة للخلايا</b> (مثلاً "EBITDA في Summary!F12 جاي من P&L!F40 ناقص…").</li><li>يبني نماذج من الصفر: القوائم التلاتة، DCF، موازنة، تدفق نقدي 13 أسبوع، عدد الموظفين.</li><li>يغيّر الافتراضات <b>من غير ما يكسر روابط المعادلات</b>.</li><li>يلاقي ويصلّح #REF! و #VALUE! والمراجع الدائرية والأرقام اليدوية.</li><li>ينضّف البيانات (فصل الأسماء، التواريخ، الأرقام العربية، التكرار).</li><li>يعمل Pivot ورسوم وجداول حساسية.</li><li>بيشارك السياق مع PowerPoint و Word فتقدر تبني عرض من الملف المفتوح.</li></ul>`)},
 {h:T("Set-up in 5 steps","التجهيز في 5 خطوات"),b:T(`<ol><li>Paid Claude plan (Pro and up). Excel on web, Windows (M365 16.0.13127.20296+) or Mac (16.46+).</li><li>Home → Add-ins → search "Claude by Anthropic" → Add. (IT can deploy for everyone via M365 Admin Center → Integrated apps.)</li><li>Sign in with your Claude account.</li><li>Open your workbook, open the Claude panel, start with "Explain this workbook".</li><li>Approve each change; keep a version copy before big edits.</li></ol>`,`<ol><li>خطة Claude مدفوعة (Pro وفوق). Excel ويب أو ويندوز (M365 16.0.13127.20296+) أو ماك (16.46+).</li><li>Home ← Add-ins ← دوّر على "Claude by Anthropic" ← Add. (الـ IT يقدر ينشره للكل من M365 Admin Center ← Integrated apps.)</li><li>سجّل بحساب Claude.</li><li>افتح الملف وافتح لوحة Claude وابدأ بـ "اشرحلي الملف ده".</li><li>وافق على كل تعديل؛ واحتفظ بنسخة قبل التعديلات الكبيرة.</li></ol>`)},
 {h:T("Rules for safe Excel AI","قواعد الأمان مع Excel"),b:T(`<ul><li>Ask for formulas, never pasted values.</li><li>Ask for a change log of every cell touched.</li><li>Check one row manually per calculation block.</li><li>Keep assumptions on one sheet; Claude respects that structure.</li><li>Classify the file before uploading — client data follows your company policy.</li></ul>`,`<ul><li>اطلب معادلات، مش قيم ملصوقة.</li><li>اطلب سجل تغييرات بكل خلية اتعدلت.</li><li>راجع صف واحد يدوي في كل بلوك حسابات.</li><li>خلي الافتراضات في شيت واحد؛ Claude بيحترم الهيكل ده.</li><li>صنّف الملف قبل ما ترفعه — بيانات العملاء بتمشي على سياسة شركتك.</li></ul>`)}
 ],
 cases:[
 XL("Explain an inherited model","افهم نموذج ورثته",["Open the file","Ask for a map of tabs and flow","Ask for every hard-coded number","Ask for a one-page user guide"],["افتح الملف","اطلب خريطة الشيتات وتدفقها","اطلب كل الأرقام المكتوبة يدوي","اطلب دليل استخدام صفحة واحدة"],
 `Explain this workbook: list each tab, its purpose and how data flows between tabs. Then list every hard-coded number inside formulas with its cell address, and write a one-page user guide on a new sheet "Guide".`,`اشرحلي الملف ده: كل شيت والغرض منه وإزاي البيانات بتمشي بين الشيتات. وبعدين طلّعلي كل رقم مكتوب يدوي جوه معادلة بعنوان خليته، واكتب دليل استخدام صفحة واحدة في شيت جديد اسمه "Guide".`),
 XL("Trace a number","تتبّع رقم",["Select the KPI cell","Ask Claude to trace it back","Check each step it cites"],["اختار خلية المؤشر","اطلب من Claude يتتبعه لورا","راجع كل خطوة بيشير لها"],
 `Trace Summary!F12 (EBITDA) back to its source inputs. Show each step with cell references and explain any adjustment in plain English and Arabic.`,`تتبّع Summary!F12 (EBITDA) لحد المدخلات الأصلية. اعرض كل خطوة بمراجع الخلايا واشرح أي تسوية بالإنجليزي والعربي ببساطة.`),
 XL("Fix formula errors","صلّح أخطاء المعادلات",["Ask for a full error scan","Review the list","Approve fixes one block at a time"],["اطلب فحص كامل للأخطاء","راجع القائمة","وافق على التصليحات بلوك بلوك"],
 `Scan the whole workbook for #REF!, #VALUE!, #DIV/0!, circular references, inconsistent formulas across a row, and totals that exclude rows. Return Sheet | Cell | Issue | Proposed fix. Don't change anything until I approve.`,`افحص الملف كله على #REF! و #VALUE! و #DIV/0! والمراجع الدائرية والمعادلات غير المتسقة في نفس الصف والإجماليات اللي ناقصها صفوف. الناتج: الشيت | الخلية | المشكلة | التصليح المقترح. متغيّرش حاجة غير لما أوافق.`),
 XL("Build a 3-statement model","ابني نموذج القوائم التلاتة",["Give 3 years of history","State drivers","Ask for checks (balance sheet balances, cash ties)"],["ادّيله 3 سنين تاريخية","حدد المحركات","اطلب ضوابط (الميزانية متوازنة والنقدية مطابقة)"],
 `Build a linked 3-statement model (IS, BS, CF indirect) for 5 forecast years from the historical tabs. Drivers on an "Assumptions" sheet: revenue growth, gross margin, opex % of sales, DSO/DIO/DPO, capex % of sales, depreciation years, tax 22.5%, interest rate. Add a checks row: BS balances and CF ending cash = BS cash. All in EGP thousands, formulas only.`,`ابني نموذج قوائم تلاتة مترابط (دخل، ميزانية، تدفق نقدي غير مباشر) لـ 5 سنين توقع من الشيتات التاريخية. المحركات في شيت "Assumptions": نمو الإيرادات، هامش الربح الإجمالي، المصروفات % من المبيعات، DSO/DIO/DPO، الاستثمارات % من المبيعات، سنين الإهلاك، ضريبة 22.5%، سعر الفايدة. ضيف صف ضوابط: الميزانية متوازنة ونقدية آخر المدة = نقدية الميزانية. كله بالألف جنيه ومعادلات بس.`),
 XL("DCF with Egypt/KSA risk","DCF بمخاطر مصر/السعودية",["Build FCF from the model","Build WACC with country risk premium","Add sensitivity grid"],["ابني FCF من النموذج","ابني WACC بعلاوة مخاطر الدولة","ضيف جدول حساسية"],
 `Add a DCF sheet: unlevered FCF from the model, WACC built from risk-free rate, beta, equity risk premium, country risk premium for [Egypt/KSA], pre-tax cost of debt and target D/E. Terminal value by Gordon growth. Output EV, net debt, equity value and a 5×5 sensitivity (WACC × terminal growth). Label every assumption with its source cell.`,`ضيف شيت DCF: التدفق الحر من النموذج، WACC مبني من العائد الخالي من المخاطر والبيتا وعلاوة مخاطر السوق وعلاوة مخاطر الدولة لـ [مصر/السعودية] وتكلفة الدين قبل الضريبة ونسبة الدين المستهدفة. القيمة النهائية بنمو جوردن. الناتج: قيمة المنشأة وصافي الدين وقيمة حقوق الملكية وجدول حساسية 5×5 (WACC × النمو النهائي). اكتب مصدر كل افتراض.`),
 XL("FX scenario without breaking links","سيناريو سعر صرف من غير ما الروابط تتكسر",["Ask Claude to locate every FX input","Add a scenario selector","Compare outputs"],["اطلب يلاقي كل مدخل سعر صرف","ضيف اختيار سيناريو","قارن النتايج"],
 `Find every place the EGP/USD rate is used. Replace them with one input cell, then add a scenario selector (Base 48, Stress 55, Severe 62). Show net profit, cash and covenant ratios under each scenario. Don't overwrite formulas; give me a change log.`,`لاقي كل مكان سعر الجنيه/الدولار مستخدم فيه. خليهم كلهم يقروا من خلية مدخلات واحدة، وبعدين ضيف اختيار سيناريو (أساسي 48، ضغط 55، شديد 62). اعرض صافي الربح والنقدية ونسب التعهدات في كل سيناريو. متكتبش فوق المعادلات؛ وادّيني سجل التغييرات.`),
 XL("Budget vs actual + commentary","موازنة مقابل فعلي + تعليق",["Paste actuals","Ask for variance table","Ask for drivers and commentary"],["الصق الفعلي","اطلب جدول الانحرافات","اطلب الأسباب والتعليق"],
 `Build a Budget vs Actual sheet for September and YTD: variance in value and %, red/amber/green flags above 5% and 10%. Then write a 150-word commentary for the CFO explaining the 3 biggest variances with likely drivers. Ask me if a driver is unclear rather than guessing.`,`ابني شيت موازنة مقابل فعلي لسبتمبر ومن أول السنة: الانحراف بالقيمة والنسبة، وإشارات أحمر/أصفر/أخضر فوق 5% و 10%. وبعدين اكتب تعليق 150 كلمة للمدير المالي يشرح أكبر 3 انحرافات وأسبابها المحتملة. اسألني لو سبب مش واضح بدل ما تخمّن.`),
 XL("13-week cash flow","التدفق النقدي 13 أسبوع",["Give opening cash and AR/AP aging","Ask for weekly model","Add minimum cash alert"],["ادّيله النقدية الافتتاحية وأعمار العملاء والموردين","اطلب نموذج أسبوعي","ضيف تنبيه حد أدنى"],
 `Build a 13-week cash flow: opening balance, receipts from AR aging (by DSO pattern), payments to suppliers (by AP aging), payroll on the 25th, rent, taxes, capex, loan installments. Closing balance with conditional formatting under a minimum of EGP 5M. Add Base and Stress columns.`,`ابني تدفق نقدي 13 أسبوع: الرصيد الافتتاحي، التحصيلات من أعمار العملاء (حسب نمط DSO)، المدفوعات للموردين (حسب أعمارهم)، المرتبات يوم 25، الإيجار، الضرائب، الاستثمارات، أقساط القروض. الرصيد الختامي بتنسيق شرطي لو نزل عن 5 مليون جنيه. ضيف عمود أساسي وعمود ضغط.`),
 XL("Clean a messy export","نضّف تصدير بايظ",["Upload the export","Describe the target format","Ask for a cleaning log"],["ارفع الملف","اوصف الشكل المطلوب","اطلب سجل التنضيف"],
 `Clean the "Raw" sheet into a new "Clean" sheet: split full names, convert Arabic-Indic digits to Western, standardize dates to DD/MM/YYYY, trim spaces, remove exact duplicates, flag near-duplicates. Add a log sheet with counts of each fix.`,`نضّف شيت "Raw" في شيت جديد "Clean": افصل الأسماء، حوّل الأرقام العربية لإنجليزي، وحّد التواريخ DD/MM/YYYY، شيل المسافات الزيادة، امسح التكرار التام وعلّم على شبه المتكرر. ضيف شيت سجل بعدد كل تصليح.`),
 XL("Pivot & chart pack","حزمة Pivot ورسوم",["Name the questions","Ask for pivots per question","Ask for chart sheet"],["حدد الأسئلة","اطلب Pivot لكل سؤال","اطلب شيت رسوم"],
 `From the Sales table create pivots for: revenue by region by month, top 10 customers, product mix %. Then create a "Charts" sheet with a line chart (trend), bar chart (regions) and donut (mix), titled in Arabic and English.`,`من جدول المبيعات اعمل Pivot لـ: الإيرادات حسب المنطقة والشهر، أعلى 10 عملاء، نسب مزيج المنتجات. وبعدين شيت "Charts" فيه رسم خطي (الاتجاه) وأعمدة (المناطق) ودونات (المزيج)، بعناوين عربي وإنجليزي.`),
 XL("Financial ratios & DuPont","النسب المالية و DuPont",["Point to IS and BS","Ask for ratio sheet","Ask for interpretation"],["حدد قائمة الدخل والميزانية","اطلب شيت النسب","اطلب التفسير"],
 `Add a "Ratios" sheet for 3 years: current, quick, cash ratio; D/E, debt ratio, interest cover; asset, inventory and receivables turnover; ROA, ROE with DuPont split (margin × turnover × leverage). Traffic lights against benchmarks I'll give, and a 5-line interpretation.`,`ضيف شيت "Ratios" لـ 3 سنين: نسبة التداول والسريعة والنقدية؛ الدين لحقوق الملكية ونسبة الدين وتغطية الفوايد؛ دوران الأصول والمخزون والعملاء؛ ROA و ROE بتحليل DuPont (الهامش × الدوران × الرافعة). إشارات ضوئية حسب المعايير اللي هديهالك، وتفسير 5 سطور.`),
 XL("Credit spreading","تحليل ائتماني في القالب",["Open bank template","Upload borrower statements","Ask to map and compute"],["افتح قالب البنك","ارفع قوائم العميل","اطلب الربط والحساب"],
 `Map the borrower's statements (uploaded PDF) into our spreading template. Compute DSCR, leverage (Debt/EBITDA), interest cover and covenant headroom vs the limits in cells B3:B6. Flag any line you had to reclassify and why.`,`انقل قوائم العميل (PDF مرفوع) في قالب التحليل بتاعنا. احسب DSCR والرافعة (الدين/EBITDA) وتغطية الفوايد وهامش التعهدات مقابل الحدود في B3:B6. علّم على أي بند أعدت تصنيفه وليه.`),
 XL("Headcount & payroll plan","خطة الموظفين والمرتبات",["List departments and grades","Add hiring plan","Add increments and social insurance"],["حدد الإدارات والدرجات","ضيف خطة التعيين","ضيف الزيادات والتأمينات"],
 `Build a 2027 headcount plan: current staff by department and grade, planned hires by month, attrition 12%, annual increment 15% in April, employer social insurance per Egyptian rules (put the rate as an input), total monthly cost and variance vs payroll budget.`,`ابني خطة موظفين 2027: الموظفين الحاليين حسب الإدارة والدرجة، التعيينات المخططة بالشهر، معدل ترك 12%، زيادة سنوية 15% في أبريل، تأمينات صاحب العمل حسب القواعد المصرية (حط النسبة كمدخل)، التكلفة الشهرية الإجمالية والانحراف عن موازنة المرتبات.`),
 XL("Workbook → board deck","من Excel لعرض المجلس",["Finish the model","Open PowerPoint template","Ask Claude in PowerPoint to build from workbook"],["خلّص النموذج","افتح قالب PowerPoint","اطلب من Claude في PowerPoint يبني من الملف"],
 `In PowerPoint, using the open template and the open workbook, build 6 slides: KPIs vs budget, revenue bridge (native waterfall), cash runway, FX sensitivity, 3 risks, decisions requested. Every number must reference the workbook.`,`في PowerPoint، بالقالب المفتوح والملف المفتوح، ابني 6 شرائح: المؤشرات مقابل الموازنة، جسر الإيرادات (شلال أصلي)، مدة كفاية النقدية، حساسية سعر الصرف، 3 مخاطر، القرارات المطلوبة. كل رقم لازم يرجع للملف.`)
 ]},
prompting:{icon:"✎",t:T("Effective prompts — the complete method","البرومبت الفعّال — المنهج الكامل"),sub:T("From a vague ask to a reliable, reusable instruction.","من طلب غامض لتعليمات موثوقة تتعاد."),
 sections:[
 {h:T("The 10 rules","القواعد العشرة"),b:T(`<ol><li><b>Clear and direct.</b> If a smart new colleague would be confused, Claude will be too.</li><li><b>Explain why.</b> The purpose lets Claude make the right trade-offs.</li><li><b>Give context it can't guess:</b> numbers, period, currency, audience, constraints.</li><li><b>Show 3–5 examples</b> in &lt;example&gt; tags for format or tone.</li><li><b>Structure with XML tags:</b> &lt;role&gt;, &lt;context&gt;, &lt;documents&gt;, &lt;instructions&gt;, &lt;output_format&gt;.</li><li><b>Long documents first, question last</b> — Anthropic reports up to 30% better quality.</li><li><b>Ask for thinking</b> on hard problems (raise effort), and for a plan before execution.</li><li><b>Chain big jobs:</b> extract → analyze → draft → review, one step per message.</li><li><b>Define done</b> with stop conditions and a checklist.</li><li><b>Make Claude ask:</b> "restate my ask and ask up to 3 questions first."</li></ol>`,`<ol><li><b>وضوح ومباشرة.</b> لو زميل ذكي جديد هيتلخبط، Claude هيتلخبط.</li><li><b>اشرح السبب.</b> الهدف بيخلي Claude يوازن صح.</li><li><b>ادّيله السياق اللي مش هيخمّنه:</b> أرقام، فترة، عملة، جمهور، قيود.</li><li><b>اعرض 3–5 أمثلة</b> جوه &lt;example&gt; للشكل أو النبرة.</li><li><b>نظّم بوسوم XML:</b> &lt;role&gt; و &lt;context&gt; و &lt;documents&gt; و &lt;instructions&gt; و &lt;output_format&gt;.</li><li><b>المستندات الطويلة الأول والسؤال في الآخر</b> — Anthropic بتقول ممكن تحسّن الجودة لحد 30%.</li><li><b>اطلب تفكير</b> في المسائل الصعبة (ارفع الـ Effort)، واطلب خطة قبل التنفيذ.</li><li><b>قسّم الشغل الكبير:</b> استخراج ← تحليل ← كتابة ← مراجعة، خطوة في كل رسالة.</li><li><b>عرّف "خلصت"</b> بشروط توقف وقائمة مراجعة.</li><li><b>خلّي Claude يسأل:</b> "اعد طلبي واسألني لحد 3 أسئلة الأول."</li></ol>`)},
 {h:T("Weak vs strong","ضعيف مقابل قوي"),b:T(`<div class="vs"><div class="bad"><b>Weak</b><p>"Analyze these financials."</p></div><div class="good"><b>Strong</b><p>"You are a credit analyst at an Egyptian bank. Using the attached 3-year statements (EGP thousands), compute DSCR, Debt/EBITDA and interest cover; compare to our limits (DSCR ≥1.25, Debt/EBITDA ≤3.5). We decide on a EGP 50M facility next week. Output a table + 5-line recommendation. Flag any number you had to estimate."</p></div></div>`,`<div class="vs"><div class="bad"><b>ضعيف</b><p>"حلّل القوائم دي."</p></div><div class="good"><b>قوي</b><p>"إنت محلل ائتمان في بنك مصري. من القوائم المرفقة لـ 3 سنين (بالألف جنيه) احسب DSCR والدين/EBITDA وتغطية الفوايد؛ وقارنهم بحدودنا (DSCR ≥ 1.25، الدين/EBITDA ≤ 3.5). هنقرر على تسهيل 50 مليون جنيه الأسبوع الجاي. الناتج جدول + توصية 5 سطور. علّم على أي رقم اضطريت تقدّره."</p></div></div>`)},
 {h:T("8 prompt patterns","8 أنماط برومبت"),b:T(`<ul><li><b>Interviewer:</b> "Ask me questions one at a time until you have enough to build X."</li><li><b>Critic:</b> "Review this as a sceptical CFO. List the 5 weakest points."</li><li><b>Red team:</b> "What would make this forecast wrong?"</li><li><b>Options:</b> "Give 3 approaches with pros, cons and when to choose each."</li><li><b>Template filler:</b> "Fill this exact template; leave [MISSING] where you lack data."</li><li><b>Teacher:</b> "Explain like I'm a new analyst, then quiz me with 3 questions."</li><li><b>Translator:</b> "Rewrite for a board audience in Arabic, keep numbers."</li><li><b>Checker:</b> "Verify every number against the source and list mismatches."</li></ul>`,`<ul><li><b>المحاوِر:</b> "اسألني سؤال سؤال لحد ما يبقى عندك كفاية تبني X."</li><li><b>الناقد:</b> "راجع ده كمدير مالي متشكك. اكتب أضعف 5 نقط."</li><li><b>الفريق الأحمر:</b> "إيه اللي ممكن يخلي التوقع ده غلط؟"</li><li><b>البدائل:</b> "ادّيني 3 طرق بالمزايا والعيوب وإمتى أختار كل واحدة."</li><li><b>ملء القالب:</b> "املا القالب ده بالظبط؛ واكتب [ناقص] لو مفيش بيانات."</li><li><b>المعلّم:</b> "اشرح كأني محلل جديد، وبعدين اختبرني بـ 3 أسئلة."</li><li><b>المترجم:</b> "اعد الكتابة لجمهور مجلس إدارة بالعربي، وخلي الأرقام زي ما هي."</li><li><b>المدقق:</b> "راجع كل رقم على المصدر وطلّع الاختلافات."</li></ul>`)},
 {h:T("Fixing a bad answer","تصليح إجابة وحشة"),b:T(`<ul><li><b>Edit your original message</b> instead of adding corrections below — it replaces the bad branch and keeps context clean.</li><li>Name the exact gap: "Section 2 ignores FX; redo only section 2."</li><li>Give a sample of the output you wanted.</li><li>If three tries fail, start a new chat with a better prompt and the hand-off summary.</li></ul>`,`<ul><li><b>عدّل رسالتك الأصلية</b> بدل ما تضيف تصليحات تحت — كده بتشيل الفرع الغلط والسياق يفضل نضيف.</li><li>سمّي الفجوة بالظبط: "الجزء 2 متجاهل سعر الصرف؛ اعد الجزء 2 بس."</li><li>ادّيله عينة من الشكل اللي عايزه.</li><li>لو 3 محاولات فشلوا، ابدأ محادثة جديدة ببرومبت أحسن وملخص التسليم.</li></ul>`)}
 ],cases:[]},
tokens:{icon:"◐",t:T("Tokens & context — save usage, keep quality","التوكنز والسياق — وفّر الاستهلاك وحافظ على الجودة"),sub:T("How usage works, and 20 habits that keep it low.","الاستهلاك بيشتغل إزاي، و 20 عادة تقلّله."),
 sections:[
 {h:T("How usage really works","الاستهلاك بيشتغل إزاي فعلاً"),b:T(`<p>Every reply re-reads <b>everything in context</b>: instructions, project files, memory, connector tool definitions, attachments, the full conversation and Claude's own long answers. So message 30 of a chat costs far more than message 3. Thinking, agentic steps (Cowork, Claude Code, Chrome) and large files multiply this. Arabic text usually takes more tokens per word than English.</p>`,`<p>كل رد بيعيد قراية <b>كل اللي في السياق</b>: التعليمات، ملفات المشروع، الذاكرة، تعريفات أدوات الـ Connectors، المرفقات، المحادثة كلها وردود Claude الطويلة. فالرسالة رقم 30 بتكلّف أكتر بكتير من الرسالة رقم 3. والتفكير والخطوات الوكيلية (Cowork و Claude Code و Chrome) والملفات الكبيرة بيضاعفوا ده. والنص العربي غالباً بياخد توكنز أكتر للكلمة من الإنجليزي.</p>`)},
 {h:T("Conversation habits","عادات المحادثة"),b:T(`<ol><li>One task = one chat. Start fresh when the topic changes.</li><li>When a chat gets long, ask for a hand-off summary and continue in a new chat.</li><li>Edit your earlier message instead of stacking corrections.</li><li>Ask for short outputs: "max 200 words", "table only", "no preamble".</li><li>Ask for diffs: "only change section 3" instead of "rewrite everything".</li><li>Don't re-paste the same document — reference it or put it in a Project.</li><li>Batch questions into one message rather than five small ones.</li></ol>`,`<ol><li>مهمة واحدة = محادثة واحدة. ابدأ جديد لما الموضوع يتغيّر.</li><li>لما المحادثة تطول، اطلب ملخص تسليم وكمّل في محادثة جديدة.</li><li>عدّل رسالتك القديمة بدل ما تكوّم تصليحات.</li><li>اطلب مخرجات قصيرة: "أقصى 200 كلمة"، "جدول بس"، "من غير مقدمة".</li><li>اطلب تعديل جزئي: "غيّر الجزء 3 بس" بدل "اكتب كل حاجة من الأول".</li><li>متلصقش نفس المستند تاني — اشير له أو حطه في Project.</li><li>اجمع الأسئلة في رسالة واحدة بدل 5 رسايل صغيرة.</li></ol>`)},
 {h:T("Files & projects","الملفات والمشاريع"),b:T(`<ol start="8"><li>Upload only the sheets/pages you need; export one tab to CSV instead of a 40-tab workbook.</li><li>Convert scanned PDFs to text once, keep the text.</li><li>Keep Project knowledge lean — every file is loaded into every chat in that project.</li><li>Put standing rules in Project instructions or a Skill, not in every message.</li><li>Prefer Skills for repeat methods: they load only when triggered.</li></ol>`,`<ol start="8"><li>ارفع الشيتات/الصفحات اللي محتاجها بس؛ صدّر شيت واحد CSV بدل ملف فيه 40 شيت.</li><li>حوّل الـ PDF المصوّر لنص مرة واحدة واحتفظ بالنص.</li><li>خلي معرفة المشروع خفيفة — كل ملف بيتحمّل في كل محادثة جوه المشروع.</li><li>حط القواعد الثابتة في تعليمات المشروع أو Skill، مش في كل رسالة.</li><li>فضّل الـ Skills للطرق المتكررة: بتتحمّل بس لما تتطلب.</li></ol>`)},
 {h:T("Tools, models & agents","الأدوات والموديلات والوكلاء"),b:T(`<ol start="13"><li>Turn off connectors and tools you don't need in this chat.</li><li>Use Sonnet as default; Haiku for bulk; Opus/Fable only when needed.</li><li>Lower effort for simple tasks.</li><li>In Cowork, give one well-scoped task with a clear stop condition — vague tasks wander.</li><li>Claude Code: keep CLAUDE.md short, <code>/context</code> to inspect, <code>/compact</code> around 70%, <code>/clear</code> between tasks, use subagents for exploration so the main context stays clean.</li></ol>`,`<ol start="13"><li>اقفل الـ Connectors والأدوات اللي مش محتاجها في المحادثة دي.</li><li>Sonnet الافتراضي؛ Haiku للشغل الكمّي؛ Opus/Fable وقت الحاجة بس.</li><li>قلّل الـ Effort في المهام البسيطة.</li><li>في Cowork، ادّي مهمة واحدة محددة بشرط توقف واضح — المهام المطاطة بتلف.</li><li>Claude Code: خلي CLAUDE.md قصير، <code>/context</code> للمراجعة، <code>/compact</code> حوالين 70%، <code>/clear</code> بين المهام، واستخدم subagents للاستكشاف علشان السياق الرئيسي يفضل نضيف.</li></ol>`)},
 {h:T("API cost levers","أدوات توفير الـ API"),b:T(`<ol start="18"><li><b>Prompt caching</b> for long repeated system prompts (cache reads ≈ 0.1× input price).</li><li><b>Batches</b> for non-urgent bulk jobs (50% off).</li><li><b>Structured outputs</b> to avoid retries from malformed JSON.</li></ol>`,`<ol start="18"><li><b>التخزين المؤقت</b> للبرومبتات الطويلة المتكررة (القراءة من الكاش ≈ 0.1 من سعر الإدخال).</li><li><b>Batches</b> للشغل الكمّي غير العاجل (خصم 50%).</li><li><b>المخرجات المهيكلة</b> علشان تتجنب إعادة المحاولة بسبب JSON بايظ.</li></ol>`)}
 ],cases:[]},
cowork:{icon:"◉",t:T("Cowork — deep dive","Cowork — تعمق"),sub:T("Your agent for files, tools and multi-step work.","وكيلك للملفات والأدوات والشغل متعدد الخطوات."),
 sections:[
 {h:T("Chat vs Cowork vs Claude Code","الشات مقابل Cowork مقابل Claude Code"),b:T(`<table><tr><th></th><th>Chat</th><th>Cowork</th><th>Claude Code</th></tr><tr><td>Best for</td><td>Questions, drafts, analysis</td><td>Multi-step knowledge work on files and apps</td><td>Building software and scripts</td></tr><tr><td>Works on</td><td>Uploads, connectors</td><td>Local folders, connectors, browser, computer</td><td>Code repositories, terminal</td></tr><tr><td>Output</td><td>Answers, artifacts, files</td><td>Finished files in your folder, scheduled results</td><td>Code, commits, PRs</td></tr><tr><td>Who</td><td>Everyone</td><td>Analysts, managers, operations</td><td>Builders, technical users</td></tr></table>`,`<table><tr><th></th><th>الشات</th><th>Cowork</th><th>Claude Code</th></tr><tr><td>الأنسب لـ</td><td>أسئلة ومسودات وتحليل</td><td>شغل معرفي متعدد الخطوات على ملفات وبرامج</td><td>بناء برامج وسكريبتات</td></tr><tr><td>بيشتغل على</td><td>المرفقات والـ Connectors</td><td>فولدرات محلية و Connectors ومتصفح وكمبيوتر</td><td>مستودعات الكود والـ Terminal</td></tr><tr><td>المخرج</td><td>إجابات و Artifacts وملفات</td><td>ملفات جاهزة في فولدرك ونتايج مجدولة</td><td>كود و commits و PRs</td></tr><tr><td>لمين</td><td>للكل</td><td>المحللين والمديرين والعمليات</td><td>المطوّرين والتقنيين</td></tr></table>`)},
 {h:T("A good Cowork brief","تكليف Cowork الكويس"),b:T(`<ol><li><b>Outcome:</b> the files you want and where.</li><li><b>Inputs:</b> folder, connectors, links.</li><li><b>Rules:</b> naming, currency, language, what never to touch.</li><li><b>Checkpoints:</b> "show me the plan first", "ask before sending/deleting/posting".</li><li><b>Done:</b> the checklist.</li></ol>`,`<ol><li><b>النتيجة:</b> الملفات اللي عايزها وفين.</li><li><b>المدخلات:</b> الفولدر والـ Connectors واللينكات.</li><li><b>القواعد:</b> التسمية، العملة، اللغة، اللي ممنوع يتلمس.</li><li><b>نقاط التوقف:</b> "وريني الخطة الأول"، "اسأل قبل الإرسال/المسح/الترحيل".</li><li><b>الانتهاء:</b> قائمة المراجعة.</li></ol>`)},
 {h:T("Scheduled tasks & Dispatch","المهام المجدولة و Dispatch"),b:T(`<p>Turn any repeatable Cowork task into a schedule (daily, weekly). Use Dispatch from your phone to start a task on your desktop while you're out — the computer must stay awake. Good schedules: Monday brief, Friday KPI pack, daily regulator watch, month-end checklist reminders.</p>`,`<p>حوّل أي مهمة Cowork متكررة لجدول (يومي، أسبوعي). واستخدم Dispatch من الموبايل تبدأ مهمة على الكمبيوتر وإنت برّه — بشرط الكمبيوتر يفضل صاحي. جداول مفيدة: ملخص الإتنين، حزمة مؤشرات الجمعة، متابعة التعليمات الرقابية يومياً، تذكير قائمة إقفال الشهر.</p>`)}
 ],
 cases:[
 XL("Course content factory","مصنع محتوى الكورس",["Folder with outline + brand","Ask for module files","Review and publish"],["فولدر فيه المخطط والبراند","اطلب ملفات الوحدات","راجع وانشر"],`In folder "Course_Claude", read Outline.md and Brand.md. For each module create: a 2-page Arabic handout (docx), a 6-slide deck (pptx) in the brand template, and 10 quiz questions (xlsx). Save in /Module_[n]. Show me the plan for module 1 first.`,`في فولدر "Course_Claude" اقرا Outline.md و Brand.md. لكل وحدة اعمل: ملزمة عربي صفحتين (docx)، عرض 6 شرائح (pptx) بقالب البراند، و 10 أسئلة اختبار (xlsx). احفظهم في /Module_[n]. وريني خطة الوحدة الأولى الأول.`),
 XL("Receipt & expense sorting","فرز الإيصالات والمصاريف",["Drop photos in a folder","Ask for extraction","Review the summary"],["حط الصور في فولدر","اطلب الاستخراج","راجع الملخص"],`Read every receipt image in "Receipts_Sep". Extract date, vendor, amount, currency, VAT and category into Expenses_Sep.xlsx, convert to EGP at the rate in rates.csv, and list unreadable receipts separately. Rename each image as YYYY-MM-DD_vendor_amount.`,`اقرا كل صورة إيصال في "Receipts_Sep". طلّع التاريخ والمورد والمبلغ والعملة والضريبة والفئة في Expenses_Sep.xlsx، وحوّل للجنيه بسعر rates.csv، واكتب الإيصالات المش مقروءة لوحدها. وسمّي كل صورة YYYY-MM-DD_المورد_المبلغ.`),
 XL("Competitor deal-pricing review","مراجعة تسعير المنافسين",["Give links/files","Ask for comparison","Ask for pricing engine update"],["ادّي اللينكات/الملفات","اطلب المقارنة","اطلب تحديث محرك التسعير"],`Compare our discount grid (pricing.xlsx) with the three competitor offers in "Competitors". Build a comparison table and recommend changes to discount tiers with margin impact. Update a copy of pricing.xlsx, never the original.`,`قارن جدول الخصومات بتاعنا (pricing.xlsx) بعروض المنافسين التلاتة في "Competitors". اعمل جدول مقارنة واقترح تعديلات على شرائح الخصم بأثرها على الهامش. حدّث نسخة من pricing.xlsx، مش الأصل.`)
 ]},
memory:{icon:"◎",t:T("Memory — deep dive","الذاكرة — تعمق"),sub:T("Make Claude remember the right things, and only those.","خلّي Claude يفتكر الحاجات الصح، وبس."),
 sections:[
 {h:T("Three layers of memory","3 طبقات للذاكرة"),b:T(`<ol><li><b>Account memory</b> — facts about you and your work, across chats.</li><li><b>Project memory</b> — scoped to one project; can be kept separate from your general memory.</li><li><b>Claude Code memory</b> — CLAUDE.md files (project and user level) loaded every session.</li></ol><p>Plus <b>past-chat search</b> for retrieval, and <b>incognito</b> for nothing saved to memory.</p>`,`<ol><li><b>ذاكرة الحساب</b> — معلومات عنك وعن شغلك في كل المحادثات.</li><li><b>ذاكرة المشروع</b> — خاصة بمشروع واحد؛ وممكن تفضل منفصلة عن ذاكرتك العامة.</li><li><b>ذاكرة Claude Code</b> — ملفات CLAUDE.md (للمشروع وللمستخدم) بتتحمّل كل جلسة.</li></ol><p>وكمان <b>البحث في المحادثات القديمة</b> للاسترجاع، و<b>المتخفي</b> علشان مفيش حاجة تتحفظ.</p>`)},
 {h:T("What to remember — and what not","تفتكر إيه — وإيه لأ"),b:T(`<div class="vs"><div class="good"><b>Good to remember</b><p>Your role, reporting conventions, preferred language and format, recurring projects, brand colors, citation style.</p></div><div class="bad"><b>Keep out</b><p>Passwords, ID or account numbers, client personal data, salaries of named people, anything confidential you wouldn't put on a shared drive.</p></div></div>`,`<div class="vs"><div class="good"><b>كويس يتفتكر</b><p>دورك، طريقة تقاريرك، اللغة والشكل المفضّل، المشاريع المتكررة، ألوان البراند، أسلوب المراجع.</p></div><div class="bad"><b>بعّده</b><p>كلمات السر، أرقام الهوية أو الحسابات، بيانات العملاء الشخصية، مرتبات أشخاص بالاسم، أي حاجة سرية مش هتحطها على درايف مشترك.</p></div></div>`)},
 {h:T("Maintenance routine","روتين الصيانة"),b:T(`<ul><li>Monthly: open Settings → Memory, delete stale items.</li><li>When a fact changes, tell Claude: "Update: our fiscal year now ends in December."</li><li>To forget: "Forget what I said about project X."</li><li>Start a client engagement with a project that has its own memory.</li></ul>`,`<ul><li>كل شهر: افتح Settings ← Memory وامسح القديم.</li><li>لما معلومة تتغير قول: "تحديث: سنتنا المالية بقت بتخلص في ديسمبر."</li><li>علشان ينسى: "انسى اللي قلته عن مشروع X."</li><li>ابدأ أي شغل مع عميل بـ Project ليه ذاكرة خاصة.</li></ul>`)}
 ],cases:[]},
projects:{icon:"▥",t:T("Projects — deep dive","Projects — تعمق"),sub:T("Templates for 10 professional projects.","قوالب لـ 10 مشاريع احترافية."),
 sections:[
 {h:T("Anatomy of a great project","تشريح مشروع ممتاز"),b:T(`<ul><li><b>Name:</b> specific ("ACME — FY27 Budget", not "Work").</li><li><b>Instructions (150–300 words):</b> role, audience, conventions, language rule, what to always do, what never to do, when to ask.</li><li><b>Knowledge (3–10 files):</b> stable references only.</li><li><b>Chats:</b> one per deliverable.</li><li><b>Review:</b> quarterly trim.</li></ul>`,`<ul><li><b>الاسم:</b> محدد ("ACME — موازنة 2027" مش "شغل").</li><li><b>التعليمات (150–300 كلمة):</b> الدور، الجمهور، الأعراف، قاعدة اللغة، اللي يتعمل دايماً، اللي ممنوع، إمتى يسأل.</li><li><b>المعرفة (3–10 ملفات):</b> مراجع ثابتة بس.</li><li><b>المحادثات:</b> واحدة لكل مخرج.</li><li><b>المراجعة:</b> تنضيف كل ربع سنة.</li></ul>`)},
 {h:T("10 project blueprints","10 نماذج مشاريع"),b:T(`<table><tr><th>Project</th><th>Knowledge</th><th>Key instruction</th></tr>
<tr><td>Monthly FP&A pack</td><td>CoA, budget, last pack</td><td>Always compare to budget and LY</td></tr>
<tr><td>LC desk</td><td>UCP 600/ISBP notes, checklist</td><td>Mark findings "for examiner review"</td></tr>
<tr><td>Credit committee</td><td>Policy, memo template</td><td>Use bank limits; flag estimates</td></tr>
<tr><td>Board secretary</td><td>Prior minutes, charter</td><td>Formal Arabic, decisions table</td></tr>
<tr><td>HR policies</td><td>Handbook, labour-law notes</td><td>Cite section; escalate legal questions</td></tr>
<tr><td>Brand content</td><td>Brand book, best posts</td><td>Egyptian dialect, hooks first</td></tr>
<tr><td>Sales accounts</td><td>Offers, case studies</td><td>Personalize per client</td></tr>
<tr><td>Course building</td><td>Outline, brand, prompt library</td><td>Bilingual, practical, ROI-first</td></tr>
<tr><td>Doctoral thesis</td><td>Proposal, literature matrix</td><td>APA 7, real references only</td></tr>
<tr><td>Client X engagement</td><td>Contract, scope, data room index</td><td>Never mix with other clients</td></tr></table>`,`<table><tr><th>المشروع</th><th>المعرفة</th><th>التعليمة الأساسية</th></tr>
<tr><td>حزمة FP&A الشهرية</td><td>دليل الحسابات، الموازنة، آخر تقرير</td><td>قارن دايماً بالموازنة والسنة اللي فاتت</td></tr>
<tr><td>مكتب الاعتمادات</td><td>ملاحظات UCP 600 و ISBP، قائمة المراجعة</td><td>اكتب "لمراجعة الفاحص" على كل ملاحظة</td></tr>
<tr><td>لجنة الائتمان</td><td>السياسة، قالب المذكرة</td><td>استخدم حدود البنك؛ علّم على التقديرات</td></tr>
<tr><td>أمانة المجلس</td><td>المحاضر السابقة، اللائحة</td><td>عربي رسمي وجدول قرارات</td></tr>
<tr><td>سياسات الموارد البشرية</td><td>دليل الموظفين، ملاحظات قانون العمل</td><td>اذكر البند؛ وصعّد الأسئلة القانونية</td></tr>
<tr><td>محتوى البراند</td><td>دليل البراند، أحسن البوستات</td><td>لهجة مصرية، والـ Hook الأول</td></tr>
<tr><td>حسابات المبيعات</td><td>العروض، دراسات الحالة</td><td>خصّص لكل عميل</td></tr>
<tr><td>بناء الكورس</td><td>المخطط، البراند، مكتبة البرومبتات</td><td>ثنائي اللغة، عملي، العائد أولاً</td></tr>
<tr><td>رسالة الدكتوراه</td><td>الخطة البحثية، مصفوفة الأدبيات</td><td>APA 7 ومراجع حقيقية بس</td></tr>
<tr><td>عميل X</td><td>العقد، النطاق، فهرس البيانات</td><td>متخلطش مع عملاء تانيين أبداً</td></tr></table>`)}
 ],cases:[]},
capabilities:{icon:"✺",t:T("Capabilities map — what Claude can do","خريطة القدرات — Claude يقدر يعمل إيه"),sub:T("Every capability, where it lives and what to use it for.","كل قدرة، موجودة فين، وتستخدمها في إيه."),
 sections:[{h:T("Capability matrix","مصفوفة القدرات"),b:T(`<table><tr><th>Capability</th><th>Where</th><th>Business use</th></tr>
<tr><td>Read & analyze files (PDF, Excel, images)</td><td>Chat, Projects</td><td>Statements, contracts, invoices</td></tr>
<tr><td>Web search & Research</td><td>Chat</td><td>Market scans, regulations, competitors</td></tr>
<tr><td>Create real files</td><td>Chat (code execution)</td><td>xlsx models, docx memos, pptx decks, pdf</td></tr>
<tr><td>Artifacts</td><td>Chat</td><td>Calculators, dashboards, training apps</td></tr>
<tr><td>Docs & Slides (beta)</td><td>Claude app</td><td>Co-written documents, presentable decks</td></tr>
<tr><td>Design (beta)</td><td>claude.ai/design</td><td>Flyers, decks, prototypes, brand systems</td></tr>
<tr><td>Projects</td><td>Claude app</td><td>Ongoing clients, reports, courses</td></tr>
<tr><td>Memory & past-chat search</td><td>Claude app</td><td>Consistency, retrieval</td></tr>
<tr><td>Styles</td><td>Claude app</td><td>Brand and audience voice</td></tr>
<tr><td>Skills</td><td>App, Code, API</td><td>Repeatable methods</td></tr>
<tr><td>Plugins</td><td>App, Cowork, Code</td><td>Role bundles (finance, sales, HR…)</td></tr>
<tr><td>Connectors (MCP)</td><td>Everywhere</td><td>Drive, Gmail, CRM, ERP, data vendors</td></tr>
<tr><td>Cowork, schedules, Dispatch</td><td>Desktop (web/mobile beta)</td><td>Month-end, digests, file work</td></tr>
<tr><td>Computer use (beta)</td><td>Cowork, API</td><td>Apps without connectors</td></tr>
<tr><td>Excel, PowerPoint, Word, Outlook</td><td>Microsoft 365</td><td>Models, decks, documents, inbox</td></tr>
<tr><td>Chrome agent</td><td>Chrome</td><td>Portals, forms, web research</td></tr>
<tr><td>Claude Tag</td><td>Slack (Team/Ent.)</td><td>Team requests, channel digests</td></tr>
<tr><td>Claude Code</td><td>Terminal, IDE, web, desktop</td><td>Scripts, tools, websites</td></tr>
<tr><td>API, Agent SDK, Managed Agents</td><td>Developer platform</td><td>Products, pipelines, agents</td></tr>
<tr><td>Voice & mobile</td><td>iOS, Android</td><td>Dictation, approvals on the go</td></tr></table>`,`<table><tr><th>القدرة</th><th>فين</th><th>الاستخدام في البيزنس</th></tr>
<tr><td>قراءة وتحليل الملفات (PDF و Excel وصور)</td><td>الشات، Projects</td><td>قوائم، عقود، فواتير</td></tr>
<tr><td>البحث و Research</td><td>الشات</td><td>مسح السوق، اللوائح، المنافسين</td></tr>
<tr><td>إنشاء ملفات حقيقية</td><td>الشات (تنفيذ الكود)</td><td>نماذج xlsx، مذكرات docx، عروض pptx، pdf</td></tr>
<tr><td>Artifacts</td><td>الشات</td><td>حاسبات، داشبوردات، تطبيقات تدريب</td></tr>
<tr><td>Docs و Slides (بيتا)</td><td>تطبيق Claude</td><td>مستندات مشتركة، عروض تقديمية</td></tr>
<tr><td>Design (بيتا)</td><td>claude.ai/design</td><td>فلايرز، عروض، نماذج، أنظمة براند</td></tr>
<tr><td>Projects</td><td>تطبيق Claude</td><td>عملاء مستمرين، تقارير، كورسات</td></tr>
<tr><td>الذاكرة والبحث في المحادثات</td><td>تطبيق Claude</td><td>اتساق واسترجاع</td></tr>
<tr><td>Styles</td><td>تطبيق Claude</td><td>صوت البراند والجمهور</td></tr>
<tr><td>Skills</td><td>التطبيق، Code، API</td><td>طرق متكررة</td></tr>
<tr><td>Plugins</td><td>التطبيق، Cowork، Code</td><td>حزم وظيفية (مالية، مبيعات، HR…)</td></tr>
<tr><td>Connectors (MCP)</td><td>في كل مكان</td><td>Drive و Gmail و CRM و ERP ومزوّدي البيانات</td></tr>
<tr><td>Cowork والجدولة و Dispatch</td><td>الديسكتوب (الويب والموبايل بيتا)</td><td>إقفال الشهر، ملخصات، شغل الملفات</td></tr>
<tr><td>استخدام الكمبيوتر (بيتا)</td><td>Cowork، API</td><td>برامج مفيهاش Connector</td></tr>
<tr><td>Excel و PowerPoint و Word و Outlook</td><td>Microsoft 365</td><td>نماذج، عروض، مستندات، بريد</td></tr>
<tr><td>وكيل Chrome</td><td>Chrome</td><td>بوابات، فورمز، بحث ويب</td></tr>
<tr><td>Claude Tag</td><td>Slack (Team/Ent.)</td><td>طلبات الفريق، ملخصات القنوات</td></tr>
<tr><td>Claude Code</td><td>Terminal، IDE، ويب، ديسكتوب</td><td>سكريبتات، أدوات، مواقع</td></tr>
<tr><td>API و Agent SDK و Managed Agents</td><td>منصة المطورين</td><td>منتجات، خطوط معالجة، وكلاء</td></tr>
<tr><td>الصوت والموبايل</td><td>iOS و Android</td><td>إملاء، موافقات وإنت ماشي</td></tr></table>`)}],cases:[]}
};
