// ---------- Round 9: month-end simulation, agent hand-off chains, CFO capstone (finance department tabs) + module cheat sheets ----------
const UX17={dept:T('Departments','الوظائف'),sim:T('Month-end simulation','محاكاة نهاية الشهر'),chains:T('Hand-off chains','سلاسل التسليم'),cap:T('CFO capstone','مشروع المدير المالي'),cheat:T('Cheat sheet (1 page)','ملخص في صفحة')};
let FDTAB='dept';

// ---------- 2. Month-end simulation: one fictional company, five agents in order ----------
const SIMCO={name:T('Sahel Trading (fictional)','شركة الساحل للتجارة (افتراضية)'),about:T('A food distributor in Egypt with 140 staff, selling to supermarkets and wholesalers. Month: September 2026. Amounts in EGP thousands.','موزع أغذية في مصر فيه 140 موظف، بيبيع للسوبر ماركت وتجار الجملة. الشهر: سبتمبر 2026. المبالغ بالألف جنيه.'),
data:{
pl:'line,budget_egp_k,actual_egp_k\nRevenue,12400,11850\nCost of goods sold,8680,8450\nSalaries,1350,1410\nRent,280,280\nLogistics,520,610\nMarketing,300,190\nOther opex,240,265\nDepreciation,150,150\nFinance cost,210,235',
bank:'source,date,reference,description,amount_egp_k\nBank,2026-09-28,DEP-118,Customer receipt Hyper One,640\nGL,2026-09-28,DEP-118,Customer receipt Hyper One,640\nBank,2026-09-29,CHG-09,Bank charges September,-18\nGL,2026-09-30,DEP-121,Customer receipt Al Fajr Market,410\nBank,2026-09-30,TRF-552,Unidentified incoming transfer,95\nGL,2026-09-30,PAY-731,Supplier payment Delta Packaging,-260\nGL,2026-09-30,PAY-731,Supplier payment Delta Packaging,-260\nBank,2026-09-30,PAY-731,Supplier payment Delta Packaging,-260\nBalances,2026-09-30,,Bank statement closing 6265 / GL cash closing 6533,',
ar:'customer,invoice,amount_egp_k,due_date,days_overdue\nHyper One,INV-901,820,2026-08-15,46\nAl Fajr Market,INV-905,410,2026-09-10,20\nGreen Basket,INV-873,1150,2026-07-20,72\nNour Wholesale,INV-911,560,2026-09-25,5\nMetro Stores,INV-868,300,2026-07-05,87\nCity Mart,INV-915,240,2026-10-05,0',
cash:'item,value\nOpening bank balance (after reconciliation),[from step 1]\nMinimum cash buffer,2000\nWeekly supplier payments,1900\nMonthly payroll (paid in week 4 of each month),1410\nMonthly rent (week 1),280\nLoan instalment (week 6),900\nVAT payment (week 3),350\nWeekly cash sales and new collections (base),2050'}};
const SIMSTEPS=[
{a:'bank-reconciler',d:['bank'],t:T('Reconcile the September bank account to the GL. List every difference, classify it (timing, error, unrecorded), propose adjusting entries for review, and give the reconciled cash balance.','طابق حساب البنك لشهر سبتمبر مع دفتر الأستاذ. اكتب كل فرق، وصنّفه (توقيت، خطأ، مش متسجل)، واقترح قيود تسوية للمراجعة، واِدّي رصيد الكاش بعد التسوية.')},
{a:'management-accounts-preparer',d:['pl'],t:T('Prepare September management accounts: P&L vs budget with gross margin and EBITDA, including the adjustments proposed in step 1. Flag anything that needs a decision.','جهّز حسابات الإدارة لشهر سبتمبر: قائمة الدخل قصاد الموازنة بهامش الربح الإجمالي والـ EBITDA، ومعاها قيود التسوية المقترحة في الخطوة 1. علّم أي حاجة محتاجة قرار.')},
{a:'variance-analyst',d:['pl'],t:T('Explain the budget-versus-actual variances in the management accounts from step 2: volume/price/cost drivers for revenue and gross margin, and the three biggest opex variances, with a materiality threshold of 5% or EGP 50k.','اشرح فروق الموازنة قصاد الفعلي في حسابات الإدارة من الخطوة 2: محركات الكمية والسعر والتكلفة للإيراد والهامش، وأكبر 3 فروق في المصروفات التشغيلية، بحد أهمية نسبية 5% أو 50 ألف جنيه.')},
{a:'cash-forecaster',d:['ar','cash'],t:T('Build a 13-week direct cash-flow forecast starting 1 October 2026, using the reconciled opening balance from step 1, the AR aging and the cash assumptions. Show the weeks below the EGP 2,000k buffer and the collection actions that fix them, using the variance notes from step 3.','اعمل توقع تدفق نقدي مباشر لـ 13 أسبوع يبدأ 1 أكتوبر 2026، برصيد الافتتاح بعد التسوية من الخطوة 1، وأعمار الديون، وافتراضات الكاش. وضّح الأسابيع اللي تحت حد الأمان 2 مليون جنيه وإجراءات التحصيل اللي تعالجها، مستعين بملاحظات الفروق من الخطوة 3.')},
{a:'board-report-writer',d:[],t:T('Write a one-page board report for September from steps 2–4: headline results, KPIs vs target, cash outlook, top 3 risks with mitigations, decisions requested, and an appendix of anticipated board questions with answers.','اكتب تقرير مجلس إدارة في صفحة لشهر سبتمبر من الخطوات 2–4: النتائج الرئيسية، المؤشرات قصاد المستهدف، نظرة الكاش، أكبر 3 مخاطر وإزاي نعالجها، القرارات المطلوبة، وملحق بأسئلة المجلس المتوقعة وإجاباتها.')}];
let SIM=Object.assign({i:0,out:['','','','',''],chk:{},busy:false},ST.fsim||{});
function saveSIM(){const {busy,...r}=SIM;ST.fsim=r;saveST()}
function simPrompt(i,lang){const st=SIMSTEPS[i];const [f,a]=fdFind(st.a);if(!a)return '';const en=lang==='en';
const prev=i===0?'':SIMSTEPS.slice(0,i).map((s,k)=>`### ${en?'Output of step':'مخرج الخطوة'} ${k+1} — ${fdFind(s.a)[1].n[lang]}\n${SIM.out[k].trim()||(en?`[paste the output of step ${k+1} here]`:`[الصق مخرج الخطوة ${k+1} هنا]`)}`).join('\n\n');
return fdPrompt(a,f,lang)+`\n\n---\n${en?'TODAY’S TASK':'مهمة النهارده'} — ${SIMCO.name[lang]}\n${SIMCO.about[lang]}\n\n${st.t[lang]}\n\n${st.d.map(k=>`### ${k}.csv\n${SIMCO.data[k]}`).join('\n\n')}${prev?'\n\n'+prev:''}`}
function simDone(i){const st=SIMSTEPS[i];const sk=fdSkill(fdFind(st.a)[1].sk);const n=sk?fdList(sk.checks.en).length:0;return !!SIM.out[i].trim()&&[...Array(n).keys()].every(c=>SIM.chk[i+'_'+c])}
function vSim5(){const ar=LANG==='ar';const lang=ar?'ar':'en';const i=Math.min(SIM.i,4);const st=SIMSTEPS[i];const [f,a]=fdFind(st.a);if(!a)return '';const sk=fdSkill(a.sk);const done=SIMSTEPS.map((_,k)=>simDone(k));const all=done.every(Boolean);
const pi=PSTORE.push(simPrompt(i,lang))-1;
let h=`<p class="lede">${ar?'شغّل 5 وكلاء بالترتيب على شركة واحدة افتراضية، زي إقفال شهر حقيقي. مخرج كل خطوة بيدخل في اللي بعدها. شغّل الخطوة مع Claude أو انسخ البرومبت والصق الرد.':'Run five agents in order on one fictional company, like a real month-end. Each step’s output feeds the next. Run a step with Claude, or copy the prompt and paste the answer back.'}</p>
<div class="card simco"><b>🏢 ${L(SIMCO.name)}</b><p class="k">${L(SIMCO.about)}</p></div>
<ol class="simrail">${SIMSTEPS.map((s,k)=>{const x=fdFind(s.a);return `<li class="${k===i?'on':''} ${done[k]?'done':''}"><button data-simi="${k}"><span>${done[k]?'✓':k+1}</span>${x[0].icon} ${esc(L(x[1].n))}</button></li>`}).join('')}</ol>
${all?`<div class="simwin">🏆 ${ar?'خلّصت إقفال الشهر بالـ 5 وكلاء! نزّل الملف كامل تحت.':'You completed the month-end with all five agents! Download the full pack below.'}</div>`:''}
<section class="card"><div class="k">${ar?'الخطوة':'Step'} ${i+1}/5 · ${L(f.t)}</div><h2 style="margin-top:4px">${f.icon} ${L(a.n)}</h2><p><b>${ar?'المطلوب:':'Task:'}</b> ${esc(L(st.t))}</p>
${st.d.length?`<details class="fdsp"><summary>📊 ${ar?'بيانات الشركة للخطوة دي':'Company data for this step'}</summary>${st.d.map(k=>`<h4>${k}.csv</h4><pre dir="ltr">${esc(SIMCO.data[k])}</pre>`).join('')}</details>`:''}
${i>0?`<p class="k">↪ ${ar?'البرومبت بيضم مخرجات الخطوات اللي فاتت تلقائيًا.':'The prompt includes the outputs of the previous steps automatically.'} ${SIMSTEPS.slice(0,i).map((_,k)=>SIM.out[k].trim()?'✓':'✗').join(' ')}</p>`:''}
<details class="fdsp"><summary>🧠 ${ar?'البرومبت الكامل (system prompt + مهمة + بيانات)':'Full prompt (system prompt + task + data)'}</summary><pre dir="auto">${esc(simPrompt(i,lang))}</pre></details>
<div class="row-btns"><button class="btn-gold" data-sim="run" ${SIM.busy?'disabled':''}>${SIM.busy?(ar?'Claude شغال…':'Claude is working…'):'▶ '+(ar?'شغّل الخطوة مع Claude':'Run this step with Claude')}</button><button class="copy" data-i="${pi}">${ar?'انسخ البرومبت':'Copy prompt'}</button></div><p class="note" id="simnote"></p>
<label class="pbf"><b>${ar?'مخرج الخطوة (من Claude أو الصقه)':'Step output (from Claude, or paste it)'}</b><textarea class="search" id="simout" rows="10" dir="auto">${esc(SIM.out[i])}</textarea></label>
${sk?`<h3>✅ ${ar?'راجع قبل ما تسلّم للخطوة اللي بعدها':'Check before you hand over'}</h3><div class="simchk">${fdList(L(sk.checks)).map((c,k)=>`<label><input type="checkbox" data-simc="${i}_${k}" ${SIM.chk[i+'_'+k]?'checked':''}> ${esc(c)}</label>`).join('')}</div>`:''}
<div class="row-btns"><button class="tbtn" data-simi="${Math.max(0,i-1)}" ${i===0?'disabled':''}>${ar?'→ اللي قبلها':'← Previous'}</button><button class="btn-gold" data-simi="${Math.min(4,i+1)}" ${i===4||!done[i]?'disabled':''}>${ar?'سلّم للخطوة اللي بعدها ←':'Hand over to next step →'}</button>${done.some(Boolean)?`<button class="tbtn" data-sim="dl">⬇ ${ar?'ملف الإقفال (MD)':'Month-end pack (MD)'}</button>`:''}<button class="tbtn" data-sim="reset">${ar?'ابدأ من الأول':'Start over'}</button></div></section>`;
return h}
async function simRun(){const ar=LANG==='ar';const n=t=>{const e=document.getElementById('simnote');if(e)e.textContent=t};const i=SIM.i;
if(i>0&&!SIM.out[i-1].trim()){n(ar?'كمّل الخطوة اللي قبلها الأول.':'Complete the previous step first.');return}
const sample=await tutorSample();if(!sample){n(ar?'التشغيل مع Claude بيشتغل لما المنصة تتفتح جوه Claude (claude.ai). تقدر تنسخ البرومبت وتلصق الرد.':'Running with Claude works when the platform is opened inside Claude (claude.ai). You can copy the prompt and paste the answer.');return}
SIM.busy=true;render();try{const {text}=await sample(simPrompt(i,ar?'ar':'en')+'\n\n'+(ar?'اكتب المخرج بشكل مختصر (أقل من 450 كلمة) بجداول Markdown.':'Keep the output concise (under 450 words) with Markdown tables.'),{modelTier:'default',onText:({text})=>{const b=document.getElementById('simout');if(b)b.value=text}});SIM.out[i]=text||''}
catch(e){n(e&&e.code==='rate_limited'?(ar?'طلبات كتير — جرّب بعد شوية.':'Too many requests — try again in a moment.'):(ar?'مقدرتش أشغّل الخطوة دلوقتي. جرّب تاني.':'Could not run the step right now. Try again.'))}
SIM.busy=false;saveSIM();render()}
function simCheckWin(){if(SIMSTEPS.every((_,k)=>simDone(k))&&!ST.fsimXP){ST.fsimXP=1;addXP(20);saveST()}}

// ---------- 3. Agent hand-off chains ----------
const HCH=[
{k:'collect-cash-board',t:T('Collections → cash → board','التحصيل ← الكاش ← المجلس'),a:['collections-prioritiser','cash-forecaster','board-report-writer'],h:[[T('Prioritised collection list with the expected receipt week per customer','قائمة تحصيل بالأولوية مع أسبوع التحصيل المتوقع لكل عميل'),T('Expected dates are based on payment history, not hope','التواريخ المتوقعة مبنية على تاريخ السداد، مش على الأمل')],[T('13-week forecast with buffer breaches and actions','توقع 13 أسبوع بالأسابيع اللي تحت حد الأمان والإجراءات'),T('Closing balances roll correctly from week to week','الأرصدة الختامية بتترحّل صح من أسبوع للتاني')]]},
{k:'close-to-forecast',t:T('Close → accounts → variance → forecast','الإقفال ← الحسابات ← الفروق ← التوقع'),a:['bank-reconciler','management-accounts-preparer','variance-analyst','rolling-forecaster'],h:[[T('Reconciled cash balance and proposed adjusting entries','رصيد الكاش بعد التسوية وقيود التسوية المقترحة'),T('Every difference is classified and explained','كل فرق متصنّف ومشروح')],[T('Management accounts with budget comparison','حسابات الإدارة مع مقارنة الموازنة'),T('Totals tie to the trial balance','الإجماليات متطابقة مع ميزان المراجعة')],[T('Variance drivers and what is one-off vs recurring','محركات الفروق وإيه اللي مرة واحدة وإيه المتكرر'),T('Only recurring drivers change the forecast','المحركات المتكررة بس هي اللي تغيّر التوقع')]]},
{k:'procure-to-pay',t:T('Procure → match → pay → cash','الشراء ← المطابقة ← الدفع ← الكاش'),a:['three-way-match-checker','payment-run-planner','cash-forecaster'],h:[[T('Invoices cleared for payment and the exceptions on hold','الفواتير الجاهزة للدفع والاستثناءات المعلّقة'),T('No invoice passes without PO and goods receipt','مفيش فاتورة تعدّي من غير أمر شراء واستلام')],[T('Proposed payment run by week, for approval','دفعة السداد المقترحة بالأسبوع، للموافقة'),T('A person approves the run before any payment','إنسان بيوافق على الدفعة قبل أي سداد')]]},
{k:'pricing-decision',t:T('Discounts → price model → CFO memo','الخصومات ← نموذج السعر ← مذكرة المدير المالي'),a:['discount-leakage-analyst','price-change-modeller','cfo-strategy-memo-writer'],h:[[T('Where discounts leak margin, by segment and rep','الخصومات بتسرّب الهامش فين، حسب الشريحة والمندوب'),T('Leakage is measured against the discount policy','التسريب متقاس قصاد سياسة الخصومات')],[T('Price and volume scenarios with break-even volume','سيناريوهات السعر والكمية مع كمية التعادل'),T('Elasticity is a stated range, not one number','المرونة مدى مكتوب، مش رقم واحد')]]},
{k:'fundraising',t:T('Valuation → cap table → investor update','التقييم ← جدول الملكية ← تحديث المستثمرين'),a:['valuation-helper','cap-table-modeller','investor-update-writer'],h:[[T('Valuation range with key assumptions','مدى التقييم بالافتراضات الأساسية'),T('A range with sensitivities, never a single number','مدى مع حساسيات، عمره ما يبقى رقم واحد')],[T('Dilution scenarios per round size','سيناريوهات التخفيف حسب حجم الجولة'),T('Ownership adds up to 100% in every scenario','الملكية مجموعها 100% في كل سيناريو')]]},
{k:'tax-controls',t:T('E-invoice exceptions → VAT → controls','استثناءات الفاتورة الإلكترونية ← القيمة المضافة ← الرقابة'),a:['einvoice-exceptions-checker','vat-return-preparer','internal-controls-tester'],h:[[T('Exceptions list: rejected, missing or mismatched invoices','قائمة الاستثناءات: فواتير مرفوضة أو ناقصة أو مش متطابقة'),T('Each exception has an owner and a fix date','كل استثناء ليه مسؤول وميعاد تصليح')],[T('Draft VAT return with reconciling items','مسودة إقرار القيمة المضافة ببنود المطابقة'),T('The draft goes to the tax adviser before filing','المسودة بتروح للمستشار الضريبي قبل التقديم')]]},
{k:'people-cost',t:T('Headcount → labour variance → budget','العمالة ← فروق تكلفة العمالة ← الموازنة'),a:['headcount-payroll-planner','labour-cost-variance-analyst','budget-builder'],h:[[T('Headcount and payroll plan by department','خطة العمالة والمرتبات حسب الإدارة'),T('Personal data is anonymised before it moves on','البيانات الشخصية متشالة الأسماء قبل ما تتنقل')],[T('Labour cost variance by rate, hours and mix','فروق تكلفة العمالة حسب المعدل والساعات والمزيج'),T('Overtime causes are separated from pay-rate changes','أسباب الأوفرتايم منفصلة عن تغييرات الأجر')]]}];
let HC={k:'collect-cash-board',s:0};
function hcDiag(c){const n=c.a.length;const gap=22;const w=Math.floor((640-gap*(n+1))/n);const nodes=c.a.map((k,i)=>{const [f,a]=fdFind(k);const x0=gap+i*(w+gap);return [k,LANG==='ar'?640-x0-w:x0,110,w,70,T(f.icon+' '+a.n.en,f.icon+' '+a.n.ar)]});
const edges=c.a.slice(1).map((k,i)=>[c.a[i],k]);const steps=[];
c.a.forEach((k,i)=>{const [f,a]=fdFind(k);steps.push({on:[k],c:T(`${a.n.en}: ${a.job.en}`,`${a.n.ar}: ${a.job.ar}`)});if(i<c.h.length){const [pk,ck]=c.h[i];steps.push({on:[k,k+'>'+c.a[i+1],c.a[i+1]],c:T(`Hand-off → ${pk.en}. Check before passing: ${ck.en}.`,`التسليم ← ${pk.ar}. راجع قبل التسليم: ${ck.ar}.`)})}});
steps.push({on:c.a.concat(edges.map(e=>e[0]+'>'+e[1])),c:T('The chain runs end to end — with a person approving at each hand-off.','السلسلة بتشتغل من الأول للآخر — وإنسان بيوافق عند كل تسليم.')});
return {k:'hc-'+c.k,t:c.t,d:T('',''),nodes,edges,steps}}
function hcPrompt(c,lang){const en=lang==='en';let p=en?`You will run a chain of ${c.a.length} finance agents in order: ${c.a.map(k=>fdFind(k)[1].n.en).join(' → ')}.\nFor each step: act as that agent (role and job below), produce its outputs, run its checks, then pass ONLY the hand-off package to the next step. STOP after each step and wait for my approval before continuing. Never post entries, release payments or send messages.\nUse only the data I attach. Write [MISSING] for any gap and label every assumption.\n`:`هتشغّل سلسلة من ${c.a.length} وكلاء ماليين بالترتيب: ${c.a.map(k=>fdFind(k)[1].n.ar).join(' ← ')}.\nفي كل خطوة: اشتغل كأنك الوكيل ده (الدور والمهمة تحت)، طلّع مخرجاته، اعمل مراجعاته، وبعدين سلّم «حزمة التسليم» بس للخطوة اللي بعدها. اقف بعد كل خطوة واستنى موافقتي قبل ما تكمّل. ممنوع ترحيل قيود أو صرف فلوس أو إرسال رسايل.\nاستخدم البيانات اللي هرفقها بس. اكتب [MISSING] لأي نقص وعلّم كل افتراض.\n`;
c.a.forEach((k,i)=>{const [f,a]=fdFind(k);const sk=fdSkill(a.sk);p+=`\n## ${en?'Step':'الخطوة'} ${i+1} — ${a.n[lang]} (${f.t[lang]})\n${en?'Role':'الدور'}: ${a.role[lang]}\n${en?'Job':'المهمة'}: ${a.job[lang]}\n${en?'Outputs':'المخرجات'}: ${fdList(a.out[lang]).join('; ')}\n${sk?`${en?'Method':'الطريقة'}: ${fdList(sk.steps[lang]).join(' → ')}\n`:''}${i<c.h.length?`${en?'Hand-off package to the next step':'حزمة التسليم للخطوة اللي بعدها'}: ${c.h[i][0][lang]}\n${en?'Check before passing':'راجع قبل التسليم'}: ${c.h[i][1][lang]}\n`:''}`});
return p+(en?'\nStart with step 1. First list the inputs you need from me.':'\nابدأ بالخطوة 1. الأول اكتب المدخلات اللي محتاجها مني.')}
function vChains(){const ar=LANG==='ar';const c=HCH.find(x=>x.k===HC.k)||HCH[0];const D=hcDiag(c);const s=Math.min(HC.s,D.steps.length-1);const pi=PSTORE.push(hcPrompt(c,ar?'ar':'en'))-1;
return `<p class="lede">${ar?'الوكلاء بيشتغلوا أحسن كفريق: مخرج وكيل بيبقى مدخل اللي بعده. شوف إيه اللي بيتسلّم في كل خطوة، وإيه اللي لازم يتراجع قبل التسليم.':'Agents work best as a team: one agent’s output becomes the next one’s input. See what is handed over at each step and what must be checked first.'}</p>
<div class="chips">${HCH.map(x=>`<button class="chip ${x.k===c.k?'on':''}" data-hck="${x.k}">${L(x.t)}</button>`).join('')}</div>
<section class="dgbox card hcbox"><h2 style="margin-top:0">🔗 ${L(c.t)}</h2><div>${dgSVG(D,s)}</div><div class="dgcap"><b>${s+1}/${D.steps.length}</b> ${esc(L(D.steps[s].c))}</div>
<div class="row-btns"><button class="tbtn" data-hc="prev" ${s===0?'disabled':''}>${ar?'→ السابق':'← Previous'}</button><button class="tbtn" data-hc="next" ${s===D.steps.length-1?'disabled':''}>${ar?'التالي ←':'Next →'}</button></div></section>
<div class="tablewrap"><table><tr><th>#</th><th>${ar?'الوكيل':'Agent'}</th><th>${ar?'بيسلّم إيه':'Hands over'}</th><th>${ar?'راجع قبل التسليم':'Check before passing'}</th></tr>${c.a.map((k,i)=>{const [f,a]=fdFind(k);return `<tr><td>${i+1}</td><td>${f.icon} <a href="#findept/${f.k}">${esc(L(a.n))}</a></td><td>${i<c.h.length?esc(L(c.h[i][0])):'—'}</td><td>${i<c.h.length?esc(L(c.h[i][1])):(ar?'موافقة نهائية':'Final approval')}</td></tr>`}).join('')}</table></div>
<div class="row-btns"><button class="btn-gold copy" data-i="${pi}">${ar?'انسخ برومبت السلسلة (لـ Cowork أو Project)':'Copy the chain prompt (for Cowork or a Project)'}</button></div>
<details class="fdsp"><summary>🧠 ${ar?'شوف برومبت السلسلة':'View the chain prompt'}</summary><pre dir="auto">${esc(hcPrompt(c,ar?'ar':'en'))}</pre></details>`}

// ---------- 5. CFO capstone ----------
let CAP=Object.assign({co:'',ind:'',size:'',pain:'',ag:['','',''],why:['','',''],ho:['',''],appr:'',kpi:'',roll:'',res:null,busy:false},ST.fcap||{});
function saveCAP(){const {busy,...r}=CAP;ST.fcap=r;saveST()}
const CAPRUB=[['fit',T('Fit to the company’s real pain points','مناسبة لمشاكل الشركة الحقيقية')],['handoffs',T('Clear hand-offs between the agents','تسليمات واضحة بين الوكلاء')],['controls',T('Controls, approvals and data protection','الرقابة والموافقات وحماية البيانات')],['value',T('Measurable value (KPIs, time saved)','قيمة قابلة للقياس (مؤشرات، وقت متوفر)')],['rollout',T('Realistic 30-day rollout','خطة تطبيق واقعية في 30 يوم')]];
function capMD(lang){const en=lang==='en';const A=CAP.ag.map(k=>fdFind(k)).filter(x=>x[1]);
return `# ${en?'Mini finance department blueprint':'مخطط إدارة مالية مصغّرة'} — ${CAP.co||'[company]'}\n\n- ${en?'Industry':'المجال'}: ${CAP.ind}\n- ${en?'Size':'الحجم'}: ${CAP.size}\n- ${en?'Pain points':'المشاكل'}: ${CAP.pain}\n\n## ${en?'Agents':'الوكلاء'}\n${CAP.ag.map((k,i)=>{const x=fdFind(k);return x[1]?`${i+1}. **${x[1].n[lang]}** (${x[0].t[lang]}) — ${x[1].job[lang]}\n   - ${en?'Why':'ليه'}: ${CAP.why[i]}${i<2?`\n   - ${en?'Hands over':'بيسلّم'}: ${CAP.ho[i]}`:''}`:''}).filter(Boolean).join('\n')}\n\n## ${en?'Approvals & controls':'الموافقات والرقابة'}\n${CAP.appr}\n\n## ${en?'KPIs':'المؤشرات'}\n${CAP.kpi}\n\n## ${en?'30-day rollout':'خطة 30 يوم'}\n${CAP.roll}\n${CAP.res?`\n## ${en?'Claude’s grade':'تقييم Claude'}: ${CAP.res.total}/100\n${CAP.res.verdict}\n\n${en?'Strengths':'نقاط القوة'}:\n${CAP.res.strengths.map(s=>'- '+s).join('\n')}\n\n${en?'Improve':'للتحسين'}:\n${CAP.res.improve.map(s=>'- '+s).join('\n')}\n`:''}\n---\nClaude Mastery · CFO capstone\n${A.length?'':''}`}
function vCap(){const ar=LANG==='ar';const opt=v=>`<option value="">${ar?'— اختار وكيل —':'— choose an agent —'}</option>`+FD.map(f=>`<optgroup label="${esc(L(f.t))}">${f.agents.map(a=>`<option value="${a.k}" ${v===a.k?'selected':''}>${esc(L(a.n))}</option>`).join('')}</optgroup>`).join('');
const inp=(k,ph)=>`<input class="search" data-capf="${k}" value="${esc(CAP[k])}" placeholder="${esc(ph)}">`;const ta=(k,ph,r)=>`<textarea class="search" data-capf="${k}" rows="${r||3}" dir="auto" placeholder="${esc(ph)}">${esc(CAP[k])}</textarea>`;
const filled=CAP.co&&CAP.pain&&CAP.ag.every(Boolean)&&CAP.ho.every(x=>x.trim())&&CAP.appr&&CAP.kpi&&CAP.roll;
let h=`<p class="lede">${ar?'مشروع التخرج: صمّم إدارة مالية مصغّرة من 3 وكلاء لشركتك (أو شركة تعرفها). حدد التسليمات والموافقات والمؤشرات وخطة 30 يوم — وClaude يقيّمها بمعايير واضحة.':'Your capstone: design a 3-agent mini finance department for your company (or one you know). Define the hand-offs, approvals, KPIs and a 30-day rollout — then Claude grades it against a clear rubric.'}</p>
<div class="twocol"><div class="abpane"><h3>1 · ${ar?'الشركة':'The company'}</h3><label class="pbf"><b>${ar?'الاسم':'Name'}</b>${inp('co',ar?'اسم الشركة (ممكن افتراضي)':'Company name (can be fictional)')}</label><label class="pbf"><b>${ar?'المجال':'Industry'}</b>${inp('ind',ar?'مثلاً: توزيع أدوية':'e.g. pharma distribution')}</label><label class="pbf"><b>${ar?'الحجم':'Size'}</b>${inp('size',ar?'موظفين، إيراد سنوي، فريق المالية':'staff, annual revenue, finance team size')}</label><label class="pbf"><b>${ar?'أكبر 3 مشاكل في المالية':'Top 3 finance pain points'}</b>${ta('pain',ar?'مثلاً: الإقفال بياخد 12 يوم، التحصيل متأخر…':'e.g. close takes 12 days, collections are late…')}</label></div>
<div class="abpane"><h3>2 · ${ar?'الوكلاء الثلاثة بالترتيب':'Three agents, in order'}</h3>${[0,1,2].map(i=>`<label class="pbf"><b>${ar?'الوكيل':'Agent'} ${i+1}</b><select class="search" data-capa="${i}">${opt(CAP.ag[i])}</select></label><input class="search" data-capw="${i}" value="${esc(CAP.why[i])}" placeholder="${ar?'ليه الوكيل ده؟ أي مشكلة بيحلها؟':'Why this agent? Which pain does it solve?'}">${i<2?`<input class="search" data-caph="${i}" value="${esc(CAP.ho[i])}" placeholder="${ar?`بيسلّم إيه للوكيل ${i+2}؟`:`What does it hand to agent ${i+2}?`}" style="margin-top:6px">`:''}`).join('<hr style="border:0;border-top:1px dashed var(--line);margin:10px 0">')}</div></div>
<div class="twocol"><div class="abpane"><h3>3 · ${ar?'الموافقات والرقابة':'Approvals & controls'}</h3>${ta('appr',ar?'مين يوافق على إيه، البيانات اللي ممنوع تدخل، مكان حفظ المخرجات':'Who approves what, which data never goes in, where outputs are stored')}</div><div class="abpane"><h3>4 · ${ar?'المؤشرات':'KPIs'}</h3>${ta('kpi',ar?'مثلاً: أيام الإقفال من 12 لـ 7، DSO من 75 لـ 60، ساعات متوفرة':'e.g. close days 12 → 7, DSO 75 → 60, hours saved')}</div></div>
<div class="abpane"><h3>5 · ${ar?'خطة 30 يوم':'30-day rollout'}</h3>${ta('roll',ar?'الأسبوع 1… الأسبوع 2… الأسبوع 3… الأسبوع 4…':'Week 1… Week 2… Week 3… Week 4…',4)}</div>
<div class="row-btns" style="margin-top:12px"><button class="btn-gold" data-cap="grade" ${CAP.busy||!filled?'disabled':''}>${CAP.busy?(ar?'Claude بيقيّم…':'Claude is grading…'):'🎓 '+(ar?'قيّم مع Claude':'Grade with Claude')}</button><button class="tbtn" data-cap="dl">⬇ ${ar?'نزّل المخطط (MD)':'Download blueprint (MD)'}</button><button class="tbtn" data-cap="clear">${ar?'امسح':'Clear'}</button></div>${filled?'':`<p class="k" style="font-size:12.5px">${ar?'املا كل الخانات علشان تقدر تقيّم.':'Fill every section to unlock grading.'}</p>`}<p class="note" id="capnote"></p>`;
if(CAP.res){const r=CAP.res;h+=`<section class="card capres"><h2 style="margin-top:0">🎓 ${ar?'تقييم Claude':'Claude’s grade'} <span class="pkscore ${r.total>=80?'hi':r.total>=60?'mid':'lo'}">${r.total}/100</span></h2>${r.verdict?`<p dir="auto">${esc(r.verdict)}</p>`:''}<div class="bars" style="display:grid;grid-template-columns:1fr;gap:6px">${CAPRUB.map(c=>{const v=r.scores[c[0]]||0;return `<div class="bar2"><span>${L(c[1])}</span><i><em style="width:${v*5}%;background:${v>=15?'var(--green)':v>=10?'var(--gold)':'var(--red)'}"></em></i><b>${v}/20</b></div>`}).join('')}</div>
<div class="twocol"><div><h3>✓ ${ar?'نقاط القوة':'Strengths'}</h3><ul>${r.strengths.map(s=>`<li dir="auto">${esc(s)}</li>`).join('')}</ul></div><div><h3>↗ ${ar?'حسّن':'Improve'}</h3><ul>${r.improve.map(s=>`<li dir="auto">${esc(s)}</li>`).join('')}</ul></div></div>${r.total>=70?`<p class="simwin">🏆 ${ar?'مبروك — نجحت في مشروع المدير المالي!':'Congratulations — you passed the CFO capstone!'}</p>`:''}</section>`}
return h}
async function capGrade(){const ar=LANG==='ar';const n=t=>{const e=document.getElementById('capnote');if(e)e.textContent=t};const sample=await tutorSample();if(!sample){n(ar?'التقييم مع Claude بيشتغل لما المنصة تتفتح جوه Claude (claude.ai).':'Grading with Claude works when the platform is opened inside Claude (claude.ai).');return}
CAP.busy=true;render();const ask=`You are a demanding CFO coach grading a capstone: a 3-agent mini finance department designed for a company in Egypt or the Gulf. Grade each criterion from 0 to 20: fit (agents match the stated pain points), handoffs (clear packages passed between agents in a sensible order), controls (named approvals, no autonomous posting/paying/sending, data protection), value (specific measurable KPIs with baselines), rollout (realistic 30-day plan with owners). Be specific and quote the design. Write verdict, strengths and improve in ${ar?'Egyptian Arabic':'English'}.
Reply with JSON only: {"scores":{"fit":0,"handoffs":0,"controls":0,"value":0,"rollout":0},"verdict":"","strengths":["",""],"improve":["","",""]}

DESIGN:
${capMD('en').slice(0,7000)}`;
try{const j=await sample.json(ask,{modelTier:'default'});const sc={};CAPRUB.forEach(c=>sc[c[0]]=Math.max(0,Math.min(20,Math.round(+((j.scores||{})[c[0]])||0))));
CAP.res={scores:sc,total:Object.values(sc).reduce((a,b)=>a+b,0),verdict:String(j.verdict||''),strengths:(j.strengths||[]).slice(0,5).map(String),improve:(j.improve||[]).slice(0,5).map(String)};if(CAP.res.total>=70&&!ST.fcapXP){ST.fcapXP=1;addXP(15)}}
catch(e){n(e&&e.code==='rate_limited'?(ar?'طلبات كتير — جرّب بعد شوية.':'Too many requests — try again in a moment.'):(ar?'مقدرتش أقيّم دلوقتي. جرّب تاني.':'Could not grade right now. Try again.'))}
CAP.busy=false;saveCAP();render()}

// ---------- Finance department page tabs ----------
{const _fd=vFinDept;vFinDept=function(){const seg=location.hash.slice(1).split('/');if(['sim','chains','cap'].includes(seg[1]))FDTAB=seg[1];else if(seg[1])FDTAB='dept';
const ar=LANG==='ar';const tabs=`<div class="tabs fdtabs">${[['dept','🗂',UX17.dept],['sim','🗓',UX17.sim],['chains','🔗',UX17.chains],['cap','🎓',UX17.cap]].map(t=>`<button class="tab ${FDTAB===t[0]?'on':''}" data-fdtab="${t[0]}">${t[1]} ${L(t[2])}</button>`).join('')}</div>`;
if(FDTAB==='dept')return _fd().replace(/(<\/h1>)/,'$1'+tabs);
crumb(L(UX16.fd)+' › '+L(UX17[FDTAB]));const body=FDTAB==='sim'?vSim5():FDTAB==='chains'?vChains():vCap();return `<h1>💼 ${L(UX16.fd)}</h1>${tabs}${body}`}}

// ---------- 15. One-page cheat sheet per module ----------
function cheatBlocks(n){const d=DAYS.find(x=>x.n==n);const ar=LANG==='ar';const dir=ar?'rtl':'ltr';const q=(QUIZ[n]||[]).slice(0,4);
const tips=[];d.units.forEach(u=>(L(u.tips)||[]).slice(0,1).forEach(t=>tips.push(t)));
const mp=d.units.map(u=>(u.prompts||[])[0]).filter(Boolean)[0];const g=k=>mp?((L(mp.p).match(new RegExp(`<${k}>([\\s\\S]*?)</${k}>`))||[])[1]||'').trim().split('\n')[0]:'';
return [`<div class="exdoc mcheat" dir="${dir}"><div class="chhead"><div><div class="chbrand">Claude Mastery · ${ar?'د. سارة سالم':'Dr. Sara Salem'}</div><h1>📄 ${L(UI.day)} ${d.n} · ${esc(L(d.t))}</h1><p>${esc(L(d.sub))}</p></div><div class="qr" style="width:78px">${QR_PLATFORM}</div></div>
<div class="chgrid">${d.units.map(u=>`<div class="chu"><div class="chid">${u.id}</div><h3>${esc(L(u.t))}</h3>${CEO[u.id]?`<p class="chceo">${esc(L(CEO[u.id]))}</p>`:''}<ol>${(L(u.steps)||[]).slice(0,4).map(s=>`<li>${esc(strip(s))}</li>`).join('')}</ol></div>`).join('')}</div>
<div class="chgrid2">${mp?`<div class="chbox"><h3>🧱 ${ar?'نمط البرومبت':'Prompt pattern'}</h3><p><b>${ar?'الدور':'Role'}:</b> ${esc(g('role'))}</p><p><b>${ar?'المهمة':'Task'}:</b> ${esc(g('task'))}</p><p><b>${ar?'السياق':'Context'}:</b> ${ar?'حقايق، ملفات، فترة، عملة — «استخدم المرفق بس»':'facts, files, period, currency — “use only the attached”'}</p><p><b>${ar?'اقف لما':'Stop when'}:</b> ${ar?'حدود قابلة للمراجعة':'checkable limits'} · <b>${ar?'الشكل':'Format'}:</b> ${ar?'جدول/مذكرة + اللغة':'table/memo + language'}</p></div>`:''}
<div class="chbox"><h3>💡 ${ar?'افتكر':'Remember'}</h3><ul>${tips.slice(0,4).map(t=>`<li>${esc(strip(t))}</li>`).join('')}</ul></div>
${q.length?`<div class="chbox"><h3>🧠 ${ar?'أسئلة سريعة':'Quick check'}</h3><ul>${q.map(x=>`<li><b>${esc(L(x.q))}</b> → ${esc(L(x.o[x.a]))}</li>`).join('')}</ul></div>`:''}
<div class="chbox"><h3>🛡 ${ar?'دايمًا':'Always'}</h3><ul><li>${ar?'استخدم البيانات المرفقة بس — ومفيش أرقام متألفة':'Use only the attached data — no invented numbers'}</li><li>${ar?'علّم الافتراضات واطلب أسئلة توضيح':'Label assumptions; let Claude ask questions first'}</li><li>${ar?'إنسان بيراجع قبل أي قرار أو إرسال':'A person reviews before any decision or sending'}</li></ul></div></div>
<div class="chfoot">${ar?'كما في سبتمبر 2026':'As of Sept 2026'} · ${PLATFORM_URL}</div></div>`]}
async function cheatDownload(n,btn){const old=btn.textContent;btn.disabled=true;btn.textContent=LANG==='ar'?'جاري…':'Working…';try{await multiPagePDF(cheatBlocks(n),`Claude-Mastery-Cheat-Sheet-Module-${n}-${LANG.toUpperCase()}.pdf`);btn.textContent='✓'}catch(e){console.error(e);btn.textContent=LANG==='ar'?'حصلت مشكلة':'Failed'}btn.disabled=false;setTimeout(()=>btn.textContent=old,2500)}
{const _mb=modExportBar;modExportBar=function(n){return _mb(n).replace(/<\/div>$/,`<button class="tbtn" data-cheat="${n}">📄 ${L(UX17.cheat)}</button></div>`)}}

document.addEventListener('click',e=>{const g=s=>e.target.closest(s);let x;
if(x=g('[data-fdtab]')){FDTAB=x.dataset.fdtab;render();return}
if(x=g('[data-simi]')){SIM.i=+x.dataset.simi;simCheckWin();saveSIM();render();return}
if(x=g('[data-sim]')){const a=x.dataset.sim;if(a==='run'&&!SIM.busy)simRun();else if(a==='reset'){SIM={i:0,out:['','','','',''],chk:{},busy:false};saveSIM();render()}else if(a==='dl'){const ar=LANG==='ar';const md=`# ${L(SIMCO.name)} — ${ar?'ملف إقفال سبتمبر 2026':'September 2026 month-end pack'}\n\n${L(SIMCO.about)}\n\n`+SIMSTEPS.map((s,k)=>{const a=fdFind(s.a)[1];return `## ${k+1}. ${L(a.n)}\n\n${L(s.t)}\n\n${SIM.out[k].trim()||(ar?'_لسه_':'_not yet_')}\n`}).join('\n')+`\n---\nClaude Mastery · ${ar?'محاكاة نهاية الشهر':'Month-end simulation'}\n`;saveFile('Sahel-Trading-month-end-pack.md',md).then(ok=>{if(ok)x.textContent='✓'})}return}
if(x=g('[data-hck]')){HC={k:x.dataset.hck,s:0};render();return}
if(x=g('[data-hc]')){const c=HCH.find(y=>y.k===HC.k);const n=hcDiag(c).steps.length;if(x.dataset.hc==='prev')HC.s=Math.max(0,HC.s-1);else HC.s=Math.min(n-1,HC.s+1);if(HC.s===n-1){ST.hcDone=Object.assign({},ST.hcDone);if(!ST.hcDone[c.k]){ST.hcDone[c.k]=1;addXP(3);saveST()}}render();return}
if(x=g('[data-cap]')){const a=x.dataset.cap;if(a==='grade'&&!CAP.busy)capGrade();else if(a==='dl')saveFile(`CFO-capstone-${slug(CAP.co)||'blueprint'}.md`,capMD(LANG==='ar'?'ar':'en')).then(ok=>{if(ok)x.textContent='✓'});else if(a==='clear'){CAP={co:'',ind:'',size:'',pain:'',ag:['','',''],why:['','',''],ho:['',''],appr:'',kpi:'',roll:'',res:null,busy:false};saveCAP();render()}return}
if(x=g('[data-cheat]')){cheatDownload(+x.dataset.cheat,x);return}});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='simout'){SIM.out[SIM.i]=t.value;saveSIM();return}
if(t.dataset&&t.dataset.capf){CAP[t.dataset.capf]=t.value;saveCAP();capLive();return}if(t.dataset&&t.dataset.capw!==undefined){CAP.why[+t.dataset.capw]=t.value;saveCAP();capLive();return}if(t.dataset&&t.dataset.caph!==undefined){CAP.ho[+t.dataset.caph]=t.value;saveCAP();capLive();return}});
function capLive(){const b=document.querySelector('[data-cap=grade]');if(b&&!CAP.busy)b.disabled=!(CAP.co&&CAP.pain&&CAP.ag.every(Boolean)&&CAP.ho.every(x=>x.trim())&&CAP.appr&&CAP.kpi&&CAP.roll)}
document.addEventListener('change',e=>{const t=e.target;if(t.dataset&&t.dataset.simc){SIM.chk[t.dataset.simc]=t.checked;saveSIM();simCheckWin();render();return}if(t.dataset&&t.dataset.capa!==undefined){CAP.ag[+t.dataset.capa]=t.value;saveCAP();capLive();return}});
