// ---------- Round 16: MCP planner tabs (connector library, server spec builder), Simulators (visibility sim), Module 4 security game, integration patterns, plugin builder, Skill library tabs (field Skills, trigger tester, governance), field agents + connector cards, ROI business case, agents & automation career path ----------
const FDMAP={finance:'fpa',accounting:'close',fpa:'fpa',cfo:'board',treasury:'cash',compliance:'tax',procurement:'spend'};
UX12.sims=T('Simulators','المحاكيات');
const UX22={plan:T('Planner','المخطط'),lib:T('Connector use cases','حالات استخدام الـ Connectors'),spec:T('MCP server spec builder','باني مواصفات سيرفر MCP'),see:T('What can Claude see?','Claude شايف إيه؟'),sec:T('Connector security game','لعبة أمان الـ Connectors'),pat:T('ERP / CRM integration patterns','أنماط ربط الـ ERP / CRM'),plugin:T('Plugin builder','باني الـ Plugin'),fsk:T('Field Skills','Skills المجالات'),trig:T('Trigger tester','مختبر التفعيل'),gov:T('Skill governance','حوكمة الـ Skills'),fag:T('Agents for this field','وكلاء المجال ده'),fconn:T('Connector use cases for this field','حالات Connectors للمجال ده')};
const CONNT={email:T('Email','الإيميل'),calendar:T('Calendar','التقويم'),drive:T('Cloud drive','التخزين السحابي'),crm:'CRM',erp:'ERP',ticketing:T('Ticketing','التذاكر'),database:T('Database','قاعدة البيانات'),chat:T('Team chat','شات الفريق'),sheets:T('Spreadsheets','الشيتات'),esign:T('E-signature','التوقيع الإلكتروني'),hris:T('HR system','نظام الموارد البشرية'),accounting:T('Accounting system','نظام الحسابات')};
const ctl=k=>{const v=CONNT[k];return v?(typeof v==='string'?v:L(v)):k};

// field agents/skills are searchable by the finance-department helpers
{const _ff=fdFind;fdFind=function(k){const r=_ff(k);if(r&&r[1])return r;for(const [fk,F] of Object.entries(FAG)){const a=(F.agents||[]).find(x=>x.k===k);if(a)return [fagField(fk),a]}return []}}
{const _fs=fdSkill;fdSkill=function(k){const s=_fs(k);if(s)return s;for(const F of Object.values(FAG)){const x=(F.skills||[]).find(y=>y.k===k);if(x)return x}return null}}
function fagField(k){const f=fieldOf(k);return {k,icon:f.icon,t:f.t,d:T('','')}}
function fieldAgents(k){if(FAG[k]&&FAG[k].agents)return {f:fagField(k),agents:FAG[k].agents,skills:FAG[k].skills};const m=FDMAP[k]&&FD.find(f=>f.k===FDMAP[k]);if(m)return {f:m,agents:m.agents,skills:m.skills.slice(0,3)};return null}

// ===== MCP connector planner: tabs =====
let MCTAB='plan',CLC='all';
{const _m=vMCPP;vMCPP=function(){const tabs=`<div class="tabs big">${[['plan','🔌',UX22.plan],['lib','📚',UX22.lib],['spec','🧱',UX22.spec]].map(t=>`<button class="tab ${MCTAB===t[0]?'on':''}" data-mctab="${t[0]}">${t[1]} ${L(t[2])}</button>`).join('')}</div>`;
if(MCTAB==='plan')return _m().replace(/(<\/h1>)/,'$1'+tabs);crumb(L(UX6.mcpp)+' › '+L(UX22[MCTAB]));return `<h1>🔌 ${L(UX6.mcpp)}</h1>`+tabs+(MCTAB==='lib'?vConnLib():vSpec())}}
function vConnLib(){const ar=LANG==='ar';if(typeof CONNLIB==='undefined')return '';const types=['all',...new Set(CONNLIB.map(c=>c.conn))];const list=CONNLIB.filter(c=>CLC==='all'||c.conn===CLC);const badge=a=>`<span class="pkscore ${a==='read'?'hi':a==='draft'?'mid':'lo'}">${a==='read'?(ar?'قراءة بس':'read-only'):a==='draft'?(ar?'مسودات':'drafts'):(ar?'كتابة':'write')}</span>`;
return `<p class="lede">${ar?'30 حالة استخدام حقيقية للـ Connectors: Claude بيقرا إيه، يكتب إيه، فين الموافقة البشرية، وإيه الخطر — ومعاها البرومبت الماستر.':'30 real connector use cases: what Claude reads, what it may write, where the human approves, the main risk — plus the master prompt.'}</p><div class="chips">${types.map(t=>`<button class="chip ${CLC===t?'on':''}" data-clc="${t}">${t==='all'?(ar?'الكل':'All'):ctl(t)}</button>`).join('')}</div>
<div class="fdlist">${list.map(c=>`<details class="fdag"><summary class="fdhead"><span class="fdi">${c.icon}</span><span class="fdt"><b>${esc(L(c.t))}</b><span class="k">${ctl(c.conn)} · ${esc(L(c.field))}</span></span>${badge(c.access)}</summary><div class="fdbody"><div class="fdcols"><div><h4>👁 ${ar?'بيقرا':'Reads'}</h4><p>${esc(L(c.reads))}</p></div><div><h4>✍ ${ar?'بيكتب':'Writes'}</h4><p>${esc(L(c.writes))}</p></div><div><h4>✅ ${ar?'الموافقة':'Approval'}</h4><p>${esc(L(c.approval))}</p></div><div><h4>⚠ ${ar?'الخطر والضابط':'Risk & control'}</h4><p>${esc(L(c.risk))}</p></div></div>${promptBox(c.pr)}</div></details>`).join('')}</div>`}
let SP=Object.assign({sys:'',what:'',users:'',objs:'',acts:'',auth:'',cons:'',res:null,busy:false},ST.sp||{});SP.busy=false;
function saveSP(){const {busy,...r}=SP;ST.sp=r;saveST()}
const snake=s=>String(s||'').toLowerCase().replace(/[^a-z0-9؀-ۿ]+/g,'_').replace(/^_|_$/g,'').slice(0,40)||'tool';
function spTools(){if(SP.res&&SP.res.tools)return SP.res.tools;const t=[];String(SP.objs).split('\n').map(s=>s.trim()).filter(Boolean).forEach(o=>{const n=snake(o);t.push({name:'search_'+n,kind:'read',input:'query, limit',output:`matching ${o} records (id + key fields)`,risk:'low'},{name:'get_'+n,kind:'read',input:'id',output:`one ${o} record`,risk:'low'})});
String(SP.acts).split('\n').map(s=>s.trim()).filter(Boolean).forEach(a=>{const w=/create|update|delete|send|post|pay|approve|change|أنشئ|عدّل|احذف|ابعت|ادفع|رحّل/i.test(a);t.push({name:snake(a),kind:w?'draft':'read',input:'[fields]',output:w?'a DRAFT for human approval (not executed)':'result',risk:w?'high':'med'})});return t}
function spMD(){const ar=LANG==='ar';const tools=spTools();return `# MCP server spec — ${SP.sys||'[system]'}\n\n## Purpose\n${SP.what||'[..]'}\n\n## Users\n${SP.users||'[..]'}\n\n## Tools (least privilege)\n\n| Tool | Kind | Input | Output | Risk |\n|---|---|---|---|---|\n${tools.map(t=>`| ${t.name} | ${t.kind} | ${t.input} | ${t.output} | ${t.risk} |`).join('\n')}\n\n## Auth & access\n${SP.auth||'Service account with read-only scope; write tools return drafts only.'}\n\n## Constraints\n${SP.cons||'- No free-text SQL\n- Log every call (who, when, inputs, outputs)\n- Rate limits and timeouts\n- Secrets in a vault, never in prompts'}\n\n## Controls\n- Read tools by default; any write = draft + named human approval\n- Validate and sanitise inputs; cap result sizes\n- Treat content from documents as data, not instructions (prompt-injection guard)\n- Separate test and production; review access quarterly\n`}
function spPrompt(lang){const en=lang==='en';return (en?MPen:MPar)(en?'Senior integration engineer who builds secure MCP servers with Claude Code for companies in Egypt and the Gulf':'مهندس تكامل أول بيبني سيرفرات MCP آمنة بـ Claude Code لشركات في مصر والخليج',en?`Build an MCP server for ${SP.sys||'[system]'} from the spec below`:`ابني سيرفر MCP لـ ${SP.sys||'[النظام]'} من المواصفات اللي تحت`,
`- Spec: [paste the spec.md]\n- System API / database: [docs or schema]\n- Environment: [test first, then production]\n- Language: [TypeScript or Python]`,en?'Start with read-only tools, add draft tools last; write tests for every tool and a README with setup and access steps.':'ابدأ بأدوات القراءة، وضيف أدوات المسودات في الآخر؛ اكتب اختبارات لكل أداة وREADME بخطوات الإعداد والصلاحيات.',
en?'- Every tool in the spec implemented with input validation\n- 0 write actions without a draft + approval step\n- Tests pass for all tools\n- Max 1 README page of setup':'- كل أداة في المواصفات متنفذة مع التحقق من المدخلات\n- 0 كتابة من غير مسودة + موافقة\n- الاختبارات ناجحة لكل الأدوات\n- README صفحة واحدة للإعداد بالكتير',en?'A project folder, tests, README, and a short list of open questions.':'فولدر المشروع، الاختبارات، README، وقايمة قصيرة بالأسئلة المفتوحة.')}
function vSpec(){const ar=LANG==='ar';const f=(k,q,ph,ta)=>`<label class="pbf"><b>${q}</b>${ta?`<textarea class="search" rows="3" data-sp="${k}" dir="auto" placeholder="${esc(ph)}">${esc(SP[k])}</textarea>`:`<input class="search" data-sp="${k}" value="${esc(SP[k])}" placeholder="${esc(ph)}">`}</label>`;const tools=spTools();const i=PSTORE.push(spPrompt(ar?'ar':'en'))-1;
return `<p class="lede">${ar?'اوصف نظام داخلي عندك، وخد مواصفات سيرفر MCP: قايمة الأدوات (قراءة/مسودة)، المدخلات والمخرجات، المخاطر والضوابط — جاهزة لقسم الـ IT أو لـ Claude Code.':'Describe an in-house system and get an MCP server spec: the tool list (read / draft), inputs and outputs, risks and controls — ready for IT or Claude Code.'}</p>
<div class="twocol"><div class="abpane">${f('sys',ar?'اسم النظام':'System name',ar?'مثلاً: نظام المخازن الداخلي':'e.g. in-house inventory system')}${f('what',ar?'Claude هيعمل بيه إيه؟':'What should Claude do with it?',ar?'يجاوب على أسئلة المخزون ويجهّز طلبات شراء':'answer stock questions and prepare purchase requests')}${f('users',ar?'مين هيستخدمه؟':'Who uses it?',ar?'فريق المشتريات':'procurement team')}${f('objs',ar?'البيانات (سطر لكل نوع)':'Data objects (one per line)','item\nsupplier\npurchase order',1)}${f('acts',ar?'الإجراءات (سطر لكل إجراء)':'Actions (one per line)','create purchase request\nupdate reorder level',1)}${f('auth',ar?'الدخول والصلاحيات':'Auth & access',ar?'حساب خدمة قراءة بس':'read-only service account')}${f('cons',ar?'قيود':'Constraints','',1)}
<div class="row-btns"><button class="btn-gold" data-sp2="ai" ${SP.busy?'disabled':''}>${SP.busy?'…':'✨ '+(ar?'حسّن المواصفات مع Claude':'Refine the spec with Claude')}</button><button class="tbtn" data-sp2="md">⬇ spec.md</button><button class="tbtn" data-sp2="reset">${ar?'امسح':'Clear'}</button></div><p class="note" id="spnote"></p></div>
<div class="abpane"><h3>🧱 ${ar?'الأدوات':'Tools'} (${tools.length})</h3><div class="tablewrap"><table><tr><th>${ar?'الأداة':'Tool'}</th><th>${ar?'النوع':'Kind'}</th><th>${ar?'المدخل':'Input'}</th><th>${ar?'المخرج':'Output'}</th><th>${ar?'الخطر':'Risk'}</th></tr>${tools.map(t=>`<tr><td><code>${esc(t.name)}</code></td><td>${esc(t.kind)}</td><td>${esc(t.input)}</td><td>${esc(t.output)}</td><td>${esc(t.risk)}</td></tr>`).join('')}</table></div>${SP.res&&SP.res.notes?`<ul class="k">${SP.res.notes.map(n=>`<li dir="auto">${esc(n)}</li>`).join('')}</ul>`:''}
<h3>💻 ${ar?'برومبت Claude Code للبناء':'Claude Code build prompt'}</h3><div class="row-btns"><button class="btn-gold copy" data-i="${i}">${L(UI.copy)}</button></div><p class="note">${ar?'ابني الأول على بيئة اختبار، ومحدش يشغّل أدوات كتابة على الإنتاج من غير موافقة الـ IT والأمن.':'Build against a test environment first; no write tools in production without IT and security approval.'}</p></div></div>`}
async function spAI(){const ar=LANG==='ar';const sample=await tutorSample();if(!sample){ntf('spnote',ar?'بيشتغل جوه claude.ai.':'Works inside claude.ai.');return}SP.busy=true;render();
try{const j=await sample.json(`You are a security-minded integration architect. Turn this description into an MCP server tool list with least privilege: prefer read tools; any change must be a draft tool that returns a draft for human approval; no free-text SQL. Write notes in ${ar?'Egyptian Arabic':'English'}. JSON only: {"tools":[{"name":"snake_case","kind":"read|draft","input":"","output":"","risk":"low|med|high"}],"notes":["3-5 key risks/controls"]}\n\n${spMD().slice(0,4000)}`,{modelTier:'default'});if(!j||!Array.isArray(j.tools))throw 0;SP.res={tools:j.tools.slice(0,20).map(t=>({name:String(t.name||'tool'),kind:String(t.kind||'read'),input:String(t.input||''),output:String(t.output||''),risk:String(t.risk||'')})),notes:(j.notes||[]).slice(0,6).map(String)}}catch(e){ntf('spnote',ar?'مقدرتش دلوقتي.':'Could not do it now.')}SP.busy=false;saveSP();render()}

// ===== Simulators: "What can Claude see?" =====
let SEE=Object.assign({on:['email','drive'],req:'',step:-1},ST.see||{});
{const _vs=vSim;vSim=function(){const btn=`<button class="tab ${SIMTAB==='see'?'on':''}" data-simtab="see">👁 ${L(UX22.see)}</button>`;if(SIMTAB!=='see')return _vs().replace(/(<div class="tabs big">[\s\S]*?)(<\/div>)/,'$1'+btn+'$2');
const keep=SIMTAB;SIMTAB='agent';let head;try{head=_vs()}finally{SIMTAB=keep}const m=head.match(/^<h1>[\s\S]*?<\/h1><div class="tabs big">[\s\S]*?<\/div>/);const tabs=(m?m[0]:'').replace(/ on"/g,'"').replace(/(<div class="tabs big">[\s\S]*?)(<\/div>)$/,'$1'+btn+'$2');crumb(L(UX12.sims)+' › '+L(UX22.see));return tabs+vSee()}}
function vSee(){const ar=LANG==='ar';if(typeof SEESIM==='undefined')return '';const C=SEESIM.connectors,R=SEESIM.requests;const rq=R.find(r=>r.k===SEE.req)||R[0];const need=new Set(rq.uses);const on=new Set(SEE.on);const missing=[...need].filter(k=>!on.has(k));const extra=[...on].filter(k=>!need.has(k));const steps=fdList(L(rq.steps));const s=Math.min(SEE.step,steps.length-1);
return `<p class="lede">${ar?'اختار الـ Connectors اللي مفعّلة وطلب — وشوف خطوة بخطوة Claude هيقرا إيه، ناقصه إيه، وفين الصلاحيات الزيادة.':'Pick the connectors that are on and a request — then see step by step what Claude would read, what is missing, and where access is broader than needed.'}</p>
<div class="twocol"><div class="abpane"><h3>🔌 ${ar?'الـ Connectors المفعّلة':'Connectors switched on'}</h3>${C.map(c=>`<label class="afrow ${on.has(c.k)?'on':''}"><input type="checkbox" data-seec="${c.k}" ${on.has(c.k)?'checked':''}><span><b>${c.icon} ${esc(L(c.t))}</b><span class="k">${esc(L(c.data)).replace(/\|/g,' · ')}</span></span><span class="pkscore ${c.risk==='high'?'lo':c.risk==='med'?'mid':'hi'}">${c.risk}</span></label>`).join('')}
<h3 style="margin-top:12px">💬 ${ar?'الطلب':'The request'}</h3><div class="chips">${R.map(r=>`<button class="chip ${r.k===rq.k?'on':''}" data-seer="${r.k}">${esc(L(r.t))}</button>`).join('')}</div></div>
<div class="abpane"><h3>👁 ${esc(L(rq.t))}</h3><ol class="seesteps">${steps.map((t,i)=>`<li class="${i<=s?'on':''}">${esc(t)}</li>`).join('')}</ol><div class="row-btns"><button class="tbtn" data-sees="prev" ${s<0?'disabled':''}>${ar?'→ السابق':'← Previous'}</button><button class="btn-gold" data-sees="next" ${s>=steps.length-1?'disabled':''}>${ar?'الخطوة الجاية ←':'Next step →'}</button></div>
${missing.length?`<div class="seewarn no">⛔ ${ar?'Claude مش هيقدر يكمّل من غير':'Claude cannot finish without'}: <b>${missing.map(k=>esc(L(C.find(c=>c.k===k).t))).join(', ')}</b></div>`:`<div class="seewarn ok">✓ ${ar?'كل الـ Connectors المطلوبة مفعّلة.':'All needed connectors are on.'}</div>`}
${extra.length?`<div class="seewarn mid">⚠ ${ar?'صلاحيات زيادة عن اللازم للطلب ده':'More access than this request needs'}: <b>${extra.map(k=>esc(L(C.find(c=>c.k===k).t))).join(', ')}</b> — ${ar?'افصلها لو مش محتاجها.':'switch them off if you do not need them.'}</div>`:''}
<p><b>🔒 ${ar?'بيانات حساسة':'Sensitive data'}:</b> ${esc(L(rq.sensitive))}</p><p><b>✂ ${ar?'أقل صلاحية كفاية':'Minimum access that is enough'}:</b> ${esc(L(rq.minimum))}</p></div></div>`}

// ===== Module 4: connector security game =====
let SG=Object.assign({ans:{}},ST.sg||{});
function secSection(){const ar=LANG==='ar';if(typeof SECGAME==='undefined')return '';const n=Object.keys(SG.ans).length;const ok=SECGAME.filter(q=>{const a=SG.ans[q.k];return a!==undefined&&q.opts[a]&&q.opts[a][1]}).length;
return `<section class="mergedsec" id="secgame"><h2>🛡 ${L(UX22.sec)} <span class="pkscore ${ok>=8?'hi':ok>=5?'mid':'lo'}">${ok}/${SECGAME.length}</span></h2><p class="k">${ar?'10 إعدادات Connectors في شركات — اكتشف الحاجة الخطيرة واختار الحل الآمن.':'10 connector setups at companies — spot the risky part and pick the safe fix.'} ${n===SECGAME.length?(ar?'· خلّصت! تقدر تعيد.':'· Done! You can retry.'):''}</p>
${SECGAME.map((q,i)=>{const a=SG.ans[q.k];return `<div class="fcqq"><b>${i+1}. ${esc(L(q.t))}</b><p class="k">${esc(L(q.setup))}</p><div class="chips">${q.opts.map((o,j)=>`<button class="chip ${a!==undefined?(o[1]?'ok':j===a?'no':''):''}" data-sg="${q.k}|${j}" ${a!==undefined?'disabled':''}>${esc(L(o[0]))}</button>`).join('')}</div>${a!==undefined?`<p class="k">${q.opts[a][1]?'✓':'✗'} ${esc(L(q.why))}</p>`:''}</div>`}).join('')}<div class="row-btns"><button class="tbtn" data-sgr="1">↺ ${ar?'العب تاني':'Play again'}</button></div></section>`}

// ===== Integration patterns (deep dive "API integration, agents & mini-ERP build") + Module 7 card =====
let IPS={};
function patSection(){const ar=LANG==='ar';if(typeof INTPAT==='undefined')return '';return `<section id="patterns" class="mergedsec"><h2>🔗 ${L(UX22.pat)}</h2><p class="k">${ar?'6 أنماط لربط Claude بأنظمة الـ ERP والـ CRM — من الأأمن للأقوى. كل نمط: إمتى تستخدمه، الخطوات، الضوابط، والبرومبت.':'6 patterns for connecting Claude to ERP and CRM systems — from safest to most powerful. Each: when to use it, the flow, the controls and the prompt.'}</p>
${INTPAT.map(p=>{const n=p.flow.length;const gap=14;const w=Math.floor((640-gap*(n+1))/n);const D={nodes:p.flow.map((f,i)=>{const x0=gap+i*(w+gap);return ['p'+i,LANG==='ar'?640-x0-w:x0,110,w,70,f[0]]}),edges:p.flow.slice(1).map((f,i)=>['p'+i,'p'+(i+1)]),steps:p.flow.map((f,i)=>({on:['p'+i].concat(i?['p'+(i-1)+'>p'+i]:[]),c:f[1]}))};const s=Math.min(IPS[p.k]||0,n-1);
return `<details class="fdag" ${IPS[p.k]!==undefined?'open':''}><summary class="fdhead"><span class="fdi">${p.icon}</span><span class="fdt"><b>${esc(L(p.t))}</b><span class="k">${esc(L(p.when))}</span></span></summary><div class="fdbody"><div class="dgbox card">${dgSVG(D,s)}<div class="dgcap"><b>${s+1}/${n}</b> ${esc(L(p.flow[s][1]))}</div><div class="row-btns"><button class="tbtn" data-ips="${p.k}|-1" ${s===0?'disabled':''}>${ar?'→':'←'}</button><button class="tbtn" data-ips="${p.k}|1" ${s===n-1?'disabled':''}>${ar?'←':'→'}</button></div></div><p><b>🛠 ${ar?'الأدوات':'Tools'}:</b> ${esc(L(p.tools))}</p><p><b>🛡 ${ar?'الضوابط':'Controls'}:</b></p><ul>${fdList(L(p.controls)).map(c=>`<li>${esc(c)}</li>`).join('')}</ul>${promptBox(p.pr)}</div></details>`}).join('')}</section>`}
{const _vd=vDeep;vDeep=function(k){const h=_vd(k);if(k!=='integration')return h;return h.replace(/(<div class="pager">)/,patSection()+'$1')}}
{const _vd=vDay;vDay=function(n,id){const h=_vd(n,id);if(id)return h;const ar=LANG==='ar';if(String(n)==='4')return h+secSection();if(String(n)==='7')return h+`<button class="card fdbanner" data-go="deep/integration">🔗 <b>${L(UX22.pat)}</b><span class="k">${ar?'6 أنماط ربط آمنة بالـ ERP والـ CRM برسومات وبرومبتات — في درس «ربط الـ API والوكلاء والـ Mini-ERP».':'6 safe ERP / CRM integration patterns with diagrams and prompts — inside «API integration, agents & mini-ERP build».'}</span></button>`;return h}}

// ===== Skill builder: plugin builder tab =====
let SBTAB='skill';let PLB=Object.assign({name:'',role:'',desc:'',skills:[],cmds:[],conns:[]},ST.plb||{});
function savePLB(){ST.plb=PLB;saveST()}
function allSkillOpts(){const o=[];FD.forEach(f=>f.skills.forEach(s=>o.push([s.k,f.t,s.n])));Object.entries(FAG).forEach(([k,F])=>(F.skills||[]).forEach(s=>o.push([s.k,fieldOf(k).t,s.n])));return o}
{const _sb=vSkillBuilder;vSkillBuilder=function(){const tabs=`<div class="tabs big"><button class="tab ${SBTAB==='skill'?'on':''}" data-sbtab="skill">🧩 Skill</button><button class="tab ${SBTAB==='plugin'?'on':''}" data-sbtab="plugin">📦 ${L(UX22.plugin)}</button></div>`;if(SBTAB==='skill')return _sb().replace(/(<\/h1>)/,'$1'+tabs);crumb(L(UX2.skb)+' › '+L(UX22.plugin));return `<h1>🧩 ${L(UX2.skb)}</h1>`+tabs+vPlugin()}}
function vPlugin(){const ar=LANG==='ar';const opts=allSkillOpts();const groups={};opts.forEach(o=>{const g=L(o[1]);(groups[g]=groups[g]||[]).push(o)});
return `<p class="lede">${ar?'اجمع Skills ووامر (من برومبتاتك المحفوظة) وأنواع Connectors لوظيفة كاملة في Plugin واحد — وصدّره كفولدر جاهز بالهيكل.':'Bundle Skills, commands (from your saved prompts) and connector types for a whole role into one plugin — and export it as a ready folder.'}</p>
<div class="twocol"><div class="abpane"><label class="pbf"><b>${ar?'اسم الـ Plugin (kebab-case)':'Plugin name (kebab-case)'}</b><input class="search" data-plb="name" value="${esc(PLB.name)}" placeholder="finance-manager-toolkit"></label><label class="pbf"><b>${ar?'الوظيفة':'Role'}</b><input class="search" data-plb="role" value="${esc(PLB.role)}" placeholder="${ar?'مدير مالي':'Finance manager'}"></label><label class="pbf"><b>${ar?'الوصف':'Description'}</b><textarea class="search" rows="2" data-plb="desc" dir="auto">${esc(PLB.desc)}</textarea></label>
<h4>🔌 ${ar?'أنواع الـ Connectors':'Connector types'}</h4><div class="chips">${Object.keys(CONNT).map(k=>`<button class="chip ${PLB.conns.includes(k)?'on':''}" data-plc="${k}">${ctl(k)}</button>`).join('')}</div>
<h4>⌘ ${ar?'أوامر من برومبتاتي المحفوظة':'Commands from my saved prompts'}</h4>${ST.mine.length?ST.mine.slice(0,20).map((m,i)=>`<label class="afrow ${PLB.cmds.includes(i)?'on':''}"><input type="checkbox" data-plm="${i}" ${PLB.cmds.includes(i)?'checked':''}><span>${esc(m.t)}</span></label>`).join(''):`<p class="k">${ar?'لسه مفيش — احفظ برومبتات من الاستوديو أو المساعد.':'None yet — save prompts from the Studio or the assistant.'}</p>`}</div>
<div class="abpane aflist"><h4>🧩 Skills (${PLB.skills.length})</h4>${Object.entries(groups).map(([g,list])=>`<details ${list.some(o=>PLB.skills.includes(o[0]))?'open':''}><summary><b>${esc(g)}</b> <span class="k">(${list.length})</span></summary>${list.map(o=>`<label class="afrow ${PLB.skills.includes(o[0])?'on':''}"><input type="checkbox" data-pls="${o[0]}" ${PLB.skills.includes(o[0])?'checked':''}><span>${esc(L(o[2]))}<span class="k">${o[0]}</span></span></label>`).join('')}</details>`).join('')}</div></div>
<div class="row-btns"><button class="btn-gold" data-plx="zip" ${PLB.name&&PLB.skills.length?'':'disabled'}>⬇ ${ar?'نزّل فولدر الـ Plugin (ZIP)':'Download the plugin folder (ZIP)'}</button></div><p class="note">${ar?'الهيكل: .claude-plugin/plugin.json + skills/ + commands/ + .mcp.json (قالب). راجع آخر توثيق للـ Plugins قبل النشر — كما في سبتمبر 2026. الـ Connectors الفعلية بيضيفها الأدمن.':'Layout: .claude-plugin/plugin.json + skills/ + commands/ + .mcp.json (template). Check the current plugin docs before you publish — as of Sept 2026. Real connectors are added by your admin.'}</p>`}
async function plZip(btn){await ensureZip();const z=new JSZip();const id=slug(PLB.name)||'my-plugin';const r=z.folder(id);r.folder('.claude-plugin').file('plugin.json',JSON.stringify({name:id,description:PLB.desc||PLB.role,version:'0.1.0',author:{name:(ST.profile&&ST.profile.name)||''}},null,2));
PLB.skills.forEach(k=>{const s=fdSkill(k);if(s)r.folder('skills/'+s.k).file('SKILL.md',fdSkillMd(s,'en'))});PLB.cmds.forEach(i=>{const m=ST.mine[i];if(m)r.folder('commands').file(slug(m.t).slice(0,40)+'.md',`---\ndescription: ${JSON.stringify(m.t.slice(0,200))}\n---\n\n${m.p}\n`)});
r.file('.mcp.json',JSON.stringify({mcpServers:Object.fromEntries(PLB.conns.map(c=>[c,{_todo:`Add the approved ${c} connector / MCP server here (least privilege, read-only by default)`}]))},null,2));r.file('README.md',`# ${id}\n\n${PLB.desc||''}\n\nRole: ${PLB.role}\n\n- Skills: ${PLB.skills.join(', ')}\n- Commands: ${PLB.cmds.length}\n- Connector types: ${PLB.conns.join(', ')||'none'}\n\nReview every Skill and command before sharing with your team. Built with Claude Mastery.\n`);
const ok=await saveFile(id+'.zip',await z.generateAsync({type:'blob'}));if(ok){btn.textContent='✓';if(!ST.plXP){ST.plXP=1;addXP(10)}}}

// ===== Skill library tabs: field Skills, trigger tester, governance =====
let FSK='sales';let TT=Object.assign({desc:'',reqs:'',res:null,busy:false},ST.tt||{});TT.busy=false;let GOV=Object.assign({rows:[]},ST.gov||{});
{const _vs=vSkills;vSkills=function(){const extra=[['field','🗃',UX22.fsk],['test','🎯',UX22.trig],['gov','🏛',UX22.gov]];const btns=extra.map(t=>`<button class="tab ${SKVIEW===t[0]?'on':''}" data-skv="${t[0]}">${t[1]} ${L(t[2])}</button>`).join('');
if(!['field','test','gov'].includes(SKVIEW))return _vs().replace(/(<div class="tabs big">[\s\S]*?)(<\/div>)/,'$1'+btns+'$2');const keep=SKVIEW;SKVIEW='plugins';let head;try{head=_vs()}finally{SKVIEW=keep}const m=head.match(/<div class="tabs big">[\s\S]*?<\/div>/);const tabs=(m?m[0]:'').replace(/ on"/g,'"').replace(/(<div class="tabs big">[\s\S]*?)(<\/div>)$/,'$1'+btns+'$2');
crumb(L(UI.skills)+' › '+L(extra.find(x=>x[0]===SKVIEW)[2]));return `<h1>✦ ${L(UI.skills)}</h1>`+tabs+(SKVIEW==='field'?vFieldSkills():SKVIEW==='test'?vTrig():vGov())}}
function vFieldSkills(){const ar=LANG==='ar';const fa=fieldAgents(FSK);const sk=fa?fa.skills:[];
return `<p class="lede">${ar?'3 Skills جاهزة لكل مجال من الـ 30 — طريقة ثابتة Claude يكررها كل مرة. نزّل SKILL.md أو كل Skills المجال ZIP.':'3 ready Skills for each of the 30 fields — a repeatable method Claude follows every time. Download SKILL.md or all of a field’s Skills as ZIP.'}</p>
<select class="search" id="fsksel">${FIELDLIB.map(f=>`<option value="${f.k}" ${FSK===f.k?'selected':''}>${f.icon} ${esc(L(f.t))}</option>`).join('')}</select>
<div class="grid" style="margin-top:10px">${sk.map(s=>`<div class="card"><h3>🧩 ${esc(L(s.n))}</h3><p class="k" style="font-size:13px">${esc(L(s.when))}</p><ol class="fdsteps">${fdList(L(s.steps)).map(t=>`<li>${esc(t)}</li>`).join('')}</ol><div class="row-btns"><button class="tbtn" data-fdsk="${s.k}">⬇ SKILL.md</button><button class="tbtn" data-ttload="${s.k}">🎯 ${ar?'اختبر التفعيل':'Test trigger'}</button></div></div>`).join('')||`<p class="k">${ar?'قريبًا.':'Coming soon.'}</p>`}</div>${sk.length?`<div class="row-btns"><button class="btn-gold" data-fskz="${FSK}">⬇ ${ar?'كل Skills المجال (ZIP)':'All field Skills (ZIP)'}</button></div>`:''}`}
function ttLocal(){const d=TT.desc.trim();const dn=asNorm(d);const terms=new Set(dn.split(/[^\p{L}\p{N}]+/u).filter(w=>w.length>3&&!AS_STOP.has(w)).map(asStem));const reqs=TT.reqs.split('\n').map(s=>s.trim()).filter(Boolean).slice(0,8);
const tips=[];if(d.length<80)tips.push(T('Too short — say what it does AND when to use it.','قصير جدًا — قول بيعمل إيه وإمتى يتستخدم.'));if(d.length>1000)tips.push(T('Over 1,000 characters — tighten it.','أكتر من 1000 حرف — اختصره.'));if(!/use when|استخدم(ها)? لما|when the user|لما المستخدم/i.test(d))tips.push(T('Add «Use when …» with the words people actually type.','ضيف «استخدمها لما …» بالكلمات اللي الناس بتكتبها فعلًا.'));if(!/\b(create|build|draft|analy|review|prepare|reconcile|write|اعمل|جهّز|حلّل|راجع|اكتب|طابق)/i.test(d))tips.push(T('Start with action verbs (draft, reconcile, review…).','ابدأ بأفعال (جهّز، طابق، راجع…).'));
const rows=reqs.map(r=>{const rt=[...new Set(asNorm(r).split(/[^\p{L}\p{N}]+/u).filter(w=>w.length>3&&!AS_STOP.has(w)).map(asStem))];const hit=rt.filter(w=>[...terms].some(t=>t.includes(w)||w.includes(t))).length;const sc=rt.length?hit/rt.length:0;return {r,sc,v:sc>=0.4?'yes':sc>=0.2?'maybe':'no'}});return {rows,tips}}
function vTrig(){const ar=LANG==='ar';const R=ttLocal();const lab=v=>v==='yes'?(ar?'هتتفعّل غالبًا':'likely triggers'):v==='maybe'?(ar?'ممكن':'maybe'):(ar?'غالبًا لأ':'unlikely');
return `<p class="lede">${ar?'الـ Skill بتتفعّل من وصفها. الصق الوصف وطلبات حقيقية — وشوف هتتفعّل ولا لأ، ونصايح تصلّح الوصف المبهم.':'A Skill triggers from its description. Paste the description and real requests — see whether it would trigger, with tips to fix a vague description.'}</p>
<div class="twocol"><div class="abpane"><label class="pbf"><b>${ar?'وصف الـ Skill':'Skill description'}</b><textarea class="search" id="ttdesc" rows="5" dir="auto">${esc(TT.desc)}</textarea></label><label class="pbf"><b>${ar?'طلبات تجربة (سطر لكل طلب)':'Test requests (one per line)'}</b><textarea class="search" id="ttreqs" rows="5" dir="auto" placeholder="${ar?'اعملي توقع الكاش للـ 13 أسبوع الجايين\nلخّص الإيميل ده':'Build the 13-week cash forecast\nSummarise this email'}">${esc(TT.reqs)}</textarea></label><div class="row-btns"><button class="btn-gold" data-tt="ai" ${TT.busy?'disabled':''}>${TT.busy?'…':'✨ '+(ar?'اسأل Claude':'Ask Claude')}</button></div><p class="note" id="ttnote"></p></div>
<div class="abpane"><h3>🎯 ${ar?'فحص فوري':'Instant check'}</h3>${R.rows.length?`<ul class="ttl">${R.rows.map(x=>`<li class="${x.v}"><b>${lab(x.v)}</b> — <span dir="auto">${esc(x.r)}</span></li>`).join('')}</ul>`:`<p class="k">${ar?'اكتب طلبات تجربة.':'Add test requests.'}</p>`}${R.tips.length?`<h4>💡 ${ar?'حسّن الوصف':'Improve the description'}</h4><ul>${R.tips.map(t=>`<li>${L(t)}</li>`).join('')}</ul>`:''}
${TT.res?`<h3>✨ Claude</h3><ul class="ttl">${TT.res.verdicts.map(v=>`<li class="${v.trigger?'yes':'no'}"><b>${v.trigger?'✓':'✗'}</b> <span dir="auto">${esc(v.request)}</span><div class="k" dir="auto">${esc(v.why)}</div></li>`).join('')}</ul>${TT.res.better?`<h4>${ar?'وصف أحسن':'Better description'}</h4><pre dir="auto" class="repre">${esc(TT.res.better)}</pre><div class="row-btns"><button class="tbtn" data-tt="use">${ar?'استخدمه':'Use it'}</button></div>`:''}`:''}</div></div>`}
async function ttAI(){const ar=LANG==='ar';if(!TT.desc.trim()||!TT.reqs.trim()){ntf('ttnote',ar?'اكتب الوصف والطلبات.':'Write the description and requests.');return}const sample=await tutorSample();if(!sample){ntf('ttnote',ar?'بيشتغل جوه claude.ai.':'Works inside claude.ai.');return}TT.busy=true;render();
try{const j=await sample.json(`A Claude Skill is chosen only from its description. For each request, judge whether a model would choose this Skill. Then write a better description (what it does + "Use when …" with the words users type, max 600 chars). Write "why" in ${ar?'Egyptian Arabic':'English'}; keep the description in its original language. JSON only: {"verdicts":[{"request":"","trigger":true,"why":""}],"better":""}\n\nDESCRIPTION:\n${TT.desc.slice(0,1500)}\n\nREQUESTS:\n${TT.reqs.slice(0,1500)}`,{modelTier:'default'});TT.res={verdicts:(j.verdicts||[]).slice(0,8).map(v=>({request:String(v.request||''),trigger:!!v.trigger,why:String(v.why||'')})),better:String(j.better||'')}}catch(e){ntf('ttnote',ar?'مقدرتش دلوقتي.':'Could not do it now.')}TT.busy=false;ST.tt=Object.assign({},TT,{busy:false});saveST();render()}
const GOVST=[['draft',T('Draft','مسودة')],['review',T('In review','تحت المراجعة')],['approved',T('Approved','معتمدة')],['retired',T('Retired','متوقفة')]];
function vGov(){const ar=LANG==='ar';const today=nowISO();
return `<p class="lede">${ar?'سجل Skills الفريق: صاحب كل Skill، الإصدار، ميعاد المراجعة، الحالة، وآخر تغيير — علشان الـ Skills تفضل دقيقة ومحدّثة.':'Your team’s Skill register: owner, version, review date, status and last change for each Skill — so Skills stay accurate and current.'}</p>
<div class="tablewrap"><table class="amtable"><tr><th>Skill</th><th>${ar?'المسؤول':'Owner'}</th><th>${ar?'الإصدار':'Version'}</th><th>${ar?'ميعاد المراجعة':'Review by'}</th><th>${ar?'الحالة':'Status'}</th><th>${ar?'آخر تغيير':'Last change'}</th><th></th></tr>${GOV.rows.map((r,i)=>`<tr class="${r.rev&&r.rev<today&&r.st!=='retired'?'govdue':''}"><td><input class="search" data-gv="${i}|sk" value="${esc(r.sk)}"></td><td><input class="search" data-gv="${i}|ow" value="${esc(r.ow)}"></td><td><input class="search" data-gv="${i}|v" value="${esc(r.v)}" style="width:70px"></td><td><input class="search" type="date" data-gv="${i}|rev" value="${esc(r.rev)}"></td><td><select class="search" data-gv="${i}|st">${GOVST.map(s=>`<option value="${s[0]}" ${r.st===s[0]?'selected':''}>${L(s[1])}</option>`).join('')}</select></td><td><input class="search" data-gv="${i}|ch" value="${esc(r.ch)}"></td><td><button class="tbtn" data-gvd="${i}">✕</button></td></tr>`).join('')}</table></div>
<div class="row-btns"><button class="tbtn" data-gva="1">＋ ${ar?'ضيف Skill':'Add Skill'}</button><button class="tbtn" data-gvx="csv">⬇ CSV</button><button class="tbtn" data-gvx="log">⬇ ${ar?'قالب سجل التغييرات':'Change-log template'}</button></div>
<p class="note">${ar?'قواعد: كل Skill ليها صاحب واحد، مراجعة كل 3 شهور أو مع أي تغيير في Claude أو السياسات، ومفيش Skill «معتمدة» من غير اختبار على 3 طلبات حقيقية. الصفوف المتأخرة عن ميعاد المراجعة لونها مختلف.':'Rules: one owner per Skill, review every 3 months or when Claude or policies change, and no Skill is «approved» without testing on 3 real requests. Rows past their review date are highlighted.'}</p>`}

// ===== Field pages: agents + connector cards =====
{const _vf=vFields;vFields=function(){const h=_vf();if(typeof FTAB!=='undefined'&&FTAB!=='lib')return h;const k=FLK;const ar=LANG==='ar';const fa=fieldAgents(k);const cn=(FAG[k]&&FAG[k].conn)||[];let x='';
if(fa)x+=`<section class="mergedsec"><h2>🤖 ${L(UX22.fag)} (${fa.agents.length})</h2><p class="k">${ar?'كل وكيل ليه دور واحد، system prompt جاهز، مدخلات ومخرجات، ضوابط، ومهمة عملية.':'Each agent has one role, a ready system prompt, inputs and outputs, guardrails and a practical task.'}${FDMAP[k]?` <a href="#findept/${FDMAP[k]}">${ar?'من الإدارة المالية':'From the finance department'} →</a>`:''}</p><div class="fdlist">${fa.agents.map(a=>fdCard(fa.f,a)).join('')}</div></section>`;
if(cn.length)x+=`<section class="mergedsec"><h2>🔌 ${L(UX22.fconn)}</h2><div class="fdlist">${cn.map(c=>`<details class="fdag"><summary class="fdhead"><span class="fdi">🔌</span><span class="fdt"><b>${esc(L(c.t))}</b><span class="k">${ctl(c.conn)}</span></span></summary><div class="fdbody"><div class="fdcols"><div><h4>👁 ${ar?'بيقرا':'Reads'}</h4><p>${esc(L(c.reads))}</p></div><div><h4>✍ ${ar?'بيكتب':'Writes'}</h4><p>${esc(L(c.writes))}</p></div><div><h4>✅ ${ar?'الموافقة':'Approval'}</h4><p>${esc(L(c.approval))}</p></div></div>${promptBox(c.pr)}</div></details>`).join('')}</div></section>`;
return h+x}}
{const _bi=buildIdx;buildIdx=function(){_bi();Object.entries(FAG).forEach(([k,F])=>(F.agents||[]).forEach(a=>IDX.push({t:T(a.n.en+' · '+fieldOf(k).t.en,a.n.ar+' · '+fieldOf(k).t.ar),txt:(a.n.en+' '+a.n.ar+' '+a.job.en+' '+a.job.ar).toLowerCase(),r:'fields/'+k,k:T('Field agent','وكيل المجال'),snip:a.job.en})))}}

// ===== 19. ROI business case from the cost estimator =====
{const _vc=vCost;vCost=function(){const ar=LANG==='ar';return _vc()+`<div class="abpane" style="margin-top:12px"><h3>📄 ${ar?'دراسة جدوى في صفحة لمديرك':'One-page business case for your manager'}</h3><div class="pkgrid3"><label class="pbf"><b>${ar?'اسم الأتمتة / الوكيل':'Automation / agent name'}</b><input class="search" data-cen="name" value="${esc(CE.name||'')}"></label><label class="pbf"><b>${ar?'المسؤول':'Owner'}</b><input class="search" data-cen="owner" value="${esc(CE.owner||'')}"></label><label class="pbf"><b>${ar?'المخاطر والضوابط':'Risks & controls'}</b><input class="search" data-cen="risk" value="${esc(CE.risk||'')}" placeholder="${ar?'موافقة بشرية قبل الإرسال؛ قراءة بس':'human approval before sending; read-only'}"></label></div><div class="row-btns"><button class="btn-gold" data-ceb="pdf">⬇ PDF</button><button class="tbtn" data-ceb="ppt">⬇ PPT</button></div></div>`}}
function ceNums(){const m=CE.runs*(CE.manual-CE.review)/60;return {m,y:m*12,val:m*12*CE.rate,pay:m>0?CE.setup/m:Infinity,err:CE.runs*12*Math.max(0,CE.err0-CE.err1)/100}}
async function ceExport(fmt,btn){const ar=LANG==='ar';const n=ceNums();const name=CE.name||(ar?'الأتمتة المقترحة':'Proposed automation');const lines=[(ar?'المشكلة: ':'Problem: ')+`${CE.runs} ${ar?'مرة في الشهر ×':'runs a month ×'} ${CE.manual} ${ar?'دقيقة شغل يدوي':'manual minutes'}`,(ar?'الحل: وكيل Claude + مراجعة بشرية ':'Solution: a Claude agent + human review of ')+`${CE.review} ${ar?'دقيقة':'minutes'}`,(ar?'الوقت الموفّر: ':'Time saved: ')+`${n.m.toFixed(1)} ${ar?'ساعة/شهر':'h/month'} · ${n.y.toFixed(0)} ${ar?'ساعة/سنة':'h/year'}`,(ar?'قيمة الوقت: ':'Value of time: ')+`${Math.round(n.val).toLocaleString()} EGP / ${ar?'سنة':'year'}`,(ar?'استرداد الإعداد: ':'Setup payback: ')+(isFinite(n.pay)?n.pay.toFixed(1)+(ar?' شهر':' months'):'—'),(ar?'أخطاء أقل: ':'Fewer errors: ')+`${n.err.toFixed(0)} / ${ar?'سنة':'year'}`,(ar?'المخاطر والضوابط: ':'Risks & controls: ')+(CE.risk||(ar?'موافقة بشرية قبل أي إرسال':'human approval before anything is sent')),(ar?'المسؤول: ':'Owner: ')+(CE.owner||'—'),(ar?'المطلوب: موافقة على pilot لمدة 30 يوم بقياس قبل وبعد.':'The ask: approve a 30-day pilot with before/after measurement.')];
const old=btn.textContent;btn.disabled=true;try{if(fmt==='pdf')await multiPagePDF([`<div class="exdoc" dir="${ar?'rtl':'ltr'}"><div class="k">Claude Mastery · ${ar?'دراسة جدوى':'Business case'}</div><h1>${esc(name)}</h1><ul style="font-size:16px;line-height:1.9">${lines.map(l=>`<li>${esc(l)}</li>`).join('')}</ul><p class="k">${ar?'تقديرات بناءً على مدخلات المستخدم — تتقاس في الـ pilot.':'Estimates based on the user’s inputs — to be measured in the pilot.'}</p></div>`],`Business-case-${slug(name)||'automation'}.pdf`);else await pptDeck(name,ar?'دراسة جدوى في صفحة':'One-page business case',[{h:ar?'الخلاصة':'Summary',lines}],`Business-case-${slug(name)||'automation'}.pptx`);btn.textContent='✓'}catch(e){console.error(e);btn.textContent=ar?'تعذّر':'Failed'}btn.disabled=false;setTimeout(()=>{if(btn.isConnected)btn.textContent=old},2000)}

// ===== 20. Agents & automation career path =====
CAREERS.push({k:'agents',icon:'🤖',t:T('AI agents & automation lead','قائد الوكلاء والأتمتة'),d:T('Design, test and run safe agents and automations — from one prompt to a team of agents with approvals.','صمّم واختبر وشغّل وكلاء وأتمتة آمنة — من برومبت واحد لفريق وكلاء بموافقات.'),ls:['4.1','4.2','4.3','4.4','6.1','6.2','7.2','9.4'],fl:['operations','pm'],pj:6,ex:'auto'});
{const _cs=careerState;careerState=function(c){if(c.ex!=='auto')return _cs(c);const s=_cs(Object.assign({},c,{ex:null}));const done=Object.values(ST.ba||{}).some(a=>a.length>=5)&&!!ST.pgXP;s.ex={t:T('Finish a build-along project and run the agent playground','خلّص مشروع «ابني معانا» وشغّل ملعب الوكلاء'),ok:done,go:'day/6'};s.pct=Math.round((s.pct*3+(done?100:0))/4);return s}}

document.addEventListener('click',e=>{const g=s=>e.target.closest(s);let x;
if(x=g('[data-mctab]')){MCTAB=x.dataset.mctab;render();return}if(x=g('[data-clc]')){CLC=x.dataset.clc;render();return}
if(x=g('[data-sp2]')){const a=x.dataset.sp2;if(a==='ai'&&!SP.busy)spAI();else if(a==='md')saveFile('mcp-server-spec.md',spMD());else if(a==='reset'){SP={sys:'',what:'',users:'',objs:'',acts:'',auth:'',cons:'',res:null,busy:false};saveSP();render()}return}
if(x=g('[data-seer]')){SEE.req=x.dataset.seer;SEE.step=-1;ST.see=SEE;saveST();render();return}if(x=g('[data-sees]')){SEE.step=Math.max(-1,SEE.step+(x.dataset.sees==='next'?1:-1));render();return}
if(x=g('[data-sg]')){const [k,j]=x.dataset.sg.split('|');SG.ans=Object.assign({},SG.ans,{[k]:+j});ST.sg=SG;if(Object.keys(SG.ans).length===SECGAME.length&&!ST.sgXP){ST.sgXP=1;addXP(15)}saveST();render();return}if(x=g('[data-sgr]')){SG.ans={};ST.sg=SG;saveST();render();return}
if(x=g('[data-ips]')){const [k,d]=x.dataset.ips.split('|');const p=INTPAT.find(y=>y.k===k);IPS[k]=Math.max(0,Math.min(p.flow.length-1,(IPS[k]||0)+(+d)));render();return}
if(x=g('[data-sbtab]')){SBTAB=x.dataset.sbtab;render();return}if(x=g('[data-plc]')){const k=x.dataset.plc;PLB.conns=PLB.conns.includes(k)?PLB.conns.filter(y=>y!==k):PLB.conns.concat(k);savePLB();render();return}if(x=g('[data-plx]')){plZip(x);return}
if(x=g('[data-fskz]')){(async()=>{await ensureZip();const z=new JSZip();const fa=fieldAgents(x.dataset.fskz);fa.skills.forEach(s=>z.folder(s.k).file('SKILL.md',fdSkillMd(s,'en')).file('SKILL.ar.md',fdSkillMd(s,'ar').replace(/^---[\s\S]*?---\n\n/,'')));const ok=await saveFile(`skills-${x.dataset.fskz}.zip`,await z.generateAsync({type:'blob'}));if(ok)x.textContent='✓'})();return}
if(x=g('[data-ttload]')){const s=fdSkill(x.dataset.ttload);if(s){TT.desc=s.when.en;TT.reqs='';TT.res=null;SKVIEW='test';render()}return}
if(x=g('[data-tt]')){if(x.dataset.tt==='ai'&&!TT.busy)ttAI();else if(x.dataset.tt==='use'&&TT.res){TT.desc=TT.res.better;TT.res=null;ST.tt=TT;saveST();render()}return}
if(x=g('[data-gva]')){GOV.rows.push({sk:'',ow:'',v:'1.0',rev:'',st:'draft',ch:''});ST.gov=GOV;saveST();render();return}if(x=g('[data-gvd]')){GOV.rows.splice(+x.dataset.gvd,1);ST.gov=GOV;saveST();render();return}
if(x=g('[data-gvx]')){if(x.dataset.gvx==='csv')saveFile('skill-register.csv',BOM+['skill,owner,version,review_by,status,last_change'].concat(GOV.rows.map(r=>[r.sk,r.ow,r.v,r.rev,r.st,r.ch].map(csvq).join(','))).join('\n'));else saveFile('skill-change-log-template.md','# Skill change log — [skill-name]\n\n| Date | Version | Change | Why | Tested on (3 requests) | Approved by |\n|---|---|---|---|---|---|\n| YYYY-MM-DD | 1.0 | First release | | | |\n');return}
if(x=g('[data-ceb]')){ceExport(x.dataset.ceb,x);return}},true);
document.addEventListener('change',e=>{const t=e.target,d=t.dataset||{};
if(d.seec){SEE.on=t.checked?SEE.on.concat(d.seec):SEE.on.filter(k=>k!==d.seec);ST.see=SEE;saveST();render();return}
if(d.pls){PLB.skills=t.checked?PLB.skills.concat(d.pls):PLB.skills.filter(k=>k!==d.pls);savePLB();render();return}if(d.plm!==undefined){const i=+d.plm;PLB.cmds=t.checked?PLB.cmds.concat(i):PLB.cmds.filter(k=>k!==i);savePLB();render();return}
if(t.id==='fsksel'){FSK=t.value;render();return}
if(d.gv&&(t.tagName==='SELECT'||t.type==='date')){const [i,f]=d.gv.split('|');GOV.rows[+i][f]=t.value;ST.gov=GOV;saveST();render();return}});
document.addEventListener('input',e=>{const t=e.target,d=t.dataset||{};
if(d.sp){SP[d.sp]=t.value;SP.res=null;saveSP();return}if(d.plb){PLB[d.plb]=t.value;savePLB();return}
if(t.id==='ttdesc'){TT.desc=t.value;ST.tt=Object.assign({},TT,{busy:false});saveST();r14rerender('x');return}if(t.id==='ttreqs'){TT.reqs=t.value;ST.tt=Object.assign({},TT,{busy:false});saveST();r14rerender('x');return}
if(d.gv&&t.tagName!=='SELECT'&&t.type!=='date'){const [i,f]=d.gv.split('|');GOV.rows[+i][f]=t.value;ST.gov=GOV;saveST();return}
if(d.cen){CE[d.cen]=t.value;ST.ce=CE;saveST();return}});
