// ===== FEATURES 7: more industry editions, day in the life, skills radar, module workbooks, home "Today" panel, wider search, Claude news, My work link =====
const UX15={dil:T('A day in the life','يوم في حياة'),radar:T('Skills radar','رادار المهارات'),wbk:T('Module workbook PDF','كراسة الموديول PDF'),today:T('Today','النهارده'),news:T('Claude news & updates','أخبار وتحديثات Claude')};

// ---------- 9. more industry editions ----------
INDS.push(
['telecom',T('Telecom','الاتصالات'),'📡',T('a telecom operator','شركة اتصالات'),T('ARPU, churn rate, network availability, NPS, cost per subscriber','متوسط الإيراد لكل مشترك، نسبة الفقد، توفر الشبكة، NPS، التكلفة لكل مشترك'),T('subscriber base, usage and billing extracts, network KPIs','قاعدة المشتركين، استخراجات الاستخدام والفواتير، مؤشرات الشبكة'),T('telecom regulator licence conditions and consumer rules — paste the current text','شروط ترخيص جهاز تنظيم الاتصالات وقواعد حماية المستهلك — الصق النص الحالي')],
['education',T('Education','التعليم'),'🏫',T('a school group or university','مجموعة مدارس أو جامعة'),T('enrolment, retention, pass rates, fee collection, cost per student','القيد، الاستمرار، نسب النجاح، تحصيل المصروفات، التكلفة لكل طالب'),T('student information system, fee schedules, assessment results — anonymised','نظام بيانات الطلبة، جداول المصروفات، نتايج التقييم — من غير بيانات تعريفية'),T('ministry and accreditation rules — paste the current text; never include student identities','قواعد الوزارة والاعتماد — الصق النص الحالي؛ وعمرك ما تحط هوية طالب')],
['logistics',T('Logistics','اللوجستيات'),'🚚',T('a logistics or freight company','شركة لوجستيات أو شحن'),T('on-time delivery, truck fill rate, cost per shipment, warehouse utilisation, damage rate','التسليم في الميعاد، امتلاء العربيات، التكلفة لكل شحنة، استغلال المخازن، نسبة التلف'),T('shipment logs, fleet data, warehouse management extracts','سجلات الشحنات، بيانات الأسطول، استخراجات إدارة المخازن'),T('customs and transport regulations — paste the current text','قواعد الجمارك والنقل — الصق النص الحالي')],
['hospitality',T('Hospitality & tourism','الضيافة والسياحة'),'🏨',T('a hotel or tourism group','مجموعة فنادق أو سياحة'),T('occupancy, ADR, RevPAR, guest satisfaction, cost per occupied room','الإشغال، متوسط سعر الغرفة، الإيراد لكل غرفة متاحة، رضا النزلاء، التكلفة لكل غرفة مشغولة'),T('PMS bookings, channel reports, guest reviews','حجوزات نظام الإدارة، تقارير القنوات، تقييمات النزلاء'),T('tourism authority and guest-data rules — paste the current text','قواعد هيئة السياحة وبيانات النزلاء — الصق النص الحالي')],
['oilgas',T('Oil & gas / energy','البترول والطاقة'),'🛢',T('an oil, gas or energy company','شركة بترول أو غاز أو طاقة'),T('production volume, uptime, lifting cost, HSE incidents, capex execution','حجم الإنتاج، وقت التشغيل، تكلفة الاستخراج، حوادث السلامة، تنفيذ الاستثمارات'),T('production reports, maintenance logs, HSE records','تقارير الإنتاج، سجلات الصيانة، سجلات السلامة'),T('HSE and concession agreement terms — paste the current text','قواعد السلامة وشروط اتفاقية الامتياز — الصق النص الحالي')],
['ngo',T('NGOs & non-profits','الجمعيات والمنظمات غير الربحية'),'🤝',T('an NGO or foundation','جمعية أو مؤسسة غير ربحية'),T('beneficiaries reached, cost per beneficiary, grant utilisation, donor retention, outcome indicators','المستفيدين، التكلفة لكل مستفيد، استخدام المنح، استمرار المتبرعين، مؤشرات النتايج'),T('programme M&E data, grant budgets, donor database','بيانات المتابعة والتقييم، ميزانيات المنح، قاعدة المتبرعين'),T('donor agreement terms and NGO law — paste the current text','شروط اتفاقيات المانحين وقانون الجمعيات — الصق النص الحالي')]);

// ---------- 11. a day in the life (on #fields and #tracks) ----------
function dilSection(k){const d=DIL[k];if(!d)return '';const ar=LANG==='ar';const tot=d.reduce((a,r)=>a+r[6],0);const hm=tot>=60?(ar?`${Math.floor(tot/60)} ساعة و${tot%60} دقيقة`:`${Math.floor(tot/60)} h ${tot%60} min`):(ar?`${tot} دقيقة`:`${tot} min`);
return `<h2>🕘 ${L(UX15.dil)} — ${esc(L(fieldOf(k).t))}</h2><p class="note">${ar?`6 لحظات في يوم شغل، والأداة المناسبة، وبرومبت سريع. توفير تقديري حوالي ${hm} في اليوم.`:`Six moments of a working day, the right tool and a quick prompt. Estimated time saved: about ${hm} a day.`}</p><ol class="dil">${d.map(r=>{const i=PSTORE.push(ar?r[5]:r[4])-1;return `<li><div class="dilt">${r[0]}</div><div class="dilb"><div class="dilh"><b>${esc(ar?r[2]:r[1])}</b><span class="tag">${esc(r[3])}</span><span class="dils">−${r[6]} ${ar?'دقيقة':'min'}</span></div><div class="dilp" dir="auto">“${esc(ar?r[5]:r[4])}”</div><button class="copy" data-i="${i}">${L(UI.copy)}</button></div></li>`}).join('')}</ol><p class="note">${ar?'الوقت الموفّر تقدير توضيحي — قيسه في شغلك.':'Time saved is an illustrative estimate — measure it in your own work.'}</p>`}
{const _vf=vFields;vFields=function(){const seg=location.hash.slice(1).split('/');if(seg[0]==='fields'&&seg[1]&&FIELDLIB.find(f=>f.k===seg[1])){FLK=seg[1];history.replaceState(null,'','#fields')}let h=_vf();const k=fieldOf(FLK).k;const i=h.indexOf('<h2>🔗');return i>0?h.slice(0,i)+dilSection(k)+h.slice(i):h+dilSection(k)}}
{const _vt=vTracks;vTracks=function(){const seg=location.hash.slice(1).split('/');if(seg[0]==='tracks'&&seg[1]&&FIELDLIB.find(f=>f.k===seg[1])){FLK=seg[1];history.replaceState(null,'','#tracks')}const h=_vt();const i=h.indexOf('<h2>🎓');const s=dilSection(fieldOf(FLK).k);return i>0?h.slice(0,i)+s+h.slice(i):h+s}}
{const _ve=vE2E;vE2E=function(){const seg=location.hash.slice(1).split('/');if(seg[0]==='e2e'&&seg[1]&&E2E.find(c=>c.k===seg[1])){E2EK=seg[1];history.replaceState(null,'','#e2e')}return _ve()}}

// ---------- 14. skills radar ----------
const RADAR=[['prompt',T('Prompting','هندسة البرومبت'),['1.4','1.5','1.6','1.8','1.9'],[1]],['work',T('Workspace & context','مساحة العمل والسياق'),['2.1','2.2','2.3','2.4','2.5'],[2]],['tools',T('Deliverables & apps','المخرجات والتطبيقات'),['3.1','3.2','3.3','5.1','5.2','5.3','5.4'],[3,5]],['auto',T('Skills, agents & automation','Skills والوكلاء والأتمتة'),['4.1','4.2','4.3','4.4','6.1','6.2','7.1','7.2','7.3'],[4,6,7]],['gov',T('Governance & ethics','الحوكمة والأخلاقيات'),['9.1','9.2','9.3','9.4','9.5','9.6'],[9]],['apply',T('Applied field work','التطبيق في المجال'),[],[]]];
function radarScores(){return RADAR.map(([k,t,units,mods])=>{if(k==='apply'){const tasks=Object.values(ST.fl||{}).reduce((a,x)=>a+x.length,0);const proj=Object.values(ST.proj||{}).filter(p=>p.res&&p.res.total>=70).length;const cases=Object.keys(ST.remix||{}).length+Object.keys(ST.rx||{}).length;return {k,t,v:Math.min(100,Math.round(tasks*4+proj*10+cases*3))}}
const l=units.length?units.filter(u=>DONE.includes(u)).length/units.length:0;const q=mods.map(m=>ST.quiz[m]).filter(x=>x!=null);const qs=q.length?q.reduce((a,b)=>a+b,0)/q.length/100:0;const pj=mods.filter(m=>ST.proj&&ST.proj[m]&&ST.proj[m].res&&ST.proj[m].res.total>=70).length/Math.max(1,mods.length);
return {k,t,v:Math.round(100*(l*0.6+qs*0.25+pj*0.15))}})}
function radarSVG(sc){const N=sc.length,R=120,cx=170,cy=150;const pt=(i,r)=>{const a=-Math.PI/2+2*Math.PI*i/N;return [cx+r*Math.cos(a),cy+r*Math.sin(a)]};
const ring=f=>sc.map((_,i)=>pt(i,R*f).join(',')).join(' ');const poly=sc.map((s,i)=>pt(i,R*Math.max(.03,s.v/100)).join(',')).join(' ');
return `<svg viewBox="-80 0 500 300" class="radar" role="img" aria-label="${esc(L(UX15.radar))}">${[.25,.5,.75,1].map(f=>`<polygon points="${ring(f)}" fill="none" stroke="var(--line)" stroke-width="1"/>`).join('')}${sc.map((_,i)=>{const [x,y]=pt(i,R);return `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="var(--line)"/>`}).join('')}<polygon points="${poly}" fill="var(--gold)" fill-opacity=".28" stroke="var(--gold)" stroke-width="2"/>${sc.map((s,i)=>{const [x,y]=pt(i,R*Math.max(.03,s.v/100));return `<circle cx="${x}" cy="${y}" r="3.5" fill="var(--gold)"/>`}).join('')}${sc.map((s,i)=>{const [x,y]=pt(i,R+16);const anc=Math.abs(x-cx)<10?'middle':x>cx?'start':'end';return `<text x="${x}" y="${y}" text-anchor="${anc}" dominant-baseline="middle" font-size="10.5" fill="var(--ink2)">${esc(L(s.t))} ${s.v}</text>`}).join('')}</svg>`}
function radarSection(){const ar=LANG==='ar';const sc=radarScores();const low=sc.slice().sort((a,b)=>a.v-b.v)[0];const go={prompt:'day/1/1.4',work:'day/2/2.2',tools:'day/3/3.1',auto:'day/4/4.1',gov:'day/9/9.1',apply:'fields'}[low.k];
return `<h2>🕸 ${L(UX15.radar)}</h2><div class="radarwrap">${radarSVG(sc)}<div><p>${ar?'الرادار مبني على الدروس اللي خلصتها (60%)، والاختبارات (25%)، ومشروعات الموديولات (15%). محور التطبيق بيعد مهام المجالات والمشروعات والألعاب.':'Built from lessons completed (60%), quiz scores (25%) and module projects (15%). The applied axis counts field tasks, projects and practice games.'}</p><div class="tips2"><b>${ar?'ركّز بعد كده على':'Focus next on'}:</b> ${esc(L(low.t))} (${low.v}) <button class="tbtn" data-go="${go}">${ar?'ابدأ':'Start'} →</button></div></div></div>`}
{const _vh=vHub;vHub=function(){const h=_vh();if(PRTAB!=='prog')return h;const i=h.indexOf('<div class="tabs big">');const j=h.indexOf('</div>',i)+6;return h.slice(0,j)+radarSection()+h.slice(j)}}

// ---------- 24. module workbook PDF ----------
function workbookBlocks(n){const d=DAYS.find(x=>x.n==n);const ar=LANG==='ar';const dir=ar?'rtl':'ltr';const W=x=>`<div class="exdoc" dir="${dir}">${x}</div>`;const lines=k=>`<div class="wblines">${'<i></i>'.repeat(k)}</div>`;
const skel=ar?['الدور','المهمة','السياق (حقايق، ملفات، فترة، عملة)','المنطق (القرار اللي بيخدمه)','شروط التوقف','شكل المخرج']:['Role','Task','Context (facts, files, period, currency)','Reasoning (the decision it supports)','Stop conditions','Output format'];
const blocks=[W(`<div style="background:#13284B;color:#fff;border-radius:16px;padding:40px 36px;min-height:960px;display:flex;flex-direction:column;justify-content:space-between"><div><div style="color:#F1D27A;font-size:22px;font-weight:600">Claude Mastery · ${ar?'د. سارة سالم':'Dr. Sara Salem'}</div><h1 style="color:#fff;font-size:42px;margin:24px 0 8px">📓 ${ar?'كراسة':'Workbook'} · ${L(UI.day)} ${d.n}</h1><p style="color:#C7D1E2;font-size:22px">${esc(L(d.t))}</p><p style="color:#C7D1E2">${esc(L(d.sub))}</p></div><div style="display:flex;justify-content:space-between;align-items:flex-end"><div style="color:#C7D1E2">${ar?'الاسم':'Name'}: ______________________<br><br>${ar?'التاريخ':'Date'}: ______________</div><div class="qr" style="width:110px">${QR_PLATFORM}</div></div></div>`)];
d.units.forEach(u=>{const mp=(u.prompts||[]).slice(-1)[0];const st=(L(u.steps)||[]).slice(0,5);
blocks.push(W(`<div class="k">${u.id} · ${u.dur} ${L(UI.min)}</div><h1>${esc(L(u.t))}</h1>${CEO[u.id]?`<div class="ceobox">👔 ${esc(L(CEO[u.id]))}</div>`:''}<h3>✏️ ${ar?'تمرين: طبّقها على شغلك':'Exercise: apply it to your work'}</h3><div class="bkl">${st.map((s,i)=>`<div><b>${i+1}.</b> ${esc(strip(s))} <span class="wbbox"></span></div>`).join('')}</div>${mp?`<p><b>${ar?'البرومبت المقترح':'Suggested prompt'}:</b> ${esc(L(mp.t))}</p>`:''}<h3>${ar?'المهمة اللي هطبّق عليها':'The task I will apply it to'}</h3>${lines(2)}<table class="wbt"><tr><th>${ar?'قبل':'Before'}</th><th>${ar?'بعد':'After'}</th></tr><tr><td>${ar?'الوقت':'Time'}:</td><td>${ar?'الوقت':'Time'}:</td></tr><tr><td>${ar?'الجودة':'Quality'}:</td><td>${ar?'الجودة':'Quality'}:</td></tr></table><h3>🤔 ${ar?'أسئلة للتفكير':'Reflection'}</h3><p>1. ${ar?`إيه أهم حاجة اتعلمتها في «${esc(L(u.t))}»؟`:`What is the most useful idea in “${esc(L(u.t))}”?`}</p>${lines(2)}<p>2. ${ar?'إيه اللي هتغيره في شغلك الأسبوع ده؟':'What will you change in your work this week?'}</p>${lines(2)}<p>3. ${ar?'إيه المخاطرة أو الضابط اللي لازم تفتكره؟':'Which risk or control must you remember?'}</p>${lines(2)}`))});
blocks.push(W(`<h1>🧱 ${ar?'قالب البرومبت الماستر (فاضي)':'Blank master prompt template'}</h1>${skel.map(s=>`<h3>${s}</h3>${lines(3)}`).join('')}<h3>${ar?'الضوابط':'Controls'}</h3><p>☐ ${ar?'اسأل لحد 3 أسئلة الأول':'Ask up to 3 questions first'} &nbsp; ☐ ${ar?'راجع كل رقم':'Check every number'} &nbsp; ☐ ${ar?'علّم الافتراضات':'Label assumptions'} &nbsp; ☐ ${ar?'مراجعة بشرية':'Human review'}</p>`));
const p=projOf(n);if(p)blocks.push(W(`<h1>🛠 ${ar?'مشروع الموديول':'Module project'}</h1><h2>${esc(L(p.t))}</h2><p>${esc(L(p.brief))}</p><p><b>${ar?'المطلوب':'Deliverable'}:</b> ${esc(L(p.deliv))}</p><table class="wbt"><tr><th>${ar?'المعيار':'Criterion'}</th><th>/25</th></tr>${p.rub.map(c=>`<tr><td>${esc(L(c.t))}</td><td></td></tr>`).join('')}</table><h3>${ar?'ملاحظاتي':'My notes'}</h3>${lines(8)}`));
return blocks}
async function workbookDownload(n,btn){const old=btn.textContent;btn.disabled=true;try{await multiPagePDF(workbookBlocks(n),`Claude-Mastery-Workbook-Module-${n}-${LANG.toUpperCase()}.pdf`,(i,t)=>{btn.textContent=`${LANG==='ar'?'جاري':'Working'} ${i+1}/${t}…`});btn.textContent='✓'}catch(e){console.error(e);btn.textContent=LANG==='ar'?'حصلت مشكلة':'Failed'}btn.disabled=false;setTimeout(()=>btn.textContent=old,2500)}
{const _mb=modExportBar;modExportBar=function(n){return _mb(n).replace(/<\/div>$/,`<button class="tbtn" data-wbk="${n}">📓 ${L(UX15.wbk)}</button></div>`)}}

// ---------- news (static verified items + owner-added items in db `news`) ----------
const NEWS_CHECKED='2026-10-02';
const NEWS=[
['2026-10-01','product',T('Customize Claude Code with mods','تخصيص Claude Code بالـ mods'),T('Mods are small TypeScript functions that change how Claude Code works — rewrite prompts, block risky commands, add custom UI.','الـ mods دوال TypeScript صغيرة بتغيّر طريقة شغل Claude Code — تعيد كتابة البرومبتات، تمنع أوامر خطرة، أو تضيف واجهة.'),'https://claude.com/blog/claude-code-mods','day/7/7.1'],
['2026-10-01','customers',T('Barclays scales Claude across its operations','باركليز بتوسّع استخدام Claude في عملياتها'),T('Barclays is expanding its collaboration with Anthropic to integrate enterprise-grade AI across global operations.','باركليز بتوسّع شراكتها مع Anthropic علشان تدمج AI للمؤسسات في عملياتها حول العالم.'),'https://www.anthropic.com/news/barclays-scales-claude','day/9/9.4'],
['2026-09-30','product',T('Claude for Government is generally available','Claude للجهات الحكومية متاح للكل'),T('Claude for Government is now generally available, with Claude Code CLI and Claude for Microsoft 365 in early access.','Claude للجهات الحكومية بقى متاح للكل، و Claude Code CLI و Claude لـ Microsoft 365 في وصول مبكر.'),'https://claude.com/blog/claude-for-government-is-now-generally-available','day/9/9.1'],
['2026-09-25','product',T('Build plugins for Claude with the directory submission portal','ابني plugins لـ Claude من بوابة التقديم للدليل'),T('Package MCP connectors and Agent Skills as plugins, submit them to the Claude directory and track review and usage.','اجمع connectors الـ MCP والـ Skills في plugin، وقدّمه لدليل Claude وتابع المراجعة والاستخدام.'),'https://claude.com/blog/build-plugins-for-claude','day/4/4.2'],
['2026-09-23','product',T('Claude Marketplace','سوق Claude (Marketplace)'),T('One place to find plugins, connectors, agents and service partners for Claude — or list what you have built.','مكان واحد تلاقي فيه plugins و connectors ووكلاء وشركاء خدمات لـ Claude — أو تعرض اللي بنيته.'),'https://claude.com/blog/claude-marketplace','day/4/4.3'],
['2026-09-23','research',T('Claude agents discover a novel enzyme system','وكلاء Claude بيكتشفوا نظام إنزيمات جديد'),T('Early results from Anthropic’s life sciences lab: Claude agents found an enzyme system whose function is still unknown.','نتايج أولية من معمل علوم الحياة في Anthropic: وكلاء Claude لقوا نظام إنزيمات وظيفته لسه مش معروفة.'),'https://www.anthropic.com/news/claude-discovers-novel-enzyme-system',''],
['2026-09-17','product',T('Projects redesigned: from folder to conversation','الـ Projects بشكل جديد: من فولدر لمحادثة'),T('A new experience for Claude projects, available in beta in Claude Code.','تجربة جديدة لمشروعات Claude، متاحة كنسخة تجريبية في Claude Code.'),'https://claude.com/blog/projects-redesigned','day/2/2.2'],
['2026-09-17','company',T('Life Sciences Verification Program','برنامج التحقق لعلوم الحياة'),T('Anthropic introduced a verification program for life sciences work with Claude.','Anthropic أطلقت برنامج تحقق لشغل علوم الحياة مع Claude.'),'https://www.anthropic.com/news/life-sciences-verification-program',''],
['2026-09-16','product',T('Claude Cowork and chat are now one Claude','Claude Cowork والشات بقوا Claude واحد'),T('Cowork and chat are one Claude, rolling out on Pro and Max plans: hand over the task, Claude does the work, you keep the final say.','Cowork والشات بقوا Claude واحد، وبيتطلق على خطط Pro و Max: سلّم المهمة وClaude يعمل الشغل والقرار الأخير ليك.'),'https://claude.com/blog/cowork-is-now-claude','day/6/6.1'],
['2026-09-15','product',T('Claude for Small Business: new workflows, integrations and training','Claude للشركات الصغيرة: سير عمل وربط وتدريب جديد'),T('New Claude for Small Business workflows and integrations to help owners run and grow their business, plus the next leg of the SMB tour.','سير عمل وربط جديد في Claude للشركات الصغيرة يساعد أصحاب الشغل يديروا ويكبّروا شغلهم، ومرحلة جديدة من جولة الشركات الصغيرة.'),'https://claude.com/blog/claude-for-small-business-launches-new-workflows-integrations-and-training-programs','day/11/11.1'],
['2026-09-01','safety',T('Enterprise Frontier Safeguards','ضمانات الحدود للمؤسسات'),T('Anthropic is developing frontier safeguards together with enterprise customers.','Anthropic بتطوّر ضمانات أمان متقدمة بالتعاون مع عملائها من المؤسسات.'),'https://www.anthropic.com/news/enterprise-frontier-safeguards','day/9/9.2'],
['2026-08-26','product',T('Claude in Chrome is generally available','Claude في Chrome متاح للكل'),T('Available on every paid plan; it can work through browser tasks without approving each step, with a safety check on every action.','متاح على كل الخطط المدفوعة؛ ويقدر يخلّص مهام المتصفح من غير موافقة على كل خطوة، مع فحص أمان على كل إجراء.'),'https://claude.com/blog/claude-in-chrome-generally-available','day/5/5.3'],
['2026-08-26','product',T('Cowork gets a built-in browser','Cowork بقى فيه متصفح مدمج'),T('Claude has its own browser inside the Cowork desktop app — no extension, and your own tabs and logins stay out of it.','Claude بقى عنده متصفح جوه تطبيق Cowork على الكمبيوتر — من غير إضافة، وتابات وحساباتك بتفضل بعيد عنه.'),'https://claude.com/blog/cowork-built-in-browser','day/6/6.2'],
['2026-08-14','safety',T('How Claude’s text watermark works','إزاي العلامة المائية في نصوص Claude بتشتغل'),T('Future Claude models will add a text watermark to comply with the EU AI Act; Anthropic explains how it works.','موديلات Claude الجاية هتحط علامة مائية في النص للالتزام بقانون الـ AI الأوروبي؛ وAnthropic بتشرح إزاي.'),'https://www.anthropic.com/news/claude-text-watermark','day/9/9.2'],
['2026-06-18','product',T('Claude Code now supports artifacts','Claude Code بقى بيدعم الـ artifacts'),T('Preview in-progress work in Claude Code as a live, interactive artifact you can share with your team.','شوف الشغل اللي بتعمله في Claude Code كـ artifact تفاعلي حي وشاركه مع فريقك.'),'https://claude.com/blog/artifacts-in-claude-code','day/3/3.1'],
['2026-05-19','product',T('Managed Agents: self-hosted sandboxes and MCP tunnels','Managed Agents: بيئات مستضافة عندك وأنفاق MCP'),T('Claude Managed Agents can run in a sandbox you control and connect to your private MCP servers.','Claude Managed Agents يقدروا يشتغلوا في بيئة إنت متحكم فيها ويتصلوا بسيرفرات MCP الخاصة بيك.'),'https://claude.com/blog/claude-managed-agents-updates','day/7/7.2'],
['2026-04-23','product',T('Memory for Claude Managed Agents','الذاكرة لـ Claude Managed Agents'),T('A built-in memory layer lets agents learn across sessions and share what they learned.','طبقة ذاكرة مدمجة بتخلي الوكلاء يتعلموا عبر الجلسات ويشاركوا اللي اتعلموه.'),'https://claude.com/blog/claude-managed-agents-memory','day/7/7.2']];
const NEWSCAT={product:T('Product','المنتج'),company:T('Company','الشركة'),customers:T('Customers','العملاء'),research:T('Research','الأبحاث'),safety:T('Safety & policy','الأمان والسياسات')};
let NW={docs:[],state:'init',cat:'all',f:{date:new Date().toISOString().slice(0,10),cat:'product',ten:'',tar:'',sen:'',sar:'',url:'',paste:''},busy:false,msg:''};
async function newsInit(){if(NW.state!=='init')return;NW.state='loading';await wallInit().catch(()=>{});if(!WALL.db){NW.state='off';return}
try{WALL.db.collection('news').onSnapshot(s=>{NW.docs=s.docs.filter(d=>d.exists).map(d=>({id:d.id,...d.data()}));NW.state='ready';if(location.hash.startsWith('#news')||location.hash==='#home'||location.hash==='')render()},()=>{NW.state='off'})}catch(e){NW.state='off'}}
function allNews(){const dyn=NW.docs.filter(d=>d.title&&d.url&&/^https:\/\//.test(d.url)).map(d=>[String(d.date||'').slice(0,10),d.cat||'product',T(String(d.title.en||''),String(d.title.ar||d.title.en||'')),T(String(d.sum&&d.sum.en||''),String(d.sum&&d.sum.ar||d.sum&&d.sum.en||'')),d.url,'',d.id]);return dyn.concat(NEWS).sort((a,b)=>b[0].localeCompare(a[0]))}
function newsCard(n){const ar=LANG==='ar';let host='';try{host=new URL(n[4]).hostname.replace(/^www\./,'')}catch(e){}return `<article class="newsc"><div class="k">${fmtDate(n[0])} · ${esc(L(NEWSCAT[n[1]]||NEWSCAT.product))}${n[6]?` · <span class="tag">${ar?'جديد من المدرّبة':'Added by instructor'}</span>`:''}</div><h3 dir="auto">${esc(L(n[2]))}</h3><p dir="auto">${esc(L(n[3]))}</p><div class="row-btns"><a class="tbtn" href="${esc(n[4])}" target="_blank" rel="noopener">${ar?'المصدر':'Source'}: ${esc(host)} ↗</a>${n[5]?`<button class="tbtn" data-go="${n[5]}">📘 ${ar?'الدرس المرتبط':'Related lesson'}</button>`:''}${n[6]&&WALL.owner?`<button class="tbtn" data-nwdel="${esc(n[6])}">✕</button>`:''}</div></article>`}
function vNews(){crumb(L(UX15.news));const ar=LANG==='ar';newsInit();const list=allNews().filter(n=>NW.cat==='all'||n[1]===NW.cat);
let h=`<h1>📰 ${L(UX15.news)}</h1><p class="lede">${ar?'آخر إعلانات Anthropic و Claude من المصادر الرسمية، وكل خبر بلينك المصدر والدرس المرتبط بيه.':'The latest Anthropic and Claude announcements from official sources — every item links to its source and the related lesson.'}</p>`;
h+=`<div class="chips">${[['all',T('All','الكل')]].concat(Object.entries(NEWSCAT)).map(([k,t])=>`<button class="chip ${NW.cat===k?'on':''}" data-nwcat="${k}">${L(t)}</button>`).join('')}</div>`;
h+=`<div class="newsgrid">${list.map(newsCard).join('')}</div><p class="note">${ar?'الأخبار الثابتة متراجعة من anthropic.com/news و claude.com/blog يوم '+fmtDate(NEWS_CHECKED)+'. الأخبار الأحدث بتضيفها المدرّبة.':'Built-in items checked against anthropic.com/news and claude.com/blog on '+fmtDate(NEWS_CHECKED)+'. Newer items are added by the instructor.'}</p><div class="row-btns"><a class="tbtn" href="https://www.anthropic.com/news" target="_blank" rel="noopener">anthropic.com/news ↗</a><a class="tbtn" href="https://claude.com/blog" target="_blank" rel="noopener">claude.com/blog ↗</a><a class="tbtn" href="https://docs.claude.com/en/release-notes/overview" target="_blank" rel="noopener">${ar?'ملاحظات إصدار المطورين':'Developer release notes'} ↗</a><a class="tbtn" href="https://support.claude.com/en/articles/12138966-release-notes" target="_blank" rel="noopener">${ar?'ملاحظات إصدار التطبيقات':'App release notes'} ↗</a></div>`;
if(WALL.owner){const f=NW.f;h+=`<h2>✍ ${ar?'ضيف خبر (للمدرّبة)':'Add a news item (instructor)'}</h2><div class="abpane"><label class="pbf"><b>${ar?'الصق نص الإعلان (اختياري)':'Paste the announcement (optional)'}</b><textarea class="search" id="nwpaste" rows="4" dir="auto">${esc(f.paste)}</textarea></label><button class="tbtn" data-nw="draft" ${NW.busy?'disabled':''}>${NW.busy?(ar?'Claude بيكتب…':'Claude is drafting…'):'✨ '+(ar?'اكتب الكارت بالعربي والإنجليزي':'Draft the card in English and Arabic')}</button>
<div class="pkgrid3"><label class="pbf"><b>${ar?'التاريخ':'Date'}</b><input class="search" type="date" data-nwf="date" value="${esc(f.date)}"></label><label class="pbf"><b>${ar?'التصنيف':'Category'}</b><select data-nwf="cat">${Object.entries(NEWSCAT).map(([k,t])=>`<option value="${k}" ${f.cat===k?'selected':''}>${L(t)}</option>`).join('')}</select></label><label class="pbf"><b>${ar?'لينك المصدر (https)':'Source link (https)'}</b><input class="search" data-nwf="url" value="${esc(f.url)}" placeholder="https://www.anthropic.com/news/…"></label></div>
<label class="pbf"><b>Title (English)</b><input class="search" data-nwf="ten" value="${esc(f.ten)}"></label><label class="pbf"><b>العنوان (عربي)</b><input class="search" dir="rtl" data-nwf="tar" value="${esc(f.tar)}"></label><label class="pbf"><b>Summary (English)</b><textarea class="search" rows="2" data-nwf="sen">${esc(f.sen)}</textarea></label><label class="pbf"><b>الملخص (عربي)</b><textarea class="search" dir="rtl" rows="2" data-nwf="sar">${esc(f.sar)}</textarea></label>
<button class="btn-gold" data-nw="add">${ar?'انشر الخبر':'Publish the item'}</button><p class="note" id="nwnote">${esc(NW.msg)||(ar?'استخدم المصادر الرسمية بس، وراجع الملخص قبل النشر.':'Use official sources only, and check the summary before publishing.')}</p></div>`}
return h}
async function newsDraft(){const ar=LANG==='ar';const sample=await tutorSample();if(!sample){NW.msg=ar?'الكتابة مع Claude بتشتغل جوه claude.ai.':'Drafting with Claude works inside claude.ai.';render();return}if(!NW.f.paste.trim()){NW.msg=ar?'الصق نص الإعلان الأول.':'Paste the announcement first.';render();return}
NW.busy=true;render();try{const j=await sample.json(`Turn this official Anthropic/Claude announcement into a short news card for business learners in Egypt and the Gulf. Use only facts in the text. Reply with JSON only: {"title_en":"","title_ar":"(Egyptian Arabic)","summary_en":"under 35 words","summary_ar":"under 35 words, Egyptian Arabic","category":"product|company|customers|research|safety","date":"YYYY-MM-DD if stated, else empty"}\n\nTEXT:\n${NW.f.paste.slice(0,8000)}`,{modelTier:'quick'});Object.assign(NW.f,{ten:String(j.title_en||''),tar:String(j.title_ar||''),sen:String(j.summary_en||''),sar:String(j.summary_ar||''),cat:NEWSCAT[j.category]?j.category:NW.f.cat,date:/^\d{4}-\d{2}-\d{2}$/.test(j.date||'')?j.date:NW.f.date});NW.msg=ar?'راجع الكارت وضيف لينك المصدر.':'Check the card and add the source link.'}catch(e){NW.msg=ar?'مقدرتش أكتب الكارت.':'Could not draft the card.'}NW.busy=false;render()}
async function newsAdd(){const ar=LANG==='ar';const f=NW.f;if(!f.ten.trim()||!/^https:\/\//.test(f.url.trim())){NW.msg=ar?'العنوان الإنجليزي ولينك https مطلوبين.':'An English title and an https source link are required.';render();return}
try{await WALL.db.collection('news').add({date:f.date,cat:f.cat,title:{en:f.ten.trim().slice(0,200),ar:f.tar.trim().slice(0,200)},sum:{en:f.sen.trim().slice(0,400),ar:f.sar.trim().slice(0,400)},url:f.url.trim().slice(0,400),at:new Date().toISOString()});NW.f={date:new Date().toISOString().slice(0,10),cat:'product',ten:'',tar:'',sen:'',sar:'',url:'',paste:''};NW.msg=ar?'اتنشر.':'Published.'}catch(e){NW.msg=ar?'مقدرتش أنشر.':'Could not publish.'}render()}

// ---------- 27. home "Today" panel ----------
function todayPanel(){const ar=LANG==='ar';newsInit();
const next=(()=>{for(const d of DAYS)for(const u of d.units)if(!DONE.includes(u.id))return [d,u];return null})();
const m=next?next[0].n:1;const qs=QUIZ[m]||[];const dayN=Math.floor(Date.now()/864e5);const q=qs.length?qs[dayN%qs.length]:null;
const pj=PROJECTS.find(p=>!(ST.proj[p.n]&&ST.proj[p.n].res&&ST.proj[p.n].res.total>=70));const f=fieldOf(ST.flk||'finance');const task=f.tasks[dayN%4];const nw=allNews()[0];
return `<section class="today"><div class="tdh"><div><div class="sig">${L(UX15.today)} · ${fmtDate(new Date().toISOString().slice(0,10))}</div><h2>${ar?'يومك مع Claude':'Your day with Claude'}</h2></div><div class="tdk"><span>🔥 ${streak()}</span><span>${ST.xp} XP</span><span>${pct()}%</span></div></div>
<div class="tdg">${next?`<div class="tdc"><div class="k">📘 ${ar?'الدرس الجاي':'Next lesson'}</div><b>${next[1].id} · ${esc(L(next[1].t))}</b><div class="row-btns"><button class="btn-gold" data-go="day/${next[0].n}/${next[1].id}">${ar?'افتح':'Open'}</button><button class="tbtn" data-l60="${next[1].id}">⏱ 60s</button></div></div>`:''}
${q?`<div class="tdc"><div class="k">🧠 ${ar?'كارت مراجعة النهارده':'Today’s review card'}</div><b dir="auto">${esc(L(q.q))}</b><details><summary>${ar?'شوف الإجابة':'Show the answer'}</summary><p dir="auto">${esc(L(q.o[q.a]))} — ${esc(L(q.e))}</p></details></div>`:''}
${pj?`<div class="tdc"><div class="k">🛠 ${ar?'المشروع الجاي':'Next project'}</div><b>${esc(L(pj.t))}</b><div class="row-btns"><button class="tbtn" data-go="day/${pj.n}">${ar?'افتح الموديول':'Open the module'} ${pj.n}</button></div></div>`:''}
<div class="tdc"><div class="k">🗃 ${ar?'مهمة النهارده في مجالك':'Today’s task in your field'} · ${esc(L(f.t))}</div><b>${esc(L(task.t))}</b><div class="row-btns"><button class="tbtn" data-flgo="${f.k}">${ar?'افتح المهمة':'Open the task'}</button></div></div>
${nw?`<div class="tdc"><div class="k">📰 ${ar?'آخر خبر':'Latest news'} · ${fmtDate(nw[0])}</div><b dir="auto">${esc(L(nw[2]))}</b><div class="row-btns"><button class="tbtn" data-go="news">${ar?'كل الأخبار':'All news'}</button></div></div>`:''}</div></section>`}
{const _vho=vHome;vHome=function(){const h=_vho();const i=h.indexOf('</section>');return i>0?h.slice(0,i+10)+todayPanel()+h.slice(i+10):todayPanel()+h}}

// ---------- 30. wider search ----------
{const _bi=buildIdx;buildIdx=function(){_bi();const add=(t,txt,r,k)=>IDX.push({t,txt:(t.en+' '+t.ar+' '+txt).toLowerCase(),r,k,snip:txt});
FIELDLIB.forEach(f=>f.tasks.forEach(t=>add(T(f.t.en+' · '+t.t.en,f.t.ar+' · '+t.t.ar),strip(t.p.en+' '+t.p.ar),'fields/'+f.k,T('Field library','مكتبة المجالات'))));
Object.entries(CHAINS).forEach(([k,c])=>add(c.t,c.steps.map(s=>s.t.en+' '+s.t.ar+' '+s.p.en).join(' '),'fields/'+k,T('Prompt chain','سلسلة برومبتات')));
Object.entries(FGLOSS).forEach(([k,g])=>g.forEach(x=>add(T(x[0]+' — '+x[1],x[1]+' — '+x[0]),'','fields/'+k,T('Field glossary · '+fieldOf(k).t.en,'قاموس المجال · '+fieldOf(k).t.ar))));
E2E.forEach(c=>add(T(c.co.en,c.co.ar),strip(c.prob.en+' '+c.prob.ar+' '+c.phases.map(p=>p.t.en+' '+p.d.en).join(' ')),'e2e/'+c.k,T('Company case · '+c.f.en,'حالة شركة · '+c.f.ar)));
Object.entries(DIL).forEach(([k,d])=>d.forEach(r=>add(T(fieldOf(k).t.en+' · '+r[1],fieldOf(k).t.ar+' · '+r[2]),r[4]+' '+r[5],'fields/'+k,T('A day in the life','يوم في حياة'))));
allNews().forEach(n=>add(n[2],n[3].en+' '+n[3].ar,'news',T('News','أخبار')));
PROJECTS.forEach(p=>add(p.t,p.brief.en+' '+p.brief.ar,'day/'+p.n,T('Module project','مشروع موديول')));}}
let SKF='all';
{const _vs=vSearch;vSearch=function(q){IDX=null;let h=_vs(q);const ar=LANG==='ar';const kinds=[['all',T('All','الكل')],['Lesson',T('Lessons','الدروس')],['Field library',T('Field library','مكتبة المجالات')],['Prompt chain',T('Chains','السلاسل')],['Field glossary',T('Glossary','القاموس')],['Company case',T('Company cases','حالات الشركات')],['A day in the life',T('Day in the life','يوم في حياة')],['News',T('News','الأخبار')]];
const chips=`<div class="chips">${kinds.map(k=>`<button class="chip ${SKF===k[0]?'on':''}" data-skf="${k[0]}">${L(k[1])}</button>`).join('')}</div>`;h=h.replace(/(<p class="note">)/,chips+'$1');
if(SKF!=='all'){const want=SKF.toLowerCase();h=h.replace(/<a class="case srch"[\s\S]*?<\/a>/g,m=>{const meta=(m.match(/<div class="meta">([^<]*)</)||[])[1]||'';const en=IDX.find(x=>L(x.k)===meta);return en&&en.k.en.toLowerCase().startsWith(want)?m:''})}return h}}

// ---------- My work: platform link banner ----------
{const _vw=vWork;vWork=function(){const ar=LANG==='ar';const i=PSTORE.push(PLATFORM_URL)-1;const h=_vw();const banner=`<section class="commbanner"><div><b>🎓 ${ar?'منصة Claude Mastery':'Claude Mastery platform'}</b><span>${ar?`${DAYS.length} موديول، ${DAYS.reduce((a,d)=>a+d.units.length,0)} درس، ${FIELDLIB.length} مجال، ${E2E.length} حالة شركة، مكتبة برومبتات ماستر ومعمل واستوديو.`:`${DAYS.length} modules, ${DAYS.reduce((a,d)=>a+d.units.length,0)} lessons, ${FIELDLIB.length} fields, ${E2E.length} company cases, master prompt library, lab and studio.`}</span><span dir="ltr" style="display:block;margin-top:4px">${PLATFORM_URL}</span></div><div class="row-btns"><a class="btn-gold" href="${PLATFORM_URL}" target="_blank" rel="noopener">${ar?'افتح المنصة':'Open the platform'} ↗</a><button class="copy" data-i="${i}">${ar?'انسخ اللينك':'Copy link'}</button></div></section>`;const j=h.indexOf('</p>');return h.slice(0,j+4)+banner+h.slice(j+4)}}
WORKCATS.forEach(c=>c.items.forEach(w=>{if(w.u===PLATFORM_URL)w.d=T(`This bilingual course platform: ${'11'} modules, field library for 23 fields, company cases, lab, studio, packs, news and export center.`,'المنصة ثنائية اللغة دي: 11 موديول، مكتبة لـ 23 مجال، حالات شركات، معمل، استوديو، حزم، أخبار، ومركز تصدير.')}));

// ---------- events ----------
document.addEventListener('click',e=>{const g=s=>e.target.closest(s);let x;
if(x=g('[data-wbk]')){workbookDownload(+x.dataset.wbk,x);return}
if(x=g('[data-nwcat]')){NW.cat=x.dataset.nwcat;render();return}
if(x=g('[data-nw]')){if(x.dataset.nw==='draft'&&!NW.busy)newsDraft();if(x.dataset.nw==='add')newsAdd();return}
if(x=g('[data-nwdel]')){WALL.db.doc('news/'+x.dataset.nwdel).delete().catch(()=>{});return}
if(x=g('[data-skf]')){SKF=x.dataset.skf;render();return}});
document.addEventListener('input',e=>{const t=e.target;if(t.dataset&&t.dataset.nwf&&t.tagName!=='SELECT')NW.f[t.dataset.nwf]=t.value;if(t.id==='nwpaste')NW.f.paste=t.value});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset&&t.dataset.nwf&&t.tagName==='SELECT')NW.f[t.dataset.nwf]=t.value});
