let ST={xp:0,days:[],quiz:{},built:0,sims:0,name:'',mine:[]};try{Object.assign(ST,JSON.parse(localStorage.getItem('cm_state')||'{}'))}catch(e){}
const saveST=()=>{try{localStorage.setItem('cm_state',JSON.stringify(ST))}catch(e){}};
(function(){const d=new Date().toISOString().slice(0,10);if(!ST.days.includes(d)){ST.days.push(d);saveST()}})();
function streak(){const s=new Set(ST.days);let n=0;let d=new Date();for(;;){const k=d.toISOString().slice(0,10);if(s.has(k)){n++;d.setDate(d.getDate()-1)}else break}return n}
function addXP(n){ST.xp+=n;saveST();const t=document.getElementById('xpToast');if(t){t.textContent='+'+n+' XP';t.classList.add('on');setTimeout(()=>t.classList.remove('on'),1200)}}
function quizAvg(){const v=Object.values(ST.quiz);return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0}
function stats(){const mods=DAYS.filter(d=>d.units.every(u=>DONE.includes(u.id))).map(d=>d.n);return {xp:ST.xp,streak:streak(),pct:pct(),quizAvg:quizAvg(),built:ST.built,sims:ST.sims,lessons:DONE.length,mods}}
const UX={quiz:T("Quiz & flashcards","الاختبارات والكروت"),tutor:T("AI tutor","المدرّس الذكي"),sim:T("Agent-loop simulator","محاكي حلقة الوكيل"),builder:T("Prompt builder","باني البرومبت"),prog:T("My progress & badges","تقدّمي وشاراتي"),cert:T("Certificate","الشهادة"),learn:T("Learn & practice","اتعلم واتمرن"),ceo:T("Explain like I'm a CEO","اشرحلي كأني CEO"),present:T("Present","اعرض"),search:T("Search everything…","ابحث في كل حاجة…")};
// QUIZ
let qMode='quiz',qAns={},qDone=false,fcI=0,fcFlip=false,fcDeck='mod';
function vQuiz(m){m=+m||1;crumb(L(UX.quiz));const qs=QUIZ[m];const ar=LANG==='ar';
let h=`<h1>🧠 ${L(UX.quiz)}</h1><div class="chips">${DAYS.map(d=>`<button class="chip ${d.n===m?'on':''}" data-go="quiz/${d.n}">${L(UI.day)} ${d.n}${ST.quiz[d.n]!=null?` · ${ST.quiz[d.n]}%`:''}</button>`).join('')}</div><h2>${L(UI.day)} ${m} · ${L(DAYS[m-1].t)}</h2><div class="tabs"><button class="tab ${qMode==='quiz'?'on':''}" data-qmode="quiz">${ar?'اختبار':'Quiz'}</button><button class="tab ${qMode==='fc'?'on':''}" data-qmode="fc">${ar?'كروت مراجعة':'Flashcards'}</button></div>`;
if(qMode==='quiz'){h+=qs.map((q,i)=>`<div class="case"><h3>${i+1}. ${L(q.q)}</h3>${q.o.map((o,j)=>{let cls='';if(qDone){if(j===q.a)cls='right';else if(qAns[i]===j)cls='wrong'}return `<label class="opt ${cls}"><input type="radio" name="q${i}" data-qa="${i}:${j}" ${qAns[i]===j?'checked':''} ${qDone?'disabled':''}> ${L(o)}</label>`}).join('')}${qDone?`<div class="note" style="margin-top:6px">${L(q.e)}</div>`:''}</div>`).join('');
const sc=qs.filter((q,i)=>qAns[i]===q.a).length;
h+=qDone?`<div class="case"><b>${ar?'النتيجة':'Score'}: ${sc}/${qs.length} (${Math.round(sc*100/qs.length)}%)</b> <button class="dlbtn" data-qreset="1">${ar?'اعد الاختبار':'Retake'}</button> ${m<DAYS.length?`<button class="tbtn" data-go="quiz/${m+1}">${L(UI.next)}</button>`:''}</div>`:`<button class="dlbtn" data-qsubmit="${m}">${ar?'سلّم الإجابات':'Submit answers'}</button>`}
else{const deck=fcDeck==='gloss'?GLOSS.map(g=>({f:LANG==='ar'?g[1]:g[0],b:LANG==='ar'?g[3]:g[2]})):qs.map(q=>({f:L(q.q),b:L(q.o[q.a])+' — '+L(q.e)}));fcI=Math.min(fcI,deck.length-1);const c=deck[fcI];
h+=`<div class="chips"><button class="chip ${fcDeck==='mod'?'on':''}" data-fcdeck="mod">${ar?'كروت الموديول':'Module cards'}</button><button class="chip ${fcDeck==='gloss'?'on':''}" data-fcdeck="gloss">${ar?'كروت القاموس':'Glossary cards'} (${GLOSS.length})</button></div><div class="fc ${fcFlip?'flip':''}" data-fcflip="1"><div class="fin"><div class="ff">${esc(c.f)}</div><div class="fb">${esc(c.b)}</div></div></div><div class="pager"><button class="tbtn" data-fcnav="-1">${L(UI.prev)}</button><span>${fcI+1}/${deck.length} · ${ar?'اضغط الكارت للقلب':'tap card to flip'}</span><button class="tbtn" data-fcnav="1">${L(UI.next)}</button></div>`}
return h}
// TUTOR
let TUT=[],tutBusy=false,tutCtl=null,TUTSAMPLE;
async function tutorSample(){if(TUTSAMPLE!==undefined)return TUTSAMPLE;try{TUTSAMPLE=window.claude&&window.claude.use?await window.claude.use('sample'):null}catch(e){TUTSAMPLE=null}return TUTSAMPLE}
function vTutor(){crumb(L(UX.tutor));const ar=LANG==='ar';const chips=ar?['اشرحلي الفرق بين Skill و Project و Plugin','إزاي أكتب برومبت ماستر لتوقع المبيعات؟','امتى أستخدم Cowork وامتى Claude Code؟','اختبرني في هندسة البرومبت','اشرحلي MCP كأني CEO']:['Explain Skill vs Project vs Plugin','How do I write a master prompt for a sales forecast?','When should I use Cowork vs Claude Code?','Quiz me on prompt engineering','Explain MCP like I\'m a CEO'];
let h=`<h1>💬 ${L(UX.tutor)}</h1><p class="lede">${ar?'مدرّس بيعتمد على محتوى المنصة. بيسألك سؤال يحدد مستواك، ويشرح خطوة خطوة. كل سؤال بيستخدم من رصيد Claude بتاعك وهيطلب موافقتك أول مرة.':'A tutor grounded in this platform. It checks your level, then teaches step by step. Each question uses your own Claude usage and asks your permission the first time.'}</p><div class="chips">${chips.map((c,i)=>`<button class="chip" data-tchip="${i}">${esc(c)}</button>`).join('')}</div><div class="chat" id="chat">${TUT.map(m=>`<div class="msg ${m.role}">${m.role==='assistant'?fmtMD(m.content):esc(m.content)}</div>`).join('')}${tutBusy?'<div class="msg assistant" id="tlive">…</div>':''}</div><div class="ask"><textarea id="tq" rows="2" placeholder="${ar?'اكتب سؤالك…':'Ask a question…'}"></textarea><button class="dlbtn" id="tsend" ${tutBusy?'disabled':''}>${ar?'اسأل':'Ask'}</button>${tutBusy?`<button class="tbtn" id="tstop">${ar?'وقّف':'Stop'}</button>`:''}</div><p class="note" id="tnote"></p>`;
window._tchips=chips;return h}
function fmtMD(s){return esc(s).replace(/\*\*(.+?)\*\*/g,'<b>$1</b>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n/g,'<br>')}
async function tutorAsk(text){if(!text.trim()||tutBusy)return;const sample=await tutorSample();const note=()=>document.getElementById('tnote');
if(!sample){TUT.push({role:'user',content:text},{role:'assistant',content:LANG==='ar'?'المدرّس الذكي بيشتغل لما المنصة تتفتح جوه Claude. افتح لينك المنصة من claude.ai.':'The AI tutor works when the platform is opened inside Claude. Open the platform link on claude.ai.'});render();return}
TUT.push({role:'user',content:text});tutBusy=true;render();
const toc=DAYS.map(d=>`Module ${d.n}: ${d.t.en} — `+d.units.map(u=>u.id+' '+u.t.en).join('; ')).join('\n');
const rules=`You are the AI tutor of "Claude Mastery", a bilingual course by Dr. Sara Salem (AI Finance Expert) for finance and business professionals in Egypt and the Gulf. Answer in ${LANG==='ar'?'Egyptian Arabic, keeping technical terms in English':'English'}. Teach, don't lecture: if the learner's level is unclear, ask one short calibrating question first; give one focused step and one question per reply; use finance examples; keep replies under 180 words; point to the lesson id from the curriculum when relevant. Be accurate; if unsure, say so. Curriculum:\n${toc}`;
tutCtl=new AbortController();
try{const {text:ans}=await sample([{role:'user',content:rules},{role:'assistant',content:LANG==='ar'?'تمام، جاهز.':'Ready.'},...TUT],{cache:false,signal:tutCtl.signal,modelTier:'quick',onText:({text})=>{const l=document.getElementById('tlive');if(l)l.innerHTML=fmtMD(text)}});TUT.push({role:'assistant',content:ans})}
catch(e){if(e&&e.text)TUT.push({role:'assistant',content:e.text});const msg={not_granted:LANG==='ar'?'المدرّس محتاج موافقتك علشان يستخدم Claude.':'The tutor needs your permission to use Claude.',rate_limited:LANG==='ar'?'استنى شوية وجرّب تاني.':'Please wait a moment and try again.',cancelled:''}[e&&e.code];tutBusy=false;render();const n=note();if(n)n.textContent=msg??(LANG==='ar'?'حصلت مشكلة — جرّب تاني.':'Something went wrong — try again.');return}
tutBusy=false;render();const c=document.getElementById('chat');if(c)c.scrollTop=c.scrollHeight}
// SIM
let simK='close',simI=0,simAppr=true;
function vSim(){crumb(L(UX.sim));const ar=LANG==='ar';const s=SIMS.find(x=>x.k===simK);const steps=s.steps.filter(x=>simAppr||x[0]!=='approval');
const icons={plan:'🗺',tool:'🛠',result:'📥',review:'🔍',repeat:'🔁',approval:'🛡',deliver:'✅'};
let h=`<h1>🔄 ${L(UX.sim)}</h1><p class="lede">${ar?'شوف الوكيل وهو بيشتغل خطوة خطوة: Claude بيقرر يستخدم أداة، التطبيق بينفّذها ويرجّع النتيجة، و Claude يكمّل لحد ما يخلّص.':'Watch an agent work step by step: Claude decides to call a tool, your application executes it and returns the result, and Claude continues until done.'}</p><div class="chips">${SIMS.map(x=>`<button class="chip ${x.k===simK?'on':''}" data-simk="${x.k}">${L(x.t)}</button>`).join('')}</div>`;
h+=`<div class="simloop">${['Goal','Plan','Tool','Result','Review','Repeat','Deliver'].map((x,i)=>{const map={0:'goal',1:'plan',2:'tool',3:'result',4:'review',5:'repeat',6:'deliver'};const cur=simI===0?'goal':(steps[simI-1]||[''])[0];return `<span class="${map[i]===cur||(map[i]==='review'&&cur==='approval')?'on':''}">${ar?['الهدف','الخطة','الأداة','النتيجة','المراجعة','التكرار','التسليم'][i]:x}</span>`}).join('<b>→</b>')}</div>`;
h+=`<label class="opt"><input type="checkbox" data-simappr="1" ${simAppr?'checked':''}> ${ar?'موافقة بشرية قبل الإجراءات الخارجية':'Human approval before external actions'}</label>`;
h+=`<div class="simlog"><div class="lg goal">🎯 ${ar?'الهدف':'Goal'}: ${L(s.goal)}</div>${steps.slice(0,simI).map(x=>`<div class="lg ${x[0]}">${icons[x[0]]} ${esc(L(x[1]))}</div>`).join('')}</div>`;
h+=simI<steps.length?`<button class="dlbtn" data-simnext="1">${ar?'الخطوة الجاية ▶':'Next step ▶'}</button>`:`<div class="case">${ar?'خلصت الحلقة. الوكيل سلّم النتيجة.':'Loop complete. The agent delivered the result.'} <button class="tbtn" data-simreset="1">${ar?'شغّل تاني':'Run again'}</button></div>`;
return h}
// BUILDER
let PB_={role:'',task:'',context:'',reasoning:'',stop:'',output:'',ctrl:[0,1,2,3]};
const PB_CTRL=[T("Ask up to 3 clarifying questions first.","اسألني لحد 3 أسئلة توضيحية الأول."),T("Label every assumption.","علّم على كل افتراض."),T("Never invent numbers; write [MISSING].","متألّفش أرقام؛ اكتب [ناقص]."),T("Check every number against its source before finishing.","راجع كل رقم على مصدره قبل ما تخلّص."),T("Show me the plan before acting.","وريني الخطة قبل التنفيذ."),T("Drafts only — ask before sending, posting or deleting.","مسودات بس — اسأل قبل الإرسال أو النشر أو المسح."),T("End with the 3 next steps.","اختم بأهم 3 خطوات جاية.")];
function pbOut(){const c=PB_.ctrl.map(i=>'- '+L(PB_CTRL[i])).join('\n');return `<role>${PB_.role}</role>\n<task>${PB_.task}</task>\n<context>\n${PB_.context}\n</context>\n<reasoning>${PB_.reasoning}</reasoning>\n<stop_when>\n${PB_.stop}\n</stop_when>\n<output_format>\n${PB_.output}\n</output_format>${c?'\n<controls>\n'+c+'\n</controls>':''}`}
function vBuilder(){crumb(L(UX.builder));const ar=LANG==='ar';const F=[['role',T('1 · Role','1 · الدور'),T('Senior FP&A analyst at an Egyptian retailer','محلل FP&A أول في شركة تجزئة مصرية')],['task',T('2 · Task','2 · المهمة'),T('Build the September variance pack','اعمل حزمة انحرافات سبتمبر')],['context',T('3 · Context','3 · السياق'),T('Files, numbers, period, currency, audience, constraints','الملفات، الأرقام، الفترة، العملة، الجمهور، القيود')],['reasoning',T('4 · Reasoning','4 · المنطق'),T('The decision this supports','القرار اللي بيدعمه')],['stop',T('5 · Stop conditions','5 · شروط التوقف'),T('What done looks like (checklist)','شكل الانتهاء (قائمة)')],['output',T('6 · Output format','6 · شكل المخرج'),T('Table/memo/xlsx, language, length','جدول/مذكرة/xlsx، اللغة، الطول')]];
const filled=F.filter(f=>PB_[f[0]].trim()).length;const i=PSTORE.push(pbOut())-1;window._pbi=i;
return `<h1>🧱 ${L(UX.builder)}</h1><p class="lede">${ar?'املا البلوكات الستة واختار الضوابط — البرومبت الماستر بيتكتب لوحده.':'Fill the six blocks and pick your controls — the master prompt writes itself.'}</p><div class="bar"><span style="width:${filled*100/6}%"></span></div><div class="pbgrid"><div>${F.map(f=>`<label class="pbf"><b>${L(f[1])}</b><textarea data-pb="${f[0]}" rows="${f[0]==='context'||f[0]==='stop'?4:2}" placeholder="${esc(L(f[2]))}">${esc(PB_[f[0]])}</textarea></label>`).join('')}<b>${ar?'الضوابط (كلماتي القوية)':'Controls (my power words)'}</b>${PB_CTRL.map((c,j)=>`<label class="opt"><input type="checkbox" data-pbc="${j}" ${PB_.ctrl.includes(j)?'checked':''}> ${L(c)}</label>`).join('')}</div><div><div class="prompt"><div class="ph"><h3>${ar?'البرومبت الماستر':'Your master prompt'}</h3><span><button class="copy" data-i="${i}">${L(UI.copy)}</button> <button class="dlbtn" data-pbsave="1">${ar?'احفظ':'Save'}</button></span></div><pre dir="auto" id="pbout">${esc(pbOut())}</pre></div>${ST.mine.length?`<h3>${ar?'برومبتاتي المحفوظة':'My saved prompts'}</h3>`+ST.mine.map((p,k)=>{const ii=PSTORE.push(p.p)-1;return `<div class="skill"><b>${esc(p.t)}</b><div class="tr">${p.d}</div><button class="copy" data-i="${ii}">${L(UI.copy)}</button> <button class="tbtn" data-pbdel="${k}">${ar?'امسح':'Delete'}</button></div>`}).join(''):''}${builderExtras()}</div></div>`}
// PROGRESS + CERT
function vProg(){crumb(L(UX.prog));const s=stats();const ar=LANG==='ar';return `<h1>🏅 ${L(UX.prog)}</h1><div class="stat4"><div><b>${s.xp}</b>XP</div><div><b>${s.streak}🔥</b>${ar?'أيام ورا بعض':'day streak'}</div><div><b>${s.pct}%</b>${ar?'المنهج':'curriculum'}</div><div><b>${s.quizAvg}%</b>${ar?'متوسط الاختبارات':'quiz average'}</div></div><h2>${ar?'الشارات':'Badges'}</h2><div class="badges">${BADGES.map(b=>{const ok=b[3](s);return `<div class="badge ${ok?'on':''}"><span>${b[1]}</span>${L(b[2])}</div>`}).join('')}</div><h2>${ar?'إزاي تكسب نقط':'How to earn XP'}</h2><ul><li>${ar?'خلّص درس':'Complete a lesson'}: +${XPV.lesson}</li><li>${ar?'كل إجابة صح':'Each correct answer'}: +${XPV.quiz}</li><li>${ar?'شغّل حلقة وكيل للآخر':'Finish an agent-loop run'}: +${XPV.sim}</li><li>${ar?'انسخ برومبت':'Copy a prompt'}: +${XPV.copy}</li></ul><button class="dlbtn" data-go="cert">🎓 ${L(UX.cert)}</button>`}
function tier(q){return q>=90?['Gold','ذهبية','#C9A227']:q>=80?['Silver','فضية','#9AA4B2']:['Bronze','برونزية','#B07A4A']}
function certId(){let h=0;const s=(ST.name||'')+'|'+DONE.length+'|'+quizAvg();for(const c of s)h=(h*31+c.charCodeAt(0))>>>0;return 'CM-'+h.toString(36).toUpperCase().padStart(7,'0')}
function certSVG(){const s=stats();const t=tier(s.quizAvg);const d=new Date().toISOString().slice(0,10);const nm=esc(ST.name||'—');const qr=QR_PLATFORM.replace(/<svg/,'<svg x="890" y="560" width="150" height="150"');
return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800" width="1200" height="800"><rect width="1200" height="800" fill="#FBF8F1"/><rect x="24" y="24" width="1152" height="752" fill="none" stroke="#13284B" stroke-width="6"/><rect x="40" y="40" width="1120" height="720" fill="none" stroke="${t[2]}" stroke-width="2"/><text x="600" y="140" text-anchor="middle" font-family="Readex Pro,Arial" font-size="22" fill="#46556E" letter-spacing="6">CERTIFICATE OF COMPLETION · شهادة إتمام</text><text x="600" y="215" text-anchor="middle" font-family="Readex Pro,Arial" font-weight="700" font-size="54" fill="#13284B">Claude Mastery</text><text x="600" y="265" text-anchor="middle" font-family="Readex Pro,Arial" font-size="20" fill="#46556E">Claude for business — 9 modules · ${DAYS.reduce((a,d)=>a+d.units.length,0)} lessons</text><text x="600" y="345" text-anchor="middle" font-family="Readex Pro,Arial" font-size="20" fill="#46556E">This certifies that · نشهد بأن</text><text x="600" y="420" text-anchor="middle" font-family="Amiri,Readex Pro,Arial" font-weight="700" font-size="56" fill="#13284B">${nm}</text><line x1="330" y1="445" x2="870" y2="445" stroke="${t[2]}" stroke-width="2"/><text x="600" y="495" text-anchor="middle" font-family="Readex Pro,Arial" font-size="20" fill="#13284B">completed the curriculum with a quiz average of ${s.quizAvg}% · ${t[0]} level · المستوى ${t[1]}</text><circle cx="190" cy="630" r="70" fill="${t[2]}"/><text x="190" y="640" text-anchor="middle" font-family="Readex Pro,Arial" font-weight="700" font-size="26" fill="#fff">${t[0].toUpperCase()}</text><text x="600" y="640" text-anchor="middle" font-family="Amiri,Arial" font-size="30" fill="#13284B">Dr. Sara Salem · د. سارة سالم</text><text x="600" y="672" text-anchor="middle" font-family="Readex Pro,Arial" font-size="16" fill="#46556E">Creator &amp; instructor — AI Finance Expert</text><text x="600" y="720" text-anchor="middle" font-family="Readex Pro,Arial" font-size="14" fill="#7A869A">${certId()} · ${d}</text>${qr}</svg>`}
function vCert(){crumb(L(UX.cert));const s=stats();const ar=LANG==='ar';const ok=s.pct>=100&&s.quizAvg>=70;
let h=`<h1>🎓 ${L(UX.cert)}</h1><p class="lede">${ar?'الشهادة بتتفتح لما تخلّص كل الدروس وتجيب متوسط 70% أو أكتر في الاختبارات. المستويات: برونزي 70% وفضي 80% ودهبي 90%.':'Unlocks when you complete every lesson and average 70%+ in the quizzes. Levels: Bronze 70%, Silver 80%, Gold 90%.'}</p><div class="stat4"><div><b>${s.pct}%</b>${ar?'الدروس':'lessons'}</div><div><b>${s.quizAvg}%</b>${ar?'الاختبارات':'quizzes'}</div><div><b>${Object.keys(ST.quiz).length}/${DAYS.length}</b>${ar?'اختبارات متخلّصة':'quizzes taken'}</div></div>`;
h+=`<label class="pbf"><b>${ar?'الاسم على الشهادة (عربي أو إنجليزي)':'Name on certificate (Arabic or English)'}</b><input id="cname" class="search" value="${esc(ST.name)}"></label>`;
h+=`<div class="certwrap ${ok?'':'locked'}">${certSVG()}${ok?'':`<div class="lockmsg">${ar?'لسه — كمّل الدروس والاختبارات':'Not yet — finish lessons and quizzes'}</div>`}</div>`;
if(ok)h+=`<div class="row-btns">${mailBtns('Claude Mastery certificate — '+certId(),(LANG==='ar'?'خلّصت منهج Claude Mastery. كود التحقق: ':'I completed Claude Mastery. Verification code: ')+certId()+'\n'+PLATFORM_URL)}</div><p><button class="dlbtn" data-certdl="1">${ar?'نزّل الشهادة (SVG)':'Download certificate (SVG)'}</button></p><p class="note">${ar?'كود التحقق':'Verification code'}: ${certId()} — ${ar?'الـ QR بيودّي للمنصة.':'the QR links to the platform.'}</p>`;
return h}
// LIVE
let LIVE=null;
function liveSlides(d,u){const ar=LANG==='ar';const S=[];S.push(`<div class="ls-title"><div class="k">${L(UI.day)} ${d.n} · ${L(d.t)}</div><h1>${u.id} · ${L(u.t)}</h1><div class="sig">${ar?'د. سارة سالم':'Dr. Sara Salem'}</div></div>`);
if(CEO[u.id])S.push(`<h2>👔 ${L(UX.ceo)}</h2><p class="big">${L(CEO[u.id])}</p>`);
const tmp=document.createElement('div');tmp.innerHTML=L(u.body);let buf='';[...tmp.children].forEach(el=>{if(el.tagName==='H3'&&buf){S.push(buf);buf=''}buf+=el.outerHTML;if(el.tagName!=='H3'&&buf.length>500){S.push(buf);buf=''}});if(buf)S.push(buf);
const st=L(u.steps)||[];if(st.length)S.push(`<h2>${L(UI.steps)}</h2><ol class="steps">${st.map(x=>`<li>${x}</li>`).join('')}</ol>`);
(u.cases||[]).forEach(c=>S.push(`<h2>💼 ${L(c.t)}</h2><p class="big">${L(c.d)}</p>`));
(u.prompts||[]).slice(-1).forEach(p=>S.push(`<h2>✎ ${L(p.t)}</h2><pre class="lspre" dir="auto">${esc(L(p.p))}</pre>`));return S}
function openLive(n,id){const d=DAYS.find(x=>x.n==n),u=d.units.find(x=>x.id==id);LIVE={s:liveSlides(d,u),i:0};drawLive()}
function drawLive(){let o=document.getElementById('live');if(!LIVE){if(o)o.remove();return}if(!o){o=document.createElement('div');o.id='live';o.className='liveov';document.body.appendChild(o)}
o.innerHTML=`<div class="lsl">${LIVE.s[LIVE.i]}</div><div class="lnav"><button data-lv="-1">‹</button><span>${LIVE.i+1}/${LIVE.s.length}</span><button data-lv="1">›</button><button data-lv="x">✕</button></div>`}
// SEARCH
let IDX=null,SQ='';
function strip(h){return String(h||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')}
function buildIdx(){IDX=[];const add=(t,txt,r,k)=>IDX.push({t,txt:(t.en+' '+t.ar+' '+txt).toLowerCase(),r,k,snip:txt});
DAYS.forEach(d=>d.units.forEach(u=>add(T(u.id+' · '+u.t.en,u.id+' · '+u.t.ar),strip(u.body.en+' '+u.body.ar)+' '+(u.steps.en||[]).join(' '),`day/${d.n}/${u.id}`,T('Lesson','درس'))));
Object.keys(DEEP).forEach(k=>{DEEP[k].sections.forEach(s=>add(T(DEEP[k].t.en+' › '+s.h.en,DEEP[k].t.ar+' › '+s.h.ar),strip(s.b.en+' '+s.b.ar),`deep/${k}`,T('Deep dive','تعمق')));DEEP[k].cases.forEach(c=>add(c.t,strip(c.p.en+' '+c.p.ar),`deep/${k}`,T('Case','حالة')))});
CASES.forEach(g=>g.items.forEach(c=>add(c.t,strip((c.d.en||'')+' '+(c.d.ar||'')+' '+c.p.en+' '+c.p.ar),'cases',T('Use case · '+g.t.en,'حالة · '+g.t.ar))));
LAB.forEach(c=>add(c.t,strip(c.p.en+' '+c.p.ar),'lab',T('Lab','المعمل')));
WORDS.forEach(g=>g.w.forEach(w=>add(T(w[0],w[1]),'','words',T('Power word','كلمة قوية'))));
GLOSS.forEach(g=>add(T(g[0],g[1]),g[2]+' '+g[3],'glossary',T('Glossary','القاموس')));
WORKCATS.forEach(c=>c.items.forEach(w=>add(w.t,strip(w.d.en+' '+w.d.ar),'work',T('My work','أعمالي'))));
SKILLS.forEach(g=>g.items.forEach(s=>add(T(s.n,s.n),s.d.en+' '+s.d.ar+' '+s.w.en+' '+s.w.ar+' '+s.f.en+' '+s.f.ar,'skills',T('Skill','Skill'))));}
function vSearch(q){q=decodeURIComponent(q||'');crumb(L(UX.search));if(!IDX)buildIdx();const terms=q.toLowerCase().split(/\s+/).filter(Boolean);
const res=terms.length?IDX.map(x=>({x,s:terms.reduce((a,t)=>a+(x.txt.includes(t)?1:0)+((x.t.en+x.t.ar).toLowerCase().includes(t)?2:0),0)})).filter(r=>r.s>=terms.length).sort((a,b)=>b.s-a.s).slice(0,60):[];
return `<h1>⌕ ${LANG==='ar'?'نتايج البحث':'Search results'}</h1><input class="search" id="sq2" value="${esc(q)}" placeholder="${L(UX.search)}"><p class="note">${res.length} ${LANG==='ar'?'نتيجة':'results'}</p>`+res.map(r=>{const t=terms[0]||'';const s=r.x.snip||'';const i=s.toLowerCase().indexOf(t);const sn=i>=0?'…'+esc(s.slice(Math.max(0,i-60),i+120))+'…':'';return `<a class="case srch" href="#${r.x.r}"><div class="meta">${L(r.x.k)}</div><h3>${esc(L(r.x.t))}</h3>${sn?`<div class="k" style="font-size:13px;color:var(--ink2)">${sn}</div>`:''}</a>`}).join('')}
