// ---------- Round 13: assistant (tutor merged, page-aware, test prompt, file upload, exports, voice), career paths, PPT exports ----------
const uById=id=>{const r=unitById(id);return r?r[1]:null};
const UX19={careers:T('Career paths','المسارات المهنية'),pptx:T('Export as PPT','صدّر PPT')};

// ---- shared PowerPoint helper: slides = [{h, sub?, lines?:[], code?:string, notes?}]
async function pptDeck(title,sub,slides,filename){await loadScript('https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.bundle.js',()=>window.PptxGenJS);const ar=LANG==='ar';const al=ar?'right':'left';
const pres=new PptxGenJS();pres.layout='LAYOUT_WIDE';pres.rtlMode=ar;const NAVY='13284B',GOLD='C9A227',INK='1E293B';let qr=null;try{qr=await svgPng(QR_PLATFORM)}catch(e){}
let s=pres.addSlide();s.background={color:NAVY};s.addText('Claude Mastery',{x:0.6,y:0.7,w:9,h:0.5,fontSize:18,color:GOLD,fontFace:'Arial',align:al,rtlMode:ar});s.addText(title,{x:0.6,y:1.4,w:10.5,h:1.8,fontSize:36,bold:true,color:'FFFFFF',fontFace:'Arial',align:al,rtlMode:ar,valign:'top'});if(sub)s.addText(sub,{x:0.6,y:3.3,w:10.5,h:1.2,fontSize:17,color:'C7D1E2',fontFace:'Arial',align:al,rtlMode:ar,valign:'top'});s.addText(ar?'د. سارة سالم — صانعة المحتوى والمدرّبة':'Dr. Sara Salem — Creator & instructor',{x:0.6,y:5.9,w:8,h:0.5,fontSize:14,color:'FFFFFF',fontFace:'Arial',align:al,rtlMode:ar});if(qr)s.addImage({data:qr,x:11,y:5,w:1.7,h:1.7});
const chunk=(arr,n)=>{const o=[];for(let i=0;i<arr.length;i+=n)o.push(arr.slice(i,i+n));return o};
slides.forEach(sl=>{const lines=(sl.lines||[]).filter(Boolean);const parts=lines.length?chunk(lines,7):[[]];parts.forEach((pl,pi)=>{if(!pl.length&&sl.code&&pi===0)return;const a=pres.addSlide();a.background={color:'F4F6FA'};a.addText(sl.h+(parts.length>1?` (${pi+1}/${parts.length})`:''),{x:0.5,y:0.3,w:12.3,h:0.9,fontSize:26,bold:true,color:NAVY,fontFace:'Arial',align:al,rtlMode:ar});if(sl.sub&&pi===0)a.addText(sl.sub,{x:0.5,y:1.15,w:12.3,h:0.5,fontSize:14,color:'5B6B82',fontFace:'Arial',align:al,rtlMode:ar});
if(pl.length)a.addText(pl.map((x,i)=>({text:String(x).slice(0,400),options:{bullet:true,breakLine:i<pl.length-1}})),{x:0.5,y:1.8,w:12.3,h:5.2,fontSize:16,color:INK,fontFace:'Arial',align:al,rtlMode:ar,paraSpaceAfter:8,valign:'top'});if(sl.notes)a.addNotes(String(sl.notes).slice(0,2500))});
if(sl.code){const cl=String(sl.code).split('\n');chunk(cl,22).forEach((c,ci,all)=>{const b=pres.addSlide();b.background={color:'FFFFFF'};b.addText('✎ '+sl.h+(all.length>1?` (${ci+1}/${all.length})`:''),{x:0.5,y:0.3,w:12.3,h:0.7,fontSize:20,bold:true,color:NAVY,fontFace:'Arial',align:al,rtlMode:ar});b.addText(c.join('\n'),{x:0.5,y:1.1,w:12.3,h:6.1,fontSize:11,color:INK,fontFace:'Courier New',valign:'top',fill:{color:'EEF2F7'},margin:10,align:/[؀-ۿ]/.test(c.join(''))?'right':'left',rtlMode:/[؀-ۿ]/.test(c.join(''))})})}});
const blob=await pres.write({outputType:'blob'});return saveFile(filename,blob)}

// ---- 1. AI tutor merged into the assistant
UX.tutor=T('AI assistant','المساعد الذكي');

// ---- 2. Page-aware context
function asPage(){const r=(location.hash.slice(1)||'home').split('/');const ar=LANG==='ar';
try{if(r[0]==='day'&&r[2]){const u=uById(r[2]);if(u)return {t:u.t,txt:`Lesson ${u.id} — ${u.t.en}\n${strip(u.body.en||'').slice(0,1500)}\nSteps: ${(u.steps&&u.steps.en||[]).join('; ')}${(u.prompts||[])[0]?'\nLesson master prompt:\n'+u.prompts[0].p.en.slice(0,1200):''}`}}
if(r[0]==='day'&&r[1]){const d=DAYS.find(x=>x.n==r[1]);if(d)return {t:d.t,txt:`Module ${d.n} — ${d.t.en}: ${d.sub?d.sub.en:''}\nLessons: ${d.units.map(u=>u.id+' '+u.t.en).join('; ')}`}}
if(r[0]==='fields'){const f=fieldOf(FLK);const F=FIELDMODS[f.k];return {t:f.t,txt:`Field: ${f.t.en}\nField tasks: ${f.tasks.map(t=>t.t.en).join('; ')}${F?'\nField course: '+F.m.t.en+' — lessons: '+F.m.units.map(u=>u.t.en).join('; '):''}`}}
if(r[0]==='sim'&&SIMTAB==='fin'){const F=FD.find(f=>f.k===FDS.f)||FD[0];return {t:T('Claude Finance Department · '+F.t.en,'الإدارة المالية · '+F.t.ar),txt:`Finance function: ${F.t.en}\nAgents: ${F.agents.map(a=>a.n.en+' ('+a.job.en+')').join('; ')}`}}
if(r[0]==='quiz'){const d=DAYS.find(x=>x.n==r[1]);if(d)return {t:T('Quiz · '+d.t.en,'اختبار · '+d.t.ar),txt:`Quiz for module ${d.n} ${d.t.en}`}}
if(r[0]==='deep'&&DEEP[r[1]]){const D=DEEP[r[1]];return {t:D.t,txt:`Deep dive: ${D.t.en}\n`+(D.sections||[]).map(s=>(s.h?s.h.en:'')+': '+strip(s.b&&s.b.en||'').slice(0,250)).join('\n').slice(0,1800)}}
if(r[0]==='cases')return {t:T('Use-case library','مكتبة حالات الاستخدام'),txt:'Use-case library: '+CASES.map(g=>g.t.en).join(', ')};
const h1=document.querySelector('#view h1');if(h1)return {t:T(h1.textContent,h1.textContent),txt:'Page: '+h1.textContent}}catch(e){}
return null}
const ASK_PAGE=T(['Explain this page simply','Give me a master prompt for this page','Turn this into an agent','Make a Skill from this'],['اشرحلي الصفحة دي ببساطة','اديني برومبت ماستر للصفحة دي','حوّل ده لوكيل','اعمل Skill من ده']);

// ---- 7. File upload (CSV, TXT, MD, JSON, XLSX)
let ASF=null;
async function asReadFile(file){const n=file.name.toLowerCase();if(file.size>8*1024*1024)throw new Error('big');
if(/\.(xlsx|xls)$/.test(n)){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js',()=>window.XLSX);const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});return wb.SheetNames.slice(0,3).map(s=>`### Sheet: ${s}\n`+XLSX.utils.sheet_to_csv(wb.Sheets[s])).join('\n\n')}
return await file.text()}

// ---- assistant: send with page context + attached file
{const _ask=asAsk;asAsk=async function(q){if(!q||!q.trim()||AS.busy)return;const pg=asPage();AS._page=pg;AS._file=ASF;ASF=null;return _ask(q)}}
{const _sample=tutorSample;tutorSample=async function(){const s=await _sample();if(!s||s._asWrapped)return s;const w=async(input,opts)=>{if(Array.isArray(input)&&input.length&&AS.busy){input=input.slice();const pg=AS._page,fl=AS._file;if(pg||fl){const first=Object.assign({},input[0]);first.content+=`${pg?`\n\nCURRENT PAGE the learner is looking at (answer about it when they say "this page", "this lesson" or "this"):\n${pg.txt}`:''}${fl?`\n\nATTACHED FILE from the learner (${fl.name}) — use it as the data/context; do not repeat it back in full:\n${fl.text.slice(0,40000)}`:''}`;input[0]=first}}return s(input,opts)};w.json=(...a)=>s.json(...a);w._asWrapped=true;return w}}
// re-wrap the cached sampler (it may already be resolved)
try{if(typeof TUTSAMPLE!=='undefined')TUTSAMPLE=undefined}catch(e){}

// ---- 4. Test a generated prompt on sample data
function asPickData(p){const t=asNorm(p);let best=null,bs=0;Object.keys(DATA).forEach(k=>{const cols=DATA[k].csv.split('\n')[0].split(',');let s=(t.includes(k)?5:0)+cols.reduce((a,c)=>a+(t.includes(c.replace(/_/g,' '))||t.includes(c)?1:0),0)+(t.includes(asNorm(DATA[k].en))?3:0);if(s>bs){bs=s;best=k}});return best||'kpis'}
async function asTest(mi,ci){const m=AS.msgs[mi];if(!m||!m.prompts)return;const p=m.prompts[ci];const ar=LANG==='ar';m.tests=m.tests||{};const k=asPickData(p);const rows=DATA[k].csv.split('\n').slice(0,26).join('\n');
m.tests[ci]={busy:true,data:k};asRender();const sample=await tutorSample();if(!sample){m.tests[ci]={err:ar?'الاختبار بيشتغل لما المنصة تتفتح جوه Claude.':'Testing works when the platform is opened inside Claude.'};asRender();return}
try{const {text}=await sample(`${p}\n\n---\nTEST RUN on fictional sample data «${DATA[k].en}» (${k}.csv):\n${rows}\n\nRun the prompt on this data now. If something essential is missing, state your assumption instead of asking. Keep the answer under 350 words.`,{modelTier:'quick'});
const score=/<role>|<job>/.test(p)?pkScoreFull(p).score:null;m.tests[ci]={out:text,score,data:k}}catch(e){m.tests[ci]={err:e&&e.code==='rate_limited'?(ar?'طلبات كتير — جرّب بعد شوية.':'Too many requests — try again soon.'):(ar?'مقدرتش أختبر دلوقتي.':'Could not test right now.')}}asRender()}

// ---- 8. Export answers / whole chat (MD, PDF, PPT, Skill ZIP)
function asPairs(only){const out=[];AS.msgs.forEach((m,i)=>{if(m.role==='assistant'&&(only===undefined||only===i)){const q=(AS.msgs[i-1]&&AS.msgs[i-1].role==='user')?AS.msgs[i-1].text:'';out.push({q,m})}});return out}
function asText(m){return m.text||[m.why,(m.steps||[]).join('\n'),m.en,m.ar].filter(Boolean).join('\n\n')}
async function asExport(fmt,only,btn){const ar=LANG==='ar';const P=asPairs(only);if(!P.length)return;const base='Claude-Mastery-assistant-'+new Date().toISOString().slice(0,10);const old=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.textContent='…'}
try{if(fmt==='md'){await saveFile(base+'.md',P.map(x=>`## ${x.q}\n\n${asText(x.m)}\n`).join('\n---\n\n')+'\n\n— Claude Mastery assistant\n')}
else if(fmt==='pdf'){await multiPagePDF(P.map(x=>`<div class="exdoc" dir="${ar?'rtl':'ltr'}"><div class="k">Claude Mastery · ${ar?'المساعد':'Assistant'}</div><h2>${esc(x.q)}</h2>${asFmt(asText(x.m))}</div>`),base+'.pdf')}
else if(fmt==='ppt'){const sl=[];P.forEach(x=>{const t=asText(x.m);const prose=t.replace(/```[a-zA-Z]*\n?[\s\S]*?(```|$)/g,'').split('\n').map(l=>l.replace(/^#+\s*|\*\*/g,'').trim()).filter(l=>l&&l.length>2);sl.push({h:x.q.slice(0,90),lines:prose.slice(0,21)});[...t.matchAll(/```[a-zA-Z]*\n([\s\S]*?)```/g)].forEach((c,i)=>sl.push({h:(ar?'برومبت ':'Prompt ')+(i+1)+' — '+x.q.slice(0,60),code:c[1].trim()}))});await pptDeck(ar?'إجابات المساعد':'Assistant answers',P.length+(ar?' سؤال':' questions'),sl,base+'.pptx')}
else if(fmt==='skill'){await ensureZip();const z=new JSZip();P.forEach((x,i)=>{const t=asText(x.m);const blocks=[...t.matchAll(/```[a-zA-Z]*\n([\s\S]*?)```/g)].map(c=>c[1].trim());const sk=blocks.find(b=>/^---\s*\nname:/.test(b));const nm=sk?(sk.match(/name:\s*([a-z0-9-]+)/)||[])[1]:null;const id=nm||slug(x.q).slice(0,40)||'skill-'+(i+1);
const md=sk||`---\nname: ${id}\ndescription: ${JSON.stringify(('Use when the user asks: '+x.q).slice(0,900))}\n---\n\n# ${x.q}\n\n## Method\nFollow the master prompt below. Ask up to 3 clarifying questions first, label assumptions, never invent numbers, and mark items for human review.\n\n## Master prompt\n\n${blocks[0]||t}\n`;z.folder(id).file('SKILL.md',md);blocks.filter(b=>b!==sk&&/[؀-ۿ]/.test(b)).slice(0,1).forEach(b=>z.folder(id).file('SKILL.ar.md',b))});await saveFile(base+'-skills.zip',await z.generateAsync({type:'blob'}))}
if(btn)btn.textContent='✓'}catch(e){console.error(e);if(btn)btn.textContent=ar?'تعذّر':'Failed'}if(btn){btn.disabled=false;setTimeout(()=>{if(btn.isConnected)btn.textContent=old},2000)}}

// ---- 12. Voice input
let ASV=null;function asVoice(btn){const ar=LANG==='ar';const SR=window.SpeechRecognition||window.webkitSpeechRecognition;const note=t=>{const n=document.getElementById('asnote');if(n)n.textContent=t};
if(!SR){note(ar?'الإدخال بالصوت مش متاح في المتصفح ده — استخدم زرار الميكروفون في كيبورد موبايلك.':'Voice input is not available in this browser — use the microphone key on your phone keyboard.');return}
if(ASV){try{ASV.stop()}catch(e){}ASV=null;btn.classList.remove('on');return}
try{const r=new SR();r.lang=ar?'ar-EG':'en-US';r.interimResults=true;r.continuous=false;const t=document.getElementById('asq');const base=t?t.value:'';
r.onresult=e=>{let s='';for(const x of e.results)s+=x[0].transcript;if(t)t.value=(base?base+' ':'')+s};r.onerror=e=>{note(e.error==='not-allowed'||e.error==='service-not-allowed'?(ar?'المايك مش مسموح هنا — استخدم ميكروفون الكيبورد أو اكتب سؤالك.':'The microphone is not allowed here — use your keyboard’s dictation or type your question.'):(ar?'مقدرتش أسمع — جرّب تاني.':'Could not hear you — try again.'))};r.onend=()=>{ASV=null;btn.classList.remove('on')};r.start();ASV=r;btn.classList.add('on');note(ar?'🎤 بسمعك…':'🎤 Listening…')}catch(e){note(ar?'الإدخال بالصوت مش متاح هنا.':'Voice input is not available here.')}}

// ---- assistant UI additions (wrap render)
{const _r=asRender;asRender=function(){_r();const b=document.getElementById('asbox');if(!b||!AS.open)return;const ar=LANG==='ar';const pg=asPage();
const head=b.querySelector('.ashead');if(head&&AS.msgs.some(m=>m.role==='assistant')){const x=document.createElement('span');x.className='asexp';x.innerHTML=`<span class="k">⬇ ${ar?'المحادثة':'Chat'}:</span>${['md','pdf','ppt','skill'].map(f=>`<button class="tbtn" data-asexp="${f}">${f==='skill'?'Skill ZIP':f.toUpperCase()}</button>`).join('')}`;head.after(x)}
const msgs=[...b.querySelectorAll('.asmsgs .msg.assistant')];let ai=0;AS.msgs.forEach((m,i)=>{if(m.role!=='assistant')return;const el=msgs[ai++];if(!el)return;
if(m.prompts&&m.prompts.length){el.querySelectorAll('.asp').forEach((box,ci)=>{const ph=box.querySelector('.ph');if(ph&&/<role>|<job>|^---/m.test(m.prompts[ci]||''))ph.insertAdjacentHTML('beforeend',`<button class="tbtn" data-astest="${i}|${ci}">▶ ${ar?'اختبره':'Test it'}</button>`);const t=m.tests&&m.tests[ci];if(t)box.insertAdjacentHTML('beforeend',t.busy?`<div class="astest">⏳ ${ar?'بيتجرب على':'Testing on'} ${t.data}.csv…</div>`:t.err?`<div class="astest">${esc(t.err)}</div>`:`<div class="astest"><div class="k">🧪 ${ar?'تجربة على بيانات':'Test on sample data'} <b>${t.data}.csv</b>${t.score!=null?` · ${ar?'جودة البرومبت':'Prompt score'} <span class="pkscore ${t.score>=80?'hi':t.score>=55?'mid':'lo'}">${t.score}</span>`:''}</div>${fmtMD(t.out)}</div>`)})}
el.insertAdjacentHTML('beforeend',`<div class="asone"><span class="k">⬇</span>${['md','pdf','ppt','skill'].map(f=>`<button class="tbtn" data-asexp1="${f}|${i}">${f==='skill'?'Skill':f.toUpperCase()}</button>`).join('')}</div>`)});
const box=b.querySelector('.asmsgs');if(box&&!AS.msgs.length&&pg){box.insertAdjacentHTML('afterbegin',`<div class="aspage">📍 ${ar?'إنت في':'You are on'}: <b>${esc(L(pg.t))}</b><div class="chips">${L(ASK_PAGE).map((s,i)=>`<button class="chip" data-aspage="${i}">${esc(s)}</button>`).join('')}</div></div>`)}
const ask=b.querySelector('.ask');if(ask){ask.insertAdjacentHTML('afterbegin',`<div class="astools"><label class="tbtn" title="${ar?'ارفع ملف':'Attach a file'}">📎<input type="file" id="asfile" accept=".csv,.txt,.md,.json,.tsv,.xlsx,.xls" hidden></label><button class="tbtn" data-asvoice="1" title="${ar?'اسأل بصوتك':'Ask by voice'}">🎤</button></div>`);ask.insertAdjacentHTML('beforebegin',`<div class="asfoot">${ASF?`<span class="asfile">📎 ${esc(ASF.name)} · ${Math.round(ASF.text.length/1000)}k ${ar?'حرف':'chars'} <button class="tbtn" data-asfx="1">✕</button></span>`:''}<span class="k" id="asnote">${ASF?(ar?'متشاركش بيانات سرية إلا لو شركتك سامحة.':'Do not share confidential data unless your company allows it.'):''}</span></div>`)}
const mm=document.getElementById('asmsgs');if(mm)mm.scrollTop=mm.scrollHeight}}

// ---- 18. Career paths with certificates
const CAREERS=[
{k:'finmgr',icon:'💼',t:T('AI-ready finance manager','مدير مالي جاهز للـ AI'),d:T('Run reporting, forecasting and close with Claude and keep control of every number.','شغّل التقارير والتوقعات والإقفال بـ Claude وخلّي كل رقم تحت سيطرتك.'),ls:['1.4','1.6','2.2','4.1','5.1','5.7','6.1','9.4'],fl:['finance','fpa'],pj:5,ex:'fd'},
{k:'cfo',icon:'🏛',t:T('AI-ready CFO','مدير مالي تنفيذي جاهز للـ AI'),d:T('Lead finance strategy, capital decisions and an AI-enabled finance team.','قود استراتيجية المالية وقرارات رأس المال وفريق مالي شغال بالـ AI.'),ls:['1.4','2.2','4.4','6.2','8.1','8.2','9.4','9.6'],fl:['cfo','treasury'],pj:8,ex:'cap'},
{k:'hr',icon:'👥',t:T('AI lead in HR','قائد AI في الموارد البشرية'),d:T('Bring Claude into hiring, performance, policy and people analytics — fairly and privately.','دخّل Claude في التوظيف والأداء والسياسات وتحليلات الموظفين — بعدل وخصوصية.'),ls:['1.4','1.6','2.2','4.1','8.3','9.7','9.8','10.1'],fl:['hr','trainer'],pj:9},
{k:'growth',icon:'📈',t:T('AI-powered sales & marketing leader','قائد مبيعات وتسويق بالـ AI'),d:T('Win more deals and run campaigns faster with research, proposals and content on Claude.','اكسب صفقات أكتر وشغّل حملات أسرع بالبحث والعروض والمحتوى على Claude.'),ls:['1.4','1.6','3.1','4.3','5.2','10.1','8.8'],fl:['sales','marketing'],pj:3},
{k:'audit',icon:'🔍',t:T('AI-ready auditor & compliance officer','مراجع ومسؤول التزام جاهز للـ AI'),d:T('Plan, test and report with Claude while keeping evidence and independence.','خطط واختبر واكتب التقارير بـ Claude مع الحفاظ على الأدلة والاستقلالية.'),ls:['1.4','1.9','5.5','5.8','9.5','9.6','9.7','9.8'],fl:['audit','compliance'],pj:9},
{k:'bank',icon:'🏦',t:T('AI-ready banker','مصرفي جاهز للـ AI'),d:T('Credit analysis, trade finance and monitoring with Claude inside bank controls.','تحليل ائتماني وتمويل تجارة ومتابعة بـ Claude جوه ضوابط البنك.'),ls:['1.4','1.6','5.1','5.6','9.5','9.6','10.2'],fl:['banking','tradefin'],pj:5},
{k:'ops',icon:'⚙',t:T('AI operations & supply chain manager','مدير عمليات وسلاسل إمداد بالـ AI'),d:T('SOPs, procurement, projects and automation with Cowork and agents.','إجراءات ومشتريات ومشروعات وأتمتة بـ Cowork والوكلاء.'),ls:['1.4','2.2','4.4','5.1','6.1','6.2'],fl:['operations','procurement','pm'],pj:6},
{k:'sme',icon:'🏪',t:T('AI-enabled SME owner','صاحب شركة صغيرة بالـ AI'),d:T('Run cash, sales, people and growth of a small or family business with Claude.','ادير الكاش والمبيعات والناس ونمو شركة صغيرة أو عائلية بـ Claude.'),ls:['1.4','2.2','8.5','8.6','8.7','8.8','10.1'],fl:['ceo','startup'],pj:8},
{k:'creator',icon:'🎬',t:T('AI content creator & trainer','صانع محتوى ومدرّب بالـ AI'),d:T('Research, script, design and teach in Arabic and English with Claude.','ابحث واكتب وصمّم ودرّب بالعربي والإنجليزي بـ Claude.'),ls:['1.4','3.1','3.2','10.1','10.2','10.3'],fl:['content','trainer'],pj:10}];
function careerState(c){const ls=c.ls.filter(id=>uById(id));const ld=ls.filter(id=>DONE.includes(id)).length;const fl=c.fl.filter(k=>FIELDMODS[k]);const fd=fl.reduce((a,k)=>a+Math.min(4,((ST.fcd||{})[k]||[]).length),0);
const pr=PROJECTS.find(p=>p.n===c.pj);const pjOk=!!(ST.proj&&ST.proj[c.pj]&&ST.proj[c.pj].res&&ST.proj[c.pj].res.total>=70);let ex=null;if(c.ex==='fd')ex={t:T('Run 5 finance-department tasks','شغّل 5 مهام في الإدارة المالية'),ok:Object.keys(ST.fdRun||{}).length>=5,go:'findept'};if(c.ex==='cap')ex={t:T('Pass the CFO capstone','انجح في مشروع المدير المالي'),ok:!!ST.fcapXP,go:'findept/cap'};
const parts=[ls.length?ld/ls.length:1,fl.length?fd/(fl.length*4):1,pr?(pjOk?1:0):1].concat(ex?[ex.ok?1:0]:[]);const pct=Math.round(100*parts.reduce((a,b)=>a+b,0)/parts.length);return {ls,ld,fl,fd,pr,pjOk,ex,pct}}
function careerCertSVG(c){const nm=esc((ST.profile&&ST.profile.name)||ST.name||'—');const d=new Date().toISOString().slice(0,10);const s=careerState(c);const qr=QR_PLATFORM.replace(/\s(width|height)="[^"]*"/g,'').replace(/<svg/,'<svg x="1010" y="560" width="140" height="140"').replace(/<path/,'<rect width="37" height="37" fill="#fff"/><path');
return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 760" width="1200" height="760"><rect width="1200" height="760" fill="#13284B"/><rect x="28" y="28" width="1144" height="704" fill="none" stroke="#D9B44A" stroke-width="3"/><rect x="40" y="40" width="1120" height="680" fill="none" stroke="#D9B44A" stroke-width="1" opacity=".5"/><text x="80" y="130" font-family="Amiri,serif" font-size="34" fill="#F1D27A">Claude Mastery · د. سارة سالم</text><text x="80" y="220" font-family="Arial" font-size="52" font-weight="700" fill="#fff">Career path certificate</text><text x="80" y="285" font-family="Arial" font-size="32" fill="#F1D27A">${esc(c.t.en)}</text><text x="80" y="330" font-family="Arial" font-size="26" fill="#C7D1E2">${esc(c.t.ar)}</text><text x="80" y="420" font-family="Arial" font-size="24" fill="#C7D1E2">Awarded to</text><text x="80" y="485" font-family="Arial" font-size="52" font-weight="700" fill="#F1D27A">${nm}</text><text x="80" y="560" font-family="Arial" font-size="22" fill="#C7D1E2">${s.ls.length} lessons · ${s.fl.length} field courses · module project${s.ex?' · '+esc(s.ex.t.en):''} · ${d}</text><text x="80" y="680" font-family="Arial" font-size="20" fill="#93A2BC">Dr. Sara Salem — Creator &amp; instructor</text>${qr}</svg>`}
function careersSection(){const ar=LANG==='ar';return `<section class="careers" id="careers"><h2>🧭 ${L(UX19.careers)}</h2><p class="k">${ar?'اختار مسار لوظيفتك: دروس + كورسات مجال + مشروع (+ مهمة عملية). خلّص المسار كله وخد شهادة المسار.':'Pick a path for your role: lessons + field courses + a project (+ a practical task). Finish it all to earn the path certificate.'}</p><div class="crgrid">${CAREERS.map(c=>{const s=careerState(c);const open=ST.crOpen===c.k;
return `<div class="crcard ${open?'open':''}"><button class="crhead" data-cro="${c.k}"><span class="cri">${c.icon}</span><span class="crt"><b>${esc(L(c.t))}</b><span class="k">${esc(L(c.d))}</span></span><span class="pkscore ${s.pct>=100?'hi':s.pct>=40?'mid':'lo'}">${s.pct}%</span></button><div class="bar"><span style="width:${s.pct}%"></span></div>
${open?`<div class="crbody"><h4>📘 ${ar?'الدروس':'Lessons'} (${s.ld}/${s.ls.length})</h4><ul>${s.ls.map(id=>{const u=uById(id);const d=DAYS.find(x=>x.units.includes(u));return `<li>${DONE.includes(id)?'✓':'○'} <a href="#day/${d?d.n:id.split('.')[0]}/${id}">${id} · ${esc(L(u.t))}</a></li>`}).join('')}</ul>
<h4>📚 ${ar?'كورسات المجال':'Field courses'} (${s.fd}/${s.fl.length*4})</h4><ul>${s.fl.map(k=>`<li>${Math.min(4,((ST.fcd||{})[k]||[]).length)}/4 <a href="#fields/${k}">${esc(L(FIELDMODS[k].m.t))}</a></li>`).join('')}</ul>
${s.pr?`<h4>🛠 ${ar?'المشروع':'Project'}</h4><p>${s.pjOk?'✓':'○'} <a href="#projects">${esc(L(s.pr.t))}</a> <span class="k">(${ar?'لازم 70+':'needs 70+'})</span></p>`:''}${s.ex?`<h4>🎯 ${ar?'مهمة عملية':'Practical task'}</h4><p>${s.ex.ok?'✓':'○'} <a href="#${s.ex.go}">${esc(L(s.ex.t))}</a></p>`:''}
<div class="row-btns">${s.pct>=100?`<button class="btn-gold" data-crcert="${c.k}">🎓 ${ar?'نزّل شهادة المسار':'Download path certificate'}</button>`:`<span class="k">${ar?'الشهادة بتفتح لما المسار يوصل 100%.':'The certificate unlocks at 100%.'}</span>`}<button class="tbtn" data-crppt="${c.k}">📊 ${ar?'خطة المسار PPT':'Path plan PPT'}</button></div></div>`:''}</div>`}).join('')}</div></section>`}
{const _vc=vCert;vCert=function(){return _vc()+careersSection()}}
async function careerPPT(c,btn){const ar=LANG==='ar';const s=careerState(c);const old=btn.textContent;btn.disabled=true;btn.textContent='…';try{
const sl=[{h:ar?'المسار في سطور':'The path at a glance',lines:[L(c.d),`${s.ls.length} ${ar?'دروس':'lessons'}`,`${s.fl.length} ${ar?'كورسات مجال':'field courses'}`,s.pr?(ar?'مشروع: ':'Project: ')+L(s.pr.t):'',s.ex?L(s.ex.t):'',`${ar?'التقدم الحالي':'Current progress'}: ${s.pct}%`]},
{h:ar?'الدروس':'Lessons',lines:s.ls.map(id=>id+' · '+L(uById(id).t)+(DONE.includes(id)?' ✓':''))}];
s.fl.forEach(k=>{const F=FIELDMODS[k];sl.push({h:L(F.m.t),sub:L(F.m.sub),lines:F.m.units.map(u=>L(u.t))})});
if(s.pr)sl.push({h:(ar?'المشروع: ':'Project: ')+L(s.pr.t),lines:[L(s.pr.brief),(ar?'المطلوب: ':'Deliverable: ')+L(s.pr.deliv)].concat(s.pr.rub.map(r=>L(r.t)))});
await pptDeck(L(c.t),L(c.d),sl,`Claude-Mastery-path-${c.k}.pptx`);btn.textContent='✓'}catch(e){console.error(e);btn.textContent=ar?'تعذّر':'Failed'}btn.disabled=false;setTimeout(()=>{if(btn.isConnected)btn.textContent=old},2000)}

// ---- PPT export for field courses
async function fcPPT(k,btn){const ar=LANG==='ar';const F=FIELDMODS[k];if(!F)return;const old=btn.textContent;btn.disabled=true;btn.textContent='…';try{const sl=[];
F.m.units.forEach(u=>{sl.push({h:L(u.t),sub:`${u.dur} ${L(UI.min)}`,lines:(L(u.steps)||[]).map(strip).concat((L(u.tips)||[]).map(t=>'💡 '+strip(t))),notes:strip(L(u.body))});(u.prompts||[]).forEach(p=>sl.push({h:L(p.t),code:L(p.p)}))});
if(F.quiz.length)sl.push({h:ar?'اختبر نفسك':'Quick quiz',lines:F.quiz.map((q,i)=>`${i+1}. ${L(q.q)} → ${L(q.o[q.a])}`)});if(F.proj)sl.push({h:(ar?'مشروع المجال: ':'Field project: ')+L(F.proj.t),lines:[L(F.proj.brief),(ar?'المطلوب: ':'Deliverable: ')+L(F.proj.deliv)].concat(F.proj.rub.map(r=>L(r.t)))});
await pptDeck(L(F.m.t),L(F.m.sub),sl,`Claude-Mastery-field-course-${k}-${LANG.toUpperCase()}.pptx`);btn.textContent='✓'}catch(e){console.error(e);btn.textContent=ar?'تعذّر':'Failed'}btn.disabled=false;setTimeout(()=>{if(btn.isConnected)btn.textContent=old},2000)}
{const _fc=fieldCourse;fieldCourse=function(k){const h=_fc(k);if(!h)return h;return h.replace(/(<\/h2>)/,`$1<div class="row-btns"><button class="tbtn" data-fcppt="${k}">📊 ${L(UX19.pptx)}</button></div>`)}}

document.addEventListener('click',e=>{const g=s=>e.target.closest(s);let x;
if(x=g('[data-aspage]')){asAsk(L(ASK_PAGE)[+x.dataset.aspage]);return}
if(x=g('[data-astest]')){const [i,c]=x.dataset.astest.split('|').map(Number);asTest(i,c);return}
if(x=g('[data-asexp]')){asExport(x.dataset.asexp,undefined,x);return}
if(x=g('[data-asexp1]')){const [f,i]=x.dataset.asexp1.split('|');asExport(f,+i,x);return}
if(x=g('[data-asvoice]')){asVoice(x);return}
if(x=g('[data-asfx]')){ASF=null;asRender();return}
if(x=g('[data-cro]')){ST.crOpen=ST.crOpen===x.dataset.cro?'':x.dataset.cro;saveST();render();return}
if(x=g('[data-crcert]')){const c=CAREERS.find(y=>y.k===x.dataset.crcert);svgToPng(careerCertSVG(c),2400,1520).then(b=>saveFile(`Claude-Mastery-${c.k}-path-certificate.png`,b));if(!(ST.crCert||{})[c.k]){ST.crCert=Object.assign({},ST.crCert,{[c.k]:1});addXP(25);saveST()}return}
if(x=g('[data-crppt]')){careerPPT(CAREERS.find(y=>y.k===x.dataset.crppt),x);return}
if(x=g('[data-fcppt]')){fcPPT(x.dataset.fcppt,x);return}},true);
document.addEventListener('change',async e=>{const t=e.target;if(t.id!=='asfile'||!t.files||!t.files[0])return;const f=t.files[0];const ar=LANG==='ar';try{const text=await asReadFile(f);ASF={name:f.name,text};asRender()}catch(err){const n=document.getElementById('asnote');if(n)n.textContent=err&&err.message==='big'?(ar?'الملف أكبر من 8 ميجا.':'The file is over 8 MB.'):(ar?'مقدرتش أقرا الملف ده — جرّب CSV أو TXT أو XLSX.':'Could not read this file — try CSV, TXT or XLSX.')}});
