// ===== FEATURES 3: prompt rescue game, explain-like-my-manager, pack test with Claude, pack -> Skill, offline course pack, showcase wall =====
const UX10={rescue:T('Prompt rescue','إنقاذ البرومبت'),elm:T('Explain like my manager','اشرحها لمديري'),wall:T('Showcase wall','حائط الأعمال'),offline:T('Offline course pack','حزمة الكورس أوفلاين')};
const slug=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60);

// ---------- 2. PROMPT RESCUE (before / after game) ----------
const RX_ISSUES=[['role',T('No role or expertise','مفيش دور أو خبرة')],['task',T('Vague task — no single clear deliverable','المهمة مبهمة — مفيش مخرج واحد واضح')],['context',T('No context, facts or data','مفيش سياق أو حقايق أو بيانات')],['numbers',T('No period, currency or limits','مفيش فترة أو عملة أو حدود')],['stop',T('No stop conditions (what “done” looks like)','مفيش شروط توقف (شكل "خلصت")')],['output',T('No output format','مفيش شكل للمخرج')]];
const RX=[
{w:T('Write a report about our sales.','اكتب تقرير عن المبيعات بتاعتنا.'),miss:['role','task','context','numbers','stop','output'],
 m:T(MPen('Senior sales analyst for an Egyptian FMCG distributor','Write the Q3 2026 sales performance report for the commercial director','- Data: attached CRM export (deals, stage, amount EGP, rep)\n- Period: Jul–Sep 2026 vs Q2 2026\n- Targets: EGP 42M quarterly','The director decides where to move two sales reps next quarter','- Revenue vs target and vs Q2, by rep and product\n- Top 3 risks with deal ids\n- Every number traced to the file','One-page report: 5-line summary, table by rep, 3 recommendations.'),MPar('محلل مبيعات أول لموزع سلع استهلاكية في مصر','اكتب تقرير أداء مبيعات الربع التالت 2026 لمدير المبيعات','- البيانات: ملف CRM مرفق (الصفقات، المرحلة، المبلغ بالجنيه، المندوب)\n- الفترة: يوليو–سبتمبر 2026 مقارنة بالربع التاني\n- المستهدف: 42 مليون جنيه في الربع','المدير هيقرر ينقل أنهي مندوبين الربع الجاي','- الإيراد مقابل المستهدف والربع اللي فات، حسب المندوب والمنتج\n- أهم 3 مخاطر بأرقام الصفقات\n- كل رقم متتبّع للملف','تقرير صفحة واحدة: ملخص 5 سطور، جدول بالمندوبين، 3 توصيات.'))},
{w:T('You are a senior FP&A analyst. Analyze the attached file and tell me what you think.','إنت محلل FP&A أول. حلل الملف المرفق وقولي رأيك.'),miss:['task','context','numbers','stop','output'],
 m:T(MPen('Senior FP&A analyst','Explain the budget-vs-actual variances in the attached file for September 2026','- File: bva.csv (cost centre, budget, actual, EGP)\n- Materiality: variances over EGP 250k or 5%\n- Audience: CFO','The CFO must approve a reforecast this week','- Every material variance explained or flagged “needs owner input”\n- Price vs volume split where possible\n- No variance left unexplained without a flag','Table of material variances + 5 bullet insights + questions for budget owners.'),MPar('محلل FP&A أول','اشرح انحرافات الموازنة مقابل الفعلي في الملف المرفق لشهر سبتمبر 2026','- الملف: bva.csv (مركز التكلفة، الموازنة، الفعلي، بالجنيه)\n- الأهمية النسبية: انحرافات فوق 250 ألف جنيه أو 5%\n- الجمهور: المدير المالي','المدير المالي لازم يعتمد إعادة التوقع الأسبوع ده','- كل انحراف مهم متشرح أو متعلّم "محتاج رأي المسؤول"\n- فصل السعر عن الكمية لو ممكن\n- مفيش انحراف من غير شرح أو علامة','جدول الانحرافات المهمة + 5 ملاحظات + أسئلة لمسؤولي الموازنة.'))},
{w:T('Create a 10-slide board deck in English on Q3 results: revenue, margin, cash.','اعمل عرض 10 شرايح للمجلس بالإنجليزي عن نتايج الربع التالت: الإيراد والهامش والكاش.'),miss:['role','context','stop'],
 m:T(MPen('Investor-relations lead preparing board material','Create a 10-slide board deck on Q3 2026 results: revenue, gross margin, cash','- Attached: Q3 management accounts and Q2 deck for style\n- Currency EGP millions; compare to budget and Q3 2025\n- Board asked last time about receivables ageing','The board approves the Q4 capex plan in this meeting','- One message per slide in the title\n- Every chart sourced to the accounts\n- Receivables question answered on its own slide','10 slides in English, speaker notes under 60 words each.'),MPar('مسؤول علاقات المستثمرين بيجهّز مادة المجلس','اعمل عرض 10 شرايح للمجلس عن نتايج الربع التالت 2026: الإيراد وهامش الربح والكاش','- مرفق: حسابات الإدارة للربع التالت وعرض الربع التاني للستايل\n- العملة مليون جنيه؛ مقارنة بالموازنة وبالربع التالت 2025\n- المجلس سأل المرة اللي فاتت عن أعمار المديونيات','المجلس هيعتمد خطة الاستثمار للربع الرابع في الاجتماع ده','- رسالة واحدة لكل شريحة في العنوان\n- كل رسم ليه مصدر من الحسابات\n- سؤال المديونيات ليه شريحة لوحده','10 شرايح بالإنجليزي، ملاحظات المتحدث أقل من 60 كلمة لكل شريحة.'))},
{w:T('As our credit controller, write an email to Al-Nour Trading about invoice INV-2291 (EGP 480,000, 45 days overdue).','بصفتك مسؤول الائتمان، اكتب إيميل لشركة النور للتجارة عن الفاتورة INV-2291 (480,000 جنيه، متأخرة 45 يوم).'),miss:['output','stop'],
 m:T(MPen('Credit controller at a B2B distributor','Write a payment-reminder email to Al-Nour Trading about invoice INV-2291','- Amount: EGP 480,000; 45 days overdue; terms were 30 days\n- Relationship: 6-year customer, usually pays on time\n- Two reminders already sent without reply','Collect this month without damaging a good relationship','- Firm but respectful tone; no threats\n- States amount, due date and a clear ask with a date\n- Offers a call to agree a payment plan','Email in English and Arabic: subject line + body under 150 words.'),MPar('مسؤول ائتمان في شركة توزيع B2B','اكتب إيميل تذكير بالسداد لشركة النور للتجارة عن الفاتورة INV-2291','- المبلغ: 480,000 جنيه؛ متأخرة 45 يوم؛ الشروط كانت 30 يوم\n- العلاقة: عميل من 6 سنين وعادةً بيدفع في ميعاده\n- اتبعت تذكيرين من غير رد','نحصّل الشهر ده من غير ما نخسر علاقة كويسة','- نبرة حازمة ومحترمة؛ من غير تهديد\n- فيه المبلغ وتاريخ الاستحقاق وطلب واضح بتاريخ\n- بيعرض مكالمة للاتفاق على جدولة','إيميل بالعربي والإنجليزي: عنوان + نص أقل من 150 كلمة.'))},
{w:T('Summarize this contract in a table.','لخّص العقد ده في جدول.'),miss:['role','task','context','stop'],
 m:T(MPen('Commercial lawyer reviewing supplier contracts','Summarize the attached supply agreement for the procurement manager, focusing on risk','- Attached: supply agreement (PDF)\n- Our side: buyer; governing law Egypt\n- Watch: payment terms, penalties, liability cap, termination, auto-renewal','Procurement decides this week whether to sign or renegotiate','- Every clause cited by number\n- Unusual or one-sided terms flagged\n- Nothing presented as legal advice; open questions listed','Table: clause, what it says, risk (high/medium/low), suggested change.'),MPar('محامي تجاري بيراجع عقود الموردين','لخّص عقد التوريد المرفق لمدير المشتريات مع التركيز على المخاطر','- مرفق: عقد التوريد (PDF)\n- طرفنا: المشتري؛ القانون الحاكم مصري\n- ركّز على: شروط الدفع، الغرامات، سقف المسؤولية، الإنهاء، التجديد التلقائي','المشتريات هتقرر الأسبوع ده نوقّع ولا نعيد التفاوض','- كل بند بيتذكر برقمه\n- البنود الغريبة أو اللي في صالح طرف واحد متعلّمة\n- مفيش حاجة متقدمة كرأي قانوني نهائي؛ الأسئلة المفتوحة متسجلة','جدول: البند، بيقول إيه، الخطر (عالي/متوسط/قليل)، التعديل المقترح.'))},
{w:T('As CFO, build next year\'s budget. Make it good.','بصفتك المدير المالي، اعمل موازنة السنة الجاية. اعملها كويس.'),miss:['context','numbers','stop','output'],
 m:T(MPen('CFO of a mid-size manufacturing company','Build the 2027 operating budget draft for the executive committee','- Attached: 2026 actuals to September, headcount list, price list\n- Assumptions: volume +8%, EGP/USD 52, wage increase 15%\n- Capex ceiling EGP 30M','The committee needs a first draft to challenge before November','- Assumptions listed and adjustable\n- P&L, cash flow and headcount tie together\n- Base, upside and downside cases','Excel-ready tables by month + one-page memo of key assumptions and risks.'),MPar('مدير مالي لشركة تصنيع متوسطة','اعمل مسودة موازنة التشغيل لسنة 2027 للجنة التنفيذية','- مرفق: فعلي 2026 لحد سبتمبر، قائمة الموظفين، قائمة الأسعار\n- الافتراضات: الكميات +8%، الدولار 52 جنيه، زيادة أجور 15%\n- سقف الاستثمارات 30 مليون جنيه','اللجنة محتاجة مسودة أولى تناقشها قبل نوفمبر','- الافتراضات متسجلة وقابلة للتعديل\n- قائمة الدخل والتدفق النقدي والعمالة مترابطين\n- سيناريو أساسي ومتفائل ومتشائم','جداول شهرية جاهزة لـ Excel + مذكرة صفحة بأهم الافتراضات والمخاطر.'))}];
if(!ST.rx)ST.rx={};let RXI=0,RXS={pick:[],checked:false,txt:'',show:false};
const RX_TARGET=70;
const rxSkeleton=w=>`<role>[who should answer — expertise + market]</role>\n<task>${w}</task>\n<context>\n- [facts, files, data]\n- [period, currency, limits]\n</context>\n<reasoning>[the decision this supports]</reasoning>\n<stop_when>\n- [what “done” looks like]\n</stop_when>\n<output_format>\n[format, language, length]\n</output_format>`;
function vRescue(){crumb(L(UX10.rescue));const ar=LANG==='ar';const r=RX[RXI];const done=Object.keys(ST.rx).length;const sc=pkScore(RXS.txt);
let h=`<h1>🛟 ${L(UX10.rescue)}</h1><p class="lede">${ar?'كل جولة فيها برومبت ضعيف. حدّد اللي ناقصه، وبعدين أعد كتابته لحد ما درجة الاستوديو توصل '+RX_TARGET+' أو أكتر.':'Each round shows a weak prompt. Spot what is missing, then rewrite it until the studio score reaches '+RX_TARGET+' or more.'}</p>`;
h+=`<div class="chips">${RX.map((x,i)=>`<button class="chip ${i===RXI?'on':''}" data-rxgo="${i}">${ar?'جولة':'Round'} ${i+1}${ST.rx[i]?` · ✓ ${ST.rx[i]}`:''}</button>`).join('')}</div><p class="note">${done}/${RX.length} ${ar?'جولات اتنقذت':'rounds rescued'}</p>`;
h+=`<div class="rxweak"><div class="k">${ar?'البرومبت الضعيف':'Weak prompt'} · ${ar?'الدرجة':'score'} ${pkBadge(pkScore(L(r.w)))}</div><p dir="auto">“${esc(L(r.w))}”</p></div>`;
h+=`<h2>1 · ${ar?'إيه اللي ناقص؟':'What is missing?'}</h2><div class="rxissues">${RX_ISSUES.map(([k,lab])=>{let cls='';if(RXS.checked){const miss=r.miss.includes(k),pk=RXS.pick.includes(k);cls=miss&&pk?'right':miss?'missed':pk?'wrong':''}return `<label class="opt ${cls}"><input type="checkbox" data-rxi="${k}" ${RXS.pick.includes(k)?'checked':''} ${RXS.checked?'disabled':''}> ${L(lab)}</label>`}).join('')}</div>`;
if(!RXS.checked)h+=`<button class="dlbtn" data-rx="check">${ar?'شوف الإجابة':'Check'}</button>`;
else{const hit=r.miss.filter(k=>RXS.pick.includes(k)).length,wrong=RXS.pick.filter(k=>!r.miss.includes(k)).length;h+=`<p class="note">${ar?`لقيت ${hit} من ${r.miss.length}`:`You found ${hit} of ${r.miss.length}`}${wrong?(ar?` · ${wrong} اختيار زيادة`:` · ${wrong} extra pick${wrong>1?'s':''}`):''}</p>`;
h+=`<h2>2 · ${ar?'أعد كتابته':'Rewrite it'}</h2><div class="rxrow"><textarea class="search" id="rxtxt" rows="12" dir="auto" placeholder="${ar?'اكتب البرومبت المحسّن هنا…':'Write the improved prompt here…'}">${esc(RXS.txt)}</textarea><div class="rxscore"><div id="rxring">${ring(sc)}</div><div class="k">${ar?'المستهدف':'Target'} ${RX_TARGET}</div><div id="rxpass">${sc>=RX_TARGET?`<b class="ok">✓ ${ar?'اتنقذ!':'Rescued!'}</b>`:''}</div></div></div>
<div class="row-btns"><button class="tbtn" data-rx="skel">${ar?'حط هيكل البلوكات الستة':'Insert the six-block skeleton'}</button><button class="btn-gold" data-rx="submit">✓ ${ar?'سلّم':'Submit'}</button><button class="tbtn" data-rx="show">${ar?'شوف الإجابة النموذجية':'Show model answer'}</button>${RXI<RX.length-1?`<button class="tbtn" data-rxgo="${RXI+1}">${ar?'الجولة الجاية':'Next round'} →</button>`:''}</div><p class="note" id="rxnote"></p>`;
if(RXS.show)h+=promptBox({t:T('Model answer','الإجابة النموذجية'),p:r.m},`${ar?'الدرجة':'Score'} ${pkScore(L(r.m))}`)}
return h}
function rxReset(i){RXI=i;RXS={pick:[],checked:false,txt:'',show:false}}

// ---------- 5. EXPLAIN LIKE MY MANAGER ----------
const ELM={};let elmBusy=false;
async function elmRun(uid){const ar=LANG==='ar';const box=document.getElementById('elmbox');const key=uid+':'+LANG;
const u=DAYS.flatMap(d=>d.units).find(x=>x.id===uid);if(!u||!box)return;
const sample=await tutorSample();if(!sample){box.hidden=false;box.innerHTML=`<p>${ar?'الميزة دي بتشتغل لما المنصة تتفتح جوه Claude (claude.ai).':'This works when the platform is opened inside Claude (claude.ai).'}</p>`;return}
elmBusy=true;box.hidden=false;box.innerHTML=`<p class="k">${ar?'Claude بيكتب…':'Claude is writing…'}</p>`;
const src=strip(L(u.body)).slice(0,3500);
const ask=`Rewrite this lesson from a Claude training course as a briefing for a busy senior manager in a finance or business team in Egypt or the Gulf. Write in ${ar?'Egyptian Arabic, keeping product and technical terms in English':'plain English'}. Use exactly these five short labelled lines: ${ar?'"إيه ده"، "القيمة للبيزنس"، "المخاطر والضوابط"، "المجهود والتكلفة"، "القرار المطلوب منك"':'"What it is", "Business value", "Risks & controls", "Effort & cost", "Decision you need to make"'}. Under 130 words in total. No jargon without a one-word explanation. Only use facts from the lesson; if the lesson doesn't say, write that it is not covered.\n\nLesson title: ${L(u.t)}\nManager note: ${CEO[uid]?L(CEO[uid]):'-'}\nLesson text:\n${src}`;
try{const {text}=await sample(ask,{modelTier:'quick',onText:({text})=>{const b=document.getElementById('elmbox');if(b)b.innerHTML=fmtMD(text)}});ELM[key]=text;const b=document.getElementById('elmbox');if(b)b.innerHTML=fmtMD(text)+elmTools(uid)}
catch(e){const b=document.getElementById('elmbox');if(b)b.innerHTML=`<p>${e&&e.code==='not_granted'?(ar?'محتاج توافق إن المنصة تستخدم Claude.':'Allow the platform to use Claude to get the briefing.'):e&&e.code==='rate_limited'?(ar?'طلبات كتير — جرّب بعد شوية.':'Too many requests — try again in a moment.'):(ar?'مقدرتش أجهّز الملخص. جرّب تاني.':'Could not prepare the briefing. Try again.')}</p>`}
elmBusy=false}
const elmTools=uid=>{const i=PSTORE.push(ELM[uid+':'+LANG]||'')-1;return `<div class="row-btns"><button class="copy" data-i="${i}">${L(UI.copy)}</button><button class="tbtn" data-elm="${uid}" data-elmfresh="1">↻ ${LANG==='ar'?'اكتبها تاني':'Rewrite'}</button></div>`};
{const _vDay=vDay;vDay=function(n,uid){let h=_vDay(n,uid);if(!uid||PRINT)return h;const d=DAYS.find(x=>x.n==n);const u=d&&d.units.find(x=>x.id==uid);if(!u)return h;
const c=ELM[u.id+':'+LANG];h=h.replace(/(<button class="tbtn[^"]*" data-ceo="1">[^<]*<\/button>)/,`$1<button class="tbtn" data-elm="${u.id}">🗣 ${L(UX10.elm)}</button>`);
return h.replace('<div class="tabs">',`<div class="elmbox" id="elmbox" aria-live="polite" ${c?'':'hidden'}>${c?fmtMD(c)+elmTools(u.id):''}</div><div class="tabs">`)}}

// ---------- 9. TEST A WHOLE PACK WITH CLAUDE ----------
let PT={rows:[],busy:false,ds:'auto',ctl:null};const PT_MAX=8;
function ptSection(){const ar=LANG==='ar';const n=Math.min(ST.basket.length,PT_MAX);
let h=`<h2>🧪 ${ar?'اختبر الحزمة مع Claude':'Test the pack with Claude'}</h2><div class="abpane"><p>${ar?`Claude بيشغّل كل برومبت في السلة على بيانات تجريبية وبيقيّم النتيجة مقابل شروط التوقف. أول ${PT_MAX} برومبتات بس، وكل برومبت بيستخدم من رصيد Claude بتاعك.`:`Claude runs each prompt in the basket on sample data and grades the result against its stop conditions. First ${PT_MAX} prompts only; each one uses your own Claude usage.`}</p>
<div class="pkgrid3"><label class="pbf"><b>${ar?'البيانات التجريبية':'Sample data'}</b><select id="ptds"><option value="auto" ${PT.ds==='auto'?'selected':''}>${ar?'تلقائي (بيانات الحالة لو موجودة)':'Automatic (case data when available)'}</option><option value="none" ${PT.ds==='none'?'selected':''}>${ar?'من غير بيانات':'No data'}</option>${Object.keys(DATA).map(k=>`<option value="${k}" ${PT.ds===k?'selected':''}>${esc(L(DATA[k]))}</option>`).join('')}</select></label></div>
<div class="row-btns">${PT.busy?`<button class="tbtn" data-pt="stop">■ ${ar?'وقّف':'Stop'}</button>`:`<button class="btn-gold" data-pt="run" ${n?'':'disabled'}>▶ ${ar?`اختبر ${n} برومبت`:`Test ${n} prompt${n===1?'':'s'}`}</button>`}${PT.rows.length&&!PT.busy?`<button class="tbtn" data-pt="md">⤓ ${ar?'تقرير .md':'Report .md'}</button>`:''}</div>`;
if(PT.rows.length){const g=PT.rows.filter(r=>r.res);const avg=g.length?Math.round(g.reduce((a,r)=>a+(+r.res.score||0),0)/g.length):0;
h+=`<p class="note">${g.length}/${PT.rows.length} ${ar?'اتختبروا':'tested'}${g.length?` · ${ar?'متوسط درجة Claude':'average Claude score'} ${pkBadge(avg)}`:''}</p><div class="tablewrap"><table class="ptable"><tr><th>${ar?'البرومبت':'Prompt'}</th><th>${ar?'الاستوديو':'Studio'}</th><th>${ar?'Claude':'Claude'}</th><th>${ar?'اللي اشتغل':'Worked'}</th><th>${ar?'المشاكل':'Issues'}</th><th>${ar?'التحسين المقترح':'Suggested fix'}</th></tr>`+PT.rows.map(r=>`<tr><td dir="auto"><b>${esc(r.t)}</b><div class="k">${esc(r.ds)}</div></td><td>${pkBadge(r.studio)}</td><td>${r.res?`${pkBadge(+r.res.score||0)} <b>${esc(String(r.res.grade||''))}</b>`:r.err?`<span class="k">${esc(r.err)}</span>`:'…'}</td><td dir="auto">${r.res?esc((r.res.strengths||[]).join(' · ')):''}</td><td dir="auto">${r.res?esc((r.res.issues||[]).join(' · ')):''}</td><td dir="auto">${r.res?esc(r.res.fix||''):''}</td></tr>`).join('')+`</table></div>`}
return h+`</div>`}
function ptData(item){if(PT.ds==='none')return['',''];let k=PT.ds;if(k==='auto'){const lab=LAB.find(c=>pkNorm(c.p.en)===pkNorm(pkTxt(item.p,'en'))||pkNorm(c.p.ar)===pkNorm(pkTxt(item.p,'ar')));k=lab&&(lab.data||[])[0]}if(!k||!DATA[k])return['',''];return [k,DATA[k].csv.slice(0,4000)]}
async function ptRun(){const ar=LANG==='ar';const sample=await tutorSample();if(!sample){pkNote(ar?'الاختبار بيشتغل لما المنصة تتفتح جوه Claude (claude.ai).':'Testing works when the platform is opened inside Claude (claude.ai).');return}
const items=ST.basket.slice(0,PT_MAX);PT.rows=items.map(b=>{const p=pkTxt(b.p,LANG);return {t:pkTxt(b.t,LANG),p,studio:pkScore(p),ds:'',res:null,err:''}});PT.busy=true;PT.ctl=new AbortController();render();
for(let i=0;i<items.length&&PT.busy;i++){const row=PT.rows[i];const [k,csv]=ptData(items[i]);row.ds=k?L(DATA[k]):(ar?'من غير بيانات':'no data');
const ask=`You are testing a prompt from a prompt library. First, silently carry out the PROMPT below as the assistant would, using the SAMPLE DATA if given (if the prompt needs files that are not provided, use reasonable placeholders and note it). Then grade how well the prompt led to a useful, correct, complete answer, judged against its own stop conditions and output format. Reply with JSON only: {"score": integer 0-100, "grade": "A"|"B"|"C"|"D"|"F", "strengths": [up to 2 short strings], "issues": [up to 3 short strings], "fix": "one sentence on how to improve the prompt"}. Write the strings in ${ar?'Egyptian Arabic':'English'}.\n\nPROMPT:\n${row.p.slice(0,6000)}\n\nSAMPLE DATA${k?' ('+k+'.csv)':''}:\n${csv||'(none)'}`;
try{row.res=await sample.json(ask,{modelTier:'default',signal:PT.ctl.signal})}catch(e){if(e&&e.code==='cancelled')break;row.err=e&&e.code==='rate_limited'?(ar?'طلبات كتير':'rate limited'):e&&e.code==='not_granted'?(ar?'محتاج موافقة':'permission needed'):(ar?'فشل':'failed');if(e&&(e.code==='not_granted'||e.code==='rate_limited'))break}
render()}
PT.busy=false;render()}
function ptReport(){let m=`# Pack test report — ${PKM.name}\n\nTested ${new Date().toISOString().slice(0,10)} · ${PT.rows.length} prompts\n\n| Prompt | Data | Studio score | Claude score | Grade |\n|---|---|---|---|---|\n`;
PT.rows.forEach(r=>m+=`| ${r.t.replace(/\|/g,'/')} | ${r.ds} | ${r.studio} | ${r.res?r.res.score:'-'} | ${r.res?r.res.grade:r.err||'-'} |\n`);
PT.rows.forEach(r=>{if(r.res)m+=`\n## ${r.t}\n\n- Strengths: ${(r.res.strengths||[]).join('; ')}\n- Issues: ${(r.res.issues||[]).join('; ')}\n- Suggested fix: ${r.res.fix||''}\n`});return m}

// ---------- 10. PACK -> SKILL FOLDER ----------
async function pkSkillZip(pk,name){await ensureZip();const z=new JSZip();const id=slug(name)||'prompt-pack-skill';const root=z.folder(id);
const files=pk.items.map((it,k)=>{const f=`prompts/${String(k+1).padStart(2,'0')}-${slug(it.title)||'prompt'}.md`;root.file(f,`# ${it.title}${it.title_ar?` — ${it.title_ar}`:''}\n\n`+(it.prompt_ar?`## English\n\n${it.prompt_en}\n\n## العربية\n\n${it.prompt_ar}\n`:`${it.prompt}\n`));(it.data||[]).forEach(d=>{if(DATA[d])root.file(`data/${d}.csv`,BOM+DATA[d].csv)});return [it.title,f]});
const desc=(pk.description||`Reusable prompts from the "${pk.name}" pack.`).replace(/\s+/g,' ').replace(/\.?$/,'.').slice(0,700)+` Use when the user asks for: ${pk.items.slice(0,6).map(i=>i.title).join('; ')}.`.slice(0,300);
root.file('SKILL.md',`---\nname: ${id}\ndescription: ${JSON.stringify(desc.slice(0,1000))}\n---\n\n# ${pk.name}\n\n${pk.description||''}\n\n## How to use this skill\n\n1. Match the user's request to the closest prompt in the index below.\n2. Open that file and follow its six blocks (role, task, context, reasoning, stop conditions, output format).\n3. Fill every [bracket] from the user's message or files; ask up to 3 clarifying questions when something is missing.\n4. Check the stop conditions before you answer, and label assumptions.\n5. If sample data is listed in \`data/\`, use it only when the user asks for a demo.\n\n## Prompt index\n\n${files.map(([t,f])=>`- [${t}](${f})`).join('\n')}\n\n---\nBuilt with Claude Mastery · ${LINKEDIN}\n`);
root.file('README.md',`# ${pk.name} — Skill folder\n\nThis folder is a Claude Skill: \`SKILL.md\` (name + description + instructions) and the prompts it uses.\n\nTo use it, upload this folder as a ZIP where your Claude plan lets you add custom Skills — see the Skills lesson in Module 4 of Claude Mastery. Review every prompt before sharing the Skill with your team.\n`);
await saveFile(id+'-skill.zip',await z.generateAsync({type:'blob'}))}
{const _pe=pkExport;pkExport=async function(src,btn,nameOverride){if(PKM.fmt!=='skill')return _pe(src,btn,nameOverride);const ar=LANG==='ar';const items=pkItems(src);if(!items.length){pkNote(ar?'مفيش برومبتات في المصدر ده.':'Nothing to export from this source.');return}
const meta=Object.assign({},PKM,{lang:PKM.lang==='bi'?'bi':'en'});if(nameOverride)meta.name=nameOverride;const old=btn&&btn.textContent;if(btn){btn.disabled=true;btn.textContent=ar?'جاري…':'Working…'}
try{const pk=pkPayload(items,meta);const nm=slug(meta.name)?meta.name:(nameOverride?STARTER.find(s=>L(s[2])===nameOverride):null)?.[2]?.en||meta.name;await pkSkillZip(pk,nm);pkNote(ar?`اتعمل فولدر Skill فيه ${pk.items.length} برومبت.`:`Skill folder created with ${pk.items.length} prompts.`)}catch(e){console.error(e);pkNote(ar?'حصلت مشكلة في التصدير.':'Export failed.')}
if(btn){btn.disabled=false;btn.textContent=old}}}
{const _vp=vPacks;vPacks=function(){let h=_vp();const ar=LANG==='ar';
h=h.replace(`<option value="pdf" ${PKM.fmt==='pdf'?'selected':''}>PDF</option>`,`<option value="pdf" ${PKM.fmt==='pdf'?'selected':''}>PDF</option><option value="skill" ${PKM.fmt==='skill'?'selected':''}>${ar?'فولدر Skill (.zip)':'Skill folder (.zip)'}</option>`);
h=h.replace(/⤓ SKILL</g,'⤓ Skill<');
const anchor=`<h2>🚀 `;const i=h.indexOf(anchor);return i>0?h.slice(0,i)+ptSection()+h.slice(i):h+ptSection()}}

// ---------- 20. OFFLINE COURSE PACK ----------
async function offlinePack(btn){const ar=LANG==='ar';const old=btn.textContent;btn.disabled=true;btn.textContent=ar?'جاري التجهيز…':'Preparing…';
try{await ensureZip();const z=new JSZip();const css=document.querySelector('style').textContent;const keepL=LANG;const page=(lang,title,body,back)=>`<!doctype html><html lang="${lang}" dir="${lang==='ar'?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><style>${css} html,body{height:auto;overflow:visible}.exdoc{max-width:900px;margin:0 auto;padding:24px}.offnav{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;max-width:900px;margin:0 auto;padding:12px 24px;font-family:'Readex Pro',Arial,sans-serif}</style></head><body>${back||''}${body}${back||''}</body></html>`;
const idx={en:[],ar:[]};
for(const lang of ['en','ar']){LANG=lang;for(const d of DAYS){const prev=d.n>1?`<a href="module-${d.n-1}.html">← ${lang==='ar'?'اللي قبله':'Previous'}</a>`:'<span></span>';const next=d.n<DAYS.length?`<a href="module-${d.n+1}.html">${lang==='ar'?'اللي بعده':'Next'} →</a>`:'<span></span>';
const nav=`<nav class="offnav">${prev}<a href="../index.html">${lang==='ar'?'الفهرس':'Contents'}</a>${next}</nav>`;z.file(`course/${lang}/module-${d.n}.html`,page(lang,`${L(UI.day)} ${d.n} · ${L(d.t)}`,moduleHTML(d.n),nav));idx[lang].push(`<li><a href="${lang}/module-${d.n}.html">${d.n} · ${esc(L(d.t))}</a> <small>(${d.units.length} ${lang==='ar'?'دروس':'lessons'})</small></li>`)}}
LANG=keepL;
z.file('course/index.html',page('en','Claude Mastery — offline course',`<div class="exdoc"><div class="exhead"><div><div class="sig">Dr. Sara Salem · د. سارة سالم</div><h1>Claude Mastery — offline course</h1><p>Open any module below. Everything works without internet except external links.</p></div><div class="qr" style="width:90px">${QR_PLATFORM}</div></div><div class="twocol"><div><h2>English</h2><ol>${idx.en.join('')}</ol></div><div dir="rtl"><h2>العربية</h2><ol>${idx.ar.join('')}</ol></div></div><h2>Also in this pack</h2><ul><li>pdf/ — curriculum and master prompt books</li><li>prompts/ — full prompt library (Markdown + CSV) and six starter packs (JSON + Skill folders)</li><li>data/ — sample datasets for every lab case</li><li>community/ — Anthropic community and official links</li></ul></div>`));
z.file('pdf/Claude-Mastery-Curriculum-AR.pdf',b64blob(PDF_AR));if(typeof PDF_EN!=='undefined')z.file('pdf/Claude-Mastery-Curriculum-EN.pdf',b64blob(PDF_EN));z.file('pdf/Master-Prompt-Book-AR.pdf',b64blob(PDF_MP_AR));if(typeof PDF_MP_EN!=='undefined')z.file('pdf/Master-Prompt-Book-EN.pdf',b64blob(PDF_MP_EN));
z.file('prompts/Prompt-Library.md',mdPrompts());z.file('prompts/Prompt-Library.csv',csvPrompts());z.file('prompts/Use-Cases.md',mdCases());z.file('prompts/Glossary.csv',csvGloss());
const meta={name:'',desc:'',tags:'',version:'1.0',lang:'bi'};for(const s of STARTER){const pk=pkPayload(pkStarterItems(s[0]),Object.assign({},meta,{name:s[2].en,desc:`Starter pack: ${s[2].en} prompts from Claude Mastery.`}));z.file(`prompts/starter-packs/${slug(s[2].en)}.json`,JSON.stringify(pk,null,1))}
Object.keys(DATA).forEach(k=>z.file('data/'+k+'.csv',BOM+DATA[k].csv));
z.file('community/Community-and-sources.md','# Anthropic community & official sources\n'+COMMUNITY.concat(REFS).map(g=>`\n## ${g.g.en} / ${g.g.ar}\n\n`+g.items.map(i=>`- [${i[0]}](${i[1]})${i[2]?' — '+i[2].en:''}`).join('\n')).join('\n'));
z.file('README.txt','Claude Mastery — offline course pack\n\nOpen course/index.html in any browser.\n\nDr. Sara Salem · '+LINKEDIN+'\n');
const blob=await z.generateAsync({type:'blob'});await saveFile('Claude-Mastery-Offline-Course.zip',blob);btn.textContent='✓'}
catch(e){console.error(e);btn.textContent=ar?'حصلت مشكلة':'Failed'}btn.disabled=false;setTimeout(()=>btn.textContent=old,2500)}
{const _vx=vExport;vExport=function(){const ar=LANG==='ar';return `<div class="commbanner"><div><b>💼 ${L(UX10.offline)}</b><span>${ar?'ZIP واحد فيه كل الموديولات بالعربي والإنجليزي كصفحات تتفتح من غير نت، والـ PDFs، ومكتبة البرومبتات، والحزم الجاهزة، والبيانات التجريبية.':'One ZIP with every module in English and Arabic as pages that open without internet, plus the PDFs, prompt library, starter packs and sample data.'}</span></div><button class="btn-gold" data-offline="1">⤓ ${ar?'نزّل الحزمة':'Download the pack'}</button></div>`+_vx()}}

// ---------- 12. SHOWCASE WALL (shared, db) ----------
let WALL={db:null,user:null,me:null,owner:false,docs:[],names:{},state:'init',unsub:null,can:null,err:''};
let WF2=Object.assign({title:'',what:'',features:'',result:'',link:'',prompt:'',ok:false},ST.wf2||{});
const WALL_MAX=10;
async function wallInit(){if(WALL.state!=='init')return;WALL.state='loading';
try{const use=window.claude&&window.claude.use;WALL.db=use?await use('db'):null;WALL.user=use?await use('user'):null}catch(e){WALL.db=null}
if(!WALL.db){WALL.state='off';if(location.hash.startsWith('#showcase'))render();return}
try{WALL.me=WALL.user?await WALL.user.id():null;WALL.owner=WALL.user?await WALL.user.isOwner():false;WALL.can=WALL.user?await WALL.user.can('data.write'):null}catch(e){}
WALL.unsub=WALL.db.collection('wall').onSnapshot(async snap=>{WALL.docs=snap.docs.filter(d=>d.exists).map(d=>({id:d.id,...d.data()}));const first=WALL.state!=='ready';WALL.state='ready';
const ids=WALL.docs.map(d=>d.id).filter(id=>!(id in WALL.names));if(ids.length&&WALL.user){try{const ps=await WALL.user.profiles(ids);ids.forEach(id=>WALL.names[id]=(ps[id]&&ps[id].name)||'')}catch(e){}}
if(location.hash.startsWith('#showcase')){if(first)render();else wallPaint()}},e=>{WALL.state='error';WALL.err=e&&e.code||'';if(location.hash.startsWith('#showcase'))render()})}
function wallPosts(){const all=[];WALL.docs.forEach(d=>(d.posts||[]).forEach(p=>all.push(Object.assign({uid:d.id},p))));
const likes={};WALL.docs.forEach(d=>(d.likes||[]).forEach(k=>likes[k]=(likes[k]||0)+1));all.forEach(p=>p.likes=likes[p.uid+':'+p.id]||0);return all.sort((a,b)=>String(b.at).localeCompare(String(a.at)))}
const myDoc=()=>WALL.docs.find(d=>d.id===WALL.me)||{posts:[],likes:[]};
async function wallSave(next){const ref=WALL.db.doc('wall/'+WALL.me);await ref.set({posts:next.posts||[],likes:next.likes||[]})}
function wallCards(){const ar=LANG==='ar';const posts=wallPosts();const mine=myDoc();
if(!posts.length)return `<div class="empty">${ar?'لسه مفيش أعمال على الحائط. كن أول واحد يشارك!':'No work on the wall yet. Be the first to share!'}</div>`;
return `<div class="wallgrid">`+posts.map(p=>{const key=p.uid+':'+p.id;const liked=(mine.likes||[]).includes(key);const nm=p.uid===WALL.me?(ar?'إنت':'You'):(WALL.names[p.uid]||(ar?'متدرب':'A learner'));const pi=p.prompt?PSTORE.push(p.prompt)-1:-1;
return `<article class="wallcard"><div class="k">${esc(nm)} · ${esc(String(p.at||'').slice(0,10))}</div><h3 dir="auto">${esc(p.title)}</h3><p dir="auto">${esc(p.what)}</p>${p.result?`<p class="wallres" dir="auto">📈 ${esc(p.result)}</p>`:''}${p.features?`<div class="chips">${String(p.features).split(',').map(f=>f.trim()).filter(Boolean).slice(0,6).map(f=>`<span class="chip">${esc(f)}</span>`).join('')}</div>`:''}
${p.prompt?`<details><summary>${ar?'البرومبت':'Prompt'}</summary><pre class="testout" dir="auto">${esc(p.prompt)}</pre><button class="copy" data-i="${pi}">${L(UI.copy)}</button></details>`:''}
<div class="row-btns">${/^https:\/\//.test(p.link||'')?`<a class="tbtn" href="${esc(p.link)}" target="_blank" rel="noopener">${ar?'افتح':'Open'} ↗</a>`:''}<button class="tbtn ${liked?'donebtn':''}" data-wlike="${esc(key)}" ${WALL.me?'':'disabled'}>❤ ${p.likes}</button>${p.uid===WALL.me||WALL.owner?`<button class="tbtn" data-wdel="${esc(key)}">${p.uid===WALL.me?(ar?'احذف':'Delete'):(ar?'احذف (المالك)':'Remove (owner)')}</button>`:''}</div></article>`}).join('')+`</div>`}
function vShowcase(){crumb(L(UX10.wall));const ar=LANG==='ar';wallInit();
let h=`<h1>🖼 ${L(UX10.wall)}</h1><p class="lede">${ar?'اعرض اللي بنيته بـ Claude لباقي المتدربين، وشوف شغلهم واستلهم منه. الحائط مشترك بين كل اللي عندهم لينك المنصة.':'Show what you built with Claude to the other learners, and get ideas from theirs. The wall is shared by everyone who can open the platform.'}</p>`;
if(WALL.state==='off')return h+`<div class="empty">${ar?'الحائط بيشتغل لما المنصة تتفتح جوه Claude وإنت مسجّل دخول.':'The wall works when the platform is opened inside Claude while you are signed in.'}</div>`;
if(WALL.state==='error')return h+`<div class="empty">${ar?'مقدرتش أحمّل الحائط. افتح الصفحة تاني.':'Could not load the wall. Reopen the page.'}</div>`;
const mine=myDoc();const canPost=WALL.me&&WALL.can!==false&&(mine.posts||[]).length<WALL_MAX;
h+=`<div class="twocol"><div class="abpane"><h3>＋ ${ar?'شارك عمل':'Share a build'}</h3>`;
if(!WALL.me)h+=`<p class="note">${ar?'سجّل دخول على claude.ai علشان تقدر تنشر.':'Sign in on claude.ai to post.'}</p>`;
else if(WALL.can===false)h+=`<p class="note">${ar?'صلاحيتك على المنصة مشاهدة بس — تقدر تشوف الحائط من غير ما تنشر.':'You have view-only access — you can browse the wall but not post.'}</p>`;
else h+=`<label class="pbf"><b>${ar?'العنوان':'Title'} *</b><input class="search" data-wf2="title" maxlength="90" value="${esc(WF2.title)}" placeholder="${ar?'مثلاً: Skill لفحص مستندات الاعتماد':'e.g. A Skill that checks LC documents'}"></label>
<label class="pbf"><b>${ar?'عمل إيه وبيحل أنهي مشكلة؟':'What it does and the problem it solves'} *</b><textarea class="search" rows="3" maxlength="500" data-wf2="what" dir="auto">${esc(WF2.what)}</textarea></label>
<div class="pkgrid3"><label class="pbf"><b>${ar?'مميزات Claude':'Claude features'}</b><input class="search" data-wf2="features" maxlength="120" value="${esc(WF2.features)}" placeholder="Projects, Skills, Cowork"></label><label class="pbf"><b>${ar?'النتيجة':'Result'}</b><input class="search" data-wf2="result" maxlength="140" value="${esc(WF2.result)}" placeholder="${ar?'وفّر 6 ساعات في الأسبوع':'Saved 6 hours a week'}"></label><label class="pbf"><b>${ar?'لينك (https)':'Link (https)'}</b><input class="search" data-wf2="link" maxlength="300" value="${esc(WF2.link)}" placeholder="https://claude.ai/artifact/…"></label></div>
<label class="pbf"><b>${ar?'البرومبت (اختياري)':'Prompt (optional)'}</b><textarea class="search" rows="3" maxlength="4000" data-wf2="prompt" dir="auto">${esc(WF2.prompt)}</textarea></label>
<label class="opt"><input type="checkbox" data-wf2ok="1" ${WF2.ok?'checked':''}> ${ar?'متأكد إن مفيش بيانات عملاء أو أرقام سرية':'I confirm there is no client data or confidential numbers'}</label>
<button class="btn-gold" data-wpost="1" ${canPost?'':'disabled'}>${ar?'انشر على الحائط':'Post to the wall'}</button><p class="note" id="wnote">${ar?`كل شخص يقدر ينشر لحد ${WALL_MAX} أعمال. الكل يقدر يشوف المنشور.`:`Up to ${WALL_MAX} posts per person. Everyone with access can see what you post.`}</p>`;
h+=`</div><div class="abpane"><h3>${ar?'إزاي تكتب منشور كويس':'How to write a good post'}</h3><ol class="steps">${(ar?['عنوان بيقول القيمة، مش اسم الأداة.','المشكلة والنتيجة برقم.','اذكر مميزات Claude اللي استخدمتها.','شارك البرومبت لو مفيهوش بيانات سرية.']:['A title that says the value, not the tool.','The problem and a result with a number.','Name the Claude features you used.','Share the prompt if it has nothing confidential.']).map(s=>`<li>${s}</li>`).join('')}</ol><button class="tbtn" data-go="community">🤝 ${L(UX9.hub)}</button></div></div>`;
h+=`<h2>${ar?'على الحائط':'On the wall'} <span class="k" id="wcount">(${wallPosts().length})</span></h2><div id="wallbody">${WALL.state==='ready'?wallCards():`<div class="empty">${ar?'بيحمّل…':'Loading…'}</div>`}</div>`;
return h}
function wallPaint(){const b=document.getElementById('wallbody');if(!b){render();return}b.innerHTML=wallCards();const c=document.getElementById('wcount');if(c)c.textContent=`(${wallPosts().length})`}
async function wallPost(btn){const ar=LANG==='ar';const n=document.getElementById('wnote');const say=t=>{if(n)n.textContent=t};
if(!WF2.title.trim()||!WF2.what.trim()){say(ar?'اكتب العنوان والوصف.':'Add a title and a description.');return}
if(!WF2.ok){say(ar?'علّم على تأكيد إن مفيش بيانات سرية.':'Tick the confirmation that there is no confidential data.');return}
if(WF2.link&&!/^https:\/\//.test(WF2.link.trim())){say(ar?'اللينك لازم يبدأ بـ https://':'The link must start with https://');return}
const mine=myDoc();const post={id:Date.now().toString(36),at:new Date().toISOString(),title:WF2.title.trim().slice(0,90),what:WF2.what.trim().slice(0,500),features:WF2.features.trim().slice(0,120),result:WF2.result.trim().slice(0,140),link:WF2.link.trim().slice(0,300),prompt:WF2.prompt.trim().slice(0,4000)};
btn.disabled=true;try{await wallSave({posts:[post,...(mine.posts||[])].slice(0,WALL_MAX),likes:mine.likes||[]});WF2={title:'',what:'',features:'',result:'',link:'',prompt:'',ok:false};ST.wf2=WF2;saveST();addXP(15);render()}
catch(e){btn.disabled=false;say(e&&e.code==='invalid_argument'?(ar?'مش مسموحلك تنشر على الحائط ده.':'You do not have permission to post on this wall.'):e&&e.code==='quota_exceeded'?(ar?'الحائط مليان — اطلب من المالك يمسح منشورات قديمة.':'The wall is full — ask the owner to remove old posts.'):(ar?'مقدرتش أنشر. جرّب تاني.':'Could not post. Try again.'))}}
async function wallDel(key){const [uid,pid]=key.split(':');const d=WALL.docs.find(x=>x.id===uid);if(!d)return;const posts=(d.posts||[]).filter(p=>p.id!==pid);
try{await WALL.db.doc('wall/'+uid).set({posts,likes:d.likes||[]})}catch(e){const n=document.getElementById('wnote');if(n)n.textContent=LANG==='ar'?'مقدرتش أحذف.':'Could not delete.'}}
let wallLikeBusy=false;async function wallLike(key){if(!WALL.me||wallLikeBusy)return;wallLikeBusy=true;const mine=myDoc();const likes=(mine.likes||[]).includes(key)?mine.likes.filter(k=>k!==key):[...(mine.likes||[]),key].slice(-500);try{await wallSave({posts:mine.posts||[],likes})}catch(e){}wallLikeBusy=false}

// ---------- events ----------
document.addEventListener('click',e=>{const g=s=>e.target.closest(s);let x;
if(x=g('[data-rxgo]')){rxReset(+x.dataset.rxgo);render();return}
if(x=g('[data-rx]')){const a=x.dataset.rx;const r=RX[RXI];
if(a==='check'){RXS.checked=true;render();return}
if(a==='skel'){RXS.txt=rxSkeleton(RXS.txt.trim()&&!/<role>/.test(RXS.txt)?RXS.txt.trim():L(r.w));render();return}
if(a==='show'){RXS.show=true;render();return}
if(a==='submit'){const sc=pkScore(RXS.txt);const n=document.getElementById('rxnote');if(sc>=RX_TARGET){const first=!ST.rx[RXI];ST.rx[RXI]=Math.max(ST.rx[RXI]||0,sc);saveST();if(first)addXP(15);if(n)n.textContent=LANG==='ar'?`برافو! ${sc}/100`:`Well done! ${sc}/100`;render()}else if(n)n.textContent=LANG==='ar'?`لسه ${sc} — زوّد السياق والأرقام وشروط التوقف.`:`Still ${sc} — add context, numbers and stop conditions.`;return}}
if(x=g('[data-elm]')){const id=x.dataset.elm;if(x.dataset.elmfresh)delete ELM[id+':'+LANG];if(!elmBusy){if(ELM[id+':'+LANG]){const b=document.getElementById('elmbox');if(b){b.hidden=!b.hidden}}else elmRun(id)}return}
if(x=g('[data-pt]')){const a=x.dataset.pt;if(a==='run'&&!PT.busy)ptRun();if(a==='stop'){PT.busy=false;if(PT.ctl)PT.ctl.abort();render()}if(a==='md')saveFile('Pack-test-report.md',ptReport());return}
if(x=g('[data-offline]')){offlinePack(x);return}
if(x=g('[data-wpost]')){wallPost(x);return}
if(x=g('[data-wdel]')){wallDel(x.dataset.wdel);return}
if(x=g('[data-wlike]')){wallLike(x.dataset.wlike);return}});
document.addEventListener('input',e=>{const t=e.target;
if(t.id==='rxtxt'){RXS.txt=t.value;const sc=pkScore(t.value);const r=document.getElementById('rxring');if(r)r.innerHTML=ring(sc);const p=document.getElementById('rxpass');if(p)p.innerHTML=sc>=RX_TARGET?`<b class="ok">✓ ${LANG==='ar'?'اتنقذ!':'Rescued!'}</b>`:''}
if(t.dataset&&t.dataset.wf2){WF2[t.dataset.wf2]=t.value;ST.wf2=WF2;saveST()}});
document.addEventListener('change',e=>{const t=e.target;
if(t.dataset&&t.dataset.rxi){const k=t.dataset.rxi;RXS.pick=t.checked?[...RXS.pick,k]:RXS.pick.filter(y=>y!==k)}
if(t.id==='ptds'){PT.ds=t.value}
if(t.dataset&&t.dataset.wf2ok){WF2.ok=t.checked;ST.wf2=WF2;saveST()}});
