// ---------- Round 15: agent playground / team designer / cost estimator, automation hub tabs, Module 3 artifact & design studio, failure gallery, Module 6 build-alongs, Studio cleanup ----------
const UX21={play:T('Playground','الملعب'),team:T('Team designer','مصمم الفريق'),cost:T('Cost & time','التكلفة والوقت'),design:T('Designer','المصمم'),find:T('Automation finder','مكتشف الأتمتة'),recipes:T('Recipes','وصفات'),matrix:T('Approval matrix','مصفوفة الموافقات'),risk:T('Risk register','سجل المخاطر'),fix:T('Fix & re-enhance','صلّح وحسّن'),saved:T('My saved prompts','برومبتاتي المحفوظة'),fails:T('Failure gallery','معرض الأخطاء'),ba:T('Build-along projects','مشروعات ابني معانا'),m3:T('Artifact & design studio','استوديو الـ Artifacts والتصميم')};
const nowISO=()=>new Date().toISOString().slice(0,10);
const ntf=(id,t)=>{const e=document.getElementById(id);if(e)e.textContent=t};

// ===== Agent builder: more tabs =====
{const _ab=vAgentB;vAgentB=function(){const extra=[['play','🧪',UX21.play],['team','🕸',UX21.team],['cost','⏱',UX21.cost]];const btns=extra.map(t=>`<button class="tab ${AGTAB===t[0]?'on':''}" data-agtab="${t[0]}">${t[1]} ${L(t[2])}</button>`).join('');
if(!['play','team','cost'].includes(AGTAB))return _ab().replace(/(<div class="tabs big">[\s\S]*?)(<\/div>)/,'$1'+btns+'$2');
const keep=AGTAB;AGTAB='guide';let head;try{head=_ab()}finally{AGTAB=keep}const m=head.match(/^<h1>[\s\S]*?<\/h1><div class="tabs big">[\s\S]*?<\/div>/);const tabs=(m?m[0]:'').replace(/ on"/g,'"').replace(/(<div class="tabs big">[\s\S]*?)(<\/div>)$/,'$1'+btns+'$2');
crumb(L(UX4.agentb)+' › '+L(extra.find(x=>x[0]===AGTAB)[2]));return tabs+(AGTAB==='play'?vPlay():AGTAB==='team'?vTeam():vCost())}}

// --- 1. Agent playground: a real tool-using run with an approval gate (all sends are simulated)
let PG=Object.assign({goal:'',data:'ar_aging',appr:true,trace:[],out:'',busy:false},ST.pg||{});PG.busy=false;let PGCTL=null,PGWAIT=null;
function savePG(){const {busy,...r}=PG;r.trace=(r.trace||[]).slice(-40);ST.pg=r;saveST()}
function calcExpr(s){let i=0;s=String(s).replace(/\s+/g,'').replace(/,/g,'');const peek=()=>s[i];const num=()=>{let m=s.slice(i).match(/^\d+(\.\d+)?/);if(!m)throw new Error('number expected at '+i);i+=m[0].length;return parseFloat(m[0])};
const fac=()=>{if(peek()==='-'){i++;return -fac()}if(peek()==='('){i++;const v=add();if(s[i++]!==')')throw new Error(') expected');return v}const v=num();if(peek()==='%'){i++;return v/100}return v};
const mul=()=>{let v=fac();while(peek()==='*'||peek()==='/'){const o=s[i++];const r=fac();v=o==='*'?v*r:v/r}return v};const add=()=>{let v=mul();while(peek()==='+'||peek()==='-'){const o=s[i++];const r=mul();v=o==='+'?v+r:v-r}return v};
const v=add();if(i<s.length)throw new Error('unexpected '+s[i]);return Math.round(v*10000)/10000}
function pgTools(){const push=e=>{PG.trace.push(e);pgPaint()};return [
{name:'list_datasets',description:'Lists the sample datasets available to this agent with their columns. Returns name, title and columns.',execute(){const r=Object.keys(DATA).map(k=>({name:k,title:DATA[k].en,columns:DATA[k].csv.split('\n')[0]}));push({k:'tool',n:'list_datasets',i:'',o:r.length+' datasets'});return r}},
{name:'read_dataset',description:'Reads rows of one sample dataset as CSV text. Use the dataset name from list_datasets. Returns the header and up to max_rows rows.',inputSchema:{type:'object',properties:{name:{type:'string'},max_rows:{type:'number'}},required:['name']},execute(x){const k=String(x.name||'');if(!DATA[k])throw new Error('unknown dataset '+k);const n=Math.min(200,Math.max(1,Number(x.max_rows)||60));const rows=DATA[k].csv.split('\n');const out=rows.slice(0,n+1).join('\n');push({k:'tool',n:'read_dataset',i:k+' ('+Math.min(n,rows.length-1)+' rows)',o:(rows.length-1)+' rows in file'});return out}},
{name:'calculate',description:'Evaluates an arithmetic expression exactly (numbers, + - * / %, parentheses). Use it for every total, average, ratio or percentage. Returns the number.',inputSchema:{type:'object',properties:{expression:{type:'string'}},required:['expression']},execute(x){const r=calcExpr(x.expression);push({k:'tool',n:'calculate',i:String(x.expression).slice(0,120),o:String(r)});return r}},
{name:'save_draft',description:'Saves a draft document (memo, table, plan) for the human to review. Returns a confirmation.',inputSchema:{type:'object',properties:{title:{type:'string'},content:{type:'string'}},required:['title','content']},execute(x){push({k:'draft',n:'save_draft',i:String(x.title||'Draft'),o:String(x.content||'').slice(0,4000)});return 'Draft saved for review.'}},
{name:'send_message',description:'Sends an email or message to a person outside the team. A human must approve it first; returns approved or rejected. Only use for the final, reviewed message.',inputSchema:{type:'object',properties:{to:{type:'string'},subject:{type:'string'},body:{type:'string'}},required:['to','body']},async execute(x,ctx){const e={k:'send',n:'send_message',i:`${x.to||''} — ${x.subject||''}`,o:String(x.body||'').slice(0,2000),st:PG.appr?'wait':'auto'};push(e);
if(!PG.appr){e.st='sent';pgPaint();return 'Sent (simulated — nothing actually left the platform).'}
const ok=await new Promise(res=>{PGWAIT=res;ctx.signal.addEventListener('abort',()=>res(false))});PGWAIT=null;e.st=ok?'sent':'rejected';pgPaint();return ok?'Approved by the human and sent (simulated).':'Rejected by the human. Do not send. Revise or stop.'}}]}
function pgTrace(){const ar=LANG==='ar';return PG.trace.map((e,i)=>`<div class="pgev ${e.k}"><span class="pgn">${i+1}</span><div><b>${e.k==='plan'?'🧭':e.k==='draft'?'📝':e.k==='send'?'✉':'🔧'} ${esc(e.n)}</b>${e.i?` <span class="k">${esc(e.i)}</span>`:''}${e.o?`<div class="pgo" dir="auto">${esc(e.o).slice(0,1800)}</div>`:''}${e.k==='send'?`<div class="pgst">${e.st==='wait'?`⏸ ${ar?'مستني موافقتك':'Waiting for your approval'} <button class="btn-gold" data-pga="1">✓ ${ar?'وافق':'Approve'}</button><button class="tbtn" data-pga="0">✕ ${ar?'ارفض':'Reject'}</button>`:e.st==='sent'?'✓ '+(ar?'اتبعت (محاكاة)':'Sent (simulated)'):e.st==='rejected'?'✕ '+(ar?'اترفض':'Rejected'):''}</div>`:''}</div></div>`).join('')}
function pgPaint(){const b=document.getElementById('pgtrace');if(b){b.innerHTML=pgTrace()||`<p class="k">${LANG==='ar'?'لسه مفيش خطوات.':'No steps yet.'}</p>`;b.scrollTop=b.scrollHeight}}
function vPlay(){const ar=LANG==='ar';return `<p class="lede">${ar?'اديله هدف، وشوف الوكيل بيشتغل خطوة بخطوة: يخطط، يقرا البيانات، يحسب بأداة، يكتب مسودة — ويقف يستنى موافقتك قبل أي إرسال. كل الإرسال هنا محاكاة.':'Give the agent a goal and watch it work step by step: plan, read data, calculate with a tool, draft — and stop for your approval before anything is sent. All sending here is simulated.'}</p>
<div class="twocol"><div class="abpane"><label class="pbf"><b>${ar?'الهدف':'Goal'}</b><textarea class="search" id="pggoal" rows="4" dir="auto" placeholder="${ar?'مثلاً: رتّب العملاء المتأخرين في الدفع وجهّز رسالة متابعة لأكبر واحد':'e.g. Rank overdue customers and draft a follow-up email to the largest one'}">${esc(PG.goal)}</textarea></label>
<label class="pbf"><b>${ar?'البيانات اللي يبدأ بيها':'Starting dataset'}</b><select class="search" id="pgdata">${Object.keys(DATA).map(k=>`<option value="${k}" ${PG.data===k?'selected':''}>${esc(L(T(DATA[k].en,DATA[k].ar)))} (${k})</option>`).join('')}</select></label>
<label class="fdrun"><input type="checkbox" id="pgappr" ${PG.appr?'checked':''}> ${ar?'وقف لموافقتي قبل أي إرسال (موصى بيه)':'Pause for my approval before sending (recommended)'}</label>
<div class="row-btns"><button class="btn-gold" data-pg="run" ${PG.busy?'disabled':''}>${PG.busy?(ar?'الوكيل شغال…':'Agent running…'):'▶ '+(ar?'شغّل الوكيل':'Run the agent')}</button>${PG.busy?`<button class="tbtn" data-pg="stop">■ ${ar?'وقّف':'Stop'}</button>`:''}<button class="tbtn" data-pg="clear">${ar?'امسح':'Clear'}</button></div><p class="note" id="pgnote"></p>
<div class="chips">${(ar?['لخّص الموازنة قصاد الفعلي وطلّع أكبر 3 انحرافات','رتّب أولويات التحصيل وجهّز رسالة لأكبر عميل متأخر','قارن عروض الموردين واقترح الأفضل بمبررات']:['Summarise budget vs actual and find the 3 biggest variances','Prioritise collections and draft a message to the largest overdue customer','Compare supplier quotes and recommend one with reasons']).map((s,i)=>`<button class="chip" data-pgs="${i}" data-d="${['bva','ar_aging','suppliers'][i]}">${s}</button>`).join('')}</div></div>
<div class="abpane"><h3>🧭 ${ar?'خطوات الوكيل':'Agent steps'}</h3><div id="pgtrace" class="pgtrace">${pgTrace()||`<p class="k">${ar?'لسه مفيش خطوات.':'No steps yet.'}</p>`}</div>${PG.out?`<h3>✅ ${ar?'التسليم النهائي':'Final delivery'}</h3><div class="pgfinal">${fmtMD(PG.out)}</div>`:''}</div></div>`}
async function pgRun(){const ar=LANG==='ar';if(!PG.goal.trim()){ntf('pgnote',ar?'اكتب هدف الأول.':'Write a goal first.');return}const sample=await tutorSample();if(!sample){ntf('pgnote',ar?'الملعب بيشتغل لما المنصة تتفتح جوه Claude (claude.ai).':'The playground works when the platform is opened inside Claude (claude.ai).');return}
PG.trace=[];PG.out='';PG.busy=true;render();PGCTL=new AbortController();
const ask=`You are a careful business agent working for a company in Egypt or the Gulf. GOAL: ${PG.goal}
Starting dataset: ${PG.data} (read it with read_dataset). Work like an agent:
1) First write a short plan (max 4 steps) in one sentence each.
2) Use tools: read the data, use calculate for EVERY number you report, save_draft for documents.
3) Only if the goal needs something sent to a person, call send_message once with the final reviewed message; a human approves it.
4) Stop when the goal is met. Finish with a short delivery: what you did, key numbers (from calculate), what needs human review.
Never invent numbers or data. Reply in ${ar?'Egyptian Arabic':'English'}.`;
try{const {text}=await sample(ask,{tools:pgTools(),modelTier:'default',signal:PGCTL.signal,onText:({text})=>{PG.out=text;const f=document.querySelector('.pgfinal');if(f)f.innerHTML=fmtMD(text)}});PG.out=text||PG.out;if(!ST.pgXP){ST.pgXP=1;addXP(10)}}
catch(e){if(e&&e.code!=='cancelled')ntf('pgnote',e.code==='rate_limited'?(ar?'طلبات كتير — جرّب بعد شوية.':'Too many requests — try again soon.'):(ar?'الوكيل وقف بسبب خطأ. جرّب تاني.':'The agent stopped with an error. Try again.'));PG.out=(e&&e.text)||PG.out}
PG.busy=false;PGCTL=null;savePG();render()}

// --- 4. Multi-agent team designer
let TEAM=Object.assign({name:'',steps:[{a:'collections-prioritiser',ho:'',ap:false},{a:'cash-forecaster',ho:'',ap:false},{a:'board-report-writer',ho:'',ap:true}]},ST.team||{});
function saveTEAM(){ST.team=TEAM;saveST()}
const tmAgent=s=>{if(s.a&&s.a!=='custom'){const r=fdFind(s.a);if(r[1])return {f:r[0],a:r[1],n:r[1].n,job:r[1].job}}return {n:T(s.cn||'Custom agent',s.cn||'وكيل مخصص'),job:T(s.cj||'',s.cj||'')}};
function teamDiag(){const n=TEAM.steps.length;const gap=18;const w=Math.floor((640-gap*(n+1))/n);const nodes=TEAM.steps.map((s,i)=>{const x0=gap+i*(w+gap);const g=tmAgent(s);return ['t'+i,LANG==='ar'?640-x0-w:x0,110,w,70,T((s.ap?'✅ ':'')+g.n.en,(s.ap?'✅ ':'')+g.n.ar)]});const edges=TEAM.steps.slice(1).map((s,i)=>['t'+i,'t'+(i+1)]);
return {k:'team',t:T('',''),d:T('',''),nodes,edges,steps:[{on:nodes.map(x=>x[0]).concat(edges.map(e=>e[0]+'>'+e[1])),c:T('','')}]}}
function teamPrompt(lang){const en=lang==='en';let p=en?`You run a team of ${TEAM.steps.length} agents in order${TEAM.name?` («${TEAM.name}»)`:''}. For each step act as that agent, produce its outputs, check them, and pass ONLY the hand-off package to the next step. Stop and wait for my approval wherever marked. Never post, pay or send anything yourself. Use only the data I attach; write [MISSING] for gaps and label assumptions.\n`:`هتشغّل فريق من ${TEAM.steps.length} وكلاء بالترتيب${TEAM.name?` («${TEAM.name}»)`:''}. في كل خطوة اشتغل كأنك الوكيل ده، طلّع مخرجاته وراجعها، وسلّم «حزمة التسليم» بس للخطوة اللي بعدها. اقف واستنى موافقتي في الأماكن المعلّمة. ممنوع ترحّل أو تدفع أو تبعت أي حاجة بنفسك. استخدم البيانات اللي هرفقها بس؛ اكتب [MISSING] لأي نقص وعلّم الافتراضات.\n`;
TEAM.steps.forEach((s,i)=>{const g=tmAgent(s);p+=`\n## ${en?'Step':'الخطوة'} ${i+1} — ${g.n[lang]}\n${en?'Job':'المهمة'}: ${g.job[lang]||'[..]'}\n`;if(g.a)p+=`${en?'Outputs':'المخرجات'}: ${fdList(g.a.out[lang]).join('; ')}\n`;if(i<TEAM.steps.length-1)p+=`${en?'Hand-off to step':'التسليم للخطوة'} ${i+2}: ${s.ho||'[..]'}\n`;if(s.ap)p+=en?'⏸ STOP here for human approval before continuing.\n':'⏸ اقف هنا لموافقة بشرية قبل ما تكمّل.\n'});
return p+(en?'\nStart with step 1: list the inputs you need from me.':'\nابدأ بالخطوة 1: اكتب المدخلات اللي محتاجها مني.')}
function vTeam(){const ar=LANG==='ar';const lang=ar?'ar':'en';const opt=v=>`<option value="custom" ${v==='custom'?'selected':''}>✎ ${ar?'وكيل مخصص':'Custom agent'}</option>`+FD.map(f=>`<optgroup label="${esc(L(f.t))}">${f.agents.map(a=>`<option value="${a.k}" ${v===a.k?'selected':''}>${esc(L(a.n))}</option>`).join('')}</optgroup>`).join('');const pi=PSTORE.push(teamPrompt(lang))-1;
return `<p class="lede">${ar?'صمّم فريق وكلاء: رتّبهم، حدد بيتسلّموا إيه من بعض، وفين لازم موافقة بشرية. وبعدين صدّر الفريق كبرومبت واحد لـ Cowork ومعاه الـ Skills.':'Design a team of agents: order them, define what each hands to the next and where a human must approve. Then export the team as one Cowork prompt plus the Skills.'}</p>
<label class="pbf"><b>${ar?'اسم الفريق':'Team name'}</b><input class="search" data-tmn="1" value="${esc(TEAM.name)}" placeholder="${ar?'مثلاً: فريق إقفال الشهر':'e.g. Month-end team'}"></label>
<div class="tmsteps">${TEAM.steps.map((s,i)=>`<div class="tmstep"><span class="fdn">${i+1}</span><div class="tmbody"><select class="search" data-tma="${i}">${opt(s.a)}</select>${s.a==='custom'?`<input class="search" data-tmc="${i}|cn" value="${esc(s.cn||'')}" placeholder="${ar?'اسم الوكيل':'Agent name'}"><input class="search" data-tmc="${i}|cj" value="${esc(s.cj||'')}" placeholder="${ar?'المهمة الواحدة':'The one job'}">`:''}${i<TEAM.steps.length-1?`<input class="search" data-tmh="${i}" value="${esc(s.ho)}" placeholder="${ar?`بيسلّم إيه للخطوة ${i+2}؟`:`What does it hand to step ${i+2}?`}">`:''}<label class="fdrun"><input type="checkbox" data-tmp="${i}" ${s.ap?'checked':''}> ${ar?'موافقة بشرية بعد الخطوة دي':'Human approval after this step'}</label></div><div class="tmops"><button class="tbtn" data-tmo="up|${i}" ${i===0?'disabled':''}>↑</button><button class="tbtn" data-tmo="down|${i}" ${i===TEAM.steps.length-1?'disabled':''}>↓</button><button class="tbtn" data-tmo="del|${i}" ${TEAM.steps.length<3?'disabled':''}>✕</button></div></div>`).join('')}</div>
<div class="row-btns"><button class="tbtn" data-tmo="add|0" ${TEAM.steps.length>=6?'disabled':''}>＋ ${ar?'ضيف وكيل':'Add agent'}</button></div>
<section class="dgbox card">${dgSVG(teamDiag(),0)}</section>
<div class="row-btns"><button class="btn-gold copy" data-i="${pi}">${ar?'انسخ برومبت الفريق لـ Cowork':'Copy the team prompt for Cowork'}</button><button class="tbtn" data-tmx="zip">⬇ ${ar?'الفريق + الـ Skills (ZIP)':'Team + Skills (ZIP)'}</button><button class="tbtn" data-tmx="md">⬇ MD</button></div>
<details class="fdsp"><summary>🧠 ${ar?'شوف برومبت الفريق':'View the team prompt'}</summary><pre dir="auto">${esc(teamPrompt(lang))}</pre></details>`}
async function teamZip(btn){await ensureZip();const z=new JSZip();const id=slug(TEAM.name)||'agent-team';const root=z.folder(id);root.file('TEAM-PROMPT-EN.md',teamPrompt('en'));root.file('TEAM-PROMPT-AR.md',teamPrompt('ar'));TEAM.steps.forEach((s,i)=>{const g=tmAgent(s);if(g.a){const sk=fdSkill(g.a.sk);root.file(`agents/${i+1}-${g.a.k}.md`,fdPrompt(g.a,g.f,'en'));if(sk)root.folder('skills/'+sk.k).file('SKILL.md',fdSkillMd(sk,'en'))}});const ok=await saveFile(id+'.zip',await z.generateAsync({type:'blob'}));if(ok)btn.textContent='✓'}

// --- 5. Cost & time estimator
let CE=Object.assign({runs:20,manual:45,review:10,setup:6,rate:350,err0:8,err1:3},ST.ce||{});
function vCost(){const ar=LANG==='ar';const m=CE.runs*(CE.manual-CE.review)/60;const y=m*12;const val=y*CE.rate;const setupCost=CE.setup*CE.rate;const pay=m>0?setupCost/(m*CE.rate):Infinity;const errSaved=CE.runs*12*Math.max(0,CE.err0-CE.err1)/100;
const f=(k,lbl,suf)=>`<label class="pbf"><b>${lbl}</b><input class="search" type="number" min="0" data-ce="${k}" value="${CE[k]}"> <span class="k">${suf||''}</span></label>`;const bar=(v,max,c)=>`<i class="cebar"><em style="width:${Math.min(100,max?v*100/max:0)}%;background:${c}"></em></i>`;
return `<p class="lede">${ar?'قبل ما تبني وكيل، احسب: هيوفّر قد إيه، والمراجعة هتاخد قد إيه، وإمتى يرجّع تكلفة إعداده. الأرقام تقديرات إنت بتدخلها.':'Before you build an agent, estimate: time saved, review time and when the setup pays back. The numbers are your own estimates.'}</p>
<div class="twocol"><div class="abpane">${f('runs',ar?'مرات التشغيل في الشهر':'Runs per month')}${f('manual',ar?'دقايق الشغل اليدوي لكل مرة':'Manual minutes per run')}${f('review',ar?'دقايق مراجعتك لمخرج الوكيل':'Your review minutes per agent run')}${f('setup',ar?'ساعات الإعداد (مرة واحدة)':'Setup hours (one-off)')}${f('rate',ar?'تكلفة ساعة الموظف':'Hourly staff cost','EGP')}${f('err0',ar?'نسبة الأخطاء قبل':'Error rate before','%')}${f('err1',ar?'نسبة الأخطاء بعد':'Error rate after','%')}</div>
<div class="abpane"><h3>📊 ${ar?'النتيجة':'Result'}</h3><div class="cegrid"><div><span class="k">${ar?'ساعات موفّرة/شهر':'Hours saved / month'}</span><b>${m.toFixed(1)}</b></div><div><span class="k">${ar?'ساعات موفّرة/سنة':'Hours saved / year'}</span><b>${y.toFixed(0)}</b></div><div><span class="k">${ar?'قيمة الوقت/سنة':'Value of time / year'}</span><b>${Math.round(val).toLocaleString()} EGP</b></div><div><span class="k">${ar?'استرداد الإعداد':'Setup payback'}</span><b>${isFinite(pay)?pay.toFixed(1)+(ar?' شهر':' months'):'—'}</b></div><div><span class="k">${ar?'أخطاء أقل/سنة':'Fewer errors / year'}</span><b>${errSaved.toFixed(0)}</b></div></div>
<p class="k">${ar?'دقايق كل مرة':'Minutes per run'}</p><div class="cerow"><span>${ar?'يدوي':'Manual'}</span>${bar(CE.manual,CE.manual,'var(--red)')}<b>${CE.manual}</b></div><div class="cerow"><span>${ar?'وكيل + مراجعة':'Agent + review'}</span>${bar(CE.review,CE.manual,'var(--green)')}<b>${CE.review}</b></div>
<p class="note">${ar?'استخدام Claude بيتحسب من حدود خطتك؛ المهام التقيلة بتستهلك أكتر. المراجعة البشرية جزء من الحساب ومش اختيارية.':'Claude usage counts toward your plan’s limits; heavier tasks use more. Human review is part of the maths, not optional.'}</p>${m<=0?`<p class="note">⚠ ${ar?'المراجعة بتاخد وقت أكتر من الشغل اليدوي — الوكيل ده مش مستاهل دلوقتي.':'Review takes longer than doing it by hand — this agent is not worth it yet.'}</p>`:''}</div></div>`}

// ===== Workflow designer → automation hub tabs (8, 9, 11, 13) =====
let WFTAB='design';
{const _wf=vWF;vWF=function(){const ar=LANG==='ar';const tabs=`<div class="tabs big">${[['design','🔀',UX21.design],['find','🔎',UX21.find],['recipes','📗',UX21.recipes],['matrix','✅',UX21.matrix],['risk','⚠',UX21.risk]].map(t=>`<button class="tab ${WFTAB===t[0]?'on':''}" data-wftab="${t[0]}">${t[1]} ${L(t[2])}</button>`).join('')}</div>`;
if(WFTAB==='design')return _wf().replace(/(<\/h1>)/,'$1'+tabs);crumb(L(UX6.wf)+' › '+L(UX21[WFTAB]));return `<h1>🔀 ${L(UX6.wf)}</h1>`+tabs+(WFTAB==='find'?vAFind():WFTAB==='recipes'?vRecipes():WFTAB==='matrix'?vMatrix():vRisk())}}
let AF=Object.assign({field:'all',sel:{},week:'',res:null,busy:false},ST.af||{});AF.busy=false;
function saveAF(){const {busy,...r}=AF;ST.af=r;saveST()}
const AFW={'Cowork':1,'Scheduled task':1.1,'Project':0.8,'Skill':0.9,'Connector':0.9,'Claude in Excel':0.85,'API':0.7},AFR={low:1,med:0.75,high:0.5},AFF={daily:21,weekly:4.3,monthly:1};
function afScore(x){const s=AF.sel[x.k]||{};const mins=s.m!=null?s.m:x.mins;return Math.round(mins*AFF[x.freq]*(AFW[x.tool]||0.8)*AFR[x.risk]/6)}
function vAFind(){const ar=LANG==='ar';if(typeof AUTOFIND==='undefined')return '';const list=AUTOFIND.filter(x=>AF.field==='all'||x.field===AF.field);const chosen=AUTOFIND.filter(x=>AF.sel[x.k]);const top=chosen.slice().sort((a,b)=>afScore(b)-afScore(a)).slice(0,5);const fields=['all',...new Set(AUTOFIND.map(x=>x.field))];
return `<p class="lede">${ar?'علّم المهام اللي بتعملها، وعدّل الدقايق لو حابب. هنرتّبلك أحسن 5 مهام تستاهل أتمتة حسب الوقت والتكرار والمخاطرة — أو اوصف أسبوعك وClaude يقترح.':'Tick the tasks you do and adjust the minutes. We rank the top 5 worth automating by time, frequency and risk — or describe your week and let Claude suggest.'}</p>
<div class="chips">${fields.map(f=>`<button class="chip ${AF.field===f?'on':''}" data-aff="${f}">${f==='all'?(ar?'الكل':'All'):f}</button>`).join('')}</div>
<div class="twocol"><div class="abpane aflist">${list.map(x=>{const s=AF.sel[x.k];return `<label class="afrow ${s?'on':''}"><input type="checkbox" data-afk="${x.k}" ${s?'checked':''}><span><b>${esc(L(x.t))}</b><span class="k">${x.freq} · ${x.tool} · ${ar?'مخاطرة':'risk'} ${x.risk}</span></span>${s?`<input class="search afm" type="number" min="1" data-afm="${x.k}" value="${s.m!=null?s.m:x.mins}" title="${ar?'دقايق كل مرة':'minutes per run'}">`:`<span class="k">${x.mins}′</span>`}</label>`}).join('')}</div>
<div class="abpane"><h3>🏆 ${ar?'أحسن 5 تستاهل أتمتة':'Top 5 to automate'}</h3>${top.length?`<ol class="aftop">${top.map(x=>`<li><b>${esc(L(x.t))}</b> <span class="pkscore hi">${afScore(x)}</span><div class="k">${x.tool} — ${esc(L(x.why))}</div><div class="k">≈ ${Math.round(((AF.sel[x.k]||{}).m??x.mins)*AFF[x.freq]/60*10)/10} ${ar?'ساعة/شهر':'h / month'}</div></li>`).join('')}</ol>`:`<p class="k">${ar?'علّم مهام من القايمة.':'Tick tasks in the list.'}</p>`}
<h3 style="margin-top:14px">💬 ${ar?'أو اوصف أسبوعك':'Or describe your week'}</h3><textarea class="search" id="afweek" rows="4" dir="auto" placeholder="${ar?'مثلاً: كل يوم بطابق البنك، كل اتنين بعمل تقرير مبيعات…':'e.g. Every day I reconcile the bank; every Monday I build a sales report…'}">${esc(AF.week)}</textarea><div class="row-btns"><button class="btn-gold" data-af="ask" ${AF.busy?'disabled':''}>${AF.busy?'…':'✨ '+(ar?'اقترح مع Claude':'Suggest with Claude')}</button></div><p class="note" id="afnote"></p>
${AF.res?`<ol class="aftop">${AF.res.map(r=>`<li><b dir="auto">${esc(r.task)}</b> · ${esc(r.tool)} <span class="k">≈ ${esc(String(r.hours_per_month))} ${ar?'ساعة/شهر':'h/mo'}</span><div class="k" dir="auto">${esc(r.why)}</div></li>`).join('')}</ol>`:''}</div></div>`}
async function afAsk(){const ar=LANG==='ar';if(!AF.week.trim()){ntf('afnote',ar?'اوصف أسبوعك الأول.':'Describe your week first.');return}const sample=await tutorSample();if(!sample){ntf('afnote',ar?'الاقتراح مع Claude بيشتغل جوه claude.ai.':'Suggestions with Claude work inside claude.ai.');return}
AF.busy=true;render();try{const j=await sample.json(`You help a professional in Egypt or the Gulf decide what to automate with Claude (Cowork, scheduled tasks, Projects, Skills, connectors, Claude in Excel, API). From their week below, pick the 5 tasks most worth automating (time × frequency, low risk first) and keep a human review for anything sent, paid or filed. Write task and why in ${ar?'Egyptian Arabic':'English'}. JSON only: {"top":[{"task":"","tool":"","hours_per_month":0,"why":""}]}\n\nWEEK:\n${AF.week.slice(0,4000)}`,{modelTier:'default'});AF.res=(j.top||[]).slice(0,5).map(r=>({task:String(r.task||''),tool:String(r.tool||''),hours_per_month:r.hours_per_month,why:String(r.why||'')}))}catch(e){ntf('afnote',ar?'مقدرتش أقترح دلوقتي.':'Could not suggest right now.')}AF.busy=false;saveAF();render()}
let RCAT='all';
function vRecipes(){const ar=LANG==='ar';if(typeof RECIPES==='undefined')return '';const cats=['all',...new Set(RECIPES.map(r=>r.cat))];const list=RECIPES.filter(r=>RCAT==='all'||r.cat===RCAT);
return `<p class="lede">${ar?'وصفات أتمتة جاهزة: إيه اللي يشغّلها، بأنهي أداة، الخطوات، مين يوافق — والبرومبت الماستر.':'Ready automation recipes: what triggers it, which tool, the steps, who approves — and the master prompt.'}</p><div class="chips">${cats.map(c=>`<button class="chip ${RCAT===c?'on':''}" data-rcat="${c}">${c==='all'?(ar?'الكل':'All'):c}</button>`).join('')}</div>
<div class="fdlist">${list.map(r=>`<details class="fdag"><summary class="fdhead"><span class="fdi">${r.icon}</span><span class="fdt"><b>${esc(L(r.t))}</b><span class="k">⏰ ${esc(L(r.trigger))}</span></span></summary><div class="fdbody"><p><b>🛠 ${ar?'الأداة':'Tool'}:</b> ${esc(L(r.tool))}</p><ol>${L(r.steps).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p><b>✅ ${ar?'الموافقة':'Approval'}:</b> ${esc(L(r.approval))}</p>${promptBox(r.pr)}<div class="row-btns"><button class="tbtn" data-rmx="${r.k}">✅ ${ar?'ابني مصفوفة موافقات منها':'Build an approval matrix from it'}</button></div></div></details>`).join('')}</div>`}
let AM=Object.assign({name:'',rows:[]},ST.am||{});
function saveAM(){ST.am=AM;saveST()}
const AMRISK=[['low',T('Low','منخفضة')],['med',T('Medium','متوسطة')],['high',T('High','عالية')]];
function vMatrix(){const ar=LANG==='ar';return `<p class="lede">${ar?'لكل خطوة في الأتمتة: مستوى المخاطرة، مين يوافق، الحد، والدليل اللي يتحفظ. صدّرها كجدول سياسة.':'For each automated step: risk level, who approves, the threshold and the evidence kept. Export it as a policy table.'}</p>
<label class="pbf"><b>${ar?'اسم الأتمتة':'Automation name'}</b><input class="search" data-amn="1" value="${esc(AM.name)}"></label>
<div class="tablewrap"><table class="amtable"><tr><th>#</th><th>${ar?'الخطوة':'Step'}</th><th>${ar?'المخاطرة':'Risk'}</th><th>${ar?'مين يوافق':'Approver'}</th><th>${ar?'الحد':'Threshold'}</th><th>${ar?'الدليل':'Evidence'}</th><th></th></tr>${AM.rows.map((r,i)=>`<tr><td>${i+1}</td><td><input class="search" data-amr="${i}|step" value="${esc(r.step)}"></td><td><select class="search" data-amr="${i}|risk">${AMRISK.map(x=>`<option value="${x[0]}" ${r.risk===x[0]?'selected':''}>${L(x[1])}</option>`).join('')}</select></td><td><input class="search" data-amr="${i}|appr" value="${esc(r.appr)}" placeholder="${ar?'مثلاً: المدير المالي':'e.g. Finance manager'}"></td><td><input class="search" data-amr="${i}|thr" value="${esc(r.thr)}" placeholder="${ar?'مثلاً: أي مبلغ فوق 50 ألف':'e.g. any amount above 50k'}"></td><td><input class="search" data-amr="${i}|ev" value="${esc(r.ev)}" placeholder="${ar?'مثلاً: لوج + نسخة المسودة':'e.g. log + draft copy'}"></td><td><button class="tbtn" data-amd="${i}">✕</button></td></tr>`).join('')}</table></div>
<div class="row-btns"><button class="tbtn" data-ama="1">＋ ${ar?'ضيف خطوة':'Add step'}</button><button class="tbtn" data-amx="md">⬇ MD</button><button class="tbtn" data-amx="csv">⬇ CSV</button></div>
<p class="note">${ar?'قاعدة ذهبية: أي حاجة بتتبعت لعميل، أو فلوس بتتصرف، أو قيود بتترحّل، أو حاجة بتتقدّم لجهة رسمية = موافقة بشرية باسم واضح.':'Golden rule: anything sent to a customer, money paid, entries posted or filings submitted = a named human approval.'}</p>`}
const amMD=()=>`# ${AM.name||'Approval matrix'}\n\n| # | Step | Risk | Approver | Threshold | Evidence |\n|---|---|---|---|---|---|\n`+AM.rows.map((r,i)=>`| ${i+1} | ${r.step} | ${r.risk} | ${r.appr} | ${r.thr} | ${r.ev} |`).join('\n')+'\n';
let RK=Object.assign({sel:{},desc:'',res:null,busy:false},ST.rk||{});RK.busy=false;
function saveRK(){const {busy,...r}=RK;ST.rk=r;saveST()}
function vRisk(){const ar=LANG==='ar';if(typeof RISKLIB==='undefined')return '';const sel=RISKLIB.filter(r=>RK.sel[r.k]);const cell=(s,l)=>sel.filter(r=>(RK.sel[r.k].s||r.sev)===s&&(RK.sel[r.k].l||r.lik)===l).length;
const heat=`<table class="heat"><tr><th>${ar?'الأثر ↓ / الاحتمال →':'Impact ↓ / likelihood →'}</th>${[1,2,3,4,5].map(l=>`<th>${l}</th>`).join('')}</tr>${[5,4,3,2,1].map(s=>`<tr><th>${s}</th>${[1,2,3,4,5].map(l=>{const n=cell(s,l);const sc=s*l;return `<td class="${sc>=15?'hh':sc>=8?'hm':'hl'}">${n||''}</td>`}).join('')}</tr>`).join('')}</table>`;
return `<p class="lede">${ar?'اختار المخاطر اللي تخص الأتمتة بتاعتك، قدّر الأثر والاحتمال، وحط ضابط ومسؤول لكل واحدة. أو اوصف الأتمتة وClaude يقترح المخاطر.':'Pick the risks that apply to your automation, rate impact and likelihood, and set a control and owner for each. Or describe the automation and let Claude suggest risks.'}</p>
<div class="twocol"><div class="abpane aflist">${RISKLIB.map(r=>{const s=RK.sel[r.k];return `<label class="afrow ${s?'on':''}"><input type="checkbox" data-rkk="${r.k}" ${s?'checked':''}><span><b>${esc(L(r.t))}</b><span class="k">${r.cat} · ${ar?'الضابط':'control'}: ${esc(L(r.ctrl))}</span></span>${s?`<span class="rksl"><select data-rks="${r.k}|s">${[1,2,3,4,5].map(v=>`<option ${((s.s||r.sev)===v)?'selected':''}>${v}</option>`).join('')}</select><select data-rks="${r.k}|l">${[1,2,3,4,5].map(v=>`<option ${((s.l||r.lik)===v)?'selected':''}>${v}</option>`).join('')}</select></span>`:''}</label>`}).join('')}</div>
<div class="abpane"><h3>🌡 ${ar?'خريطة المخاطر':'Heat map'} (${sel.length})</h3>${heat}<div class="row-btns"><button class="tbtn" data-rkx="csv" ${sel.length?'':'disabled'}>⬇ CSV</button><button class="tbtn" data-rkx="md" ${sel.length?'':'disabled'}>⬇ MD</button></div>
<h3 style="margin-top:12px">💬 ${ar?'اوصف الأتمتة':'Describe the automation'}</h3><textarea class="search" id="rkdesc" rows="3" dir="auto">${esc(RK.desc)}</textarea><div class="row-btns"><button class="btn-gold" data-rk="ask" ${RK.busy?'disabled':''}>${RK.busy?'…':'✨ '+(ar?'اقترح المخاطر مع Claude':'Suggest risks with Claude')}</button></div><p class="note" id="rknote"></p>${RK.res?`<ul>${RK.res.map(x=>`<li dir="auto"><b>${esc(x.risk)}</b> — ${esc(x.control)} <span class="k">(${esc(x.level)})</span></li>`).join('')}</ul>`:''}</div></div>`}
const rkRows=()=>RISKLIB.filter(r=>RK.sel[r.k]).map(r=>{const s=RK.sel[r.k];return {t:L(r.t),cat:r.cat,sev:s.s||r.sev,lik:s.l||r.lik,ctrl:L(r.ctrl),owner:L(r.owner)}});
async function rkAsk(){const ar=LANG==='ar';if(!RK.desc.trim()){ntf('rknote',ar?'اوصف الأتمتة الأول.':'Describe the automation first.');return}const sample=await tutorSample();if(!sample){ntf('rknote',ar?'بيشتغل جوه claude.ai.':'Works inside claude.ai.');return}RK.busy=true;render();
try{const j=await sample.json(`List the 6 most important risks of this business automation/agent and one practical control for each (data leakage, wrong numbers, prompt injection, over-broad connector access, silent failure, missing approvals, audit trail, people over-reliance…). Write in ${ar?'Egyptian Arabic':'English'}. JSON only: {"risks":[{"risk":"","control":"","level":"low|med|high"}]}\n\nAUTOMATION:\n${RK.desc.slice(0,3000)}`,{modelTier:'default'});RK.res=(j.risks||[]).slice(0,8).map(x=>({risk:String(x.risk||''),control:String(x.control||''),level:String(x.level||'')}))}catch(e){ntf('rknote',ar?'مقدرتش دلوقتي.':'Could not do it now.')}RK.busy=false;saveRK();render()}

// ===== Module 3: artifact & design studio (14, 15, 16, 17, 19) =====
let M3TAB='gallery',AGC='all';
let WZ=Object.assign({users:'',data:'',actions:'',show:'',look:'',lang:'both',save:''},ST.wz||{});let BR=Object.assign({type:'one-pager',aud:'',msg:'',size:'A4 portrait',brand:'',langs:'Arabic + English',must:'',tone:''},ST.br||{});let BK=Object.assign({c:['#13284B','#C9A227','#FFFFFF','#1C7F7A'],fonts:''},ST.bk||{});let DL2=Object.assign({k:'sales_monthly',sel:[0,1,2],aud:''},ST.dl2||{});
function m3Section(){const ar=LANG==='ar';const tabs=[['gallery','🖼',T('Artifact gallery','معرض الـ Artifacts')],['wizard','🪄',T('Artifact builder wizard','معالج بناء Artifact')],['brief','🎨',T('Design brief generator','مولّد بريف التصميم')],['brand','🎯',T('Brand kit checker','فاحص هوية البراند')],['dash','📊',T('Dashboard lab','معمل الداشبورد')]];
const body=M3TAB==='gallery'?m3Gallery():M3TAB==='wizard'?m3Wizard():M3TAB==='brief'?m3Brief():M3TAB==='brand'?m3Brand():m3Dash();
return `<section id="m3studio" class="mergedsec"><h2>🧰 ${L(UX21.m3)}</h2><div class="tabs big">${tabs.map(t=>`<button class="tab ${M3TAB===t[0]?'on':''}" data-m3tab="${t[0]}">${t[1]} ${L(t[2])}</button>`).join('')}</div>${body}</section>`}
function m3Gallery(){const ar=LANG==='ar';if(typeof ARTGAL==='undefined')return '';const cats=['all',...new Set(ARTGAL.map(a=>a.cat))];const list=ARTGAL.filter(a=>AGC==='all'||a.cat===AGC);
return `<p class="lede">${ar?'20 Artifact جاهزين لفرق الشغل — اختار واحد وانسخ البرومبت الماستر، وClaude يبنيهولك.':'20 ready artifacts for business teams — pick one, copy the master prompt, and Claude builds it.'}</p><div class="chips">${cats.map(c=>`<button class="chip ${AGC===c?'on':''}" data-agc="${c}">${c==='all'?(ar?'الكل':'All'):c}</button>`).join('')}</div>
<div class="grid">${list.map(a=>`<details class="card agcard"><summary><span class="fdi">${a.icon}</span> <b>${esc(L(a.t))}</b><div class="k">${esc(L(a.d))}</div><div class="k">👥 ${esc(L(a.users))}${a.data?` · 📊 ${a.data}.csv`:''}</div></summary>${promptBox(a.pr)}${a.data&&DATA[a.data]?`<button class="dlbtn" data-csv="${a.data}">⬇ ${a.data}.csv</button>`:''}</details>`).join('')}</div>`}
function wzPrompt(lang){const en=lang==='en';const L2=WZ.lang==='both'?(en?'Arabic (RTL) and English with a language toggle':'عربي (RTL) وإنجليزي بزرار تبديل اللغة'):WZ.lang==='ar'?(en?'Arabic (RTL)':'العربي (RTL)'):(en?'English':'الإنجليزي');
return (en?MPen:MPar)(en?'Senior product designer and front-end developer who builds Claude artifacts for business teams in Egypt and the Gulf':'مصمم منتجات ومطوّر واجهات أول بيبني Claude artifacts لفرق شغل في مصر والخليج',en?`Build an interactive artifact for: ${WZ.users||'[who uses it]'}`:`ابني artifact تفاعلي لـ: ${WZ.users||'[مين هيستخدمه]'}`,
`- ${en?'Users':'المستخدمين'}: ${WZ.users||'[..]'}\n- ${en?'Data':'البيانات'}: ${WZ.data||'[paste or attach the data]'}\n- ${en?'What users do':'المستخدم بيعمل إيه'}: ${WZ.actions||'[..]'}\n- ${en?'What it calculates / shows':'بيحسب / بيعرض إيه'}: ${WZ.show||'[..]'}\n- ${en?'Look':'الشكل'}: ${WZ.look||'[brand colours, clean, mobile-friendly]'}\n- ${en?'Language':'اللغة'}: ${L2}\n- ${en?'Saving / sharing':'الحفظ / المشاركة'}: ${WZ.save||'[none / export CSV / print]'}`,
en?'Plan the screens first (max 3), then the data model, then build. Every number comes from the data or the user’s inputs.':'خطط للشاشات الأول (3 بالكتير)، بعدين شكل البيانات، وبعدين ابني. كل رقم من البيانات أو من مدخلات المستخدم.',
en?'- Works on a phone (no horizontal scroll)\n- Readable in light and dark\n- No invented numbers; empty states handled\n- Max 3 screens or tabs':'- يشتغل على الموبايل (من غير scroll عرضي)\n- مقروء في الوضع الفاتح والغامق\n- مفيش أرقام متألفة؛ والحالات الفاضية متعالجة\n- 3 شاشات أو تابات بالكتير',
en?'One self-contained artifact, then 3 bullets: how to use it, what to check, what to improve next.':'Artifact واحد كامل، وبعده 3 نقاط: إزاي يتستخدم، تراجع إيه، تحسّن إيه بعد كده.')}
function m3Wizard(){const ar=LANG==='ar';const f=(k,q,ph)=>`<label class="pbf"><b>${q}</b><input class="search" data-wz="${k}" value="${esc(WZ[k])}" placeholder="${esc(ph)}"></label>`;const lang=ar?'ar':'en';const p=wzPrompt(lang);const i=PSTORE.push(p)-1;const sc=pkScoreFull(p).score;
return `<p class="lede">${ar?'جاوب على 6 أسئلة — والمعالج يكتبلك برومبت ماستر كامل لـ Artifact.':'Answer 6 questions — the wizard writes a complete master prompt for your artifact.'}</p><div class="twocol"><div class="abpane">${f('users',ar?'1. مين هيستخدمه؟':'1. Who uses it?',ar?'مثلاً: مديري الفروع':'e.g. branch managers')}${f('data',ar?'2. بيانات إيه؟':'2. What data?',ar?'مثلاً: sales_monthly.csv':'e.g. sales_monthly.csv')}${f('actions',ar?'3. المستخدم بيعمل إيه؟':'3. What do users do?',ar?'يفلتر بالمنطقة والمنتج':'filter by region and product')}${f('show',ar?'4. بيحسب أو بيعرض إيه؟':'4. What does it calculate or show?',ar?'الإيراد والنمو وأعلى 5 منتجات':'revenue, growth, top 5 products')}${f('look',ar?'5. الشكل':'5. Look',ar?'ألوان البراند، بسيط':'brand colours, clean')}<label class="pbf"><b>${ar?'6. اللغة':'6. Language'}</b><select class="search" data-wz="lang">${[['both','AR + EN'],['ar','العربي'],['en','English']].map(o=>`<option value="${o[0]}" ${WZ.lang===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select></label>${f('save',ar?'الحفظ أو المشاركة':'Saving or sharing',ar?'تصدير CSV وطباعة':'export CSV and print')}</div>
<div class="abpane"><h3>🧠 ${ar?'البرومبت الماستر':'Master prompt'} <span class="pkscore ${sc>=80?'hi':sc>=55?'mid':'lo'}">${sc}</span></h3><pre dir="auto" class="repre">${esc(p)}</pre><div class="row-btns"><button class="btn-gold copy" data-i="${i}">${L(UI.copy)}</button><button class="tbtn" data-rei="${i}">♻ ${ar?'حسّنه':'Re-enhance'}</button></div></div></div>`}
function brPrompt(lang){const en=lang==='en';return (en?MPen:MPar)(en?'Senior brand and visual designer using Claude Design for a company in Egypt or the Gulf':'مصمم براند وجرافيك أول بيستخدم Claude Design لشركة في مصر أو الخليج',en?`Design a ${BR.type} for ${BR.aud||'[audience]'}`:`صمّم ${BR.type} لـ ${BR.aud||'[الجمهور]'}`,
`- ${en?'Key message':'الرسالة الأساسية'}: ${BR.msg||'[..]'}\n- ${en?'Size / format':'المقاس / الشكل'}: ${BR.size}\n- ${en?'Brand (colours, fonts, logo)':'البراند (ألوان، خطوط، لوجو)'}: ${BR.brand||'[use our design system]'}\n- ${en?'Languages':'اللغات'}: ${BR.langs}\n- ${en?'Must include':'لازم يحتوي'}: ${BR.must||'[..]'}\n- ${en?'Tone':'النبرة'}: ${BR.tone||'[professional, warm]'}`,
en?'Start with 2 layout options, then refine the chosen one. Keep the visual hierarchy: headline → proof → call to action.':'ابدأ باقتراحين للتصميم، وبعدين حسّن اللي هتختاره. حافظ على ترتيب: العنوان ← الدليل ← الدعوة لإجراء.',
en?'- Text contrast at least 4.5:1\n- Arabic set right-to-left with an Arabic font\n- Every number and claim provided by me, none invented\n- 1 page unless I say otherwise':'- تباين النص 4.5:1 على الأقل\n- العربي من اليمين للشمال بخط عربي\n- كل رقم ومعلومة مني أنا، ومفيش حاجة متألفة\n- صفحة واحدة إلا لو قلت غير كده',
en?'A canvas draft I can refine with comments, then export to PDF and PPTX.':'مسودة على اللوحة أقدر أعدّلها بالتعليقات، وبعدين تتصدّر PDF و PPTX.')}
function m3Brief(){const ar=LANG==='ar';const f=(k,q,ph)=>`<label class="pbf"><b>${q}</b><input class="search" data-br="${k}" value="${esc(BR[k])}" placeholder="${esc(ph||'')}"></label>`;const p=brPrompt(ar?'ar':'en');const i=PSTORE.push(p)-1;
return `<p class="lede">${ar?'بريف قوي = تصميم أحسن من أول مرة. املا الخانات وخد بريف جاهز لـ Claude Design.':'A strong brief = a better design first time. Fill the fields and get a ready brief for Claude Design.'}</p><div class="twocol"><div class="abpane"><label class="pbf"><b>${ar?'نوع التصميم':'Asset type'}</b><select class="search" data-br="type">${['one-pager','pitch deck','social carousel','flyer','infographic','event invitation','landing page prototype','course cover'].map(o=>`<option ${BR.type===o?'selected':''}>${o}</option>`).join('')}</select></label>${f('aud',ar?'الجمهور':'Audience',ar?'مثلاً: مديري مشتريات في السعودية':'e.g. procurement heads in KSA')}${f('msg',ar?'الرسالة الأساسية':'Key message')}${f('size',ar?'المقاس':'Size','A4 portrait / 1080×1350')}${f('brand',ar?'البراند':'Brand',ar?'#13284B كحلي، #C9A227 دهبي، Readex Pro':'#13284B navy, #C9A227 gold, Readex Pro')}${f('langs',ar?'اللغات':'Languages')}${f('must',ar?'لازم يحتوي':'Must include',ar?'لوجو، QR، رقم تليفون':'logo, QR, phone')}${f('tone',ar?'النبرة':'Tone')}</div>
<div class="abpane"><h3>🎨 ${ar?'البريف':'The brief'}</h3><pre dir="auto" class="repre">${esc(p)}</pre><div class="row-btns"><button class="btn-gold copy" data-i="${i}">${L(UI.copy)}</button><a class="tbtn" href="https://claude.ai/design" target="_blank" rel="noopener">↗ claude.ai/design</a></div></div></div>`}
function hexRgb(h){h=String(h).trim().replace('#','');if(h.length===3)h=h.split('').map(c=>c+c).join('');if(!/^[0-9a-f]{6}$/i.test(h))return null;return [0,2,4].map(i=>parseInt(h.slice(i,i+2),16))}
function lum(rgb){const c=rgb.map(v=>{v/=255;return v<=0.03928?v/12.92:Math.pow((v+0.055)/1.055,2.4)});return 0.2126*c[0]+0.7152*c[1]+0.0722*c[2]}
function cratio(a,b){const A=hexRgb(a),B=hexRgb(b);if(!A||!B)return null;const l1=lum(A),l2=lum(B);return Math.round((Math.max(l1,l2)+0.05)/(Math.min(l1,l2)+0.05)*100)/100}
function m3Brand(){const ar=LANG==='ar';const cs=BK.c.filter(c=>hexRgb(c));const ARF=[['Readex Pro',T('Clean UI and body text','واجهات ونصوص')],['Cairo',T('Friendly headings and body','عناوين ونصوص ودودة')],['Tajawal',T('Light, modern body text','نصوص خفيفة وحديثة')],['IBM Plex Sans Arabic',T('Corporate reports and dashboards','تقارير وداشبوردات رسمية')],['Noto Kufi Arabic',T('Strong headings','عناوين قوية')],['Amiri',T('Classic, formal titles','عناوين رسمية كلاسيك')]];
return `<p class="lede">${ar?'دخّل ألوان البراند وشوف التباين بين كل لونين (نص على خلفية) حسب WCAG: 4.5 للنص العادي و3 للعناوين الكبيرة.':'Enter your brand colours and see the contrast for every text-on-background pair (WCAG): 4.5 for body text, 3 for large headings.'}</p>
<div class="bkcolors">${BK.c.map((c,i)=>`<label class="bkc"><input type="color" data-bkc="${i}" value="${hexRgb(c)?'#'+String(c).replace('#','').slice(0,6):'#000000'}"><input class="search" data-bkh="${i}" value="${esc(c)}"></label>`).join('')}<button class="tbtn" data-bka="1" ${BK.c.length>=6?'disabled':''}>＋</button></div>
<div class="tablewrap"><table class="bkt"><tr><th>${ar?'النص ↓ / الخلفية →':'Text ↓ / background →'}</th>${cs.map(b=>`<th><span class="sw" style="background:${b}"></span>${b}</th>`).join('')}</tr>${cs.map(t=>`<tr><th><span class="sw" style="background:${t}"></span>${t}</th>${cs.map(b=>{if(t===b)return '<td>—</td>';const r=cratio(t,b);return `<td style="background:${b};color:${t}" title="${r}"><b>Aa أب</b><div class="bkr ${r>=4.5?'ok':r>=3?'mid':'no'}">${r} ${r>=4.5?'AA':r>=3?(ar?'عناوين بس':'large only'):'✗'}</div></td>`}).join('')}</tr>`).join('')}</table></div>
<h3>🔤 ${ar?'خطوط عربي مقترحة (Google Fonts)':'Suggested Arabic fonts (Google Fonts)'}</h3><ul>${ARF.map(f=>`<li><b>${f[0]}</b> — ${L(f[1])}</li>`).join('')}</ul><p class="note">${ar?'استخدم خط واحد للعناوين وواحد للنص بالكتير، واختبر الأرقام العربي والإنجليزي في نفس الجدول.':'Use at most one heading font and one body font, and test Arabic and Western digits in the same table.'}</p>`}
function dlPrompt(lang){const en=lang==='en';const K=(typeof DASHKPI!=='undefined'&&DASHKPI[DL2.k])||[];const sel=K.filter((_,i)=>DL2.sel.includes(i));
return (en?MPen:MPar)(en?'Senior BI developer who builds interactive Claude artifact dashboards for managers in Egypt and the Gulf':'مطوّر BI أول بيبني داشبوردات Claude artifact تفاعلية لمديرين في مصر والخليج',en?`Build an interactive KPI dashboard from ${DL2.k}.csv`:`ابني داشبورد مؤشرات تفاعلي من ${DL2.k}.csv`,
`- ${en?'Data':'البيانات'}: ${DL2.k}.csv (${DATA[DL2.k].csv.split('\n')[0]})\n- ${en?'Audience':'الجمهور'}: ${DL2.aud||'[..]'}\n`+sel.map(r=>`- KPI: ${en?r[0]:r[1]} = ${en?r[2]:r[3]} → ${r[4]}`).join('\n'),
en?'Validate the data first (types, blanks, duplicates), compute each KPI exactly from the columns, then lay out KPI cards on top, charts below, and filters on the side.':'راجع البيانات الأول (الأنواع، الخانات الفاضية، التكرار)، احسب كل مؤشر بالظبط من الأعمدة، وبعدين حط كروت المؤشرات فوق والرسوم تحت والفلاتر على الجنب.',
en?'- Every KPI value matches a manual check on 3 rows\n- Max 6 visuals\n- Readable on a phone and in dark mode\n- Note any data issue instead of hiding it':'- كل قيمة مؤشر متطابقة مع مراجعة يدوية على 3 صفوف\n- 6 رسوم بالكتير\n- مقروء على الموبايل وفي الوضع الغامق\n- اكتب أي مشكلة في البيانات بدل ما تخبيها',
en?'One artifact with filters + a 5-bullet insight summary in English.':'Artifact واحد بفلاتر + ملخص 5 نقاط بالعربي.')}
function m3Dash(){const ar=LANG==='ar';if(typeof DASHKPI==='undefined')return '';const K=DASHKPI[DL2.k]||[];const p=dlPrompt(ar?'ar':'en');const i=PSTORE.push(p)-1;const rows=DATA[DL2.k].csv.split('\n');
return `<p class="lede">${ar?'اختار بيانات، علّم المؤشرات، وخد برومبت داشبورد كامل — ومعاه ملف البيانات للتجربة.':'Pick a dataset, tick the KPIs and get a complete dashboard prompt — plus the data file to try it.'}</p><div class="chips">${Object.keys(DASHKPI).map(k=>`<button class="chip ${DL2.k===k?'on':''}" data-dlk="${k}">${k}</button>`).join('')}</div>
<div class="twocol"><div class="abpane"><h3>📐 ${ar?'المؤشرات':'KPIs'}</h3>${K.map((r,j)=>`<label class="afrow ${DL2.sel.includes(j)?'on':''}"><input type="checkbox" data-dls="${j}" ${DL2.sel.includes(j)?'checked':''}><span><b>${esc(ar?r[1]:r[0])}</b><span class="k">${esc(ar?r[3]:r[2])} · ${r[4]}</span></span></label>`).join('')}<label class="pbf"><b>${ar?'الجمهور':'Audience'}</b><input class="search" data-dla="1" value="${esc(DL2.aud)}"></label><div class="tablewrap"><table class="dlprev"><tr>${rows[0].split(',').map(c=>`<th>${esc(c)}</th>`).join('')}</tr>${rows.slice(1,5).map(r=>`<tr>${r.split(',').map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</table></div><p class="k">${rows.length-1} ${ar?'صف':'rows'}</p></div>
<div class="abpane"><h3>🧠 ${ar?'برومبت الداشبورد':'Dashboard prompt'}</h3><pre dir="auto" class="repre">${esc(p)}</pre><div class="row-btns"><button class="btn-gold copy" data-i="${i}">${L(UI.copy)}</button><button class="dlbtn" data-csv="${DL2.k}">⬇ ${DL2.k}.csv</button><button class="tbtn" data-rei="${i}">♻</button></div></div></div>`}
{const _vd=vDay;vDay=function(n,id){const h=_vd(n,id);if(id)return h;if(String(n)==='3')return h+m3Section();if(String(n)==='6')return h+baSection();return h}}

// ===== 22. Failure gallery on the certificates page =====
let FGC='all';
function failSection(){const ar=LANG==='ar';if(typeof FAILS2==='undefined')return '';const cats=['all',...new Set(FAILS2.map(f=>f.cat))];const list=FAILS2.filter(f=>FGC==='all'||f.cat===FGC);const seen=ST.fgSeen||{};
return `<section class="careers"><h2>🧯 ${L(UX21.fails)}</h2><p class="k">${ar?`أخطاء بتحصل فعلًا مع الوكلاء والأتمتة والـ artifacts — اقرا القصة، السبب، الحل، والسطر اللي يمنعها. اقرا الـ ${FAILS2.length} علشان تاخد XP.`:`Real-style failures with agents, automations and artifacts — the story, root cause, fix and the line that prevents it. Read all ${FAILS2.length} to earn XP.`} (${Object.keys(seen).length}/${FAILS2.length})</p><div class="chips">${cats.map(c=>`<button class="chip ${FGC===c?'on':''}" data-fgc="${c}">${c==='all'?(ar?'الكل':'All'):c}</button>`).join('')}</div>
<div class="fdlist">${list.map(f=>{const i=PSTORE.push(L(f.guard))-1;return `<details class="fdag" data-fgk="${f.k}"><summary class="fdhead"><span class="fdi">${f.icon}</span><span class="fdt"><b>${esc(L(f.t))}</b><span class="k">${f.cat}</span></span>${seen[f.k]?'<span class="fdok">✓</span>':''}</summary><div class="fdbody"><p>📖 ${esc(L(f.story))}</p><p><b>🔍 ${ar?'السبب':'Root cause'}:</b> ${esc(L(f.why))}</p><p><b>🛠 ${ar?'الحل':'Fix'}:</b> ${esc(L(f.fix))}</p><div class="fdtask"><b>🛡 ${ar?'السطر اللي يمنعها':'The line that prevents it'}</b><p dir="auto">${esc(L(f.guard))}</p><button class="copy" data-i="${i}">${L(UI.copy)}</button></div></div></details>`}).join('')}</div></section>`}
{const _vc=vCert;vCert=function(){return _vc()+failSection()}}

// ===== 21. Build-along projects on the Module 6 page =====
function baSection(){const ar=LANG==='ar';if(typeof BUILDALONG==='undefined')return '';const st=ST.ba||{};
return `<section class="mergedsec" id="buildalong"><h2>🧱 ${L(UX21.ba)}</h2><p class="k">${ar?'3 مشروعات بتتبني على 5 أيام، كل يوم ليه هدف وخطوات ونقطة مراجعة وبرومبت ماستر. علّم كل يوم لما تخلّصه.':'3 projects built over 5 days — each day has a goal, steps, a checkpoint and a master prompt. Tick each day when you finish it.'}</p>
${BUILDALONG.map(p=>{const d=st[p.k]||[];return `<details class="crcard ${d.length===p.days.length?'open':''}"><summary class="crhead"><span class="cri">${p.icon}</span><span class="crt"><b>${esc(L(p.t))}</b><span class="k">${esc(L(p.d))}</span></span><span class="pkscore ${d.length===p.days.length?'hi':d.length?'mid':'lo'}">${d.length}/${p.days.length}</span></summary><div class="crbody">${p.days.map((x,i)=>`<details class="fdag"><summary class="fdhead"><span class="fdn">${i+1}</span><span class="fdt"><b>${esc(L(x.t))}</b><span class="k">${esc(L(x.goal))}</span></span>${d.includes(i)?'<span class="fdok">✓</span>':''}</summary><div class="fdbody"><ol>${L(x.steps).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="fdtask"><b>🏁 ${ar?'نقطة المراجعة':'Checkpoint'}</b><p>${esc(L(x.check))}</p></div>${promptBox(x.pr)}<label class="fdrun"><input type="checkbox" data-bad="${p.k}|${i}" ${d.includes(i)?'checked':''}> ${ar?'خلّصت اليوم ده':'I finished this day'}</label></div></details>`).join('')}</div></details>`}).join('')}</section>`}

// ===== Studio: remove Saved; merge Fix my real prompt + Re-enhance =====
{const _tabs=vStudioTabs;vStudioTabs=function(){let h=_tabs().replace(/<button class="tab[^"]*" data-stutab="saved">[\s\S]*?<\/button>/,'').replace(/<button class="tab[^"]*" data-stutab="clinic">[\s\S]*?<\/button>/,'').replace(/<button class="tab[^"]*" data-stutab="reenh">[\s\S]*?<\/button>/,'');return h.replace(/<\/div>$/,`<button class="tab ${['fix','clinic','reenh'].includes(stuTab)?'on':''}" data-stutab="fix">🩺 ${L(UX21.fix)}</button></div>`)}}
{const _vs=vStudio;vStudio=function(){if(stuTab==='saved')stuTab='build';if(stuTab==='clinic'||stuTab==='reenh')stuTab='fix';if(stuTab!=='fix')return _vs();crumb(L(UX3.studio)+' › '+L(UX21.fix));const ar=LANG==='ar';
const cur=RE.hist.length?RE.hist[RE.hist.length-1].p:RE.p;const loc=cur.trim()?fxLocal(cur):[];
const diag=`<section class="mergedsec"><h2>🩺 ${ar?'التشخيص':'Diagnosis'}</h2><div class="twocol"><div class="abpane">${loc.length?`<h3>${ar?'مخاطر محتملة':'Likely risks'}</h3><ul class="lint">${loc.map(f=>`<li class="no">✗ <b>${L(f[0])}</b> — ${L(f[3])}</li>`).join('')}</ul>`:`<p class="k">${cur.trim()?(ar?'✓ مفيش مخاطر واضحة.':'✓ No obvious risks.'):(ar?'الصق برومبت فوق.':'Paste a prompt above.')}</p>`}<label class="pbf"><b>${ar?'الرد الوحش اللي طلع (اختياري)':'The bad answer it produced (optional)'}</b><textarea class="search" id="fxo2" rows="4" dir="auto">${esc(FX.out)}</textarea></label><div class="row-btns"><button class="btn-gold" data-fx2="run" ${FX.busy?'disabled':''}>${FX.busy?(ar?'Claude بيشخّص…':'Claude is diagnosing…'):'🩺 '+(ar?'شخّص مع Claude':'Diagnose with Claude')}</button></div><p class="note" id="fxnote"></p></div>
<div class="abpane">${FX.res?`<h3>${ar?'تشخيص Claude':'Claude’s diagnosis'}</h3><div class="tablewrap"><table><tr><th>${ar?'المشكلة':'Failure'}</th><th>${ar?'من البرومبت':'From your prompt'}</th><th>${ar?'العلاج':'Fix'}</th></tr>${(FX.res.failures||[]).map(f=>`<tr><td><b>${esc(f.type)}</b></td><td dir="auto">${esc(f.quote)}</td><td dir="auto">${esc(f.fix)}</td></tr>`).join('')}</table></div><p class="k">${ar?'البرومبت المصلّح اتضاف كنسخة جديدة فوق.':'The fixed prompt was added as a new version above.'}</p>`:`<p class="k">${ar?'Claude هيقولك فين البرومبت بيقع بالظبط، ويضيف نسخة مصلّحة.':'Claude shows exactly where the prompt fails and adds a fixed version.'}</p>`}</div></div></section>`;
return `<h1>🎛 ${L(UX3.studio)}</h1>`+vStudioTabs()+vReenh()+diag}}
async function fixDiag(){const cur=RE.hist.length?RE.hist[RE.hist.length-1].p:RE.p;FX.p=cur;FX.out=(document.getElementById('fxo2')||{}).value||FX.out;await fxRun();if(FX.res&&FX.res.rewrite){RE.hist.push({p:FX.res.rewrite,s:pkScoreFull(FX.res.rewrite).score,by:'claude',changes:(FX.res.failures||[]).map(f=>f.type+': '+f.fix).slice(0,6)});saveRE();render()}}

// ===== My saved prompts → progress hub =====
function savedSection(){const ar=LANG==='ar';return `<section class="careers"><h2>💾 ${L(UX21.saved)} (${ST.mine.length})</h2>${ST.mine.length?`<div class="fdlist">${ST.mine.slice(0,60).map((m,k)=>{const i=PSTORE.push(m.p)-1;return `<details class="fdag"><summary class="fdhead"><span class="fdt"><b>${esc(m.t)}</b><span class="k">${m.d}</span></span></summary><div class="fdbody"><pre dir="auto" class="repre">${esc(m.p)}</pre><div class="row-btns"><button class="copy" data-i="${i}">${L(UI.copy)}</button><button class="tbtn" data-rei="${i}">♻ ${ar?'حسّنه':'Re-enhance'}</button><button class="tbtn" data-stuload="${k}">🎛 ${ar?'افتح في البناء':'Open in Build'}</button><button class="tbtn" data-pbdel="${k}">✕ ${ar?'امسح':'Delete'}</button></div></div></details>`}).join('')}</div><div class="row-btns"><button class="tbtn" data-pbexp="all">⬇ ${ar?'كلهم .md':'All as .md'}</button></div>`:`<p class="k">${ar?'لسه مفيش برومبتات محفوظة — احفظ من الاستوديو أو المساعد.':'No saved prompts yet — save from the Studio or the assistant.'}</p>`}</section>`}
{const _vh=vHub;vHub=function(){return _vh()+savedSection()}}

document.addEventListener('click',e=>{const g=s=>e.target.closest(s);let x;
if(x=g('[data-pg]')){const a=x.dataset.pg;if(a==='run'&&!PG.busy)pgRun();else if(a==='stop'&&PGCTL)PGCTL.abort();else if(a==='clear'){PG.trace=[];PG.out='';savePG();render()}return}
if(x=g('[data-pga]')){if(PGWAIT)PGWAIT(x.dataset.pga==='1');return}
if(x=g('[data-pgs]')){const ar=LANG==='ar';PG.goal=x.textContent;PG.data=x.dataset.d;savePG();render();return}
if(x=g('[data-tmo]')){const [a,i]=x.dataset.tmo.split('|');const n=+i;const s=TEAM.steps;if(a==='up'&&n>0)[s[n-1],s[n]]=[s[n],s[n-1]];if(a==='down'&&n<s.length-1)[s[n+1],s[n]]=[s[n],s[n+1]];if(a==='del'&&s.length>2)s.splice(n,1);if(a==='add'&&s.length<6)s.push({a:'custom',cn:'',cj:'',ho:'',ap:false});saveTEAM();render();return}
if(x=g('[data-tmx]')){if(x.dataset.tmx==='zip')teamZip(x);else saveFile((slug(TEAM.name)||'agent-team')+'.md',teamPrompt(LANG==='ar'?'ar':'en')).then(ok=>{if(ok)x.textContent='✓'});return}
if(x=g('[data-wftab]')){WFTAB=x.dataset.wftab;render();return}
if(x=g('[data-aff]')){AF.field=x.dataset.aff;saveAF();render();return}
if(x=g('[data-af]')){if(!AF.busy)afAsk();return}
if(x=g('[data-rcat]')){RCAT=x.dataset.rcat;render();return}
if(x=g('[data-rmx]')){const r=RECIPES.find(y=>y.k===x.dataset.rmx);if(r){AM={name:L(r.t),rows:L(r.steps).map(s=>({step:s,risk:/send|email|pay|post|file|ابعت|إرسال|دفع|ترحيل/i.test(s)?'high':'low',appr:'',thr:'',ev:''}))};saveAM();WFTAB='matrix';render()}return}
if(x=g('[data-ama]')){AM.rows.push({step:'',risk:'low',appr:'',thr:'',ev:''});saveAM();render();return}
if(x=g('[data-amd]')){AM.rows.splice(+x.dataset.amd,1);saveAM();render();return}
if(x=g('[data-amx]')){if(x.dataset.amx==='md')saveFile('approval-matrix.md',amMD());else saveFile('approval-matrix.csv',BOM+['step,risk,approver,threshold,evidence'].concat(AM.rows.map(r=>[r.step,r.risk,r.appr,r.thr,r.ev].map(csvq).join(','))).join('\n'));return}
if(x=g('[data-rk]')){if(!RK.busy)rkAsk();return}
if(x=g('[data-rkx]')){const rows=rkRows();if(x.dataset.rkx==='csv')saveFile('risk-register.csv',BOM+['risk,category,impact,likelihood,score,control,owner'].concat(rows.map(r=>[r.t,r.cat,r.sev,r.lik,r.sev*r.lik,r.ctrl,r.owner].map(csvq).join(','))).join('\n'));else saveFile('risk-register.md','# Risk register\n\n| Risk | Cat | I | L | Score | Control | Owner |\n|---|---|---|---|---|---|---|\n'+rows.map(r=>`| ${r.t} | ${r.cat} | ${r.sev} | ${r.lik} | ${r.sev*r.lik} | ${r.ctrl} | ${r.owner} |`).join('\n'));return}
if(x=g('[data-m3tab]')){M3TAB=x.dataset.m3tab;render();return}
if(x=g('[data-agc]')){AGC=x.dataset.agc;render();return}
if(x=g('[data-dlk]')){DL2.k=x.dataset.dlk;DL2.sel=[0,1,2];ST.dl2=DL2;saveST();render();return}
if(x=g('[data-bka]')){BK.c.push('#888888');ST.bk=BK;saveST();render();return}
if(x=g('[data-fgc]')){FGC=x.dataset.fgc;render();return}
if(x=g('[data-fx2]')){if(!FX.busy)fixDiag();return}},true);
document.addEventListener('toggle',e=>{const d=e.target;if(d&&d.dataset&&d.dataset.fgk&&d.open){ST.fgSeen=Object.assign({},ST.fgSeen);if(!ST.fgSeen[d.dataset.fgk]){ST.fgSeen[d.dataset.fgk]=1;if(typeof FAILS2!=='undefined'&&Object.keys(ST.fgSeen).length===FAILS2.length)addXP(15);saveST()}}},true);
document.addEventListener('change',e=>{const t=e.target,d=t.dataset||{};
if(t.id==='pgdata'){PG.data=t.value;savePG();return}if(t.id==='pgappr'){PG.appr=t.checked;savePG();return}
if(d.tma!==undefined){TEAM.steps[+d.tma].a=t.value;saveTEAM();render();return}if(d.tmp!==undefined){TEAM.steps[+d.tmp].ap=t.checked;saveTEAM();render();return}
if(d.afk){AF.sel=Object.assign({},AF.sel);if(t.checked)AF.sel[d.afk]={};else delete AF.sel[d.afk];saveAF();render();return}
if(d.rkk){RK.sel=Object.assign({},RK.sel);if(t.checked)RK.sel[d.rkk]={};else delete RK.sel[d.rkk];saveRK();render();return}
if(d.rks){const [k,f]=d.rks.split('|');RK.sel[k][f]=+t.value;saveRK();render();return}
if(d.amr&&t.tagName==='SELECT'){const [i,f]=d.amr.split('|');AM.rows[+i][f]=t.value;saveAM();return}
if(d.wz&&t.tagName==='SELECT'){WZ[d.wz]=t.value;ST.wz=WZ;saveST();render();return}
if(d.br&&t.tagName==='SELECT'){BR[d.br]=t.value;ST.br=BR;saveST();render();return}
if(d.bkc!==undefined){BK.c[+d.bkc]=t.value;ST.bk=BK;saveST();render();return}
if(d.dls!==undefined){const j=+d.dls;DL2.sel=t.checked?DL2.sel.concat(j):DL2.sel.filter(v=>v!==j);ST.dl2=DL2;saveST();render();return}
if(d.bad){const [k,i]=d.bad.split('|');ST.ba=Object.assign({},ST.ba);const a=(ST.ba[k]||[]).slice();const n=+i;if(t.checked&&!a.includes(n)){a.push(n);ST.baXP=Object.assign({},ST.baXP);if(!ST.baXP[k+n]){ST.baXP[k+n]=1;addXP(5)}}if(!t.checked&&a.includes(n))a.splice(a.indexOf(n),1);ST.ba[k]=a;saveST();render();return}});
let _r14t=null;const r14rerender=(sel)=>{clearTimeout(_r14t);_r14t=setTimeout(()=>{const a=document.activeElement;const key=a&&a.getAttribute&&(a.getAttribute('data-'+sel)!==null?sel:null);const val=a&&a.dataset?JSON.stringify(a.dataset):'';const pos=a&&a.selectionStart;render();if(val){const d=JSON.parse(val);const k=Object.keys(d)[0];const n=document.querySelector(`[data-${k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}="${d[k]}"]`);if(n){n.focus();try{n.setSelectionRange(pos,pos)}catch(e){}}}},500)};
document.addEventListener('input',e=>{const t=e.target,d=t.dataset||{};
if(t.id==='pggoal'){PG.goal=t.value;savePG();return}if(d.tmn){TEAM.name=t.value;saveTEAM();return}if(d.tmh!==undefined){TEAM.steps[+d.tmh].ho=t.value;saveTEAM();return}if(d.tmc){const [i,f]=d.tmc.split('|');TEAM.steps[+i][f]=t.value;saveTEAM();return}
if(d.ce){CE[d.ce]=Math.max(0,Number(t.value)||0);ST.ce=CE;saveST();r14rerender('ce');return}
if(d.afm){AF.sel[d.afm].m=Math.max(1,Number(t.value)||1);saveAF();r14rerender('afm');return}if(t.id==='afweek'){AF.week=t.value;saveAF();return}
if(d.amn){AM.name=t.value;saveAM();return}if(d.amr&&t.tagName!=='SELECT'){const [i,f]=d.amr.split('|');AM.rows[+i][f]=t.value;saveAM();return}
if(t.id==='rkdesc'){RK.desc=t.value;saveRK();return}
if(d.wz&&t.tagName!=='SELECT'){WZ[d.wz]=t.value;ST.wz=WZ;saveST();r14rerender('wz');return}if(d.br&&t.tagName!=='SELECT'){BR[d.br]=t.value;ST.br=BR;saveST();r14rerender('br');return}
if(d.bkh!==undefined){BK.c[+d.bkh]=t.value;ST.bk=BK;saveST();if(hexRgb(t.value))r14rerender('bkh');return}if(d.dla){DL2.aud=t.value;ST.dl2=DL2;saveST();r14rerender('dla');return}
if(t.id==='fxo2'){FX.out=t.value;return}});
