// ===== FEATURES 6: merges (progress+card+ROI, quiz+spot), lesson redesign + 60-second lesson, fix-my-prompt clinic, industry editions, field glossary & chains views, field booklets =====
const UX14={hub:T('My progress, card & ROI','تقدّمي والكارت والعائد'),l60:T('Lesson in 60 seconds','الدرس في 60 ثانية'),clinic:T('Fix my real prompt','صلّح برومبتي الحقيقي'),edition:T('Industry edition','نسخة الصناعة'),gloss:T('Field glossary','قاموس المجال'),chain:T('Prompt chain','سلسلة برومبتات'),booklet:T('Field booklet PDF','كتيّب المجال PDF')};

// ---------- merge: progress + achievement card + ROI ----------
var PRTAB='prog';
function vHub(){const ar=LANG==='ar';const tabs=`<div class="tabs big"><button class="tab ${PRTAB==='prog'?'on':''}" data-prtab="prog">🏅 ${L(UX.prog)}</button><button class="tab ${PRTAB==='card'?'on':''}" data-prtab="card">🪪 ${L(UX6.card)}</button><button class="tab ${PRTAB==='roi'?'on':''}" data-prtab="roi">％ ${L(UX4.roi)}</button></div>`;
const body=PRTAB==='card'?vCard():PRTAB==='roi'?vROI():vProg();crumb(L(UX14.hub));return `<h1>🏅 ${L(UX14.hub)}</h1>`+tabs+body.replace(/^<h1>[\s\S]*?<\/h1>/,'')}

// ---------- merge: quiz & flashcards + spot the hallucination ----------
{const _vq=vQuiz;vQuiz=function(m){const ar=LANG==='ar';const spotTab=`<button class="tab ${qMode==='spot'?'on':''}" data-qmode="spot">🔎 ${L(UX11.spot)}</button>`;
if(qMode!=='spot'){const h=_vq(m);return h.replace(/(data-qmode="fc">[^<]*<\/button>)/,'$1'+spotTab)}
crumb(L(UX11.spot));return `<h1>🧠 ${L(UX.quiz)}</h1><div class="tabs"><button class="tab" data-qmode="quiz">${ar?'اختبار':'Quiz'}</button><button class="tab" data-qmode="fc">${ar?'كروت مراجعة':'Flashcards'}</button>${spotTab}</div>`+vSpot().replace(/^<h1>[\s\S]*?<\/h1>/,'')}}

// ---------- 19. lesson page redesign: sticky module TOC + lesson progress ----------
if(!ST.lv)ST.lv={};
const curUnit=()=>{const r=location.hash.slice(1).split('/');return r[0]==='day'&&r[2]?r[2]:null};
function lessonProgress(uid){const seen=(ST.lv[uid]||[]).length;return Math.min(100,Math.round(100*(Math.min(seen,4)/4)*0.8+(DONE.includes(uid)?20:0)))}
{const _vd=vDay;vDay=function(n,uid){const h=_vd(n,uid);if(!uid||PRINT)return h;const d=DAYS.find(x=>x.n==n);if(!d||!d.units.find(x=>x.id==uid))return h;const ar=LANG==='ar';
if(!ST.lv[uid])ST.lv[uid]=[];if(!ST.lv[uid].includes(unitTab)){ST.lv[uid].push(unitTab);saveST()}const lp=lessonProgress(uid);
const toc=`<nav class="ltoc" aria-label="${ar?'دروس الموديول':'Module lessons'}"><div class="k">${L(UI.day)} ${d.n}</div><b>${esc(L(d.t))}</b><ol>${d.units.map(u=>`<li class="${u.id==uid?'cur':''} ${DONE.includes(u.id)?'ok':''}"><a href="#day/${d.n}/${u.id}"><span>${DONE.includes(u.id)?'✓':u.id}</span>${esc(L(u.t))}</a><i style="width:${lessonProgress(u.id)}%"></i></li>`).join('')}</ol><div class="ltools"><button class="tbtn" data-l60="${uid}">⏱ ${L(UX14.l60)}</button></div></nav>`;
const bar=`<div class="lprog"><div><span style="width:${lp}%"></span></div><small>${ar?'تقدّم الدرس':'Lesson progress'} ${lp}% · ${ar?`فتحت ${Math.min((ST.lv[uid]||[]).length,4)} من 4 تبويبات`:`${Math.min((ST.lv[uid]||[]).length,4)} of 4 tabs opened`}${DONE.includes(uid)?(ar?' · ✓ خلص':' · ✓ done'):''}</small></div>`;
return `<div class="lgrid">${toc}<div class="lmain">${bar}${h}</div></div>`}}
function readBar(){const m=document.getElementById('main');if(!m||document.getElementById('readbar'))return;const b=document.createElement('div');b.id='readbar';b.className='readbar';m.prepend(b);m.addEventListener('scroll',()=>{const p=m.scrollHeight>m.clientHeight?m.scrollTop/(m.scrollHeight-m.clientHeight):0;b.style.width=(curUnit()?Math.round(p*100):0)+'%'},{passive:true})}
document.addEventListener('DOMContentLoaded',readBar);setTimeout(readBar,500);

// ---------- 4. Lesson in 60 seconds ----------
let L60={uid:null,i:0,t:null,paused:false};
function l60Frames(uid){const r=unitById(uid);if(!r)return [];const [d,u]=r;const ar=LANG==='ar';const steps=(L(u.steps)||[]).slice(0,4);const tips=(L(u.tips)||[]);const txt=strip(L(u.body)).trim();const first=txt.split(/(?<=[.!؟?])\s/).slice(0,2).join(' ').slice(0,260);const mp=(u.prompts||[]).slice(-1)[0];
return [`<div class="sig">${L(UI.day)} ${d.n} · ${u.dur} ${L(UI.min)}</div><h1>${esc(L(u.t))}</h1><p>${esc(L(d.t))}</p>`,
`<h2>${ar?'الفكرة':'The idea'}</h2><p class="big">${esc(first)}</p>`,
steps.length?`<h2>${ar?'الخطوات':'The steps'}</h2><ol class="l60s">${steps.map(s=>`<li>${esc(strip(s))}</li>`).join('')}</ol>`:`<h2>${ar?'الخطوات':'The steps'}</h2><p>${ar?'افتح الدرس للتفاصيل.':'Open the lesson for details.'}</p>`,
`<h2>${ar?'خلّي بالك':'Remember'}</h2>${tips[0]?`<p class="big">💡 ${esc(strip(tips[0]))}</p>`:''}${CEO[uid]?`<p>👔 ${esc(L(CEO[uid]))}</p>`:''}`,
`<h2>${ar?'جرّبها دلوقتي':'Try it now'}</h2>${mp?`<p class="big">✎ ${esc(L(mp.t))}</p>`:''}<div class="row-btns" style="justify-content:center"><button class="btn-gold" data-l60go="${d.n}/${u.id}">${ar?'افتح الدرس':'Open the lesson'}</button></div>`]}
function l60Open(uid){L60={uid,i:0,t:null,paused:window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches};l60Paint();if(!L60.paused)l60Tick()}
function l60Tick(){clearTimeout(L60.t);L60.t=setTimeout(()=>{const n=l60Frames(L60.uid).length;if(L60.i<n-1){L60.i++;l60Paint();l60Tick()}},12000)}
function l60Paint(){let o=document.getElementById('l60');if(!o){o=document.createElement('div');o.id='l60';o.className='l60ov';o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');document.body.appendChild(o)}const fr=l60Frames(L60.uid);const ar=LANG==='ar';
o.innerHTML=`<div class="l60card" dir="${ar?'rtl':'ltr'}"><div class="l60bars">${fr.map((_,k)=>`<i class="${k<L60.i?'done':k===L60.i?(L60.paused?'done':'run'):''}"></i>`).join('')}</div><div class="l60body">${fr[L60.i]}</div><div class="l60nav"><button class="tbtn" data-l60n="-1" ${L60.i?'':'disabled'}>${ar?'→':'←'}</button><button class="tbtn" data-l60n="p">${L60.paused?'▶':'❚❚'}</button><button class="tbtn" data-l60n="1" ${L60.i<fr.length-1?'':'disabled'}>${ar?'←':'→'}</button><button class="tbtn" data-l60n="x">✕</button></div></div>`;
const b=o.querySelector('.l60body');if(b)b.focus&&b.focus()}
function l60Close(){clearTimeout(L60.t);const o=document.getElementById('l60');if(o)o.remove();L60.uid=null}

// ---------- 13. Fix my real prompt (Studio tab) ----------
let FX=Object.assign({p:'',out:'',res:null,busy:false},ST.fx||{});
function pkScoreFull(text){text=String(text||'');const tag=k=>{const m=text.match(new RegExp(`<${k}>([\\s\\S]*?)</${k}>`));return m?m[1].trim():''};const hasXml=/<role>|<task>|<context>/.test(text);const keep=SU;
SU=Object.assign({},keep,hasXml?{goal:'',role:tag('role'),task:tag('task'),context:tag('context'),reasoning:tag('reasoning'),stop:tag('stop_when'),output:tag('output_format')}:{goal:'',role:'',task:text.split('\n')[0],context:text,reasoning:'',stop:'',output:''},{tech:[hasXml?'xml':'',/clarif|اسأل/i.test(text)?'ask':'',/verify|check every number|راجع/i.test(text)?'verify':''].filter(Boolean)});
let s;try{s=suScore()}finally{SU=keep}return s}
function fxLocal(p){const t=p.toLowerCase();const out=[];const has=re=>re.test(t);
if(!has(/only use|use only|attached|مرفق|بس من|استخدم .*بس/))out.push(FAILS[0]);if(!has(/<stop_when>|max|under|at most|أقل من|بالكتير|حد أقصى/))out.push(FAILS[1]);if(!has(/<output_format>|table|json|format|جدول|شكل/))out.push(FAILS[2]);if(!has(/review|flag|human|مراجعة|علّم/))out.push(FAILS[4]);if(!has(/arabic|english|عربي|إنجليزي|بالعربي/))out.push(FAILS[6]);return out}
function vClinic(){const ar=LANG==='ar';const s=FX.p.trim()?pkScoreFull(FX.p):null;const loc=FX.p.trim()?fxLocal(FX.p):[];
let h=`<p class="lede">${ar?'الصق برومبت حقيقي من شغلك (ولو عندك الرد الوحش اللي طلع، الصقه كمان). هتاخد تشخيص فوري، وبعدين Claude يشخّص ويعيد الكتابة.':'Paste a real prompt from your work (and the bad answer it produced, if you have it). You get an instant diagnosis, then Claude diagnoses it and rewrites it.'}</p>
<div class="twocol"><div class="abpane"><label class="pbf"><b>${ar?'البرومبت بتاعك':'Your prompt'}</b><textarea class="search" id="fxp" rows="10" dir="auto">${esc(FX.p)}</textarea></label><label class="pbf"><b>${ar?'الرد اللي جالك (اختياري)':'The answer you got (optional)'}</b><textarea class="search" id="fxo" rows="5" dir="auto">${esc(FX.out)}</textarea></label>
<div class="row-btns"><button class="btn-gold" data-fx="run" ${FX.busy?'disabled':''}>${FX.busy?(ar?'Claude بيشخّص…':'Claude is diagnosing…'):'🩺 '+(ar?'شخّص وأعد الكتابة مع Claude':'Diagnose & rewrite with Claude')}</button><button class="tbtn" data-fx="clear">${ar?'امسح':'Clear'}</button></div><p class="note" id="fxnote"></p></div>
<div class="abpane"><h3>${ar?'تشخيص فوري':'Instant diagnosis'}</h3>${s?`<div class="rxscore" style="margin-bottom:10px">${ring(s.score)}</div><div class="bars" style="display:grid;grid-template-columns:1fr;gap:4px">${s.el.map((e,k)=>`<div class="bar2"><span>${['Role','Task','Context','Reasoning','Stop','Output'][k]}</span><i><em style="width:${e.p}%;background:${e.p>=60?'var(--green)':e.p>=30?'var(--gold)':'var(--red)'}"></em></i></div>`).join('')}</div>${loc.length?`<h3 style="margin-top:12px">${ar?'مخاطر محتملة':'Likely risks'}</h3><ul class="lint">${loc.map(f=>`<li class="no">✗ <b>${L(f[0])}</b> — ${L(f[3])}</li>`).join('')}</ul>`:''}`:`<p class="k">${ar?'الصق برومبت علشان تشوف التشخيص.':'Paste a prompt to see the diagnosis.'}</p>`}</div></div>`;
if(FX.res){const r=FX.res;const after=pkScore(r.rewrite||'');h+=`<h2>${ar?'تشخيص Claude':'Claude’s diagnosis'}</h2><div class="tablewrap"><table><tr><th>${ar?'المشكلة':'Failure'}</th><th>${ar?'من البرومبت':'From your prompt'}</th><th>${ar?'العلاج':'Fix'}</th></tr>${(r.failures||[]).map(f=>`<tr><td><b>${esc(f.type||'')}</b></td><td dir="auto">${esc(f.quote||'')}</td><td dir="auto">${esc(f.fix||'')}</td></tr>`).join('')}</table></div>
<h2>${ar?'البرومبت بعد التصليح':'The fixed prompt'} <span class="pkscore ${after>=80?'hi':after>=55?'mid':'lo'}">${s?s.score:'?'} → ${after}</span></h2>${promptBox({t:T('Rewritten prompt','البرومبت بعد إعادة الكتابة'),p:r.rewrite||''})}<div class="row-btns"><button class="btn-gold" data-fx="save">💾 ${ar?'احفظ في برومبتاتي':'Save to My prompts'}</button><button class="tbtn" data-fx="studio">🎛 ${ar?'افتحه في الاستوديو':'Open in the studio'}</button></div>`}
return h}
async function fxRun(){const ar=LANG==='ar';const n=t=>{const e=document.getElementById('fxnote');if(e)e.textContent=t};if(!FX.p.trim()){n(ar?'الصق البرومبت الأول.':'Paste your prompt first.');return}
const sample=await tutorSample();if(!sample){n(ar?'التشخيص مع Claude بيشتغل لما المنصة تتفتح جوه Claude (claude.ai).':'Diagnosis with Claude works when the platform is opened inside Claude (claude.ai).');return}
FX.busy=true;render();
const ask=`You are a prompt engineering coach for business professionals in Egypt and the Gulf. Diagnose the prompt below using these failure types: made-up numbers, missed constraint, wrong format, ignored part of the file, over-confident advice, stale facts, language drift, plus missing role, vague task, missing context. Quote the exact words in the prompt that cause each failure. Then rewrite it as a master prompt with the XML blocks <role>, <task>, <context>, <reasoning>, <stop_when>, <output_format>, keeping every fact from the original and putting unknowns in [brackets]. Write types, fixes and the rewrite in ${ar?'Egyptian Arabic for explanations (rewrite in the same language as the original prompt)':'English (rewrite in the same language as the original prompt)'}. Reply with JSON only: {"failures":[{"type":"","quote":"","fix":""}],"rewrite":""}\n\nPROMPT:\n${FX.p.slice(0,6000)}${FX.out.trim()?`\n\nANSWER IT PRODUCED:\n${FX.out.slice(0,3000)}`:''}`;
try{const j=await sample.json(ask,{modelTier:'default'});if(!j||typeof j.rewrite!=='string')throw new Error('shape');FX.res={failures:(j.failures||[]).slice(0,10).map(f=>({type:String(f.type||''),quote:String(f.quote||''),fix:String(f.fix||'')})),rewrite:j.rewrite};addXP(5)}
catch(e){FX.res=null;n(e&&e.code==='rate_limited'?(ar?'طلبات كتير — جرّب بعد شوية.':'Too many requests — try again in a moment.'):(ar?'مقدرتش أشخّص دلوقتي. جرّب تاني.':'Could not diagnose right now. Try again.'))}
FX.busy=false;saveFX();render()}
function saveFX(){const {busy,...r}=FX;ST.fx=r;saveST()}
{const _tabs=vStudioTabs;vStudioTabs=function(){return _tabs().replace(/<\/div>$/,`<button class="tab ${stuTab==='clinic'?'on':''}" data-stutab="clinic">🩺 ${L(UX14.clinic)}</button></div>`)}}
{const _vs=vStudio;vStudio=function(){if(stuTab!=='clinic')return _vs();crumb(L(UX3.studio)+' › '+L(UX14.clinic));return `<h1>🎛 ${L(UX3.studio)}</h1>`+vStudioTabs()+vClinic()}}

// ---------- 8. Industry editions for the field library ----------
const INDS=[['general',T('General','عام'),'🏢'],
['banking',T('Banking','البنوك'),'🏦',T('a bank in Egypt or the Gulf','بنك في مصر أو الخليج'),T('NIM, cost-to-income, NPL ratio, CASA ratio, capital adequacy','صافي هامش الفايدة، نسبة التكلفة للدخل، نسبة القروض المتعثرة، نسبة الحسابات الجارية والتوفير، كفاية رأس المال'),T('core banking extracts, loan book, branch data','استخراجات النظام البنكي، محفظة القروض، بيانات الفروع'),T('central bank circulars (CBE / SAMA / CBUAE) — paste the current text','منشورات البنك المركزي (المصري / ساما / الإماراتي) — الصق النص الحالي')],
['fmcg',T('FMCG','السلع الاستهلاكية'),'🛍',T('an FMCG manufacturer or distributor','مصنّع أو موزع سلع استهلاكية'),T('sell-in vs sell-out, numeric distribution, out-of-stock rate, trade spend %, gross margin by SKU','المبيعات للموزع مقابل المستهلك، الانتشار الرقمي، نسبة النفاد، نسبة الإنفاق التجاري، الهامش لكل صنف'),T('distributor sales, retail audit, promotions calendar','مبيعات الموزعين، مراجعة منافذ التجزئة، تقويم العروض'),T('consumer protection and pricing rules — paste the current text','قواعد حماية المستهلك والتسعير — الصق النص الحالي')],
['realestate',T('Real estate','العقارات'),'🏗',T('a real estate developer','مطور عقاري'),T('units sold, collections vs instalments due, cancellation rate, construction progress %, cost per m²','الوحدات المباعة، التحصيل مقابل الأقساط المستحقة، نسبة الإلغاء، نسبة تقدم الإنشاء، التكلفة للمتر'),T('sales and instalment schedules, contractor progress reports, land and permit files','جداول البيع والأقساط، تقارير تقدم المقاولين، ملفات الأرض والتراخيص'),T('real estate registration and off-plan sales rules — paste the current text','قواعد التسجيل العقاري والبيع على الخريطة — الصق النص الحالي')],
['healthcare',T('Healthcare','الرعاية الصحية'),'🏥',T('a private hospital or clinic group','مجموعة مستشفيات أو عيادات خاصة'),T('bed occupancy, average length of stay, claim rejection rate, revenue per patient, wait time','نسبة إشغال الأسرّة، متوسط مدة الإقامة، نسبة رفض المطالبات، الإيراد لكل مريض، وقت الانتظار'),T('admissions, insurance claims, pharmacy sales — anonymised','الدخول، مطالبات التأمين، مبيعات الصيدلية — من غير بيانات تعريفية'),T('health regulator and patient-data rules — paste the current text; never include patient identities','قواعد الجهة الصحية وبيانات المرضى — الصق النص الحالي؛ وعمرك ما تحط هوية مريض')],
['government',T('Government','الجهات الحكومية'),'🏛',T('a government entity or public authority','جهة حكومية أو هيئة عامة'),T('service time, budget execution %, citizen satisfaction, project milestones on time','وقت الخدمة، نسبة تنفيذ الموازنة، رضا المواطنين، المراحل في ميعادها'),T('budget execution reports, service logs, project plans','تقارير تنفيذ الموازنة، سجلات الخدمات، خطط المشروعات'),T('public procurement, data classification and approved-tools rules — paste the current text','قواعد المشتريات الحكومية وتصنيف البيانات والأدوات المعتمدة — الصق النص الحالي')]];
let IND=ST.ind||'general';
function applyInd(text,lang){if(IND==='general')return text;const i=INDS.find(x=>x[0]===IND);if(!i)return text;const ar=lang==='ar';
const ctx=ar?`\n- الصناعة: ${i[3].ar}\n- مؤشرات الصناعة اللي تستخدمها لو مناسبة: ${i[4].ar}\n- بيانات الصناعة المعتادة: ${i[5].ar}\n- القواعد: ${i[6].ar}`:`\n- Industry: ${i[3].en}\n- Industry KPIs to use where relevant: ${i[4].en}\n- Typical industry data: ${i[5].en}\n- Rules: ${i[6].en}`;
return text.replace(/<\/role>/,(ar?` — قطاع ${i[1].ar}`:` — ${i[1].en} sector`)+'</role>').replace(/\n<\/context>/,ctx+'\n</context>')}
const indP=p=>T(applyInd(p.en,'en'),applyInd(p.ar,'ar'));

// ---------- 10. field glossary + 7. prompt chains (views inside the field library) ----------
function glossLink(html,k){const g=(FGLOSS[k]||[]).slice().sort((a,b)=>b[LANG==='ar'?1:0].length-a[LANG==='ar'?1:0].length);if(!g.length)return html;const ar=LANG==='ar';
return html.replace(/(<pre[^>]*>)([\s\S]*?)(<\/pre>)/g,(m,a,body,c)=>{let b=body;g.forEach(([en,arT])=>{const term=ar?arT:en;const other=ar?en:arT;const safe=esc(term).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const re=ar?new RegExp(`(^|[\\s(«“])(${safe})(?=[\\s،.؛:)»”]|$)`,'g'):new RegExp(`(^|[^\\w>])(${safe})(?=[^\\w<]|$)`,'gi');b=b.replace(re,(mm,p1,p2)=>`${p1}<abbr class="gl" title="${esc(other)}">${p2}</abbr>`)});return a+b+c})}
function glossSection(k){const g=FGLOSS[k]||[];if(!g.length)return '';const ar=LANG==='ar';return `<details class="case fgl"><summary><h3>📖 ${L(UX14.gloss)} (${g.length})</h3><div class="k">${ar?'المصطلحات دي متعلّمة في البرومبتات — حط الماوس عليها تشوف الترجمة.':'These terms are marked in the prompts — hover to see the translation.'}</div></summary><div class="tablewrap"><table><tr><th>English</th><th>العربية</th></tr>${g.map(t=>`<tr><td dir="ltr">${esc(t[0])}</td><td>${esc(t[1])}</td></tr>`).join('')}</table></div></details>`}
function chainSection(k){const c=CHAINS[k];if(!c)return '';const ar=LANG==='ar';
return `<h2>🔗 ${L(UX14.chain)}: ${esc(L(c.t))}</h2><p class="note">${ar?'كل خطوة بتستخدم مخرج الخطوة اللي قبلها — الصقه مكان [مخرج الخطوة].':'Each step uses the output of the previous one — paste it where it says [output of step].'}</p><ol class="chain">${c.steps.map((s,i)=>`<li><div class="chn">${i+1}</div><div class="chb">${glossLink(promptBox({t:s.t,p:indP(s.p)}),k)}</div></li>`).join('')}</ol><div class="row-btns"><button class="tbtn" data-chcopy="${k}">⧉ ${ar?'انسخ السلسلة كلها':'Copy the whole chain'}</button><button class="tbtn" data-chpack="${k}">📦 ${ar?'السلسلة للسلة':'Chain to basket'}</button></div>`}
{const _vf=vFields;vFields=function(){let h=_vf();const ar=LANG==='ar';const f=fieldOf(FLK);
const ed=`<div class="indbar"><span class="k">${L(UX14.edition)}:</span>${INDS.map(i=>`<button class="chip ${IND===i[0]?'on':''}" data-ind="${i[0]}">${i[2]} ${L(i[1])}</button>`).join('')}</div>${IND!=='general'?(()=>{const i=INDS.find(x=>x[0]===IND);return `<div class="indnote"><b>${i[2]} ${L(i[1])}</b> — ${ar?'المؤشرات':'KPIs'}: ${esc(L(i[4]))} · ${ar?'البيانات':'Data'}: ${esc(L(i[5]))} · ${ar?'القواعد':'Rules'}: ${esc(L(i[6]))}</div>`})():''}`;
h=h.replace('<div class="ftasks">',ed+'<div class="ftasks">');
// rebuild prompts with the edition + glossary links
const i=h.indexOf('<h2>⚗');const extra=chainSection(f.k)+glossSection(f.k)+`<div class="row-btns" style="margin:14px 0"><button class="btn-gold" data-booklet="${f.k}">📘 ${L(UX14.booklet)}</button></div>`;
h=i>0?h.slice(0,i)+extra+h.slice(i):h+extra;return glossLink(h,f.k)}}
{const _vt=vTracks;vTracks=function(){const h=_vt();return h.replace(`<button class="tbtn" data-recipe="${FLK}">`,`<button class="tbtn" data-booklet="${FLK}">📘 ${L(UX14.booklet)}</button><button class="tbtn" data-recipe="${FLK}">`)}}

// ---------- 20. Field booklet (multi-page PDF) ----------
async function multiPagePDF(blocks,filename,onp){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js',()=>window.html2canvas);await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js',()=>window.jspdf&&window.jspdf.jsPDF);
const pdf=new window.jspdf.jsPDF({unit:'pt',format:'a4',orientation:'portrait'});const PW=pdf.internal.pageSize.getWidth(),PH=pdf.internal.pageSize.getHeight();const M=28,W=794,CH=Math.floor((PH-2*M)*W/(PW-2*M));
const css=document.querySelector('style').textContent;let first=true,page=0;
for(let bi=0;bi<blocks.length;bi++){if(onp)onp(bi,blocks.length);const fr=document.createElement('iframe');fr.style.cssText='position:absolute;left:-12000px;top:0;width:'+W+'px;height:1200px;border:0';document.body.appendChild(fr);
fr.srcdoc=`<!doctype html><html lang="${LANG}" dir="${LANG==='ar'?'rtl':'ltr'}" data-theme="light"><head><meta charset="utf-8"><link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@300;400;500;600;700&family=Amiri:wght@700&display=swap" rel="stylesheet"><style>${css} html,body{background:#fff;height:auto;overflow:visible;margin:0}.exdoc{padding:22px 26px}.exdoc pre{white-space:pre-wrap}.bkl div{display:flex;gap:8px;margin:3px 0}.bkl b{color:#9C7614;min-width:18px}</style></head><body>${blocks[bi]}</body></html>`;
await new Promise(r=>fr.onload=r);try{await fr.contentDocument.fonts.ready}catch(e){}await new Promise(r=>setTimeout(r,250));const body=fr.contentDocument.body;const H=body.scrollHeight;fr.style.height=H+'px';
const cv=await html2canvas(body,{scale:2,backgroundColor:'#ffffff',foreignObjectRendering:true,windowWidth:W,width:W,height:H});fr.remove();
for(let y=0;y<H;y+=CH){const h=Math.min(CH,H-y);const part=document.createElement('canvas');part.width=cv.width;part.height=Math.ceil(h*2);part.getContext('2d').drawImage(cv,0,y*2,cv.width,h*2,0,0,cv.width,h*2);
if(!first)pdf.addPage();first=false;page++;pdf.addImage(part.toDataURL('image/jpeg',0.88),'JPEG',M,M,PW-2*M,h*(PW-2*M)/W);pdf.setFontSize(8);pdf.setTextColor(130);pdf.text(`Claude Mastery · ${page}`,PW/2,PH-12,{align:'center'})}}
await saveFile(filename,pdf.output('blob'))}
function bookletBlocks(k){const f=fieldOf(k);const ar=LANG==='ar';const dir=ar?'rtl':'ltr';const wrap=x=>`<div class="exdoc" dir="${dir}">${x}</div>`;const pre=t=>`<pre dir="auto" style="background:#EEF2F7;border-radius:8px;padding:10px;font-size:11px;line-height:1.55">${esc(t)}</pre>`;
const ind=INDS.find(x=>x[0]===IND);const blocks=[];
blocks.push(wrap(`<div style="background:#13284B;color:#fff;border-radius:16px;padding:40px 36px;min-height:960px;display:flex;flex-direction:column;justify-content:space-between"><div><div style="color:#F1D27A;font-size:22px;font-weight:600">Claude Mastery · ${ar?'د. سارة سالم':'Dr. Sara Salem'}</div><h1 style="color:#fff;font-size:44px;margin:24px 0 8px">${f.icon} ${esc(L(f.t))}</h1><p style="color:#C7D1E2;font-size:20px">${ar?'كتيّب المجال: الدروس، المهام، سلسلة البرومبتات، القاموس، وكارت الوصفات':'Field booklet: lessons, tasks, prompt chain, glossary and recipe card'}${IND!=='general'?` · ${esc(L(ind[1]))}`:''}</p></div><div style="display:flex;justify-content:space-between;align-items:flex-end"><div style="color:#C7D1E2">${(ST.profile&&ST.profile.name)||ST.name||''}<br>${new Date().toISOString().slice(0,10)}</div><div class="qr" style="width:120px">${QR_PLATFORM}</div></div></div>`));
blocks.push(wrap(`<h1>📘 ${ar?'دروس المسار':'Track lessons'}</h1>`+trackLessons(k).map(id=>{const [d,u]=unitById(id);const st=(L(u.steps)||[]);return `<h2 style="margin-top:16px">${u.id} · ${esc(L(u.t))}</h2>${CEO[id]?`<div class="ceobox">👔 ${esc(L(CEO[id]))}</div>`:''}${st.length?`<div class="bkl">${st.map((x,i)=>`<div><b>${i+1}.</b> ${esc(strip(x))}</div>`).join('')}</div>`:''}`}).join('')));
f.tasks.forEach(t=>blocks.push(wrap(`<div class="k">${esc(L(CAD[t.c]))}</div><h1>${esc(L(t.t))}</h1>${pre(L(indP(t.p)))}<h3>${ar?'مثال لمخرج متكامل':'Example of a finished output'}</h3>${pre(L(t.ex))}`)));
const c=CHAINS[k];if(c)blocks.push(wrap(`<h1>🔗 ${esc(L(c.t))}</h1>`+c.steps.map((s,i)=>`<h3>${i+1}. ${esc(L(s.t))}</h3>${pre(L(indP(s.p)))}`).join('')));
const g=FGLOSS[k]||[];if(g.length)blocks.push(wrap(`<h1>📖 ${L(UX14.gloss)}</h1><table><tr><th>English</th><th>العربية</th></tr>${g.map(x=>`<tr><td dir="ltr">${esc(x[0])}</td><td>${esc(x[1])}</td></tr>`).join('')}</table>`));
blocks.push(recipeHTML(k));return blocks}
async function bookletDownload(k,btn){const old=btn.textContent;btn.disabled=true;try{await multiPagePDF(bookletBlocks(k),`Field-booklet-${fieldOf(k).t.en.replace(/[^A-Za-z]+/g,'-')}-${LANG.toUpperCase()}.pdf`,(i,n)=>{btn.textContent=`${LANG==='ar'?'جاري':'Working'} ${i+1}/${n}…`});btn.textContent='✓'}catch(e){console.error(e);btn.textContent=LANG==='ar'?'حصلت مشكلة':'Failed'}btn.disabled=false;setTimeout(()=>btn.textContent=old,2500)}

// ---------- events ----------
document.addEventListener('click',e=>{const g=s=>e.target.closest(s);let x;
if(x=g('[data-prtab]')){PRTAB=x.dataset.prtab;render();return}
if(x=g('[data-tab]')){const u=curUnit();if(u){const t=x.dataset.tab;if(!ST.lv[u])ST.lv[u]=[];if(!ST.lv[u].includes(t)){ST.lv[u].push(t);saveST()}}}
if(x=g('[data-l60]')){l60Open(x.dataset.l60);return}
if(x=g('[data-l60n]')){const a=x.dataset.l60n;const n=l60Frames(L60.uid).length;if(a==='x'){l60Close();return}if(a==='p'){L60.paused=!L60.paused;if(L60.paused)clearTimeout(L60.t);else l60Tick();l60Paint();return}L60.i=Math.max(0,Math.min(n-1,L60.i+(+a)));l60Paint();if(!L60.paused)l60Tick();return}
if(x=g('[data-l60go]')){l60Close();go('day/'+x.dataset.l60go);return}
if(x=g('[data-fx]')){const a=x.dataset.fx;if(a==='run'&&!FX.busy)fxRun();if(a==='clear'){FX={p:'',out:'',res:null,busy:false};saveFX();render()}if(a==='save'&&FX.res){ST.mine.unshift({t:(FX.p.split('\n')[0]||'Fixed prompt').slice(0,80),d:new Date().toISOString().slice(0,10),p:FX.res.rewrite});saveST();addXP(5);const n=document.getElementById('fxnote');if(n)n.textContent=LANG==='ar'?'اتحفظ.':'Saved.'}if(a==='studio'&&FX.res){SU.goal='';SU.task=(FX.p.split('\n')[0]||'').slice(0,120);SU.context=FX.res.rewrite;stuTab='build';saveSU();render()}return}
if(x=g('[data-ind]')){IND=x.dataset.ind;ST.ind=IND;saveST();render();return}
if(x=g('[data-chcopy]')){const c=CHAINS[x.dataset.chcopy];const t=c.steps.map((s,i)=>`### ${i+1}. ${L(s.t)}\n\n${L(indP(s.p))}`).join('\n\n---\n\n');(navigator.clipboard?navigator.clipboard.writeText(t):Promise.reject()).then(()=>{x.textContent='✓'},()=>{x.textContent=LANG==='ar'?'مقدرتش أنسخ':'Copy failed'});return}
if(x=g('[data-chpack]')){const k=x.dataset.chpack;CHAINS[k].steps.forEach((s,i)=>pkAdd(`${L(CHAINS[k].t)} · ${i+1}. ${L(s.t)}`,indP(s.p)));return}
if(x=g('[data-booklet]')){bookletDownload(x.dataset.booklet,x);return}});
document.addEventListener('keydown',e=>{if(!L60.uid)return;if(e.key==='Escape')l60Close();if(e.key==='ArrowRight'||e.key==='ArrowLeft'){const dir=(e.key==='ArrowRight')!==(LANG==='ar')?1:-1;const n=l60Frames(L60.uid).length;L60.i=Math.max(0,Math.min(n-1,L60.i+dir));l60Paint();if(!L60.paused)l60Tick()}});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='fxp'){FX.p=t.value;clearTimeout(window._fxT);window._fxT=setTimeout(()=>{saveFX();if(document.activeElement===t){const pos=t.selectionStart;render();const el=document.getElementById('fxp');if(el){el.focus();el.setSelectionRange(pos,pos)}}},700)}if(t.id==='fxo'){FX.out=t.value;saveFX()}});
