// ---------- Round 17: fill-the-blank drills, practice data packs, handoff game, Skill from a chat, plugin gallery, skills & badges card, certificate verification ----------
const UX23={drill:T('Fill-the-blank drills','تمارين املا الفراغ'),data:T('Practice data','بيانات للتدريب'),hand:T('Handoff game','لعبة التسليم بين الوكلاء'),chat:T('Skill from a chat','Skill من محادثة'),gal:T('Ready plugin bundles by department','باقات Plugins جاهزة حسب الإدارة'),card2:T('Skills & badges card','كارت المهارات والشارات'),verify:T('Verify a certificate','تحقق من شهادة')};
const MPTAGS=['role','task','context','reasoning','stop_when','output_format'];
const MPTAGN={role:T('Role','الدور'),task:T('Task','المهمة'),context:T('Context','السياق'),reasoning:T('Reasoning','طريقة التفكير'),stop_when:T('Stop when','امتى يقف'),output_format:T('Output format','شكل المخرج')};
const mpPart=(p,k)=>((p.match(new RegExp('<'+k+'>([\\s\\S]*?)</'+k+'>'))||[])[1]||'').trim();
const kw=s=>new Set(asNorm(s).split(/[^\p{L}\p{N}]+/u).filter(w=>w.length>3&&!AS_STOP.has(w)).map(asStem));

// ===== 10. Fill-the-blank drills (Studio tab) =====
function drillPool(){const o=[];Object.entries(FAG).forEach(([k,F])=>(F.agents||[]).forEach(a=>o.push({fk:k,a,fin:false})));FD.forEach(f=>f.agents.forEach(a=>o.push({fk:f.k,a,fin:true})));return o}
let DR=Object.assign({i:-1,hide:'context',ans:'',res:null,ai:null,busy:false},ST.dr||{});DR.busy=false;
function saveDR(){ST.dr=Object.assign({},DR,{busy:false});saveST()}
function drPrompt(){const P=drillPool();if(DR.i<0||DR.i>=P.length)DR.i=Math.floor(Math.random()*P.length);const x=P[DR.i];const f=x.fin?FD.find(y=>y.k===x.fk):fagField(x.fk);return {x,f,p:fdPrompt(x.a,f,LANG)}}
const DRRULE={role:[[s=>s.length>=40,T('At least one full sentence (40+ characters)','جملة كاملة على الأقل (40 حرف أو أكتر)')],[s=>/(you are|act as|إنت|انت|أنت)/i.test(s),T('Says who Claude is ("You are…")','بتقول Claude مين («إنت…»)')],[s=>s.split(/[.!؟?]\s+/).filter(x=>x.trim().length>12).length>=2,T('Adds background: expertise, audience or market','بتضيف خلفية: الخبرة أو الجمهور أو السوق')]],
task:[[s=>s.length>=25,T('Clear sentence (25+ characters)','جملة واضحة (25 حرف أو أكتر)')],[s=>s.length<=350,T('One focused job (under 350 characters)','مهمة واحدة مركّزة (أقل من 350 حرف)')],[s=>s.trim().split(/\s+/).length>=6,T('Specific: what, for whom or from which data (6+ words)','محددة: إيه، لمين، أو من أنهي بيانات (6 كلمات أو أكتر)')]],
context:[[s=>(s.match(/^\s*[-•]\s/gm)||[]).length>=3,T('3+ bullet lines','3 نقط أو أكتر')],[s=>/\[[^\]]+\]|\d/.test(s),T('Concrete details or [placeholders]','تفاصيل محددة أو [خانات]')],[s=>/(never|don't|do not|only|must|ممنوع|متعملش|بس|لازم)/i.test(s),T('At least one guardrail','ضابط واحد على الأقل')]],
reasoning:[[s=>(s.match(/^\s*\d+[.)]/gm)||[]).length>=3,T('3+ numbered steps','3 خطوات مرقّمة أو أكتر')],[s=>(s.match(/^\s*\d+[.)]/gm)||[]).length>=4,T('A full method (4+ steps)','طريقة كاملة (4 خطوات أو أكتر)')],[s=>s.length>=80,T('Enough detail (80+ characters)','تفاصيل كفاية (80 حرف أو أكتر)')]],
stop_when:[[s=>s.length>=40,T('Clear enough (40+ characters)','واضحة كفاية (40 حرف أو أكتر)')],[s=>/\d|(all |every|match|reconcil|deliver|complete|done|كل|متطابق|اتسلّم|خلص|اكتمل)/i.test(s),T('A finish line you can check (a number or “all … done”)','خط نهاية تقدر تتأكد منه (رقم أو «كل … خلص»)')],[s=>/(ask|approv|missing|human|beyond|scope|do not|don't|never|open question|اسأل|موافقة|ناقص|شخص|ما تتعداش|متتعداش|ممنوع|الأسئلة المفتوحة)/i.test(s),T('A limit: when to stop, ask or hand over','حد: امتى يقف أو يسأل أو يسلّم')]],
output_format:[[s=>/(table|section|heading|bullet|json|csv|summary|جدول|قسم|عناوين|نقط|ملخص|سطور)/i.test(s)||/^\s*[-•]\s/m.test(s),T('Names a structure (table, sections…)','بتحدد شكل (جدول، أقسام…)')],[s=>/\d/.test(s),T('Sets a length or count','بتحدد طول أو عدد')],[s=>s.length>=40,T('Enough detail (40+ characters)','تفاصيل كفاية (40 حرف أو أكتر)')]]};
function drLocal(ans,orig,tag){const rules=DRRULE[tag].map(r=>[r[1],r[0](ans)]);const a=kw(ans),o=kw(orig);const ov=o.size?[...o].filter(w=>a.has(w)).length/o.size:0;const score=Math.round(rules.filter(r=>r[1]).length/rules.length*70+Math.min(1,ov*2.5)*30);return {rules,ov:Math.round(ov*100),score}}
function vDrill(){const ar=LANG==='ar';const {x,f,p}=drPrompt();const tag=DR.hide;const orig=mpPart(p,tag);const shown=p.replace(new RegExp('(<'+tag+'>)[\\s\\S]*?(</'+tag+'>)'),'$1\n▢▢▢ '+(ar?'اكتب الجزء ده':'YOUR PART GOES HERE')+' ▢▢▢\n$2');const R=DR.res;const done=Object.keys(ST.drDone||{}).length;
return `<section class="mergedsec"><h2>🧩 ${L(UX23.drill)}</h2><p class="k">${ar?'برومبت ماستر حقيقي من مكتبة الوكلاء ناقصه جزء. اكتبه إنت، وبعدين قارن بالنسخة الأصلية. التقييم المحلي بيبص على القواعد، وClaude بيقيّم المعنى.':'A real master prompt from the agent library with one part missing. Write it yourself, then compare with the original. The instant check looks at the rules; Claude grades the meaning.'} <b>${ar?'خلّصت':'Done'}: ${done}</b></p>
<div class="chips">${MPTAGS.map(t=>`<button class="chip ${tag===t?'on':''}" data-drh="${t}">${esc(L(MPTAGN[t]))}</button>`).join('')}<button class="chip" data-drn="1">🎲 ${ar?'برومبت تاني':'Another prompt'}</button></div>
<p class="k">${esc(x.a.n?L(x.a.n):'')} · ${f.icon||''} ${esc(L(f.t))}</p>
<div class="twocol"><div class="abpane"><pre class="testout" dir="auto" style="max-height:420px">${esc(shown)}</pre></div>
<div class="abpane"><label class="pbf"><b>&lt;${tag}&gt; — ${ar?'اكتب الجزء الناقص':'write the missing part'}</b><textarea class="search" id="drans" rows="9" dir="auto">${esc(DR.ans)}</textarea></label>
<div class="row-btns"><button class="btn-gold" data-dra="check">✓ ${ar?'قيّم إجابتي':'Check my answer'}</button><button class="tbtn" data-dra="ai" ${DR.busy?'disabled':''}>${DR.busy?'…':'✨ '+(ar?'تقييم Claude':'Claude’s grade')}</button><button class="tbtn" data-dra="show">👁 ${ar?'اعرض الأصل':'Show the original'}</button></div><p class="note" id="drnote"></p>
${R?`<div class="stu-dash" style="grid-template-columns:1fr"><div><span class="pkscore ${R.score>=80?'hi':R.score>=60?'mid':'lo'}">${R.score}</span> <b>${ar?'التقييم المحلي':'Instant check'}</b> · ${ar?'تغطية أفكار الأصل':'Covers the original’s ideas'}: ${R.ov}%</div><ul class="lint">${R.rules.map(r=>`<li class="${r[1]?'ok':'no'}">${r[1]?'✓':'✗'} ${esc(L(r[0]))}</li>`).join('')}</ul></div>`:''}
${DR.ai?`<div class="abpane"><h3>✨ Claude: ${DR.ai.score}/100</h3>${DR.ai.good.length?`<p><b>${ar?'كويس':'Good'}:</b> ${DR.ai.good.map(esc).join(' · ')}</p>`:''}${DR.ai.missing.length?`<p><b>${ar?'ناقص':'Missing'}:</b> ${DR.ai.missing.map(esc).join(' · ')}</p>`:''}${DR.ai.better?`<pre class="testout" dir="auto">${esc(DR.ai.better)}</pre>`:''}</div>`:''}
${DR.show?`<h4>${ar?'الجزء الأصلي':'The original part'}</h4><pre class="testout" dir="auto">${esc(orig)}</pre>`:''}</div></div></section>`}
async function drAI(){const ar=LANG==='ar';const sample=await tutorSample();if(!sample){ntf('drnote',ar?'بيشتغل جوه claude.ai.':'Works inside claude.ai.');return}if(!DR.ans.trim()){ntf('drnote',ar?'اكتب إجابتك الأول.':'Write your answer first.');return}DR.busy=true;render();
const {p}=drPrompt();const tag=DR.hide;try{const j=await sample.json(`You grade a learner's attempt at one part of a master prompt. Part: <${tag}>. Compare the learner's text with the reference for meaning, specificity, guardrails and usefulness (not wording). Reply in ${ar?'Egyptian Arabic':'English'}. JSON only: {"score":0-100,"good":["max 3 short points"],"missing":["max 3 short points"],"better":"an improved version of the learner's part, same language as the learner, max 900 characters"}\n\nFULL PROMPT WITH THE PART HIDDEN:\n${p.replace(new RegExp('<'+tag+'>[\\s\\S]*?</'+tag+'>'),'<'+tag+'>[hidden]</'+tag+'>').slice(0,5000)}\n\nREFERENCE PART:\n${mpPart(p,tag).slice(0,2000)}\n\nLEARNER'S PART:\n${DR.ans.slice(0,2000)}`,{modelTier:'default'});DR.ai={score:Math.max(0,Math.min(100,+j.score||0)),good:(j.good||[]).slice(0,3).map(String),missing:(j.missing||[]).slice(0,3).map(String),better:String(j.better||'').slice(0,1200)};drMark(DR.ai.score)}catch(e){ntf('drnote',ar?'مقدرتش دلوقتي.':'Could not do it now.')}DR.busy=false;saveDR();render()}
function drMark(sc){if(sc>=70){const k=DR.i+'|'+DR.hide;ST.drDone=ST.drDone||{};if(!ST.drDone[k]){ST.drDone[k]=sc;addXP(5)}saveST()}}

// ===== 11. Real-data practice packs (Studio tab + Module 5 card) =====
function csvRows(s){const rows=[];let row=[],f='',q=false;s=String(s).trim();for(let i=0;i<s.length;i++){const c=s[i];if(q){if(c==='"'){if(s[i+1]==='"'){f+='"';i++}else q=false}else f+=c}else if(c==='"')q=true;else if(c===','){row.push(f);f=''}else if(c==='\n'){row.push(f);rows.push(row);row=[];f=''}else if(c!=='\r')f+=c}if(f||row.length){row.push(f);rows.push(row)}return rows}
function vPrac(){const ar=LANG==='ar';if(typeof PRACDATA==='undefined')return '';const seen=ST.pracSeen||{};
return `<section class="mergedsec" id="pracdata"><h2>📂 ${L(UX23.data)}</h2><p class="k">${ar?`${PRACDATA.length} ملفات بيانات «وسخة» زي اللي في الشغل بالظبط: تكرار، تواريخ بأشكال مختلفة، أرقام مكتوبة كنص، خانات فاضية. نزّل الملف، ارفعه لـ Claude مع البرومبت الماستر، وشوف هيلاقي المشاكل المزروعة ولا لأ.`:`${PRACDATA.length} messy data files, just like real work: duplicates, mixed date formats, numbers stored as text, blank cells. Download a file, give it to Claude with the master prompt, and see whether it finds the planted problems.`}</p>
<div class="row-btns" style="margin-bottom:10px"><button class="btn-gold" data-prz="all">⬇ ${ar?'نزّل كل الملفات (ZIP)':'Download all files (ZIP)'}</button></div>
<div class="fdlist">${PRACDATA.map(p=>{const rows=csvRows(p.csv);return `<details class="fdag"><summary class="fdhead"><span class="fdi">${p.icon}</span><span class="fdt"><b>${esc(L(p.t))} ${seen[p.k]?'✓':''}</b><span class="k">${esc(L(p.field))} · ${p.file} · ${rows.length-1} ${ar?'صف':'rows'}</span></span></summary><div class="fdbody"><p>${esc(L(p.story))}</p>
<div class="tablewrap"><table><tr>${rows[0].map(c=>`<th>${esc(c)}</th>`).join('')}</tr>${rows.slice(1,7).map(r=>`<tr>${r.map(c=>`<td dir="auto">${esc(c)}</td>`).join('')}</tr>`).join('')}</table></div><p class="k">${ar?'أول 6 صفوف بس — الملف كامل في التنزيل.':'First 6 rows only — the full file is in the download.'}</p>
<div class="row-btns"><button class="btn-gold" data-prd="${p.k}">⬇ ${p.file}</button></div>
<h4>🎯 ${ar?'المهام':'Tasks'}</h4><ol class="fdsteps">${p.tasks.map(t=>`<li>${esc(L(t))}</li>`).join('')}</ol>
${promptBox(p.pr)}
<details><summary><b>🕵 ${ar?'المشاكل المزروعة (افتحها بعد ما تخلّص)':'The planted problems (open after you finish)'}</b></summary><ul>${p.issues.map(i=>`<li>${esc(L(i.t))} <span class="k">— ${esc(i.where)}</span></li>`).join('')}</ul></details></div></details>`}).join('')}</div></section>`}
async function pracZip(btn){await ensureZip();const z=new JSZip();PRACDATA.forEach(p=>z.file(p.file,BOM+p.csv.trim()+'\n'));z.file('README.txt',PRACDATA.map(p=>p.file+' — '+p.t.en+'\n'+p.tasks.map((t,i)=>'  '+(i+1)+'. '+t.en).join('\n')).join('\n\n')+'\n\nFictional practice data from Claude Mastery. Remove nothing real; never upload real customer data to tools your company has not approved.\n');const ok=await saveFile('claude-mastery-practice-data.zip',await z.generateAsync({type:'blob'}));if(ok&&btn)btn.textContent='✓'}

{const _tabs=vStudioTabs;vStudioTabs=function(){return _tabs().replace(/<\/div>$/,`<button class="tab ${stuTab==='drill'?'on':''}" data-stutab="drill">🧩 ${L(UX23.drill)}</button><button class="tab ${stuTab==='data'?'on':''}" data-stutab="data">📂 ${L(UX23.data)}</button></div>`)}}
{const _vs=vStudio;vStudio=function(){if(stuTab!=='drill'&&stuTab!=='data')return _vs();crumb(L(UX3.studio)+' › '+L(stuTab==='drill'?UX23.drill:UX23.data));return `<h1>🎛 ${L(UX3.studio)}</h1>`+vStudioTabs()+(stuTab==='drill'?vDrill():vPrac())}}
{const _vd=vDay;vDay=function(n,id){const h=_vd(n,id);if(id||String(n)!=='5'||typeof PRACDATA==='undefined')return h;const ar=LANG==='ar';return h+`<button class="card fdbanner" data-prgo="1">📂 <b>${L(UX23.data)}</b><span class="k">${ar?`${PRACDATA.length} ملفات Excel/CSV «وسخة» للتدريب على التنضيف والتحليل مع Claude`:`${PRACDATA.length} messy Excel/CSV files to practise cleaning and analysis with Claude`} →</span></button>`}}

// ===== 17. Multi-agent handoff game (Agent builder tab) =====
let HG=Object.assign({k:'',order:[],picks:{},human:-1},ST.hgs||{});
function saveHG(){ST.hgs=HG;saveST()}
const hgShuf=s=>s.agents.map((a,i)=>i).sort((a,b)=>{const h=i=>{let x=0;for(const c of s.k+i)x=(x*33+c.charCodeAt(0))>>>0;return x};return h(a)-h(b)});
function vHand(){const ar=LANG==='ar';if(typeof HANDOFF==='undefined')return '';const s=HANDOFF.find(x=>x.k===HG.k)||HANDOFF[0];if(HG.k!==s.k){HG={k:s.k,order:[],picks:{},human:-1}}
const n=s.agents.length;const placed=HG.order.length===n;const orderOK=placed&&HG.order.every((v,i)=>v===i);const passesDone=Object.keys(HG.picks).length===n-1;const passOK=s.passes.filter((p,i)=>HG.picks[i]===p.ok).length;const best=(ST.hg||{})[s.k];
const ag=i=>`<span class="hgag"><span class="fdi">${s.agents[i].icon}</span><b>${esc(L(s.agents[i].n))}</b></span>`;
let h=`<section class="mergedsec"><h2>🔁 ${L(UX23.hand)}</h2><p class="k">${ar?'رتّب الوكلاء بالترتيب الصح، اختار إيه اللي يتسلّم بين كل وكيل والتاني، وحدد فين لازم شخص يوافق.':'Put the agents in the right order, choose what passes between each pair, and mark where a person must approve.'}</p>
<div class="chips">${HANDOFF.map(x=>`<button class="chip ${x.k===s.k?'on':''}" data-hgk="${x.k}">${x.icon} ${esc(L(x.t))}${(ST.hg||{})[x.k]!==undefined?' ✓':''}</button>`).join('')}</div>
<div class="abpane"><h3>🎯 ${esc(L(s.goal))}</h3>${best!==undefined?`<p class="k">${ar?'أحسن نتيجة':'Best score'}: ${best}%</p>`:''}
<h4>1 · ${ar?'رتّب الوكلاء':'Order the agents'}</h4><div class="chips">${hgShuf(s).filter(i=>!HG.order.includes(i)).map(i=>`<button class="chip" data-hga="${i}" title="${esc(L(s.agents[i].does))}">${s.agents[i].icon} ${esc(L(s.agents[i].n))}</button>`).join('')||`<span class="k">${ar?'كله اترتّب.':'All placed.'}</span>`}</div>
<ol class="hgline">${HG.order.map((i,j)=>`<li class="${placed?(i===j?'ok':'no'):''}">${ag(i)}<span class="k">${esc(L(s.agents[i].does))}</span></li>`).join('')}</ol>
<div class="row-btns"><button class="tbtn" data-hgx="undo" ${HG.order.length?'':'disabled'}>↶ ${ar?'تراجع':'Undo'}</button><button class="tbtn" data-hgx="reset">⟲ ${ar?'من الأول':'Start again'}</button>${placed&&!orderOK?`<button class="tbtn" data-hgx="fix">✓ ${ar?'وريني الترتيب الصح':'Show the right order'}</button>`:''}</div>
${placed?`<p class="${orderOK?'k':''}">${orderOK?'✅ '+(ar?'الترتيب صح.':'Right order.'):'⚠ '+(ar?'الترتيب مش مظبوط — المسلسل اللي بالأحمر في مكان غلط.':'Not quite — the red ones are in the wrong place.')}</p>`:''}</div>`;
if(orderOK){h+=`<div class="abpane" style="margin-top:12px"><h4>2 · ${ar?'إيه اللي يتسلّم؟':'What gets handed over?'}</h4>${s.passes.map((p,i)=>{const a=HG.picks[i];return `<div class="fcqq"><p>${ag(i)} → ${ag(i+1)}</p><div class="chips">${p.opts.map((o,j)=>`<button class="chip ${a!==undefined?(j===p.ok?'ok':j===a?'no':''):''}" data-hgp="${i}|${j}" ${a!==undefined?'disabled':''}>${esc(L(o))}</button>`).join('')}</div>${a!==undefined?`<p class="k">${a===p.ok?'✅':'❌'} ${esc(L(p.why))}</p>`:''}</div>`}).join('')}</div>`;
if(passesDone){h+=`<div class="abpane" style="margin-top:12px"><h4>3 · ${ar?'فين لازم شخص يوافق قبل الخطوة اللي بعدها؟':'Where must a person approve before the next step?'}</h4><div class="chips">${s.agents.map((a,i)=>`<button class="chip ${HG.human>=0?(i===s.humanAfter?'ok':i===HG.human?'no':''):''}" data-hgh="${i}" ${HG.human>=0?'disabled':''}>${ar?'بعد':'After'} ${a.icon} ${esc(L(a.n))}</button>`).join('')}</div>
${HG.human>=0?`<p>${HG.human===s.humanAfter?'✅':'❌'} 🧑‍⚖️ ${esc(L(s.human))}</p><div class="ceobox"><b>💡 ${ar?'الدرس':'The lesson'}:</b> ${esc(L(s.lesson))}</div><p><b>${ar?'نتيجتك':'Your score'}: ${hgScore(s)}%</b> <button class="tbtn" data-hgx="reset">⟲ ${ar?'العب تاني':'Play again'}</button></p>`:''}</div>`}}
return h+'</section>'}
function hgScore(s){const n=s.agents.length;const parts=1+(n-1)+1;const got=(HG.order.every((v,i)=>v===i)&&!HG.fixed?1:0)+s.passes.filter((p,i)=>HG.picks[i]===p.ok).length+(HG.human===s.humanAfter?1:0);return Math.round(got/parts*100)}
{const _ab=vAgentB;vAgentB=function(){const btn=`<button class="tab ${AGTAB==='handoff'?'on':''}" data-agtab="handoff">🔁 ${L(UX23.hand)}</button>`;if(AGTAB!=='handoff')return _ab().replace(/(<div class="tabs big">[\s\S]*?)(<\/div>)/,'$1'+btn+'$2');
const keep=AGTAB;AGTAB='guide';let head;try{head=_ab()}finally{AGTAB=keep}const m=head.match(/^<h1>[\s\S]*?<\/h1><div class="tabs big">[\s\S]*?<\/div>/);const tabs=(m?m[0]:'').replace(/ on"/g,'"').replace(/(<div class="tabs big">[\s\S]*?)(<\/div>)$/,'$1'+btn+'$2');crumb(L(UX4.agentb)+' › '+L(UX23.hand));return tabs+vHand()}}

// ===== 19. Skill from a past chat (Skill builder tab) =====
let SC=Object.assign({txt:'',res:null,busy:false},ST.sc||{});SC.busy=false;
function saveSC(){ST.sc=Object.assign({},SC,{busy:false});saveST()}
function scParse(t){const lines=String(t).split('\n');const turns=[];let cur=null;const who=l=>{const m=l.match(/^\s*(user|you|human|me|أنا|انا|المستخدم|claude|assistant|ai|المساعد)\s*[:：]\s*/i);if(!m)return null;return [/^(claude|assistant|ai|المساعد)$/i.test(m[1])?'a':'u',l.slice(m[0].length)]};
lines.forEach(l=>{const w=who(l);if(w){cur={r:w[0],t:w[1]};turns.push(cur)}else if(cur)cur.t+='\n'+l;else{cur={r:'u',t:l};turns.push(cur)}});return turns.filter(x=>x.t.trim())}
function scLocal(){const turns=scParse(SC.txt);const us=turns.filter(x=>x.r==='u').map(x=>x.t.trim());const as=turns.filter(x=>x.r==='a').map(x=>x.t);const first=(us[0]||'').replace(/\s+/g,' ').slice(0,140);
const steps=[];as.forEach(a=>a.split('\n').forEach(l=>{const m=l.match(/^\s*(?:\d+[.)]|[-•*])\s+(.{8,160})/);if(m&&steps.length<8&&!steps.includes(m[1].trim()))steps.push(m[1].trim())}));
const words=asNorm(first.replace(/^(please|can you|could you|i need you to|help me|i want you to)\s+/i,'')).split(/[^a-z0-9]+/).filter(w=>w.length>2&&!AS_STOP.has(w)).slice(0,4);const name=(words.join('-')||'my-skill').slice(0,40);
return {name,description:first?`Use when the user asks to ${first.replace(/^(please|can you|could you|i need you to|help me)\s+/i,'').replace(/[.?!]+$/,'')}. Follows the steps that worked in a past conversation.`:'',when:us.slice(0,3).map(u=>u.replace(/\s+/g,' ').slice(0,120)),steps:steps.length?steps:['Confirm the goal, inputs and audience','Do the work in the order agreed','Check the result against the request before replying'],inputs:[],output:'',checks:['Never invent figures; write [MISSING] and ask','Label assumptions','A person approves before anything is sent, posted or paid'],examples:us.slice(0,2).map(u=>u.replace(/\s+/g,' ').slice(0,160)),turns:turns.length}}
function scMD(r){const L1=a=>(a||[]).filter(Boolean).map(x=>'- '+x).join('\n');return `---\nname: ${slug(r.name)||'my-skill'}\ndescription: ${JSON.stringify(String(r.description||'').slice(0,1000))}\n---\n\n# ${r.name}\n\n## When to use\n${L1(r.when)}\n\n## Steps\n${(r.steps||[]).map((s,i)=>(i+1)+'. '+s).join('\n')}\n${r.inputs&&r.inputs.length?`\n## Inputs\n${L1(r.inputs)}\n`:''}${r.output?`\n## Output\n${r.output}\n`:''}\n## Checks before replying\n${L1(r.checks)}\n${r.examples&&r.examples.length?`\n## Example requests\n${L1(r.examples)}\n`:''}`}
function vSkillChat(){const ar=LANG==='ar';const r=SC.res||(SC.txt.trim()?scLocal():null);
return `<section class="mergedsec"><h2>💬 ${L(UX23.chat)}</h2><p class="k">${ar?'محادثة نفعت معاك؟ الصقها هنا (سطور تبدأ بـ «User:» و«Claude:») وهنطلع منها مسودة SKILL.md تقدر تعيد استخدامها. شيل أي بيانات شخصية أو سرية الأول.':'Had a chat that worked well? Paste it here (lines starting with "User:" and "Claude:") and get a draft SKILL.md you can reuse. Remove personal or confidential data first.'}</p>
<div class="twocol"><div class="abpane"><label class="pbf"><b>${ar?'المحادثة':'The conversation'}</b><textarea class="search" id="sctxt" rows="14" dir="auto" placeholder="User: …\nClaude: …">${esc(SC.txt)}</textarea></label><div class="row-btns"><button class="btn-gold" data-scx="ai" ${SC.busy||!SC.txt.trim()?'disabled':''}>${SC.busy?'…':'✨ '+(ar?'خلّي Claude يكتبها':'Let Claude write it')}</button>${SC.res?`<button class="tbtn" data-scx="local">↺ ${ar?'رجّع للمسودة المحلية':'Back to the instant draft'}</button>`:''}</div><p class="note" id="scnote"></p></div>
<div class="abpane">${r?`<h3>${SC.res?'✨ Claude':(ar?'مسودة فورية':'Instant draft')} ${r.turns!==undefined?`<span class="k">(${r.turns} ${ar?'رسالة':'turns'})</span>`:''}</h3><pre class="testout" dir="auto" style="max-height:420px">${esc(scMD(r))}</pre><div class="row-btns"><button class="btn-gold" data-scx="md">⬇ SKILL.md</button><button class="tbtn" data-scx="zip">⬇ ZIP</button><button class="tbtn" data-scx="test">🎯 ${ar?'جرّب الوصف في فاحص التفعيل':'Test the description in the trigger tester'}</button></div>`:`<p class="k">${ar?'الصق محادثة على الشمال.':'Paste a conversation on the left.'}</p>`}</div></div></section>`}
async function scAI(){const ar=LANG==='ar';const sample=await tutorSample();if(!sample){ntf('scnote',ar?'بيشتغل جوه claude.ai.':'Works inside claude.ai.');return}SC.busy=true;render();
try{const j=await sample.json(`Turn this conversation into a reusable Claude Skill. Capture what the user wanted and the method that worked, not the specific data. Generalise names and numbers into [placeholders]. Add checks so it never invents figures and keeps a person approving anything sent, posted or paid. Write the Skill in ${ar?'English (keep it usable by teams), with Arabic examples if the chat was Arabic':'English'}. JSON only: {"name":"kebab-case","description":"what it does AND when to use it, max 300 chars","when":["3 trigger situations"],"steps":["4-8 steps"],"inputs":["inputs"],"output":"output format","checks":["3-5 checks"],"examples":["2-3 example requests"]}\n\nCONVERSATION:\n${SC.txt.slice(0,12000)}`,{modelTier:'default'});if(!j||!Array.isArray(j.steps))throw 0;const A=a=>(Array.isArray(a)?a:[]).map(String).slice(0,8);SC.res={name:slug(String(j.name||'my-skill')).slice(0,60)||'my-skill',description:String(j.description||'').slice(0,1000),when:A(j.when),steps:A(j.steps),inputs:A(j.inputs),output:String(j.output||''),checks:A(j.checks),examples:A(j.examples)}}catch(e){ntf('scnote',ar?'مقدرتش دلوقتي.':'Could not do it now.')}SC.busy=false;saveSC();render()}
{const _sb=vSkillBuilder;vSkillBuilder=function(){const btn=`<button class="tab ${SBTAB==='chat'?'on':''}" data-sbtab="chat">💬 ${L(UX23.chat)}</button>`;if(SBTAB!=='chat')return _sb().replace(/(data-sbtab="plugin">[\s\S]*?<\/button>)/,'$1'+btn);
const keep=SBTAB;SBTAB='plugin';let head;try{head=_sb()}finally{SBTAB=keep}const m=head.match(/^<h1>[\s\S]*?<\/h1><div class="tabs big">[\s\S]*?<\/div>/);const tabs=(m?m[0]:'').replace(/ on"/g,'"').replace(/(data-sbtab="plugin">[\s\S]*?<\/button>)/,'$1'+btn);crumb(L(UX2.skb)+' › '+L(UX23.chat));return tabs+vSkillChat()}}

// ===== 20. Plugin gallery by department (Plugin tab) =====
function galDepts(){const o=[];FD.forEach(f=>{const conns=[...new Set(Object.entries(FDMAP).filter(([k,v])=>v===f.k&&FAG[k]&&FAG[k].conn).flatMap(([k])=>FAG[k].conn.map(c=>c.conn)))];o.push({k:'fd-'+f.k,icon:f.icon,t:f.t,fin:true,f,agents:f.agents,skills:f.skills,conns})});
Object.entries(FAG).forEach(([k,F])=>{if(!F.agents)return;const f=fagField(k);o.push({k,icon:f.icon,t:f.t,fin:false,f,agents:F.agents,skills:F.skills,conns:[...new Set((F.conn||[]).map(c=>c.conn))]})});return o}
async function galZip(d,btn){await ensureZip();const z=new JSZip();const id=slug(d.t.en)+'-pack';const r=z.folder(id);r.folder('.claude-plugin').file('plugin.json',JSON.stringify({name:id,description:`${d.t.en}: ${d.agents.length} agents and ${d.skills.length} Skills from Claude Mastery`,version:'0.1.0',author:{name:'Claude Mastery — Dr. Sara Salem'}},null,2));
d.skills.forEach(s=>r.folder('skills/'+s.k).file('SKILL.md',fdSkillMd(s,'en')));d.agents.forEach(a=>{const p=fdPrompt(a,d.f,'en');r.folder('agents').file(a.k+'.md',`---\nname: ${a.k}\ndescription: ${JSON.stringify(((a.job&&a.job.en)||'').slice(0,300))}\n---\n\n${p}\n`);r.folder('commands').file(a.k+'.md',`---\ndescription: ${JSON.stringify('Run the '+a.n.en+' on what I give you')}\n---\n\nAct as the ${a.n.en}. Follow this brief exactly, ask for any missing input first, and return a draft for my approval.\n\n${p}\n\nMy input: $ARGUMENTS\n`)});
r.file('.mcp.json',JSON.stringify({mcpServers:Object.fromEntries(d.conns.map(c=>[c,{_todo:`Add your company's approved ${c} connector / MCP server here (least privilege, read-only by default)`}]))},null,2));
r.file('README.md',`# ${d.t.en} pack\n\n- Agents (agents/ and commands/): ${d.agents.map(a=>a.n.en).join(', ')}\n- Skills: ${d.skills.map(s=>s.n.en).join(', ')}\n- Connector types to wire up: ${d.conns.join(', ')||'none'}\n\nBefore sharing with your team: read every file, replace [placeholders], connect only approved connectors in .mcp.json, and keep a person approving anything that is sent, posted, paid or filed.\n\nBuilt with Claude Mastery.\n`);
const ok=await saveFile(id+'.zip',await z.generateAsync({type:'blob'}));if(ok&&btn)btn.textContent='✓'}
function vPlGallery(){const ar=LANG==='ar';const D=galDepts();return `<section class="mergedsec" id="plgal"><h2>🗂 ${L(UX23.gal)} (${D.length})</h2><p class="k">${ar?'كل باقة فيها وكلاء الإدارة (كـ agents وأوامر /)، الـ Skills بتاعتها، وقالب .mcp.json للـ Connectors. نزّلها زي ما هي أو افتحها في الباني وعدّل.':'Each bundle holds the department’s agents (as agents and / commands), its Skills, and a .mcp.json template for its connectors. Download it as is, or open it in the builder and edit.'}</p>
<div class="grid">${D.map(d=>`<div class="card"><h3>${d.icon} ${esc(L(d.t))}${d.fin?` <span class="tag">${ar?'مالية':'Finance'}</span>`:''}</h3><p class="k">🤖 ${d.agents.length} · 🧩 ${d.skills.length} · 🔌 ${d.conns.length?d.conns.map(ctl).join(', '):'—'}</p><div class="row-btns"><button class="btn-gold" data-pgz="${d.k}">⬇ ZIP</button><button class="tbtn" data-pgc="${d.k}">✎ ${ar?'عدّل في الباني':'Customise'}</button></div></div>`).join('')}</div></section>`}
{const _vp=vPlugin;vPlugin=function(){return _vp()+vPlGallery()}}

// ===== 28. Skills & badges card (Card page) =====
const MODSHORT={1:T('Prompting','البرومبت'),2:T('Projects & memory','Projects والذاكرة'),3:T('Artifacts & docs','Artifacts والمستندات'),4:T('Skills & connectors','Skills والـ Connectors'),5:T('Office tools','أدوات المكتب'),6:T('Cowork agents','وكلاء Cowork'),7:T('Claude Code & API','Claude Code والـ API'),8:T('Leading AI change','قيادة التغيير بالـ AI'),9:T('Responsible AI','الـ AI المسؤول'),10:T('Arabic content','المحتوى العربي')};
function modPct(d){const n=d.units.length;return n?Math.round(d.units.filter(u=>DONE.includes(u.id)).length/n*100):0}
function topSkills(){return DAYS.map(d=>({n:d.n,t:MODSHORT[d.n]||d.t,p:modPct(d)})).sort((a,b)=>b.p-a.p||a.n-b.n).slice(0,5)}
async function makeCard2(){const ar=LANG==='ar';const c=document.createElement('canvas');c.width=1200;c.height=627;const x=c.getContext('2d');try{await document.fonts.load('700 40px "Readex Pro"')}catch(e){}
x.fillStyle='#13284B';x.fillRect(0,0,1200,627);x.strokeStyle='rgba(255,255,255,.05)';for(let i=0;i<1200;i+=28){x.beginPath();x.moveTo(i,0);x.lineTo(i,627);x.stroke()}for(let j=0;j<627;j+=28){x.beginPath();x.moveTo(0,j);x.lineTo(1200,j);x.stroke()}
const s=stats();const R=ar?1130:70,dir=ar?-1:1;x.direction=ar?'rtl':'ltr';x.textAlign=ar?'right':'left';
x.fillStyle='#F1D27A';x.font='700 26px Amiri, serif';x.fillText(ar?'مهاراتي في Claude · Claude Mastery':'My Claude skills · Claude Mastery',R,78);
x.fillStyle='#fff';x.font='700 54px "Readex Pro", Arial';x.fillText(ST.name||(ar?'اسمك':'Your name'),R,148);
x.fillStyle='#C7D1E2';x.font='400 24px "Readex Pro", Arial';x.fillText(ar?`${s.xp} نقطة · ${s.lessons} درس · ${s.pct}% من المنهج`:`${s.xp} XP · ${s.lessons} lessons · ${s.pct}% of the curriculum`,R,192);
const sk=topSkills();sk.forEach((k,i)=>{const y=250+i*56;x.fillStyle='#fff';x.font='600 22px "Readex Pro", Arial';x.fillText(L(k.t),R,y);const bx=ar?R-560:R+0,w=560;x.fillStyle='rgba(255,255,255,.12)';x.fillRect(ar?R-w:R,y+12,w,12);x.fillStyle='#D9B44A';const fw=w*k.p/100;x.fillRect(ar?R-fw:R,y+12,fw,12);x.textAlign=ar?'left':'right';x.fillStyle='#C7D1E2';x.font='400 18px "Readex Pro", Arial';x.fillText(k.p+'%',ar?R-w:R+w,y);x.textAlign=ar?'right':'left'});
const got=BADGES.filter(b=>b[3](s)).slice(0,8);const BX=ar?60:700,BY=230;x.textAlign='center';got.forEach((b,i)=>{const cx=BX+70+(i%4)*115+(ar?0:0),cy=BY+40+Math.floor(i/4)*120;x.fillStyle='rgba(217,180,74,.16)';x.beginPath();x.arc(cx+(ar?0:0),cy,42,0,7);x.fill();x.font='40px "Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji",sans-serif';x.fillStyle='#fff';x.fillText(b[1],cx,cy+14);x.font='400 14px "Readex Pro", Arial';x.fillStyle='#C7D1E2';x.fillText(L(b[2]).slice(0,16),cx,cy+64)});
if(!got.length){x.font='400 20px "Readex Pro", Arial';x.fillStyle='#93A2BC';x.fillText(ar?'الشارات هتظهر هنا':'Badges will appear here',BX+230,BY+60)}
x.textAlign=ar?'right':'left';x.fillStyle='#fff';x.font='400 20px "Readex Pro", Arial';x.fillText(ar?'مع د. سارة سالم — خبيرة AI في المالية':'With Dr. Sara Salem — AI Finance Expert',R,575);
if(ST.certReg){x.fillStyle='#F1D27A';x.font='400 16px "Readex Pro", Arial';x.fillText((ar?'كود الشهادة: ':'Certificate code: ')+ST.certReg.code,R,603)}
const q=new Image();q.src='data:image/png;base64,'+(await svgPng(QR_PLATFORM)).split(',')[1];await new Promise(r=>q.onload=r);x.fillStyle='#fff';x.fillRect(ar?60:1030,480,120,120);x.drawImage(q,ar?64:1034,484,112,112);
return await new Promise(r=>c.toBlob(r,'image/png'))}
{const _vc=vCard;vCard=function(){const ar=LANG==='ar';const sk=topSkills().filter(k=>k.p>0).map(k=>L(k.t));const s=stats();const got=BADGES.filter(b=>b[3](s));const post=ar?`مهاراتي في Claude مع Claude Mastery 🎓\n${sk.length?'أقوى مجالاتي: '+sk.join('، ')+'\n':''}${got.length?'الشارات: '+got.map(b=>b[1]+' '+L(b[2])).join(' · ')+'\n':''}#Claude #AI`:`My Claude skills with Claude Mastery 🎓\n${sk.length?'Strongest areas: '+sk.join(', ')+'\n':''}${got.length?'Badges: '+got.map(b=>b[1]+' '+L(b[2])).join(' · ')+'\n':''}#Claude #AI`;const i=PSTORE.push(post)-1;
return _vc()+`<section class="mergedsec"><h2>🏷 ${L(UX23.card2)}</h2><p class="k">${ar?'كارت تاني بمقاس لينكدإن فيه أقوى 5 مجالات عندك بالنسبة، والشارات اللي كسبتها، وكود الشهادة لو سجّلتها.':'A second LinkedIn-sized card with your 5 strongest areas, the badges you earned, and your certificate code if you registered it.'}</p><div class="row-btns"><button class="btn-gold" data-card2="png">⤓ PNG</button><button class="tbtn" data-card2="preview">${ar?'معاينة':'Preview'}</button></div><div id="card2prev" class="cardprev"></div><div class="prompt"><div class="ph"><h3>${ar?'نص البوست':'Post text'}</h3><button class="copy" data-i="${i}">${L(UI.copy)}</button></div><pre dir="auto">${esc(post)}</pre></div></section>`}}

// ===== 32. Certificate verification (Certificates page + #verify) =====
let CVF={q:'',res:null,busy:false,note:''};
async function cvDB(){try{const use=window.claude&&window.claude.use;if(!use)return null;const db=await use('db');const user=await use('user');return db&&user?{db,user}:null}catch(e){return null}}
async function cvRegister(btn){const ar=LANG==='ar';const s=stats();if(!(s.pct>=100&&s.quizAvg>=70))return;if(!ST.name||!ST.name.trim()){ntf('cvnote',ar?'اكتب اسمك على الشهادة الأول.':'Type your name for the certificate first.');return}const c=await cvDB();if(!c){ntf('cvnote',ar?'التسجيل بيشتغل لما المنصة تتفتح جوه claude.ai وإنت عامل دخول.':'Registration works when the platform is opened on claude.ai while you are signed in.');return}
btn.disabled=true;try{const id=await c.user.id();const ref=c.db.doc('certs/'+id);let cur=[];try{const g=await ref.get();if(g&&g.exists)cur=(g.data().certs)||[]}catch(e){}const code=certId();const t=tier(s.quizAvg);const rec={code,name:ST.name.trim().slice(0,80),title:'Claude Mastery',level:t[0],quiz:s.quizAvg,date:nowISO().slice(0,10)};
await ref.set({certs:cur.filter(x=>x.code!==code).concat(rec).slice(-10)});ST.certReg=rec;saveST();render()}catch(e){btn.disabled=false;ntf('cvnote',(e&&e.code)==='permission_denied'||(e&&e.code)==='not_granted'?(ar?'معندكش صلاحية تسجيل — اطلب من صاحبة المنصة صلاحية «Contributor».':'You do not have permission to register — ask the platform owner for contributor access.'):(ar?'مقدرتش أسجّل دلوقتي.':'Could not register now.'))}}
async function cvCheck(){const ar=LANG==='ar';const q=CVF.q.trim().toUpperCase();if(!q)return;const c=await cvDB();if(!c){CVF.note=ar?'التحقق بيشتغل لما المنصة تتفتح جوه claude.ai وإنت عامل دخول.':'Verification works when the platform is opened on claude.ai while signed in.';CVF.res=null;render();return}CVF.busy=true;render();
try{const snap=await c.db.collection('certs').get();let hit=null;snap.docs.forEach(d=>{if(!d.exists||hit)return;const x=(d.data().certs||[]).find(r=>String(r.code).toUpperCase()===q);if(x)hit=x});CVF.res=hit?{ok:true,r:hit}:{ok:false};CVF.note=''}catch(e){CVF.note=ar?'مقدرتش أتحقق دلوقتي.':'Could not check now.'}CVF.busy=false;render()}
function vVerify(code){crumb(L(UX23.verify));const ar=LANG==='ar';if(code&&!CVF.q){CVF.q=decodeURIComponent(code);setTimeout(cvCheck,0)}const r=CVF.res;
return `<h1>🔏 ${L(UX23.verify)}</h1><p class="lede">${ar?'اكتب كود الشهادة (زي CM-XXXXXXX) عشان تتأكد إنها اتسجّلت على المنصة.':'Enter a certificate code (like CM-XXXXXXX) to confirm it was registered on the platform.'}</p>
<div class="abpane"><div class="stu-goal" style="grid-template-columns:1fr auto"><input class="search" id="cvq" value="${esc(CVF.q)}" placeholder="CM-XXXXXXX" dir="ltr"><button class="btn-gold" data-cvx="check" ${CVF.busy?'disabled':''}>${CVF.busy?'…':(ar?'تحقق':'Verify')}</button></div><p class="note" id="cvnote2">${esc(CVF.note||'')}</p>
${r?(r.ok?`<div class="seewarn ok">✅ <b>${ar?'شهادة سليمة':'Valid certificate'}</b><br>${ar?'الاسم':'Name'}: <b dir="auto">${esc(r.r.name)}</b> · ${esc(r.r.title)} · ${ar?'المستوى':'Level'}: ${esc(r.r.level)} (${+r.r.quiz||0}%) · ${ar?'التاريخ':'Date'}: ${esc(r.r.date)}</div>`:`<div class="seewarn no">⛔ ${ar?'الكود ده مش متسجّل. اتأكد من الكتابة أو اطلب من صاحب الشهادة يسجّلها من صفحة الشهادات.':'This code is not registered. Check the spelling, or ask the holder to register it from the Certificates page.'}</div>`):''}</div>
<p class="k">${ar?'الصفحة دي بتقرا سجل الشهادات المشترك جوه المنصة. أي حد معاه لينك المنصة يقدر يتحقق.':'This page reads the platform’s shared certificate register. Anyone with the platform link can check a code.'}</p>`}
function cvSection(){const ar=LANG==='ar';const s=stats();const ok=s.pct>=100&&s.quizAvg>=70;const reg=ST.certReg;
return `<section class="mergedsec" id="certverify"><h2>🔏 ${ar?'التحقق من الشهادة':'Certificate verification'}</h2><p class="k">${ar?'سجّل شهادتك عشان أي حد (مدير، HR، عميل) يقدر يتأكد منها بالكود. اسمك والكود والمستوى والتاريخ هيبقوا ظاهرين لأي حد بيتحقق.':'Register your certificate so anyone (a manager, HR, a client) can confirm it with the code. Your name, code, level and date become visible to anyone who checks.'}</p>
${ok?(reg&&reg.code===certId()?`<div class="seewarn ok">✅ ${ar?'متسجّلة':'Registered'}: <b>${esc(reg.code)}</b> · ${esc(reg.date)}</div><div class="row-btns"><button class="tbtn" data-cvx="copy">🔗 ${ar?'انسخ لينك التحقق':'Copy the verification link'}</button><button class="tbtn" data-cvx="reg">↻ ${ar?'سجّل تاني':'Register again'}</button></div>`:`<div class="row-btns"><button class="btn-gold" data-cvx="reg">🔏 ${ar?'سجّل شهادتي للتحقق':'Register my certificate for verification'}</button></div>`):`<p class="k">🔒 ${ar?'بيتفتح لما الشهادة تتفتح.':'Opens when your certificate unlocks.'}</p>`}
<p class="note" id="cvnote"></p><div class="row-btns"><button class="tbtn" data-go="verify">🔎 ${L(UX23.verify)}</button></div></section>`}
{const _vc=vCert;vCert=function(){return _vc()+cvSection()}}

// ===== events =====
document.addEventListener('click',e=>{const g=s=>e.target.closest(s);let x;
if(x=g('[data-drh]')){DR.hide=x.dataset.drh;DR.ans='';DR.res=null;DR.ai=null;DR.show=false;saveDR();render();return}if(x=g('[data-drn]')){DR.i=-1;DR.ans='';DR.res=null;DR.ai=null;DR.show=false;DR.hide=MPTAGS[Math.floor(Math.random()*6)];drPrompt();saveDR();render();return}
if(x=g('[data-dra]')){const a=x.dataset.dra;if(a==='check'){if(!DR.ans.trim()){ntf('drnote',LANG==='ar'?'اكتب إجابتك الأول.':'Write your answer first.');return}const {p}=drPrompt();DR.res=drLocal(DR.ans,mpPart(p,DR.hide),DR.hide);drMark(DR.res.score);saveDR();render()}else if(a==='ai')drAI();else{DR.show=!DR.show;saveDR();render()}return}
if(x=g('[data-prd]')){const p=PRACDATA.find(y=>y.k===x.dataset.prd);saveFile(p.file,BOM+p.csv.trim()+'\n').then(ok=>{if(ok){ST.pracSeen=Object.assign({},ST.pracSeen,{[p.k]:1});saveST()}});return}if(x=g('[data-prz]')){pracZip(x);return}
if(x=g('[data-prgo]')){labTab='studio';stuTab='data';go('lab');return}
if(x=g('[data-hgk]')){HG={k:x.dataset.hgk,order:[],picks:{},human:-1};saveHG();render();return}if(x=g('[data-hga]')){HG.order.push(+x.dataset.hga);saveHG();render();return}
if(x=g('[data-hgx]')){const a=x.dataset.hgx;if(a==='undo')HG.order.pop();else if(a==='reset')HG={k:HG.k,order:[],picks:{},human:-1};else if(a==='fix'){const s=HANDOFF.find(y=>y.k===HG.k);HG.order=s.agents.map((_,i)=>i);HG.fixed=true}saveHG();render();return}
if(x=g('[data-hgp]')){const [i,j]=x.dataset.hgp.split('|').map(Number);HG.picks=Object.assign({},HG.picks,{[i]:j});saveHG();render();return}
if(x=g('[data-hgh]')){HG.human=+x.dataset.hgh;const s=HANDOFF.find(y=>y.k===HG.k);const sc=hgScore(s);ST.hg=ST.hg||{};if(ST.hg[s.k]===undefined)addXP(10);ST.hg[s.k]=Math.max(ST.hg[s.k]||0,sc);saveHG();render();return}
if(x=g('[data-scx]')){const a=x.dataset.scx;const r=SC.res||scLocal();if(a==='ai')scAI();else if(a==='local'){SC.res=null;saveSC();render()}else if(a==='md')saveFile('SKILL.md',scMD(r));else if(a==='zip'){(async()=>{await ensureZip();const z=new JSZip();z.folder(slug(r.name)||'my-skill').file('SKILL.md',scMD(r));await saveFile((slug(r.name)||'my-skill')+'.zip',await z.generateAsync({type:'blob'}))})()}else if(a==='test'){TT.desc=r.description||'';TT.reqs=(r.examples||[]).join('\n');TT.res=null;ST.tt=Object.assign({},TT,{busy:false});saveST();SKVIEW='test';go('skills')}return}
if(x=g('[data-pgz]')){const d=galDepts().find(y=>y.k===x.dataset.pgz);if(d)galZip(d,x);return}
if(x=g('[data-pgc]')){const d=galDepts().find(y=>y.k===x.dataset.pgc);if(d){PLB={name:slug(d.t.en)+'-pack',role:L(d.t),desc:`${d.t.en}: ${d.agents.length} agents and ${d.skills.length} Skills`,skills:d.skills.map(s=>s.k),cmds:[],conns:d.conns.slice()};savePLB();render();const v=document.querySelector('main');if(v)v.scrollTop=0}return}
if(x=g('[data-card2]')){const btn=x;btn.disabled=true;makeCard2().then(b=>{btn.disabled=false;if(x.dataset.card2==='png')saveFile('Claude-Mastery-Skills-Card.png',b);else{const el=document.getElementById('card2prev');if(el){const u=URL.createObjectURL(b);el.innerHTML=`<img src="${u}" alt="">`}}}).catch(()=>{btn.disabled=false});return}
if(x=g('[data-cvx]')){const a=x.dataset.cvx;if(a==='reg')cvRegister(x);else if(a==='check')cvCheck();else if(a==='copy'){const t=PLATFORM_URL+' → '+(LANG==='ar'?'تحقق من شهادة':'Verify a certificate')+': '+ST.certReg.code;try{navigator.clipboard.writeText(t);x.textContent='✓'}catch(e){ntf('cvnote',t)}}return}},true);
document.addEventListener('input',e=>{const t=e.target;if(t.id==='drans'){DR.ans=t.value;DR.res=null;saveDR();return}if(t.id==='sctxt'){SC.txt=t.value;SC.res=null;saveSC();r14rerender('x');return}if(t.id==='cvq'){CVF.q=t.value;CVF.res=null;return}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target&&e.target.id==='cvq'){e.preventDefault();cvCheck()}});
