// ===== FIELD LIBRARY VIEW (#fields), FIELD TRACKS (#tracks) + certificate, RECIPE CARDS, MODULE PROJECTS (#projects) =====
const UX13={fields:T('Field library','مكتبة المجالات'),tracks:T('Field tracks','مسارات المجالات'),projects:T('Module projects','مشروعات الموديولات'),recipe:T('Recipe card','كارت الوصفات'),e2e:T('Company cases A–Z','حالات الشركات من الألف للياء')};
const LABFIELD={sales:'Sales',finance:'Finance',banking:'Banking',audit:'Audit',tradefin:'Trade finance',hr:'HR',marketing:'Marketing',content:'Content',operations:'Operations',procurement:'Procurement',cs:'Customer service',pm:'Project management',ceo:'CEO',legal:'Legal',trainer:'Trainer',product:'Product',academic:'Academic',cfo:'CFO',ea:'Executive assistant',accounting:'Accounting',fpa:'FP&A',treasury:'Treasury',compliance:'Compliance'};
const TRACK_CORE=['1.4','1.6','1.9','2.2','4.1','4.4','9.1'];
const TRACK_EXTRA={finance:['5.1','6.1','9.5'],cfo:['5.1','6.1','9.4'],fpa:['5.1','6.1','3.2'],accounting:['5.1','6.1','9.5'],treasury:['5.1','6.1','9.6'],banking:['5.1','9.5','9.6'],audit:['5.1','9.5','9.6'],tradefin:['5.1','6.1','10.2'],
sales:['3.1','5.2','5.3'],marketing:['3.1','3.3','10.1'],content:['3.1','10.1','10.3'],cs:['5.4','10.1','10.3'],product:['3.1','3.3','7.3'],hr:['3.2','5.2','9.6'],trainer:['3.1','3.2','10.1'],academic:['2.1','3.2','10.2'],ea:['2.3','5.2','5.3'],
legal:['9.5','9.6','10.2'],compliance:['9.4','9.5','9.6'],operations:['5.1','6.1','6.2'],procurement:['5.1','6.1','9.6'],pm:['3.2','6.1','5.4'],ceo:['3.2','6.1','9.4']};
if(!ST.fl)ST.fl={};if(!ST.proj)ST.proj={};
let FLK=ST.flk||'finance';
const fieldOf=k=>FIELDLIB.find(f=>f.k===k)||FIELDLIB[0];
const unitById=id=>{for(const d of DAYS){const u=d.units.find(x=>x.id===id);if(u)return [d,u]}return null};
const trackLessons=k=>TRACK_CORE.concat(TRACK_EXTRA[k]||[]).filter(id=>unitById(id));
function trackState(k){const ls=trackLessons(k);const ld=ls.filter(id=>DONE.includes(id)).length;const tasks=(ST.fl[k]||[]).length;const total=ls.length+4;return {ls,ld,tasks,pct:Math.round(100*(ld+tasks)/total)}}
const block=(text,k)=>{const m=String(text).match(new RegExp(`<${k}>([\\s\\S]*?)</${k}>`));return m?m[1].trim():''};
function fieldChips(cur,attr){return `<div class="fchips">${FIELDLIB.map(f=>`<button class="chip ${f.k===cur?'on':''}" data-${attr}="${f.k}">${f.icon} ${L(f.t)}</button>`).join('')}</div>`}
function dataChips(keys){if(!keys.length)return '';const ar=LANG==='ar';return `<div class="chips"><span class="k">${ar?'بيانات تجريبية':'Sample data'}:</span>${keys.filter(k=>DATA[k]).map(k=>`<button class="chip" data-fldata="${k}">⤓ ${esc(L(DATA[k]))}.csv</button>`).join('')}</div>`}

// ---------- 1. Field library ----------
function vFields(){crumb(L(UX13.fields));const ar=LANG==='ar';const f=fieldOf(FLK);const done=ST.fl[f.k]||[];
let h=`<h1>🗃 ${L(UX13.fields)}</h1><p class="lede">${ar?`${FIELDLIB.length} مجال، ولكل مجال 4 مهام (يومي، أسبوعي، شهري، سنوي) — كل مهمة ببرومبت ماستر وبيانات تجريبية ومثال لمخرج متكامل.`:`${FIELDLIB.length} fields, each with four tasks (daily, weekly, monthly, yearly) — every task with a master prompt, sample data and a filled example output.`}</p>`+fieldChips(f.k,'flk');
h+=`<section class="fhead"><div><div class="k">${f.icon} ${ar?'مجال':'Field'}</div><h2 style="margin:4px 0">${L(f.t)}</h2>${dataChips(f.data)}</div><div class="row-btns"><button class="btn-gold" data-recipe="${f.k}">📄 ${L(UX13.recipe)} PDF</button><button class="tbtn" data-flpack="${f.k}">📦 ${ar?'الأربعة للسلة':'All 4 to basket'}</button><button class="tbtn" data-trk="${f.k}">🎓 ${ar?'مسار المجال':'Field track'}</button></div></section>`;
h+=`<div class="ftasks">`+f.tasks.map(t=>`<article class="ftask"><header><span class="cad cad-${t.c}">${L(CAD[t.c])}</span><h3>${L(t.t)}</h3><label class="opt fdone"><input type="checkbox" data-fldone="${f.k}:${t.c}" ${done.includes(t.c)?'checked':''}> ${ar?'جرّبتها':'Practised'}</label></header>${promptBox({t:T('Master prompt','البرومبت الماستر'),p:t.p})}<details class="fex" ${PRINT?'open':''}><summary>${ar?'مثال لمخرج متكامل':'Example of a finished output'}</summary><pre class="testout" dir="auto">${esc(L(t.ex))}</pre><p class="note">${ar?'مثال توضيحي بأرقام تجريبية.':'Illustrative example with sample figures.'}</p></details></article>`).join('')+`</div>`;
const labs=LAB.filter(c=>c.field.en===LABFIELD[f.k]);if(labs.length)h+=`<h2>⚗ ${ar?'حالات المعمل للمجال ده':'Lab cases for this field'} (${labs.length})</h2>`+labs.map(c=>caseCard(c,`${L(CC[c.cat])} · ${L(c.field)}`)).join('');
return h}

// ---------- 11. Field tracks ----------
function vTracks(){crumb(L(UX13.tracks));const ar=LANG==='ar';const f=fieldOf(FLK);const s=trackState(f.k);const ok=s.pct>=100;
let h=`<h1>🎓 ${L(UX13.tracks)}</h1><p class="lede">${ar?'اختار مجالك وشوف بس الدروس والبرومبتات والحالات والبيانات اللي تخصه. خلّص المسار وخد شهادة المجال.':'Pick your field and see only the lessons, prompts, cases and data that fit it. Finish the track to earn a field certificate.'}</p>`+fieldChips(f.k,'trk');
h+=`<section class="cdash"><div class="cd-l"><div class="sig">${ar?'مسار':'Track'}</div><h1>${f.icon} ${L(f.t)}</h1><p>${ar?`${s.ls.length} درس + 4 مهام عملية من مكتبة المجال.`:`${s.ls.length} lessons + 4 practical tasks from the field library.`}</p></div><div class="cd-r"><div class="cd-ring">${ring(s.pct)}</div><div class="cd-kpi"><div><b>${s.ld}/${s.ls.length}</b>${ar?'دروس':'lessons'}</div><div><b>${s.tasks}/4</b>${ar?'مهام':'tasks'}</div></div></div></section>`;
h+=`<h2>📘 ${ar?'الدروس':'Lessons'}</h2><ol class="pathlist">${s.ls.map(id=>{const [d,u]=unitById(id);return `<li class="${DONE.includes(id)?'ok':''}"><a href="#day/${d.n}/${u.id}">${u.id} · ${esc(L(u.t))}</a><span class="wk">${u.dur} ${L(UI.min)}</span></li>`}).join('')}</ol>`;
h+=`<h2>🗃 ${ar?'المهام العملية':'Practical tasks'}</h2><div class="grid">${f.tasks.map(t=>`<button class="card" data-flgo="${f.k}"><span class="cad cad-${t.c}">${L(CAD[t.c])}</span> ${(ST.fl[f.k]||[]).includes(t.c)?'✓':''}<h3 style="margin-top:6px">${esc(L(t.t))}</h3></button>`).join('')}</div>`;
const labs=LAB.filter(c=>c.field.en===LABFIELD[f.k]);h+=`<h2>⚗ ${ar?'المزيد':'More for this field'}</h2><div class="row-btns"><button class="tbtn" data-trklab="${f.k}">⚗ ${ar?'حالات المعمل':'Lab cases'} (${labs.length})</button><button class="tbtn" data-recipe="${f.k}">📄 ${L(UX13.recipe)}</button><button class="tbtn" data-go="projects">🛠 ${L(UX13.projects)}</button></div>${dataChips(f.data)}`;
h+=`<h2>🎓 ${ar?'شهادة المسار':'Track certificate'}</h2><div class="certwrap ${ok?'':'locked'}">${trackCertSVG(f)}${ok?'':`<div class="lockmsg">🔒 ${s.pct}%</div>`}</div>${ok?`<div class="row-btns"><button class="btn-gold" data-trkcert="${f.k}">⤓ PNG</button></div>`:`<p class="note">${ar?'خلّص كل الدروس وعلّم المهام الأربعة "جرّبتها" في مكتبة المجالات.':'Complete every lesson and mark the four tasks as “Practised” in the field library.'}</p>`}`;
return h}
function trackCertSVG(f){const nm=esc((ST.profile&&ST.profile.name)||ST.name||'—');const d=new Date().toISOString().slice(0,10);const qr=QR_PLATFORM.replace(/\s(width|height)="[^"]*"/g,'').replace(/<svg/,'<svg x="1010" y="560" width="140" height="140"').replace(/<path/,'<rect width="37" height="37" fill="#fff"/><path');
return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 760" width="1200" height="760"><rect width="1200" height="760" fill="#13284B"/><rect x="28" y="28" width="1144" height="704" fill="none" stroke="#D9B44A" stroke-width="3"/><text x="80" y="130" font-family="Amiri,serif" font-size="34" fill="#F1D27A">Claude Mastery · د. سارة سالم</text><text x="80" y="230" font-family="Arial" font-size="56" font-weight="700" fill="#fff">Field track certificate</text><text x="80" y="290" font-family="Arial" font-size="30" fill="#C7D1E2">${esc(f.t.en)} · ${esc(f.t.ar)}</text><text x="80" y="400" font-family="Arial" font-size="24" fill="#C7D1E2">Awarded to</text><text x="80" y="465" font-family="Arial" font-size="52" font-weight="700" fill="#F1D27A">${nm}</text><text x="80" y="560" font-family="Arial" font-size="22" fill="#C7D1E2">${trackLessons(f.k).length} lessons · 4 practical tasks · ${d}</text><text x="80" y="680" font-family="Arial" font-size="20" fill="#93A2BC">Dr. Sara Salem — Creator &amp; instructor</text>${qr}</svg>`}
async function svgToPng(svg,w,h){const url='data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(svg)));const img=new Image();await new Promise((r,j)=>{img.onload=r;img.onerror=j;img.src=url});const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);return await new Promise(r=>c.toBlob(r,'image/png'))}

// ---------- 13. Recipe cards ----------
function recipeHTML(k){const f=fieldOf(k);const ar=LANG==='ar';
const items=f.tasks.map(t=>({t:L(t.t),src:L(CAD[t.c]),p:L(t.p)})).concat(LAB.filter(c=>c.field.en===LABFIELD[k]).slice(0,6).map(c=>({t:L(c.t),src:ar?'حالة معمل':'Lab case',p:L(c.p)}))).slice(0,10);
const one=x=>{const role=block(x.p,'role'),task=block(x.p,'task'),out=block(x.p,'output_format').split('\n')[0];return `<div class="rc"><div class="rcsrc">${esc(x.src)}</div><b>${esc(x.t)}</b>${role?`<div><i>${ar?'الدور':'Role'}:</i> ${esc(role)}</div>`:''}${task?`<div><i>${ar?'المهمة':'Task'}:</i> ${esc(task)}</div>`:''}${out?`<div><i>${ar?'المخرج':'Output'}:</i> ${esc(out)}</div>`:''}</div>`};
return `<div class="exdoc" dir="${ar?'rtl':'ltr'}"><div class="exhead"><div><div class="sig">${ar?'كارت الوصفات':'Recipe card'} · Claude Mastery</div><h1>${f.icon} ${esc(L(f.t))} — ${ar?'أهم 10 برومبتات ماستر':'top 10 master prompts'}</h1><p>${ar?'كل وصفة: الدور + المهمة + المخرج. البرومبت الكامل في المنصة.':'Each recipe: role + task + output. Full prompts on the platform.'}</p></div><div class="qr" style="width:80px">${QR_PLATFORM}</div></div><style>.rcg{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.rc{border:1px solid #D6DCE6;border-radius:8px;padding:8px 10px;font-size:10.5px;line-height:1.45;background:#F7F9FC}.rc b{display:block;color:#13284B;font-size:12px;margin-bottom:3px}.rc i{color:#9C7614;font-style:normal;font-weight:600}.rcsrc{font-size:9.5px;color:#7A869A}</style><div class="rcg">${items.map(one).join('')}</div><p class="note">Claude Mastery · ${PLATFORM_URL}</p></div>`}
async function recipeDownload(k,btn){const old=btn.textContent;btn.disabled=true;btn.textContent=LANG==='ar'?'جاري…':'Working…';try{await pkPDF(recipeHTML(k),`Recipe-card-${fieldOf(k).t.en.replace(/[^A-Za-z]+/g,'-')}-${LANG.toUpperCase()}.pdf`);btn.textContent='✓'}catch(e){console.error(e);btn.textContent=LANG==='ar'?'حصلت مشكلة':'Failed'}btn.disabled=false;setTimeout(()=>btn.textContent=old,2500)}

// ---------- 12. Module projects ----------
const projOf=n=>PROJECTS.find(p=>p.n==n);
function projCard(n){const p=projOf(n);if(!p)return '';const ar=LANG==='ar';const st=ST.proj[n]||{};const r=st.res;
let h=`<section class="projcard"><div class="k">🛠 ${ar?'مشروع الموديول':'Module project'} ${n}</div><h2 style="margin:4px 0 8px">${L(p.t)}</h2><p>${L(p.brief)}</p><p class="note">${ar?'المطلوب':'Deliverable'}: ${L(p.deliv)}</p>
<div class="tablewrap"><table><tr><th>${ar?'معيار التقييم':'Rubric'}</th><th>${ar?'الدرجة':'Points'}</th>${r?`<th>${ar?'درجتك':'You'}</th>`:''}</tr>${p.rub.map(c=>`<tr><td>${L(c.t)}</td><td>25</td>${r?`<td><b>${(r.scores&&r.scores[c.k])??'-'}</b></td>`:''}</tr>`).join('')}</table></div>`;
if(PRINT)return h+`</section>`;
h+=`<label class="pbf"><b>${ar?'تسليمك':'Your submission'}</b><textarea class="search" rows="8" dir="auto" data-pjtxt="${n}" placeholder="${ar?'الصق شغلك هنا…':'Paste your work here…'}">${esc(st.text||'')}</textarea></label><label class="pbf"><b>${ar?'لينك (اختياري)':'Link (optional)'}</b><input class="search" data-pjlink="${n}" value="${esc(st.link||'')}" placeholder="https://"></label>
<div class="row-btns"><button class="btn-gold" data-pjgrade="${n}" ${PJBUSY?'disabled':''}>${PJBUSY===n?(ar?'Claude بيقيّم…':'Claude is grading…'):(ar?'قيّم مع Claude':'Grade with Claude')}</button>${r?`<span class="pkscore ${r.total>=70?'hi':r.total>=50?'mid':'lo'}">${r.total}/100</span>`:''}</div><p class="note" id="pjnote${n}"></p>`;
if(r)h+=`<div class="elmbox">${r.total>=70?`<b>✓ ${ar?'نجحت':'Passed'}</b> · `:''}${(r.strengths||[]).length?`<b>${ar?'نقط القوة':'Strengths'}:</b> ${esc(r.strengths.join(' · '))}<br>`:''}${(r.improve||[]).length?`<b>${ar?'حسّن':'Improve'}:</b> ${esc(r.improve.join(' · '))}<br>`:''}${r.next?`<b>${ar?'الخطوة الجاية':'Next step'}:</b> ${esc(r.next)}`:''}</div>`;
return h+`</section>`}
let PJBUSY=0;
async function projGrade(n){const ar=LANG==='ar';const p=projOf(n);const st=ST.proj[n]||(ST.proj[n]={});const note=t=>{const e=document.getElementById('pjnote'+n);if(e)e.textContent=t};
if(!(st.text||'').trim()){note(ar?'الصق شغلك الأول.':'Paste your work first.');return}
const sample=await tutorSample();if(!sample){note(ar?'التقييم بيشتغل لما المنصة تتفتح جوه Claude (claude.ai).':'Grading works when the platform is opened inside Claude (claude.ai).');return}
PJBUSY=n;render();
const ask=`You are grading a practical project in a Claude training course for business professionals. Be fair and specific. Project: ${p.t.en}. Brief: ${p.brief.en}. Deliverable: ${p.deliv.en}.\nRubric (each criterion 0-25): ${p.rub.map(c=>`${c.k} = ${c.t.en}`).join('; ')}.\nScore only what is in the submission; if something is missing, score it low and say so. Write strengths, improvements and next step in ${ar?'Egyptian Arabic':'English'}. Reply with JSON only: {"scores": {${p.rub.map(c=>`"${c.k}": integer`).join(', ')}}, "total": integer 0-100, "strengths": [up to 3 short strings], "improve": [up to 3 short strings], "next": "one sentence"}\n\nSUBMISSION:\n${st.text.slice(0,9000)}${st.link?`\nLink provided: ${st.link}`:''}`;
try{const j=await sample.json(ask,{modelTier:'default'});const sc=j.scores||{};const total=Math.max(0,Math.min(100,Math.round(p.rub.reduce((a,c)=>a+Math.max(0,Math.min(25,+sc[c.k]||0)),0))));
const first=!(st.res&&st.res.total>=70);st.res={scores:sc,total,strengths:(j.strengths||[]).map(String).slice(0,3),improve:(j.improve||[]).map(String).slice(0,3),next:String(j.next||''),at:new Date().toISOString()};saveST();if(total>=70&&first)addXP(25)}
catch(e){note(e&&e.code==='rate_limited'?(ar?'طلبات كتير — جرّب بعد شوية.':'Too many requests — try again in a moment.'):(ar?'مقدرتش أقيّم دلوقتي. جرّب تاني.':'Could not grade right now. Try again.'))}
PJBUSY=0;render()}
function vProjects(){crumb(L(UX13.projects));const ar=LANG==='ar';const passed=PROJECTS.filter(p=>ST.proj[p.n]&&ST.proj[p.n].res&&ST.proj[p.n].res.total>=70).length;
return `<h1>🛠 ${L(UX13.projects)}</h1><p class="lede">${ar?'مشروع عملي لكل موديول: مخرج حقيقي بيتقيّم مع Claude على 4 معايير (25 درجة لكل واحد). النجاح من 70.':'One practical project per module: a real deliverable graded with Claude on four criteria (25 points each). Pass mark 70.'}</p><p class="note">${passed}/${PROJECTS.length} ${ar?'مشروعات ناجحة':'projects passed'}</p><div class="grid">${PROJECTS.map(p=>{const r=ST.proj[p.n]&&ST.proj[p.n].res;return `<button class="card" data-go="day/${p.n}"><div class="k">${ar?'موديول':'Module'} ${p.n}${r?` · ${r.total}/100`:''}</div><h3>${r&&r.total>=70?'✓ ':''}${esc(L(p.t))}</h3><div class="k">${esc(L(p.brief))}</div></button>`}).join('')}</div>`}
{const _vd=vDay;vDay=function(n,uid){const h=_vd(n,uid);if(uid)return h;const i=h.lastIndexOf('<div class="pager">');const card=projCard(n);return i>0?h.slice(0,i)+card+h.slice(i):h+card}}

// ---------- events ----------
document.addEventListener('click',e=>{const g=s=>e.target.closest(s);let x;
if(x=g('[data-flk]')){FLK=x.dataset.flk;ST.flk=FLK;saveST();render();return}
if(x=g('[data-trk]')){FLK=x.dataset.trk;ST.flk=FLK;saveST();if(!location.hash.startsWith('#tracks'))go('tracks');else render();return}
if(x=g('[data-flgo]')){FLK=x.dataset.flgo;ST.flk=FLK;saveST();go('fields');return}
if(x=g('[data-trklab]')){LF.field=LABFIELD[x.dataset.trklab]||'all';LF.cat='all';labTab='cases';go('lab');return}
if(x=g('[data-fldata]')){const k=x.dataset.fldata;saveFile(k+'.csv',BOM+DATA[k].csv);return}
if(x=g('[data-flpack]')){fieldOf(x.dataset.flpack).tasks.forEach(t=>pkAdd(L(fieldOf(x.dataset.flpack).t)+' · '+L(t.t),t.p));return}
if(x=g('[data-recipe]')){recipeDownload(x.dataset.recipe,x);return}
if(x=g('[data-trkcert]')){const f=fieldOf(x.dataset.trkcert);svgToPng(trackCertSVG(f),2400,1520).then(b=>saveFile(`Claude-Mastery-${f.t.en.replace(/[^A-Za-z]+/g,'-')}-track-certificate.png`,b));return}
if(x=g('[data-pjgrade]')){if(!PJBUSY)projGrade(+x.dataset.pjgrade);return}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset&&t.dataset.fldone){const [k,c]=t.dataset.fldone.split(':');const a=ST.fl[k]||(ST.fl[k]=[]);if(!ST.flxp)ST.flxp=[];if(t.checked&&!a.includes(c)){a.push(c);if(!ST.flxp.includes(k+c)){ST.flxp.push(k+c);addXP(5)}}else if(!t.checked)ST.fl[k]=a.filter(y=>y!==c);saveST()}});
document.addEventListener('input',e=>{const t=e.target;if(t.dataset&&t.dataset.pjtxt){const n=t.dataset.pjtxt;(ST.proj[n]||(ST.proj[n]={})).text=t.value;clearTimeout(window._pjT);window._pjT=setTimeout(saveST,500)}if(t.dataset&&t.dataset.pjlink){const n=t.dataset.pjlink;(ST.proj[n]||(ST.proj[n]={})).link=t.value;saveST()}});
