// ===== FIELD LIBRARY (part 2) =====
F('cs','Customer service','خدمة العملاء','🎧',['tickets','customers'],[
['d','Daily ticket triage','فرز التذاكر اليومي',["Customer service team lead","Triage today’s new tickets","- Attached: tickets.csv (ticket, date, channel, language, text)\n- Categories: billing, delivery, product, account, complaint\n- Urgent: legal threat, safety, VIP, repeated contact","Agents start with the right tickets","- Category, urgency and sentiment per ticket\n- Arabic and English handled in their own language\n- Suggested first reply for urgent ones","Triage table + draft replies for urgent tickets."],["قائد فريق خدمة عملاء","افرز التذاكر الجديدة النهارده","- مرفق: tickets.csv (التذكرة، التاريخ، القناة، اللغة، النص)\n- الفئات: فواتير، توصيل، منتج، حساب، شكوى\n- العاجل: تهديد قانوني، أمان، عميل مهم، تواصل متكرر","الموظفين يبدأوا بالتذاكر الصح","- الفئة والاستعجال والانطباع لكل تذكرة\n- العربي والإنجليزي كل واحد بلغته\n- أول رد مقترح للعاجل","جدول الفرز + ردود مقترحة للعاجل."],
"42 tickets: delivery 18, billing 11 … · urgent 4 (2 repeated contacts, 1 legal threat, 1 VIP)","42 تذكرة: توصيل 18، فواتير 11 … · عاجل 4 (2 تواصل متكرر، 1 تهديد قانوني، 1 عميل مهم)"],
['w','Weekly top issues report','تقرير أهم المشاكل الأسبوعي',["Customer experience analyst","Find the week’s top contact reasons and root causes","- Attached: tickets.csv","Fixing root causes reduces tickets","- Top 5 reasons with counts and example quotes\n- Likely root cause and owning team\n- One fix per issue","Issues table + owner actions."],["محلل تجربة عملاء","طلّع أهم أسباب التواصل الأسبوع ده وجذورها","- مرفق: tickets.csv","حل الأسباب الجذرية بيقلل التذاكر","- أهم 5 أسباب بالعدد ومقتطفات\n- السبب الجذري المحتمل والفريق المسؤول\n- حل واحد لكل مشكلة","جدول المشاكل + إجراءات للمسؤولين."],
"#1 late delivery (31%) — courier cut-off moved to 2 pm · owner: logistics · fix: update website delivery promise","رقم 1 تأخير التوصيل (31%) — ميعاد شركة الشحن اتغير للساعة 2 · المسؤول: اللوجستيات · الحل: تحديث وعد التوصيل على الموقع"],
['m','Monthly churn-risk list','قائمة العملاء المعرضين للفقد الشهرية',["Customer success manager","Identify customers at risk of leaving","- Attached: customers.csv (segment, tenure, spend, orders 90d, tickets 90d, last order, NPS)","The team calls at-risk customers this month","- Risk factors explained per customer\n- Ranked by value at risk\n- Suggested conversation opener","At-risk list + call scripts."],["مدير نجاح عملاء","حدد العملاء المعرضين إنهم يمشوا","- مرفق: customers.csv (الشريحة، المدة، الصرف، الطلبات 90 يوم، التذاكر 90 يوم، آخر طلب، NPS)","الفريق هيكلّم العملاء المعرضين الشهر ده","- عوامل الخطر متشرحة لكل عميل\n- مترتبين بالقيمة المعرضة للخطر\n- بداية مقترحة للمكالمة","قائمة المعرضين + نصوص المكالمات."],
"18 customers at risk (EGP 640k monthly spend) — no order in 45+ days and 2+ tickets","18 عميل معرضين للخطر (صرف شهري 640 ألف جنيه) — مفيش طلب من 45+ يوم و2+ تذاكر"],
['y','Annual service standards review','المراجعة السنوية لمعايير الخدمة',["Head of customer service","Review our service standards and propose next year’s targets","- This year’s KPIs: first response, resolution time, CSAT, NPS [attach]\n- Benchmarks we trust: [paste sources]","Targets drive staffing and tools budget","- Current vs proposed target per KPI with reason\n- Staffing implication\n- Where AI drafting is allowed and where a human must answer","Standards table + staffing note + AI-use rules."],["رئيس خدمة العملاء","راجع معايير الخدمة واقترح مستهدفات السنة الجاية","- مؤشرات السنة دي: أول رد، وقت الحل، الرضا، NPS [ارفع]\n- مقارنات بنثق فيها: [الصق المصادر]","المستهدفات بتحدد العمالة وميزانية الأدوات","- الحالي مقابل المقترح لكل مؤشر بالسبب\n- أثرها على العمالة\n- فين مسموح الـ AI يكتب وفين لازم إنسان يرد","جدول المعايير + ملاحظة العمالة + قواعد استخدام الـ AI."],
"First response 4h → 2h (AI drafts, agent approves) · CSAT 82% → 86% · complaints always answered by a person","أول رد 4 ساعات ← ساعتين (الـ AI يكتب والموظف يعتمد) · الرضا 82% ← 86% · الشكاوى دايماً يرد عليها إنسان"]]);

F('pm','Project management','إدارة المشروعات','📋',['project'],[
['d','Daily stand-up summary','ملخص الاجتماع اليومي',["Project coordinator","Summarise today’s stand-up notes into actions","- Notes: [paste]\n- Plan: project.csv","Everyone leaves with clear actions","- Actions with owner and date\n- Blockers separated\n- Changes to the plan flagged","Action list + blockers + plan changes."],["منسق مشروع","لخّص ملاحظات الاجتماع اليومي لإجراءات","- الملاحظات: [الصق]\n- الخطة: project.csv","كل واحد يخرج بإجراءات واضحة","- إجراءات بمسؤول وتاريخ\n- المعوقات لوحدها\n- التغييرات على الخطة متعلّمة","قائمة الإجراءات + المعوقات + تغييرات الخطة."],
"Actions 6 · blocker: vendor API keys (owner: Ali, due Thu) · plan change: testing moves 3 days","إجراءات 6 · معوّق: مفاتيح API من المورد (المسؤول: علي، الخميس) · تغيير: الاختبار يتأخر 3 أيام"],
['w','Weekly status report','تقرير الحالة الأسبوعي',["Project manager","Write the weekly status report for the sponsor","- Attached: project.csv (task, owner, planned end, forecast end, % complete, budget, spent, depends on)","The sponsor decides on escalations","- RAG for schedule, budget and scope with reasons\n- Critical-path delays\n- Decisions needed from the sponsor","One page: RAG, milestones, risks, decisions."],["مدير مشروع","اكتب تقرير الحالة الأسبوعي للراعي","- مرفق: project.csv (المهمة، المسؤول، النهاية المخططة، المتوقعة، الإنجاز، الميزانية، المصروف، الاعتماد على)","الراعي بيقرر التصعيدات","- أخضر/أصفر/أحمر للجدول والميزانية والنطاق بالأسباب\n- تأخيرات المسار الحرج\n- القرارات المطلوبة من الراعي\n- كل حالة متبررة بأرقام من الخطة (الإنجاز، المصروف، التواريخ)","صفحة: الحالة، المراحل، المخاطر، القرارات."],
"Schedule: amber (data migration +6 days on critical path) · Budget: green (61% spent at 64% complete) · Decision: approve weekend migration","الجدول: أصفر (نقل البيانات +6 أيام على المسار الحرج) · الميزانية: أخضر (61% مصروف عند 64% إنجاز) · القرار: اعتماد النقل في الإجازة"],
['m','Monthly risk and issue review','مراجعة المخاطر والمشاكل الشهرية',["PMO analyst","Review the project risk and issue logs","- Logs: [attach]","Stale risks hide real problems","- Risks without update in 30 days flagged\n- Top 5 by score with mitigation status\n- Issues that should become change requests","Risk table + clean-up actions."],["محلل PMO","راجع سجل المخاطر والمشاكل للمشروع","- السجلات: [ارفع]","المخاطر القديمة بتخبّي مشاكل حقيقية","- المخاطر اللي متحدثتش من 30 يوم متعلّمة\n- أهم 5 بالدرجة وحالة التخفيف\n- المشاكل اللي لازم تبقى طلبات تغيير","جدول المخاطر + إجراءات التنضيف."],
"9 stale risks · top risk: key user availability during go-live (score 20) · 2 issues → change requests","9 مخاطر قديمة · أعلى خطر: توفر المستخدمين الأساسيين وقت التشغيل (درجة 20) · مشكلتين ← طلبات تغيير"],
['y','Annual portfolio review','مراجعة المحفظة السنوية',["Head of PMO","Review the project portfolio for next year’s planning","- Portfolio list with cost, benefits, status: [attach]\n- Strategy priorities: [paste]","Leadership chooses what to fund","- Each project scored on value, risk and strategic fit\n- Continue / change / stop recommendation\n- Capacity check","Portfolio table + funding recommendation."],["رئيس PMO","راجع محفظة المشروعات لتخطيط السنة الجاية","- قائمة المحفظة بالتكلفة والعائد والحالة: [ارفع]\n- أولويات الاستراتيجية: [الصق]","القيادة هتختار تموّل إيه","- كل مشروع متقيّم بالقيمة والخطر والتوافق\n- توصية نكمّل / نعدّل / نوقف\n- مراجعة الطاقة\n- كل توصية مربوطة بالدرجة وبالأولوية الاستراتيجية","جدول المحفظة + توصية التمويل."],
"23 projects: continue 15 · change 5 · stop 3 (EGP 7.4M freed for the CRM programme)","23 مشروع: نكمّل 15 · نعدّل 5 · نوقف 3 (7.4 مليون جنيه تتحرر لبرنامج CRM)"]]);

F('ceo','CEO','الرئيس التنفيذي','🧭',['kpis'],[
['d','Daily executive brief','الملخص التنفيذي اليومي',["Chief of staff","Prepare my daily brief","- Calendar: [paste]\n- Email and messages needing me: [paste]\n- KPIs: kpis.csv","I have 10 minutes before my first meeting","- Top 3 decisions today\n- Prep notes for each meeting\n- KPI exceptions only","Brief: decisions, meetings, exceptions — under 250 words."],["مدير مكتب","جهّز ملخصي اليومي","- الأجندة: [الصق]\n- الإيميلات والرسايل اللي محتاجاني: [الصق]\n- المؤشرات: kpis.csv","عندي 10 دقايق قبل أول اجتماع","- أهم 3 قرارات النهارده\n- ملاحظات تحضير لكل اجتماع\n- استثناءات المؤشرات بس","ملخص: القرارات، الاجتماعات، الاستثناءات — أقل من 250 كلمة."],
"Decide: approve Q4 hiring freeze exceptions · Meeting 11:00 bank: ask about FX line · KPI exception: DSO 71 days","قرار: اعتماد استثناءات تجميد التعيين للربع الرابع · اجتماع 11 مع البنك: اسأل عن خط العملة · استثناء: أيام التحصيل 71"],
['w','Weekly leadership agenda','أجندة القيادة الأسبوعية',["Chief of staff","Build this week’s leadership meeting agenda","- Open actions from last meeting: [paste]\n- Department updates: [paste]\n- KPIs: kpis.csv","The meeting should end with decisions, not updates","- Max 5 items, each with a decision question\n- Pre-reads named\n- Time per item","Agenda table + pre-read list."],["مدير مكتب","ابني أجندة اجتماع القيادة الأسبوع ده","- الإجراءات المفتوحة من الاجتماع اللي فات: [الصق]\n- تحديثات الأقسام: [الصق]\n- المؤشرات: kpis.csv","الاجتماع لازم يخلص بقرارات مش تحديثات","- 5 بنود بالكتير، كل بند بسؤال قرار\n- القراءات المسبقة متسمية\n- وقت لكل بند","جدول الأجندة + قائمة القراءات."],
"1. Pricing for Q4 (decide: +5% or hold?) 15 min · 2. Collections plan (approve escalation?) 10 min …","1. تسعير الربع الرابع (القرار: +5% ولا نثبّت؟) 15 دقيقة · 2. خطة التحصيل (نعتمد التصعيد؟) 10 دقايق …"],
['m','Monthly board update','تحديث مجلس الإدارة الشهري',["CEO’s strategy adviser","Draft the monthly board update letter","- KPIs and financials: [attach]\n- Key events: [paste]","The board wants signal, not noise","- Three messages: performance, risks, asks\n- Numbers consistent with the finance pack\n- Plain language","Two-page letter + KPI appendix."],["مستشار استراتيجي للرئيس التنفيذي","اكتب مسودة خطاب التحديث الشهري للمجلس","- المؤشرات والأرقام المالية: [ارفع]\n- أهم الأحداث: [الصق]","المجلس عايز الإشارة المهمة مش الدوشة","- 3 رسايل: الأداء، المخاطر، الطلبات\n- الأرقام متطابقة مع ملف المالية\n- لغة بسيطة","خطاب صفحتين + ملحق المؤشرات."],
"Performance: revenue +12% YoY, margin under pressure · Risk: FX on imported inputs · Ask: approve FX hedging policy","الأداء: الإيراد +12% عن السنة اللي فاتت، والهامش تحت ضغط · الخطر: العملة على المدخلات المستوردة · الطلب: اعتماد سياسة التحوط"],
['y','Annual strategy offsite pack','ملف اجتماع الاستراتيجية السنوي',["Strategy director","Prepare the pack for the annual strategy offsite","- Performance vs strategy: [attach]\n- Market and competitor notes: [paste]","Leadership sets next year’s 3–5 priorities","- Where we won and lost, with evidence\n- Three strategic options with trade-offs\n- Questions for each session","Pack outline + option papers + session questions."],["مدير الاستراتيجية","جهّز ملف اجتماع الاستراتيجية السنوي","- الأداء مقابل الاستراتيجية: [ارفع]\n- ملاحظات السوق والمنافسين: [الصق]","القيادة هتحدد 3–5 أولويات للسنة الجاية","- كسبنا وخسرنا فين بالأدلة\n- 3 اختيارات استراتيجية بالمفاضلات\n- أسئلة لكل جلسة","إطار الملف + أوراق الاختيارات + أسئلة الجلسات."],
"Option A: defend core (low risk) · B: expand to KSA (high growth, capital) · C: digital channel (medium)","اختيار أ: نحمي الأساس (خطر قليل) · ب: التوسع في السعودية (نمو عالي، رأس مال) · ج: قناة رقمية (متوسط)"]]);

F('legal','Legal','القانوني','⚖',['contracts'],[
['d','Daily contract intake','استقبال العقود اليومي',["In-house lawyer","Triage today’s contracts for review","- Contracts received: [attach]\n- Playbook: standard positions and red lines [paste]","Low-risk contracts should not wait in the queue","- Risk level per contract with the clauses that drive it\n- Deviations from the playbook quoted\n- Route: fast-track / full review","Intake table + routing."],["محامي داخلي","افرز العقود اللي وصلت النهارده للمراجعة","- العقود: [ارفع]\n- دليل التفاوض: المواقف المعتادة والخطوط الحمرا [الصق]","العقود قليلة الخطر متستناش في الطابور","- مستوى الخطر لكل عقد بالبنود اللي بتحدده\n- الاختلافات عن الدليل مقتبسة\n- المسار: سريع / مراجعة كاملة","جدول الاستقبال + المسار."],
"5 contracts: 3 fast-track (standard NDA) · 2 full review (unlimited liability, auto-renewal 3 years)","5 عقود: 3 سريع (اتفاقية سرية عادية) · 2 مراجعة كاملة (مسؤولية مفتوحة، تجديد تلقائي 3 سنين)"],
['w','Weekly renewals and notices','التجديدات والإخطارات الأسبوعية',["Contract manager","List contracts with notice deadlines in the next 60 days","- Attached: contracts.csv (party, type, value, start, end, notice days, auto-renew, owner)\n- Today: [date]","Missed notices lock us into bad renewals","- Notice deadline computed per contract\n- Auto-renewals highlighted\n- Owner reminder drafted","Deadline table + reminder emails."],["مدير عقود","طلّع العقود اللي مواعيد إخطارها في الـ 60 يوم الجايين","- مرفق: contracts.csv (الطرف، النوع، القيمة، البداية، النهاية، أيام الإخطار، تجديد تلقائي، المسؤول)\n- النهارده: [التاريخ]","الإخطارات اللي بتفوت بتقفلنا في تجديدات وحشة","- ميعاد الإخطار محسوب لكل عقد\n- التجديد التلقائي متعلّم\n- تذكير للمسؤول مكتوب","جدول المواعيد + إيميلات التذكير."],
"4 notices due: cleaning services (notice by 12 Oct, auto-renews 1 year, EGP 1.1M)","4 إخطارات: خدمات النظافة (الإخطار قبل 12 أكتوبر، تجديد تلقائي سنة، 1.1 مليون جنيه)"],
['m','Monthly litigation and claims summary','ملخص القضايا والمطالبات الشهري',["Head of legal","Summarise the litigation and claims portfolio","- Case list with status, exposure and next hearing: [attach]","Finance needs provisions; management needs risk view","- Exposure by case and probability band\n- Changes since last month\n- Provision suggestion for finance to assess","Portfolio table + changes + notes for finance."],["رئيس الشؤون القانونية","لخّص محفظة القضايا والمطالبات","- قائمة القضايا بالحالة والتعرض والجلسة الجاية: [ارفع]","المالية محتاجة المخصصات؛ والإدارة محتاجة صورة الخطر","- التعرض لكل قضية وشريحة الاحتمال\n- التغييرات من الشهر اللي فات\n- اقتراح مخصص المالية تقيّمه","جدول المحفظة + التغييرات + ملاحظات للمالية."],
"12 cases · total exposure EGP 8.6M · 2 probable (EGP 1.4M) → provision review","12 قضية · التعرض الكلي 8.6 مليون جنيه · 2 محتملين (1.4 مليون) ← مراجعة المخصص"],
['y','Annual legal risk and policy review','المراجعة السنوية للمخاطر والسياسات القانونية',["General counsel","Review our legal risk register and policies for the year ahead","- Risk register and policies list: [attach]\n- New laws and regulations: [paste official texts]","The board approves the legal risk appetite","- Each policy due for update with reason\n- New regulatory requirements mapped to owners\n- Top 5 legal risks with mitigations","Review memo + update plan."],["المستشار القانوني العام","راجع سجل المخاطر القانونية والسياسات للسنة الجاية","- سجل المخاطر وقائمة السياسات: [ارفع]\n- القوانين واللوائح الجديدة: [الصق النصوص الرسمية]","المجلس هيعتمد الشهية للمخاطر القانونية","- كل سياسة محتاجة تحديث بالسبب\n- المتطلبات الجديدة مربوطة بمسؤولين\n- أهم 5 مخاطر قانونية بإجراءات التخفيف","مذكرة المراجعة + خطة التحديث."],
"7 policies to update (data protection, AI use, procurement) · new requirement: e-invoicing for B2C → owner: finance","7 سياسات للتحديث (حماية البيانات، استخدام الـ AI، المشتريات) · متطلب جديد: الفاتورة الإلكترونية للأفراد ← المسؤول: المالية"]]);

F('trainer','Trainer','المدرّب','🎓',[],[
['d','Daily session plan','خطة الجلسة اليومية',["Corporate trainer","Plan today’s 90-minute session","- Topic and audience: [..]\n- Learning outcomes: [list]\n- Group level: [..]","Adults learn by doing, not by listening","- Timed agenda with at least 50% practice\n- One check for understanding per outcome\n- Materials list","Session plan table + exercise sheet."],["مدرّب شركات","خطط لجلسة النهارده (90 دقيقة)","- الموضوع والجمهور: [..]\n- نواتج التعلم: [قائمة]\n- مستوى المجموعة: [..]","الكبار بيتعلموا بالتطبيق مش بالسماع","- أجندة بالوقت وفيها 50% تطبيق على الأقل\n- اختبار فهم لكل ناتج\n- قائمة المواد","جدول خطة الجلسة + ورقة التمرين."],
"0–10 warm-up poll · 10–30 demo · 30–65 pairs exercise on real files · 65–80 debrief · 80–90 quiz","0–10 تصويت للتسخين · 10–30 عرض عملي · 30–65 تمرين ثنائي على ملفات حقيقية · 65–80 نقاش · 80–90 اختبار"],
['w','Weekly learner feedback summary','ملخص آراء المتدربين الأسبوعي',["Learning analyst","Summarise this week’s session feedback","- Feedback forms: [attach]","The next sessions improve quickly","- Ratings by session and trainer\n- Top themes with quotes\n- Three changes for next week","Feedback table + themes + changes."],["محلل تعلّم","لخّص آراء جلسات الأسبوع ده","- استمارات الرأي: [ارفع]","الجلسات الجاية تتحسن بسرعة","- التقييمات حسب الجلسة والمدرّب\n- أهم المواضيع بمقتطفات\n- 3 تغييرات للأسبوع الجاي","جدول الآراء + المواضيع + التغييرات."],
"Average 4.5/5 · theme: «more time on real files» (14 mentions) · change: cut slides from 25 to 12","المتوسط 4.5 من 5 · موضوع: «وقت أكتر على ملفات حقيقية» (14 مرة) · التغيير: الشرايح من 25 لـ 12"],
['m','Monthly assessment bank','بنك أسئلة شهري',["Assessment designer","Write this month’s assessment questions","- Lessons covered: [list]\n- Outcomes: [list]","Assessments must test application, not memory","- 10 scenario questions with 4 options\n- Explanation for the right answer\n- Mapped to outcomes","Question table + answer key."],["مصمم تقييم","اكتب أسئلة التقييم للشهر ده","- الدروس: [قائمة]\n- النواتج: [قائمة]","التقييم لازم يختبر التطبيق مش الحفظ","- 10 أسئلة سيناريو بـ 4 اختيارات\n- شرح للإجابة الصح\n- مربوطة بالنواتج","جدول الأسئلة + مفتاح الإجابات."],
"Q1 scenario: a forecast includes an unagreed loan — which prompt fix? (B) · outcome 2","س1 سيناريو: توقع فيه قرض محدش وافق عليه — أنهي تصليح للبرومبت؟ (ب) · الناتج 2"],
['y','Annual training needs analysis','تحليل الاحتياجات التدريبية السنوي',["Learning and development manager","Run the training needs analysis for next year","- Performance reviews and skill gaps: [attach]\n- Strategy priorities: [paste]","The L&D budget goes where it matters","- Gaps by department and level\n- Programmes proposed with audience and outcomes\n- Budget and measurement plan","TNA table + programme list + budget."],["مدير التعلم والتطوير","اعمل تحليل الاحتياجات التدريبية للسنة الجاية","- تقييمات الأداء وفجوات المهارات: [ارفع]\n- أولويات الاستراتيجية: [الصق]","ميزانية التدريب تروح للمكان الصح","- الفجوات حسب القسم والمستوى\n- برامج مقترحة بجمهورها ونواتجها\n- الميزانية وطريقة القياس","جدول الاحتياجات + قائمة البرامج + الميزانية."],
"Top gaps: data analysis (finance, sales), AI tools (all), negotiation (procurement) · 6 programmes · EGP 2.4M","أهم الفجوات: تحليل البيانات (المالية، المبيعات)، أدوات الـ AI (الكل)، التفاوض (المشتريات) · 6 برامج · 2.4 مليون جنيه"]]);

F('product','Product','المنتج','🧩',['customers','baskets'],[
['d','Daily feedback digest','ملخص آراء العملاء اليومي',["Product manager","Digest today’s customer feedback","- Reviews, tickets and survey comments: [paste]","The team sees what customers feel today","- Grouped by feature with counts\n- Bugs separated from requests\n- Quotes for the top 3","Digest table + quotes."],["مدير منتج","لخّص آراء العملاء النهارده","- التقييمات والتذاكر وتعليقات الاستبيان: [الصق]","الفريق يشوف العملاء حاسين بإيه النهارده","- متجمعة حسب الميزة بالعدد\n- الأعطال منفصلة عن الطلبات\n- مقتطفات لأهم 3","جدول الملخص + المقتطفات."],
"Checkout: 9 (4 bugs: card fails on Safari) · search: 6 requests for Arabic spelling tolerance","الدفع: 9 (4 أعطال: الكارت بيفشل على Safari) · البحث: 6 طلبات لتحمّل أخطاء الإملاء العربي"],
['w','Weekly product metrics','مؤشرات المنتج الأسبوعية',["Product analyst","Report this week’s product metrics","- Attached: customers.csv and baskets.csv\n- Metrics: active users, orders, basket size, repeat rate","The squad decides next week’s focus","- Metrics vs last week and target\n- One insight from basket analysis\n- Hypothesis to test","Metrics table + insight + test idea."],["محلل منتج","طلّع مؤشرات المنتج الأسبوع ده","- مرفق: customers.csv و baskets.csv\n- المؤشرات: المستخدمين النشطين، الطلبات، حجم السلة، التكرار","الفريق هيحدد تركيز الأسبوع الجاي","- المؤشرات مقابل الأسبوع اللي فات والمستهدف\n- ملاحظة واحدة من تحليل السلة\n- فرضية نختبرها","جدول المؤشرات + الملاحظة + فكرة الاختبار."],
"Repeat rate 34% (+2 pts) · coffee + croissant bought together in 41% of baskets → test a bundle","التكرار 34% (+2 نقطة) · قهوة + كرواسون في 41% من السلال ← نجرّب باقة"],
['m','Monthly roadmap review','مراجعة خارطة الطريق الشهرية',["Head of product","Re-prioritise the roadmap for next month","- Backlog with effort estimates: [attach]\n- Goals: [paste]","We build what moves the goals","- RICE score per item with inputs shown\n- Top 5 for next month\n- What we explicitly will not do","Prioritised table + not-now list."],["رئيس المنتج","أعد ترتيب أولويات خارطة الطريق للشهر الجاي","- قائمة المهام بتقديرات المجهود: [ارفع]\n- الأهداف: [الصق]","نبني اللي بيحرّك الأهداف","- درجة RICE لكل بند والمدخلات ظاهرة\n- أهم 5 للشهر الجاي\n- اللي مش هنعمله بوضوح","جدول الأولويات + قائمة مش دلوقتي."],
"Top: fix Safari checkout (RICE 840) · Arabic search tolerance (610) · Not now: dark mode","الأول: تصليح الدفع على Safari (840) · تحمّل أخطاء البحث العربي (610) · مش دلوقتي: الوضع الليلي"],
['y','Annual product strategy','استراتيجية المنتج السنوية',["Chief product officer","Draft next year’s product strategy","- Market research and customer insights: [attach]\n- Business goals: [paste]","The strategy guides every squad","- Vision, target customers and bets\n- Measurable outcomes per bet\n- Risks and assumptions to test early","Strategy document + outcome table."],["مسؤول المنتج الأول","اكتب مسودة استراتيجية المنتج للسنة الجاية","- أبحاث السوق ورؤى العملاء: [ارفع]\n- أهداف الشركة: [الصق]","الاستراتيجية بتوجّه كل فريق","- الرؤية والعملاء المستهدفين والرهانات\n- نتايج قابلة للقياس لكل رهان\n- المخاطر والافتراضات نختبرها بدري","مستند الاستراتيجية + جدول النتايج."],
"Bet 1: subscriptions (target 20% of revenue) · Bet 2: B2B ordering portal · Assumption to test: willingness to pay monthly","رهان 1: الاشتراكات (المستهدف 20% من الإيراد) · رهان 2: بوابة طلبات للشركات · افتراض نختبره: الاستعداد للدفع الشهري"]]);

F('academic','Academic','أكاديمي','📚',[],[
['d','Daily reading notes','ملاحظات القراية اليومية',["Research assistant","Summarise today’s papers for my literature review","- Papers: [attach PDFs]\n- My research question: [..]","Notes must be reusable when I write","- Per paper: question, method, sample, findings, limitations\n- Relevance to my question in one line\n- Quotes with page numbers only from the text","Notes table + citation list in APA."],["مساعد بحثي","لخّص أبحاث النهارده للمراجعة الأدبية","- الأبحاث: [ارفع PDF]\n- سؤال البحث بتاعي: [..]","الملاحظات لازم تنفع لما أكتب","- لكل بحث: السؤال، المنهج، العينة، النتايج، القيود\n- علاقته بسؤالي في سطر\n- الاقتباسات بأرقام الصفحات من النص بس","جدول الملاحظات + قائمة المراجع APA."],
"Paper 1: Smith (2024) · survey of 412 SMEs · AI adoption ↑ with manager training · limitation: self-reported","بحث 1: سميث (2024) · استبيان 412 شركة صغيرة · تبني الـ AI بيزيد مع تدريب المديرين · القيد: بيانات ذاتية"],
['w','Weekly writing sprint','سباق الكتابة الأسبوعي',["Academic writing coach","Review this week’s draft section","- Draft: [paste]\n- Style guide: [APA / university]","My supervisor meets me on Thursday","- Argument flow and gaps\n- Claims without citations flagged\n- No rewriting — comments only","Comment table + three priorities."],["مدرّب كتابة أكاديمية","راجع الجزء اللي كتبته الأسبوع ده","- المسودة: [الصق]\n- دليل الأسلوب: [APA / الجامعة]","مشرفي هيقابلني الخميس","- تسلسل الحجة والفجوات\n- الادعاءات من غير مراجع متعلّمة\n- من غير إعادة كتابة — تعليقات بس","جدول التعليقات + 3 أولويات."],
"Gap: link between hypothesis 2 and the literature · 4 claims without citations · priority: tighten the method section","فجوة: الربط بين الفرضية 2 والأدبيات · 4 ادعاءات من غير مراجع · الأولوية: ضبط جزء المنهجية"],
['m','Monthly data analysis plan','خطة تحليل البيانات الشهرية',["Research methods adviser","Plan the analysis for my collected data","- Variables and scales: [list]\n- Hypotheses: [list]\n- Sample: [n, description]","The analysis must answer each hypothesis","- Test per hypothesis with assumptions to check\n- Steps in SPSS / R / Excel\n- How to report results","Analysis plan table + reporting template."],["مستشار مناهج بحث","خطط لتحليل البيانات اللي جمعتها","- المتغيرات والمقاييس: [قائمة]\n- الفرضيات: [قائمة]\n- العينة: [العدد، الوصف]","التحليل لازم يجاوب كل فرضية","- اختبار لكل فرضية والافتراضات اللي تتراجع\n- الخطوات في SPSS / R / Excel\n- إزاي تكتب النتايج","جدول خطة التحليل + قالب كتابة النتايج."],
"H1: Pearson correlation (check normality) · H2: regression with control variables · report with APA tables","ف1: ارتباط بيرسون (راجع الاعتدالية) · ف2: انحدار بمتغيرات ضابطة · الكتابة بجداول APA"],
['y','Annual research plan','خطة البحث السنوية',["Senior researcher","Plan my research year","- Projects and deadlines: [list]\n- Target journals and conferences: [list]\n- Research hours available per week: [n]","Output and quality both count","- Timeline by month with milestones\n- Submission targets matched to journals\n- Risks to the timeline","12-month plan + submission table."],["باحث أول","خطط لسنتي البحثية","- المشروعات والمواعيد: [قائمة]\n- المجلات والمؤتمرات المستهدفة: [قائمة]\n- ساعات البحث المتاحة في الأسبوع: [العدد]","الإنتاج والجودة الاتنين مهمين","- جدول شهري بالمراحل\n- مستهدفات النشر مربوطة بالمجلات ومواعيد التقديم\n- مخاطر على الجدول وخطة بديلة لكل خطر","خطة 12 شهر + جدول النشر."],
"Q1 finish data collection · Q2 submit paper 1 · Q3 conference · Q4 thesis chapter 4","الربع الأول إنهاء جمع البيانات · التاني تقديم البحث الأول · التالت مؤتمر · الرابع الفصل الرابع"]]);

F('cfo','CFO','المدير المالي','📊',['kpis','dcf_inputs','bva'],[
['d','Daily CFO dashboard note','ملاحظة لوحة المدير المالي اليومية',["Finance chief of staff","Write the CFO’s daily note","- Cash, FX, collections, key approvals pending: [paste]","The CFO decides in five minutes","- Exceptions only\n- Approvals waiting with deadlines\n- One risk to watch","Note under 150 words."],["مدير مكتب المالية","اكتب ملاحظة المدير المالي اليومية","- الكاش، العملة، التحصيل، الموافقات المعلقة: [الصق]","المدير المالي بيقرر في 5 دقايق","- الاستثناءات بس\n- الموافقات المعلقة بمواعيدها\n- خطر واحد للمتابعة","ملاحظة أقل من 150 كلمة."],
"Cash EGP 18.4M · FX need USD 85k Tuesday · 3 approvals (capex EGP 1.2M due today) · watch: C107 overdue 78 days","الكاش 18.4 مليون جنيه · احتياج 85 ألف دولار التلات · 3 موافقات (استثمار 1.2 مليون مطلوب النهارده) · متابعة: C107 متأخر 78 يوم"],
['w','Weekly cash and FX committee','لجنة الكاش والعملة الأسبوعية',["Treasury and FP&A lead","Prepare the weekly cash and FX committee paper","- 13-week cash forecast: [attach]\n- FX exposures and bank lines: [paste]","The committee sets payments and hedges for the week","- Lowest cash week and cause\n- FX exposure by currency vs policy\n- Decisions requested","Two-page paper + decision list."],["مسؤول الخزينة والتخطيط المالي","جهّز ورقة لجنة الكاش والعملة الأسبوعية","- توقع الكاش 13 أسبوع: [ارفع]\n- التعرض للعملة وخطوط البنوك: [الصق]","اللجنة بتحدد المدفوعات والتحوط للأسبوع","- أقل أسبوع كاش وسببه\n- التعرض للعملة مقابل السياسة\n- القرارات المطلوبة","ورقة صفحتين + قائمة القرارات."],
"Lowest week 9 (EGP 2.1M) — tax payment · USD exposure 74% hedged (policy 60–80%) · decide: roll USD 1M forward","أقل أسبوع رقم 9 (2.1 مليون جنيه) — دفعة ضرايب · الدولار متغطي 74% (السياسة 60–80%) · القرار: تمديد عقد آجل بمليون دولار"],
['m','Monthly investor and bank update','تحديث المستثمرين والبنوك الشهري',["CFO","Draft the monthly update for investors and lending banks","- Results and KPIs: kpis.csv and bva.csv\n- Covenant tests: [paste]","Trust comes from consistent, early disclosure","- Results vs budget and last year\n- Covenants with headroom\n- Outlook and risks, no forward-looking promises\n- Every figure ties to the monthly finance pack","Letter + appendix tables."],["المدير المالي","اكتب مسودة التحديث الشهري للمستثمرين والبنوك","- النتايج والمؤشرات: kpis.csv و bva.csv\n- اختبارات التعهدات: [الصق]","الثقة بتيجي من الإفصاح الثابت والبدري","- النتايج مقابل الموازنة والسنة اللي فاتت\n- التعهدات بالمساحة المتبقية\n- التوقعات والمخاطر من غير وعود مستقبلية","خطاب + جداول ملحقة."],
"Revenue +12% YoY · EBITDA 8% below budget · covenants met (DSCR 1.31, headroom 5%)","الإيراد +12% عن السنة اللي فاتت · الـ EBITDA أقل من الموازنة 8% · التعهدات متحققة (DSCR 1.31، مساحة 5%)"],
['y','Annual valuation and capital plan','التقييم وخطة رأس المال السنوية',["Corporate finance director","Update the valuation and propose the capital plan","- Attached: dcf_inputs.csv\n- Business plan: [attach]","The board decides dividends, debt and investment","- DCF with assumptions shown and sensitivity on WACC and growth\n- Capital options: dividends, debt paydown, capex\n- Recommendation framed for board judgement","Valuation summary + sensitivity grid + capital options table."],["مدير تمويل الشركات","حدّث التقييم واقترح خطة رأس المال","- مرفق: dcf_inputs.csv\n- خطة العمل: [ارفع]","المجلس بيقرر الأرباح والدين والاستثمار","- تدفقات مخصومة بافتراضات ظاهرة وحساسية لتكلفة رأس المال والنمو\n- اختيارات رأس المال: أرباح، سداد دين، استثمار\n- التوصية لحكم المجلس","ملخص التقييم + جدول الحساسية + جدول الاختيارات."],
"Equity value EGP 1.42bn (WACC 22%, g 8%) · range 1.25–1.63bn · option: pay down 30% of debt, keep dividend","قيمة حقوق الملكية 1.42 مليار جنيه (تكلفة رأس المال 22%، نمو 8%) · المدى 1.25–1.63 مليار · اختيار: سداد 30% من الدين مع ثبات التوزيعات"]]);

F('ea','Executive assistant','المساعد التنفيذي','🗂',[],[
['d','Daily inbox and calendar triage','فرز الإيميل والأجندة اليومي',["Executive assistant to [role]","Triage the inbox and calendar for today","- Emails: [paste or connect]\n- Calendar: [paste]\n- My manager’s priorities: [list]","My manager focuses on what matters","- Emails sorted: act today, delegate, file\n- Draft replies for routine ones\n- Calendar conflicts with suggestions","Triage list + draft replies + calendar notes."],["مساعد تنفيذي لـ [الدور]","افرز الإيميل والأجندة للنهارده","- الإيميلات: [الصق أو اربط]\n- الأجندة: [الصق]\n- أولويات مديري: [قائمة]","مديري يركّز على المهم","- الإيميلات متقسمة: يتعمل النهارده، يتفوّض، يتحفظ\n- ردود مقترحة للروتيني\n- تعارضات الأجندة باقتراحات","قائمة الفرز + الردود + ملاحظات الأجندة."],
"Act today 4 · delegate 7 · file 22 · conflict: 3 pm board call overlaps with the bank — propose bank at 4:30","يتعمل النهارده 4 · يتفوّض 7 · يتحفظ 22 · تعارض: مكالمة المجلس 3 العصر مع البنك — اقتراح البنك 4:30"],
['w','Weekly meeting prep pack','ملف تحضير الاجتماعات الأسبوعي',["Executive assistant","Prepare briefing notes for next week’s external meetings","- Meeting list with attendees: [paste]\n- Past notes and emails: [attach]","No meeting starts unprepared","- Per meeting: purpose, who is who, history, open items, ask\n- One page each","Briefing notes."],["مساعد تنفيذي","جهّز ملاحظات تحضير لاجتماعات الأسبوع الجاي الخارجية","- قائمة الاجتماعات والحضور: [الصق]\n- ملاحظات وإيميلات سابقة: [ارفع]","مفيش اجتماع يبدأ من غير تحضير","- لكل اجتماع: الهدف، مين مين، التاريخ، البنود المفتوحة، الطلب\n- صفحة لكل واحد","ملاحظات التحضير."],
"Bank X, Tue 11:00 · purpose: FX line renewal · open item: collateral release · ask: +USD 2M limit","البنك X، التلات 11 · الهدف: تجديد خط العملة · بند مفتوح: فك الضمان · الطلب: زيادة الحد مليونين دولار"],
['m','Monthly travel and expense reconciliation','مطابقة السفر والمصروفات الشهرية',["Executive assistant","Reconcile my manager’s travel and expenses for the month","- Card statement and receipts: [attach]\n- Policy limits: [paste]","Claims go in on time and within policy","- Each item matched to a receipt\n- Missing receipts and over-policy items listed\n- Claim summary by category","Reconciliation table + claim summary."],["مساعد تنفيذي","طابق سفر ومصروفات مديري للشهر","- كشف الكارت والإيصالات: [ارفع]\n- حدود السياسة: [الصق]","المطالبات تتقدم في ميعادها وفي حدود السياسة","- كل بند متطابق مع إيصال\n- الإيصالات الناقصة والبنود فوق السياسة متسجلة\n- ملخص المطالبة حسب الفئة","جدول المطابقة + ملخص المطالبة."],
"31 items matched · 2 receipts missing · 1 hotel night over limit by EGP 900","31 بند متطابق · إيصالين ناقصين · ليلة فندق فوق الحد بـ 900 جنيه"],
['y','Annual calendar plan','خطة الأجندة السنوية',["Executive assistant","Build my manager’s annual calendar","- Board, committee and budget dates: [list]\n- Public holidays and Ramadan dates: [paste official sources]\n- Personal priorities: [..]","Big rocks go in first","- Fixed governance dates first\n- Travel blocks and focus time\n- Clashes flagged","12-month calendar table."],["مساعد تنفيذي","ابني الأجندة السنوية لمديري","- مواعيد المجلس واللجان والموازنة: [قائمة]\n- الإجازات الرسمية ومواعيد رمضان: [الصق من مصادر رسمية]\n- الأولويات الشخصية: [..]","الحاجات الكبيرة تتحط الأول","- مواعيد الحوكمة الثابتة الأول\n- فترات السفر ووقت التركيز\n- التعارضات متعلّمة","جدول أجندة 12 شهر."],
"Board: 4 meetings (Feb, May, Aug, Nov) · budget season Oct · focus Fridays · clash: AGM in Ramadan week 2","المجلس: 4 اجتماعات (فبراير، مايو، أغسطس، نوفمبر) · موسم الموازنة أكتوبر · الجمعة للتركيز · تعارض: الجمعية العمومية في تاني أسبوع رمضان"]]);

F('accounting','Accounting','المحاسبة','🧾',['bank_gl','ap_aging','ar_aging'],[
['d','Daily bank matching','مطابقة البنك اليومية',["Accountant","Match yesterday’s bank lines to the ledger","- Attached: bank_gl.csv","Unmatched items must be cleared daily","- Matched by amount, date ±3 days and reference\n- Unmatched listed with likely reason\n- No journal posted without review","Matching table + suggested journals."],["محاسب","طابق حركات البنك امبارح مع الدفاتر","- مرفق: bank_gl.csv","البنود غير المطابقة لازم تتسوى كل يوم","- المطابقة بالمبلغ والتاريخ ±3 أيام والمرجع\n- غير المطابق متسجل بالسبب المحتمل\n- مفيش قيد يتسجل من غير مراجعة","جدول المطابقة + قيود مقترحة."],
"58 matched · 3 unmatched: bank charges EGP 1,250 (suggest JE), customer transfer without reference (ask sales)","58 مطابق · 3 غير مطابقين: مصاريف بنكية 1,250 جنيه (قيد مقترح)، تحويل عميل من غير مرجع (اسأل المبيعات)"],
['w','Weekly payables run','دورة المدفوعات الأسبوعية',["Accounts payable lead","Prepare this week’s supplier payment run","- Attached: ap_aging.csv\n- Payment terms and approvals: [paste]","Pay on time without breaching cash limits","- Due and overdue invoices\n- Duplicates and missing approvals flagged\n- Total by currency","Payment proposal + exceptions."],["مسؤول الدائنين","جهّز دورة مدفوعات الموردين للأسبوع ده","- مرفق: ap_aging.csv\n- شروط الدفع والموافقات: [الصق]","ندفع في الميعاد من غير ما نكسر حدود الكاش","- الفواتير المستحقة والمتأخرة\n- المكرر والناقص موافقة متعلّم\n- الإجمالي حسب العملة","مقترح الدفع + الاستثناءات."],
"Pay 24 invoices: EGP 3.6M, USD 120k · 1 possible duplicate (same amount and supplier within 3 days)","دفع 24 فاتورة: 3.6 مليون جنيه، 120 ألف دولار · فاتورة محتملة التكرار (نفس المبلغ والمورد في 3 أيام)"],
['m','Monthly close checklist','قائمة الإقفال الشهري',["Chief accountant","Run the month-end close checklist","- Checklist and owners: [paste]\n- Trial balance: [attach]","The close finishes on working day 5","- Each task: done, in progress, blocked\n- Accounts with unusual movement vs last month flagged\n- Accruals and prepayments reviewed","Close tracker + unusual movements list."],["رئيس الحسابات","شغّل قائمة الإقفال الشهري","- القائمة والمسؤولين: [الصق]\n- ميزان المراجعة: [ارفع]","الإقفال يخلص خامس يوم عمل","- كل مهمة: خلصت، شغالة، متوقفة\n- الحسابات اللي حركتها غريبة عن الشهر اللي فات متعلّمة\n- المستحقات والمدفوعات مقدماً متراجعة\n- المهام المتوقفة ليها سبب ومسؤول وميعاد","متابعة الإقفال + قائمة الحركات الغريبة."],
"18/22 tasks done · blocked: inventory count sign-off · unusual: repairs +180% vs last month","18 من 22 مهمة خلصت · متوقف: اعتماد الجرد · غريب: الصيانة +180% عن الشهر اللي فات"],
['y','Annual audit preparation','التحضير للمراجعة السنوية',["Financial reporting manager","Prepare for the external audit","- Auditor’s request list (PBC): [attach]\n- Last year’s management letter: [attach]","A smooth audit saves fees and time","- Each request with owner, due date and status\n- Last year’s findings with remediation evidence\n- Draft notes that changed","PBC tracker + findings follow-up."],["مدير التقارير المالية","جهّز للمراجعة الخارجية","- قائمة طلبات المراجع: [ارفع]\n- خطاب الإدارة السنة اللي فاتت: [ارفع]","المراجعة السلسة بتوفّر أتعاب ووقت","- كل طلب بمسؤول وميعاد وحالة\n- ملاحظات السنة اللي فاتت بدليل التصحيح\n- مسودة الإيضاحات اللي اتغيرت","متابعة الطلبات + متابعة الملاحظات."],
"PBC 86 items: 61 ready · 3 prior findings closed with evidence, 1 open (fixed asset tagging)","طلبات 86: 61 جاهزين · 3 ملاحظات قديمة اتقفلت بالدليل، 1 مفتوحة (ترقيم الأصول الثابتة)"]]);

F('fpa','FP&A','التخطيط والتحليل المالي','📉',['bva','sales_monthly'],[
['d','Daily flash sales','المبيعات اللحظية اليومية',["FP&A analyst","Report yesterday’s sales vs plan","- Sales extract: [paste]\n- Daily plan: [paste]","Leaders react within the month, not after","- Day and month-to-date vs plan\n- Top 3 drivers of the gap\n- Run-rate to month end","Five-line flash + small table."],["محلل FP&A","طلّع مبيعات امبارح مقابل الخطة","- استخراج المبيعات: [الصق]\n- الخطة اليومية: [الصق]","القيادة تتصرف جوه الشهر مش بعده","- اليوم ومن أول الشهر مقابل الخطة\n- أهم 3 أسباب للفرق\n- المعدل لحد آخر الشهر","نشرة 5 سطور + جدول صغير."],
"MTD EGP 21.4M (−3% vs plan) · gap from Delta (−1.1M) · run-rate to month end 44.0M vs plan 45.5M","من أول الشهر 21.4 مليون جنيه (−3% عن الخطة) · الفرق من الدلتا (−1.1) · المعدل لآخر الشهر 44.0 مقابل خطة 45.5"],
['w','Weekly rolling forecast','التوقع المتجدد الأسبوعي',["FP&A manager","Update the rolling forecast with this week’s information","- Attached: sales_monthly.csv\n- Pipeline and known events: [paste]","The CFO sees the landing for the quarter","- Forecast by month with method stated\n- Change vs last week explained\n- Upside and downside","Forecast table + bridge + risks."],["مدير FP&A","حدّث التوقع المتجدد بمعلومات الأسبوع ده","- مرفق: sales_monthly.csv\n- الـ pipeline والأحداث المعروفة: [الصق]","المدير المالي يشوف هنقفل الربع فين","- التوقع لكل شهر والطريقة متوضحة\n- التغيير عن الأسبوع اللي فات متشرح\n- سيناريو أفضل وأسوأ","جدول التوقع + الجسر + المخاطر."],
"Q4 landing EGP 138M (−2M vs last week: one tender delayed) · range 131–144M","نهاية الربع الرابع 138 مليون جنيه (−2 عن الأسبوع اللي فات: مناقصة اتأجلت) · المدى 131–144"],
['m','Monthly variance deep dive','تحليل الانحرافات العميق الشهري',["Senior FP&A analyst","Explain this month’s variances with price, volume and mix","- Attached: bva.csv and sales_monthly.csv","Management needs causes, not just numbers","- Revenue bridge: price, volume, mix\n- Cost variances by driver\n- Actions with owners","Bridge chart data + commentary."],["محلل FP&A أول","اشرح انحرافات الشهر ده بالسعر والكمية والمزيج","- مرفق: bva.csv و sales_monthly.csv","الإدارة محتاجة الأسباب مش الأرقام بس","- جسر الإيراد: سعر، كمية، مزيج\n- انحرافات التكلفة حسب المحرك\n- إجراءات بمسؤولين","بيانات رسم الجسر + الشرح."],
"Revenue gap −EGP 1.4M: price +0.6M, volume −2.3M, mix +0.3M","فرق الإيراد −1.4 مليون جنيه: سعر +0.6، كمية −2.3، مزيج +0.3"],
['y','Annual budget build','بناء الموازنة السنوية',["FP&A lead","Consolidate department budgets into the company budget","- Department submissions: [attach]\n- Assumptions pack: [attach]","The executive committee approves the budget","- Submissions checked against assumptions\n- Gaps to target with options\n- P&L, cash and headcount consistent","Consolidated budget + gap options + checks list."],["مسؤول FP&A","جمّع موازنات الأقسام في موازنة الشركة","- موازنات الأقسام: [ارفع]\n- ملف الافتراضات: [ارفع]","اللجنة التنفيذية هتعتمد الموازنة","- الموازنات متراجعة مقابل الافتراضات\n- الفجوة عن المستهدف باختيارات\n- قائمة الدخل والكاش والعمالة متسقين","الموازنة المجمعة + اختيارات الفجوة + قائمة المراجعات."],
"Consolidated EBITDA EGP 82M vs target 90M · options: pricing +3% (+5M), hiring delay (+2M)","الـ EBITDA المجمع 82 مليون جنيه مقابل مستهدف 90 · الاختيارات: تسعير +3% (+5)، تأجيل تعيين (+2)"]]);

F('treasury','Treasury','الخزينة','🏛',['ap_aging','ar_aging'],[
['d','Daily cash position','مركز الكاش اليومي',["Treasury analyst","Prepare today’s cash position across banks","- Bank balances: [paste]\n- Today’s expected receipts (ar_aging.csv) and payments (ap_aging.csv)","Idle cash costs money; shortfalls cost more","- Position by bank and currency\n- Surplus to invest or shortfall to fund\n- Limits by bank respected","Position table + recommended moves."],["محلل خزينة","جهّز مركز الكاش النهارده في كل البنوك","- أرصدة البنوك: [الصق]\n- المقبوضات المتوقعة (ar_aging.csv) والمدفوعات (ap_aging.csv) النهارده","الكاش العاطل بيكلّف؛ والعجز بيكلّف أكتر","- المركز حسب البنك والعملة\n- فائض للاستثمار أو عجز للتمويل\n- حدود كل بنك متراعية","جدول المركز + التحركات المقترحة."],
"Surplus EGP 6.2M → place 5M overnight at Bank A (within limit) · USD short 85k Tuesday","فائض 6.2 مليون جنيه ← إيداع 5 مليون ليلة في البنك أ (في حدوده) · عجز 85 ألف دولار التلات"],
['w','Weekly 13-week cash forecast','توقع الكاش 13 أسبوع الأسبوعي',["Treasury manager","Roll the 13-week cash forecast","- Last week’s forecast vs actual: [attach]\n- AR and AP: ar_aging.csv, ap_aging.csv","Funding decisions need a reliable view","- Forecast accuracy for last week\n- Lowest balance week and cause\n- Funding or investment actions","13-week table + accuracy note + actions."],["مدير خزينة","حدّث توقع الكاش 13 أسبوع","- توقع الأسبوع اللي فات مقابل الفعلي: [ارفع]\n- المديونيات والدائنين: ar_aging.csv و ap_aging.csv","قرارات التمويل محتاجة صورة موثوقة","- دقة التوقع للأسبوع اللي فات كنسبة\n- أقل أسبوع رصيد وسببه\n- إجراءات تمويل أو استثمار في حدود البنوك","جدول 13 أسبوع + ملاحظة الدقة + الإجراءات."],
"Accuracy 94% · lowest week 9 (EGP 2.1M) — tax payment · action: draw EGP 5M revolving line in week 8","الدقة 94% · أقل أسبوع رقم 9 (2.1 مليون جنيه) — دفعة ضرايب · الإجراء: سحب 5 مليون من الخط المتجدد في الأسبوع 8"],
['m','Monthly FX exposure report','تقرير التعرض للعملة الشهري',["Treasury risk analyst","Report FX exposures and hedges","- Exposures by currency and maturity: [attach]\n- Hedge book: [attach]\n- Policy: hedge 60–80% of 6-month exposure","The committee checks policy compliance","- Net exposure and hedge ratio by currency\n- Breaches flagged\n- Hedging options with cost","Exposure table + options."],["محلل مخاطر خزينة","طلّع تقرير التعرض للعملة والتحوط","- التعرض حسب العملة والاستحقاق: [ارفع]\n- عقود التحوط: [ارفع]\n- السياسة: تحوط 60–80% من تعرض 6 شهور","اللجنة بتراجع الالتزام بالسياسة","- صافي التعرض ونسبة التحوط لكل عملة\n- المخالفات متعلّمة\n- اختيارات تحوط بتكلفتها","جدول التعرض + الاختيارات."],
"USD 74% hedged (OK) · EUR 41% — BREACH (policy 60%) → option: forward EUR 1.2M","الدولار متغطي 74% (تمام) · اليورو 41% — مخالفة (السياسة 60%) ← اختيار: عقد آجل 1.2 مليون يورو"],
['y','Annual bank relationship review','المراجعة السنوية لعلاقات البنوك',["Group treasurer","Review our banking relationships and facilities","- Facilities, pricing, wallet share by bank: [attach]","We concentrate business with banks that support us","- Facility usage and cost per bank\n- Service quality notes\n- Proposal: grow, keep or reduce","Bank scorecard + proposal."],["أمين خزينة المجموعة","راجع علاقاتنا مع البنوك والتسهيلات","- التسهيلات والتسعير ونصيب كل بنك: [ارفع]","نركّز شغلنا مع البنوك اللي بتدعمنا","- استخدام التسهيلات وتكلفتها لكل بنك\n- ملاحظات جودة الخدمة\n- المقترح: نكبّر، نحافظ، نقلّل","بطاقة البنوك + المقترح."],
"Bank A: 46% of wallet, best pricing → grow · Bank D: 4%, unused line costs fees → reduce","البنك أ: 46% من الشغل وأحسن تسعير ← نكبّر · البنك د: 4%، خط مش مستخدم بيكلّف عمولات ← نقلّل"]]);

F('compliance','Compliance','الامتثال','🛡',['transactions','contracts'],[
['d','Daily regulatory watch','متابعة اللوائح اليومية',["Compliance analyst","Summarise new regulatory publications for our business","- New publications: [paste official texts or links]\n- Our business lines: [list]","We must not miss anything that applies to us","- Each item: what it says, who it affects, effective date from the text\n- Relevance: high / medium / none\n- No interpretation beyond the text","Watch table + items for the officer."],["محلل امتثال","لخّص المنشورات الرقابية الجديدة اللي تخص شغلنا","- المنشورات الجديدة: [الصق النصوص أو الروابط الرسمية]\n- خطوط الأعمال: [قائمة]","مينفعش يفوتنا حاجة تخصنا","- كل بند: بيقول إيه، بيأثر على مين، تاريخ السريان من النص\n- الأهمية: عالية / متوسطة / مفيش\n- من غير تفسير أبعد من النص","جدول المتابعة + بنود للمسؤول."],
"2 items: central bank circular on card limits (high, effective per text 1 Jan) · tax authority FAQ update (medium)","بندين: منشور البنك المركزي عن حدود الكروت (عالي، السريان حسب النص 1 يناير) · تحديث أسئلة مصلحة الضرائب (متوسط)"],
['w','Weekly third-party screening','فحص الأطراف التالتة الأسبوعي',["KYC analyst","Screen this week’s new suppliers and customers","- New parties: [attach]\n- Screening results from our tool: [attach]","We onboard only parties we understand","- Hits reviewed: true match, false positive, needs more info\n- Missing KYC documents listed\n- Decision left to the compliance officer","Screening table + document requests."],["محلل اعرف عميلك","افحص الموردين والعملاء الجداد الأسبوع ده","- الأطراف الجديدة: [ارفع]\n- نتايج الفحص من أداتنا: [ارفع]","بنتعامل بس مع الأطراف اللي فاهمينها","- النتايج متراجعة: تطابق حقيقي، إنذار كاذب، محتاج معلومات\n- مستندات KYC الناقصة متسجلة\n- القرار لمسؤول الامتثال","جدول الفحص + طلبات المستندات."],
"14 parties · 2 hits: 1 false positive (name only), 1 needs more info (shareholder unclear)","14 طرف · نتيجتين: 1 إنذار كاذب (الاسم بس)، 1 محتاج معلومات (المساهم مش واضح)"],
['m','Monthly compliance monitoring report','تقرير مراقبة الامتثال الشهري',["Compliance officer","Write the monthly compliance monitoring report","- Monitoring results, breaches, training completion: [attach]\n- Transactions review: transactions.csv","The board risk committee tracks compliance health","- KPIs vs targets\n- Breaches with root cause and remediation\n- Upcoming regulatory deadlines","Report: dashboard, breaches, deadlines."],["مسؤول امتثال","اكتب تقرير مراقبة الامتثال الشهري","- نتايج المراقبة، المخالفات، إتمام التدريب: [ارفع]\n- مراجعة المعاملات: transactions.csv","لجنة المخاطر في المجلس بتتابع صحة الامتثال","- المؤشرات مقابل المستهدف\n- المخالفات بسببها الجذري والتصحيح\n- المواعيد الرقابية الجاية","تقرير: لوحة، مخالفات، مواعيد."],
"Training 93% complete · 1 breach: late regulatory report (2 days) — root cause: single owner · deadline: AML return 31 Oct","التدريب 93% · مخالفة واحدة: تقرير رقابي متأخر يومين — السبب: مسؤول واحد · ميعاد: تقرير غسل الأموال 31 أكتوبر"],
['y','Annual compliance risk assessment','تقييم مخاطر الامتثال السنوي',["Head of compliance","Run the annual compliance risk assessment","- Obligations register: [attach]\n- Incidents and audit findings: [attach]\n- Contracts register: contracts.csv","The compliance plan follows the highest risks","- Inherent risk, controls, residual risk per obligation\n- Top 10 residual risks\n- Next year’s monitoring plan","Risk assessment table + monitoring plan."],["رئيس الامتثال","اعمل تقييم مخاطر الامتثال السنوي","- سجل الالتزامات: [ارفع]\n- الحوادث وملاحظات المراجعة: [ارفع]\n- سجل العقود: contracts.csv","خطة الامتثال بتمشي ورا أعلى المخاطر","- الخطر الأصلي والضوابط والخطر المتبقي لكل التزام\n- أعلى 10 مخاطر متبقية\n- خطة المراقبة للسنة الجاية","جدول تقييم المخاطر + خطة المراقبة."],
"Top residual risks: data protection (AI tools), sanctions screening gaps, e-invoicing readiness","أعلى المخاطر المتبقية: حماية البيانات (أدوات الـ AI)، فجوات فحص العقوبات، جاهزية الفاتورة الإلكترونية"]]);
