// ===== FIELD LIBRARY (part 1): per field, daily / weekly / monthly / yearly master prompts with sample data and example outputs =====
const FIELDLIB=[];
const CAD={d:T('Daily','يومي'),w:T('Weekly','أسبوعي'),m:T('Monthly','شهري'),y:T('Yearly','سنوي')};
// F(key, en, ar, icon, datasets, tasks) — task: [cadence, titleEn, titleAr, [role,task,context,reasoning,stop,output] en, same ar, exampleEn, exampleAr]
function F(k,en,ar,icon,data,tasks){FIELDLIB.push({k,t:T(en,ar),icon,data,tasks:tasks.map(x=>({c:x[0],t:T(x[1],x[2]),p:T(MPen(...ENR(x[3])),MPar(...ENR(x[4],1))),ex:T(x[5],x[6])}))})}

F('sales','Sales','المبيعات','📈',['crm_deals','crm_activities','territories','pricing'],[
['d','Daily deal priorities','أولويات الصفقات اليومية',["Sales coach for a B2B team in Egypt","Tell me which 5 deals to work on today and the next step for each","- Attached: crm_deals.csv and crm_activities.csv\n- My name in the rep column: [name]\n- Today: [date]","I have about 3 hours of selling time today","- Exactly 5 deals, ranked by value × urgency\n- Each next step is one concrete action\n- Reason cites the data (days since activity, close date)","Table: deal, customer, value EGP, why today, next step."],["مدرّب مبيعات لفريق B2B في مصر","قولّي أشتغل على أنهي 5 صفقات النهارده والخطوة الجاية لكل واحدة","- مرفق: crm_deals.csv و crm_activities.csv\n- اسمي في عمود المندوب: [الاسم]\n- النهارده: [التاريخ]","عندي حوالي 3 ساعات بيع النهارده","- 5 صفقات بالظبط، مترتبة بالقيمة × الاستعجال\n- كل خطوة جاية إجراء واحد محدد\n- السبب من البيانات (أيام من آخر نشاط، تاريخ الإقفال)","جدول: الصفقة، العميل، القيمة بالجنيه، ليه النهارده، الخطوة الجاية."],
"1. D2000 · C110 · EGP 706,000 · close date in 2 days, 34 days silent → call the decision maker today\n2. D2007 · C104 · EGP 410,000 · proposal sent 9 days ago → send the revised discount\n3. …","1. D2000 · C110 · 706,000 جنيه · الإقفال بعد يومين وساكتة من 34 يوم ← كلّم صاحب القرار النهارده\n2. D2007 · C104 · 410,000 جنيه · العرض اتبعت من 9 أيام ← ابعت الخصم المعدّل\n3. …"],
['w','Weekly pipeline review','مراجعة الـ pipeline الأسبوعية',["Sales operations analyst","Prepare the Monday pipeline review for the team","- Attached: crm_deals.csv\n- At risk: 21+ days without activity, past close date, decision maker not met\n- Stage probabilities: [paste]","The director decides where to focus the team this week","- Weighted pipeline by rep\n- Every at-risk deal with its reason\n- Slipped deals since last week, if last week’s file is attached","One page: KPI line, table by rep, at-risk list, 3 decisions for the meeting."],["محلل عمليات مبيعات","جهّز مراجعة الـ pipeline لاجتماع الاتنين","- مرفق: crm_deals.csv\n- المعرّض للخطر: 21+ يوم من غير نشاط، تاريخ إقفال فات، صاحب القرار متقابلش\n- احتمالات المراحل: [الصق]","المدير هيقرر يركّز الفريق على إيه الأسبوع ده","- الـ pipeline المرجّح لكل مندوب\n- كل صفقة معرضة للخطر بسببها\n- الصفقات اللي اتأخرت من الأسبوع اللي فات لو ملف الأسبوع اللي فات مرفق","صفحة: سطر المؤشرات، جدول بالمندوبين، قائمة الخطر، 3 قرارات للاجتماع."],
"Weighted pipeline EGP 9.8M (−6% WoW)\nMona 3.1M · Omar 2.4M · Hany 2.2M · Sara 2.1M\nAt risk: 7 deals, EGP 2.6M — mainly no decision-maker meeting (4)\nDecision: Omar and Hany book 2 executive meetings each","الـ pipeline المرجّح 9.8 مليون جنيه (−6% عن الأسبوع اللي فات)\nمنى 3.1 · عمر 2.4 · هاني 2.2 · سارة 2.1\nمعرّض للخطر: 7 صفقات، 2.6 مليون — أغلبها من غير مقابلة صاحب القرار (4)\nالقرار: عمر وهاني يحجزوا مقابلتين مع الإدارة كل واحد"],
['m','Monthly win/loss and discount review','مراجعة الكسب والخسارة والخصومات الشهرية',["Revenue analyst","Analyse this month’s won and lost deals and the discounts given","- Attached: pricing.csv (list price, discount %, units, won, segment)\n- Discount policy: max [x]% without approval","Management wants to know if discounts buy wins or just margin loss","- Win rate by discount band and segment\n- Deals above policy listed\n- Correlation stated carefully, not as proof","Table by discount band + 3 findings + a policy recommendation."],["محلل إيرادات","حلل الصفقات المكسوبة والخسرانة الشهر ده والخصومات اللي اتادت","- مرفق: pricing.csv (السعر، نسبة الخصم، الكمية، اتكسبت، الشريحة)\n- سياسة الخصم: أقصى [x]% من غير موافقة","الإدارة عايزة تعرف الخصم بيجيب صفقات ولا بيضيّع هامش بس","- نسبة الكسب حسب شريحة الخصم ونوع العميل\n- الصفقات اللي فوق السياسة متسجلة\n- العلاقة متقالة بحذر مش كدليل قاطع","جدول حسب شريحة الخصم + 3 نتايج + توصية للسياسة."],
"Discount 0–5%: win rate 31% · 5–10%: 38% · 10–15%: 40% · >15%: 41%\nAbove 10% adds little win rate but costs ~EGP 420k margin this month\nRecommendation: approval needed above 10%","خصم 0–5%: نسبة كسب 31% · 5–10%: 38% · 10–15%: 40% · أكتر من 15%: 41%\nفوق 10% مش بيزوّد الكسب كتير بس كلّف حوالي 420 ألف جنيه هامش الشهر ده\nالتوصية: موافقة مطلوبة فوق 10%"],
['y','Annual territory and quota plan','خطة المناطق والمستهدفات السنوية',["Sales planning manager","Propose next year’s territory split and quotas","- Attached: territories.csv (rep, region, accounts, pipeline, last year sales, market potential)\n- Company growth target: [x]%","Quotas must be fair and reachable to keep good reps","- Quota per rep with the formula shown\n- Capacity and potential balanced\n- Assumptions listed","Quota table + method note + risks."],["مدير تخطيط مبيعات","اقترح تقسيم المناطق والمستهدفات للسنة الجاية","- مرفق: territories.csv (المندوب، المنطقة، الحسابات، الـ pipeline، مبيعات السنة اللي فاتت، حجم السوق)\n- مستهدف نمو الشركة: [x]%","المستهدفات لازم تكون عادلة وممكنة علشان نحافظ على الكويسين","- مستهدف لكل مندوب والمعادلة ظاهرة\n- توازن بين الطاقة وحجم السوق\n- الافتراضات متسجلة","جدول المستهدفات + ملاحظة عن الطريقة + المخاطر."],
"Quota = 60% × last year × (1+growth) + 40% × share of potential\nMona EGP 14.2M · Omar 11.8M · Hany 10.9M · Sara 10.1M (total 47.0M, +12%)\nRisk: Upper Egypt potential is an estimate","المستهدف = 60% × السنة اللي فاتت × (1+النمو) + 40% × نصيب حجم السوق\nمنى 14.2 مليون · عمر 11.8 · هاني 10.9 · سارة 10.1 (الإجمالي 47.0، +12%)\nخطر: حجم السوق في الصعيد تقديري"]]);

F('finance','Finance','المالية','💰',['bva','ar_aging','kpis'],[
['d','Daily cash and collections note','ملاحظة الكاش والتحصيل اليومية',["Finance controller","Write today’s cash and collections note for the finance manager","- Bank balances by account: [paste]\n- Receipts and payments yesterday: [paste]\n- AR ageing: ar_aging.csv","The manager decides today’s payments","- Opening, movements and closing cash by account\n- Top 5 overdue customers with amount and days\n- Any payment that would breach the minimum balance flagged","Five-line note + small table."],["مراقب مالي","اكتب ملاحظة الكاش والتحصيل النهارده للمدير المالي","- أرصدة البنوك حسب الحساب: [الصق]\n- المقبوضات والمدفوعات امبارح: [الصق]\n- أعمار المديونيات: ar_aging.csv","المدير هيقرر مدفوعات النهارده","- الرصيد الافتتاحي والحركة والرصيد الختامي لكل حساب\n- أكبر 5 عملاء متأخرين بالمبلغ والأيام\n- أي دفعة هتنزّل الرصيد تحت الحد الأدنى متعلّمة","ملاحظة 5 سطور + جدول صغير."],
"Cash EGP 18.4M (+1.2M). Collections yesterday 3.1M; payments 1.9M.\nTop overdue: C107 EGP 640k (78 days), C112 410k (64), …\nFlag: supplier payment of 2.5M on Thursday would take account 2 below its 1M minimum.","الكاش 18.4 مليون جنيه (+1.2). التحصيل امبارح 3.1 مليون؛ المدفوعات 1.9.\nأكبر متأخرات: C107 بـ 640 ألف (78 يوم)، C112 بـ 410 ألف (64)، …\nتنبيه: دفعة المورد 2.5 مليون يوم الخميس هتنزّل الحساب 2 تحت حده الأدنى 1 مليون."],
['w','Weekly KPI flash','نشرة المؤشرات الأسبوعية',["Finance business partner","Prepare the weekly KPI flash for the leadership team","- Attached: kpis.csv (kpi, q2, q3, target)\n- This week’s actuals: [paste]","Leaders read it in two minutes before Monday’s meeting","- Each KPI vs target with a status colour word (green/amber/red)\n- One-line reason for every amber or red\n- No KPI left without a status","Table + three headlines."],["شريك أعمال مالي","جهّز نشرة المؤشرات الأسبوعية لفريق القيادة","- مرفق: kpis.csv (المؤشر، الربع التاني، التالت، المستهدف)\n- فعلي الأسبوع ده: [الصق]","القيادة بتقراها في دقيقتين قبل اجتماع الاتنين","- كل مؤشر مقابل المستهدف بحالة (أخضر/أصفر/أحمر)\n- سبب في سطر لكل أصفر أو أحمر\n- مفيش مؤشر من غير حالة","جدول + 3 عناوين."],
"Revenue: amber (−4% vs target) — two large orders slipped to next week\nGross margin: green (34.1%)\nDSO: red (71 days vs 60) — C107 and C112 overdue","الإيراد: أصفر (−4% عن المستهدف) — طلبيتين كبار اتأجلوا للأسبوع الجاي\nهامش الربح: أخضر (34.1%)\nأيام التحصيل: أحمر (71 يوم مقابل 60) — C107 و C112 متأخرين"],
['m','Monthly management accounts commentary','شرح حسابات الإدارة الشهري',["Senior finance manager","Write the commentary for this month’s management accounts","- Attached: bva.csv (line, month, budget, actual, last year — EGP k)\n- Materiality: EGP 250k or 5%","The board pack goes out in 3 days","- Revenue, gross margin, opex and EBITDA vs budget and last year\n- Every material variance explained or flagged\n- Outlook paragraph with risks","One page: headline, variance table, explanations, outlook."],["مدير مالي أول","اكتب شرح حسابات الإدارة للشهر ده","- مرفق: bva.csv (البند، الشهر، الموازنة، الفعلي، السنة اللي فاتت — ألف جنيه)\n- الأهمية: 250 ألف جنيه أو 5%","ملف المجلس هيطلع بعد 3 أيام","- الإيراد وهامش الربح والمصروفات والـ EBITDA مقابل الموازنة والسنة اللي فاتت\n- كل انحراف مهم متشرح أو متعلّم\n- فقرة توقعات بالمخاطر","صفحة: العنوان، جدول الانحرافات، الشرح، التوقعات."],
"EBITDA EGP 6.2M, 8% below budget, 11% above last year.\nRevenue −3% (two delayed orders); opex +5% (salaries +7.5% after the July increase).\nOutlook: delayed orders expected in October; salary run-rate stays above budget.","الـ EBITDA 6.2 مليون جنيه، أقل من الموازنة 8% وأعلى من السنة اللي فاتت 11%.\nالإيراد −3% (طلبيتين اتأخروا)؛ المصروفات +5% (المرتبات +7.5% بعد زيادة يوليو).\nالتوقعات: الطلبيات المتأخرة متوقعة في أكتوبر؛ ومعدل المرتبات هيفضل فوق الموازنة."],
['y','Annual budget assumptions pack','ملف افتراضات الموازنة السنوية',["Head of financial planning","Draft the assumptions pack for next year’s budget","- This year’s actuals and forecast: [attach]\n- Macro inputs: inflation, FX rate, wage increase [paste sources]\n- Strategic priorities: [list]","Department heads build their budgets on these assumptions","- Each assumption with value, source and owner\n- Sensitivities for FX and volume\n- Open questions for the CFO","Assumptions table + sensitivity table + questions."],["رئيس التخطيط المالي","اكتب مسودة ملف افتراضات موازنة السنة الجاية","- فعلي وتوقع السنة دي: [ارفع]\n- مدخلات الاقتصاد: التضخم، سعر الصرف، زيادة الأجور [الصق المصادر]\n- الأولويات الاستراتيجية: [قائمة]","رؤساء الأقسام هيبنوا موازناتهم على الافتراضات دي","- كل افتراض بقيمته ومصدره ومسؤوله\n- حساسية لسعر الصرف والكميات\n- أسئلة مفتوحة للمدير المالي","جدول الافتراضات + جدول الحساسية + الأسئلة."],
"Volume +8% (sales plan) · FX 52 EGP/USD (bank consensus, Sept) · wages +15% (HR)\nSensitivity: FX +10% → EBITDA −EGP 3.4M; volume −5% → −EGP 2.1M\nOpen: capex ceiling for the new line","الكميات +8% (خطة المبيعات) · الدولار 52 جنيه (متوسط توقعات البنوك، سبتمبر) · الأجور +15% (الموارد البشرية)\nالحساسية: الدولار +10% ← الـ EBITDA −3.4 مليون؛ الكميات −5% ← −2.1 مليون\nمفتوح: سقف الاستثمار للخط الجديد"]]);

F('banking','Banking','البنوك','🏦',['credit_fin','transactions'],[
['d','Daily credit file check','مراجعة ملف ائتمان يومية',["Credit analyst at a commercial bank","Check today’s incoming credit file for completeness and red flags","- Checklist: [bank’s credit file checklist]\n- Documents received: [list or attach]\n- Borrower financials: credit_fin.csv","Incomplete files waste committee time","- Every checklist item marked present / missing / unclear\n- Red flags quoted from the documents\n- No credit opinion — completeness only","Checklist table + red flags + request list for the relationship manager."],["محلل ائتمان في بنك تجاري","راجع ملف الائتمان اللي وصل النهارده من حيث الاكتمال والعلامات الحمرا","- قائمة المراجعة: [قائمة البنك]\n- المستندات اللي وصلت: [قائمة أو ارفع]\n- القوائم المالية للمقترض: credit_fin.csv","الملفات الناقصة بتضيّع وقت اللجنة","- كل بند في القائمة: موجود / ناقص / مش واضح\n- العلامات الحمرا مقتبسة من المستندات\n- من غير رأي ائتماني — الاكتمال بس","جدول القائمة + العلامات الحمرا + طلبات لمدير العلاقة."],
"Missing: audited 2025 statements, insurance certificate\nRed flag: receivables up 46% while revenue up 9%\nRequest list sent to RM: 3 items","ناقص: قوائم 2025 المراجعة، شهادة التأمين\nعلامة حمرا: المديونيات زادت 46% والإيراد زاد 9% بس\nقائمة طلبات لمدير العلاقة: 3 بنود"],
['w','Weekly transaction monitoring review','مراجعة مراقبة المعاملات الأسبوعية',["AML analyst","Review this week’s flagged card transactions","- Attached: transactions.csv (txn, merchant, mcc, amount)\n- Scenarios: [paste bank scenarios]","Alerts must be closed or escalated within policy timelines","- Each alert: pattern, reason, close or escalate\n- Escalations explained in plain words\n- No customer conclusions beyond the data","Alert table + escalation memo draft."],["محلل مكافحة غسل أموال","راجع معاملات الكروت المتعلّمة الأسبوع ده","- مرفق: transactions.csv (المعاملة، التاجر، الكود، المبلغ)\n- السيناريوهات: [الصق سيناريوهات البنك]","التنبيهات لازم تتقفل أو تتصعّد في المواعيد المحددة","- كل تنبيه: النمط، السبب، يتقفل ولا يتصعّد\n- التصعيد متشرح بكلام بسيط\n- مفيش استنتاجات عن العميل أبعد من البيانات","جدول التنبيهات + مسودة مذكرة التصعيد."],
"12 alerts: 9 close (normal travel spend), 3 escalate\nEscalate: 5 transactions just under EGP 50k at the same jeweller within 2 days","12 تنبيه: 9 يتقفلوا (صرف سفر عادي)، 3 يتصعّدوا\nتصعيد: 5 معاملات أقل شوية من 50 ألف جنيه عند نفس الصايغ في يومين"],
['m','Monthly covenant monitoring','مراقبة التعهدات الشهرية',["Relationship manager","Test the borrower’s covenants for this month","- Covenants: DSCR ≥ 1.25, Debt/EBITDA ≤ 3.5, current ratio ≥ 1.2\n- Management accounts: [attach]","Early warning protects the bank and the client","- Each ratio calculated with the formula shown\n- Headroom in % for each\n- Breach or near-breach (within 10%) flagged","Covenant table + one-paragraph note to the credit team."],["مدير علاقة","اختبر تعهدات العميل للشهر ده","- التعهدات: DSCR ≥ 1.25، الدين/EBITDA ≤ 3.5، نسبة التداول ≥ 1.2\n- حسابات الإدارة: [ارفع]","الإنذار المبكر بيحمي البنك والعميل","- كل نسبة محسوبة والمعادلة ظاهرة\n- المساحة المتبقية كنسبة لكل واحدة\n- الكسر أو القرب منه (في حدود 10%) متعلّم","جدول التعهدات + فقرة للفريق الائتماني."],
"DSCR 1.31 (headroom 5%) — near breach\nDebt/EBITDA 3.4 (3%) — near breach\nCurrent ratio 1.19 — BREACH (limit 1.2)","DSCR 1.31 (مساحة 5%) — قريب من الكسر\nالدين/EBITDA 3.4 (3%) — قريب من الكسر\nنسبة التداول 1.19 — كسر (الحد 1.2)"],
['y','Annual credit review memo','مذكرة المراجعة الائتمانية السنوية',["Senior credit analyst","Draft the annual review memo for this borrower","- Financials 3 years: credit_fin.csv\n- Facility details and conduct: [paste]\n- Industry notes: [paste]","The credit committee renews, changes or reduces the facility","- Trend analysis with ratios for 3 years\n- Risks and mitigants\n- Recommendation stated as a proposal for committee judgement","Memo: summary, financial analysis, risks, recommendation, conditions."],["محلل ائتمان أول","اكتب مسودة مذكرة المراجعة السنوية للعميل ده","- القوائم المالية 3 سنين: credit_fin.csv\n- تفاصيل التسهيل والانتظام: [الصق]\n- ملاحظات القطاع: [الصق]","لجنة الائتمان هتجدد أو تعدّل أو تخفّض التسهيل","- تحليل اتجاه بالنسب لـ 3 سنين\n- المخاطر وعوامل التخفيف\n- التوصية مقترح لحكم اللجنة","مذكرة: ملخص، تحليل مالي، مخاطر، توصية، شروط."],
"Revenue CAGR 11%; EBITDA margin down from 16% to 13%; leverage up\nRecommendation: renew at the same limit with a quarterly current-ratio test","نمو الإيراد السنوي 11%؛ هامش الـ EBITDA نزل من 16% لـ 13%؛ والمديونية زادت\nالتوصية: تجديد بنفس الحد مع اختبار ربع سنوي لنسبة التداول"]]);

F('audit','Audit','المراجعة','🔍',['expenses','bank_gl'],[
['d','Daily exceptions triage','فرز الاستثناءات اليومي',["Internal auditor","Triage yesterday’s expense claims against policy","- Attached: expenses.csv\n- Policy limits: [paste]","Exceptions must be followed up while memories are fresh","- Each exception with policy clause and row\n- Missing receipts listed separately\n- No judgement on intent","Exceptions table + follow-up emails to draft."],["مراجع داخلي","افرز مطالبات المصروفات بتاعة امبارح مقابل السياسة","- مرفق: expenses.csv\n- حدود السياسة: [الصق]","الاستثناءات لازم تتتابع والناس لسه فاكرة","- كل استثناء ببند السياسة والصف\n- الإيصالات الناقصة لوحدها\n- من غير حكم على النية","جدول الاستثناءات + إيميلات متابعة للكتابة."],
"6 exceptions: 3 over meal limit (rows 14, 22, 31), 2 missing receipts, 1 weekend taxi without approval","6 استثناءات: 3 فوق حد الوجبات (الصفوف 14، 22، 31)، 2 من غير إيصال، 1 تاكسي في الإجازة من غير موافقة"],
['w','Weekly reconciliation review','مراجعة المطابقات الأسبوعية',["Audit senior","Review this week’s bank reconciliation","- Attached: bank_gl.csv (source, date, reference, description, amount)","Unreconciled items older than 30 days are a control finding","- Matched, unmatched and timing items separated\n- Items over 30 days flagged\n- Evidence reference for each","Reconciliation summary + aged unmatched list."],["سينيور مراجعة","راجع مطابقة البنك للأسبوع ده","- مرفق: bank_gl.csv (المصدر، التاريخ، المرجع، الوصف، المبلغ)","البنود غير المطابقة اللي عدّت 30 يوم ملاحظة رقابية","- المطابق وغير المطابق وفروق التوقيت منفصلين\n- البنود اللي عدّت 30 يوم متعلّمة\n- مرجع الدليل لكل بند","ملخص المطابقة + قائمة غير المطابق بأعمارها."],
"142 matched · 6 timing (cleared next week) · 3 unmatched (EGP 84k), 1 older than 30 days","142 مطابق · 6 فروق توقيت (اتسوّت الأسبوع اللي بعده) · 3 غير مطابقين (84 ألف جنيه)، واحد منهم عدّى 30 يوم"],
['m','Monthly control test','اختبار ضابط شهري',["Internal auditor experienced in financial controls","Test the monthly journal-approval control","- Population: journal entries this month [attach]\n- Control: entries above EGP 500k need second approval\n- Sampling method: [documented method]","The audit committee relies on this test","- Test steps tied to the control description\n- Exceptions with evidence references\n- Conclusion left to the reviewer","Worksheet + exceptions + reviewer notes."],["مراجع داخلي خبرة في الضوابط المالية","اختبر ضابط اعتماد القيود الشهري","- المجتمع: قيود الشهر ده [ارفع]\n- الضابط: القيود فوق 500 ألف جنيه محتاجة اعتماد تاني\n- طريقة العينة: [الطريقة الموثقة]","لجنة المراجعة بتعتمد على الاختبار ده","- خطوات الاختبار مربوطة بوصف الضابط\n- الاستثناءات بمراجع الأدلة\n- الاستنتاج متساب للمراجع","ورقة العمل + الاستثناءات + ملاحظات للمراجع."],
"Sample 25 of 118 entries > EGP 500k · 2 exceptions: approved by the preparer (JE-4471, JE-4520)","عينة 25 من 118 قيد فوق 500 ألف جنيه · استثناءين: اتعتمدوا من نفس اللي عملهم (JE-4471، JE-4520)"],
['y','Annual risk-based audit plan','خطة المراجعة السنوية المبنية على المخاطر',["Head of internal audit","Draft next year’s risk-based audit plan","- Risk register: [attach]\n- Last 3 years’ audit coverage: [attach]\n- Available audit days: [n]","The audit committee approves the plan","- Each audit linked to top risks\n- Coverage gaps from prior years addressed\n- Days add up to the available total","Plan table (audit, risk, quarter, days) + rationale."],["رئيس المراجعة الداخلية","اكتب مسودة خطة المراجعة المبنية على المخاطر للسنة الجاية","- سجل المخاطر: [ارفع]\n- تغطية المراجعة آخر 3 سنين: [ارفع]\n- أيام المراجعة المتاحة: [العدد]","لجنة المراجعة هتعتمد الخطة","- كل مهمة مراجعة مربوطة بأهم المخاطر\n- فجوات التغطية من السنين اللي فاتت متعالجة\n- الأيام مجموعها مساوي للمتاح","جدول الخطة (المهمة، الخطر، الربع، الأيام) + المبررات."],
"14 audits · 620 days of 640 · new: cyber access review, AI use-case review · 20 days reserve","14 مهمة · 620 يوم من 640 · جديد: مراجعة صلاحيات الأمن السيبراني، مراجعة حالات استخدام الـ AI · 20 يوم احتياطي"]]);

F('tradefin','Trade finance','تمويل التجارة','🚢',['lc','ap_aging'],[
['d','Daily LC document check','فحص مستندات الاعتماد اليومي',["Trade finance document checker","Check the presented documents against the LC terms","- Attached: lc.csv (LC MT700 fields vs invoice, bill of lading, certificate of origin)\n- Rules: UCP 600 and ISBP as applied by our bank","Discrepancies must be found before presentation","- Every field compared; discrepancies quoted\n- Article reference for each discrepancy\n- No decision to pay — the examiner decides","Discrepancy table + summary for the examiner."],["فاحص مستندات تمويل تجارة","افحص المستندات المقدمة مقابل شروط الاعتماد","- مرفق: lc.csv (حقول MT700 مقابل الفاتورة والبوليصة وشهادة المنشأ)\n- القواعد: UCP 600 و ISBP زي ما البنك بيطبقهم","المخالفات لازم تتكشف قبل التقديم","- كل حقل متقارن؛ والمخالفات مقتبسة\n- مرجع المادة لكل مخالفة\n- من غير قرار بالدفع — الفاحص هو اللي يقرر","جدول المخالفات + ملخص للفاحص."],
"2 discrepancies: shipment date 18 Sep after latest 15 Sep (UCP 600 art. 14); invoice exceeds LC amount by 1% with no tolerance stated","مخالفتين: الشحن 18 سبتمبر بعد آخر موعد 15 سبتمبر (المادة 14)؛ الفاتورة أكبر من مبلغ الاعتماد بـ 1% من غير نسبة سماح"],
['w','Weekly import payments schedule','جدول مدفوعات الاستيراد الأسبوعي',["Trade operations officer","Prepare next week’s import payment schedule","- Attached: ap_aging.csv (supplier, invoice, amount, currency, due date)\n- FX available by currency: [paste]","Treasury must arrange FX in time","- Payments by currency and date\n- Shortfalls per currency flagged\n- Suppliers whose LC or collection terms apply marked","Schedule table + FX need summary."],["مسؤول عمليات تجارة","جهّز جدول مدفوعات الاستيراد للأسبوع الجاي","- مرفق: ap_aging.csv (المورد، الفاتورة، المبلغ، العملة، الاستحقاق)\n- العملة المتاحة: [الصق]","الخزينة لازم تدبّر العملة في الوقت","- المدفوعات حسب العملة والتاريخ\n- العجز في كل عملة متعلّم\n- الموردين اللي عليهم اعتماد أو تحصيل متعلّمين","جدول المدفوعات + ملخص احتياج العملة."],
"USD 412k due (shortfall 85k on Tuesday) · EUR 96k covered","مستحق 412 ألف دولار (عجز 85 ألف يوم التلات) · 96 ألف يورو متغطيين"],
['m','Monthly LC portfolio report','تقرير محفظة الاعتمادات الشهري',["Trade finance manager","Summarise the month’s LC portfolio","- LC register: [attach]","Management tracks volume, risk and fees","- Issued, utilised, expired and outstanding\n- Discrepancy rate and top causes\n- Fees earned","Dashboard table + 3 insights."],["مدير تمويل تجارة","لخّص محفظة الاعتمادات للشهر","- سجل الاعتمادات: [ارفع]","الإدارة بتتابع الحجم والخطر والعمولات","- المصدر والمستخدم والمنتهي والقائم\n- نسبة المخالفات وأهم أسبابها\n- العمولات","جدول مؤشرات + 3 ملاحظات."],
"Issued 42 (USD 18.6M) · discrepancy rate 38% — late shipment is cause #1 · fees USD 96k","اتصدر 42 (18.6 مليون دولار) · نسبة المخالفات 38% — الشحن المتأخر السبب رقم 1 · عمولات 96 ألف دولار"],
['y','Annual trade client review','المراجعة السنوية لعميل التجارة',["Trade relationship manager","Prepare the annual review of a trade finance client","- Volumes, discrepancies and claims history: [attach]\n- Limits and pricing: [paste]","Limits and pricing are renewed for next year","- Volume trend and utilisation\n- Operational quality (discrepancies, delays)\n- Proposal for limits and pricing","Review memo + proposal table."],["مدير علاقة تمويل تجارة","جهّز المراجعة السنوية لعميل تمويل تجارة","- الأحجام والمخالفات وتاريخ المطالبات: [ارفع]\n- الحدود والتسعير: [الصق]","الحدود والتسعير بيتجددوا للسنة الجاية","- اتجاه الحجم والاستخدام\n- الجودة التشغيلية (مخالفات، تأخير)\n- مقترح الحدود والتسعير","مذكرة المراجعة + جدول المقترح."],
"Volume +22%, utilisation 81%, discrepancies down from 44% to 31% → propose limit +15%, same pricing","الحجم +22%، الاستخدام 81%، المخالفات نزلت من 44% لـ 31% ← مقترح زيادة الحد 15% بنفس التسعير"]]);

F('hr','HR','الموارد البشرية','👥',['employees'],[
['d','Daily recruiting shortlist','القائمة المختصرة للتوظيف اليومية',["Talent acquisition specialist","Screen today’s CVs against the job requirements","- Job description and must-haves: [paste]\n- CVs: [attach, anonymised where possible]","Hiring managers only want strong candidates","- Each CV scored against must-haves with evidence quoted\n- No judgement on age, gender, religion or nationality\n- Top 5 with interview questions","Shortlist table + tailored interview questions."],["أخصائي استقطاب","فرز السير الذاتية بتاعة النهارده مقابل متطلبات الوظيفة","- الوصف الوظيفي والأساسيات: [الصق]\n- السير الذاتية: [ارفع، من غير بيانات تعريفية لو ممكن]","مديرين التوظيف عايزين المرشحين القويين بس","- كل سيرة متقيمة مقابل الأساسيات بالدليل مقتبس\n- من غير حكم على السن أو النوع أو الدين أو الجنسية\n- أحسن 5 بأسئلة مقابلة","جدول القائمة المختصرة + أسئلة مقابلة مخصصة."],
"Top 5 of 38 · Candidate 12: 6 years FP&A, IFRS, Power BI ✓; gap: no budgeting ownership → ask about owning a budget cycle","أحسن 5 من 38 · المرشح 12: 6 سنين FP&A، IFRS، Power BI ✓؛ الفجوة: مكانش مسؤول عن موازنة ← اسأله عن قيادة دورة موازنة"],
['w','Weekly attrition watch','متابعة الدوران الأسبوعية',["HR business partner","Identify employees at higher risk of leaving","- Attached: employees.csv (department, grade, tenure, salary, rating, promotions, overtime, engagement)","Managers can act before resignation","- Risk factors explained, not a black-box score\n- Department-level view first\n- Treat individual flags as conversation prompts, not decisions","Department table + top factors + suggested manager actions."],["شريك أعمال موارد بشرية","حدد الموظفين اللي احتمال سيبهم للشغل أعلى","- مرفق: employees.csv (القسم، الدرجة، المدة، المرتب، التقييم، الترقيات، الأوفرتايم، الارتباط)","المديرين يقدروا يتصرفوا قبل الاستقالة","- عوامل الخطر متشرحة مش رقم غامض\n- نظرة على مستوى القسم الأول\n- العلامات الفردية بداية حوار مش قرار","جدول الأقسام + أهم العوامل + إجراءات مقترحة للمديرين."],
"Sales highest risk: overtime > 30h/month and no promotion in 3 years for 9 of 30\nAction: career conversations this month; review overtime","المبيعات أعلى خطر: أوفرتايم أكتر من 30 ساعة في الشهر ومفيش ترقية من 3 سنين لـ 9 من 30\nالإجراء: حوارات مسار وظيفي الشهر ده؛ ومراجعة الأوفرتايم"],
['m','Monthly people report','تقرير الموارد البشرية الشهري',["HR analyst","Write the monthly people report for management","- Headcount, joiners, leavers, absence: [attach]\n- Last month’s report: [attach]","Management tracks workforce health","- Headcount bridge (opening, joiners, leavers, closing)\n- Attrition and absence vs last month\n- Three insights with actions","One page: KPIs, bridge, insights."],["محلل موارد بشرية","اكتب تقرير الموارد البشرية الشهري للإدارة","- العدد، المعيّنين، المستقيلين، الغياب: [ارفع]\n- تقرير الشهر اللي فات: [ارفع]","الإدارة بتتابع صحة القوى العاملة","- جسر العدد (أول المدة، المعيّنين، المستقيلين، آخر المدة)\n- الدوران والغياب مقابل الشهر اللي فات\n- 3 ملاحظات بإجراءات","صفحة: المؤشرات، الجسر، الملاحظات."],
"Headcount 92 → 95 (+5 joiners, −2 leavers) · attrition 10.9% annualised · absence 2.1%","العدد 92 ← 95 (+5 معيّنين، −2 مستقيلين) · الدوران 10.9% سنوياً · الغياب 2.1%"],
['y','Annual salary review proposal','مقترح مراجعة المرتبات السنوية',["Compensation and benefits manager","Propose this year’s salary increase budget and guidelines","- Attached: employees.csv\n- Market data and inflation: [paste sources]\n- Budget ceiling: [x]%","Fair increases keep good people within budget","- Merit matrix by rating and position in range\n- Total cost within the ceiling\n- Equity check across departments","Merit matrix + cost table + equity notes."],["مدير تعويضات ومزايا","اقترح ميزانية وإرشادات زيادة المرتبات السنة دي","- مرفق: employees.csv\n- بيانات السوق والتضخم: [الصق المصادر]\n- سقف الميزانية: [x]%","الزيادات العادلة بتحافظ على الكويسين في حدود الميزانية","- مصفوفة الجدارة حسب التقييم والموقع في المدى\n- التكلفة الإجمالية في حدود السقف\n- مراجعة العدالة بين الأقسام","مصفوفة الجدارة + جدول التكلفة + ملاحظات العدالة."],
"Merit: rating 5 → 18%, 4 → 15%, 3 → 12%, 2 → 6% · total cost 13.4% vs ceiling 14%","الجدارة: تقييم 5 ← 18%، 4 ← 15%، 3 ← 12%، 2 ← 6% · التكلفة الكلية 13.4% مقابل سقف 14%"]]);

F('marketing','Marketing','التسويق','📣',['campaigns','social'],[
['d','Daily campaign pulse','نبض الحملات اليومي',["Performance marketer","Check yesterday’s campaign results and suggest budget moves","- Attached: campaigns.csv (campaign, channel, spend, impressions, clicks, leads, sales, revenue)\n- Target cost per lead: EGP [x]","Budget should move to what works today","- Cost per lead and ROAS per campaign\n- Moves limited to ±20% per campaign\n- Reasons from the data","Table + recommended moves."],["مسوّق أداء","راجع نتايج حملات امبارح واقترح تحريك الميزانية","- مرفق: campaigns.csv (الحملة، القناة، الصرف، المشاهدات، النقرات، العملاء المحتملين، المبيعات، الإيراد)\n- تكلفة العميل المحتمل المستهدفة: [x] جنيه","الميزانية لازم تروح للي شغال النهارده","- تكلفة العميل المحتمل والعائد على الإعلان لكل حملة\n- التحريك في حدود ±20% لكل حملة\n- الأسباب من البيانات","جدول + التحريك المقترح."],
"Search brand: CPL EGP 41, ROAS 6.2 → +20% · Meta video: CPL 160 → −20%","بحث البراند: تكلفة العميل 41 جنيه، العائد 6.2 ← +20% · فيديو ميتا: تكلفة العميل 160 ← −20%"],
['w','Weekly content plan','خطة المحتوى الأسبوعية',["Content marketing lead","Plan next week’s posts using what performed best","- Attached: social.csv (post, platform, format, pillar, impressions, engagement, saves, follows)\n- Brand pillars: [list]","The team needs a ready calendar every Thursday","- 5 posts across pillars\n- Each idea linked to a past top performer\n- Arabic and English captions where needed","Calendar table + captions."],["مسؤول تسويق المحتوى","خطط لبوستات الأسبوع الجاي على أساس اللي نجح","- مرفق: social.csv (البوست، المنصة، الشكل، المحور، المشاهدات، التفاعل، الحفظ، المتابعة)\n- محاور البراند: [قائمة]","الفريق محتاج جدول جاهز كل خميس","- 5 بوستات على المحاور\n- كل فكرة مربوطة ببوست ناجح قبل كده\n- كابشن عربي وإنجليزي لو محتاج","جدول + الكابشن."],
"Mon carousel (education) — based on post 12 (saves 4.1%) · Wed reel (customer story) …","الاتنين كاروسيل (تعليمي) — على أساس بوست 12 (حفظ 4.1%) · الأربع ريل (قصة عميل) …"],
['m','Monthly marketing performance report','تقرير أداء التسويق الشهري',["Marketing analyst","Write the monthly marketing performance report","- Attached: campaigns.csv and social.csv\n- Targets: [paste]","The CMO reports marketing’s contribution to revenue","- Spend, leads, sales and revenue vs target\n- Channel ranking by ROAS\n- What to stop, start and continue","One page: KPIs, channel table, stop/start/continue."],["محلل تسويق","اكتب تقرير أداء التسويق الشهري","- مرفق: campaigns.csv و social.csv\n- المستهدفات: [الصق]","مدير التسويق بيقدّم مساهمة التسويق في الإيراد","- الصرف والعملاء المحتملين والمبيعات والإيراد مقابل المستهدف\n- ترتيب القنوات بالعائد\n- نبطّل إيه ونبدأ إيه ونكمّل إيه","صفحة: المؤشرات، جدول القنوات، نبطّل/نبدأ/نكمّل."],
"Revenue from campaigns EGP 4.8M (96% of target) · best ROAS: search 5.4 · stop: display retargeting","الإيراد من الحملات 4.8 مليون جنيه (96% من المستهدف) · أعلى عائد: البحث 5.4 · نبطّل: إعادة الاستهداف بالبانرات"],
['y','Annual marketing plan','خطة التسويق السنوية',["Head of marketing","Draft next year’s marketing plan and budget split","- This year’s results: [attach]\n- Business goals: [paste]\n- Budget: EGP [x]","The plan must link spend to revenue goals","- Goals, audiences, channels and budget by quarter\n- KPIs per channel\n- Test budget of 10–15% for new channels","Plan document + budget table + KPI table."],["رئيس التسويق","اكتب مسودة خطة التسويق وتقسيم الميزانية للسنة الجاية","- نتايج السنة دي: [ارفع]\n- أهداف الشركة: [الصق]\n- الميزانية: [x] جنيه","الخطة لازم تربط الصرف بأهداف الإيراد","- الأهداف والجمهور والقنوات والميزانية لكل ربع\n- مؤشرات لكل قناة\n- ميزانية تجارب 10–15% لقنوات جديدة","مستند الخطة + جدول الميزانية + جدول المؤشرات."],
"Budget EGP 24M: search 35%, social 30%, events 15%, content 8%, tests 12% · target 4,800 qualified leads","الميزانية 24 مليون جنيه: بحث 35%، سوشيال 30%، فعاليات 15%، محتوى 8%، تجارب 12% · المستهدف 4,800 عميل محتمل مؤهل"]]);

F('content','Content','المحتوى','✍',['social'],[
['d','Daily post from a long piece','بوست يومي من محتوى طويل',["Social editor","Turn the article below into today’s LinkedIn post","- Article: [paste]\n- Audience: finance professionals in Egypt and the Gulf\n- Voice: [describe or paste an example]","One strong post a day keeps the audience engaged","- Under 180 words; one idea only\n- Hook in the first line, question at the end\n- No claims not in the article","3 versions + suggested image idea."],["محرر سوشيال","حوّل المقال اللي تحت لبوست لينكدإن النهارده","- المقال: [الصق]\n- الجمهور: محترفين المالية في مصر والخليج\n- الصوت: [اوصف أو الصق مثال]","بوست قوي كل يوم بيخلي الجمهور متفاعل","- أقل من 180 كلمة؛ فكرة واحدة بس\n- جملة جذب في الأول وسؤال في الآخر\n- مفيش ادعاءات مش في المقال","3 نسخ + فكرة للصورة."],
"Hook: “Your month-end close is not slow. Your questions are.” … Question: What is the one report you would automate first?","جملة الجذب: «الإقفال الشهري مش بطيء. أسئلتك هي اللي بطيئة.» … السؤال: أول تقرير تحب تأتمته إيه؟"],
['w','Weekly newsletter','النشرة الأسبوعية',["Newsletter editor","Write this week’s newsletter from the links and notes below","- Links and notes: [paste]\n- Sections: one big idea, three quick tips, one tool","Subscribers should finish it in 4 minutes","- Under 600 words\n- Every fact linked to its source\n- Subject line options","Newsletter text + 3 subject lines."],["محرر نشرة","اكتب نشرة الأسبوع من الروابط والملاحظات اللي تحت","- الروابط والملاحظات: [الصق]\n- الأجزاء: فكرة كبيرة، 3 نصايح سريعة، أداة واحدة","المشتركين يخلصوها في 4 دقايق","- أقل من 600 كلمة\n- كل معلومة بمصدرها\n- اختيارات لعنوان الإيميل","نص النشرة + 3 عناوين."],
"Subject: “3 Claude habits that save finance teams a day a week” · Big idea: …","العنوان: «3 عادات Claude بتوفّر لفرق المالية يوم كل أسبوع» · الفكرة الكبيرة: …"],
['m','Monthly content audit','مراجعة المحتوى الشهرية',["Content strategist","Audit last month’s content performance","- Attached: social.csv","We double down on what works and drop the rest","- Top and bottom 5 by saves and follows\n- Patterns by format and pillar\n- Three experiments for next month","Audit table + patterns + experiments."],["استراتيجي محتوى","راجع أداء محتوى الشهر اللي فات","- مرفق: social.csv","نركّز على اللي شغال ونسيب الباقي","- أحسن وأضعف 5 بالحفظ والمتابعة\n- الأنماط حسب الشكل والمحور\n- 3 تجارب للشهر الجاي","جدول المراجعة + الأنماط + التجارب."],
"Carousels on how-to topics get 3× saves; opinion posts get comments but few follows","الكاروسيل في مواضيع إزاي بياخد 3 أضعاف الحفظ؛ وبوستات الرأي بتجيب تعليقات بس متابعات قليلة"],
['y','Annual editorial calendar','التقويم التحريري السنوي',["Editorial director","Build next year’s editorial calendar","- Business calendar: launches, events, seasons (Ramadan, budget season, year-end)\n- Pillars: [list]","Content should support business moments all year","- Monthly themes tied to business moments\n- Balance of pillars per quarter\n- Flagship pieces named","12-month calendar table + flagship list."],["مدير تحرير","ابني التقويم التحريري للسنة الجاية","- تقويم الشغل: الإطلاقات، الفعاليات، المواسم (رمضان، موسم الموازنة، آخر السنة)\n- المحاور: [قائمة]","المحتوى لازم يدعم لحظات الشغل طول السنة","- موضوع لكل شهر مربوط بلحظة شغل\n- توازن المحاور كل ربع\n- القطع الرئيسية متسمية","جدول 12 شهر + قائمة القطع الرئيسية."],
"Jan: planning season · Mar: Ramadan productivity · Oct: budget season series · Dec: year in review","يناير: موسم التخطيط · مارس: الإنتاجية في رمضان · أكتوبر: سلسلة موسم الموازنة · ديسمبر: حصاد السنة"]]);

F('operations','Operations','العمليات','⚙',['inventory','project'],[
['d','Daily stock-out risk','خطر نفاد المخزون اليومي',["Supply planner","Flag SKUs at risk of stock-out","- Attached: inventory.csv (sku, on hand, avg monthly sales, lead time, unit cost, last sale)","We must reorder before customers are affected","- Days of cover per SKU\n- At risk when cover < lead time\n- Suggested order quantity with formula","At-risk table + order suggestions."],["مخطط إمداد","علّم الأصناف المعرضة لنفاد المخزون","- مرفق: inventory.csv (الصنف، الموجود، متوسط المبيعات الشهرية، مدة التوريد، تكلفة الوحدة، آخر بيع)","لازم نطلب قبل ما العملاء يتأثروا","- أيام التغطية لكل صنف\n- معرّض للخطر لو التغطية أقل من مدة التوريد\n- الكمية المقترحة بالمعادلة","جدول المعرّض للخطر + اقتراحات الطلب."],
"SKU-118: cover 9 days vs lead time 21 → order 1,400 units · SKU-204: …","SKU-118: تغطية 9 أيام مقابل توريد 21 يوم ← اطلب 1,400 وحدة · SKU-204: …"],
['w','Weekly operations review','مراجعة العمليات الأسبوعية',["Operations manager","Prepare the weekly operations review","- KPIs: on-time delivery, output, scrap, overtime [paste]\n- Project plan: project.csv","Issues must reach the right owner by Monday","- KPI vs target with status\n- Delayed tasks with impact and owner\n- Top 3 issues with actions","Review sheet + action list."],["مدير عمليات","جهّز مراجعة العمليات الأسبوعية","- المؤشرات: التسليم في الميعاد، الإنتاج، الهالك، الأوفرتايم [الصق]\n- خطة المشروع: project.csv","المشاكل لازم توصل للمسؤول الصح يوم الاتنين","- المؤشر مقابل المستهدف بالحالة\n- المهام المتأخرة بأثرها ومسؤولها\n- أهم 3 مشاكل بإجراءات","ورقة المراجعة + قائمة الإجراءات."],
"On-time delivery 91% (target 95%) — truck availability · 2 tasks late: line 3 maintenance (owner: Karim)","التسليم في الميعاد 91% (المستهدف 95%) — توفر العربيات · مهمتين متأخرين: صيانة الخط 3 (المسؤول: كريم)"],
['m','Monthly slow-moving stock review','مراجعة المخزون الراكد الشهرية',["Inventory controller","Identify slow-moving and obsolete stock","- Attached: inventory.csv","Cash tied up in stock must be released","- Slow: no sale in 90+ days; obsolete: 180+\n- Value at cost per category\n- Actions: discount, return, write-off proposal","Table + value summary + action list."],["مراقب مخزون","حدد المخزون الراكد والمتقادم","- مرفق: inventory.csv","الفلوس المحبوسة في المخزون لازم تتحرر","- راكد: مفيش بيع من 90+ يوم؛ متقادم: 180+\n- القيمة بالتكلفة لكل فئة\n- الإجراءات: خصم، مرتجع، مقترح شطب","جدول + ملخص القيمة + قائمة الإجراءات."],
"Slow-moving EGP 1.9M (14 SKUs) · obsolete EGP 0.6M (5 SKUs) → propose clearance sale for 9 SKUs","راكد 1.9 مليون جنيه (14 صنف) · متقادم 0.6 مليون (5 أصناف) ← مقترح تصفية لـ 9 أصناف"],
['y','Annual capacity plan','خطة الطاقة السنوية',["Operations planning lead","Build next year’s capacity plan","- Sales forecast by month: [attach]\n- Line capacities and maintenance windows: [paste]","Capacity gaps must be solved before peak season","- Monthly demand vs capacity\n- Gaps with options (shifts, outsourcing, investment)\n- Cost of each option","Capacity table + options comparison."],["مسؤول تخطيط العمليات","ابني خطة الطاقة للسنة الجاية","- توقع المبيعات الشهري: [ارفع]\n- طاقات الخطوط ومواعيد الصيانة: [الصق]","فجوات الطاقة لازم تتحل قبل موسم الذروة","- الطلب الشهري مقابل الطاقة\n- الفجوات باختيارات (ورديات، تعهيد، استثمار)\n- تكلفة كل اختيار","جدول الطاقة + مقارنة الاختيارات."],
"Gap in Mar–Apr (Ramadan peak) of 18% → option A: third shift (EGP 1.2M), option B: outsourcing (EGP 1.6M)","فجوة في مارس–أبريل (ذروة رمضان) 18% ← اختيار أ: وردية تالتة (1.2 مليون جنيه)، اختيار ب: تعهيد (1.6 مليون)"]]);

F('procurement','Procurement','المشتريات','🛒',['suppliers','ap_aging'],[
['d','Daily purchase request check','مراجعة طلبات الشراء اليومية',["Procurement officer","Check today’s purchase requests against policy","- Requests: [attach]\n- Policy: thresholds, number of quotes, approved suppliers [paste]","Non-compliant requests must be returned quickly","- Each request: compliant / missing quotes / unapproved supplier / over threshold\n- What the requester must fix","Request table + return notes."],["مسؤول مشتريات","راجع طلبات الشراء النهارده مقابل السياسة","- الطلبات: [ارفع]\n- السياسة: الحدود، عدد العروض، الموردين المعتمدين [الصق]","الطلبات المخالفة لازم ترجع بسرعة","- كل طلب: مطابق / ناقصه عروض / مورد مش معتمد / فوق الحد\n- المطلوب من صاحب الطلب يصلّحه","جدول الطلبات + ملاحظات الإرجاع."],
"9 requests: 6 compliant, 2 missing a third quote, 1 unapproved supplier","9 طلبات: 6 مطابقين، 2 ناقصهم عرض تالت، 1 مورد مش معتمد"],
['w','Weekly supplier quote comparison','مقارنة عروض الموردين الأسبوعية',["Category buyer","Compare supplier quotes for this week’s tender","- Attached: suppliers.csv (supplier, price USD, quality score, lead time, payment days, on-time %, risk note)\n- Weights: price 40%, quality 25%, delivery 20%, terms 15%","The award must be defensible","- Weighted score with the formula\n- Risks noted per supplier\n- Recommendation with a runner-up","Scoring table + recommendation memo."],["مشتري فئة","قارن عروض الموردين لمناقصة الأسبوع ده","- مرفق: suppliers.csv (المورد، السعر بالدولار، الجودة، مدة التوريد، أيام السداد، الالتزام بالمواعيد، ملاحظة الخطر)\n- الأوزان: السعر 40%، الجودة 25%، التوريد 20%، الشروط 15%","الترسية لازم تكون مبررة","- الدرجة المرجّحة بالمعادلة\n- المخاطر لكل مورد\n- توصية ومورد بديل","جدول التقييم + مذكرة التوصية."],
"Supplier B 82/100 (price 2nd, quality 1st) · runner-up A 77 · risk: B single plant","المورد ب 82 من 100 (السعر التاني، الجودة الأول) · البديل أ 77 · خطر: ب عنده مصنع واحد"],
['m','Monthly spend analysis','تحليل الإنفاق الشهري',["Procurement analyst","Analyse this month’s spend","- Spend export: [attach]\n- Contracts list: [attach]","We find savings and off-contract spend","- Spend by category and supplier\n- Off-contract spend flagged\n- Top 3 savings ideas with estimates","Spend table + savings list."],["محلل مشتريات","حلل إنفاق الشهر ده","- تصدير الإنفاق: [ارفع]\n- قائمة العقود: [ارفع]","بندور على توفير وعلى إنفاق برا العقود","- الإنفاق حسب الفئة والمورد\n- الإنفاق برا العقود متعلّم\n- أهم 3 أفكار توفير بتقديراتها","جدول الإنفاق + قائمة التوفير."],
"Off-contract spend 11% (EGP 2.3M) — mostly packaging · saving idea: consolidate 4 packaging suppliers (~6%)","إنفاق برا العقود 11% (2.3 مليون جنيه) — أغلبه تغليف · فكرة توفير: دمج 4 موردين تغليف (حوالي 6%)"],
['y','Annual supplier performance review','المراجعة السنوية لأداء الموردين',["Supplier relationship manager","Prepare the annual supplier performance review","- Scorecards and incidents: [attach]\n- Spend by supplier: [attach]","We decide who to grow, keep or replace","- Score on quality, delivery, cost and service\n- Segmentation: strategic, keep, develop, exit\n- Development actions for key suppliers","Scorecard table + segmentation + actions."],["مدير علاقات الموردين","جهّز المراجعة السنوية لأداء الموردين","- بطاقات الأداء والحوادث: [ارفع]\n- الإنفاق حسب المورد: [ارفع]","بنقرر مين نكبّر ومين نحافظ عليه ومين نغيّره","- الدرجة في الجودة والتوريد والتكلفة والخدمة\n- التصنيف: استراتيجي، نحافظ، نطوّر، نخرج\n- إجراءات تطوير لأهم الموردين","جدول البطاقات + التصنيف + الإجراءات."],
"Strategic 4 · keep 11 · develop 3 · exit 2 (on-time < 80% for 3 quarters)","استراتيجي 4 · نحافظ 11 · نطوّر 3 · نخرج 2 (الالتزام أقل من 80% لـ 3 أرباع)"]]);
