GLOSS.push(
// Prompt engineering
["System prompt","برومبت النظام","Standing instructions that set Claude's role, rules and tone for a whole conversation or app.","تعليمات ثابتة بتحدد دور Claude وقواعده وأسلوبه طول المحادثة أو التطبيق."],
["Role prompting","تحديد الدور","Telling Claude which expert to act as, e.g. a senior auditor, to sharpen answers.","إنك تقول لـ Claude يتصرف كخبير معيّن، زي مراجع حسابات أول، عشان الإجابة تبقى أدق."],
["XML tags","وسوم XML","Labels like <contract> that wrap parts of a prompt so Claude can tell them apart.","علامات زي <contract> بتحوّط أجزاء البرومبت عشان Claude يفرّق بينها بوضوح."],
["Stop condition","شرط التوقف","A clear rule for when Claude should stop working or ask you before continuing.","قاعدة واضحة بتقول لـ Claude إمتى يقف أو يرجع لك قبل ما يكمّل."],
["Output format","شكل المخرج","The exact shape you want back: table, bullets, JSON, memo or email.","الشكل اللي عايز النتيجة بيه بالظبط: جدول أو نقاط أو JSON أو مذكرة أو إيميل."],
["Prefill","بداية الرد المسبقة","Writing the first words of Claude's reply via the API to steer its format or direction.","إنك تكتب أول كلمات رد Claude عن طريق الـ API عشان توجّه شكله أو اتجاهه."],
["Zero-shot","بدون أمثلة","Asking for a task with instructions only, without giving any worked examples.","إنك تطلب المهمة بالتعليمات بس من غير ما تدي أي أمثلة محلولة."],
["Rubric","معايير التقييم","A scored checklist used to judge whether an output is good enough.","قائمة معايير بدرجات بتستخدمها تحكم بيها إذا كان المخرج كويس كفاية."],
["Self-critique","المراجعة الذاتية","Asking Claude to review and improve its own draft against your criteria.","إنك تطلب من Claude يراجع مسودته ويحسّنها على حسب معاييرك."],
["Prompt library","مكتبة البرومبتات","A shared, tested collection of prompts a team reuses for recurring tasks.","مجموعة برومبتات مجرّبة ومشتركة الفريق بيعيد استخدامها في المهام المتكررة."],
["Master prompt","البرومبت الرئيسي","One detailed reusable prompt that captures context, rules and format for a whole job.","برومبت واحد مفصّل بيتعاد استخدامه وفيه السياق والقواعد والشكل لشغلانة كاملة."],
["Persona","الشخصية","A defined character, voice and audience Claude writes as, e.g. a CFO briefing the board.","شخصية وصوت وجمهور محددين Claude بيكتب على أساسهم، زي مدير مالي بيكلم مجلس الإدارة."],
["Constraint","القيد","A rule the output must respect, such as word limit, currency or no guessing.","قاعدة لازم المخرج يلتزم بيها، زي حد الكلمات أو العملة أو ممنوع التخمين."],
["Delimiter","الفاصل","Marks such as ### or tags that separate instructions from pasted data.","علامات زي ### أو وسوم بتفصل التعليمات عن البيانات الملصوقة."],
["Placeholder variable","المتغير البديل","A slot like {client_name} in a template that you fill each time you reuse it.","خانة زي {client_name} في القالب بتملاها كل مرة تعيد استخدامه."],
["Prompt iteration","تحسين البرومبت بالتكرار","Testing a prompt, reviewing results and refining it step by step.","إنك تجرّب البرومبت وتراجع النتايج وتحسّنه خطوة بخطوة."],
// AI and machine learning basics
["Inference","الاستدلال","The moment a trained model runs to produce an answer for your input.","اللحظة اللي الموديل المدرَّب بيشتغل فيها عشان يطلع إجابة على مدخلاتك."],
["Parameters","المعاملات","The learned internal numbers of a model; more usually means more capacity, not always better.","الأرقام الداخلية اللي الموديل اتعلمها؛ كترها غالبًا معناه قدرة أكبر بس مش دايمًا أحسن."],
["Training data","بيانات التدريب","The large body of text and other data a model learned patterns from.","الكم الكبير من النصوص والبيانات اللي الموديل اتعلم منها الأنماط."],
["Context","السياق","The background you give Claude: purpose, audience, data and constraints.","الخلفية اللي بتديها لـ Claude: الهدف والجمهور والبيانات والقيود."],
["Latency","زمن الاستجابة","How long you wait before a response starts or finishes.","المدة اللي بتستناها لحد ما الرد يبدأ أو يخلص."],
["Throughput","معدل الإنجاز","How much work a system processes in a given time, e.g. documents per hour.","كمية الشغل اللي النظام بيخلّصها في وقت معيّن، زي عدد المستندات في الساعة."],
["Multimodal input","المدخلات متعددة الوسائط","Giving Claude images, PDFs or charts alongside text in the same request.","إنك تدي Claude صور أو PDF أو رسوم بيانية مع النص في نفس الطلب."],
["OCR","التعرّف الضوئي على الحروف","Turning text in scanned documents or images into editable, searchable text.","تحويل النص اللي في المستندات الممسوحة أو الصور لنص قابل للتعديل والبحث."],
["Sentiment analysis","تحليل المشاعر","Classifying text as positive, negative or neutral, e.g. customer complaints.","تصنيف النص لإيجابي أو سلبي أو محايد، زي شكاوى العملاء."],
["Classification","التصنيف","Assigning each item to a predefined category, e.g. expense type or ticket priority.","إنك تحط كل عنصر في فئة محددة مسبقًا، زي نوع المصروف أو أولوية التذكرة."],
["Summarisation","التلخيص","Condensing long material into the key points for a specific reader.","اختصار المحتوى الطويل لأهم النقاط لقارئ معيّن."],
["Extraction","الاستخراج","Pulling specific fields, like dates, amounts or parties, out of documents.","سحب بيانات محددة زي التواريخ والمبالغ والأطراف من المستندات."],
["Semantic search","البحث الدلالي","Search by meaning rather than exact keywords, so similar ideas are found.","بحث بالمعنى مش بالكلمات بالظبط، فبيلاقي الأفكار المتشابهة."],
["Reranking","إعادة الترتيب","A second pass that reorders search results so the most relevant come first.","مرحلة تانية بتعيد ترتيب نتايج البحث عشان الأهم ييجي الأول."],
["Agentic workflow","سير عمل وكيلي","A process where AI plans, uses tools and takes several steps toward a goal.","عملية الذكاء الاصطناعي فيها بيخطط ويستخدم أدوات وياخد كذا خطوة لحد الهدف."],
["Guardrail","حاجز الأمان","A rule or check that keeps AI outputs and actions within safe, approved limits.","قاعدة أو فحص بيخلي مخرجات وتصرفات الـ AI جوه حدود آمنة ومعتمدة."],
["Red teaming","اختبار الاختراق العدائي","Deliberately attacking an AI system to find weaknesses before real users do.","مهاجمة نظام الـ AI عن قصد عشان تكتشف نقط ضعفه قبل المستخدمين الحقيقيين."],
["Jailbreak","كسر القيود","A trick prompt that tries to make a model ignore its safety rules.","برومبت فيه حيلة بيحاول يخلي الموديل يتجاهل قواعد الأمان بتاعته."],
["Alignment","المواءمة","Making AI behave according to human intentions and values.","إن الذكاء الاصطناعي يتصرف بما يتوافق مع نوايا البشر وقيمهم."],
["Interpretability","قابلية التفسير","Research into understanding what happens inside a model when it produces an answer.","أبحاث بتحاول تفهم إيه اللي بيحصل جوه الموديل وهو بيطلع الإجابة."],
["Constitutional AI","الذكاء الاصطناعي الدستوري","Anthropic's published approach of training a model to follow a written set of guiding principles.","منهج Anthropic المنشور لتدريب الموديل إنه يلتزم بمجموعة مبادئ مكتوبة."],
["Model distillation","تقطير الموديل","Training a smaller model to imitate a larger one so it runs faster and cheaper.","تدريب موديل أصغر يقلّد موديل أكبر عشان يشتغل أسرع وأرخص."],
["Open-weight model","موديل مفتوح الأوزان","A model whose trained parameters are published so others can download and run it.","موديل معاملاته المدرَّبة منشورة وأي حد يقدر ينزّله ويشغّله."],
["Benchmark","المعيار المرجعي","A standard test used to compare model performance on specific tasks.","اختبار قياسي بيستخدم لمقارنة أداء الموديلات في مهام معيّنة."],
// Claude usage and administration
["Seat","المقعد","One licensed user on a team or enterprise plan.","مستخدم واحد مرخّص في خطة فريق أو مؤسسة."],
["Admin console","لوحة الإدارة","Where administrators manage members, settings and permissions for an organisation.","المكان اللي المسؤولين بيديروا منه الأعضاء والإعدادات والصلاحيات للمؤسسة."],
["Workspace","مساحة العمل","A separate area that groups users, keys or settings, e.g. per team or project.","مساحة منفصلة بتجمّع مستخدمين أو مفاتيح أو إعدادات، زي لكل فريق أو مشروع."],
["API key","مفتاح API","A secret credential that lets software call the model; store it like a password.","بيانات سرية بتسمح للبرامج تكلّم الموديل؛ احفظها زي الباسورد."],
["Usage dashboard","لوحة الاستخدام","A view of how much is being used and by whom, for budgeting and oversight.","عرض لحجم الاستخدام ومين بيستخدم، عشان الميزانية والرقابة."],
["Model selection","اختيار الموديل","Choosing the model that fits the task's quality, speed and cost needs.","اختيار الموديل المناسب لاحتياجات المهمة من حيث الجودة والسرعة والتكلفة."],
["Extended context","السياق الممتد","Using a larger context window, where offered, to handle very long documents in one go.","استخدام نافذة سياق أكبر، لو متاحة، للتعامل مع مستندات طويلة جدًا مرة واحدة."],
// Data and governance
["PII","البيانات الشخصية المعرِّفة","Personally identifiable information, such as names, IDs, phone numbers or account numbers.","بيانات بتعرّف الشخص، زي الأسماء وأرقام البطاقة والتليفونات وأرقام الحسابات."],
["Data classification","تصنيف البيانات","Labelling data by sensitivity, e.g. public, internal, confidential, restricted.","تصنيف البيانات حسب حساسيتها: عامة، داخلية، سرية، مقيّدة."],
["Anonymisation","إخفاء الهوية","Removing identifiers permanently so data can no longer be linked to a person.","حذف المعرِّفات نهائيًا بحيث البيانات ماتتربطش بأي شخص تاني."],
["Pseudonymisation","الترميز المستعار","Replacing identifiers with codes; the key to re-identify is kept separately and secured.","استبدال المعرِّفات بأكواد، ومفتاح الربط بيتحفظ لوحده في مكان آمن."],
["Data minimisation","تقليل البيانات","Sharing only the data a task truly needs, nothing extra.","إنك تشارك البيانات اللي المهمة محتاجاها فعلًا بس، من غير زيادة."],
["Data residency","مكان استضافة البيانات","Where data is physically stored and processed, often set by local regulation.","المكان اللي البيانات بتتخزن وتتعالج فيه فعليًا، وغالبًا بتحدده اللوائح المحلية."],
["DLP","منع تسرّب البيانات","Data loss prevention: tools and rules that stop sensitive data leaving the company.","أدوات وقواعد بتمنع البيانات الحساسة إنها تخرج برّه الشركة."],
["Consent","الموافقة","A person's informed permission for their data to be used for a stated purpose.","إذن الشخص الواعي باستخدام بياناته لغرض معلن."],
["Retention policy","سياسة الاحتفاظ","Rules on how long data and chats are kept and when they are deleted.","قواعد بتحدد البيانات والمحادثات تتحفظ قد إيه وإمتى تتمسح."],
["Model risk management","إدارة مخاطر النماذج","Controls to validate, monitor and govern models used in decisions, common in banks.","ضوابط للتحقق من النماذج ومتابعتها وحوكمتها لما تُستخدم في القرارات، ومنتشرة في البنوك."],
["AI policy","سياسة الذكاء الاصطناعي","The company rulebook on approved AI tools, allowed data and required reviews.","دليل الشركة للأدوات المعتمدة والبيانات المسموحة والمراجعات المطلوبة."],
["Use-case register","سجل حالات الاستخدام","A central list of every AI use case with its owner, risk level and status.","قائمة مركزية بكل حالة استخدام للـ AI ومسؤولها ومستوى خطورتها وحالتها."],
["Approval matrix","مصفوفة الصلاحيات","A table defining who must approve what, by amount or risk level.","جدول بيحدد مين لازم يعتمد إيه، حسب المبلغ أو مستوى الخطورة."],
["Segregation of duties","الفصل بين المهام","No single person, or AI agent, both prepares and approves the same transaction.","مفيش شخص واحد، ولا وكيل AI، يجهّز ويعتمد نفس العملية."],
// Finance and business use of AI
["Variance commentary","تعليق الانحرافات","Narrative explaining why actuals differ from budget or forecast.","شرح مكتوب ليه الأرقام الفعلية مختلفة عن الموازنة أو التوقعات."],
["Driver-based forecast","التوقع المبني على المحركات","A forecast built from business drivers like volume, price and headcount.","توقع مبني على محركات النشاط زي الكميات والأسعار وعدد الموظفين."],
["13-week cash flow","التدفق النقدي لـ 13 أسبوع","A rolling weekly cash forecast for the next quarter, used to manage liquidity.","توقع نقدي أسبوعي متجدد للربع الجاي، بيستخدم لإدارة السيولة."],
["Reconciliation","التسوية","Matching two records, e.g. bank statement and ledger, and explaining differences.","مطابقة سجلين، زي كشف البنك ودفتر الأستاذ، وتفسير الفروق."],
["Three-way match","المطابقة الثلاثية","Checking purchase order, goods receipt and invoice agree before paying.","التأكد إن أمر الشراء وإذن الاستلام والفاتورة متطابقين قبل الدفع."],
["Anomaly detection","كشف الحالات الشاذة","Spotting unusual transactions or patterns that may signal errors or fraud.","اكتشاف العمليات أو الأنماط الغريبة اللي ممكن تكون أخطاء أو احتيال."],
["KPI pack","حزمة مؤشرات الأداء","A regular set of KPI charts and commentary sent to management.","مجموعة دورية من رسوم مؤشرات KPI مع تعليقات بتتبعت للإدارة."],
["Management accounts","الحسابات الإدارية","Internal monthly financial reports used to run the business, not for statutory filing.","تقارير مالية داخلية شهرية لإدارة الشغل، مش للإيداع القانوني."],
["Scenario analysis","تحليل السيناريوهات","Comparing outcomes under different cases such as base, upside and downside.","مقارنة النتايج تحت حالات مختلفة زي الأساسي والمتفائل والمتشائم."],
["Sensitivity analysis","تحليل الحساسية","Changing one input at a time to see how much it moves the result.","تغيير مدخل واحد كل مرة عشان تشوف بيأثر على النتيجة قد إيه."],
["Unit economics","اقتصاديات الوحدة","Revenue and cost per unit, customer or order, to test if growth is profitable.","الإيراد والتكلفة لكل وحدة أو عميل أو طلب، عشان تعرف النمو مربح ولا لأ."],
["ROI of AI","العائد على الاستثمار في AI","Value gained from AI, such as hours saved or errors avoided, versus its total cost.","القيمة اللي بتكسبها من الـ AI زي الساعات الموفرة والأخطاء اللي اتجنبتها مقابل تكلفته الكلية."],
["Time-to-value","الوقت لتحقيق القيمة","How quickly a new tool or process starts delivering measurable benefit.","الأداة أو العملية الجديدة بتبدأ تجيب فايدة ملموسة بعد قد إيه."],
["Change management","إدارة التغيير","Planning communication, training and support so people actually adopt a new way of working.","تخطيط التواصل والتدريب والدعم عشان الناس فعلًا تتبنى طريقة الشغل الجديدة."],
["Pilot","التجربة الأولية","A small, time-boxed trial with clear success metrics before wider rollout.","تجربة صغيرة لمدة محددة بمؤشرات نجاح واضحة قبل التعميم."],
["AI champion","سفير الذكاء الاصطناعي","An enthusiastic team member who helps colleagues learn and use AI tools.","زميل متحمس بيساعد زمايله يتعلموا ويستخدموا أدوات الـ AI."],
["Adoption rate","معدل التبنّي","The share of intended users actively using a tool over a period.","نسبة المستخدمين المستهدفين اللي بيستخدموا الأداة فعلًا خلال فترة."],
["Month-end close","الإقفال الشهري","The routine of posting, reconciling and reviewing accounts to finalise a month's numbers.","روتين القيود والتسويات والمراجعة لاعتماد أرقام الشهر بشكل نهائي."],
["Exception report","تقرير الاستثناءات","A list of only the items that break a rule or threshold, for focused review.","قائمة بالبنود اللي بتخالف قاعدة أو حد معيّن بس، عشان المراجعة تبقى مركّزة."]
);
