DEEP.integration={icon:"⇌",t:T("API integration, agents & mini-ERP build","تكامل الـ API والوكلاء وبناء Mini-ERP"),sub:T("Professional integration patterns with steps and master prompts — plus a 6-phase mini-ERP build.","أنماط تكامل احترافية بخطوات وبرومبتات ماستر — وبناء Mini-ERP على 6 مراحل."),
sections:[
{h:T("Integration patterns","أنماط التكامل"),b:T(`<table><tr><th>Pattern</th><th>How</th><th>Example</th></tr>
<tr><td>Request–response</td><td>Your app calls the Messages API and shows the answer</td><td>Commentary button in a BI dashboard</td></tr>
<tr><td>Batch</td><td>Nightly Batches API job, 50% cheaper</td><td>Classify 200K transactions</td></tr>
<tr><td>Extraction to system</td><td>Structured outputs → validate → write to ERP</td><td>Invoices to AP drafts</td></tr>
<tr><td>Grounded Q&A</td><td>Documents + citations (+ caching)</td><td>Policy or annual-report assistant</td></tr>
<tr><td>Tool-using agent</td><td>Agent SDK or Managed Agents with tools/MCP</td><td>KYC first pass, AP agent</td></tr>
<tr><td>Event-driven</td><td>Webhook from your system triggers a Claude call</td><td>New contract uploaded → risk summary</td></tr></table>`,`<table><tr><th>النمط</th><th>إزاي</th><th>مثال</th></tr>
<tr><td>طلب ورد</td><td>تطبيقك بينادي Messages API ويعرض الرد</td><td>زرار تعليق في داشبورد BI</td></tr>
<tr><td>دفعي</td><td>مهمة Batches بالليل، أرخص 50%</td><td>تصنيف 200 ألف عملية</td></tr>
<tr><td>استخراج لنظام</td><td>مخرجات مهيكلة ← تحقق ← كتابة في الـ ERP</td><td>الفواتير لمسودات الدائنين</td></tr>
<tr><td>أسئلة مستندة</td><td>مستندات + استشهادات (+ كاش)</td><td>مساعد سياسات أو تقارير سنوية</td></tr>
<tr><td>وكيل بأدوات</td><td>Agent SDK أو Managed Agents بأدوات/MCP</td><td>فحص KYC، وكيل الدائنين</td></tr>
<tr><td>مبني على أحداث</td><td>Webhook من نظامك بيشغّل Claude</td><td>عقد جديد اترفع ← ملخص مخاطر</td></tr></table>`)},
{h:T("8 steps for any API integration","8 خطوات لأي تكامل API"),b:T(`<ol><li>Define the business outcome and success metric.</li><li>Prototype the prompt in the Console with 10 real samples.</li><li>Fix the output contract (JSON schema / structured outputs).</li><li>Choose the model per step (Haiku bulk, Sonnet default, Opus hard).</li><li>Add validation outside the model (totals, IDs, ranges).</li><li>Add cost levers: caching, batches, short outputs.</li><li>Secure: keys in a vault, least privilege, logging, no client data you can't share.</li><li>Evaluate on a labelled set; monitor accuracy and cost monthly.</li></ol>`,`<ol><li>حدد نتيجة البيزنس ومؤشر النجاح.</li><li>جرّب البرومبت في الكونسول على 10 عينات حقيقية.</li><li>ثبّت عقد المخرجات (JSON schema / مخرجات مهيكلة).</li><li>اختار الموديل لكل خطوة (Haiku للكمّي، Sonnet الافتراضي، Opus للصعب).</li><li>ضيف تحقق برّه الموديل (الإجماليات، الأرقام التعريفية، النطاقات).</li><li>ضيف أدوات التوفير: الكاش، Batches، مخرجات قصيرة.</li><li>أمّن: المفاتيح في خزنة، أقل صلاحية، سجلات، ومفيش بيانات عملاء مش مسموح تشاركها.</li><li>قيّم على مجموعة معلّمة؛ وتابع الدقة والتكلفة كل شهر.</li></ol>`)},
{h:T("Mini-ERP build — 6 phases","بناء Mini-ERP — 6 مراحل"),b:T(`<ol><li><b>Spec</b> — modules, data model, accounting rules.</li><li><b>Prototype</b> — artifact with storage to validate the workflow.</li><li><b>App</b> — Claude Code: backend, database, auth.</li><li><b>Accounting engine</b> — posting rules, tests, trial balance always balances.</li><li><b>MCP server</b> — read-only tools so Claude can query it.</li><li><b>AI assistant & governance</b> — agent for questions and drafts, approvals and audit trail.</li></ol><p>Each phase has a master prompt in the cases below.</p>`,`<ol><li><b>المواصفات</b> — الموديولات ونموذج البيانات والقواعد المحاسبية.</li><li><b>النموذج الأولي</b> — Artifact بتخزين علشان نتأكد من سير العمل.</li><li><b>التطبيق</b> — Claude Code: باك إند وقاعدة بيانات ودخول.</li><li><b>المحرك المحاسبي</b> — قواعد الترحيل والاختبارات والميزان متوازن دايماً.</li><li><b>سيرفر MCP</b> — أدوات قراءة علشان Claude يسأله.</li><li><b>المساعد والحوكمة</b> — وكيل للأسئلة والمسودات بموافقات وسجل تدقيق.</li></ol><p>لكل مرحلة برومبت ماستر في الحالات تحت.</p>`)}
],
cases:[
CM("API 1 · Commentary in the BI dashboard","API 1 · تعليق جوه داشبورد BI","API · request–response","","",["Define fields","Prompt in Console","Endpoint + button"],["حدد الحقول","البرومبت في الكونسول","Endpoint + زرار"],
["Senior integration engineer","Add an 'Explain this variance' button to our BI dashboard backed by the Claude API","- Payload: KPI name, actual, budget, LY, top 5 drivers (JSON)\n- Model: Sonnet; max 120 words; Arabic or English per user setting\n- Stack: Python FastAPI service called by the BI tool","Managers want explanations where they look at numbers","- Endpoint with input validation and timeout\n- Prompt template versioned in repo\n- No raw customer data sent; logs without PII","Code, prompt template, tests with 10 payloads, and a cost estimate per 1,000 clicks."],
["مهندس تكامل أول","ضيف زرار 'اشرح الانحراف ده' في داشبورد الـ BI مدعوم بـ Claude API","- البيانات: اسم المؤشر، الفعلي، الموازنة، السنة اللي فاتت، أهم 5 أسباب (JSON)\n- الموديل: Sonnet؛ أقصى 120 كلمة؛ عربي أو إنجليزي حسب المستخدم\n- التقنية: خدمة Python FastAPI بتناديها أداة الـ BI","المديرين عايزين الشرح في نفس مكان الأرقام","- Endpoint بتحقق من المدخلات ومهلة\n- قالب البرومبت متسجل بنسخ في الـ repo\n- مفيش بيانات عملاء خام؛ والسجلات من غير بيانات شخصية","الكود، قالب البرومبت، اختبارات بـ 10 حالات، وتقدير تكلفة لكل 1000 ضغطة."]),
CM("API 2 · Transaction classification (Batches)","API 2 · تصنيف العمليات (Batches)","API · batch","","",["Labelled sample","Batch job","QA"],["عينة معلّمة","مهمة دفعية","مراجعة جودة"],
["ML engineer for a bank","Classify card transactions into spend categories with the Batches API","- 200K transactions/night: merchant name (Arabic/English), MCC, amount\n- 25 categories; 2,000 labelled examples\n- Haiku for bulk; Sonnet for low-confidence retries","Personal-finance insights for customers","- Accuracy ≥ 92% on a held-out set\n- Structured output {category, confidence}\n- Cost per million transactions reported","Pipeline code, prompts, evaluation report, runbook."],
["مهندس تعلم آلي في بنك","صنّف عمليات الكروت لفئات إنفاق بـ Batches API","- 200 ألف عملية كل ليلة: اسم التاجر (عربي/إنجليزي)، MCC، المبلغ\n- 25 فئة؛ و2000 مثال معلّم\n- Haiku للكمّي؛ و Sonnet لإعادة المحاولة في الحالات الضعيفة","رؤى إنفاق شخصية للعملاء","- دقة ≥ 92% على مجموعة اختبار منفصلة\n- مخرج مهيكل {category, confidence}\n- تكلفة كل مليون عملية","كود خط المعالجة، البرومبتات، تقرير التقييم، دليل التشغيل."]),
CM("API 3 · Document intake to ERP","API 3 · استقبال المستندات للـ ERP","API · extraction","","",["Schema","Validation","ERP draft"],["الـ Schema","التحقق","مسودة الـ ERP"],
["Integration architect","Build a document-intake service: PDFs → structured data → ERP draft records","- Document types: invoices, delivery notes, bank advices\n- Structured outputs per type; validation rules; ERP REST API for drafts only","Remove manual keying with full traceability","- Every field has source page reference\n- Failed validations to a review queue\n- Nothing posted without approval","Architecture, schemas, code, tests, monitoring dashboard spec."],
["مهندس معماري للتكامل","ابني خدمة استقبال مستندات: PDF ← بيانات مهيكلة ← مسودات في الـ ERP","- الأنواع: فواتير، أذون تسليم، إشعارات بنكية\n- مخرجات مهيكلة لكل نوع؛ قواعد تحقق؛ REST API للـ ERP للمسودات بس","نلغي الإدخال اليدوي مع تتبع كامل","- كل حقل ليه مرجع صفحة\n- اللي يفشل في التحقق يروح طابور مراجعة\n- مفيش ترحيل من غير موافقة","المعمارية، الـ Schemas، الكود، الاختبارات، مواصفات داشبورد المتابعة."]),
CM("API 4 · Email router (Arabic/English)","API 4 · موجّه الإيميلات (عربي/إنجليزي)","API · event-driven","","",["Webhook","Classify","Route"],["Webhook","التصنيف","التوجيه"],
["Customer-operations engineer","Route incoming customer emails with the Claude API","- Trigger: webhook on new email\n- Output: {department, urgency, language, summary, suggested_reply}\n- Departments: billing, delivery, complaints, sales, other","Emails wait days in a shared inbox","- Routing accuracy ≥ 90% on 300 labelled emails\n- Suggested reply saved as draft only\n- PII redaction before logging","Code, prompt, schema, evaluation and rollout plan."],
["مهندس عمليات العملاء","وجّه إيميلات العملاء الواردة بـ Claude API","- التشغيل: Webhook مع كل إيميل جديد\n- المخرج: {الإدارة، الأولوية، اللغة، ملخص، رد مقترح}\n- الإدارات: الفواتير، التوصيل، الشكاوى، المبيعات، أخرى","الإيميلات بتستنى أيام في بريد مشترك","- دقة التوجيه ≥ 90% على 300 إيميل معلّم\n- الرد المقترح يتحفظ مسودة بس\n- إخفاء البيانات الشخصية قبل التسجيل","الكود، البرومبت، الـ Schema، التقييم وخطة الإطلاق."]),
CM("Agent 1 · Month-end orchestrator (multi-agent)","وكيل 1 · منسّق إقفال الشهر (وكلاء متعددين)","Agent SDK","","",["Sub-agents","Orchestrator","Controller sign-off"],["وكلاء فرعيين","المنسّق","اعتماد الكنترولر"],
["Agent architect","Design a month-end orchestrator using the Agent SDK with sub-agents","- Sub-agents: bank-rec, accruals, fixed assets, variance commentary\n- Tools: file access (copies), ERP read (MCP), spreadsheet creation\n- Close calendar with dependencies","Shorten close from 8 to 4 days","- Orchestrator tracks status and blockers\n- Each sub-agent outputs drafts with evidence\n- Controller approves; no postings by agents","Architecture diagram, agent definitions, prompts, guardrails, test plan."],
["مهندس وكلاء","صمّم منسّق إقفال شهر بـ Agent SDK ووكلاء فرعيين","- الوكلاء الفرعيين: مطابقة البنوك، المستحقات، الأصول الثابتة، تعليق الانحرافات\n- الأدوات: الوصول للملفات (نسخ)، قراءة الـ ERP (MCP)، إنشاء جداول\n- جدول الإقفال بالاعتماديات","نقلل الإقفال من 8 أيام لـ 4","- المنسّق يتابع الحالة والمعوقات\n- كل وكيل فرعي يطلّع مسودات بأدلة\n- الكنترولر يعتمد؛ والوكلاء ميرحّلوش","مخطط المعمارية، تعريفات الوكلاء، البرومبتات، الضوابط، خطة الاختبار."]),
CM("Agent 2 · Vendor due-diligence (Managed Agent)","وكيل 2 · الفحص النافي للجهالة للموردين (Managed Agent)","Managed Agents","","",["Checklist","Agent run","Report"],["القائمة","تشغيل الوكيل","التقرير"],
["Procurement risk lead","Configure a managed agent for new-vendor due diligence","- Inputs: vendor name, registry number, country\n- Tools: web search/fetch, document store, our checklist\n- Output: cited due-diligence report","New vendors take 3 weeks to approve","- Ownership, litigation/news, financial health signals, sanctions screening via approved provider\n- Every claim cited\n- Risk rating proposal; human approves","Agent configuration, system prompt, permissions, report template."],
["مسؤول مخاطر المشتريات","جهّز Managed Agent لفحص الموردين الجدد","- المدخلات: اسم المورد، رقم السجل، الدولة\n- الأدوات: بحث وقراءة ويب، مخزن مستندات، قائمتنا\n- المخرج: تقرير فحص بمصادر","الموردين الجدد بياخدوا 3 أسابيع للموافقة","- الملكية، القضايا/الأخبار، مؤشرات السلامة المالية، فحص العقوبات عبر مزوّد معتمد\n- كل ادعاء بمصدر\n- اقتراح تصنيف مخاطر والإنسان يعتمد","إعدادات الوكيل، system prompt، الصلاحيات، قالب التقرير."]),
CM("ERP 1 · Spec","ERP 1 · المواصفات","Chat (Opus)","","",["Interview","Data model","Rules"],["الأسئلة","نموذج البيانات","القواعد"],
["ERP solution architect and chartered accountant","Write the mini-ERP specification","- Company: Egyptian trading SME, 15 users\n- Modules: inventory, sales, purchases, cash/bank, GL, reports\n- VAT 14%, EGP + USD, Arabic/English","Avoid rework by agreeing scope before building","- Data model (entities, fields, relations)\n- Posting rules for every transaction type\n- Roles and permissions; reports list","Spec document + ERD (Mermaid) + posting-rules table."],
["مهندس حلول ERP ومحاسب قانوني","اكتب مواصفات الـ Mini-ERP","- الشركة: تجارية صغيرة مصرية، 15 مستخدم\n- الموديولات: المخزون، المبيعات، المشتريات، النقدية/البنوك، الأستاذ العام، التقارير\n- ضريبة 14%، جنيه + دولار، عربي/إنجليزي","نتجنب إعادة الشغل بالاتفاق على النطاق قبل البناء","- نموذج البيانات (الكيانات، الحقول، العلاقات)\n- قواعد الترحيل لكل نوع معاملة\n- الأدوار والصلاحيات؛ قائمة التقارير","وثيقة المواصفات + ERD (Mermaid) + جدول قواعد الترحيل."]),
CM("ERP 2 · Artifact prototype","ERP 2 · نموذج أولي Artifact","Artifact","","",["Build","Demo data","User test"],["البناء","بيانات تجريبية","اختبار المستخدمين"],
["Product prototyper","Build a clickable mini-ERP prototype from the spec","- Spec attached\n- Persist demo data in artifact storage\n- Screens: dashboard, items, invoices, journals, TB, aging","Users validate the workflow before we code the real app","- Every invoice creates a balanced journal\n- TB balances\n- Reset demo button","Single-file HTML artifact + a 1-page test script for users."],
["مصمم نماذج أولية","ابني نموذج Mini-ERP قابل للتجربة من المواصفات","- المواصفات مرفقة\n- احفظ البيانات التجريبية في تخزين الـ Artifact\n- الشاشات: الرئيسية، الأصناف، الفواتير، القيود، الميزان، الأعمار","المستخدمين يتأكدوا من سير العمل قبل كود التطبيق الحقيقي","- كل فاتورة بتعمل قيد متوازن\n- الميزان متوازن\n- زرار إعادة الديمو","Artifact HTML ملف واحد + سيناريو اختبار صفحة للمستخدمين."]),
CM("ERP 3 · Production app","ERP 3 · التطبيق الإنتاجي","Claude Code","","",["/plan","Build modules","Deploy"],["/plan","ابني الموديولات","انشر"],
["Senior full-stack engineer","Build the mini-ERP as a production web app","- Stack: Python FastAPI + PostgreSQL + React (or your recommendation)\n- Auth with roles; audit log on every change\n- Arabic/English, RTL","Replace spreadsheets with a controlled system","- Modules per spec with migrations\n- Role-based access tested\n- CI with tests","/plan first; CLAUDE.md; code; tests; deployment guide; backup plan."],
["مهندس Full-stack أول","ابني الـ Mini-ERP كتطبيق ويب إنتاجي","- التقنية: Python FastAPI + PostgreSQL + React (أو ترشيحك)\n- دخول بأدوار؛ سجل تدقيق على كل تغيير\n- عربي/إنجليزي، RTL","نبدّل الجداول بنظام تحت السيطرة","- الموديولات حسب المواصفات بـ migrations\n- الصلاحيات متجربة\n- CI باختبارات","/plan الأول؛ CLAUDE.md؛ الكود؛ الاختبارات؛ دليل النشر؛ خطة النسخ الاحتياطي."]),
CM("ERP 4 · Accounting engine & tests","ERP 4 · المحرك المحاسبي والاختبارات","Claude Code","","",["Rules","Tests","Reconcile"],["القواعد","الاختبارات","المطابقة"],
["Accounting-systems engineer","Implement and test the posting engine","- Posting rules table from the spec\n- Weighted-average inventory; VAT 14%; FX revaluation month-end","Wrong postings destroy trust in the system","- Unit tests for every transaction type\n- Property test: debits = credits always\n- Month-end FX revaluation tested","Code, 50+ tests, a sample month with TB and statements."],
["مهندس أنظمة محاسبية","نفّذ واختبر محرك الترحيل","- جدول قواعد الترحيل من المواصفات\n- متوسط مرجح للمخزون؛ ضريبة 14%؛ إعادة تقييم العملة آخر الشهر","الترحيل الغلط بيهدم الثقة في النظام","- اختبارات لكل نوع معاملة\n- اختبار خاصية: المدين = الدائن دايماً\n- إعادة تقييم آخر الشهر متجربة","الكود، أكتر من 50 اختبار، شهر عينة بالميزان والقوائم."]),
CM("ERP 5 · MCP server","ERP 5 · سيرفر MCP","Claude Code · MCP","","",["Tools","Server","Connector"],["الأدوات","السيرفر","الـ Connector"],
["Integration engineer","Expose the mini-ERP to Claude through a read-only MCP server","- Tools: get_trial_balance, get_aging, search_invoices, get_item_stock, get_kpis\n- OAuth; row-level permissions mirror ERP roles","Managers ask questions in plain Arabic or English","- readOnlyHint on every tool\n- Parameterised queries only\n- Tested in MCP Inspector and Claude","Server code, tests, deployment notes, connector setup steps."],
["مهندس تكامل","اعرض الـ Mini-ERP لـ Claude عبر سيرفر MCP للقراءة بس","- الأدوات: get_trial_balance و get_aging و search_invoices و get_item_stock و get_kpis\n- OAuth؛ وصلاحيات على مستوى الصف زي أدوار الـ ERP","المديرين بيسألوا بعربي أو إنجليزي عادي","- readOnlyHint على كل أداة\n- استعلامات بمعاملات بس\n- متجرب في MCP Inspector و Claude","كود السيرفر، الاختبارات، ملاحظات النشر، خطوات إعداد الـ Connector."]),
CM("ERP 6 · AI assistant & governance","ERP 6 · المساعد الذكي والحوكمة","Agent · Project","","",["Assistant","Write tools with approval","Audit"],["المساعد","أدوات كتابة بموافقة","التدقيق"],
["AI product owner for the mini-ERP","Launch a CFO assistant on the ERP with governance","- MCP read tools live; add draft-only write tools (draft invoice, draft journal)\n- Users: CFO, accountants, sales managers","Faster answers without losing control","- Use-case register and risk tier\n- Approval workflow for any draft\n- Monthly sample audit of answers","Assistant instructions, permission matrix, approval flow, audit checklist."],
["مالك منتج الـ AI للـ Mini-ERP","أطلق مساعد مدير مالي على الـ ERP بحوكمة","- أدوات القراءة MCP شغالة؛ ضيف أدوات كتابة مسودات بس (مسودة فاتورة، مسودة قيد)\n- المستخدمين: المدير المالي، المحاسبين، مديري المبيعات","إجابات أسرع من غير ما نفقد السيطرة","- سجل حالات الاستخدام ومستوى الخطر\n- دورة موافقة لأي مسودة\n- مراجعة عينة شهرية للإجابات","تعليمات المساعد، مصفوفة الصلاحيات، دورة الموافقة، قائمة التدقيق."])
]};
