const CC={agent:T('Agents','الوكلاء'),artifacts:T('Artifacts','Artifacts'),design:T('Claude Design','Claude Design'),project:T('Projects & chat','Projects والشات'),connectors:T('Connectors (MCP)','Connectors (MCP)'),plugin:T('Plugins','Plugins'),skills:T('Skills','Skills'),automation:T('Automation','الأتمتة')};
const CSTEPS={agent:[["Download the test data","Open the Agent Builder (or Cowork)","Paste the master prompt as the agent's system prompt","Approve the plan it proposes","Review every draft before any external action"],["نزّل بيانات الاختبار","افتح باني الوكلاء (أو Cowork)","الصق البرومبت الماستر كـ System prompt للوكيل","وافق على الخطة اللي بيقترحها","راجع كل مسودة قبل أي إجراء خارجي"]],
artifacts:[["Download the test data","Open a new chat and attach it","Paste the master prompt","Test the artifact with the sample rows","Publish and share the link"],["نزّل بيانات الاختبار","افتح محادثة جديدة وارفعها","الصق البرومبت الماستر","اختبر الـ Artifact بالصفوف التجريبية","انشره وشارك اللينك"]],
design:[["Open claude.ai/design","Upload your brand assets (or set up the design system)","Paste the master prompt","Iterate with comments on the canvas","Export (PDF, PPTX, Canva or hand-off to Claude Code)"],["افتح claude.ai/design","ارفع مواد البراند (أو جهّز نظام التصميم)","الصق البرومبت الماستر","طوّر بالتعليقات على اللوحة","صدّر (PDF أو PPTX أو Canva أو سلّم لـ Claude Code)"]],
project:[["Create a Project and add the instructions","Upload stable reference files","Attach the test data in a chat","Paste the master prompt","Save good outputs back to the Project"],["اعمل Project وضيف التعليمات","ارفع الملفات المرجعية الثابتة","ارفع بيانات الاختبار في محادثة","الصق البرومبت الماستر","احفظ المخرجات الكويسة في الـ Project"]],
connectors:[["Connect the connector in Customize → Connectors","Confirm read-only permissions first","Paste the master prompt","Check results against the source system","Approve any write action explicitly"],["وصّل الـ Connector من Customize ← Connectors","اتأكد إن الصلاحيات قراءة بس الأول","الصق البرومبت الماستر","راجع النتايج على النظام الأصلي","وافق صراحة على أي كتابة"]],
plugin:[["Install the plugin from Customize → Plugins","Run its slash command once to see the format","Paste the master prompt with your data","Review against your policy","Share the plugin with the team"],["نزّل الـ Plugin من Customize ← Plugins","شغّل أمره مرة علشان تشوف الشكل","الصق البرومبت الماستر ببياناتك","راجع على سياستك","شارك الـ Plugin مع الفريق"]],
skills:[["Build or install the skill","Test the trigger with 3 requests","Attach the test data","Paste the master prompt","Refine the SKILL.md from what you learned"],["ابني أو نزّل الـ Skill","اختبر التشغيل بـ 3 طلبات","ارفع بيانات الاختبار","الصق البرومبت الماستر","حسّن SKILL.md من اللي اتعلمته"]],
automation:[["Put inputs in a dedicated folder (copies)","Paste the master prompt in Cowork","Run once and review","Turn it into a scheduled task","Review the first 5 runs fully"],["حط المدخلات في فولدر مخصص (نسخ)","الصق البرومبت الماستر في Cowork","شغّله مرة وراجع","حوّله لمهمة مجدولة","راجع أول 5 تشغيلات بالكامل"]]};
const LC=(cat,f,fa,data,t,ta,en,ar)=>Object.assign(CM(t,ta,CC[cat].en,'','',CSTEPS[cat][0],CSTEPS[cat][1],en,ar),{data,field:T(f,fa),cat});
const LAB2=[
// AGENTS
LC('agent','Finance','المالية',['ar_aging'],'Collections agent','وكيل التحصيل',["Credit-control agent","Prioritise overdue customers and draft reminders","- ar_aging.csv attached\n- Tiers: >90 days escalate; 61–90 firm; 31–60 friendly\n- Never threaten legal action","Cut DSO from 92 to 70 days","- Ranked call list with amounts\n- One draft per customer in Arabic/English\n- Nothing sent","Table + drafts + 5-line summary for the credit manager."],["وكيل متابعة الائتمان","رتّب العملاء المتأخرين واكتب مسودات تذكير","- ar_aging.csv مرفق\n- الفئات: > 90 يوم تصعيد؛ 61–90 حازم؛ 31–60 ودّي\n- مفيش تهديد قانوني","نقلل DSO من 92 لـ 70 يوم","- قائمة اتصال مرتبة بالمبالغ\n- مسودة لكل عميل عربي/إنجليزي\n- مفيش إرسال","جدول + مسودات + ملخص 5 سطور لمدير الائتمان."]),
LC('agent','Sales','المبيعات',['crm_deals','crm_activities'],'Pipeline coach agent','وكيل تدريب الـ Pipeline',["Sales coach agent","Review each rep's open deals and coach next steps","- CRM deals and activities attached\n- Rule: no discount >15% without CFO","Forecast accuracy and win rate","- Per rep: 3 deals to push, 1 to drop, 1 coaching tip\n- Evidence from activities","Per-rep cards + manager summary."],["وكيل تدريب مبيعات","راجع صفقات كل مندوب المفتوحة واقترح الخطوات","- صفقات وأنشطة الـ CRM مرفقة\n- القاعدة: مفيش خصم > 15% من غير المدير المالي","دقة التوقع ونسبة الفوز","- لكل مندوب: 3 صفقات يدفعها، وحدة يسيبها، ونصيحة\n- أدلة من الأنشطة","كروت لكل مندوب + ملخص للمدير."]),
LC('agent','Procurement','المشتريات',['suppliers'],'Supplier due-diligence agent','وكيل فحص الموردين',["Procurement risk agent","Run due diligence on the shortlisted suppliers","- suppliers.csv attached; web search allowed; sanctions screening via approved provider only","Award without hidden risks","- Cited findings per supplier\n- Risk rating with reasons\n- Human approves","Due-diligence report + risk table."],["وكيل مخاطر المشتريات","افحص الموردين المرشحين","- suppliers.csv مرفق؛ البحث مسموح؛ فحص العقوبات عبر مزوّد معتمد بس","ترسية من غير مخاطر مستخبية","- نتايج بمصادر لكل مورد\n- تصنيف مخاطر بالأسباب\n- الإنسان يعتمد","تقرير الفحص + جدول المخاطر."]),
LC('agent','HR','الموارد البشرية',['employees'],'Retention agent','وكيل الاحتفاظ بالموظفين',["People analytics agent","Detect retention risk patterns and propose team-level actions","- employees.csv (anonymised)\n- No individual predictions shared; no protected attributes","Reduce turnover from 19% to 12%","- Drivers by department with evidence\n- 5 team actions with cost\n- Fairness check","Brief + action plan."],["وكيل تحليلات الأفراد","اكتشف أنماط مخاطر ترك العمل واقترح إجراءات للفرق","- employees.csv (مجهول الهوية)\n- مفيش توقعات فردية؛ ومفيش خصائص محمية","نقلل الترك من 19% لـ 12%","- الأسباب لكل إدارة بالأدلة\n- 5 إجراءات للفرق بالتكلفة\n- فحص عدالة","ملخص + خطة عمل."]),
LC('agent','Customer service','خدمة العملاء',['tickets'],'Support triage agent','وكيل فرز الدعم',["Support agent","Triage tickets, draft replies and escalate","- tickets.csv (Arabic and English)\n- Escalate refunds, complaints, legal","First response under 2 hours","- Category, urgency, sentiment\n- Draft in customer's language\n- Escalation list","Table + drafts (nothing sent)."],["وكيل دعم","افرز التذاكر واكتب ردود وصعّد","- tickets.csv (عربي وإنجليزي)\n- صعّد الاسترداد والشكاوى والقانوني","أول رد أقل من ساعتين","- الفئة والأولوية والمشاعر\n- مسودة بلغة العميل\n- قائمة التصعيد","جدول + مسودات (من غير إرسال)."]),
// ARTIFACTS
LC('artifacts','Finance','المالية',['bva'],'Budget vs actual dashboard','داشبورد الموازنة مقابل الفعلي',["Finance BI designer","Build an interactive budget-vs-actual dashboard","- bva.csv attached (EGP thousands)\n- Navy/gold, Arabic/English, RTL","Management reviews variances in one screen","- KPI cards, variance bars, RAG flags\n- Filter by line\n- Correct maths","Single-file HTML artifact."],["مصممة BI مالي","ابني داشبورد تفاعلي للموازنة مقابل الفعلي","- bva.csv مرفق (بالألف جنيه)\n- كحلي/دهبي، عربي/إنجليزي، RTL","الإدارة تراجع الانحرافات في شاشة واحدة","- كروت مؤشرات، أعمدة انحراف، ألوان الحالة\n- فلتر بالبند\n- حسابات صح","Artifact HTML واحد."]),
LC('artifacts','Sales','المبيعات',['commissions'],'Commission calculator','حاسبة العمولات',["Sales ops developer","Build a commission calculator reps can use","- commissions.csv attached; rate on collections; accelerator above quota","Transparency ends disputes","- Inputs editable\n- Formula shown\n- Matches the sample rows","HTML artifact + test table."],["مطوّر عمليات مبيعات","ابني حاسبة عمولات للمندوبين","- commissions.csv مرفق؛ النسبة على التحصيل؛ والمعجّل فوق الحصة","الشفافية بتنهي الخلافات","- المدخلات قابلة للتعديل\n- المعادلة ظاهرة\n- مطابقة للصفوف التجريبية","Artifact HTML + جدول اختبار."]),
LC('artifacts','Operations','العمليات',['inventory'],'Inventory reorder app','تطبيق إعادة طلب المخزون',["Inventory app builder","Build an app showing reorder points and dead stock","- inventory.csv attached; service level 95%","Purchasing acts in minutes","- Table with ROP and status colours\n- What-if lead time\n- CSV export","HTML artifact."],["باني تطبيقات مخزون","ابني تطبيق بيوري نقاط إعادة الطلب والراكد","- inventory.csv مرفق؛ مستوى خدمة 95%","المشتريات تتصرف في دقايق","- جدول بنقطة الطلب وألوان الحالة\n- ماذا لو مدة التوريد\n- تصدير CSV","Artifact HTML."]),
LC('artifacts','Project management','إدارة المشروعات',['project'],'Project Gantt tracker','متابع Gantt للمشروع',["PMO developer","Build an interactive Gantt-style tracker","- project.csv attached\n- Slip >5 days amber, >10 red","Sponsor sees status at a glance","- Bars by task with slip\n- Critical path highlight\n- Budget variance","HTML artifact."],["مطوّر مكتب المشروعات","ابني متابع تفاعلي بشكل Gantt","- project.csv مرفق\n- تأخير > 5 أيام أصفر، > 10 أحمر","الراعي يشوف الحالة بنظرة","- أعمدة لكل مهمة بالتأخير\n- تمييز المسار الحرج\n- انحراف الميزانية","Artifact HTML."]),
LC('artifacts','Trainer','المدرّب',['employees'],'Training quiz game','لعبة اختبار تدريبية',["Learning game designer","Build a 15-question quiz game on HR policy","- Use employees.csv only for realistic scenarios (anonymised)\n- Timer, streaks, feedback","Engaging compliance training","- Mobile-friendly\n- Explanation after each answer\n- Score summary","HTML artifact."],["مصمم ألعاب تعليمية","ابني لعبة اختبار 15 سؤال عن سياسات الموارد البشرية","- استخدم employees.csv بس لسيناريوهات واقعية (مجهولة)\n- مؤقت، سلاسل، شرح","تدريب امتثال ممتع","- مناسب للموبايل\n- شرح بعد كل إجابة\n- ملخص الدرجة","Artifact HTML."]),
// DESIGN
LC('design','Marketing','التسويق',['campaigns'],'Campaign results one-pager','صفحة نتايج الحملة',["Brand designer in Claude Design","Design a one-page campaign results summary","- campaigns.csv attached; brand system navy/gold/teal","Leadership reads it in one minute","- 4 big numbers, 1 chart, 3 insights\n- Arabic and English versions","PDF + PNG exports."],["مصممة براند في Claude Design","صمّم صفحة واحدة لملخص نتايج الحملة","- campaigns.csv مرفق؛ نظام البراند كحلي/دهبي/تركوازي","القيادة تقراها في دقيقة","- 4 أرقام كبيرة، رسم، 3 استنتاجات\n- نسخة عربي وإنجليزي","تصدير PDF + PNG."]),
LC('design','CEO','المدير التنفيذي',['kpis'],'Board KPI deck','عرض مؤشرات المجلس',["Presentation designer","Design a 6-slide board KPI deck","- kpis.csv attached","The board sees the story, not the spreadsheet","- Title = message on each slide\n- Native charts\n- Speaker notes","PPTX + PDF."],["مصممة عروض","صمّم عرض مؤشرات للمجلس 6 شرائح","- kpis.csv مرفق","المجلس يشوف القصة مش الجدول","- العنوان = الرسالة في كل شريحة\n- رسوم أصلية\n- ملاحظات المتحدث","PPTX + PDF."]),
LC('design','Content','المحتوى',['social'],'Carousel from best posts','كاروسيل من أحسن البوستات',["Social designer","Turn the 3 best-performing posts into a 7-slide carousel","- social.csv attached (pick by engagement)","More reach from proven ideas","- Hook slide, 5 value slides, CTA\n- Max 25 words per slide\n- RTL Arabic","Carousel PDF + PNGs."],["مصممة سوشيال","حوّل أحسن 3 بوستات لكاروسيل 7 شرائح","- social.csv مرفق (اختار حسب التفاعل)","وصول أكتر من أفكار مجرّبة","- شريحة Hook، 5 قيمة، دعوة\n- أقصى 25 كلمة للشريحة\n- عربي RTL","PDF كاروسيل + PNG."]),
LC('design','Product','المنتجات',['expenses'],'Expense app prototype','نموذج تطبيق المصاريف',["Product designer","Prototype a 5-screen expense app","- expenses.csv for realistic sample entries","Validate with users before coding","- Clickable flow\n- Accessible contrast\n- Hand-off notes for Claude Code","Prototype + hand-off."],["مصممة منتجات","اعملي نموذج تطبيق مصاريف 5 شاشات","- expenses.csv لبيانات واقعية","نختبر مع المستخدمين قبل الكود","- تدفق قابل للضغط\n- تباين مناسب\n- ملاحظات تسليم لـ Claude Code","النموذج + التسليم."]),
LC('design','HR','الموارد البشرية',['employees'],'Org chart & headcount poster','لوحة الهيكل وعدد الموظفين',["Information designer","Design a headcount-by-department poster","- employees.csv attached (counts only, no names)","Town-hall visual","- Clear hierarchy\n- Department colours\n- Print-ready A3","PDF A3."],["مصممة معلومات","صمّم بوستر عدد الموظفين حسب الإدارة","- employees.csv مرفق (أعداد بس من غير أسماء)","صورة لاجتماع الموظفين","- تسلسل واضح\n- ألوان للإدارات\n- جاهز للطباعة A3","PDF A3."]),
// PROJECTS
LC('project','Finance','المالية',['bva','ar_aging'],'Monthly FP&A project','مشروع FP&A الشهري',["FP&A analyst (Project instructions loaded)","Produce the monthly management commentary","- bva.csv and ar_aging.csv attached\n- Project holds chart of accounts and style guide","Consistent monthly reporting","- Variance drivers\n- Cash and collections view\n- House style","Commentary (300 words) + table."],["محلل FP&A (تعليمات الـ Project محمّلة)","طلّع تعليق الإدارة الشهري","- bva.csv و ar_aging.csv مرفقين\n- الـ Project فيه دليل الحسابات ودليل الأسلوب","تقارير شهرية ثابتة","- أسباب الانحرافات\n- النقدية والتحصيل\n- أسلوب الشركة","تعليق 300 كلمة + جدول."]),
LC('project','Banking','البنوك',['credit_fin'],'Credit desk project','مشروع مكتب الائتمان',["Credit analyst (Project: bank credit policy)","Analyse the borrower and draft the memo","- credit_fin.csv attached","Committee-ready memo","- Ratios and covenants\n- Stress test\n- Policy references","Memo + appendix tables."],["محلل ائتمان (Project: سياسة الائتمان)","حلّل المقترض واكتب المذكرة","- credit_fin.csv مرفق","مذكرة جاهزة للجنة","- النسب والتعهدات\n- اختبار الضغط\n- إحالات للسياسة","مذكرة + جداول ملحق."]),
LC('project','Legal','القانوني',['contracts'],'Contracts desk project','مشروع مكتب العقود',["Legal ops analyst (Project: playbook)","Review renewals against the playbook","- contracts.csv attached","No missed notice periods","- Deadlines\n- Renegotiation points\n- Owner actions","Table + email drafts."],["محلل عمليات قانونية (Project: دليل التفاوض)","راجع التجديدات على دليل التفاوض","- contracts.csv مرفق","مفيش مواعيد إخطار فايتة","- المواعيد\n- نقاط إعادة التفاوض\n- إجراءات المسؤولين","جدول + مسودات إيميل."]),
LC('project','Trade finance','التمويل التجاري',['lc'],'LC desk project','مشروع مكتب الاعتمادات',["LC examiner (Project: UCP 600/ISBP notes)","Pre-check the documents","- lc.csv attached","Clean presentation","- Field-by-field comparison\n- Article references\n- Fix list","Discrepancy table + bilingual notice."],["فاحص اعتمادات (Project: ملاحظات UCP 600/ISBP)","افحص المستندات مبدئياً","- lc.csv مرفق","تقديم نضيف","- مقارنة حقل بحقل\n- المواد\n- قائمة تصليح","جدول المخالفات + إخطار ثنائي اللغة."]),
LC('project','Academic','الأكاديمي',['kpis'],'Thesis data chapter project','مشروع فصل البيانات في الرسالة',["Doctoral research assistant (Project: proposal + APA guide)","Write the descriptive-results section from the dataset","- kpis.csv as sample company data","Supervisor review","- Tables with interpretation\n- No causal claims without tests\n- APA formatting","Results section draft + tables."],["مساعد بحث دكتوراه (Project: المقترح + دليل APA)","اكتب جزء النتايج الوصفية من البيانات","- kpis.csv كبيانات شركة تجريبية","مراجعة المشرف","- جداول بالتفسير\n- مفيش ادعاءات سببية من غير اختبار\n- تنسيق APA","مسودة النتايج + جداول."]),
// CONNECTORS
LC('connectors','CFO','المدير المالي',['ar_aging'],'Overdue vs open deals (ERP + CRM)','المتأخر مقابل الصفقات (ERP + CRM)',["CFO analyst with ERP (MCP) and CRM connectors","Find customers >90 days overdue who have open deals","- Use ar_aging.csv as test data if connectors are not set up\n- Read-only","Align sales and finance","- Joined list with amounts\n- Proposed action per customer\n- No action executed","Table + 5 recommendations."],["محلل المدير المالي بـ Connectors للـ ERP (MCP) والـ CRM","لاقي العملاء المتأخرين > 90 يوم وعندهم صفقات مفتوحة","- استخدم ar_aging.csv كبيانات اختبار لو الـ Connectors مش متوصلة\n- قراءة بس","توافق المبيعات والمالية","- قائمة مدموجة بالمبالغ\n- إجراء مقترح لكل عميل\n- من غير تنفيذ","جدول + 5 توصيات."]),
LC('connectors','Executive assistant','المساعد التنفيذي',[],'Tomorrow\'s meeting briefs','ملخصات اجتماعات بكرة',["Executive assistant with Gmail, Calendar and Drive","Prepare a brief for each of tomorrow's meetings","- Calendar: tomorrow; Gmail: last 30 days with attendees; Drive: related files","Walk in prepared","- Purpose, history, open items, documents, 3 questions\n- Read-only","One document ordered by time."],["مساعد تنفيذي بـ Gmail و Calendar و Drive","جهّز ملخص لكل اجتماع بكرة","- الكالندر: بكرة؛ Gmail: آخر 30 يوم مع الحضور؛ Drive: الملفات المرتبطة","تدخل جاهز","- الهدف، التاريخ، المفتوح، المستندات، 3 أسئلة\n- قراءة بس","مستند واحد مرتب بالوقت."]),
LC('connectors','Sales','المبيعات',['crm_deals'],'HubSpot pipeline hygiene','نظافة الـ Pipeline في HubSpot',["Sales ops analyst with the HubSpot connector","Audit the pipeline","- Use crm_deals.csv as test data","Clean data for the forecast","- Stale deals, past close dates, missing amounts\n- Fix list per rep","Table + messages to reps (drafts)."],["محلل عمليات مبيعات بـ HubSpot connector","راجع الـ Pipeline","- استخدم crm_deals.csv كبيانات اختبار","بيانات نضيفة للتوقع","- صفقات راكدة، تواريخ فاتت، مبالغ ناقصة\n- قائمة إصلاح لكل مندوب","جدول + رسايل للمندوبين (مسودات)."]),
LC('connectors','Marketing','التسويق',['campaigns'],'Canva campaign assets','مواد الحملة في Canva',["Marketing lead with the Canva connector","Create campaign assets from the results","- campaigns.csv attached; brand kit in Canva","Fast, on-brand assets","- 3 social posts + 1 banner\n- Brand kit applied\n- Drafts in Canva","Canva designs + summary."],["مسؤول تسويق بـ Canva connector","اعمل مواد الحملة من النتايج","- campaigns.csv مرفق؛ والبراند كيت في Canva","مواد سريعة وعلى البراند","- 3 بوستات + بانر\n- البراند كيت متطبق\n- مسودات في Canva","تصاميم Canva + ملخص."]),
LC('connectors','Operations','العمليات',['project'],'Status from the task tracker','الحالة من متابع المهام',["PMO analyst with the project-tracker connector","Produce the weekly status from live tasks","- Use project.csv as test data","Sponsor update","- RAG status\n- Slips and owners\n- Decisions needed","One-page status."],["محلل مكتب المشروعات بـ Connector متابع المهام","طلّع الحالة الأسبوعية من المهام الحية","- استخدم project.csv كبيانات اختبار","تحديث للراعي","- حالة الألوان\n- التأخيرات والمسؤولين\n- القرارات المطلوبة","حالة صفحة."]),
// PLUGINS
LC('plugin','Accounting','المحاسبة',['bank_gl'],'/reconciliation run','تشغيل /reconciliation',["Accountant using the finance plugin","Run /reconciliation for the bank account","- bank_gl.csv attached","Signed recon at month-end","- Matched, bank-only, GL-only\n- Amount differences\n- Proposed entries","Reconciliation statement."],["محاسب بيستخدم Plugin المالية","شغّل /reconciliation لحساب البنك","- bank_gl.csv مرفق","مطابقة موقعة آخر الشهر","- المتطابق، البنك بس، الأستاذ بس\n- فروق المبالغ\n- قيود مقترحة","مذكرة التسوية."]),
LC('plugin','FP&A','FP&A',['bva'],'/variance-analysis run','تشغيل /variance-analysis',["FP&A analyst using the finance plugin","Run /variance-analysis on September","- bva.csv attached; materiality 5% and EGP 200K","Board commentary","- Drivers and waterfall\n- RAG\n- Narrative","Analysis + commentary."],["محلل FP&A بيستخدم Plugin المالية","شغّل /variance-analysis على سبتمبر","- bva.csv مرفق؛ الأهمية 5% و200 ألف","تعليق المجلس","- الأسباب والشلال\n- الألوان\n- التعليق","التحليل + التعليق."]),
LC('plugin','Sales','المبيعات',['crm_deals'],'sales:pipeline-review','sales:pipeline-review',["Sales manager using the sales plugin","Run a pipeline review","- crm_deals.csv attached","Weekly focus","- Coverage, ageing, at-risk deals\n- Top actions","Review + action list."],["مدير مبيعات بيستخدم Plugin المبيعات","شغّل مراجعة الـ Pipeline","- crm_deals.csv مرفق","تركيز الأسبوع","- التغطية، العمر، الصفقات في خطر\n- أهم الإجراءات","المراجعة + قائمة إجراءات."]),
LC('plugin','HR','الموارد البشرية',['employees'],'human-resources:comp-analysis','human-resources:comp-analysis',["Compensation analyst using the HR plugin","Check pay bands and outliers","- employees.csv attached","Fair pay","- Bands by grade\n- Outliers adjusted for tenure and rating\n- Budget to fix","Table + memo."],["محلل تعويضات بيستخدم Plugin الموارد البشرية","افحص نطاقات الأجور والحالات الشاذة","- employees.csv مرفق","أجور عادلة","- النطاقات حسب الدرجة\n- الشاذ بعد مراعاة المدة والتقييم\n- ميزانية التصحيح","جدول + مذكرة."]),
LC('plugin','Marketing','التسويق',['social'],'marketing:performance-report','marketing:performance-report',["Marketing manager using the marketing plugin","Produce the monthly performance report","- social.csv attached","Next month's priorities","- KPIs and trends\n- Wins and misses\n- 5 optimisations","Report + exec summary."],["مدير تسويق بيستخدم Plugin التسويق","طلّع تقرير الأداء الشهري","- social.csv مرفق","أولويات الشهر الجاي","- المؤشرات والاتجاهات\n- النجاحات والإخفاقات\n- 5 تحسينات","تقرير + ملخص تنفيذي."]),
// SKILLS
LC('skills','Finance','المالية',['bva'],'Skill: Arabic finance report','Skill: تقرير مالي بالعربي',["Skill designer","Create a 'finance-report-arabic' skill and test it on the data","- bva.csv attached\n- Rules: EGP thousands, Arabic summary first, flag >10%","Same report quality every month","- SKILL.md with Use when / Do NOT use\n- Tested output on the data","SKILL.md + sample report."],["مصممة Skills","اعمل Skill 'finance-report-arabic' واختبرها على البيانات","- bva.csv مرفق\n- القواعد: بالألف جنيه، الملخص العربي الأول، تعليم > 10%","نفس جودة التقرير كل شهر","- SKILL.md باستخدمها لما / متستخدمهاش في\n- ناتج متجرب على البيانات","SKILL.md + تقرير عينة."]),
LC('skills','Trade finance','التمويل التجاري',['lc'],'Skill: LC document checker','Skill: فاحص مستندات الاعتماد',["Skill designer for trade finance","Create 'lc-doc-checker' and run it on the sample","- lc.csv attached","Consistent examinations","- Steps per UCP 600 / ISBP\n- Discrepancy table format\n- 'for examiner review' rule","SKILL.md + test result."],["مصممة Skills للتمويل التجاري","اعمل 'lc-doc-checker' وشغّلها على العينة","- lc.csv مرفق","فحص ثابت","- خطوات حسب UCP 600 / ISBP\n- شكل جدول المخالفات\n- قاعدة 'لمراجعة الفاحص'","SKILL.md + نتيجة الاختبار."]),
LC('skills','Audit','المراجعة',['expenses'],'Skill: expense audit','Skill: مراجعة المصروفات',["Skill designer for internal audit","Create an 'expense-audit' skill","- expenses.csv attached; policy limits in the prompt","Repeatable T&E testing","- Duplicate, weekend, receipt, outlier checks\n- Findings table","SKILL.md + findings on sample."],["مصممة Skills للمراجعة الداخلية","اعمل Skill 'expense-audit'","- expenses.csv مرفق؛ حدود السياسة في البرومبت","اختبار مصروفات متكرر","- فحص التكرار والإجازات والإيصالات والشاذ\n- جدول ملاحظات","SKILL.md + ملاحظات على العينة."]),
LC('skills','Sales','المبيعات',['pricing'],'Skill: discount guardrails','Skill: حدود الخصم',["Skill designer for sales","Create a 'discount-guardrails' skill","- pricing.csv attached","Stop margin leakage","- Approval levels\n- Win-rate evidence\n- Reply template for reps","SKILL.md + analysis."],["مصممة Skills للمبيعات","اعمل Skill 'discount-guardrails'","- pricing.csv مرفق","نوقف تسرب الهامش","- مستويات الموافقة\n- أدلة نسبة الفوز\n- قالب رد للمندوبين","SKILL.md + تحليل."]),
LC('skills','Content','المحتوى',['social'],'Skill: brand voice','Skill: صوت البراند',["Editorial skill designer","Create a 'brand-voice' skill from the best posts","- social.csv attached (top posts by engagement)","Every post sounds like the brand","- Tone, structure, hooks, CTAs\n- Do/don't list\n- 2 rewritten examples","SKILL.md + examples."],["مصممة Skills تحريرية","اعمل Skill 'brand-voice' من أحسن البوستات","- social.csv مرفق (أحسن بوستات بالتفاعل)","كل بوست يبان من البراند","- النبرة والهيكل والـ Hooks والدعوات\n- اعمل/متعملش\n- مثالين متعاد كتابتهم","SKILL.md + أمثلة."]),
// AUTOMATION
LC('automation','Treasury','الخزينة',['ar_aging','ap_aging'],'Daily cash position (scheduled)','المركز النقدي اليومي (مجدول)',["Scheduled treasury task (weekdays 08:30)","Produce the daily cash position","- ar_aging.csv and ap_aging.csv as test inputs; opening cash EGP 6M","CFO approves payments by 10:00","- Inflows/outflows today and tomorrow\n- Shortfall alert","xlsx + 5-line draft email."],["مهمة خزينة مجدولة (أيام الشغل 8:30)","طلّع المركز النقدي اليومي","- ar_aging.csv و ap_aging.csv كمدخلات اختبار؛ النقدية الافتتاحية 6 مليون","المدير المالي بيوافق على المدفوعات قبل 10","- المقبوضات والمدفوعات النهارده وبكرة\n- تنبيه العجز","xlsx + مسودة إيميل 5 سطور."]),
LC('automation','Accounting','المحاسبة',['expenses'],'Weekly expense exceptions','استثناءات المصروفات الأسبوعية',["Scheduled audit task (Mondays)","Flag new expense exceptions","- expenses.csv as test input","Catch issues early","- Duplicates, missing receipts, over-limit\n- Owner per item","Exceptions.xlsx + draft emails."],["مهمة مراجعة مجدولة (كل إتنين)","علّم على استثناءات المصروفات الجديدة","- expenses.csv كمدخل اختبار","نمسك المشاكل بدري","- التكرار، الإيصالات الناقصة، تجاوز الحد\n- مسؤول لكل بند","Exceptions.xlsx + مسودات إيميل."]),
LC('automation','Sales','المبيعات',['crm_deals'],'Friday pipeline digest','ملخص الـ Pipeline يوم الجمعة',["Scheduled sales-ops task (Fridays)","Send the weekly pipeline digest","- crm_deals.csv as test input","Weekly alignment","- Moves, slips, wins, risks\n- Next week's focus","Digest draft for Slack/email."],["مهمة عمليات مبيعات مجدولة (الجمعة)","ابعت ملخص الـ Pipeline الأسبوعي","- crm_deals.csv كمدخل اختبار","توافق أسبوعي","- التحركات، التأخيرات، المكاسب، المخاطر\n- تركيز الأسبوع الجاي","مسودة ملخص لـ Slack/الإيميل."]),
LC('automation','Compliance','الالتزام',['contracts'],'Contract renewal alerts','تنبيهات تجديد العقود',["Scheduled legal-ops task (Mondays)","Alert owners about upcoming notice deadlines","- contracts.csv as test input; today 2026-10-01","No missed renewals","- Contracts within 60 days of notice\n- Owner and action","Alert list + drafts."],["مهمة عمليات قانونية مجدولة (الإتنين)","نبّه المسؤولين بمواعيد الإخطار الجاية","- contracts.csv كمدخل اختبار؛ النهارده 2026-10-01","مفيش تجديدات فايتة","- العقود خلال 60 يوم من الإخطار\n- المسؤول والإجراء","قائمة التنبيهات + مسودات."]),
LC('automation','Content','المحتوى',['social'],'Weekly content batch','دفعة المحتوى الأسبوعية',["Scheduled content task (Thursdays)","Draft next week's posts from performance","- social.csv as test input; brand-voice skill","Consistent posting","- 5 drafts\n- 2 hook variants each\n- Nothing published","Drafts folder + approval summary."],["مهمة محتوى مجدولة (الخميس)","اكتب بوستات الأسبوع الجاي من الأداء","- social.csv كمدخل اختبار؛ Skill صوت البراند","نشر منتظم","- 5 مسودات\n- نسختين Hook لكل واحد\n- مفيش نشر","فولدر مسودات + ملخص للموافقة."])
];
LAB.forEach(c=>{c.cat=c.cat||'project'});LAB.push(...LAB2);
