let LF={field:'all',cat:'all',q:'',data:false};
function vLab(){const ar=LANG==='ar';if(location.hash.slice(1).split('/')[0]==='studio'){labTab='studio';history.replaceState(null,'','#lab')}crumb(L(UI.lab));
const fields=[...new Set(LAB.map(c=>c.field.en))].sort();const catCount=k=>LAB.filter(c=>c.cat===k).length;
let h=`<section class="cdash labhero"><div class="cd-l"><div class="sig">${ar?'معمل د. سارة سالم':'Dr. Sara Salem’s lab'}</div><h1>${ar?'معمل البرومبت الماستر والاستوديو':'Master Prompt Lab & Studio'}</h1><p>${ar?`${LAB.length} حالة كاملة ببيانات اختبار، ${PROMPTS.length} برومبت في المكتبة، استوديو تبني وتختبر فيه، وحزم برومبتات تشاركها مع فريقك.`:`${LAB.length} complete cases with test data, ${PROMPTS.length} prompts in the library, a studio to build and test, and prompt packs to share with your team.`}</p></div><div class="cd-r"><div class="cd-kpi"><div><b>${LAB.length}</b>${ar?'حالة':'cases'}</div><div><b>${Object.keys(CC).length}</b>${ar?'فئات Claude':'Claude categories'}</div><div><b>${fields.length}</b>${ar?'مجال':'fields'}</div><div><b>${Object.keys(DATA).length}</b>${ar?'ملف بيانات':'datasets'}</div></div></div></section>`;
h+=`<div class="tabs big"><button class="tab ${labTab==='cases'?'on':''}" data-labtab="cases">⚗ ${ar?'الحالات + البيانات':'Cases + data'}</button><button class="tab ${labTab==='library'?'on':''}" data-labtab="library">✎ ${L(UX3.lib)}</button><button class="tab ${labTab==='studio'?'on':''}" data-labtab="studio">🎛 ${L(UX3.studio)}</button><button class="tab ${labTab==='packs'?'on':''}" data-labtab="packs">📦 ${L(UX6.packs)}</button></div>`;
if(labTab==='library')return h+vLibrary();
if(labTab==='studio')return h+vStudio().replace(/^<h1>[\s\S]*?<\/h1>/,'');
if(labTab==='packs')return h+vPacks().replace(/^<h1>[\s\S]*?<\/h1>/,'');
h+=`<div class="lfil"><input class="search" id="lfq" value="${esc(LF.q)}" placeholder="${ar?'ابحث في الحالات…':'Search cases…'}"><select id="lff"><option value="all">${ar?'كل المجالات':'All fields'}</option>${fields.map(f=>{const c=LAB.find(x=>x.field.en===f);return `<option value="${esc(f)}" ${LF.field===f?'selected':''}>${L(c.field)}</option>`}).join('')}</select><select id="lfc"><option value="all">${ar?'كل فئات Claude':'All Claude categories'}</option>${Object.keys(CC).map(k=>`<option value="${k}" ${LF.cat===k?'selected':''}>${L(CC[k])} (${catCount(k)})</option>`).join('')}</select><label class="opt"><input type="checkbox" id="lfd" ${LF.data?'checked':''}> 🧪 ${ar?'ببيانات':'With data'}</label></div>`;
h+=`<div class="catrow">${[['all',T('All','الكل'),'✦']].concat(Object.keys(CC).map(k=>[k,CC[k],{agent:'🤖',artifacts:'▣',design:'✎',project:'🗂',connectors:'🔌',plugin:'🧩',skills:'✦',automation:'⏱'}[k]])).map(x=>`<button class="catb ${LF.cat===x[0]?'on':''}" data-lfc="${x[0]}"><span>${x[2]}</span>${L(x[1])}<em>${x[0]==='all'?LAB.length:catCount(x[0])}</em></button>`).join('')}</div>`;
const q=LF.q.toLowerCase();const list=LAB.filter(c=>(LF.field==='all'||c.field.en===LF.field)&&(LF.cat==='all'||c.cat===LF.cat)&&(!LF.data||(c.data||[]).length)&&(!q||(L(c.t)+' '+c.p.en+' '+c.p.ar+' '+L(c.field)).toLowerCase().includes(q)));
h+=`<p class="note">${list.length} ${ar?'حالة':'cases'}</p>`+(list.length?list.map(c=>caseCard(c,`${L(CC[c.cat])} · ${L(c.field)}`)).join(''):`<div class="empty">${ar?'مفيش حالات بالفلاتر دي — جرّب فئة أو مجال تاني.':'No cases match these filters — try another category or field.'}</div>`);
h+=`<p style="margin-top:16px"><button class="dlbtn" data-exp="mp_ar">📕 ${ar?'كتاب البرومبتات الماستر PDF':'Master prompt book PDF'}</button> <button class="dlbtn" data-exp="data_zip">🧪 ${ar?'كل البيانات التجريبية ZIP':'All dummy data ZIP'}</button></p>`;return h}
document.addEventListener('input',e=>{if(e.target.id==='lfq'){LF.q=e.target.value;const pos=e.target.selectionStart;render();const el=document.getElementById('lfq');if(el){el.focus();el.setSelectionRange(pos,pos)}}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='lff'){LF.field=t.value;render()}if(t.id==='lfc'){LF.cat=t.value;render()}if(t.id==='lfd'){LF.data=t.checked;render()}});
document.addEventListener('click',e=>{const x=e.target.closest('[data-lfc]');if(x){LF.cat=x.dataset.lfc;render()}});
