function dataBox(keys){if(!keys||!keys.length)return '';return `<div class="databox"><h3>🧪 ${L(UI.testdata)}</h3>`+keys.filter(k=>DATA[k]).map(k=>{const d=DATA[k];const rows=d.csv.split('\n');const head=rows[0].split(',');const i=PSTORE.push(d.csv)-1;
return `<div class="dset"><div class="dhead"><b>${LANG==='ar'?d.ar:d.en}</b> <span class="k">${k}.csv · ${rows.length-1} ${LANG==='ar'?'صف':'rows'}</span><span style="flex:1"></span><button class="copy" data-i="${i}">${L(UI.copy)}</button> <button class="dlbtn" data-csv="${k}">${L(UI.dlcsv)}</button></div><div class="tablewrap"><table dir="ltr"><tr>${head.map(h=>`<th>${esc(h)}</th>`).join('')}</tr>${rows.slice(1,PRINT?rows.length:7).map(r=>`<tr>${r.split(',').map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</table></div>${!PRINT&&rows.length>7?`<div class="k" style="font-size:12px;color:var(--ink3)">+${rows.length-7} ${LANG==='ar'?'صفوف تانية في الملف':'more rows in the file'}</div>`:''}</div>`}).join('')+`</div>`}
let labF='all';
function vLabOld(){crumb(L(UI.lab));const ar0=LANG==='ar';const tabsH=`<div class="tabs big"><button class="tab ${labTab==='cases'?'on':''}" data-labtab="cases">⚗ ${L(UX3.labcases)} (${LAB.length})</button><button class="tab ${labTab==='library'?'on':''}" data-labtab="library">✎ ${L(UX3.lib)} (${PROMPTS.length})</button><button class="tab" data-go="studio">🎛 ${L(UX3.studio)}</button></div>`;if(labTab==='library')return `<h1>⚗ ${L(UI.lab)}</h1>`+tabsH+vLibrary();const fields=[...new Set(LAB.map(c=>c.field.en))];const list=LAB.filter(c=>labF==='all'||c.field.en===labF);
let h=`<h1>⚗ ${L(UI.lab)}</h1><p class="lede">${LANG==='ar'?`${LAB.length} حالة كاملة: خطوات، برومبت ماستر، وبيانات تجريبية جاهزة تجرّب بيها دلوقتي. انسخ البيانات أو نزّلها CSV وارفعها مع البرومبت.`:`${LAB.length} complete cases: steps, a master prompt and ready dummy data to try now. Copy the data or download the CSV and attach it with the prompt.`}</p>`;
h+=tabsH;h+=`<div class="chips"><button class="chip ${labF==='all'?'on':''}" data-labf="all">${L(UI.all)}</button>${fields.map(f=>{const c=LAB.find(x=>x.field.en===f);return `<button class="chip ${labF===f?'on':''}" data-labf="${f}">${L(c.field)}</button>`}).join('')}</div>`;
h+=list.map(c=>caseCard(c,L(c.field))).join('');h+=`<p style="margin-top:16px"><button class="dlbtn" data-exp="mp_${LANG}">📕 ${LANG==='ar'?'كتاب البرومبتات الماستر PDF':'Master prompt book PDF'}</button> <button class="dlbtn" data-exp="data_zip">🧪 ${LANG==='ar'?'كل البيانات التجريبية ZIP':'All dummy data ZIP'}</button></p>`;return h}
function vPrintMP(){let h=`<section class="hero" style="margin-bottom:24px"><div class="sig">${LANG==='ar'?'د. سارة سالم':'Dr. Sara Salem'}</div><h1>${LANG==='ar'?'كتاب البرومبتات الماستر':'The Master Prompt Book'}</h1><p class="lede">Claude Mastery · ${LINKEDIN}</p><div class="qr" style="width:110px">${QR_SVG}</div></section>`;
h+=`<h1>⚗ ${L(UI.lab)}</h1>`+LAB.map(c=>caseCard(c,L(c.field))).join('');
h+=`<div class="pb"></div><h1>${LANG==='ar'?'كل البرومبتات الماستر في المنهج':'All master prompts in the curriculum'}</h1>`;let last='';PROMPTS.filter(p=>p.dom!=='lab').forEach(p=>{const s=L(p.src);if(s!==last){last=s;h+=`<h2>${s}</h2>`}h+=promptBox(p)});
h+=`<div class="pb"></div>`+vWords();return h}
