// ===== LAB HUB: cases + master prompt library =====
let labTab='cases',libQ='',libDom='all',libOpen={};
const LIBSTEPS=T(["Open a new chat (or the right Project)","Attach your files — or the test data below","Paste the master prompt and fill the [brackets]","Answer Claude's clarifying questions","Review the output against the stop conditions","Save it, or turn it into a Skill if it repeats"],["افتح محادثة جديدة (أو الـ Project المناسب)","ارفع ملفاتك — أو بيانات الاختبار اللي تحت","الصق البرومبت الماستر واملا [الأقواس]","جاوب على أسئلة Claude التوضيحية","راجع الناتج على شروط التوقف","احفظه أو حوّله Skill لو بيتكرر"]);
function toMaster(p){const isM=/<role>/.test(p.p.en);if(isM)return p.p;const src=p.src.en.replace(/^Module \d+ · /,'');
return T(MPen(`Expert practitioner for: ${src}`,p.t.en,`- Original instruction:\n${p.p.en.split('\n').map(l=>'  '+l).join('\n')}\n- Files/data: [attach or paste]\n- Period, currency, audience: [..]`,'[The decision or outcome this supports]','- Every part of the original instruction answered\n- Numbers traced to sources; assumptions labelled','[Format, language, length]'),MPar(`خبير ممارس في: ${p.src.ar.replace(/^موديول \d+ · /,'')}`,p.t.ar,`- التعليمات الأصلية:\n${p.p.ar.split('\n').map(l=>'  '+l).join('\n')}\n- الملفات/البيانات: [ارفع أو الصق]\n- الفترة والعملة والجمهور: [..]`,'[القرار أو النتيجة اللي بيدعمها]','- كل جزء من التعليمات الأصلية متجاوب\n- الأرقام ليها مصادر والافتراضات متعلّمة','[الشكل، اللغة، الطول]'))}
function libData(p){if(p.dom==='lab'){const c=LAB.find(x=>x.t.en===p.t.en);return c?c.data:null}return DOMDATA[p.dom]||null}
function libItem(p,i){const ar=LANG==='ar';const tab=libOpen[i]||'master';const m=toMaster(p);const data=libData(p);
const tabs=[['master',ar?'البرومبت الماستر':'Master prompt'],['orig',ar?'الأصلي':'Original'],['steps',ar?'الخطوات':'Steps'],['data',ar?'بيانات تجريبية':'Test data']];
let body='';if(tab==='master')body=promptBox({t:T('Master prompt','البرومبت الماستر'),p:m});else if(tab==='orig')body=promptBox(p);else if(tab==='steps')body=`<ol class="steps">${L(LIBSTEPS).map(s=>`<li>${s}</li>`).join('')}</ol>`;else body=data&&data.length?dataBox(data):`<div class="empty">${ar?'المجال ده مالوش بيانات جاهزة — استخدم ملفاتك.':'No ready dataset for this field — use your own files.'}</div>`;
return `<details class="case libi" ${libOpen[i]?'open':''} data-libi="${i}"><summary><div class="meta">${L(p.src)}${/<role>/.test(p.p.en)?' · ★ master':''}${data&&data.length?' · 🧪':''}</div><h3>${L(p.t)}</h3></summary><div class="tabs">${tabs.map(t=>`<button class="tab ${tab===t[0]?'on':''}" data-libtab="${i}:${t[0]}">${t[1]}</button>`).join('')}</div>${body}</details>`}
function vLibrary(){const ar=LANG==='ar';const doms=[['all',UI.all],['course',UI.course],['lab',T('Lab','المعمل')],['agentic',T('Agentic','الوكلاء')],['integration',T('API & MCP','الـ API و MCP')],['excel',T('Excel','Excel')],['az',T('A–Z','A–Z')],['work',T('My work','أعمالي')],...CASES.map(c=>[c.k,c.t])];
const q=libQ.toLowerCase();const list=PROMPTS.map((p,i)=>[p,i]).filter(([p])=>(libDom==='all'||p.dom===libDom)&&(!q||(L(p.t)+' '+L(p.p)+' '+L(p.src)).toLowerCase().includes(q)));
return `<div class="cfil" style="grid-template-columns:2fr 1fr"><input class="search" id="libq" value="${esc(libQ)}" placeholder="${ar?'ابحث في كل البرومبتات…':'Search all prompts…'}"><select id="libdom">${doms.map(d=>`<option value="${d[0]}" ${libDom===d[0]?'selected':''}>${L(d[1])}</option>`).join('')}</select></div><p class="note">${list.length} ${ar?'برومبت — كل واحد فيه تبويب البرومبت الماستر والأصلي والخطوات والبيانات.':'prompts — each with Master, Original, Steps and Test data tabs.'}</p>`+list.slice(0,80).map(([p,i])=>libItem(p,i)).join('')+(list.length>80?`<p class="note">${ar?'اعرض أول 80 — ضيّق البحث.':'Showing the first 80 — narrow your search.'}</p>`:'')}
// ===== MODULE EXPORTS (PDF / PPT / ZIP) =====
async function svgPng(svg){const url='data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(svg.replace(/width="[^"]*"/,'width="400"').replace(/height="[^"]*"/,'height="400"'))));const img=new Image();await new Promise((r,j)=>{img.onload=r;img.onerror=j;img.src=url});const c=document.createElement('canvas');c.width=c.height=400;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,400,400);x.drawImage(img,0,0,400,400);return 'image/png;base64,'+c.toDataURL('image/png').split(',')[1]}
async function loadScript(src,test){if(test())return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
function moduleHTML(n){const d=DAYS.find(x=>x.n==n);const ar=LANG==='ar';const keep=PRINT;PRINT=true;
let h=`<div class="exdoc" dir="${ar?'rtl':'ltr'}"><div class="exhead"><div><div class="sig">${ar?'د. سارة سالم':'Dr. Sara Salem'}</div><h1>${L(UI.day)} ${d.n} · ${L(d.t)}</h1><p>${L(d.sub)}</p></div><div class="qr" style="width:90px">${QR_PLATFORM}</div></div>`;
d.units.forEach(u=>{h+=`<h2>${u.id} · ${L(u.t)}</h2>${CEO[u.id]?`<div class="ceobox">👔 ${L(CEO[u.id])}</div>`:''}<div class="prose">${L(u.body)}</div>`;const st=L(u.steps)||[];if(st.length)h+=`<h3>${L(UI.steps)}</h3><ol class="steps">${st.map(x=>`<li>${x}</li>`).join('')}</ol>`;(u.cases||[]).forEach(c=>h+=`<div class="case"><b>${L(c.t)}</b><div>${L(c.d)}</div></div>`);(u.prompts||[]).forEach(p=>h+=`<div class="prompt"><div class="ph"><h3>${L(p.t)}</h3></div><pre dir="auto">${esc(L(p.p))}</pre></div>`)});
PRINT=keep;return h+`<p class="note">Claude Mastery · ${LINKEDIN}</p></div>`}
async function exportModule(n,fmt,btn){const ar=LANG==='ar';const old=btn.textContent;btn.disabled=true;btn.textContent=ar?'جاري…':'Working…';
try{const d=DAYS.find(x=>x.n==n);const base=`Claude-Mastery-Module-${n}-${LANG.toUpperCase()}`;
if(fmt==='pdf'){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js',()=>window.html2canvas);await loadScript('https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js',()=>window.html2pdf);
const fr=document.createElement('iframe');fr.style.cssText='position:absolute;left:-12000px;top:0;width:794px;height:1200px;border:0';document.body.appendChild(fr);
const css=document.querySelector('style').textContent;fr.srcdoc=`<!doctype html><html lang="${LANG}" dir="${ar?'rtl':'ltr'}" data-theme="light"><head><meta charset="utf-8"><link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@300;400;500;600;700&family=Amiri:wght@700&display=swap" rel="stylesheet"><style>${css} html,body{background:#fff;height:auto;overflow:visible;margin:0}.exdoc{padding:24px 28px}</style></head><body>${moduleHTML(n)}</body></html>`;
await new Promise(r=>fr.onload=r);try{await fr.contentDocument.fonts.ready}catch(e){}await new Promise(r=>setTimeout(r,400));const body=fr.contentDocument.body;fr.style.height=body.scrollHeight+'px';
const canvas=await html2canvas(body,{scale:2,backgroundColor:'#ffffff',foreignObjectRendering:true,windowWidth:794,width:794,height:body.scrollHeight});fr.remove();
const blob=await html2pdf().set({margin:[8,0,10,0],image:{type:'jpeg',quality:0.9},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}}).from(canvas,'canvas').outputPdf('blob');await saveFile(base+'.pdf',blob)}
else if(fmt==='ppt'){await loadScript('https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.bundle.js',()=>window.PptxGenJS);const pres=new PptxGenJS();pres.layout='LAYOUT_WIDE';pres.rtlMode=ar;const NAVY='13284B',GOLD='C9A227',INK='1E293B';const qr=await svgPng(QR_PLATFORM);const al=ar?'right':'left';
let s=pres.addSlide();s.background={color:NAVY};s.addText(`${L(UI.day)} ${d.n}`,{x:0.6,y:0.8,w:8,h:0.6,fontSize:20,color:GOLD,fontFace:'Arial',align:al,rtlMode:ar});s.addText(L(d.t),{x:0.6,y:1.5,w:9,h:1.6,fontSize:40,bold:true,color:'FFFFFF',fontFace:'Arial',align:al,rtlMode:ar});s.addText(L(d.sub),{x:0.6,y:3.2,w:9,h:1,fontSize:18,color:'C7D1E2',fontFace:'Arial',align:al,rtlMode:ar});s.addText(ar?'د. سارة سالم — صانعة المحتوى والمدرّبة':'Dr. Sara Salem — Creator & instructor',{x:0.6,y:5.6,w:8,h:0.6,fontSize:16,color:'FFFFFF',fontFace:'Arial',align:al,rtlMode:ar});s.addImage({data:qr,x:10.8,y:4.8,w:1.8,h:1.8});
d.units.forEach(u=>{let a=pres.addSlide();a.background={color:'F4F6FA'};a.addText(`${u.id} · ${L(u.t)}`,{x:0.5,y:0.35,w:12.3,h:0.9,fontSize:28,bold:true,color:NAVY,fontFace:'Arial',align:al,rtlMode:ar});if(CEO[u.id])a.addText(L(CEO[u.id]),{x:0.5,y:1.35,w:12.3,h:1,fontSize:16,italic:true,color:'5B6B82',fontFace:'Arial',align:al,rtlMode:ar,fill:{color:'FFF7E0'},margin:8});const st=L(u.steps)||[];if(st.length)a.addText(st.map((x,i)=>({text:x,options:{bullet:{type:'number'},breakLine:i<st.length-1}})),{x:0.5,y:2.6,w:12.3,h:4.2,fontSize:16,color:INK,fontFace:'Arial',align:al,rtlMode:ar,paraSpaceAfter:6,valign:'top'});a.addNotes(strip(L(u.body)).slice(0,2500));
const mp=(u.prompts||[]).slice(-1)[0];if(mp){let b=pres.addSlide();b.background={color:'FFFFFF'};b.addText('✎ '+L(mp.t),{x:0.5,y:0.35,w:12.3,h:0.7,fontSize:22,bold:true,color:NAVY,fontFace:'Arial',align:al,rtlMode:ar});b.addText(L(mp.p).slice(0,1600),{x:0.5,y:1.15,w:12.3,h:5.9,fontSize:11,color:INK,fontFace:'Courier New',valign:'top',fill:{color:'EEF2F7'},margin:10,align:al,rtlMode:ar})}});
s=pres.addSlide();s.background={color:NAVY};s.addText(ar?'شكراً — يلا نبني مع Claude':'Thank you — let\'s build with Claude',{x:0.6,y:2,w:9,h:1,fontSize:34,bold:true,color:'FFFFFF',fontFace:'Arial',align:al,rtlMode:ar});s.addText(LINKEDIN,{x:0.6,y:3.2,w:9,h:0.6,fontSize:16,color:GOLD,fontFace:'Arial',align:al});s.addImage({data:qr,x:10.6,y:2,w:2,h:2});
const blob=await pres.write({outputType:'blob'});await saveFile(base+'.pptx',blob)}
else{await ensureZip();const z=new JSZip();let md=`# ${L(UI.day)} ${d.n} — ${L(d.t)}\n\n${L(d.sub)}\n`;const keys=new Set();
d.units.forEach(u=>{md+=`\n## ${u.id} ${L(u.t)}\n\n${strip(L(u.body))}\n`;const st=L(u.steps)||[];if(st.length)md+='\n'+st.map((x,i)=>`${i+1}. ${x}`).join('\n')+'\n';(u.prompts||[]).forEach(p=>{md+=`\n### ${L(p.t)}\n\n\`\`\`\n${L(p.p)}\n\`\`\`\n`;z.file(`prompts/${u.id}-${p.t.en.replace(/[^a-z0-9]+/gi,'-').slice(0,40)}.txt`,L(p.p))})});
z.file(`${base}.md`,md);z.file(`${base}.html`,`<!doctype html><meta charset="utf-8"><style>${document.querySelector('style').textContent}</style>${moduleHTML(n)}`);
const relevant={1:['bva'],2:['kpis'],3:['kpis'],4:['ar_aging'],5:['bva','dcf_inputs','ar_aging'],6:['bank_gl','ar_aging'],7:['transactions','expenses'],8:['kpis'],9:['employees','expenses']}[n]||[];relevant.forEach(k=>z.file(`dummy-data/${k}.csv`,BOM+DATA[k].csv));
await saveFile(base+'.zip',await z.generateAsync({type:'blob'}))}
btn.textContent='✓'}catch(e){console.error(e);btn.textContent=ar?'حصلت مشكلة':'Failed'}btn.disabled=false;setTimeout(()=>btn.textContent=old,2500)}
function modExportBar(n){const ar=LANG==='ar';return `<div class="modexp"><span>⤓ ${ar?`صدّر الموديول ${n}`:`Export module ${n}`}</span><button class="tbtn" data-modexp="${n}:pdf">PDF</button><button class="tbtn" data-modexp="${n}:ppt">PPT</button><button class="tbtn" data-modexp="${n}:zip">ZIP</button><button class="tbtn" data-cheat="${n}">📄 ${L(UX6.cheat)}</button></div>`}
function libClick(e){const g=s=>e.target.closest(s);let x;
if(x=g('[data-labtab]')){labTab=x.dataset.labtab;render();return true}
if(x=g('[data-libtab]')){e.preventDefault();const [i,t]=x.dataset.libtab.split(':');libOpen[i]=t;render();return true}
if(x=g('[data-modexp]')){const [n,f]=x.dataset.modexp.split(':');exportModule(+n,f,x);return true}
return false}
document.addEventListener('toggle',e=>{const d=e.target;if(d.classList&&d.classList.contains('libi')){const i=d.dataset.libi;if(d.open&&!libOpen[i])libOpen[i]='master';if(!d.open)delete libOpen[i]}},true);
document.addEventListener('input',e=>{if(e.target.id==='libq'){libQ=e.target.value;const pos=e.target.selectionStart;render();const el=document.getElementById('libq');if(el){el.focus();el.setSelectionRange(pos,pos)}}});
document.addEventListener('change',e=>{if(e.target.id==='libdom'){libDom=e.target.value;render()}});
