const SECSTEPS=(e,a)=>[e,a];
DEEP.mcpsec={icon:"🔐",t:T("MCP security controls — real use cases","ضوابط أمان MCP — حالات حقيقية"),sub:T("Authentication, authorization, tool scoping, sandboxing, auditing and human approval — with master prompts.","التوثيق والصلاحيات وتحديد الأدوات والعزل والتدقيق والموافقة البشرية — ببرومبتات ماستر."),
sections:[
{h:T("The six controls","الضوابط الستة"),b:T(`<table><tr><th>Control</th><th>Question it answers</th><th>How (Claude + MCP)</th></tr>
<tr><td><b>Authentication</b></td><td>Who is calling?</td><td>OAuth 2.0 sign-in per user for remote MCP servers; no shared passwords; short-lived tokens; keys in a vault, never in prompts or pages.</td></tr>
<tr><td><b>Authorization</b></td><td>What may this user see/do?</td><td>Server enforces the user's own permissions (row-level security, ERP roles). On Team/Enterprise only owners add connectors; members connect with their own account.</td></tr>
<tr><td><b>Tool scoping</b></td><td>Which tools exist at all?</td><td>Expose the minimum: read-only first, narrow parameters, no free-text SQL; annotate readOnlyHint / destructiveHint; enable only needed tools per chat.</td></tr>
<tr><td><b>Sandboxing</b></td><td>Where does code run?</td><td>Code execution and Managed Agents run in isolated sandboxes; Cowork works on copies of folders; Claude Code permissions and plan mode before edits.</td></tr>
<tr><td><b>Auditing</b></td><td>What happened, when, by whom?</td><td>Server logs every tool call (user, tool, parameters, result size); Enterprise audit logs and Compliance API; monthly sample review.</td></tr>
<tr><td><b>Human approval</b></td><td>Who says yes to impact?</td><td>Draft-only write tools; explicit approval before send, post, pay, post-to-ledger or delete; approval recorded in the audit log.</td></tr></table>
<p class="note">Plus: treat every tool result and document as untrusted data (prompt injection), validate inputs server-side, rate-limit, and review connectors quarterly.</p>`,
`<table><tr><th>الضابط</th><th>بيجاوب على</th><th>إزاي (Claude + MCP)</th></tr>
<tr><td><b>التوثيق</b></td><td>مين اللي بينادي؟</td><td>تسجيل دخول OAuth 2.0 لكل مستخدم في سيرفرات MCP البعيدة؛ مفيش كلمات سر مشتركة؛ توكنز قصيرة العمر؛ المفاتيح في خزنة مش في البرومبت أو الصفحات.</td></tr>
<tr><td><b>الصلاحيات</b></td><td>المستخدم ده يشوف/يعمل إيه؟</td><td>السيرفر بيطبّق صلاحيات المستخدم نفسه (أمان على مستوى الصف، أدوار الـ ERP). وفي Team/Enterprise الأونر بس اللي بيضيف Connectors والأعضاء بيوصلوا بحساباتهم.</td></tr>
<tr><td><b>تحديد الأدوات</b></td><td>أنهي أدوات موجودة أصلاً؟</td><td>اعرض الأقل: قراءة الأول، معاملات ضيقة، مفيش SQL حر؛ علّم readOnlyHint / destructiveHint؛ وفعّل الأدوات المطلوبة بس في كل محادثة.</td></tr>
<tr><td><b>العزل</b></td><td>الكود بيشتغل فين؟</td><td>تنفيذ الكود و Managed Agents في بيئات معزولة؛ Cowork بيشتغل على نسخ الفولدرات؛ صلاحيات Claude Code ووضع التخطيط قبل التعديل.</td></tr>
<tr><td><b>التدقيق</b></td><td>إيه اللي حصل وإمتى ومين؟</td><td>السيرفر بيسجّل كل نداء أداة (المستخدم، الأداة، المعاملات، حجم النتيجة)؛ سجلات Enterprise و Compliance API؛ مراجعة عينة شهرية.</td></tr>
<tr><td><b>الموافقة البشرية</b></td><td>مين يقول نعم للأثر؟</td><td>أدوات كتابة مسودات بس؛ موافقة صريحة قبل الإرسال أو النشر أو الدفع أو الترحيل أو المسح؛ والموافقة متسجلة في سجل التدقيق.</td></tr></table>
<p class="note">وكمان: اتعامل مع أي نتيجة أداة أو مستند كبيانات مش موثوقة (حقن الأوامر)، اتحقق من المدخلات في السيرفر، حدد معدل الطلبات، وراجع الـ Connectors كل ربع.</p>`)}
],
cases:[
CM("1 · Authentication — ERP connector with OAuth","1 · التوثيق — Connector للـ ERP بـ OAuth","MCP · Claude Code","","",["Register OAuth app","Implement auth flow","Test with 2 users","Rotate secrets"],["سجّل تطبيق OAuth","نفّذ تدفق الدخول","اختبر بمستخدمين","دوّر الأسرار"],
["Security-minded integration engineer","Add OAuth 2.0 authentication to our ERP MCP server","- Remote MCP over HTTPS; identity provider: [Entra ID / Google / Okta]\n- Callback https://claude.ai/api/mcp/auth_callback\n- Secrets in a vault","No shared credentials; every call tied to a real user","- Per-user tokens, short-lived with refresh\n- No secret in code, logs or prompts\n- Tested with two users and a revoked user","Code changes, config guide, test evidence, threat notes."],
["مهندس تكامل مهتم بالأمان","ضيف توثيق OAuth 2.0 لسيرفر MCP بتاع الـ ERP","- MCP عن بُعد على HTTPS؛ مزوّد الهوية: [Entra ID / Google / Okta]\n- رابط الرجوع https://claude.ai/api/mcp/auth_callback\n- الأسرار في خزنة","مفيش بيانات دخول مشتركة؛ وكل نداء مربوط بمستخدم حقيقي","- توكنز لكل مستخدم قصيرة العمر بتجديد\n- مفيش أسرار في الكود أو السجلات أو البرومبت\n- متجرب بمستخدمين ومستخدم ملغي","تعديلات الكود، دليل الإعداد، أدلة الاختبار، ملاحظات التهديدات."]),
CM("2 · Authorization — row-level permissions","2 · الصلاحيات — صلاحيات على مستوى الصف","MCP","","",["Map roles","Enforce in server","Negative tests"],["حدد الأدوار","طبّقها في السيرفر","اختبارات الرفض"],
["Access-control architect","Enforce ERP role permissions inside MCP tools","- Roles: CFO (all entities), branch accountant (own branch), sales manager (own customers' AR only)\n- Tools: get_aging, search_invoices","Claude must never show data the user can't see in the ERP","- Permission checked on every call server-side\n- Negative tests: 10 forbidden queries return 'not permitted'\n- No data leakage in error messages","Permission matrix + code + test report."],
["مهندس صلاحيات","طبّق صلاحيات أدوار الـ ERP جوه أدوات MCP","- الأدوار: المدير المالي (كل الشركات)، محاسب الفرع (فرعه بس)، مدير المبيعات (عملاءه بس)\n- الأدوات: get_aging و search_invoices","Claude عمره ما يعرض بيانات المستخدم ميقدرش يشوفها في الـ ERP","- الصلاحية بتتراجع في كل نداء في السيرفر\n- اختبارات رفض: 10 استعلامات ممنوعة بترجع 'غير مسموح'\n- مفيش تسريب بيانات في رسائل الخطأ","مصفوفة الصلاحيات + الكود + تقرير الاختبار."]),
CM("3 · Tool scoping — least privilege toolset","3 · تحديد الأدوات — أقل صلاحيات","MCP · mcp-builder","","",["Inventory tools","Split read/write","Annotate hints"],["حصر الأدوات","افصل القراءة/الكتابة","علّم التلميحات"],
["MCP designer","Redesign our finance MCP toolset for least privilege","- Current server exposes run_sql(query) and update_record(table, data)","A generic SQL tool is an open door","- Replace with 6 specific read tools and 1 draft-only write tool\n- Narrow parameters with validation\n- readOnlyHint/destructiveHint set; descriptions precise","New tool spec table + migration plan + code."],
["مصمم MCP","اعد تصميم أدوات MCP المالية بأقل صلاحيات","- السيرفر الحالي بيعرض run_sql(query) و update_record(table, data)","أداة SQL عامة باب مفتوح","- استبدلها بـ 6 أدوات قراءة محددة وأداة كتابة مسودات بس\n- معاملات ضيقة بتحقق\n- readOnlyHint/destructiveHint مظبوطة؛ وأوصاف دقيقة","جدول مواصفات الأدوات الجديدة + خطة الانتقال + الكود."]),
CM("4 · Sandboxing — safe document processing","4 · العزل — معالجة مستندات بأمان","Managed Agents · Cowork","","",["Isolate runtime","Copies only","No network by default"],["اعزل التشغيل","نسخ بس","من غير شبكة افتراضياً"],
["Platform security engineer","Run invoice-processing agents in an isolated sandbox","- Untrusted supplier PDFs; agent uses code execution to parse\n- Managed Agents or containerised runtime","A malicious file must not reach our systems","- No network egress except an allow-listed ERP draft endpoint\n- Read-only input mount; outputs to a separate folder\n- Resource and time limits","Sandbox configuration + allow-list + test with a malicious sample."],
["مهندس أمان المنصات","شغّل وكلاء معالجة الفواتير في بيئة معزولة","- ملفات PDF موردين غير موثوقة؛ والوكيل بيستخدم تنفيذ الكود للقراءة\n- Managed Agents أو بيئة حاويات","ملف خبيث ميوصلش لأنظمتنا","- مفيش خروج للشبكة غير endpoint مسودات الـ ERP المسموح\n- المدخلات قراءة بس؛ والمخرجات في فولدر منفصل\n- حدود موارد ووقت","إعداد العزل + القائمة المسموحة + اختبار بعينة خبيثة."]),
CM("5 · Auditing — tool-call log & monthly review","5 · التدقيق — سجل نداءات الأدوات والمراجعة الشهرية","MCP · Enterprise","","",["Log schema","Dashboard","Monthly sampling"],["شكل السجل","الداشبورد","العينة الشهرية"],
["Internal auditor for AI systems","Design the audit trail for our MCP connectors","- Fields: timestamp, user, tool, parameters (masked PII), result size, approval id\n- Enterprise audit logs and Compliance API available","Regulators and the audit committee will ask","- Log schema and retention (e.g. 1 year)\n- Anomaly rules (volume spikes, off-hours, denied calls)\n- Monthly sample review checklist","Log spec + dashboard artifact + review checklist."],
["مراجع داخلي لأنظمة الـ AI","صمّم سجل التدقيق لـ Connectors الـ MCP","- الحقول: الوقت، المستخدم، الأداة، المعاملات (البيانات الشخصية مخفية)، حجم النتيجة، رقم الموافقة\n- سجلات Enterprise و Compliance API متاحة","الرقابة ولجنة المراجعة هيسألوا","- شكل السجل ومدة الاحتفاظ (مثلاً سنة)\n- قواعد الشذوذ (قفزات الحجم، خارج المواعيد، النداءات المرفوضة)\n- قائمة مراجعة العينة الشهرية","مواصفات السجل + داشبورد Artifact + قائمة المراجعة."]),
CM("6 · Human approval — draft → approve → execute","6 · الموافقة البشرية — مسودة ← موافقة ← تنفيذ","MCP · Agent","","",["Draft tools","Approval queue","Execute & log"],["أدوات المسودات","طابور الموافقة","التنفيذ والتسجيل"],
["Controls designer","Add a human approval gate to the collections agent","- Agent drafts reminder emails and payment-plan proposals via MCP\n- Approvers: credit controller (<EGP 500K), CFO (above)","No customer receives anything unapproved","- Write tools create drafts only\n- Approval UI or Slack approval with reason\n- Execution tool checks approval id; everything logged","Flow diagram + tool changes + approval matrix."],
["مصمم ضوابط","ضيف بوابة موافقة بشرية لوكيل التحصيل","- الوكيل بيكتب مسودات تذكير واقتراحات جدولة عبر MCP\n- الموافقين: مسؤول الائتمان (< 500 ألف)، المدير المالي (فوق كده)","مفيش عميل يستلم حاجة من غير موافقة","- أدوات الكتابة بتعمل مسودات بس\n- واجهة موافقة أو موافقة Slack بالسبب\n- أداة التنفيذ بتتأكد من رقم الموافقة؛ وكل حاجة متسجلة","مخطط التدفق + تعديلات الأدوات + مصفوفة الموافقة."]),
CM("Full scenario · Secure CFO assistant on the ERP","سيناريو كامل · مساعد مدير مالي آمن على الـ ERP","MCP · all six controls","","",["Threat model","Implement 6 controls","Pen-test","Go-live checklist"],["نموذج التهديدات","نفّذ الضوابط الستة","اختبار اختراق","قائمة الإطلاق"],
["Security architect and finance controller","Design and launch a secure CFO assistant on the ERP through MCP","- Users: CFO, controllers, branch accountants\n- Data: GL, AR/AP, payroll summaries (no individual salaries)\n- Controls: authentication, authorization, tool scoping, sandboxing, auditing, human approval","Fast answers without a data breach or an unapproved action","- Threat model (STRIDE) with mitigations\n- Each of the six controls implemented and tested\n- Go-live checklist signed by IT security, finance and compliance","Architecture diagram + control matrix + test evidence + go-live checklist."],
["مهندس أمان وكنترولر مالي","صمّم وأطلق مساعد مدير مالي آمن على الـ ERP عبر MCP","- المستخدمين: المدير المالي، الكنترولرز، محاسبي الفروع\n- البيانات: الأستاذ العام، العملاء/الموردين، ملخصات المرتبات (من غير مرتبات أفراد)\n- الضوابط: التوثيق، الصلاحيات، تحديد الأدوات، العزل، التدقيق، الموافقة البشرية","إجابات سريعة من غير تسريب بيانات أو إجراء غير معتمد","- نموذج تهديدات (STRIDE) بالمعالجات\n- الضوابط الستة متنفذة ومتجربة\n- قائمة الإطلاق موقعة من أمن المعلومات والمالية والالتزام","مخطط المعمارية + مصفوفة الضوابط + أدلة الاختبار + قائمة الإطلاق."])
]};
// work done in this course project
WORKCATS.unshift({c:T("Built together in this course project","اتبنى معاً في مشروع الكورس ده"),i:"🤝",items:[
W("Claude Mastery — complete platform","Claude Mastery — المنصة الكاملة","9 modules, 33 lessons, deep dives, lab with dummy data, tutor, quizzes, certificate, builders, exports.","9 موديولات و33 درس وتعمق ومعمل ببيانات تجريبية ومدرّس وكويزات وشهادة وأدوات بناء وتصدير.","Chat",PLATFORM_URL,
["Learning-platform architect","Extend the Claude Mastery platform with [feature]","- Single self-contained HTML, Arabic/English, RTL, light/dark, brand navy/gold/teal\n- Existing sections: modules, deep dives, lab, libraries, tools, exports","Keep the platform growing without breaking what works","- Feature works in both languages and themes\n- No console errors; every route tested\n- Page stays under 16 MB","Updated HTML + change log."],
["مهندس منصات تعليمية","طوّر منصة Claude Mastery بـ [الميزة]","- HTML واحد مستقل، عربي/إنجليزي، RTL، نهاري/ليلي، كحلي/دهبي/تركوازي\n- الأقسام الحالية: الموديولات، التعمق، المعمل، المكتبات، الأدوات، التصدير","نكبّر المنصة من غير ما نكسر اللي شغال","- الميزة شغالة باللغتين والوضعين\n- مفيش أخطاء؛ وكل صفحة متجربة\n- الصفحة أقل من 16 ميجا","HTML محدّث + سجل التغييرات."]),
W("Curriculum PDFs & Master Prompt Book","ملفات المنهج PDF وكتاب البرومبتات الماستر","Arabic and English PDFs of the whole curriculum and every master prompt.","PDF عربي وإنجليزي للمنهج كله وكل البرومبتات الماستر.","Chat","",
["Publishing designer","Export the curriculum and master prompts to print-ready PDFs","- Cover with QR and LinkedIn; A4; page numbers","Learners keep a reference offline","- Arabic shaping correct\n- No cut prompts\n- Under 5 MB each","Two curriculum PDFs + two prompt books."],
["مصممة نشر","صدّر المنهج والبرومبتات الماستر لملفات PDF جاهزة للطباعة","- غلاف بـ QR ولينكدإن؛ A4؛ ترقيم صفحات","المتدربين يحتفظوا بمرجع أوفلاين","- تشكيل العربي صح\n- مفيش برومبتات مقطوعة\n- أقل من 5 ميجا لكل ملف","2 PDF للمنهج + 2 كتاب برومبتات."]),
W("Claude capability research report","تقرير بحث قدرات Claude","Feature-by-feature reference (status Sept 2026) used as the course foundation.","مرجع لكل ميزة (حالتها سبتمبر 2026) اتبنى عليه الكورس.","Research","",
["Research analyst","Produce an up-to-date reference on every Claude feature for a bilingual business course","- For each: definition, plans, steps, options, limits, use cases, prompts, official links","The course must be accurate","- Official sources prioritised\n- Uncertain items flagged\n- Course structure proposed","Structured report + glossary."],
["محللة أبحاث","طلّعي مرجع محدّث لكل ميزة في Claude لكورس بيزنس ثنائي اللغة","- لكل ميزة: التعريف، الخطط، الخطوات، الخيارات، الحدود، الحالات، البرومبتات، الروابط الرسمية","الكورس لازم يكون دقيق","- المصادر الرسمية أولاً\n- البنود غير المؤكدة متعلّمة\n- هيكل كورس مقترح","تقرير منظم + قاموس."]),
W("First React LMS version","أول نسخة منصة React","The earlier 4-day React course component that started this project.","مكوّن كورس React الـ 4 أيام اللي بدأ المشروع.","Chat","",
["React developer","Build a 4-day course LMS component","- Days, units, prompts, real cases; Arabic/English toggle; light/dark","Prototype the course structure","- Navigation and tabs work\n- Copy buttons\n- Glossary panel","Single .jsx file."],
["مطوّرة React","ابني مكوّن منصة كورس 4 أيام","- أيام، وحدات، برومبتات، حالات؛ زرار عربي/إنجليزي؛ نهاري/ليلي","نجرّب هيكل الكورس","- التنقل والتبويبات شغالين\n- أزرار النسخ\n- لوحة القاموس","ملف .jsx واحد."])]});
// references: Anthropic community (own section on the References page; links taken from claude.com/community, checked Oct 2026)
REFS.unshift({g:T("Directory & this course","الدليل والكورس ده"),items:[
["Claude connectors & apps directory","https://claude.ai/directory"],
["Claude Academy","https://academy.claude.com"],
["Claude Mastery platform (this course)","https://claude.ai/artifact/SWKveDA1ZfXuaeRLhm1mu5"]]});
const COMMUNITY=[
{i:'💬',g:T("Join the conversation","انضم للنقاش"),items:[
["Claude Community hub","https://claude.com/community",T("Events, Discord and the community newsletter in one place.","الفعاليات والديسكورد ونشرة المجتمع في مكان واحد.")],
["Claude Discord","https://discord.com/invite/6PPFFzqPDZ",T("Ask questions, share builds and meet other Claude users.","اسأل وشارك اللي بنيته واتعرّف على مستخدمين Claude التانيين.")],
["r/ClaudeAI on Reddit","https://www.reddit.com/r/ClaudeAI/",T("Community discussion, tips and showcases.","نقاشات ونصايح وأعمال من المجتمع.")]]},
{i:'📅',g:T("Events & meetups","الفعاليات واللقاءات"),items:[
["Claude Community events (Luma)","https://luma.com/claudecommunity",T("Local meetups, build days, hackathons and impact labs worldwide.","لقاءات محلية وأيام بناء وهاكاثونات حول العالم.")],
["Anthropic events","https://www.anthropic.com/events",T("Official conferences, founder houses and virtual briefings.","المؤتمرات الرسمية وبيوت المؤسسين والجلسات الأونلاين.")],
["Build with Claude","https://www.anthropic.com/events/build-with-claude",T("Anthropic’s developer event series.","سلسلة فعاليات Anthropic للمطورين.")]]},
{i:'🎓',g:T("Programs","البرامج"),items:[
["Claude Community Ambassadors","https://claude.com/community/ambassadors",T("Lead a local Claude community and host events.","قود مجتمع Claude في مدينتك ونظّم فعاليات.")],
["Claude for campus","https://claude.com/programs/campus",T("Student and university programs.","برامج الطلبة والجامعات.")],
["Claude for startups","https://claude.com/programs/startups",T("Support for early-stage startups building on Claude.","دعم للشركات الناشئة اللي بتبني على Claude.")]]},
{i:'📣',g:T("Follow Anthropic & Claude","تابع Anthropic و Claude"),items:[
["YouTube — @anthropic-ai","https://www.youtube.com/@anthropic-ai",T("Talks, demos and launch videos.","محاضرات وعروض وفيديوهات الإطلاق.")],
["X — @claudeai","https://x.com/claudeai",T("Claude product updates.","تحديثات منتج Claude.")],
["X — @AnthropicAI","https://x.com/AnthropicAI",T("Company and research news.","أخبار الشركة والأبحاث.")],
["LinkedIn — Claude","https://www.linkedin.com/showcase/claude/",T("Claude showcase page.","صفحة Claude على لينكدإن.")],
["LinkedIn — Anthropic","https://www.linkedin.com/company/anthropicresearch",T("Anthropic company page.","صفحة شركة Anthropic.")],
["Instagram — @claudeai","https://www.instagram.com/claudeai",T("Short videos and visuals.","فيديوهات قصيرة وصور.")],
["Threads — @claudeai","https://www.threads.com/@claudeai",T("Updates and conversations.","تحديثات ونقاشات.")]]},
{i:'📰',g:T("Stay current","خليك متابع"),items:[
["Anthropic news","https://www.anthropic.com/news",T("Official announcements.","الإعلانات الرسمية.")],
["Claude blog","https://claude.com/blog",T("Product guides and customer stories.","أدلة المنتج وقصص العملاء.")],
["Anthropic engineering blog","https://www.anthropic.com/engineering",T("How Anthropic builds agents and tools.","إزاي Anthropic بتبني الـ agents والأدوات.")],
["Anthropic research","https://www.anthropic.com/research",T("Alignment, interpretability and societal-impact research.","أبحاث الأمان والتفسير والأثر المجتمعي.")],
["Anthropic status","https://status.anthropic.com/",T("Live service status and incidents.","حالة الخدمة والأعطال لحظة بلحظة.")]]}];
