// Lesson 2.6 — mobile, desktop, voice
DAYS[1].units.push({id:"2.6",tag:"practical",dur:"25",t:T("Mobile, desktop & voice","الموبايل والديسكتوب والصوت"),
 body:T(`<p>Claude runs on <b>web</b>, <b>desktop</b> (macOS, Windows, Linux) and <b>mobile</b> (iOS, Android). The desktop app gives the full Cowork experience (local folders, computer use). Mobile supports chat, Projects, file and photo upload, <b>voice mode</b>, Cowork (beta), <b>Dispatch</b> (send a task to your desktop) and the Code tab. Your chats, Projects, memory, Skills and connectors sync across devices.</p>`,`<p>Claude شغال على <b>الويب</b> و<b>الديسكتوب</b> (ماك وويندوز ولينكس) و<b>الموبايل</b> (iOS و Android). تطبيق الديسكتوب بيدّي تجربة Cowork الكاملة (فولدرات محلية واستخدام الكمبيوتر). والموبايل فيه الشات والـ Projects ورفع الملفات والصور و<b>وضع الصوت</b> و Cowork (بيتا) و<b>Dispatch</b> (تبعت مهمة للكمبيوتر) وتبويب Code. محادثاتك ومشاريعك وذاكرتك والـ Skills والـ Connectors متزامنين على كل الأجهزة.</p>`),
 steps:T(["Install the mobile and desktop apps and sign in","Try voice mode for a client-call debrief","Photograph a document and ask for extraction","Use Dispatch to start a Cowork task from your phone"],["نزّل تطبيق الموبايل والديسكتوب وسجّل","جرّب وضع الصوت في تلخيص مكالمة عميل","صوّر مستند واطلب استخراج البيانات","استخدم Dispatch تبدأ مهمة Cowork من الموبايل"]),
 tips:T(["Dictate your context — speaking is often faster than typing a long prompt.","Don't photograph confidential documents on a personal device."],["اتكلم السياق بدل ما تكتبه — الكلام غالباً أسرع من كتابة برومبت طويل.","متصورش مستندات سرية على موبايلك الشخصي."]),
 cases:[{t:T("Call report on the go","تقرير زيارة وإنت ماشي"),d:T("After a client visit, dictate notes in voice mode; Claude returns a structured visit report and follow-up email draft.","بعد زيارة عميل، اتكلم ملاحظاتك بوضع الصوت؛ و Claude يرجّع تقرير زيارة منظم ومسودة إيميل متابعة.")}],
 prompts:[{t:T("Voice debrief","تلخيص صوتي"),p:T(`I'll speak my notes from a client meeting. Turn them into: meeting summary, decisions, risks, action items (owner, date), and a short follow-up email to the client in their language.`,`هتكلم ملاحظاتي من اجتماع عميل. حوّلها لـ: ملخص الاجتماع، القرارات، المخاطر، المهام (المسؤول والتاريخ)، وإيميل متابعة قصير للعميل بلغته.`)}],doc:""});
// Feature coverage per lesson
const FEAT={"1.1":"Claude app, surfaces","1.2":"AI concepts, RAG, agents, MCP","1.3":"Models, effort, thinking","1.4":"Prompting framework","1.5":"Few-shot, XML, chaining, evaluation","1.6":"Plans & pricing",
"2.1":"Files, vision, web search, Research","2.2":"Projects","2.3":"Memory, past-chat search, incognito","2.4":"Context window, compaction","2.5":"Styles, instructions","2.6":"Mobile, desktop, voice, Dispatch",
"3.1":"Artifacts, publishing","3.2":"File creation, Claude Docs, Slides","3.3":"Claude Design",
"4.1":"Skills, skill-creator","4.2":"Plugins, finance agents","4.3":"Connectors, MCP",
"5.1":"Claude for Excel","5.2":"PowerPoint, Word, Outlook","5.3":"Claude in Chrome","5.4":"Claude Tag (Slack)",
"6.1":"Cowork, schedules","6.2":"Dispatch, computer use, agent templates",
"7.1":"Claude Code, CLAUDE.md, commands","7.2":"API, Agent SDK, Managed Agents","7.3":"RAG, games, websites, apps, mini-ERP",
"8.1":"Capstones, 90-day plan","9.1":"Privacy, admin, regional rules","9.2":"Responsible AI principles","9.3":"Ethics cases","9.4":"Governance framework"};
const REFS=[
{g:T("Learn","التعلّم"),items:[
["Claude Academy — courses & tutorials","https://academy.claude.com"],
["Introduction to Claude Cowork (Academy)","https://academy.claude.com/courses/introduction-to-claude-cowork/getting-set-up"],
["Get started in Cowork in three steps (Academy)","https://academy.claude.com/tutorials/get-started-in-claude-cowork-in-three-steps"],
["Install financial-services plugins (tutorial)","https://claude.com/resources/tutorials/install-financial-services-plugins-for-cowork"],
["Anthropic courses (GitHub)","https://github.com/anthropics/courses"],
["Anthropic cookbook (GitHub)","https://github.com/anthropics/anthropic-cookbook"]]},
{g:T("Prompting","البرومبت"),items:[
["Prompt engineering overview","https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview"],
["Prompting best practices","https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices"],
["Console prompting tools (generator, improver)","https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/prompting-tools"]]},
{g:T("Product help","مساعدة المنتج"),items:[
["Claude Help Center","https://support.claude.com"],
["Use skills in Claude","https://support.claude.com/en/articles/12512180-use-skills-in-claude"],
["Use plugins in Claude","https://support.claude.com/en/articles/13837440-use-plugins-in-claude"],
["Use connectors","https://support.claude.com/en/articles/11176164-use-connectors-to-extend-claude-s-capabilities"],
["Custom connectors with remote MCP","https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp"],
["Memory & past-chat search","https://support.claude.com/en/articles/11817273-use-claude-s-chat-search-and-memory-to-build-on-previous-context"],
["Incognito chats","https://support.claude.com/en/articles/12260368-use-incognito-chats"],
["Get started with Cowork","https://support.claude.com/en/articles/13345190-get-started-with-claude-cowork"],
["Cowork on web, desktop & mobile","https://support.claude.com/en/articles/15520349-use-claude-cowork-on-web-desktop-and-mobile"],
["Claude for Excel","https://support.claude.com/en/articles/12650343-use-claude-for-excel"],
["Claude for PowerPoint","https://support.claude.com/en/articles/13521390-use-claude-for-powerpoint"],
["Plans & pricing","https://claude.com/pricing"]]},
{g:T("Products & announcements","المنتجات والإعلانات"),items:[
["Cowork and chat are now one Claude","https://claude.com/blog/cowork-is-now-claude"],
["Claude Design (Anthropic Labs)","https://www.anthropic.com/news/claude-design-anthropic-labs"],
["Introducing Claude Skills","https://www.anthropic.com/news/skills"],
["Agents for financial services","https://www.anthropic.com/news/finance-agents"],
["Cowork and plugins for finance","https://claude.com/blog/cowork-plugins-finance"],
["Deploying Claude across financial services","https://claude.com/blog/deploying-claude-across-financial-services"],
["Claude for Microsoft 365","https://claude.com/claude-for-microsoft-365"],
["Claude Tag in Slack","https://claude.com/product/tag"],
["Plugins directory","https://claude.com/plugins"],
["Introducing Claude Opus 5.5","https://www.anthropic.com/claude-opus-5-5"]]},
{g:T("Developers","المطوّرين"),items:[
["Claude Code docs","https://code.claude.com/docs/en/overview"],
["Claude Code commands","https://code.claude.com/docs/en/commands"],
["API overview","https://platform.claude.com/docs/en/api/overview"],
["Agent Skills (API)","https://platform.claude.com/docs/en/agents-and-tools/agent-skills/overview"],
["Batch processing","https://platform.claude.com/docs/en/build-with-claude/batch-processing"],
["Citations","https://platform.claude.com/docs/en/build-with-claude/citations"],
["Release notes","https://platform.claude.com/docs/en/release-notes/overview"],
["Claude Managed Agents","https://claude.com/blog/claude-managed-agents"],
["Model Context Protocol","https://modelcontextprotocol.io"],
["Agent Skills repository","https://github.com/anthropics/skills"],
["Financial-services plugins","https://github.com/anthropics/financial-services"]]},
{g:T("Research & data","البحث والبيانات"),items:[
["Anthropic Economic Index","https://www.anthropic.com/economic-index"],
["Complete guide to building skills (PDF)","https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf"]]}
];
const FOLDERNAMES={finance:T("Finance & valuation","المالية والتقييم"),excel:T("Excel & FP&A","Excel و FP&A"),automation:T("Automation","الأتمتة"),slides:T("Slides & decks","العروض"),connectors:T("Connectors & MCP","Connectors و MCP"),research:T("Research tools","أدوات البحث"),prompting:T("Prompting","البرومبت"),code:T("Claude Code","Claude Code"),design:T("Claude Design","Claude Design"),skills:T("Skills & plugins","Skills و Plugins"),cowork:T("Agentic & Cowork","الوكلاء و Cowork"),agents:T("Build an AI agent","بناء وكيل AI"),map:T("Mastery map","خريطة الإتقان")};
GLOSS.push(
["Anthropic","أنثروبيك","The AI safety company that builds Claude.","شركة أمان الذكاء الاصطناعي اللي بتطوّر Claude."],
["Claude Code","Claude Code","Agentic coding tool in terminal, IDE, desktop and web.","أداة برمجة وكيلية في الـ Terminal و IDE والديسكتوب والويب."],
["Claude Docs","Claude Docs","Co-written, shareable documents in Claude (beta).","مستندات بتتكتب مع Claude وتتشارك (بيتا)."],
["Claude Slides","Claude Slides","Decks you present from Claude or download (beta).","عروض تعرضها من Claude أو تنزّلها (بيتا)."],
["Claude for Excel","Claude for Excel","Add-in that reads, explains and builds workbooks.","إضافة بتقرا وتشرح وتبني ملفات Excel."],
["Claude in Chrome","Claude in Chrome","Browser extension that navigates and fills forms.","إضافة للمتصفح بتتنقل وتملا الفورمز."],
["Styles","الأساليب","Saved writing voices for Claude.","أصوات كتابة محفوظة لـ Claude."],
["Live artifact","Artifact حي","An artifact connected to data that updates.","Artifact متوصل ببيانات وبيتحدّث."],
["Scheduled task","مهمة مجدولة","A Cowork task that runs on a schedule.","مهمة Cowork بتشتغل في ميعاد محدد."],
["Slash command","أمر سلاش","A command typed with / to trigger a skill or action.","أمر بيتكتب بـ / علشان يشغّل Skill أو إجراء."],
["Sandbox","بيئة معزولة","Isolated environment where code runs safely.","بيئة منفصلة الكود بيشتغل فيها بأمان."],
["Rate limit","حد الاستخدام","Cap on requests or tokens in a period.","حد أقصى للطلبات أو التوكنز في فترة."],
["Usage limit","حد الخطة","How much you can use Claude per period on your plan.","قد إيه تقدر تستخدم Claude في فترة حسب خطتك."],
["Vector database","قاعدة بيانات متجهات","Stores embeddings for similarity search.","بتخزّن الـ Embeddings للبحث بالتشابه."],
["Chunking","التقطيع","Splitting documents into passages for retrieval.","تقسيم المستندات لمقاطع علشان الاسترجاع."],
["Multimodal","متعدد الوسائط","Handles text and images together.","بيتعامل مع النص والصور مع بعض."],
["OAuth","OAuth","Standard way to sign in and grant app access.","طريقة قياسية لتسجيل الدخول ومنح الصلاحية."],
["Least privilege","أقل صلاحية","Give only the access a task needs.","ادّي الصلاحية اللي المهمة محتاجاها بس."],
["Audit trail","سجل التدقيق","Record of who did what and when.","سجل مين عمل إيه وإمتى."],
["Data retention","الاحتفاظ بالبيانات","How long conversations and files are kept.","المحادثات والملفات بتتحفظ قد إيه."],
["Zero data retention","عدم الاحتفاظ بالبيانات","API option where inputs aren't stored after processing.","خيار في الـ API المدخلات مبتتخزنش بعد المعالجة."],
["SSO / SCIM","الدخول الموحّد / SCIM","Single sign-on and automatic user provisioning.","دخول موحّد وإدارة المستخدمين تلقائياً."],
["Bias","التحيز","Systematic unfairness against a group.","ظلم ممنهج ضد فئة."],
["Model card","بطاقة النموذج","Document describing a model's abilities and limits.","مستند بيوصف قدرات النموذج وحدوده."],
["Evaluation (evals)","التقييم","Testing prompts or models against scored cases.","اختبار البرومبتات أو النماذج على حالات بدرجات."],
["Workflow","سير العمل","A repeatable sequence of steps across people and tools.","تسلسل خطوات متكرر بين الناس والأدوات."],
["Orchestration","التنسيق","Coordinating several agents or tools on one task.","تنسيق كذا وكيل أو أداة على مهمة واحدة."],
["Webhook","Webhook","Automatic message one system sends another on an event.","رسالة تلقائية نظام بيبعتها لنظام تاني عند حدث."],
["JSON schema","مخطط JSON","Formal description of the structure data must follow.","وصف رسمي للهيكل اللي البيانات لازم تمشي عليه."],
["Prompt template","قالب برومبت","Reusable prompt with [VARIABLES].","برومبت يتعاد استخدامه بـ [متغيرات]."],
["Meta-prompt","برومبت عن البرومبت","A prompt that writes or improves prompts.","برومبت بيكتب أو يحسّن برومبتات."],
["Hand-off summary","ملخص التسليم","Summary used to continue work in a new chat.","ملخص بيتستخدم لاستكمال الشغل في محادثة جديدة."]
);
