SKILLS.push(
{g:T("Finance, accounting & audit plugins (more)","Plugins المالية والمحاسبة والمراجعة (المزيد)"),items:[
S("finance:journal-entry-prep",T("Accounting","المحاسبة"),"Prepares month-end journal entries with full support documentation.","بيجهّز قيود آخر الشهر بالمستندات الكاملة.","Accruals, prepaid, depreciation, payroll, revenue entries.","المستحقات والمدفوع مقدماً والإهلاك والمرتبات والإيراد.","Review-ready entries with evidence.","قيود جاهزة للمراجعة بالأدلة.","Prepare the October prepaid amortisation entry"),
S("finance:sox-testing",T("Audit · Risk","المراجعة · المخاطر"),"Generates SOX samples, testing workpapers and deficiency assessments.","بيطلّع عينات واختبارات SOX وتقييم القصور.","Quarterly or annual control testing.","اختبار الضوابط ربع سنوي أو سنوي.","Consistent, auditable testing.","اختبار ثابت وقابل للمراجعة.","Plan Q4 testing for revenue controls"),
S("statement-auditor:nav-tieout / audit-xls",T("Funds · Audit","الصناديق · المراجعة"),"Ties LP statements to the NAV pack; audits spreadsheets.","بيطابق كشوف المستثمرين مع صافي الأصول؛ ويراجع الجداول.","Before distributing LP statements.","قبل توزيع كشوف المستثمرين.","Catches capital-account errors.","بيمسك أخطاء حسابات رأس المال.","Tie this LP statement to the NAV"),
S("gl-recon / break-trace",T("Accounting · Operations","المحاسبة · العمليات"),"Reconciles GL to subledger and traces each break to its source.","بيطابق الأستاذ مع الدفاتر المساعدة ويتتبع كل فرق لمصدره.","Daily or month-end recon runs.","تشغيلات المطابقة اليومية وآخر الشهر.","Root cause, not just a list of breaks.","السبب الجذري مش بس قائمة فروق.","Trace this reconciliation break"),
S("carta-investors (30+ skills)",T("Venture & PE funds","صناديق رأس المال المخاطر والملكية الخاصة"),"Carta fund data: portfolio analytics, cap tables, SOI, fund modelling, LP reporting, ManCo budgets, SPA audits, Form ADV, AGM decks.","بيانات صناديق Carta: تحليلات المحفظة، جداول الملكية، SOI، نمذجة الصناديق، تقارير المستثمرين، موازنات شركة الإدارة، فحص الاتفاقيات، Form ADV، عروض الجمعية.","Fund administration and investor reporting on Carta.","إدارة الصناديق وتقارير المستثمرين على Carta.","Live fund data without manual exports.","بيانات الصندوق الحية من غير تصدير يدوي.","Portfolio analytics for our fund")]},
{g:T("Sales plugin (all skills)","Plugin المبيعات (كل الـ Skills)"),items:[
S("sales:daily-briefing / end-of-day / weekly-wrap",T("Sales","المبيعات"),"Morning brief, end-of-day close-out and Friday summary.","ملخص الصبح وقفل اليوم وملخص الجمعة.","Every working day.","كل يوم شغل.","Nothing slips between days.","مفيش حاجة بتضيع بين الأيام.","Daily briefing"),
S("sales:deal-review / deal-advance-gap / deal-signals / deal-slip-scenario",T("Sales","المبيعات"),"Deal health, what's missing to advance, alerts, and slip scenarios.","صحة الصفقة، الناقص للتقدم، التنبيهات، وسيناريوهات التأخير.","Before forecast calls and 1:1s.","قبل مكالمات التوقع والاجتماعات الفردية.","Honest, evidence-based deal views.","رؤية صادقة للصفقات بالدليل.","What happens if the Acme deal slips?"),
S("sales:account-plan / account-tiering / expansion-whitespace / renewal-radar / customer-health",T("Sales · Account management","المبيعات · إدارة الحسابات"),"Account plans, tiering, upsell whitespace, renewals and health checks.","خطط الحسابات، التصنيف، فرص البيع الإضافي، التجديدات، صحة العملاء.","Quarterly planning and QBRs.","التخطيط الربع سنوي ومراجعات العملاء.","Grow existing customers systematically.","تكبير العملاء الحاليين بانتظام.","Tier my accounts"),
S("sales:lead-triage / route-lead / stakeholder-map / competitive-intelligence / customer-voice / win-loss-review",T("Sales · Marketing","المبيعات · التسويق"),"Lead scoring and routing, stakeholder maps, battlecards, customer quotes, win/loss.","تقييم وتوجيه العملاء، خرائط أصحاب القرار، بطاقات المنافسة، آراء العملاء، الفوز/الخسارة.","Pipeline building and competitive deals.","بناء الـ Pipeline والصفقات التنافسية.","Focus on the right leads and arguments.","تركيز على العملاء والحجج الصح.","Triage this lead"),
S("sales:call-summary / log-activity / schedule-meeting / update-opportunity / crm-hygiene-check / create-an-asset / team-pipeline / rep-context / setup",T("Sales operations","عمليات المبيعات"),"Call recaps, CRM logging and updates, scheduling, hygiene audits, sales assets, team views, onboarding.","ملخصات المكالمات، تسجيل وتحديث الـ CRM، المواعيد، مراجعة النظافة، مواد البيع، رؤية الفريق، الإعداد.","After every call and every week.","بعد كل مكالمة وكل أسبوع.","CRM stays current with little effort.","الـ CRM محدّث بمجهود قليل.","Summarise my call and update the CRM")]},
{g:T("Engineering team roles (10x-team plugin)","أدوار فريق الهندسة (Plugin 10x-team)"),items:[
S("10x-team / cto / principal-architect / staff-engineer",T("Tech leadership","قيادة التقنية"),"Strategy, build-vs-buy, architecture, cross-team standards — orchestrated end-to-end.","الاستراتيجية، نبني ولا نشتري، المعمارية، المعايير — بتنسيق كامل.","Starting a new system or a major technical decision.","بداية نظام جديد أو قرار تقني كبير.","Senior-level thinking before code.","تفكير بمستوى خبير قبل الكود.","Design the architecture for our mini-ERP"),
S("senior-engineer / sde / qa-engineer / dba",T("Software development","تطوير البرمجيات"),"Implementation, code review, tests, database design and query tuning.","التنفيذ، مراجعة الكود، الاختبارات، تصميم قواعد البيانات وتحسين الاستعلامات.","Hands-on building and fixing.","البناء والتصليح العملي.","Production-quality code.","كود بجودة إنتاجية.","Write tests for the posting engine"),
S("security-engineer / sre / devops-engineer",T("Security · Operations","الأمان · التشغيل"),"Threat models, hardening, monitoring, CI/CD and deployment.","نماذج التهديد، التحصين، المراقبة، CI/CD والنشر.","Before go-live and for incidents.","قبل الإطلاق ووقت الحوادث.","Secure, reliable systems.","أنظمة آمنة وموثوقة.","Threat-model our MCP server"),
S("product-manager / engineering-manager / init-project / commit",T("Product · Delivery","المنتج · التسليم"),"Requirements, prioritisation, sprint planning, project setup and commits.","المتطلبات، الأولويات، تخطيط السبرنت، إعداد المشروع والـ commits.","Planning what to build and shipping it.","تخطيط اللي هنبنيه وتسليمه.","Clear scope and steady delivery.","نطاق واضح وتسليم ثابت.","Write user stories for the expense app"),
S("codex: code / plan · validate",T("Review","المراجعة"),"Sends plans or diffs for a second-opinion review; scores findings by severity.","بيبعت الخطط أو التعديلات لمراجعة تانية ويقيّم الملاحظات بالخطورة.","Before merging important changes.","قبل دمج تعديلات مهمة.","Catches blind spots.","بيمسك النقاط العمياء.","/validate this plan")]},
{g:T("Analytics & experimentation","التحليلات والتجارب"),items:[
S("analytics-diagnostic-method / traffic-change-diagnosis / anomaly-detection-time-series",T("Data · Marketing","البيانات · التسويق"),"Structured method to explain metric changes and detect real anomalies.","طريقة منظمة لتفسير تغيّر المؤشرات وكشف الشذوذ الحقيقي.","'Why did X drop?'","'ليه X نزل؟'","Separates signal from noise.","بيفصل الإشارة عن الضوضاء.","Why did traffic drop last week?"),
S("experiment-result-reader / bayesian-experiment-reader / sequential-monitoring",T("Product · Growth","المنتج · النمو"),"Reads A/B tests honestly: lift, sample size, posteriors, safe peeking.","بيقرا تجارب A/B بأمانة: الرفع، حجم العينة، الاحتمالات، المتابعة الآمنة.","Deciding to ship a variant.","قرار إطلاق نسخة.","No false wins.","مفيش مكاسب وهمية.","Is variant B really better?"),
S("causal-dag-builder / causal-evidence-checklist / causal-query-classifier",T("Research · Strategy","البحث · الاستراتيجية"),"Tests whether X really caused Y before acting.","بيختبر هل X فعلاً سبّب Y قبل التصرف.","Before rollbacks or big bets on observational data.","قبل التراجع أو الرهانات الكبيرة على بيانات ملاحظة.","Prevents correlation mistakes.","بيمنع أخطاء الارتباط.","Did the price change cause the churn?"),
S("channel-and-funnel-quality / metric-context-and-benchmarks / analytics-profile-setup / event-schema-author",T("Marketing · Product","التسويق · المنتج"),"Channel quality, metric benchmarks, business profile and event tracking schema.","جودة القنوات، معايير المؤشرات، ملف البيزنس، ومخطط تتبع الأحداث.","Setting up and judging analytics.","إعداد وتقييم التحليلات.","Right benchmarks for your model.","معايير صح لنموذجك.","Is a 3% conversion rate good for us?")]},
{g:T("Design, docs & creative tools","التصميم والمستندات والأدوات الإبداعية"),items:[
S("figma (12 skills)",T("Design · Product","التصميم · المنتج"),"Design-to-code, generate designs and libraries, diagrams, FigJam, slides, motion, shaders, SwiftUI, Code Connect.","من التصميم للكود، توليد التصاميم والمكتبات، المخططات، FigJam، الشرائح، الحركة، SwiftUI، Code Connect.","Teams working in Figma.","الفرق اللي شغالة على Figma.","Design and code stay in sync.","التصميم والكود متزامنين.","Implement this Figma screen"),
S("pdf-reading / file-reading",T("All fields","كل المجالات"),"Reads any uploaded file the right way: PDFs, spreadsheets, archives, images.","بيقرا أي ملف مرفوع بالطريقة الصح: PDF وجداول وأرشيفات وصور.","Large or complex uploads.","الملفات الكبيرة أو المعقدة.","Accurate extraction without missing parts.","استخراج دقيق من غير ما يفوّت.","Extract the tables from this annual report"),
S("product-self-knowledge",T("All fields","كل المجالات"),"Checks facts about Anthropic products before answering.","بيتحقق من معلومات منتجات Anthropic قبل الإجابة.","Questions on plans, API, Claude Code.","أسئلة عن الخطط والـ API و Claude Code.","Up-to-date product answers.","إجابات محدّثة عن المنتجات.","What does the Team plan include?"),
S("together-images / together-video / together-audio",T("Content creation","صناعة المحتوى"),"Image, video and speech generation via Together AI (with your account).","توليد صور وفيديو وصوت عبر Together AI (بحسابك).","Creative assets beyond text.","مواد إبداعية أكتر من النص.","Full media pipeline.","خط إنتاج وسائط كامل.","Generate a cover image for my course")]},
{g:T("Platforms & infrastructure","المنصات والبنية التحتية"),items:[
S("spice (Spice.ai, 15 skills)",T("Data engineering","هندسة البيانات"),"Federated SQL, data connectors, acceleration, caching, search, AI and cloud management.","SQL موزّع، موصّلات بيانات، تسريع، كاش، بحث، AI وإدارة سحابية.","Querying many data sources in one place.","الاستعلام من مصادر بيانات كتير في مكان واحد.","Fast answers across systems.","إجابات سريعة عبر الأنظمة.","Connect Postgres and S3 in Spice"),
S("together (Together AI, 12 skills)",T("AI engineering","هندسة الـ AI"),"Chat completions, embeddings, fine-tuning, batch inference, evaluations, GPU clusters, sandboxes.","المحادثة، الـ Embeddings، الضبط الدقيق، الاستدلال الدفعي، التقييم، عناقيد GPU، البيئات المعزولة.","Building with open models.","البناء بالنماذج المفتوحة.","Full open-model stack.","منظومة نماذج مفتوحة كاملة.","Create embeddings for our policy docs"),
S("cowork-plugin-management: create / customize",T("All fields","كل المجالات"),"Create a new plugin or tailor an existing one to your tools.","بيعمل Plugin جديد أو يكيّف واحد موجود على أدواتك.","Packaging your team's workflow.","تغليف سير عمل فريقك.","Your whole method in one install.","طريقتك كلها في تثبيت واحد.","Create a plugin for our finance team")]}
);
