const S=(n,f,d,da,w,wa,v,va,tr)=>({n,f,d:T(d,da),w:T(w,wa),v:T(v,va),tr});
const SKILLS=[
{g:T("Built-in document skills","Skills المستندات الجاهزة"),items:[
S("docx",T("All fields","كل المجالات"),"Creates and edits Word documents: headings, tables, tracked changes, comments, templates.","بيعمل ويعدّل ملفات Word: عناوين وجداول وتتبع تغييرات وتعليقات وقوالب.","When you need a Word file to send, sign or edit with tracked changes.","لما تحتاج ملف Word تبعته أو يتوقّع أو يتعدّل بتتبع التغييرات.","Real .docx in your template — no copy-paste formatting.","ملف .docx حقيقي بقالبك — من غير تنسيق يدوي.","Make this memo a Word doc with our letterhead"),
S("xlsx",T("Finance · Data","المالية · البيانات"),"Builds spreadsheets with real formulas, formatting and charts; cleans and restructures data.","بيبني جداول بمعادلات حقيقية وتنسيق ورسوم؛ وينضّف البيانات.","Models, reconciliations, budgets, any table you'll reuse.","النماذج والمطابقات والموازنات وأي جدول هتستخدمه تاني.","Live formulas, not pasted values — the model stays auditable.","معادلات حية مش قيم ملصوقة — النموذج يفضل قابل للمراجعة.","Turn this CSV into a formatted xlsx with totals"),
S("pptx",T("All fields","كل المجالات"),"Creates and edits PowerPoint decks; reads slides; follows templates.","بيعمل ويعدّل عروض PowerPoint ويقرا الشرائح ويمشي على القوالب.","Board packs, training decks, client proposals.","حزم المجلس، عروض التدريب، عروض العملاء.","Native, editable charts in your corporate template.","رسوم أصلية قابلة للتعديل بقالب شركتك.","Build a 10-slide deck from this report"),
S("pdf",T("All fields","كل المجالات"),"Creates, merges, splits, fills forms, watermarks and extracts tables from PDFs.","بيعمل ويدمج ويقسّم ويملا فورمز ويضيف علامة مائية ويستخرج جداول من PDF.","Bank forms, statements, merging annexes, extracting tables.","نماذج البنوك، الكشوف، دمج الملاحق، استخراج الجداول.","Handles PDF chores in seconds without extra software.","بيخلّص شغل الـ PDF في ثواني من غير برامج إضافية.","Merge these 5 PDFs and add page numbers"),
S("skill-creator",T("All fields","كل المجالات"),"Interviews you and writes a new SKILL.md; tests and improves skills.","بيسألك ويكتب SKILL.md جديدة؛ ويختبر ويحسّن الـ Skills.","When you repeat the same instructions more than a few times a week.","لما بتكرر نفس التعليمات كذا مرة في الأسبوع.","Turns your method into a reusable team asset.","بيحوّل طريقتك لأصل يستخدمه الفريق كله.","Help me build a skill for credit memos")]},
{g:T("Learning, build & creative","التعلّم والبناء والإبداع"),items:[
S("learn",T("Training · Education","التدريب · التعليم"),"Turns Claude into a tutor: diagnoses your level, one step and one question per turn, worked examples, visuals, quizzes and flashcards.","بيحوّل Claude لمعلّم: يشخّص مستواك، خطوة وسؤال في كل رد، أمثلة محلولة، رسوم، اختبارات وكروت.","When you want to understand a concept (DCF, MCP, IFRS 9) — not just get an answer.","لما عايز تفهم مفهوم (DCF، MCP، IFRS 9) — مش بس تاخد إجابة.","You actually learn the method; on graded work it teaches instead of writing the submission.","بتتعلم الطريقة فعلاً؛ وفي الشغل اللي عليه درجات بيعلّم بدل ما يكتب.","/learn Teach me WACC from scratch and quiz me"),
S("web-artifacts-builder",T("Product · Tech","المنتجات · التقنية"),"Builds multi-component web artifacts with React 18, TypeScript, Tailwind and shadcn/ui, bundled into one HTML file.","بيبني Artifacts ويب متعددة المكونات بـ React 18 و TypeScript و Tailwind و shadcn/ui في ملف HTML واحد.","When a simple artifact isn't enough: LMS with many pages, mini-ERP UI, dashboard suites with state and routing.","لما الـ Artifact البسيط ميكفيش: منصة تعليم بصفحات كتير، واجهة Mini-ERP، داشبوردات بحالة وتنقل.","Professional components and structure, still shareable as a single file.","مكونات وهيكلة احترافية ولسه بتتشارك كملف واحد.","/web-artifacts-builder Build a course LMS from this spec"),
S("import-memory",T("All fields","كل المجالات"),"Imports a memory export from ChatGPT, Gemini or another assistant into Claude's memory — as data, additively, after showing you a plan.","بيستورد ذاكرتك من ChatGPT أو Gemini أو مساعد تاني لذاكرة Claude — كبيانات وبالإضافة بس وبعد ما يعرض الخطة.","When you switch to Claude and want it to know your work, projects and people.","لما تنقل لـ Claude وعايزه يعرف شغلك ومشاريعك والناس.","Continuity from day one; sensitive categories and instruction-like text are skipped.","استمرارية من أول يوم؛ والفئات الحساسة والنصوص اللي شكلها أوامر بتتشال.","/import-memory (paste your export)"),
S("frontend-design",T("Marketing · Product","التسويق · المنتجات"),"Gives web pages a distinctive, intentional design: palette, typography, layout.","بيدّي صفحات الويب تصميم مميز ومقصود: ألوان وخطوط وتخطيط.","Landing pages, course sites, dashboards that must look premium.","صفحات الهبوط ومواقع الكورسات والداشبوردات اللي لازم تبان فخمة.","Avoids the generic 'AI look'; on-brand from the first draft.","بيبعد عن 'شكل الـ AI' العام؛ وعلى البراند من أول مسودة.","Design a landing page for my course"),
S("canvas-design",T("Marketing · Content","التسويق · المحتوى"),"Creates original posters and static visuals as PNG/PDF from a design philosophy.","بيعمل بوسترات وتصاميم ثابتة أصلية PNG/PDF من فكرة تصميمية.","Event posters, covers, certificates, social visuals.","بوسترات الفعاليات، الأغلفة، الشهادات، صور السوشيال.","Original art you can print or post, no stock look.","تصميم أصلي تطبعه أو تنشره من غير شكل الصور الجاهزة.","Make a poster for my AI finance workshop"),
S("docs",T("All fields","كل المجالات"),"Creates editable Claude Docs people share and comment on; exports to Word/PDF.","بيعمل Claude Docs قابلة للتعديل والتعليق؛ وتتصدّر Word/PDF.","Policies, guides, proposals you'll keep and collaborate on.","السياسات والأدلة والعروض اللي هتحتفظ بيها وتشتغل عليها مع غيرك.","One live link instead of file versions by email.","لينك حي واحد بدل نسخ ملفات على الإيميل.","Write our onboarding guide as a doc"),
S("mcp-builder",T("Tech · Integration","التقنية · التكامل"),"Guides building MCP servers in Python or TypeScript to connect Claude to an API.","بيرشدك تبني MCP server بـ Python أو TypeScript توصّل Claude بـ API.","When Claude must read your ERP, CRM or database safely.","لما Claude لازم يقرا الـ ERP أو CRM أو قاعدة بياناتك بأمان.","One connector works across chat, Cowork and Claude Code.","Connector واحد بيشتغل في الشات و Cowork و Claude Code.","Build an MCP server for our ERP")]},
{g:T("Finance & accounting","المالية والمحاسبة"),items:[
S("finance:variance-analysis",T("FP&A","FP&A"),"Decomposes variances into price, volume, mix and FX with waterfall and narrative.","بيفكّك الانحرافات لسعر وكمية ومزيج وصرف برسم شلال وتعليق.","Monthly/quarterly budget vs actual, board commentary.","موازنة مقابل فعلي شهري/ربع سنوي وتعليق المجلس.","Driver-based explanations instead of 'higher costs'.","شرح بالأسباب بدل 'التكاليف زادت'.","Explain why opex is 12% over budget"),
S("finance:journal-entry",T("Accounting","المحاسبة"),"Prepares journal entries with support for accruals, depreciation, revenue recognition.","بيجهّز قيود اليومية بالمستندات للمستحقات والإهلاك والإيراد.","Month-end accruals and adjustments.","مستحقات وتسويات آخر الشهر.","Consistent, documented entries ready for review.","قيود متسقة وموثقة جاهزة للمراجعة.","Book the September payroll accrual"),
S("finance:reconciliation",T("Accounting","المحاسبة"),"Reconciles GL to bank, subledger or third-party data and classifies reconciling items.","بيطابق الأستاذ العام مع البنك أو الدفاتر المساعدة ويصنّف البنود.","Bank recs, intercompany, subledger tie-outs.","مطابقات البنوك والشركات الشقيقة والدفاتر المساعدة.","Hours to minutes, with a clear exceptions list.","من ساعات لدقايق بقائمة استثناءات واضحة.","Reconcile the CIB account for September"),
S("finance:financial-statements",T("Accounting · Reporting","المحاسبة · التقارير"),"Generates IS, BS and CF with period comparisons and variance flags.","بيطلّع القوائم التلاتة بمقارنات وتنبيهات.","Monthly/quarterly reporting packs.","حزم التقارير الشهرية والربع سنوية.","Comparable statements with flagged movements.","قوائم قابلة للمقارنة بتعليم التحركات.","Prepare Q3 statements vs Q2"),
S("finance:close-management",T("Accounting","المحاسبة"),"Sequences close tasks, dependencies and status.","بيرتب مهام الإقفال والاعتماديات والحالة.","Planning and tracking month-end.","تخطيط ومتابعة إقفال الشهر.","Shorter, predictable closes.","إقفال أقصر ومتوقع.","Build our 5-day close calendar"),
S("finance:audit-support / sox-testing",T("Audit · Risk","المراجعة · المخاطر"),"Control testing, sample selection, workpapers, deficiency classification.","اختبار الضوابط، العينات، أوراق العمل، تصنيف القصور.","Internal audit and SOX-style testing.","المراجعة الداخلية واختبارات الضوابط.","Audit-ready documentation with consistent method.","توثيق جاهز للمراجعة بطريقة ثابتة.","Select a sample for the AP approval control"),
S("dcf-model / lbo-model / 3-statement-model / comps-analysis",T("Valuation · IB","التقييم · بنوك الاستثمار"),"Builds institutional-grade valuation models in Excel.","بيبني نماذج تقييم احترافية في Excel.","Valuations, deals, investment committee work.","التقييمات والصفقات ولجان الاستثمار.","Standard structure that reviewers trust.","هيكل قياسي بيثق فيه المراجعين.","Build a DCF for this company"),
S("audit-xls",T("Finance · Audit","المالية · المراجعة"),"Audits a spreadsheet for formula errors and model integrity.","بيراجع ملف Excel على أخطاء المعادلات وسلامة النموذج.","Before any model goes to the board or a client.","قبل ما أي نموذج يروح للمجلس أو العميل.","Catches #REF!, hard-codes and imbalance early.","بيمسك #REF! والأرقام اليدوية وعدم التوازن بدري.","QA this model before the board"),
S("valuation-reviewer: ic-memo / returns-analysis / portfolio-monitoring",T("Private equity","الملكية الخاصة"),"IC memos, IRR/MOIC sensitivities, portfolio KPI tracking.","مذكرات لجنة الاستثمار، حساسية IRR/MOIC، متابعة المحفظة.","Deal approval and portfolio reviews.","اعتماد الصفقات ومراجعة المحفظة.","Committee-ready materials faster.","مواد جاهزة للجنة أسرع.","Write the IC memo for this deal"),
S("file-dashboard-analyzer (Sara)",T("All fields","كل المجالات"),"Any uploaded file → Arabic interactive dashboard with executive summary.","أي ملف مرفوع ← داشبورد عربي تفاعلي بملخص تنفيذي.","When someone sends you data and wants the story fast.","لما حد يبعتلك بيانات وعايز القصة بسرعة.","Instant Arabic insight with charts and details.","رؤية عربي فورية برسوم وتفاصيل.","حلل الملف ده واعمل داشبورد")]},
{g:T("Data","البيانات"),items:[
S("data:analyze / explore-data",T("Data · All fields","البيانات · كل المجالات"),"From quick lookups to full analyses; profiles data quality.","من البحث السريع للتحليل الكامل؛ ويفحص جودة البيانات.","New dataset, 'why did X change?', quick metrics.","بيانات جديدة، 'ليه X اتغير؟'، مؤشرات سريعة.","Checks quality before conclusions.","بيفحص الجودة قبل الاستنتاج.","Profile this customer table"),
S("data:build-dashboard / create-viz / data-visualization",T("Data · Reporting","البيانات · التقارير"),"Interactive HTML dashboards and publication-quality charts.","داشبوردات HTML تفاعلية ورسوم بجودة نشر.","KPI packs, management dashboards.","حزم المؤشرات وداشبوردات الإدارة.","Shareable, self-contained dashboards.","داشبوردات مستقلة سهلة المشاركة.","Build a KPI dashboard from this data"),
S("data:statistical-analysis",T("Data · Research","البيانات · البحث"),"Descriptive stats, trends, outliers, hypothesis tests.","إحصاء وصفي واتجاهات وقيم شاذة واختبارات فروض.","Is a difference real or noise?","الفرق حقيقي ولا صدفة؟","Evidence-based decisions.","قرارات مبنية على دليل.","Is the difference between branches significant?"),
S("data:write-query / sql-queries",T("Data · Tech","البيانات · التقنية"),"Writes correct SQL for your warehouse dialect.","بيكتب SQL صحيح حسب قاعدة بياناتك.","Pulling data without waiting for IT.","سحب البيانات من غير ما تستنى الـ IT.","Correct, optimised queries.","استعلامات صحيحة ومحسّنة.","Write SQL for monthly revenue by region")]},
{g:T("HR, sales, marketing & design","الموارد البشرية والمبيعات والتسويق والتصميم"),items:[
S("human-resources: draft-offer / interview-prep / onboarding / performance-review / comp-analysis / org-planning / people-report / policy-lookup / recruiting-pipeline",T("HR","الموارد البشرية"),"The full HR cycle: offers, interviews, onboarding, reviews, compensation, org design, reports, policy answers.","دورة HR كاملة: العروض، المقابلات، التهيئة، التقييم، التعويضات، الهيكل، التقارير، السياسات.","Any recurring HR task.","أي مهمة HR متكررة.","Structured, fair and consistent people processes.","عمليات موارد بشرية منظمة وعادلة وثابتة.","Create an interview plan for a senior accountant"),
S("sales: account-research / call-prep / draft-outreach / pipeline-review / forecast / handle-objection / close-plan …",T("Sales","المبيعات"),"Prospect research, call briefs, outreach, pipeline health, forecasts, objections, close plans.","بحث العملاء، تحضير المكالمات، التواصل، صحة الـ Pipeline، التوقعات، الاعتراضات، خطط الإغلاق.","Daily selling and weekly pipeline reviews.","البيع اليومي ومراجعة الـ Pipeline الأسبوعية.","More time selling, less time preparing.","وقت أكتر للبيع ووقت أقل للتحضير.","Prep me for my call with a Saudi distributor"),
S("marketing: campaign-plan / content-creation / draft-content / email-sequence / seo-audit / competitive-brief / brand-review / performance-report",T("Marketing","التسويق"),"Campaigns, content, email flows, SEO, competitor briefs, brand checks, reports.","حملات، محتوى، سلاسل إيميل، SEO، تحليل منافسين، مراجعة البراند، تقارير.","Launches, content calendars, performance reviews.","الإطلاقات وخطط المحتوى ومراجعات الأداء.","Channel-ready content on brand.","محتوى جاهز لكل قناة وعلى البراند.","Plan a launch campaign for my course"),
S("design: user-research / ux-copy / design-critique / accessibility-review / design-system / design-handoff",T("Design · Product","التصميم · المنتجات"),"Research plans, UX writing, critique, accessibility audits, handoff specs.","خطط بحث، كتابة واجهات، نقد تصميم، مراجعة إتاحة، مواصفات تسليم.","Before launching any app, site or dashboard.","قبل إطلاق أي تطبيق أو موقع أو داشبورد.","Usable, accessible products.","منتجات سهلة الاستخدام ومتاحة للكل.","Critique this dashboard design")]},
{g:T("Productivity, content & Sara's custom skills","الإنتاجية والمحتوى و Skills سارة"),items:[
S("academic-research-general (Sara)",T("Academic","الأكاديمي"),"Full Arabic/English academic research in any field with real references (APA + MLA).","بحث أكاديمي كامل عربي/إنجليزي بمراجع حقيقية (APA + MLA).","Papers, theses, conference submissions.","الأبحاث والرسائل وأوراق المؤتمرات.","Complete structure with verifiable references.","هيكل كامل بمراجع قابلة للتحقق.","اعمل بحث أكاديمي عن التحوط من مخاطر سعر الصرف"),
S("academic-research-paper (Sara)",T("Academic · Management","الأكاديمي · الإدارة"),"Organisational-behaviour and management papers: variables, hypotheses, methodology, APA.","أوراق السلوك التنظيمي والإدارة: متغيرات وفروض ومنهجية و APA.","Management research with hypotheses.","أبحاث إدارة بفروض.","Clear variables and research gap.","متغيرات وفجوة بحثية واضحة.","اكتب ورقة بحثية عن القيادة التحويلية"),
S("youtube-script-writer (Sara)",T("Content creation","صناعة المحتوى"),"20–40 minute YouTube scripts in natural Egyptian Arabic.","سكريبتات يوتيوب 20–40 دقيقة بالعامية المصرية.","Long-form educational or story videos.","فيديوهات تعليمية أو قصصية طويلة.","Hooks, chapters and CTAs in your voice.","Hooks وفصول ودعوات بصوتك.","عاوز فيديو عن Claude للمحاسبين"),
S("productivity: task-management / memory-management / start / update",T("All fields","كل المجالات"),"Task lists, workplace memory and daily sync.","قوائم المهام وذاكرة العمل والمزامنة اليومية.","Keeping commitments and context in one place.","تجميع الالتزامات والسياق في مكان واحد.","Nothing falls through the cracks.","مفيش حاجة بتضيع.","Add these 5 tasks and show my week"),
S("google-workspace",T("All fields","كل المجالات"),"Creates or edits Google Docs, Sheets and Slides in your Drive.","بيعمل أو يعدّل Google Docs و Sheets و Slides على الدرايف.","When your team lives in Google Workspace.","لما فريقك شغال على Google Workspace.","Edits in place — no download/upload loop.","تعديل في المكان — من غير تنزيل ورفع.","Update the Google Sheet budget"),
S("morning",T("Leadership","القيادة"),"Builds your morning brief or schedules it on weekdays.","بيعمل ملخص الصبح أو يجدوله أيام الشغل.","Starting the day with priorities.","تبدأ يومك بالأولويات.","A focused start every day.","بداية مركزة كل يوم.","/morning")]}
];
