// ===== PROMPT ENGINEERING STUDIO =====
const UX3={studio:T("Prompt engineering studio","استوديو هندسة البرومبت"),lib:T("Master prompt library","مكتبة البرومبتات الماستر"),labcases:T("Lab cases + data","حالات المعمل + البيانات")};
let SU=Object.assign({goal:'',role:'',task:'',context:'',reasoning:'',stop:'',output:'',aud:'mgmt',tone:'pro',lang:'en',len:'med',fmt:'table',tech:['xml','ask','verify'],example:'',prev:'',busy:false},ST.studio||{});
const SU_AUD={ceo:T('CEO / board','المدير التنفيذي / المجلس'),mgmt:T('Management team','فريق الإدارة'),team:T('My team','فريقي'),client:T('Client','العميل'),learner:T('Learners','المتدربين')};
const SU_TONE={pro:T('Professional','احترافي'),concise:T('Concise','مختصر'),warm:T('Warm','دافي'),formal:T('Formal','رسمي')};
const SU_LANG={en:T('English','إنجليزي'),ar:T('Arabic (Egyptian)','عربي (مصري)'),bi:T('Bilingual','ثنائي اللغة')};
const SU_LEN={short:T('Short','قصير'),med:T('Medium','متوسط'),long:T('Detailed','تفصيلي')};
const SU_FMT={table:T('Table','جدول'),memo:T('Memo','مذكرة'),xlsx:T('Excel file','ملف Excel'),deck:T('Slides','شرائح'),json:T('JSON','JSON'),email:T('Email','إيميل')};
const SU_TECH=[['xml',T('XML structure','هيكلة XML')],['ask',T('Ask first','اسأل الأول')],['verify',T('Verify numbers','راجع الأرقام')],['cot',T('Step-by-step reasoning','تفكير خطوة بخطوة')],['fewshot',T('Few-shot example','مثال توضيحي')],['critique',T('Self-critique','نقد ذاتي')],['chain',T('Prompt chaining','تسلسل البرومبت')],['json',T('Structured JSON','JSON منظم')],['ground',T('Answer only from sources','من المصادر بس')],['human',T('Human review flags','علامات مراجعة بشرية')]];
function suPrompt(){const lines=[];const t=new Set(SU.tech);const lang={en:'English',ar:'Arabic (Egyptian dialect for explanations)',bi:'Arabic and English side by side'}[SU.lang];const len={short:'under 150 words',med:'about 300–500 words',long:'detailed, with sections'}[SU.len];
const out=`${SU.output||L(SU_FMT[SU.fmt])} · ${lang} · ${len} · audience: ${SU_AUD[SU.aud].en} · tone: ${SU_TONE[SU.tone].en.toLowerCase()}${t.has('json')?' · return valid JSON only':''}`;
const b=(tag,v)=>t.has('xml')?`<${tag}>\n${v}\n</${tag}>`:`${tag.toUpperCase()}: ${v}`;
lines.push(b('role',SU.role||'[Expert role, seniority, market]'));lines.push(b('task',SU.task||SU.goal||'[One clear deliverable]'));lines.push(b('context',SU.context||'- Files/data: [..]\n- Period, currency: [..]\n- Constraints: [..]'));lines.push(b('reasoning',SU.reasoning||'[The decision this supports]'));lines.push(b('stop_when',SU.stop||'- [What done looks like]'));lines.push(b('output_format',out));
if(t.has('fewshot'))lines.push(b('example',SU.example||'[Paste one example of excellent output]'));
const c=[];if(t.has('ask'))c.push('Before starting, restate the task and ask up to 3 clarifying questions.');if(t.has('ground'))c.push('Answer only from the provided sources; if missing, write "Not in the source".');if(t.has('cot'))c.push('Think step by step in <thinking>, then give the final answer in <answer>.');if(t.has('chain'))c.push('Work in stages: 1) extract 2) analyse 3) draft 4) review — show each stage briefly.');if(t.has('verify'))c.push('Never invent numbers; write [MISSING]. Check every number against its source before finishing.');if(t.has('critique'))c.push('Before finalising, critique your draft against the stop conditions and fix gaps.');if(t.has('human'))c.push('Mark anything that needs human review and end with the 3 next steps.');
if(c.length)lines.push(b('controls','- '+c.join('\n- ')));return lines.join('\n')}
function suTokens(p){const ar=(p.match(/[\u0600-\u06FF]/g)||[]).length;return Math.round((p.length-ar)/4+ar/2.2)}
function suScore(){const items=[['role',SU.role,15,T('Role names expertise + market','الدور فيه الخبرة والسوق')],['task',SU.task||SU.goal,10,T('Task is one clear deliverable','المهمة مخرج واحد واضح')],['context',SU.context,40,T('Context has facts, period, currency','السياق فيه حقايق وفترة وعملة')],['reasoning',SU.reasoning,10,T('Reasoning names the decision','المنطق بيذكر القرار')],['stop',SU.stop,20,T('Stop conditions as a checklist','شروط التوقف كقائمة')],['output',SU.output||SU.fmt,3,T('Output format specified','شكل المخرج محدد')]];
const el=items.map(([k,v,min,lab])=>{const len=(v||'').trim().length;const p=Math.min(100,Math.round(100*len/Math.max(min*2.5,30)));return {k,p:k==='output'?100:p,lab}});
const t=new Set(SU.tech);let tech=0;['ask','verify','xml'].forEach(x=>{if(t.has(x))tech+=10});['cot','critique','ground','human','fewshot'].forEach(x=>{if(t.has(x))tech+=4});
const num=/\d/.test(SU.context+SU.stop)?8:0;const base=el.reduce((a,b)=>a+b.p,0)/el.length;const score=Math.min(100,Math.round(base*0.62+tech*0.5+num));
const tips=[];el.forEach(e=>{if(e.p<60)tips.push(e.lab)});if(!num)tips.push(T('Add concrete numbers or limits','ضيف أرقام أو حدود محددة'));if(!t.has('verify'))tips.push(T('Turn on "Verify numbers"','فعّل "راجع الأرقام"'));if(!t.has('ask'))tips.push(T('Turn on "Ask first"','فعّل "اسأل الأول"'));if(SU.fmt!=='json'&&t.has('json'))tips.push(T('Set format to JSON','خلي الشكل JSON'));
return {score,el,tips}}
function ring(v){const r=52,c=2*Math.PI*r,col=v>=80?'var(--green)':v>=55?'var(--gold)':'var(--red)';return `<svg viewBox="0 0 130 130" width="130" height="130"><circle cx="65" cy="65" r="${r}" fill="none" stroke="var(--panel2)" stroke-width="12"/><circle cx="65" cy="65" r="${r}" fill="none" stroke="${col}" stroke-width="12" stroke-linecap="round" stroke-dasharray="${c*v/100} ${c}" transform="rotate(-90 65 65)"/><text x="65" y="72" text-anchor="middle" font-size="30" font-weight="700" fill="var(--ink)">${v}</text></svg>`}
function suDash(p){const ar=LANG==='ar';const s=suScore();return `<div class="stu-dash"><div class="ringbox">${ring(s.score)}<div class="k">${ar?'درجة الجودة':'Quality score'}</div></div><div class="kpis"><div><b>${suTokens(p)}</b>${ar?'توكن تقريباً':'≈ tokens'}</div><div><b>${SU.tech.length}</b>${ar?'تقنيات':'techniques'}</div><div><b>${s.el.filter(e=>e.p>=60).length}/6</b>${ar?'عناصر قوية':'strong blocks'}</div></div>
<div class="bars">${s.el.map((e,k)=>`<div class="bar2"><span>${['Role','Task','Context','Reasoning','Stop','Output'][k]}</span><i><em style="width:${e.p}%;background:${e.p>=60?'var(--green)':e.p>=30?'var(--gold)':'var(--red)'}"></em></i></div>`).join('')}</div>
${s.tips.length?`<div class="tips2"><b>${ar?'اقتراحات':'Suggestions'}</b><ul>${s.tips.slice(0,5).map(t=>`<li>${L(t)}</li>`).join('')}</ul></div>`:`<div class="tips2 ok">✓ ${ar?'برومبت قوي — جاهز للاستخدام':'Strong prompt — ready to use'}</div>`}</div>`}
function vStudio(){crumb(L(UX3.studio));const ar=LANG==='ar';const p=suPrompt();const s=suScore();const i=PSTORE.push(p)-1;window._sui=i;
const sel=(id,obj,v)=>`<select data-su="${id}">${Object.keys(obj).map(k=>`<option value="${k}" ${v===k?'selected':''}>${L(obj[k])}</option>`).join('')}</select>`;
const F=[['role',T('Role','الدور'),T('Senior FP&A analyst at an Egyptian retailer','محلل FP&A أول في شركة تجزئة مصرية')],['task',T('Task','المهمة'),T('Build the September variance pack','اعمل حزمة انحرافات سبتمبر')],['context',T('Context','السياق'),T('Files, numbers, period, currency, constraints','الملفات والأرقام والفترة والعملة والقيود')],['reasoning',T('Reasoning','المنطق'),T('The decision this supports','القرار اللي بيدعمه')],['stop',T('Stop conditions','شروط التوقف'),T('- checklist item 1\n- checklist item 2','- بند 1\n- بند 2')],['output',T('Output details (optional)','تفاصيل المخرج (اختياري)'),T('Columns, sheets, sections…','الأعمدة والشيتات والأجزاء…')]];
return `<h1>🎛 ${L(UX3.studio)}</h1><p class="lede">${ar?'لوحة تفاعلية تبني وتقيس وتحسّن البرومبت: اكتب هدفك، ولّد برومبت ماستر، ظبّط التقنيات والجمهور، وشوف الدرجة والتوكنز والتحسينات لحظياً.':'An interactive dashboard to build, measure and enhance prompts: write your goal, generate a master prompt, tune techniques and audience, and watch the score, tokens and suggestions live.'}</p>
<div class="stu-goal"><input class="search" data-su="goal" value="${esc(SU.goal)}" placeholder="${ar?'هدفك في جملة… مثلاً: تحليل انحرافات سبتمبر للمجلس':'Your goal in one line… e.g. September variance analysis for the board'}"><button class="dlbtn" data-sugo="gen" ${SU.busy?'disabled':''}>✨ ${ar?'ولّد برومبت ماستر':'Generate master prompt'}</button><button class="tbtn" data-sugo="enh" ${SU.busy?'disabled':''}>🚀 ${ar?'حسّن بـ Claude':'Enhance with Claude'}</button></div>
<div class="stu">
<div class="stu-l">${F.map(f=>`<label class="pbf"><b>${L(f[1])}</b><textarea data-su="${f[0]}" rows="${f[0]==='context'||f[0]==='stop'?4:2}" placeholder="${esc(L(f[2]))}" dir="auto">${esc(SU[f[0]])}</textarea></label>`).join('')}
<div class="stu-sel"><label>${ar?'الجمهور':'Audience'}${sel('aud',SU_AUD,SU.aud)}</label><label>${ar?'النبرة':'Tone'}${sel('tone',SU_TONE,SU.tone)}</label><label>${ar?'اللغة':'Language'}${sel('lang',SU_LANG,SU.lang)}</label><label>${ar?'الطول':'Length'}${sel('len',SU_LEN,SU.len)}</label><label>${ar?'الشكل':'Format'}${sel('fmt',SU_FMT,SU.fmt)}</label></div>
<b>${ar?'التقنيات':'Techniques'}</b><div class="chips">${SU_TECH.map(t=>`<button class="chip ${SU.tech.includes(t[0])?'on':''}" data-sutech="${t[0]}">${L(t[1])}</button>`).join('')}</div>
${SU.tech.includes('fewshot')?`<label class="pbf"><b>${ar?'المثال':'Example'}</b><textarea data-su="example" rows="3" dir="auto">${esc(SU.example)}</textarea></label>`:''}</div>
<div class="stu-r">${suDash(p)}
<div class="prompt"><div class="ph"><h3>${ar?'البرومبت':'Prompt'}${SU.prev?` <button class="tbtn" data-sugo="cmp">${ar?'قارن بالسابق':'Compare'}</button>`:''}</h3><span><button class="copy" data-i="${i}">${L(UI.copy)}</button></span></div><pre id="suout" dir="auto">${esc(p)}</pre></div>
<div id="sucmp"></div>
<div class="row-btns"><button class="dlbtn" data-sugo="save">💾 ${ar?'احفظ':'Save'}</button><button class="tbtn" data-suexp="md">.md</button><button class="tbtn" data-suexp="txt">.txt</button><button class="tbtn" data-suexp="json">.json</button><button class="tbtn" data-sugo="tobuilder">🧪 ${ar?'اختبره ببيانات تجريبية':'Test with dummy data'}</button>${mailBtns('Master prompt',p)}<button class="tbtn" data-sugo="reset">↺</button></div>
<p class="note" id="sunote"></p></div></div>`}
function suGenOffline(){const g=asGuess(SU.goal||'');const ar=LANG==='ar';SU.role=SU.role||(ar?g.role[1]:g.role[0]);SU.task=SU.task||SU.goal;SU.context=SU.context||(ar?'- الملفات/البيانات: [..]\n- الفترة: [..]، العملة: جنيه\n- القيود: [..]':'- Files/data: [..]\n- Period: [..], currency: EGP\n- Constraints: [..]');SU.reasoning=SU.reasoning||(ar?'[القرار اللي هيتاخد بالناتج]':'[Decision the output supports]');SU.stop=SU.stop||(ar?'- كل رقم ليه مصدر\n- [بند 2]\n- [بند 3]':'- Every number traced to a source\n- [item 2]\n- [item 3]');['ask','verify','xml','human'].forEach(x=>{if(!SU.tech.includes(x))SU.tech.push(x)})}
async function suClaude(mode){const sample=await tutorSample();const ar=LANG==='ar';const note=m=>{const n=document.getElementById('sunote');if(n)n.textContent=m};
if(!sample){SU.prev=suPrompt();if(mode==='gen')suGenOffline();else{['ask','verify','critique','human','xml'].forEach(x=>{if(!SU.tech.includes(x))SU.tech.push(x)});if(!/\d/.test(SU.context))SU.context+=(SU.context?'\n':'')+(ar?'- الأرقام/الحدود: [..]':'- Numbers/limits: [..]')}saveSU();render();note(ar?'اتعمل محلياً. التحسين بـ Claude بيشتغل لما المنصة تتفتح جوه Claude.':'Done locally. Claude enhancement works when the platform is opened inside Claude.');return}
SU.busy=true;SU.prev=suPrompt();render();
const ask=mode==='gen'?`Create a master prompt for this goal: "${SU.goal}". Audience: ${SU_AUD[SU.aud].en}. Return ONLY JSON with keys role, task, context, reasoning, stop, output (strings; context and stop as "- " bullet lines). Write values in ${SU.lang==='ar'?'Arabic (Egyptian)':'English'}. Be specific to finance/business in Egypt and the Gulf where relevant; use [brackets] for unknowns.`:`Improve this prompt. Keep the user's intent. Make role specific, context factual with placeholders, reasoning tied to a decision, stop conditions as a checklist, output precise. Return ONLY JSON with keys role, task, context, reasoning, stop, output.\n\n${suPrompt()}`;
try{const {text}=await sample(ask,{cache:false,modelTier:'default'});const j=JSON.parse(text.replace(/```json|```/g,'').trim());['role','task','context','reasoning','stop','output'].forEach(k=>{if(typeof j[k]==='string')SU[k]=j[k]});['ask','verify','xml'].forEach(x=>{if(!SU.tech.includes(x))SU.tech.push(x)})}
catch(e){suGenOffline()}SU.busy=false;saveSU();render()}
function saveSU(){const {busy,...rest}=SU;ST.studio=rest;saveST()}
function studioClick(e){const g=s=>e.target.closest(s);let x;
if(x=g('[data-sutech]')){const t=x.dataset.sutech;SU.tech=SU.tech.includes(t)?SU.tech.filter(y=>y!==t):[...SU.tech,t];saveSU();render();return true}
if(x=g('[data-sugo]')){const a=x.dataset.sugo;if(a==='gen'||a==='enh')suClaude(a);
if(a==='save'){ST.mine.unshift({t:(SU.task||SU.goal||'Prompt').slice(0,80),d:new Date().toISOString().slice(0,10),p:suPrompt()});ST.built++;saveST();addXP(5);const n=document.getElementById('sunote');if(n)n.textContent=LANG==='ar'?'اتحفظ في برومبتاتي.':'Saved to My prompts.'}
if(a==='tobuilder'){stuTab='test';render()}
if(a==='reset'){Object.assign(SU,{goal:'',role:'',task:'',context:'',reasoning:'',stop:'',output:'',example:'',prev:'',tech:['xml','ask','verify']});saveSU();render()}
if(a==='cmp'){const c=document.getElementById('sucmp');if(c)c.innerHTML=c.innerHTML?'':`<div class="cmp2"><div><b>${LANG==='ar'?'قبل':'Before'}</b><pre dir="auto">${esc(SU.prev)}</pre></div><div><b>${LANG==='ar'?'بعد':'After'}</b><pre dir="auto">${esc(suPrompt())}</pre></div></div>`}return true}
if(x=g('[data-suexp]')){const k=x.dataset.suexp;const p=suPrompt();if(k==='json')saveFile('master-prompt.json',JSON.stringify({role:SU.role,task:SU.task||SU.goal,context:SU.context,reasoning:SU.reasoning,stop_when:SU.stop,output_format:SU.output||SU.fmt,techniques:SU.tech,prompt:p},null,2));else saveFile('master-prompt.'+k,k==='md'?'# Master prompt\n\n```\n'+p+'\n```\n':p);return true}
return false}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset&&t.dataset.su&&t.tagName!=='SELECT'){SU[t.dataset.su]=t.value;saveSU();const o=document.getElementById('suout');if(o){const p=suPrompt();o.textContent=p;PSTORE[window._sui]=p;const d=document.querySelector('.stu-dash');if(d)d.outerHTML=suDash(p)}}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset&&t.dataset.su&&t.tagName==='SELECT'){SU[t.dataset.su]=t.value;saveSU();render()}});
// lesson 1.8 in module 1
DAYS[0].units.push({id:"1.8",tag:"advanced",dur:"45",t:T("Prompt engineering studio — generate & enhance","استوديو هندسة البرومبت — ولّد وحسّن"),
body:T(`<p>The studio is an interactive dashboard that turns a one-line goal into a scored master prompt. Use it to practise everything in this module: the six elements, techniques (XML, few-shot, step-by-step, chaining, self-critique), audience and tone, and controls.</p><p><button class="dlbtn" data-go="studio">🎛 Open the studio</button></p><ol><li>Write the goal in one line and click <b>Generate</b>.</li><li>Fill gaps the score highlights (context, numbers, stop conditions).</li><li>Toggle techniques and watch the score and token estimate.</li><li>Click <b>Enhance with Claude</b> and compare before/after.</li><li>Save, export (.md/.txt/.json) or open in the builder to test with dummy data.</li></ol>`,`<p>الاستوديو لوحة تفاعلية بتحوّل هدف في سطر لبرومبت ماستر بدرجة جودة. استخدمه تتمرن على كل الموديول ده: العناصر الستة، التقنيات (XML، الأمثلة، خطوة بخطوة، التسلسل، النقد الذاتي)، الجمهور والنبرة، والضوابط.</p><p><button class="dlbtn" data-go="studio">🎛 افتح الاستوديو</button></p><ol><li>اكتب الهدف في سطر واضغط <b>ولّد</b>.</li><li>املا الفجوات اللي الدرجة بتوريها (السياق، الأرقام، شروط التوقف).</li><li>فعّل التقنيات وشوف الدرجة وتقدير التوكنز.</li><li>اضغط <b>حسّن بـ Claude</b> وقارن قبل/بعد.</li><li>احفظ، صدّر (.md/.txt/.json) أو افتح في الباني تختبر ببيانات تجريبية.</li></ol>`),
steps:T(["Open the studio","Generate from a goal","Fix highlighted gaps","Toggle techniques","Enhance & compare","Save / export / test"],["افتح الاستوديو","ولّد من هدف","صلّح الفجوات المتعلّمة","فعّل التقنيات","حسّن وقارن","احفظ / صدّر / اختبر"]),
tips:T(["Aim for 80+ before using a prompt on real work.","Every technique costs tokens — turn on what the task needs."],["استهدف 80+ قبل ما تستخدم البرومبت في شغل حقيقي.","كل تقنية بتكلّف توكنز — فعّل اللي المهمة محتاجاه بس."]),
cases:[{t:T("From 34 to 88 in five minutes","من 34 لـ 88 في 5 دقايق"),d:T("A credit analyst types 'credit memo for a working-capital facility'; generate + adding covenant limits and stress conditions lifts the score from 34 to 88, and the first output is committee-ready.","محلل ائتمان كتب 'مذكرة ائتمان لتسهيل رأس مال عامل'؛ التوليد وإضافة حدود التعهدات وظروف الضغط رفع الدرجة من 34 لـ 88، وأول ناتج طلع جاهز للجنة.")}],
prompts:[{t:T("Master prompt — improve any prompt","البرومبت الماستر — حسّن أي برومبت"),p:T(MPen("Prompt engineer","Improve the prompt below to score 85+ on role, task, context, reasoning, stop conditions and output","- Prompt: [paste]\n- Audience: [..]\n- Techniques allowed: XML, few-shot, step-by-step, self-critique","A reliable prompt saves review time every month","- All six blocks specific; gaps as [brackets]\n- Controls: ask first, verify numbers, human review flags\n- Token-efficient","Improved prompt in a code block + a short list of what changed and why."),MPar("مهندس برومبت","حسّن البرومبت اللي تحت لدرجة 85+ في الدور والمهمة والسياق والمنطق وشروط التوقف والمخرج","- البرومبت: [الصق]\n- الجمهور: [..]\n- التقنيات المسموحة: XML، أمثلة، خطوة بخطوة، نقد ذاتي","البرومبت الموثوق بيوفّر وقت المراجعة كل شهر","- البلوكات الستة محددة؛ والفجوات بين [أقواس]\n- الضوابط: اسأل الأول، راجع الأرقام، علامات مراجعة بشرية\n- موفّر للتوكنز","البرومبت المحسّن في بلوك + قائمة قصيرة باللي اتغير وليه.")),master:true}],doc:""});
FEAT["1.8"]="Prompt studio (interactive)";CEO["1.8"]=T("A shared studio standardises prompt quality across teams and makes it measurable.","استوديو مشترك بيوحّد جودة البرومبت بين الفرق ويخليها قابلة للقياس.");
