const UX2={path:T("My learning path","مساري التعليمي"),pick:T("Claude feature picker","اختيار أداة Claude"),skb:T("Skill builder","باني الـ Skills"),tour:T("Take the tour","جولة تعريفية")};
// ---------- LEARNING PATH ----------
const PATHQ=[
{k:"role",q:T("What is your role?","إيه دورك؟"),o:[["finance",T("Finance / FP&A / accounting","مالية / FP&A / محاسبة")],["banking",T("Banking / trade finance","بنوك / تمويل تجاري")],["leader",T("CEO / manager","مدير تنفيذي / مدير")],["hr",T("HR","موارد بشرية")],["sales",T("Sales / marketing","مبيعات / تسويق")],["creator",T("Trainer / content creator","مدرّب / صانع محتوى")],["academic",T("Researcher / academic","باحث / أكاديمي")],["builder",T("Developer / builder","مطوّر / باني أدوات")]]},
{k:"level",q:T("Your Claude level today?","مستواك في Claude دلوقتي؟"),o:[["beg",T("Beginner","مبتدئ")],["int",T("Intermediate","متوسط")],["adv",T("Advanced","متقدم")]]},
{k:"goal",q:T("Main goal?","هدفك الأساسي؟"),o:[["write",T("Better documents & reports","مستندات وتقارير أحسن")],["analyse",T("Analyse data & Excel","تحليل بيانات و Excel")],["automate",T("Automate recurring work","أتمتة الشغل المتكرر")],["build",T("Build tools, apps & agents","بناء أدوات وتطبيقات ووكلاء")],["lead",T("Lead AI adoption & governance","قيادة التبني والحوكمة")]]},
{k:"time",q:T("Time per week?","وقتك في الأسبوع؟"),o:[["2",T("~2 hours","~ساعتين")],["5",T("~5 hours","~5 ساعات")],["10",T("10+ hours","10 ساعات أو أكتر")]]}];
let PA=ST.pathAns||{};
function buildPath(a){const L0=['1.1','1.3','1.4','1.6','2.2','2.4'];let core=[...L0];const add=x=>x.forEach(i=>{if(!core.includes(i))core.push(i)});
const byGoal={write:['3.2','2.5','3.1','4.1'],analyse:['5.1','2.1','3.1','4.3'],automate:['6.1','6.2','4.2','4.3','5.4'],build:['3.1','7.1','7.2','7.3','4.3'],lead:['1.7','9.1','9.2','9.3','9.4','8.1']};
const byRole={finance:['5.1','5.2','4.2'],banking:['4.1','5.1','9.1'],leader:['1.7','3.2','9.4'],hr:['3.2','4.1','9.3'],sales:['4.3','5.3','3.3'],creator:['3.3','2.5','3.1'],academic:['2.1','4.1','9.3'],builder:['7.1','7.2','7.3','4.3']};
add(byGoal[a.goal]||[]);add(byRole[a.role]||[]);if(a.level==='beg')add(['1.2','1.5','2.1','2.3']);if(a.level!=='beg')core=core.filter(i=>!['1.1'].includes(i)||a.level==='int');add(['9.2']);
const all=DAYS.flatMap(d=>d.units.map(u=>u.id));core=core.filter(i=>all.includes(i));
const labMap={finance:['Finance'],banking:['Banking','Trade finance'],leader:['CEO','Finance'],hr:['HR'],sales:['Sales','Marketing'],creator:['Content','Marketing'],academic:['Audit','Finance'],builder:['Sales','Finance']};
const labs=LAB.filter(c=>(labMap[a.role]||[]).includes(c.field.en)).slice(0,4);
const skMap={finance:['FP&A','Accounting'],banking:['Valuation','Audit'],leader:['Leadership','All fields'],hr:['HR'],sales:['Sales','Marketing'],creator:['Content creation','Marketing'],academic:['Academic'],builder:['Tech','Product']};
const sks=SKILLS.flatMap(g=>g.items).filter(s=>(skMap[a.role]||[]).some(f=>s.f.en.includes(f))).slice(0,5);
const perWeek={2:2,5:4,10:7}[a.time]||3;const weeks=Math.ceil(core.length/perWeek);
const deep={write:'prompting',analyse:'excel',automate:'cowork',build:'integration',lead:'capabilities'}[a.goal];
return {core,labs,sks,weeks,perWeek,deep}}
function vPath(){crumb(L(UX2.path));const ar=LANG==='ar';const done=PATHQ.every(q=>PA[q.k]);
let h=`<h1>🧭 ${L(UX2.path)}</h1><p class="lede">${ar?'جاوب 4 أسئلة وهنرتبلك الدروس والحالات والـ Skills اللي تناسب شغلك.':'Answer 4 questions and get the lessons, lab cases and skills that fit your work, in order.'}</p>`;
h+=PATHQ.map(q=>`<div class="case"><h3>${L(q.q)}</h3><div class="chips">${q.o.map(o=>`<button class="chip ${PA[q.k]===o[0]?'on':''}" data-pa="${q.k}:${o[0]}">${L(o[1])}</button>`).join('')}</div></div>`).join('');
if(!done)return h+`<p class="note">${ar?'كمّل الأسئلة علشان يطلع مسارك.':'Answer all questions to see your path.'}</p>`;
const p=buildPath(PA);ST.pathAns=PA;ST.path=p.core;saveST();
h+=`<div class="pathhead"><div><b>${p.core.length}</b>${ar?'درس':'lessons'}</div><div><b>${p.weeks}</b>${ar?'أسابيع':'weeks'}</div><div><b>${p.perWeek}</b>${ar?'دروس/أسبوع':'lessons/week'}</div><div><b>${p.core.filter(i=>DONE.includes(i)).length}/${p.core.length}</b>✓</div></div>`;
h+=`<h2>${ar?'دروسك بالترتيب':'Your lessons, in order'}</h2><ol class="pathlist">`+p.core.map((id,i)=>{const d=DAYS.find(x=>x.units.some(u=>u.id===id));const u=d.units.find(x=>x.id===id);return `<li class="${DONE.includes(id)?'ok':''}"><span class="wk">${ar?'أسبوع':'Week'} ${Math.floor(i/p.perWeek)+1}</span><a href="#day/${d.n}/${id}">${id} · ${L(u.t)}</a>${DONE.includes(id)?' ✓':''}</li>`}).join('')+`</ol>`;
h+=`<h2>${ar?'تعمق مقترح':'Suggested deep dive'}</h2><button class="card feature" data-go="deep/${p.deep}"><h3>${DEEP[p.deep].icon} ${L(DEEP[p.deep].t)}</h3><div class="k">${L(DEEP[p.deep].sub)}</div></button>`;
if(p.labs.length)h+=`<h2>${ar?'حالات المعمل لمجالك':'Lab cases for your field'}</h2><div class="grid">`+p.labs.map(c=>`<button class="card" data-go="lab"><span class="tag">${L(c.field)}</span><h3 style="margin-top:6px">${L(c.t)}</h3></button>`).join('')+`</div>`;
if(p.sks.length)h+=`<h2>${ar?'Skills تناسبك':'Skills for you'}</h2><div class="grid">`+p.sks.map(s=>`<button class="card" data-go="skills"><span class="n" style="font-family:monospace;color:var(--teal);font-size:12.5px">${s.n}</span><div class="k" style="margin-top:6px">${L(s.w)}</div></button>`).join('')+`</div>`;
return h+`<p><button class="tbtn" data-pareset="1">${ar?'اعد الأسئلة':'Start over'}</button></p>`}
// ---------- FEATURE PICKER ----------
const PICKQ=[
{k:"what",q:T("What do you want to do?","عايز تعمل إيه؟"),o:[["ask",T("Ask, explain, draft","أسأل أو أفهم أو أكتب")],["files",T("Analyse my files","أحلل ملفاتي")],["excel",T("Work inside Excel / PowerPoint","أشتغل جوه Excel / PowerPoint")],["deliver",T("Produce a deliverable (doc, deck, design, app)","أطلّع مخرج (مستند، عرض، تصميم، تطبيق)")],["data",T("Use live data from my tools","أستخدم بيانات حية من أدواتي")],["multi",T("Run a multi-step task on files","أنفّذ مهمة متعددة الخطوات على ملفات")],["code",T("Build software or a script","أبني برنامج أو سكريبت")],["system",T("Embed Claude in our systems","أدخّل Claude في أنظمتنا")]]},
{k:"rep",q:T("How often?","بتتكرر قد إيه؟"),o:[["once",T("Once","مرة واحدة")],["often",T("Weekly or more","كل أسبوع أو أكتر")]]},
{k:"team",q:T("For whom?","لمين؟"),o:[["me",T("Just me","ليّا أنا")],["team",T("My team","لفريقي")]]}];
let PK={};
function pickRec(a){const ar=LANG==='ar';const R=[];const r=(tool,why,route,p)=>R.push({tool,why,route,p});
const m={ask:()=>r('Chat + Projects',T('Fast answers and drafts; a Project keeps context for repeat work.','إجابات ومسودات سريعة؛ والـ Project بيحفظ السياق للشغل المتكرر.'),'day/2/2.2',T('Act as [role]. [Task]. Context: [facts]. Output: [format]. Ask me up to 3 questions first.','اتصرف كـ [الدور]. [المهمة]. السياق: [الحقايق]. المخرج: [الشكل]. اسألني لحد 3 أسئلة الأول.')),
files:()=>r('Chat with file upload + code execution',T('Claude reads PDFs, Excel and images and can compute with code.','Claude بيقرا PDF و Excel والصور ويقدر يحسب بالكود.'),'lab',T('Analyse the attached [file]. Check data quality first, then [analysis]. Table + 5 insights, sources cited.','حلّل [الملف] المرفق. افحص جودة البيانات الأول، وبعدين [التحليل]. جدول + 5 استنتاجات بالمصادر.')),
excel:()=>r('Claude for Excel / PowerPoint',T('Works in your workbook with cell citations; builds decks in your template.','بيشتغل في ملفك بالإشارة للخلايا؛ ويبني عروض بقالبك.'),'deep/excel',T('Explain this workbook with cell references, then [change] without breaking formulas. Show a change log.','اشرح الملف ده بمراجع الخلايا، وبعدين [التعديل] من غير ما تكسر المعادلات. اعرض سجل التغييرات.')),
deliver:()=>r('Artifacts · Docs · Slides · Design',T('Turns answers into shareable products: apps, documents, decks and visuals.','بيحوّل الإجابات لمنتجات تتشارك: تطبيقات ومستندات وعروض وتصاميم.'),'day/3/3.1',T('Build [deliverable] for [audience]: [sections]. Arabic/English, brand colours [..], print-ready.','ابني [المخرج] لـ [الجمهور]: [الأجزاء]. عربي/إنجليزي، ألوان البراند [..]، جاهز للطباعة.')),
data:()=>r('Connectors (MCP)',T('Reads Drive, Gmail, Calendar, CRM, ERP with your permissions.','بيقرا Drive و Gmail و Calendar و CRM و ERP بصلاحياتك.'),'day/4/4.3',T('Using [connector], pull [data] for [period] and [analysis]. Read-only; nothing sent.','باستخدام [الـ Connector] هات [البيانات] لـ [الفترة] و[التحليل]. قراءة بس؛ ومفيش إرسال.')),
multi:()=>r('Cowork',T('Plans and executes across files and tools, saving outputs to your folder.','بيخطط وينفّذ على الملفات والأدوات ويحفظ المخرجات في فولدرك.'),'day/6/6.1',T('In folder [copy], [outcome]. Show the plan first; save to /output; ask before send/post/delete.','في فولدر [النسخة]، [النتيجة]. وريني الخطة الأول؛ احفظ في /output؛ واسأل قبل الإرسال/النشر/المسح.')),
code:()=>r('Claude Code',T('Writes, tests and versions code; CLAUDE.md keeps project rules.','بيكتب ويختبر ويحفظ نسخ الكود؛ و CLAUDE.md بيحفظ قواعد المشروع.'),'day/7/7.1',T('/plan Build [tool] that [does]. Inputs [..], outputs [..]. Write tests first; keep CLAUDE.md updated.','/plan ابني [أداة] بتعمل [..]. المدخلات [..]، المخرجات [..]. اكتب الاختبارات الأول؛ وحدّث CLAUDE.md.')),
system:()=>r('Claude API / Agent SDK / Managed Agents',T('Full control, batches, structured outputs, hosted agents.','تحكم كامل، Batches، مخرجات مهيكلة، وكلاء مستضافين.'),'deep/integration',T('Design an API integration for [process]: pattern, prompt, JSON schema, validation, cost and evaluation plan.','صمّم تكامل API لـ [العملية]: النمط، البرومبت، الـ JSON schema، التحقق، التكلفة وخطة التقييم.'))};
(m[a.what]||m.ask)();
if(a.rep==='often')r('Skill (+ schedule if multi-step)',T('Repeated method → package it as a Skill; recurring tasks → Cowork schedule.','طريقة متكررة ← اعملها Skill؛ ومهمة متكررة ← جدول Cowork.'),'day/4/4.1',T('Use the skill-creator to turn this workflow into a skill: [steps]. Use when [..]; do NOT use for [..].','استخدم skill-creator تحوّل سير العمل ده لـ Skill: [الخطوات]. استخدمها لما [..]؛ ومتستخدمهاش في [..].'));
if(a.team==='team')r('Team plan + Plugin / shared Project',T('Share context and methods; admin controls and governance.','شارك السياق والطرق؛ تحكم إداري وحوكمة.'),'day/4/4.2',T('Design a team plugin/project for [function]: skills, connectors, commands, owners, rollout.','صمّم Plugin/Project للفريق لـ [الوظيفة]: Skills، Connectors، أوامر، مسؤولين، خطة نشر.'));
return R}
function vPick(){crumb(L(UX2.pick));const ar=LANG==='ar';let h=`<h1>🧭 ${L(UX2.pick)}</h1><p class="lede">${ar?'قولي عايز تعمل إيه، وهقولك أنسب أداة في Claude وليه، مع برومبت بداية ودرس.':'Tell me what you want to do and get the best Claude tool, why, a starter prompt and the lesson.'}</p>`;
h+=PICKQ.map(q=>`<div class="case"><h3>${L(q.q)}</h3><div class="chips">${q.o.map(o=>`<button class="chip ${PK[q.k]===o[0]?'on':''}" data-pk="${q.k}:${o[0]}">${L(o[1])}</button>`).join('')}</div></div>`).join('');
if(!PK.what)return h;const R=pickRec({rep:'once',team:'me',...PK});
h+=`<h2>${ar?'الترشيح':'Recommendation'}</h2>`+R.map((x,i)=>`<div class="case pickc ${i===0?'best':''}"><div class="meta">${i===0?(ar?'الأنسب':'Best fit'):(ar?'وكمان':'Also')}</div><h3>${x.tool}</h3><p>${L(x.why)}</p>${promptBox({t:T('Starter prompt','برومبت البداية'),p:x.p})}<button class="tbtn" data-go="${x.route}">${ar?'افتح الدرس':'Open the lesson'} →</button> <button class="tbtn" data-pk2b="${i}">🧱 ${ar?'كمّل في باني البرومبت':'Continue in prompt builder'}</button></div>`).join('');
window._pickR=R;return h}
// ---------- PROMPT LINT + TEST ----------
function lintPrompt(p){const ar=LANG==='ar';const c=[];const chk=(ok,en,a)=>c.push({ok,t:ar?a:en});
const f=PB_;chk(f.role.trim().length>15,'Role names expertise and context','الدور فيه الخبرة والسياق');chk(f.task.trim().length>10,'Task is one clear deliverable','المهمة مخرج واحد واضح');chk(f.context.trim().length>40,'Context has facts (files, period, currency, audience)','السياق فيه حقايق (ملفات، فترة، عملة، جمهور)');chk(/\d/.test(f.context+f.stop),'Contains concrete numbers or limits','فيه أرقام أو حدود محددة');chk(f.reasoning.trim().length>10,'Reasoning states the decision','المنطق بيذكر القرار');chk((f.stop.match(/\n|-|،|,/g)||[]).length>=1,'Stop conditions are a checklist','شروط التوقف قائمة');chk(f.output.trim().length>10,'Output format is specific','شكل المخرج محدد');chk(PB_.ctrl.includes(2)||PB_.ctrl.includes(3),'Includes an accuracy control','فيه ضابط للدقة');chk(PB_.ctrl.includes(0),'Asks clarifying questions first','بيسأل أسئلة توضيحية الأول');chk(p.length<6000,'Concise enough (saves tokens)','مختصر كفاية (بيوفّر توكنز)');
const score=Math.round(100*c.filter(x=>x.ok).length/c.length);return {score,c}}
let PBTEST={data:'',out:'',busy:false};
async function runPromptTest(){const sample=await tutorSample();const ar=LANG==='ar';const out=document.getElementById('pbtestout');
if(!sample){PBTEST.out=ar?'الاختبار مع Claude بيشتغل لما المنصة تتفتح جوه Claude. استخدم فحص الجودة فوق، أو انسخ البرومبت والبيانات وجرّبهم في محادثة جديدة.':'Testing with Claude works when the platform is opened inside Claude. Use the quality check above, or copy the prompt and data into a new chat.';render();return}
PBTEST.busy=true;PBTEST.out='';render();const data=PBTEST.data&&DATA[PBTEST.data]?`\n\n<attached_file name="${PBTEST.data}.csv">\n${DATA[PBTEST.data].csv}\n</attached_file>`:'';
try{const {text}=await sample(pbOut()+data+`\n\n(Test run: skip the clarifying questions and produce the best answer you can, labelling assumptions.)`,{cache:false,modelTier:'default',onText:({text})=>{const o=document.getElementById('pbtestout');if(o)o.textContent=text}});PBTEST.out=text}
catch(e){PBTEST.out=(e&&e.text)||(e&&e.code==='not_granted'?(ar?'محتاج موافقتك علشان يستخدم Claude.':'Permission needed to use Claude.'):(ar?'حصلت مشكلة — جرّب تاني.':'Something went wrong — try again.'))}
PBTEST.busy=false;render()}
function builderExtras(){const ar=LANG==='ar';const p=pbOut();const lint=lintPrompt(p);
return `<div class="case"><h3>✅ ${ar?'فحص الجودة':'Quality check'} — <span class="score s${lint.score>=80?'g':lint.score>=50?'a':'r'}">${lint.score}/100</span></h3><ul class="lint">${lint.c.map(x=>`<li class="${x.ok?'ok':'no'}">${x.ok?'✓':'✗'} ${x.t}</li>`).join('')}</ul></div>
<div class="case"><h3>🧪 ${ar?'اختبره مع Claude':'Test it with Claude'}</h3><label class="opt">${ar?'بيانات تجريبية (اختياري)':'Dummy data (optional)'}: <select id="pbdata"><option value="">—</option>${Object.keys(DATA).map(k=>`<option value="${k}" ${PBTEST.data===k?'selected':''}>${LANG==='ar'?DATA[k].ar:DATA[k].en}</option>`).join('')}</select></label><button class="dlbtn" data-pbtest="1" ${PBTEST.busy?'disabled':''}>${PBTEST.busy?(ar?'جاري…':'Running…'):(ar?'شغّل الاختبار':'Run test')}</button><pre class="testout" id="pbtestout" dir="auto">${esc(PBTEST.out)}</pre></div>
<div class="case"><h3>⤓ ${ar?'تصدير':'Export'}</h3><button class="dlbtn" data-pbexp="md">${ar?'البرومبت .md':'Prompt .md'}</button> <button class="dlbtn" data-pbexp="txt">.txt</button> ${ST.mine.length?`<button class="dlbtn" data-pbexp="all">${ar?'كل برومبتاتي المحفوظة .md':'All my saved prompts .md'}</button>`:''}</div>`}
// ---------- SKILL BUILDER ----------
let SK=Object.assign({name:'',field:'',what:'',when:'',not:'',inputs:'',steps:'',output:'',example:'',test:''},ST.skDraft||{});let SKTEST={out:'',busy:false};
function skMD(){const steps=SK.steps.split('\n').map(s=>s.trim()).filter(Boolean).map((s,i)=>`${i+1}. ${s.replace(/^\d+[.)]\s*/,'')}`).join('\n');
const desc=`${SK.what.trim()} Use when ${SK.when.trim()}.${SK.not.trim()?' Do NOT use for '+SK.not.trim()+'.':''}`.replace(/\s+/g,' ');
return `---\nname: ${SK.name.trim()||'my-skill'}\ndescription: ${desc}\n---\n\n# ${SK.name.trim()||'my-skill'}\n\n${SK.field?`**Field:** ${SK.field}\n\n`:''}## Inputs\n${SK.inputs.trim()||'- [describe expected files or information]'}\n\n## Steps\n${steps||'1. [step]'}\n\n## Output format\n${SK.output.trim()||'[describe the deliverable]'}\n\n## Rules\n- Never invent numbers; write [MISSING] when data is absent.\n- Label assumptions and mark items that need human review.\n- Ask up to 3 clarifying questions if key inputs are missing.\n${SK.example.trim()?`\n## Example\n${SK.example.trim()}\n`:''}`}
function lintSkill(){const ar=LANG==='ar';const c=[];const chk=(ok,en,a)=>c.push({ok,t:ar?a:en});
chk(/^[a-z0-9]+(-[a-z0-9]+)*$/.test(SK.name.trim()),'Name is lowercase-with-hyphens','الاسم حروف صغيرة بشرطات');chk(SK.what.trim().length>20,'Description says what it does','الوصف بيقول بتعمل إيه');chk(SK.when.trim().length>15,"'Use when' describes triggers","'استخدمها لما' بيوصف المواقف");chk(SK.not.trim().length>5,"'Do NOT use for' prevents false triggers","'متستخدمهاش في' بيمنع التشغيل الغلط");chk(SK.steps.split('\n').filter(s=>s.trim()).length>=3,'At least 3 steps','3 خطوات على الأقل');chk(SK.output.trim().length>10,'Output format defined','شكل المخرج محدد');chk(SK.example.trim().length>10,'Includes an example','فيه مثال');
return {score:Math.round(100*c.filter(x=>x.ok).length/c.length),c}}
function vSkillBuilder(){crumb(L(UX2.skb));const ar=LANG==='ar';const F=[['name',T('Skill name (kebab-case)','اسم الـ Skill (بشرطات)'),'lc-doc-checker'],['field',T('Field','المجال'),ar?'التمويل التجاري':'Trade finance'],['what',T('What it does','بتعمل إيه'),ar?'Examines LC documents against UCP 600 and ISBP.':'Examines LC documents against UCP 600 and ISBP.'],['when',T('Use when…','استخدمها لما…'),'the user uploads an MT700 with shipping documents'],['not',T('Do NOT use for…','متستخدمهاش في…'),'guarantees (URDG) or collections (URC 522)'],['inputs',T('Inputs','المدخلات'),'- MT700\n- Invoice, B/L, packing list'],['steps',T('Steps (one per line)','الخطوات (سطر لكل خطوة)'),'Extract LC fields\nCheck each document\nList discrepancies\nDraft notice'],['output',T('Output format','شكل المخرج'),'Discrepancy table + bilingual notice'],['example',T('Example (good output)','مثال (مخرج كويس)'),'Field 44C: latest shipment 15 Sep; B/L 18 Sep → late shipment (UCP 600 art. 14)']];
const lint=lintSkill();const i=PSTORE.push(skMD())-1;window._ski=i;
return `<h1>🧩 ${L(UX2.skb)}</h1><p class="lede">${ar?'اكتب طريقتك مرة واحدة وحوّلها لـ SKILL.md جاهز للرفع في Claude (Customize ← Skills) أو في Claude Code (.claude/skills/).':'Write your method once and turn it into a ready SKILL.md for Claude (Customize → Skills) or Claude Code (.claude/skills/).'}</p>
<div class="pbgrid"><div>${F.map(f=>`<label class="pbf"><b>${L(f[1])}</b><textarea data-sk="${f[0]}" rows="${['steps','inputs','example'].includes(f[0])?4:f[0]==='name'||f[0]==='field'?1:2}" placeholder="${esc(f[2])}" dir="auto">${esc(SK[f[0]])}</textarea></label>`).join('')}</div>
<div><div class="prompt"><div class="ph"><h3>SKILL.md</h3><span><button class="copy" data-i="${i}">${L(UI.copy)}</button></span></div><pre id="skout" dir="ltr" style="text-align:left">${esc(skMD())}</pre></div>
<div class="case"><h3>✅ ${ar?'فحص الجودة':'Quality check'} — <span id="skscore" class="score s${lint.score>=80?'g':lint.score>=50?'a':'r'}">${lint.score}/100</span></h3><ul class="lint" id="sklint">${lint.c.map(x=>`<li class="${x.ok?'ok':'no'}">${x.ok?'✓':'✗'} ${x.t}</li>`).join('')}</ul></div>
<div class="case"><h3>🧪 ${ar?'اختبر التشغيل مع Claude':'Test the trigger with Claude'}</h3><textarea data-sk="test" rows="2" class="pbtx" placeholder="${ar?'اكتب طلب مستخدم تجريبي…':'Type a sample user request…'}" dir="auto">${esc(SK.test)}</textarea><button class="dlbtn" data-sktest="1" ${SKTEST.busy?'disabled':''}>${SKTEST.busy?(ar?'جاري…':'Running…'):(ar?'شغّل الاختبار':'Run test')}</button><pre class="testout" id="sktestout" dir="auto">${esc(SKTEST.out)}</pre></div>
<div class="case"><h3>⤓ ${ar?'تصدير':'Export'}</h3><button class="dlbtn" data-skexp="md">SKILL.md</button> <button class="dlbtn" data-skexp="zip">${ar?'فولدر الـ Skill (ZIP)':'Skill folder (ZIP)'}</button> <button class="tbtn" data-skreset="1">${ar?'ابدأ من جديد':'Start over'}</button></div>
<p class="note">${ar?'ارفع الـ ZIP من Customize ← Skills ← + ← Create skill ← Upload. فعّل تنفيذ الكود الأول.':'Upload the ZIP via Customize → Skills → + → Create skill → Upload. Code execution must be on.'}</p></div></div>`}
async function runSkillTest(){const sample=await tutorSample();const ar=LANG==='ar';
if(!sample){SKTEST.out=ar?'الاختبار مع Claude بيشتغل لما المنصة تتفتح جوه Claude.':'Testing with Claude works when the platform is opened inside Claude.';render();return}
SKTEST.busy=true;SKTEST.out='';render();
try{const {text}=await sample(`You are evaluating a Claude Agent Skill.\n\n<skill>\n${skMD()}\n</skill>\n\n<user_request>${SK.test||'(none)'}</user_request>\n\n1) Would this skill's description trigger for this request? Answer YES/NO with one-line reason.\n2) If YES, briefly show how the steps would be applied (max 8 lines).\n3) Suggest one improvement to the description or steps.\nReply in ${ar?'Arabic':'English'}.`,{cache:false,modelTier:'quick',onText:({text})=>{const o=document.getElementById('sktestout');if(o)o.textContent=text}});SKTEST.out=text}
catch(e){SKTEST.out=(e&&e.text)||(ar?'حصلت مشكلة — جرّب تاني.':'Something went wrong — try again.')}
SKTEST.busy=false;render()}
// ---------- SPLASH + TOUR ----------
function splash(){if(PRINT)return;try{if(sessionStorage.getItem('cm_splash'))return;sessionStorage.setItem('cm_splash','1')}catch(e){}
const s=document.createElement('div');s.className='splash';s.innerHTML=`<div class="sp-in"><div class="sp-mark">✦</div><div class="sp-name">Claude Mastery</div><div class="sp-by">${LANG==='ar'?'د. سارة سالم — صانعة المحتوى والمدرّبة':'Dr. Sara Salem — Creator & instructor'}</div><div class="sp-tag">${LANG==='ar'?'فكّر · ابني · أتمت · اتخطى':'Think · Build · Automate · Go beyond'}</div><div class="sp-bar"><span></span></div></div>`;document.body.appendChild(s);
setTimeout(()=>{s.classList.add('out');setTimeout(()=>{s.remove();let seen=false;try{seen=localStorage.getItem('cm_tour')}catch(e){}if(!seen)startTour()},500)},1700)}
const TOUR=[['#side .brand',T('Welcome! This is your Claude Mastery platform — 9 modules, deep dives, labs and tools.','أهلاً! دي منصة Claude Mastery — 9 موديولات وتعمق ومعامل وأدوات.')],['[data-go="path"]',T('Start with your personal learning path.','ابدأ بمسارك التعليمي الشخصي.')],['[data-go="map"]',T('The mastery map shows the whole journey from prompt to AI employees.','خريطة الإتقان بتوريك الرحلة كلها من البرومبت لموظفين AI.')],['#gsearch',T('Search everything: lessons, cases, skills, words.','ابحث في كل حاجة: الدروس والحالات والـ Skills والكلمات.')],['[data-go="lab"]',T('Try master prompts with dummy data in the lab.','جرّب البرومبتات الماستر بالبيانات التجريبية في المعمل.')],['[data-go="studio"]',T('Build, check, test and export your own prompts.','ابني وافحص واختبر وصدّر برومبتاتك.')],['[data-go="agentb"]',T('Design and export real agents in 8 steps.','صمّم وصدّر وكلاء حقيقيين في 8 خطوات.')],['[data-go="quiz/1"]',T('Quizzes, flashcards, XP and your certificate live here.','الاختبارات والكروت والنقط والشهادة هنا.')],['#langBtn',T('Switch Arabic / English anytime — and light/dark next to it.','بدّل عربي/إنجليزي في أي وقت — والوضع الليلي جنبه.')],['[data-go="export"]',T('Download everything: PDFs, prompt book, data, ZIP.','نزّل كل حاجة: PDF وكتاب البرومبتات والبيانات و ZIP.')]];
let TI=-1;function startTour(){go('home');TI=0;setTimeout(drawTour,250)}
function drawTour(){document.querySelectorAll('.tour-hl').forEach(e=>e.classList.remove('tour-hl'));let b=document.getElementById('tourbox');if(TI<0||TI>=TOUR.length){if(b)b.remove();TI=-1;try{localStorage.setItem('cm_tour','1')}catch(e){}return}
const [sel,txt]=TOUR[TI];const el=document.querySelector(sel);if(el){el.classList.add('tour-hl');el.scrollIntoView({block:'center',behavior:'smooth'})}
if(!b){b=document.createElement('div');b.id='tourbox';b.className='tourbox';document.body.appendChild(b)}
const ar=LANG==='ar';b.innerHTML=`<div class="k">${TI+1}/${TOUR.length}</div><p>${L(txt)}</p><div><button class="tbtn" data-tour="skip">${ar?'تخطي':'Skip'}</button> <button class="dlbtn" data-tour="next">${TI===TOUR.length-1?(ar?'يلا نبدأ':'Let\'s go'):(ar?'التالي':'Next')}</button></div>`;
if(el){const r=el.getBoundingClientRect();b.style.top=Math.min(window.innerHeight-170,Math.max(10,r.bottom+10))+'px';b.style.left=Math.max(10,Math.min(window.innerWidth-330,(ar?r.left-180:r.left)))+'px'}else{b.style.top='40%';b.style.left='calc(50% - 160px)'}}
function toolsClick(e){const g=s=>e.target.closest(s);let x;
if(x=g('[data-pa]')){const [k,v]=x.dataset.pa.split(':');PA={...PA,[k]:v};render();return true}
if(x=g('[data-pareset]')){PA={};ST.pathAns={};saveST();render();return true}
if(x=g('[data-pk]')){const [k,v]=x.dataset.pk.split(':');PK={...PK,[k]:v};render();return true}
if(x=g('[data-pk2b]')){const r=window._pickR[+x.dataset.pk2b];SU.task=L(r.p);stuTab='build';saveSU();go('studio');return true}
if(x=g('[data-pbtest]')){runPromptTest();return true}
if(x=g('[data-pbexp]')){const k=x.dataset.pbexp;if(k==='all')saveFile('My-Prompts.md','# My saved prompts\n'+ST.mine.map(p=>`\n## ${p.t} (${p.d})\n\n\`\`\`\n${p.p}\n\`\`\`\n`).join(''));else saveFile('Master-Prompt.'+k,k==='md'?'# Master prompt\n\n```\n'+pbOut()+'\n```\n':pbOut());return true}
if(x=g('[data-sktest]')){runSkillTest();return true}
if(x=g('[data-skexp]')){const nm=(SK.name.trim()||'my-skill');if(x.dataset.skexp==='md')saveFile('SKILL.md',skMD());else ensureZip().then(async()=>{const z=new JSZip();z.file(nm+'/SKILL.md',skMD());saveFile(nm+'.zip',await z.generateAsync({type:'blob'}))});return true}
if(x=g('[data-skreset]')){Object.keys(SK).forEach(k=>SK[k]='');ST.skDraft={};saveST();SKTEST.out='';render();return true}
if(x=g('[data-tour]')){if(x.dataset.tour==='skip')TI=TOUR.length;else TI++;drawTour();return true}
if(x=g('[data-starttour]')){try{localStorage.removeItem('cm_tour')}catch(e){}startTour();return true}
return false}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.sk){SK[t.dataset.sk]=t.value;ST.skDraft=SK;saveST();const o=document.getElementById('skout');if(o)o.textContent=skMD();PSTORE[window._ski]=skMD();const l=lintSkill();const s=document.getElementById('skscore');if(s){s.textContent=l.score+'/100';s.className='score s'+(l.score>=80?'g':l.score>=50?'a':'r')}const ul=document.getElementById('sklint');if(ul)ul.innerHTML=l.c.map(x=>`<li class="${x.ok?'ok':'no'}">${x.ok?'✓':'✗'} ${x.t}</li>`).join('')}});
document.addEventListener('change',e=>{if(e.target.id==='pbdata')PBTEST.data=e.target.value});
