// ===== My curriculum dashboard =====
const UX5={mycurr:T("My curriculum","منهجي"),reg:T("Use-case register","سجل حالات الاستخدام")};
let CV={view:'board',tag:'all',st:'all',q:''};
function vCurr(){if(PRINT)return vCurrOld();crumb(L(UX5.mycurr));const ar=LANG==='ar';const all=DAYS.flatMap(d=>d.units.map(u=>[d,u]));const mins=all.reduce((a,[d,u])=>a+(+u.dur),0),doneMins=all.filter(([d,u])=>DONE.includes(u.id)).reduce((a,[d,u])=>a+(+u.dur),0);
const next=all.find(([d,u])=>!DONE.includes(u.id));const q=CV.q.toLowerCase();
const ok=([d,u])=>(CV.tag==='all'||u.tag===CV.tag)&&(CV.st==='all'||(CV.st==='done')===DONE.includes(u.id))&&(!q||(L(u.t)+' '+(FEAT[u.id]||'')).toLowerCase().includes(q));
let h=`<section class="cdash"><div class="cd-l"><div class="sig">${ar?'منهج د. سارة سالم':'Dr. Sara Salem’s curriculum'}</div><h1>${L(UX5.mycurr)}</h1><p>${ar?`${DAYS.length} موديولات و${all.length} درس — حوالي ${Math.round(mins/60)} ساعة تدريب. كل درس فيه خطوات وبرومبت ماستر وحالة حقيقية.`:`${DAYS.length} modules, ${all.length} lessons — about ${Math.round(mins/60)} training hours. Every lesson has steps, a master prompt and a real case.`}</p>${next?`<button class="btn-gold" data-go="day/${next[0].n}/${next[1].id}">${DONE.length?(ar?'كمّل':'Continue'):(ar?'ابدأ':'Start')}: ${next[1].id} ${L(next[1].t)}</button>`:`<button class="btn-gold" data-go="cert">🎓 ${L(UX.cert)}</button>`}</div>
<div class="cd-r"><div class="cd-ring">${ring(pct())}</div><div class="cd-kpi"><div><b>${DONE.length}/${all.length}</b>${ar?'درس':'lessons'}</div><div><b>${Math.round(doneMins/60)}/${Math.round(mins/60)}</b>${ar?'ساعة':'hours'}</div><div><b>${quizAvg()}%</b>${ar?'الاختبارات':'quizzes'}</div><div><b>${ST.xp}</b>XP</div></div></div></section>`;
const tags=[...new Set(all.map(([d,u])=>u.tag))];
h+=`<div class="cd-bar"><div class="seg">${[['board',ar?'لوحة':'Board'],['timeline',ar?'خط زمني':'Timeline'],['table',ar?'جدول':'Table']].map(v=>`<button class="${CV.view===v[0]?'on':''}" data-cv="view:${v[0]}">${v[1]}</button>`).join('')}</div><input class="search" id="cvq" value="${esc(CV.q)}" placeholder="${ar?'ابحث في الدروس…':'Search lessons…'}"><select id="cvtag"><option value="all">${ar?'كل الأنواع':'All types'}</option>${tags.map(t=>`<option value="${t}" ${CV.tag===t?'selected':''}>${L(TAGS[t])}</option>`).join('')}</select><select id="cvst"><option value="all">${ar?'كل الحالات':'All'}</option><option value="todo" ${CV.st==='todo'?'selected':''}>${ar?'لسه':'To do'}</option><option value="done" ${CV.st==='done'?'selected':''}>${ar?'خلص':'Done'}</option></select></div>`;
if(CV.view==='board'){h+=`<div class="cboard">`+DAYS.map(d=>{const us=d.units.filter(u=>ok([d,u]));if(!us.length)return '';const dn=d.units.filter(u=>DONE.includes(u.id)).length;const p=Math.round(100*dn/d.units.length);return `<article class="cmod"><header><span class="cnum">${d.n}</span><div><h3><a href="#day/${d.n}">${L(d.t)}</a></h3><small>${L(d.sub)}</small></div><span class="cp" title="${p}%"><i style="--p:${p}"></i><em>${p}%</em></span></header><ol>${us.map(u=>`<li class="${DONE.includes(u.id)?'ok':''} ${next&&next[1].id===u.id?'nx':''}"><button class="ck" data-done="${u.id}" aria-label="done">${DONE.includes(u.id)?'✓':''}</button><a href="#day/${d.n}/${u.id}"><b>${u.id}</b> ${L(u.t)}</a><span class="tag ${u.tag}">${L(TAGS[u.tag])}</span><span class="dur">${u.dur}′</span></li>`).join('')}</ol><footer>${modExportBar(d.n)}<button class="tbtn" data-go="quiz/${d.n}">🧠 ${L(UX.quiz)}</button></footer></article>`}).join('')+`</div>`}
else if(CV.view==='timeline'){const per=+(ST.weekly||4);let acc=0,wk=1;const rows=[];all.filter(ok).forEach(([d,u])=>{acc+=+u.dur;if(acc>per*60){wk++;acc=+u.dur}rows.push([wk,d,u])});
h+=`<p class="note">${ar?'ساعات في الأسبوع':'Hours per week'}: ${[2,4,6,10].map(x=>`<button class="chip ${+(ST.weekly||4)===x?'on':''}" data-cv="weekly:${x}">${x}</button>`).join(' ')}</p><div class="ctl">`+[...new Set(rows.map(r=>r[0]))].map(w=>`<div class="ctw"><div class="ctwh">${ar?'أسبوع':'Week'} ${w}</div>${rows.filter(r=>r[0]===w).map(([w,d,u])=>`<a class="ctl-i ${DONE.includes(u.id)?'ok':''}" href="#day/${d.n}/${u.id}"><b>${u.id}</b> ${L(u.t)}<span>${u.dur}′</span></a>`).join('')}</div>`).join('')+`</div>`}
else{h+=vCurrOld().replace(/^[\s\S]*?<h2>/,'<h2>')}
h+=`<div class="cd-deep"><h2>${L(UI.deep)}</h2><div class="chips">${DEEPORDER.map(k=>`<button class="chip" data-go="deep/${k}">${DEEP[k].icon} ${L(DEEP[k].t)}</button>`).join('')}</div></div>`;
return h}
// ===== Use-case register builder =====
ST.reg=ST.reg||[];let RG={edit:-1,f:{},flt:'all'};
const RG_Q=[['cust',T('Affects customers directly?','بيأثر على العملاء مباشرة؟')],['people',T('Influences decisions about people (hiring, credit, discipline)?','بيأثر على قرارات عن أفراد (توظيف، ائتمان، جزاءات)؟')],['conf',T('Uses confidential or personal data?','بيستخدم بيانات سرية أو شخصية؟')],['auto',T('Takes actions automatically (send, post, pay, post to ledger)?','بينفّذ إجراءات تلقائي (إرسال، نشر، دفع، ترحيل)؟')],['reg',T('Output goes to regulators or auditors?','الناتج بيروح للرقابة أو المراجعين؟')],['dec',T('Output is used in management decisions?','الناتج بيدخل في قرارات الإدارة؟')]];
function rgTier(a){if(a.people||a.auto||a.reg||(a.cust&&a.conf))return 'high';if(a.conf||a.dec||a.cust)return 'medium';return 'low'}
const RG_CTRL={low:T('Self-review · data minimisation · disclose AI use where relevant','مراجعة ذاتية · أقل بيانات · توضيح استخدام الـ AI عند اللزوم'),medium:T('Peer review of outputs · approved plan & settings · sources cited · quarterly review','مراجعة زميل · خطة وإعدادات معتمدة · مصادر مذكورة · مراجعة ربع سنوية'),high:T('Documented human approval · bias & accuracy testing · audit log · monthly sample review · incident plan','موافقة بشرية موثقة · اختبار التحيز والدقة · سجل تدقيق · عينة شهرية · خطة حوادث')};
const RG_REV={low:T('Annual','سنوي'),medium:T('Quarterly','ربع سنوي'),high:T('Monthly','شهري')};
const RG_SAMPLE=[{name:'Monthly variance commentary',owner:'FP&A lead',dept:'Finance',tool:'Claude for Excel',desc:'Draft commentary from the variance table',a:{dec:1}},{name:'CV screening first pass',owner:'HR manager',dept:'HR',tool:'Project + Skill',desc:'Score CVs against job criteria',a:{people:1,conf:1}},{name:'Customer email drafts',owner:'CS lead',dept:'Customer service',tool:'Cowork + Gmail',desc:'Draft replies; humans send',a:{cust:1,conf:1}}];
function vRegister(){crumb(L(UX5.reg));const ar=LANG==='ar';const f=RG.f;f.a=f.a||{};const tier=rgTier(f.a);const list=ST.reg.map((r,i)=>[r,i]).filter(([r])=>RG.flt==='all'||rgTier(r.a)===RG.flt);
const cnt=t=>ST.reg.filter(r=>rgTier(r.a)===t).length;const tl={low:T('Low','منخفض'),medium:T('Medium','متوسط'),high:T('High','عالي')};
let h=`<h1>🗂 ${L(UX5.reg)}</h1><p class="lede">${ar?'سجّل كل استخدام للـ AI في مؤسستك: المسؤول والبيانات ومستوى الخطر والضوابط. الخطر بيتحسب تلقائي من 6 أسئلة.':'Record every AI use in your organisation: owner, data, risk tier and controls. The tier is calculated automatically from six questions.'}</p>
<div class="stat4"><div><b>${ST.reg.length}</b>${ar?'حالة':'use cases'}</div><div class="t-high"><b>${cnt('high')}</b>${L(tl.high)}</div><div class="t-medium"><b>${cnt('medium')}</b>${L(tl.medium)}</div><div class="t-low"><b>${cnt('low')}</b>${L(tl.low)}</div></div>
<div class="rgwrap"><div class="abpane"><h3>${RG.edit>=0?(ar?'تعديل حالة':'Edit use case'):(ar?'حالة جديدة':'New use case')}</h3>${[['name',T('Use case','الحالة'),'Monthly variance commentary'],['owner',T('Accountable owner','المسؤول'),'FP&A lead'],['dept',T('Department','الإدارة'),'Finance'],['tool',T('Claude surface','أداة Claude'),'Claude for Excel'],['desc',T('What it does','بتعمل إيه'),'']].map(x=>`<label class="pbf"><b>${L(x[1])}</b><input class="search" data-rg="${x[0]}" value="${esc(f[x[0]]||'')}" placeholder="${esc(x[2])}"></label>`).join('')}
<b>${ar?'أسئلة الخطر':'Risk questions'}</b>${RG_Q.map(q=>`<label class="opt"><input type="checkbox" data-rgq="${q[0]}" ${f.a[q[0]]?'checked':''}> ${L(q[1])}</label>`).join('')}
<div class="rgtier t-${tier}"><b>${ar?'مستوى الخطر':'Risk tier'}: ${L(tl[tier])}</b><span>${ar?'الضوابط':'Controls'}: ${L(RG_CTRL[tier])}</span><span>${ar?'المراجعة':'Review'}: ${L(RG_REV[tier])}</span></div>
<div class="row-btns"><button class="btn-gold" data-rggo="save">${RG.edit>=0?(ar?'حفظ التعديل':'Save changes'):(ar?'ضيف للسجل':'Add to register')}</button>${RG.edit>=0?`<button class="btn-ghost" data-rggo="cancel">${ar?'إلغاء':'Cancel'}</button>`:''}${!ST.reg.length?`<button class="tbtn" data-rggo="sample">${ar?'ضيف 3 أمثلة':'Add 3 examples'}</button>`:''}</div></div>
<div><div class="chips">${['all','high','medium','low'].map(t=>`<button class="chip ${RG.flt===t?'on':''}" data-rgf="${t}">${t==='all'?L(UI.all):L(tl[t])}</button>`).join('')}</div>${list.length?`<div class="tablewrap"><table class="rgtab"><tr><th>${ar?'الحالة':'Use case'}</th><th>${ar?'المسؤول':'Owner'}</th><th>${ar?'الأداة':'Tool'}</th><th>${ar?'الخطر':'Tier'}</th><th>${ar?'المراجعة':'Review'}</th><th></th></tr>${list.map(([r,i])=>{const t=rgTier(r.a);return `<tr><td><b>${esc(r.name)}</b><div class="k">${esc(r.dept||'')} ${r.desc?'· '+esc(r.desc):''}</div></td><td>${esc(r.owner||'')}</td><td>${esc(r.tool||'')}</td><td><span class="tier t-${t}">${L(tl[t])}</span></td><td>${L(RG_REV[t])}</td><td><button class="tbtn" data-rge="${i}">✎</button> <button class="tbtn" data-rgd="${i}">✕</button></td></tr>`}).join('')}</table></div>`:`<div class="empty">${ar?'السجل فاضي — ضيف أول حالة من الفورم.':'The register is empty — add your first use case with the form.'}</div>`}
<div class="row-btns"><button class="tbtn" data-rgx="csv">⤓ CSV (Excel)</button><button class="tbtn" data-rgx="md">⤓ Markdown</button><button class="tbtn" data-go="day/9/9.4">${ar?'درس إطار الحوكمة':'Governance lesson'}</button></div></div></div>`;return h}
function ui3Click(e){const g=s=>e.target.closest(s);let x;
if(x=g('[data-cv]')){const [k,v]=x.dataset.cv.split(':');if(k==='weekly'){ST.weekly=+v;saveST()}else CV[k]=v;render();return true}
if(x=g('[data-rggo]')){const a=x.dataset.rggo;if(a==='save'){if(!(RG.f.name||'').trim()){alert(LANG==='ar'?'اكتب اسم الحالة الأول.':'Enter the use case name first.');return true}const r={...RG.f,a:{...(RG.f.a||{})},date:new Date().toISOString().slice(0,10)};if(RG.edit>=0)ST.reg[RG.edit]=r;else ST.reg.push(r);RG={edit:-1,f:{},flt:RG.flt};saveST();addXP(3)}
if(a==='cancel')RG={edit:-1,f:{},flt:RG.flt};if(a==='sample'){ST.reg.push(...RG_SAMPLE.map(s=>({...s,date:new Date().toISOString().slice(0,10)})));saveST()}render();return true}
if(x=g('[data-rgf]')){RG.flt=x.dataset.rgf;render();return true}
if(x=g('[data-rge]')){const i=+x.dataset.rge;RG.edit=i;RG.f=JSON.parse(JSON.stringify(ST.reg[i]));render();return true}
if(x=g('[data-rgd]')){ST.reg.splice(+x.dataset.rgd,1);saveST();render();return true}
if(x=g('[data-rgx]')){const rows=ST.reg.map(r=>{const t=rgTier(r.a);return [r.name,r.owner,r.dept,r.tool,r.desc,t,RG_CTRL[t].en,RG_REV[t].en,RG_Q.filter(q=>r.a[q[0]]).map(q=>q[1].en).join('; '),r.date]});
if(x.dataset.rgx==='csv')saveFile('AI-use-case-register.csv',BOM+'use_case,owner,department,tool,description,risk_tier,controls,review,risk_factors,date\n'+rows.map(r=>r.map(csvq).join(',')).join('\n'));else saveFile('AI-use-case-register.md','# AI use-case register\n\n| Use case | Owner | Dept | Tool | Tier | Controls | Review |\n|---|---|---|---|---|---|---|\n'+rows.map(r=>`| ${r[0]} | ${r[1]||''} | ${r[2]||''} | ${r[3]||''} | ${r[5]} | ${r[6]} | ${r[7]} |`).join('\n'));return true}
return false}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.rg){RG.f[t.dataset.rg]=t.value}if(t.id==='cvq'){CV.q=t.value;const pos=t.selectionStart;render();const el=document.getElementById('cvq');if(el){el.focus();el.setSelectionRange(pos,pos)}}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.rgq){RG.f.a=RG.f.a||{};RG.f.a[t.dataset.rgq]=t.checked?1:0;render()}if(t.id==='cvtag'){CV.tag=t.value;render()}if(t.id==='cvst'){CV.st=t.value;render()}});
