const UX6={csim:T("Case simulator","محاكي الحالات"),card:T("Achievement card","كارت الإنجاز"),cheat:T("Cheat sheet","ورقة مختصرة"),cohort:T("Cohort & instructor view","الدفعة ولوحة المدرّب"),policy:T("AI policy generator","مولّد سياسة الـ AI"),wf:T("Workflow designer","مصمم سير العمل"),mcpp:T("MCP connector planner","مخطط Connector الـ MCP"),packs:T("Prompt packs","حزم البرومبتات")};
// ===== 1. Branching case simulator =====
const N=(t,ta,opts)=>({t:T(t,ta),o:opts});const O=(t,ta,to,pts,fb,fba)=>({t:T(t,ta),to,pts,fb:T(fb,fba)});
const CSIM={
lc:{t:T('LC discrepancy under pressure','مخالفة اعتماد تحت الضغط'),s:{
start:N('Shipment documents for USD 1.25M arrive. The B/L shows shipment on 18 Sep; the LC latest shipment date is 15 Sep. The supplier asks you to "just present them".','مستندات شحنة بـ 1.25 مليون دولار وصلت. البوليصة بتقول الشحن 18 سبتمبر؛ وآخر موعد في الاعتماد 15 سبتمبر. المورد بيطلب "قدّمها وخلاص".',[O('Run the lc-doc-checker Skill on all documents first','شغّل Skill فحص المستندات على كل المستندات الأول','found',20,'Right: get the full picture before deciding.','صح: خد الصورة كاملة قبل القرار.'),O('Present them to the bank now to save time','قدّمها للبنك دلوقتي علشان الوقت','refused',-10,'Late shipment is a clear discrepancy; refusal fees and delays follow.','الشحن المتأخر مخالفة واضحة؛ هيتبعها رسوم رفض وتأخير.')]),
found:N('Claude lists: late shipment (UCP 600 art. 14), invoice amount USD 1,262,500 exceeds LC by 1% (tolerance not stated). What next?','Claude طلّع: شحن متأخر (المادة 14 من UCP 600)، والفاتورة 1,262,500 دولار بزيادة 1% عن الاعتماد (من غير نسبة سماح). تعمل إيه؟',[O('Ask the applicant to accept discrepancies / request an amendment','اطلب من المستورد يقبل المخالفات / تعديل الاعتماد','amend',20,'Best path: an amendment or waiver keeps the deal clean.','أحسن طريق: التعديل أو التنازل بيخلي الصفقة نضيفة.'),O('Ask Claude to rewrite the B/L date','اطلب من Claude يعدّل تاريخ البوليصة','ethics',-30,'Altering documents is fraud. Claude should refuse and so should you.','تعديل المستندات تزوير. Claude لازم يرفض وإنت كمان.')]),
amend:N('The applicant agrees to waive the late shipment but wants the invoice corrected. You draft the notice with Claude.','المستورد وافق يتنازل عن التأخير بس عايز تصحيح الفاتورة. بتكتب الإخطار مع Claude.',[O('Send the bilingual draft to the examiner for review first','ابعت المسودة ثنائية اللغة للفاحص يراجعها الأول','end_good',20,'Human review before external action.','مراجعة بشرية قبل أي إجراء خارجي.'),O('Let Cowork email the supplier directly','خلي Cowork يبعت للمورد مباشرة','end_mid',0,'Works, but external sends should wait for approval.','بيمشي، بس الإرسال الخارجي لازم يستنى موافقة.')]),
refused:N('The bank refuses the documents. Demurrage starts at the port.','البنك رفض المستندات. والأرضيات بدأت في الميناء.',[O('Start again with a proper check','ابدأ تاني بفحص صح','start',0,'',''),O('Finish the case','اقفل الحالة','end_bad',0,'','')]),
ethics:N('You stop. Claude explains it cannot alter documents and suggests an amendment instead.','بتوقف. Claude بيشرح إنه ميقدرش يعدّل مستندات وبيقترح تعديل الاعتماد.',[O('Request an amendment','اطلب تعديل الاعتماد','amend',5,'Recovered — integrity first.','اتصلّحت — النزاهة الأول.')])}},
credit:{t:T('Credit committee decision','قرار لجنة الائتمان'),s:{
start:N('An EGP 50M working-capital request. Claude drafts a memo: DSCR 1.31, Debt/EBITDA 3.4, current ratio 1.19 (limit 1.2).','طلب تسهيل 50 مليون جنيه. Claude كتب مذكرة: DSCR 1.31، الدين/EBITDA 3.4، التداول 1.19 (الحد 1.2).',[O('Run a stress test: sales −20%, EGP −15%','اعمل اختبار ضغط: مبيعات −20%، جنيه −15%','stress',20,'Good: covenants are close to limits.','كويس: التعهدات قريبة من الحدود.'),O('Approve — the memo recommends it','وافق — المذكرة بتوصي بكده','risk',-20,'AI drafts; people decide, with evidence.','الـ AI بيكتب؛ والناس بتقرر بالأدلة.')]),
stress:N('Under stress, DSCR falls to 0.98 and the current ratio breaches.','تحت الضغط، DSCR نزل لـ 0.98 والتداول كسر الحد.',[O('Approve with conditions: lower limit, receivables assignment, quarterly covenants','وافق بشروط: حد أقل، حوالة حق، تعهدات ربع سنوية','end_good',20,'Balanced, documented decision.','قرار متوازن وموثّق.'),O('Decline without discussing alternatives','ارفض من غير بدائل','end_mid',5,'Safe but may lose a good client; consider structure.','آمن بس ممكن تخسر عميل كويس؛ فكّر في الهيكلة.')]),
risk:N('Two months later the client breaches covenants. The audit asks who reviewed the stress case.','بعد شهرين العميل كسر التعهدات. المراجعة بتسأل مين راجع حالة الضغط.',[O('Finish the case','اقفل الحالة','end_bad',0,'','')])}},
close:{t:T('Month-end close with Cowork','إقفال الشهر بـ Cowork'),s:{
start:N('It is day 1 of close. You want Cowork to prepare bank recs, accruals and the variance memo.','النهارده أول يوم إقفال. عايز Cowork يجهّز مطابقات البنوك والمستحقات ومذكرة الانحرافات.',[O('Copy the folder and ask for the plan first','انسخ الفولدر واطلب الخطة الأول','plan',20,'Copies + plan approval = safe start.','نسخة + موافقة على الخطة = بداية آمنة.'),O('Point Cowork at the live finance drive','وجّه Cowork على درايف المالية الأصلي','live',-15,'Risky: agents should work on copies.','خطر: الوكلاء يشتغلوا على نسخ.')]),
plan:N('The plan proposes posting accrual entries directly in the ERP via MCP.','الخطة بتقترح ترحيل قيود المستحقات مباشرة في الـ ERP عبر MCP.',[O('Change it to draft entries for controller approval','غيّرها لمسودات قيود لموافقة الكنترولر','review',20,'Human approval before posting.','موافقة بشرية قبل الترحيل.'),O('Allow posting to save a day','اسمح بالترحيل علشان توفّر يوم','end_mid',-5,'Fast, but no control evidence for auditors.','سريع بس مفيش دليل رقابة للمراجعين.')]),
review:N('Outputs arrive. One variance explanation cites a number not in the TB.','المخرجات وصلت. شرح انحراف واحد فيه رقم مش موجود في الميزان.',[O('Ask Claude to trace every number to its source and fix','اطلب من Claude يتتبع كل رقم لمصدره ويصلّح','end_good',20,'Verification closes the loop.','التحقق بيقفل الحلقة.'),O('Send the pack — it is one small number','ابعت الحزمة — رقم صغير','end_mid',-5,'Small errors erode trust in the whole pack.','الأخطاء الصغيرة بتهز الثقة في الحزمة كلها.')]),
live:N('Cowork renames files in the live folder; a colleague cannot find the TB.','Cowork غيّر أسماء ملفات في الفولدر الأصلي؛ وزميلك مش لاقي الميزان.',[O('Restore and start again on a copy','رجّع واشتغل على نسخة','start',0,'','')])}}};
const CS_END={end_good:T('Excellent outcome — controlled, accurate and fast.','نتيجة ممتازة — تحت السيطرة ودقيقة وسريعة.'),end_mid:T('Acceptable outcome — but a control was skipped.','نتيجة مقبولة — بس في ضابط اتساب.'),end_bad:T('Poor outcome — review the lesson and try again.','نتيجة ضعيفة — راجع الدرس وجرّب تاني.')};
let CSS_={k:'lc',node:'start',pts:0,log:[]};
function vCsim(){crumb(L(UX6.csim));const ar=LANG==='ar';const sc=CSIM[CSS_.k];let h=`<h1>🧭 ${L(UX6.csim)}</h1><p class="lede">${ar?'اختار الحالة واتخذ القرارات. كل اختيار بيغيّر الطريق والنتيجة.':'Pick a case and make the decisions. Every choice changes the path and the outcome.'}</p><div class="chips">${Object.keys(CSIM).map(k=>`<button class="chip ${CSS_.k===k?'on':''}" data-cs="case:${k}">${L(CSIM[k].t)}</button>`).join('')}</div>`;
h+=`<div class="cslog">${CSS_.log.map(l=>`<div class="csl"><b>${esc(l.c)}</b><span class="${l.p>0?'ok':l.p<0?'no':''}">${l.p>0?'+':''}${l.p} · ${esc(l.f)}</span></div>`).join('')}</div>`;
if(CSS_.node.startsWith('end')){const g=CSS_.node;h+=`<div class="csend ${g}"><h2>${L(CS_END[g])}</h2><p>${ar?'النقط':'Score'}: <b>${CSS_.pts}</b></p><button class="btn-gold" data-cs="restart">${ar?'العب تاني':'Play again'}</button></div>`;return h}
const nd=sc.s[CSS_.node];return h+`<div class="csnode"><p>${L(nd.t)}</p><div class="csopts">${nd.o.map((o,i)=>`<button class="csopt" data-cs="pick:${i}">${L(o.t)}</button>`).join('')}</div><div class="k">${ar?'النقط':'Score'}: ${CSS_.pts}</div></div>`}
// ===== 2. Achievement card =====
async function makeCard(){const ar=LANG==='ar';const c=document.createElement('canvas');c.width=1200;c.height=627;const x=c.getContext('2d');try{await document.fonts.load('700 40px "Readex Pro"')}catch(e){}
x.fillStyle='#13284B';x.fillRect(0,0,1200,627);x.strokeStyle='rgba(255,255,255,.05)';for(let i=0;i<1200;i+=28){x.beginPath();x.moveTo(i,0);x.lineTo(i,627);x.stroke()}for(let j=0;j<627;j+=28){x.beginPath();x.moveTo(0,j);x.lineTo(1200,j);x.stroke()}
x.beginPath();x.arc(1120,40,170,0,7);x.strokeStyle='rgba(217,180,74,.15)';x.lineWidth=46;x.stroke();
const s=stats();const t=tier(s.quizAvg);x.direction=ar?'rtl':'ltr';x.textAlign=ar?'right':'left';const X=ar?1110:90;
x.fillStyle='#F1D27A';x.font='700 28px Amiri, serif';x.fillText(ar?'شهادة إنجاز · Claude Mastery':'Achievement · Claude Mastery',X,110);
x.fillStyle='#fff';x.font='700 64px "Readex Pro", Arial';x.fillText(ST.name||(ar?'اسمك':'Your name'),X,200);
x.fillStyle='#C7D1E2';x.font='400 30px "Readex Pro", Arial';x.fillText(ar?`خلّصت ${s.pct}% من المنهج · ${s.lessons} درس`:`Completed ${s.pct}% of the curriculum · ${s.lessons} lessons`,X,265);
x.fillText(ar?`${s.xp} نقطة · ${BADGES.filter(b=>b[3](s)).length} شارات · متوسط الاختبارات ${s.quizAvg}%`:`${s.xp} XP · ${BADGES.filter(b=>b[3](s)).length} badges · quiz average ${s.quizAvg}%`,X,315);
x.fillStyle=t[2];x.beginPath();x.arc(ar?1040:160,440,70,0,7);x.fill();x.fillStyle='#13284B';x.textAlign='center';x.font='700 26px "Readex Pro", Arial';x.fillText(t[0].toUpperCase(),ar?1040:160,450);
x.textAlign=ar?'right':'left';x.fillStyle='#fff';x.font='400 24px "Readex Pro", Arial';x.fillText(ar?'مع د. سارة سالم — خبيرة AI في المالية':'With Dr. Sara Salem — AI Finance Expert',ar?940:260,445);
const q=new Image();q.src='data:image/png;base64,'+(await svgPng(QR_PLATFORM)).split(',')[1];await new Promise(r=>q.onload=r);x.fillStyle='#fff';x.fillRect(ar?60:1000,420,150,150);x.drawImage(q,ar?65:1005,425,140,140);
return await new Promise(r=>c.toBlob(r,'image/png'))}
function vCard(){crumb(L(UX6.card));const ar=LANG==='ar';const s=stats();const post=ar?`خلّصت ${s.pct}% من كورس Claude Mastery مع د. سارة سالم 🎓\nاتعلمت أبني برومبت ماستر، وكلاء، وأتمتة شغل المالية بـ Claude.\n#Claude #AI #Finance`:`I've completed ${s.pct}% of Claude Mastery with Dr. Sara Salem 🎓\nI can now build master prompts, agents and finance automations with Claude.\n#Claude #AI #Finance`;const i=PSTORE.push(post)-1;
return `<h1>🏅 ${L(UX6.card)}</h1><p class="lede">${ar?'كارت بمقاس لينكدإن (1200×627) باسمك وتقدّمك وكود QR للمنصة.':'A LinkedIn-sized card (1200×627) with your name, progress and the platform QR code.'}</p><label class="pbf"><b>${ar?'الاسم':'Name'}</b><input class="search" id="cname" value="${esc(ST.name)}"></label><div class="row-btns"><button class="btn-gold" data-cardgo="png">⤓ PNG</button><button class="tbtn" data-cardgo="preview">${ar?'معاينة':'Preview'}</button></div><div id="cardprev" class="cardprev"></div><div class="prompt"><div class="ph"><h3>${ar?'نص البوست':'Post text'}</h3><button class="copy" data-i="${i}">${L(UI.copy)}</button></div><pre dir="auto">${esc(post)}</pre></div>`}
// ===== 3. Cheat sheet =====
function cheatHTML(n){const d=DAYS.find(x=>x.n==n);const ar=LANG==='ar';const w=WORDS.slice(0,4).map(g=>ar?g.w[0][1]:g.w[0][0]);
return `<div class="cheat" dir="${ar?'rtl':'ltr'}"><div class="chd"><div><div class="sig">${ar?'د. سارة سالم':'Dr. Sara Salem'} · Claude Mastery</div><h1>${L(UI.day)} ${d.n} · ${L(d.t)}</h1></div><div class="qr" style="width:70px">${QR_PLATFORM}</div></div><div class="cgrid">${d.units.map(u=>{const st=(L(u.steps)||[]).slice(0,3);return `<div class="cbox"><b>${u.id} ${L(u.t)}</b>${CEO[u.id]?`<p>${L(CEO[u.id])}</p>`:''}${st.length?`<ol>${st.map(s=>`<li>${s}</li>`).join('')}</ol>`:''}</div>`}).join('')}</div><div class="cfoot"><b>${ar?'هيكل البرومبت الماستر':'Master prompt skeleton'}:</b> &lt;role&gt; &lt;task&gt; &lt;context&gt; &lt;reasoning&gt; &lt;stop_when&gt; &lt;output_format&gt; · <b>${ar?'كلمات قوية':'Power words'}:</b> ${w.map(esc).join(' · ')}</div></div>`}
async function exportCheat(n,btn){const ar=LANG==='ar';const old=btn.textContent;btn.disabled=true;btn.textContent='…';try{await loadScript('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js',()=>window.html2canvas);await loadScript('https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js',()=>window.html2pdf);
const fr=document.createElement('iframe');fr.style.cssText='position:absolute;left:-12000px;top:0;width:1123px;height:794px;border:0';document.body.appendChild(fr);fr.srcdoc=`<!doctype html><html dir="${ar?'rtl':'ltr'}" data-theme="light"><head><meta charset="utf-8"><link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@400;600;700&family=Amiri:wght@700&display=swap" rel="stylesheet"><style>${document.querySelector('style').textContent} html,body{background:#fff;margin:0}</style></head><body>${cheatHTML(n)}</body></html>`;await new Promise(r=>fr.onload=r);try{await fr.contentDocument.fonts.ready}catch(e){}await new Promise(r=>setTimeout(r,300));const body=fr.contentDocument.body;
const canvas=await html2canvas(body,{scale:2,backgroundColor:'#fff',foreignObjectRendering:true,windowWidth:1123,width:1123,height:Math.max(794,body.scrollHeight)});fr.remove();const blob=await html2pdf().set({margin:0,jsPDF:{unit:'px',format:[1123,Math.max(794,canvas.height/2)],orientation:'landscape',hotfixes:['px_scaling']},image:{type:'jpeg',quality:.92}}).from(canvas,'canvas').outputPdf('blob');await saveFile(`Cheat-sheet-Module-${n}-${LANG.toUpperCase()}.pdf`,blob);btn.textContent='✓'}catch(e){console.error(e);btn.textContent=ar?'حصلت مشكلة':'Failed'}btn.disabled=false;setTimeout(()=>btn.textContent=old,2000)}
// ===== 4. Cohort =====
function myProgress(){return {name:ST.name||'Learner',date:new Date().toISOString(),done:DONE,xp:ST.xp,quiz:ST.quiz,streak:streak(),pct:pct(),badges:BADGES.filter(b=>b[3](stats())).map(b=>b[0])}}
let COH=(()=>{try{return JSON.parse(localStorage.getItem('cm_cohort')||'[]')}catch(e){return []}})();const saveCOH=()=>{try{localStorage.setItem('cm_cohort',JSON.stringify(COH))}catch(e){}};
function vCohort(){crumb(L(UX6.cohort));const ar=LANG==='ar';const all=DAYS.reduce((a,d)=>a+d.units.length,0);const qa=q=>{const v=Object.values(q||{});return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0};
return `<h1>👥 ${L(UX6.cohort)}</h1><p class="lede">${ar?'كل متدرب بيصدّر ملف تقدّمه، والمدرّب بيستورد الملفات هنا ويشوف الدفعة كلها. الملفات بتفضل على جهازك.':'Each learner exports a progress file; the instructor imports the files here to see the whole cohort. Files stay on your device.'}</p>
<div class="twocol"><div class="abpane"><h3>${ar?'للمتدرب':'For learners'}</h3><label class="pbf"><b>${ar?'اسمك':'Your name'}</b><input class="search" id="cname" value="${esc(ST.name)}"></label><button class="btn-gold" data-coh="export">⤓ ${ar?'صدّر ملف تقدّمي':'Export my progress file'}</button><p class="note">${ar?'ابعته للمدرّب على الإيميل أو واتساب.':'Send it to your instructor by email or WhatsApp.'}</p></div>
<div class="abpane"><h3>${ar?'للمدرّب':'For the instructor'}</h3><label class="filebtn">${ar?'استورد ملفات المتدربين (.json)':'Import learner files (.json)'}<input type="file" id="cohfile" accept=".json" multiple></label><div class="row-btns">${COH.length?`<button class="tbtn" data-coh="csv">⤓ CSV</button><button class="tbtn" data-coh="clear">${ar?'امسح الدفعة':'Clear cohort'}</button>`:''}</div></div></div>
${COH.length?`<div class="stat4"><div><b>${COH.length}</b>${ar?'متدرب':'learners'}</div><div><b>${Math.round(COH.reduce((a,c)=>a+(c.done||[]).length,0)/COH.length*100/all)}%</b>${ar?'متوسط الإنجاز':'avg completion'}</div><div><b>${Math.round(COH.reduce((a,c)=>a+qa(c.quiz),0)/COH.length)}%</b>${ar?'متوسط الاختبارات':'avg quiz'}</div><div><b>${COH.filter(c=>(c.done||[]).length>=all).length}</b>${ar?'خلّصوا':'completed'}</div></div>
<div class="tablewrap"><table><tr><th>${ar?'المتدرب':'Learner'}</th><th>${ar?'الإنجاز':'Progress'}</th><th>${ar?'الاختبارات':'Quizzes'}</th><th>XP</th><th>🔥</th><th>${ar?'آخر تحديث':'Updated'}</th><th>${ar?'الموديول الأضعف':'Needs help in'}</th></tr>${COH.sort((a,b)=>(b.done||[]).length-(a.done||[]).length).map(c=>{const pc=Math.round(100*(c.done||[]).length/all);const weak=DAYS.map(d=>[d.n,d.units.filter(u=>(c.done||[]).includes(u.id)).length/d.units.length]).sort((a,b)=>a[1]-b[1])[0];return `<tr><td><b>${esc(c.name)}</b></td><td><div class="mp2"><i style="width:${pc}%"></i></div>${pc}%</td><td>${qa(c.quiz)}%</td><td>${c.xp||0}</td><td>${c.streak||0}</td><td>${(c.date||'').slice(0,10)}</td><td>${L(UI.day)} ${weak[0]}</td></tr>`}).join('')}</table></div>`:''}`}
// ===== 5. Policy generator =====
let POL={org:'',country:'Egypt',reg:'CBE',law:'Law 151/2020',plan:'Team',tools:'Claude (chat, Projects, Cowork, Claude for Excel)',banned:'Uploading client personal data to personal accounts; automated decisions about people',owner:'',contact:'',disclose:true,train:true};
function polText(){const ar=LANG==='ar';const p=POL;const o=p.org||(ar?'[اسم المؤسسة]':'[Organisation]');
return ar?`# سياسة استخدام الذكاء الاصطناعي — ${o}\n\nالإصدار 1.0 · ${new Date().toISOString().slice(0,10)} · مالك السياسة: ${p.owner||'[المسؤول]'}\n\n## 1. الغرض والنطاق\nتنظّم السياسة دي استخدام أدوات الذكاء الاصطناعي في ${o} (${p.country}) لكل الموظفين والمتعاقدين.\n\n## 2. الأدوات المسموحة\n${p.tools} على خطة ${p.plan} بإعدادات المؤسسة فقط.\n\n## 3. تصنيف البيانات\n- عام وداخلي: مسموح.\n- سري: مسموح على خطة المؤسسة مع إخفاء الهوية لما ينفع.\n- مقيّد (أرقام هوية، حسابات، بيانات صحية): ممنوع.\nالالتزام بـ ${p.law} وتعليمات ${p.reg}.\n\n## 4. الاستخدامات الممنوعة\n${p.banned}.\n\n## 5. مستويات الخطر والموافقات\n- منخفض: مراجعة ذاتية.\n- متوسط: مراجعة زميل.\n- عالي (العملاء، الائتمان، الأفراد، التقارير الرقابية): موافقة بشرية موثقة ومراجعة دورية.\nكل حالة استخدام بتتسجل في سجل حالات الاستخدام.\n\n## 6. الدقة والمساءلة\nكل مخرج ليه مسؤول بالاسم؛ والأرقام والمراجع لازم تتراجع على المصادر.\n\n## 7. الوكلاء والأتمتة\nالوكلاء بيشتغلوا على نسخ وبأقل صلاحيات؛ وأي إرسال أو نشر أو دفع أو ترحيل محتاج موافقة.\n${p.disclose?'\n## 8. الإفصاح\nبيتوضح استخدام الـ AI في المحتوى المنشور والشغل المقدم للعملاء والأبحاث الأكاديمية.\n':''}${p.train?'\n## 9. التدريب\nكل مستخدم بيخلّص تدريب أساسي قبل الاستخدام وبيوقّع على السياسة.\n':''}\n## 10. الحوادث\nأي حادث يتبلّغ فوراً لـ ${p.contact||'[جهة الاتصال]'}: وقف ← احتواء ← تقييم ← إبلاغ حسب القانون ← تصحيح ← تعلّم.\n\n## 11. المراجعة\nالسياسة بتتراجع سنوياً أو مع أي تغيير رقابي أو تقني.\n\n> مسودة — تتراجع من الإدارة القانونية قبل الاعتماد.`
:`# AI Use Policy — ${o}\n\nVersion 1.0 · ${new Date().toISOString().slice(0,10)} · Policy owner: ${p.owner||'[Owner]'}\n\n## 1. Purpose and scope\nThis policy governs the use of AI tools at ${o} (${p.country}) by all employees and contractors.\n\n## 2. Approved tools\n${p.tools} on the ${p.plan} plan with organisation settings only.\n\n## 3. Data classification\n- Public and internal: allowed.\n- Confidential: allowed on the organisation plan, anonymised where possible.\n- Restricted (ID numbers, account numbers, health data): prohibited.\nComply with ${p.law} and ${p.reg} requirements.\n\n## 4. Prohibited uses\n${p.banned}.\n\n## 5. Risk tiers and approvals\n- Low: self-review.\n- Medium: peer review.\n- High (customers, credit, people, regulatory filings): documented human approval and periodic audit.\nEvery use case is recorded in the AI use-case register.\n\n## 6. Accuracy and accountability\nEvery output has a named owner; numbers and references are verified against sources.\n\n## 7. Agents and automation\nAgents work on copies with least privilege; any send, post, payment or ledger posting requires approval.\n${p.disclose?'\n## 8. Disclosure\nAI use is disclosed in published content, client deliverables and academic work.\n':''}${p.train?'\n## 9. Training\nEvery user completes basic training before use and signs this policy.\n':''}\n## 10. Incidents\nReport incidents immediately to ${p.contact||'[Contact]'}: stop → contain → assess → notify as required by law → fix → learn.\n\n## 11. Review\nReviewed annually or after any regulatory or technical change.\n\n> Draft — to be reviewed by Legal before approval.`}
function vPolicy(){crumb(L(UX6.policy));const ar=LANG==='ar';const F=[['org',T('Organisation','المؤسسة')],['country',T('Country','الدولة')],['reg',T('Regulator','الجهة الرقابية')],['law',T('Data-protection law','قانون حماية البيانات')],['plan',T('Claude plan','خطة Claude')],['tools',T('Approved tools','الأدوات المسموحة')],['banned',T('Prohibited uses','الاستخدامات الممنوعة')],['owner',T('Policy owner','مالك السياسة')],['contact',T('Incident contact','جهة الإبلاغ عن الحوادث')]];const t=polText();const i=PSTORE.push(t)-1;window._poli=i;
return `<h1>📜 ${L(UX6.policy)}</h1><p class="lede">${ar?'جاوب على البيانات دي وهتطلع مسودة سياسة AI كاملة تصدّرها.':'Answer these fields to get a complete AI policy draft you can export.'}</p><div class="twocol"><div class="abpane">${F.map(f=>`<label class="pbf"><b>${L(f[1])}</b><input class="search" data-pol="${f[0]}" value="${esc(POL[f[0]])}"></label>`).join('')}<label class="opt"><input type="checkbox" data-polc="disclose" ${POL.disclose?'checked':''}> ${ar?'إفصاح عن استخدام الـ AI':'Disclosure section'}</label><label class="opt"><input type="checkbox" data-polc="train" ${POL.train?'checked':''}> ${ar?'تدريب إلزامي':'Mandatory training'}</label></div><div><div class="prompt"><div class="ph"><h3>${ar?'المسودة':'Draft'}</h3><button class="copy" data-i="${i}">${L(UI.copy)}</button></div><pre id="polout" dir="auto">${esc(t)}</pre></div><div class="row-btns"><button class="tbtn" data-polx="md">⤓ .md</button><button class="tbtn" data-polx="html">⤓ .html</button>${mailBtns('AI policy draft',t)}<button class="tbtn" data-go="register">🗂 ${L(UX5.reg)}</button></div></div></div>`}
// ===== 6. Workflow designer =====
let WF=Object.assign({name:'',steps:[{who:'Finance',what:'Export TB and bank statements',sys:'ERP',appr:false},{who:'Claude (Cowork)',what:'Prepare recs, accruals and variance memo',sys:'Cowork',appr:false},{who:'Controller',what:'Review and approve drafts',sys:'Email',appr:true}],sched:''},ST.wf||{});
function wfMermaid(){return 'flowchart '+(LANG==='ar'?'RL':'LR')+'\n'+WF.steps.map((s,i)=>`  S${i}["${(s.who+': '+s.what).replace(/"/g,"'")}"]`).join('\n')+'\n'+WF.steps.slice(1).map((s,i)=>`  S${i} --> S${i+1}`).join('\n')}
function wfBrief(){return `${WF.name||'[Workflow]'}\n\nRun this workflow:\n${WF.steps.map((s,i)=>`${i+1}. ${s.who} — ${s.what} (${s.sys})${s.appr?' — STOP for human approval':''}`).join('\n')}\n\nRules: show the plan first; work on copies; save outputs to /output; ask before send, post, pay, delete.${WF.sched?'\nSchedule: '+WF.sched:''}`}
function vWF(){crumb(L(UX6.wf));const ar=LANG==='ar';const b=wfBrief();const i=PSTORE.push(b)-1;window._wfi=i;
return `<h1>🔀 ${L(UX6.wf)}</h1><p class="lede">${ar?'ارسم سير العمل خطوة خطوة، وخد مخطط Mermaid وتكليف Cowork جاهز.':'Lay out the workflow step by step and get a Mermaid diagram and a ready Cowork brief.'}</p><label class="pbf"><b>${ar?'اسم سير العمل':'Workflow name'}</b><input class="search" data-wfn="name" value="${esc(WF.name)}" placeholder="Month-end close"></label>
<div class="wfsteps">${WF.steps.map((s,k)=>`<div class="wfs"><span class="n">${k+1}</span><input data-wf="${k}:who" value="${esc(s.who)}" placeholder="${ar?'مين':'Who'}"><input data-wf="${k}:what" value="${esc(s.what)}" placeholder="${ar?'بيعمل إيه':'Does what'}"><input data-wf="${k}:sys" value="${esc(s.sys)}" placeholder="${ar?'النظام':'System'}"><label class="opt"><input type="checkbox" data-wfa="${k}" ${s.appr?'checked':''}>🛡</label><button class="tbtn" data-wfdel="${k}">✕</button></div>`).join('')}<button class="tbtn" data-wfadd="1">+ ${ar?'خطوة':'Step'}</button></div>
<div class="flow" style="margin:14px 0">${WF.steps.map((s,k)=>`<span class="${s.appr?'hl':''}">${esc(s.who)}: ${esc(s.what)}</span>${k<WF.steps.length-1?(ar?'←':'→'):''}`).join('')}</div>
<label class="pbf"><b>${ar?'الجدولة (اختياري)':'Schedule (optional)'}</b><input class="search" data-wfn="sched" value="${esc(WF.sched)}" placeholder="Every month, day 1 at 08:00"></label>
<div class="twocol"><div class="prompt"><div class="ph"><h3>${ar?'تكليف Cowork':'Cowork brief'}</h3><button class="copy" data-i="${i}">${L(UI.copy)}</button></div><pre id="wfout" dir="auto">${esc(b)}</pre></div><div class="prompt"><div class="ph"><h3>Mermaid</h3></div><pre dir="ltr" style="text-align:left" id="wfmm">${esc(wfMermaid())}</pre></div></div><div class="row-btns"><button class="tbtn" data-wfx="1">⤓ .md</button></div>`}
// ===== 7. MCP connector planner =====
let MP2=Object.assign({sys:'ERP',name:'',ents:'invoices, customers, trial balance, aging',ops:{read:true,draft:false,write:false},auth:'OAuth 2.0 (Entra ID)'},ST.mcpp||{});
function mcpTools(){const e=MP2.ents.split(',').map(s=>s.trim()).filter(Boolean);const t=[];e.forEach(x=>{const k=x.replace(/[^a-z0-9]+/gi,'_').toLowerCase();if(MP2.ops.read){t.push([`get_${k}`,'read',`Read-only. Return ${x} with filters (period, entity, id).`]);t.push([`search_${k}`,'read',`Read-only. Search ${x} by keyword and date range.`])}if(MP2.ops.draft)t.push([`create_draft_${k}`,'draft',`Create a DRAFT ${x} record; needs human approval to finalise.`]);if(MP2.ops.write)t.push([`update_${k}`,'write',`Update ${x}. Destructive — approval id required.`])});return t}
function mcpCode(){const n=(MP2.name||MP2.sys).toLowerCase().replace(/[^a-z0-9]+/g,'-');return `from mcp.server.fastmcp import FastMCP\n\nmcp = FastMCP("${n}")\n\n`+mcpTools().map(([f,k,d])=>`@mcp.tool(annotations={"readOnlyHint": ${k==='read'?'True':'False'}, "destructiveHint": ${k==='write'?'True':'False'}})\ndef ${f}(${k==='read'?'filters: dict':'data: dict'}) -> dict:\n    """${d}"""\n    user = current_user()            # from OAuth token\n    require_permission(user, "${f}")  # authorization\n    audit_log(user, "${f}", ${k==='read'?'filters':'data'})\n    ${k==='read'?'return query(filters)':k==='draft'?'return create_draft(data)':'require_approval(data["approval_id"])\n    return update(data)'}\n`).join('\n')+`\nif __name__ == "__main__":\n    mcp.run(transport="streamable-http")\n`}
function vMCPP(){crumb(L(UX6.mcpp));const ar=LANG==='ar';const tools=mcpTools();const code=mcpCode();const ci=PSTORE.push(code)-1;window._mpci=ci;
const ctrls=[[T('Authentication','التوثيق'),MP2.auth],[T('Authorization','الصلاحيات'),T('User’s own ERP role enforced server-side','دور المستخدم في النظام بيتطبّق في السيرفر')],[T('Tool scoping','تحديد الأدوات'),T(`${tools.filter(t=>t[1]==='read').length} read · ${tools.filter(t=>t[1]!=='read').length} write/draft · no free-text SQL`,`${tools.filter(t=>t[1]==='read').length} قراءة · ${tools.filter(t=>t[1]!=='read').length} كتابة/مسودة · من غير SQL حر`)],[T('Sandboxing','العزل'),T('Server isolated; outbound allow-list only','سيرفر معزول؛ خروج للشبكة بقائمة مسموحة بس')],[T('Auditing','التدقيق'),T('Every call logged: user, tool, parameters, result size','كل نداء متسجل: المستخدم، الأداة، المعاملات، حجم النتيجة')],[T('Human approval','الموافقة البشرية'),MP2.ops.write||MP2.ops.draft?T('Drafts and writes need approval id','المسودات والكتابة محتاجين رقم موافقة'):T('Read-only — no actions','قراءة بس — مفيش إجراءات')]];
const risk=MP2.ops.write?'high':MP2.ops.draft?'medium':'low';
return `<h1>🔌 ${L(UX6.mcpp)}</h1><p class="lede">${ar?'حدد النظام والبيانات والعمليات، وخد قائمة الأدوات وضوابط الأمان الستة وكود سيرفر MCP مبدئي.':'Choose the system, data and operations to get the tool list, the six security controls and a starter MCP server.'}</p>
<div class="twocol"><div class="abpane"><label class="pbf"><b>${ar?'النظام':'System'}</b><select data-mp="sys">${['ERP','CRM','Data warehouse','Google Drive / SharePoint','Ticketing','Custom API'].map(s=>`<option ${MP2.sys===s?'selected':''}>${s}</option>`).join('')}</select></label><label class="pbf"><b>${ar?'اسم السيرفر':'Server name'}</b><input class="search" data-mp="name" value="${esc(MP2.name)}" placeholder="mini-erp"></label><label class="pbf"><b>${ar?'البيانات (مفصولة بفاصلة)':'Data entities (comma-separated)'}</b><input class="search" data-mp="ents" value="${esc(MP2.ents)}"></label><b>${ar?'العمليات':'Operations'}</b>${[['read',T('Read','قراءة')],['draft',T('Create drafts','إنشاء مسودات')],['write',T('Update / write','تعديل / كتابة')]].map(o=>`<label class="opt"><input type="checkbox" data-mpo="${o[0]}" ${MP2.ops[o[0]]?'checked':''}> ${L(o[1])}</label>`).join('')}<label class="pbf"><b>${ar?'التوثيق':'Authentication'}</b><input class="search" data-mp="auth" value="${esc(MP2.auth)}"></label><div class="rgtier t-${risk}"><b>${ar?'مستوى الخطر':'Risk tier'}: ${risk}</b></div></div>
<div><div class="tablewrap"><table><tr><th>${ar?'الأداة':'Tool'}</th><th>${ar?'النوع':'Type'}</th><th>${ar?'الوصف':'Description'}</th></tr>${tools.map(t=>`<tr><td dir="ltr"><code>${t[0]}</code></td><td><span class="tier t-${t[1]==='read'?'low':t[1]==='draft'?'medium':'high'}">${t[1]}</span></td><td>${t[2]}</td></tr>`).join('')}</table></div><h3>${ar?'ضوابط الأمان':'Security controls'}</h3><div class="tablewrap"><table>${ctrls.map(c=>`<tr><td><b>${L(c[0])}</b></td><td>${typeof c[1]==='string'?esc(c[1]):L(c[1])}</td></tr>`).join('')}</table></div></div></div>
<div class="prompt"><div class="ph"><h3>server.py</h3><button class="copy" data-i="${ci}">${L(UI.copy)}</button></div><pre dir="ltr" style="text-align:left">${esc(code)}</pre></div><div class="row-btns"><button class="tbtn" data-mpx="py">⤓ server.py</button><button class="tbtn" data-mpx="md">⤓ ${ar?'خطة كاملة .md':'Full plan .md'}</button><button class="tbtn" data-go="deep/mcpsec">🔐 ${L(DEEP.mcpsec.t)}</button></div>`}
// ===== 8. Prompt packs =====
function vPacks(){crumb(L(UX6.packs));const ar=LANG==='ar';return `<h1>📦 ${L(UX6.packs)}</h1><p class="lede">${ar?'شارك برومبتاتك مع فريقك: صدّر حزمة JSON، أو استورد حزمة من زميل.':'Share prompts with your team: export a JSON pack, or import a colleague’s pack.'}</p>
<div class="twocol"><div class="abpane"><h3>${ar?'صدّر':'Export'}</h3><label class="pbf"><b>${ar?'اسم الحزمة':'Pack name'}</b><input class="search" id="packname" value="${esc(ST.packName||'My prompt pack')}"></label><button class="btn-gold" data-pack="mine">⤓ ${ar?`برومبتاتي المحفوظة (${ST.mine.length})`:`My saved prompts (${ST.mine.length})`}</button><button class="tbtn" data-pack="lab">⤓ ${ar?'كل برومبتات المعمل':'All lab prompts'} (${LAB.length})</button><button class="tbtn" data-pack="studio">⤓ ${ar?'برومبت الاستوديو الحالي':'Current studio prompt'}</button></div>
<div class="abpane"><h3>${ar?'استورد':'Import'}</h3><label class="filebtn">${ar?'اختار ملف حزمة (.json)':'Choose a pack file (.json)'}<input type="file" id="packfile" accept=".json"></label><p class="note" id="packnote">${ar?'البرومبتات المستوردة بتتضاف لـ "المحفوظ" في الاستوديو.':'Imported prompts are added to Saved in the studio.'}</p><button class="tbtn" data-labtab="studio">🎛 ${L(UX3.studio)}</button></div></div>`}
// ===== 9. Glossary with search =====
let GQ='';
function vGloss(){crumb(L(UI.gloss));const ar=LANG==='ar';const q=GQ.toLowerCase();const list=GLOSS.filter(g=>!q||g.join(' ').toLowerCase().includes(q));
return `<h1>Aa ${L(UI.gloss)}</h1><input class="search" id="gq" value="${esc(GQ)}" placeholder="${ar?'ابحث في القاموس… (عربي أو إنجليزي)':'Search the glossary… (English or Arabic)'}"><p class="note">${list.length}/${GLOSS.length}</p><div class="tablewrap"><table><tr><th>English</th><th>العربية</th><th>${ar?'المعنى':'Meaning'}</th></tr>${list.map(g=>`<tr><td><b>${g[0]}</b></td><td>${g[1]}</td><td>${ar?g[3]:g[2]}</td></tr>`).join('')}</table></div>`}
// ===== events =====
function ui4Click(e){const g=s=>e.target.closest(s);let x;
if(x=g('[data-cs]')){const [a,v]=x.dataset.cs.split(':');if(a==='case')CSS_={k:v,node:'start',pts:0,log:[]};if(a==='restart')CSS_={k:CSS_.k,node:'start',pts:0,log:[]};if(a==='pick'){const nd=CSIM[CSS_.k].s[CSS_.node];const o=nd.o[+v];CSS_.pts+=o.pts;if(L(o.fb))CSS_.log.push({c:L(o.t),p:o.pts,f:L(o.fb)});CSS_.node=o.to;if(o.to.startsWith('end')){ST.sims++;saveST();addXP(Math.max(0,CSS_.pts/4|0))}}render();return true}
if(x=g('[data-cardgo]')){makeCard().then(b=>{if(x.dataset.cardgo==='png')saveFile('Claude-Mastery-Achievement.png',b);else{const u=URL.createObjectURL(b);document.getElementById('cardprev').innerHTML=`<img src="${u}" alt="">`}});return true}
if(x=g('[data-cheat]')){exportCheat(+x.dataset.cheat,x);return true}
if(x=g('[data-coh]')){const a=x.dataset.coh;if(a==='export')saveFile(`progress-${(ST.name||'learner').replace(/\s+/g,'-')}.json`,JSON.stringify(myProgress(),null,1));if(a==='clear'){COH=[];saveCOH();render()}if(a==='csv'){const all=DAYS.reduce((s,d)=>s+d.units.length,0);saveFile('cohort.csv',BOM+'name,progress_pct,lessons_done,xp,streak,updated\n'+COH.map(c=>[c.name,Math.round(100*(c.done||[]).length/all),(c.done||[]).length,c.xp||0,c.streak||0,(c.date||'').slice(0,10)].map(csvq).join(',')).join('\n'))}return true}
if(x=g('[data-polx]')){const t=polText();if(x.dataset.polx==='md')saveFile('AI-policy.md',t);else saveFile('AI-policy.html',`<!doctype html><meta charset="utf-8"><body dir="${LANG==='ar'?'rtl':'ltr'}" style="font-family:Arial;max-width:800px;margin:40px auto;line-height:1.7">`+esc(t).replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/\n/g,'<br>'));return true}
if(x=g('[data-wfadd]')){WF.steps.push({who:'',what:'',sys:'',appr:false});saveWF();render();return true}
if(x=g('[data-wfdel]')){WF.steps.splice(+x.dataset.wfdel,1);saveWF();render();return true}
if(x=g('[data-wfx]')){saveFile('workflow.md',`# ${WF.name||'Workflow'}\n\n\`\`\`mermaid\n${wfMermaid()}\n\`\`\`\n\n## Cowork brief\n\n${wfBrief()}\n`);return true}
if(x=g('[data-mpx]')){if(x.dataset.mpx==='py')saveFile('server.py',mcpCode());else saveFile('mcp-plan.md',`# MCP connector plan — ${MP2.name||MP2.sys}\n\n## Tools\n${mcpTools().map(t=>`- \`${t[0]}\` (${t[1]}): ${t[2]}`).join('\n')}\n\n## Security controls\n- Authentication: ${MP2.auth}\n- Authorization: user's own role enforced server-side\n- Tool scoping: read-only first; no free-text SQL\n- Sandboxing: isolated server; outbound allow-list\n- Auditing: log every call\n- Human approval: approval id for drafts/writes\n\n## Starter code\n\n\`\`\`python\n${mcpCode()}\`\`\`\n`);return true}
if(x=g('[data-pack]')){const a=x.dataset.pack;const name=(document.getElementById('packname')||{}).value||'Prompt pack';ST.packName=name;saveST();let items=[];if(a==='mine')items=ST.mine.map(m=>({title:m.t,prompt:m.p}));if(a==='lab')items=LAB.map(c=>({title:L(c.t),prompt:L(c.p),data:c.data}));if(a==='studio')items=[{title:SU.task||SU.goal||'Studio prompt',prompt:suPrompt()}];saveFile(name.replace(/\s+/g,'-')+'.json',JSON.stringify({type:'claude-mastery-prompt-pack',version:1,name,author:ST.name||'',created:new Date().toISOString(),items},null,1));return true}
return false}
function saveWF(){ST.wf=WF;saveST()}
document.addEventListener('input',e=>{const t=e.target;
if(t.dataset.pol){POL[t.dataset.pol]=t.value;const o=document.getElementById('polout');if(o){o.textContent=polText();PSTORE[window._poli]=polText()}}
if(t.dataset.wf){const [k,f]=t.dataset.wf.split(':');WF.steps[+k][f]=t.value;saveWF();const o=document.getElementById('wfout');if(o){o.textContent=wfBrief();PSTORE[window._wfi]=wfBrief()}const m=document.getElementById('wfmm');if(m)m.textContent=wfMermaid()}
if(t.dataset.wfn){WF[t.dataset.wfn]=t.value;saveWF();const o=document.getElementById('wfout');if(o){o.textContent=wfBrief();PSTORE[window._wfi]=wfBrief()}}
if(t.dataset.mp&&t.tagName!=='SELECT'){MP2[t.dataset.mp]=t.value;ST.mcpp=MP2;saveST()}
if(t.id==='gq'){GQ=t.value;const pos=t.selectionStart;render();const el=document.getElementById('gq');if(el){el.focus();el.setSelectionRange(pos,pos)}}});
document.addEventListener('change',async e=>{const t=e.target;
if(t.dataset.polc){POL[t.dataset.polc]=t.checked;render()}
if(t.dataset.wfa){WF.steps[+t.dataset.wfa].appr=t.checked;saveWF();render()}
if(t.dataset.mp&&t.tagName==='SELECT'){MP2[t.dataset.mp]=t.value;ST.mcpp=MP2;saveST();render()}
if(t.dataset.mpo){MP2.ops[t.dataset.mpo]=t.checked;ST.mcpp=MP2;saveST();render()}
if(t.dataset.mp&&t.tagName==='INPUT')render();
if(t.id==='cohfile'){for(const f of t.files){try{const j=JSON.parse(await f.text());if(j&&j.done){COH=COH.filter(c=>c.name!==j.name);COH.push(j)}}catch(err){}}saveCOH();render()}
if(t.id==='packfile'&&t.files[0]){try{const j=JSON.parse(await t.files[0].text());const items=(j.items||[]).filter(i=>i.prompt);items.forEach(i=>ST.mine.unshift({t:i.title||'Imported',d:new Date().toISOString().slice(0,10),p:i.prompt}));saveST();const n=document.getElementById('packnote');if(n)n.textContent=(LANG==='ar'?`اتضاف ${items.length} برومبت.`:`Imported ${items.length} prompts.`)}catch(err){const n=document.getElementById('packnote');if(n)n.textContent=LANG==='ar'?'الملف مش حزمة صالحة.':'This file is not a valid prompt pack.'}}});
// ===== Plugins catalogue inside skills library =====
const PLUGINS=[
['finance',T('Finance & accounting','المالية والمحاسبة'),'/journal-entry · /reconciliation · /variance-analysis · /financial-statements · /close-management · /audit-support · /sox-testing',T('Month-end close, reporting and audit support for finance teams.','الإقفال الشهري والتقارير ودعم المراجعة لفرق المالية.')],
['sales',T('Sales','المبيعات'),'daily-briefing · call-prep · draft-outreach · pipeline-review · forecast · deal-review · account-plan · win-loss-review …',T('The full selling cycle from research to forecast.','دورة البيع كاملة من البحث للتوقع.')],
['marketing',T('Marketing','التسويق'),'campaign-plan · content-creation · draft-content · email-sequence · seo-audit · competitive-brief · brand-review · performance-report',T('Campaigns, content and performance on brand.','الحملات والمحتوى والأداء على البراند.')],
['human-resources',T('HR','الموارد البشرية'),'draft-offer · interview-prep · onboarding · performance-review · comp-analysis · org-planning · people-report · policy-lookup · recruiting-pipeline',T('The people cycle from hiring to reviews.','دورة الأفراد من التوظيف للتقييم.')],
['data',T('Data','البيانات'),'analyze · explore-data · build-dashboard · create-viz · statistical-analysis · write-query · sql-queries · validate-data',T('From quick lookups to dashboards and SQL.','من البحث السريع للداشبوردات و SQL.')],
['design',T('Design','التصميم'),'user-research · ux-copy · design-critique · accessibility-review · design-system · design-handoff · research-synthesis',T('Research, critique and handoff for products.','بحث ونقد وتسليم للمنتجات.')],
['productivity',T('Productivity','الإنتاجية'),'start · task-management · memory-management · update',T('Tasks and workplace memory in one place.','المهام وذاكرة العمل في مكان واحد.')],
['valuation-reviewer',T('Private equity','الملكية الخاصة'),'ic-memo · returns-analysis · portfolio-monitoring · xlsx-author',T('IC memos, returns and portfolio reviews.','مذكرات الاستثمار والعوائد ومتابعة المحفظة.')],
['statement-auditor',T('Fund audit','مراجعة الصناديق'),'nav-tieout · audit-xls · xlsx-author',T('LP statement tie-outs and spreadsheet audits.','مطابقة كشوف المستثمرين ومراجعة الجداول.')],
['carta-investors',T('Venture funds (Carta)','صناديق رأس المال المخاطر (Carta)'),'explore-data · portfolio-analytics · fund-modeling · manco · lp reporting · spa-audit · agm-deck-builder …',T('Fund data, analytics and investor reporting on Carta.','بيانات الصناديق والتحليلات وتقارير المستثمرين على Carta.')],
['figma',T('Figma','Figma'),'design-to-code · generate-design · generate-library · generate-diagram · use-slides · use-figjam · code-connect …',T('Design and code in sync through Figma.','التصميم والكود متزامنين عبر Figma.')],
['10x-team',T('Engineering team','فريق الهندسة'),'cto · principal-architect · staff/senior engineer · sde · qa · dba · sre · security · devops · product-manager · engineering-manager',T('A full virtual engineering team for builds.','فريق هندسة افتراضي كامل للبناء.')],
['spice / together',T('Data & AI infrastructure','بنية البيانات والـ AI'),'Spice: datasets · connectors · sql · search · cloud · Together: chat · embeddings · fine-tuning · batch · evaluations · GPU clusters',T('Data federation and open-model infrastructure.','توحيد البيانات وبنية النماذج المفتوحة.')],
['cowork-plugin-management',T('Plugin building','بناء الـ Plugins'),'create-cowork-plugin · cowork-plugin-customizer',T('Create or tailor plugins for your team.','اعمل أو كيّف Plugins لفريقك.')]];
let SKVIEW='skills',PLQ='';const _vSkills=vSkills;
vSkills=function(){const ar=LANG==='ar';const tabs=`<div class="tabs big"><button class="tab ${SKVIEW==='skills'?'on':''}" data-skv="skills">✦ Skills (${SKILLS.reduce((a,g)=>a+g.items.length,0)})</button><button class="tab ${SKVIEW==='plugins'?'on':''}" data-skv="plugins">🧩 Plugins (${PLUGINS.length})</button></div>`;
if(SKVIEW==='skills')return _vSkills().replace('</p>','</p>'+tabs);crumb('Plugins');const q=PLQ.toLowerCase();const list=PLUGINS.filter(p=>!q||(p[0]+L(p[1])+p[2]+L(p[3])).toLowerCase().includes(q));
return `<h1>🧩 Plugins</h1><p class="lede">${ar?'الـ Plugin حزمة Skills وأوامر و Connectors لوظيفة كاملة. بتتثبت من Customize ← Plugins أو من Cowork.':'A plugin bundles skills, commands and connectors for a whole role. Install from Customize → Plugins or in Cowork.'}</p>${tabs}<input class="search" id="plq" value="${esc(PLQ)}" placeholder="${ar?'ابحث في الـ Plugins…':'Search plugins…'}"><div class="skgrid">${list.map(p=>`<div class="skc"><div class="skh"><span class="n">${p[0]}</span><span class="tag">${L(p[1])}</span></div><p>${L(p[3])}</p><div class="skrow"><b>${ar?'بيشمل':'Includes'}</b><span dir="ltr" style="text-align:start">${p[2]}</span></div></div>`).join('')}</div>`};
document.addEventListener('click',e=>{const x=e.target.closest('[data-skv]');if(x){SKVIEW=x.dataset.skv;render()}});
document.addEventListener('input',e=>{if(e.target.id==='plq'){PLQ=e.target.value;const pos=e.target.selectionStart;render();const el=document.getElementById('plq');if(el){el.focus();el.setSelectionRange(pos,pos)}}});
