const LINKEDIN="https://www.linkedin.com/in/sara-salem-57629b226";
const WORK=[
{t:T("CMA Budget Platform","منصة موازنات CMA"),src:"Chat",u:"https://claude.ai/artifact/Li6PhTLMksgr5ZpE52ytgv",d:T("Budgeting training platform for CMA learners (latest version).","منصة تدريب على الموازنات لدارسي CMA (آخر نسخة).")},
{t:T("CMA Budget Platform — earlier version","منصة موازنات CMA — نسخة سابقة"),src:"Chat",u:"https://claude.ai/artifact/Ge7L4fDU9241S7vM3BWwXL",d:T("First iteration of the CMA budgeting platform.","النسخة الأولى من منصة موازنات CMA.")},
{t:T("Credit Review — Project Finance & Portfolio","المراجعة الائتمانية — تمويل المشروعات والمحفظة"),src:"Chat",u:"https://claude.ai/artifact/71AkCGZmyGR3dwqb4nddcd",d:T("Borrower assessment and portfolio review workspace.","مساحة لتقييم المقترض ومراجعة المحفظة.")},
{t:T("DCF Duel","مبارزة DCF"),src:"Cowork",u:"https://claude.ai/artifact/DBeWDkG63w3xb9qfxVcwFw",d:T("Interactive DCF valuation built in Cowork.","تقييم DCF تفاعلي اتبنى في Cowork.")},
{t:T("Discount Engine — Live Prototype","محرك الخصومات — نموذج حي"),src:"Cowork",u:"https://claude.ai/artifact/TLazGzon4VMZYffoqw2WHS",d:T("Live pricing and discount prototype.","نموذج حي للتسعير والخصومات.")},
{t:T("Deal Engine Console","لوحة محرك الصفقات"),src:"Cowork",u:"https://claude.ai/artifact/Nki5to8Mvs7kuPGvMbFBQm",d:T("Deal evaluation console.","لوحة تقييم الصفقات.")},
{t:T("Interactive financial analysis dashboard","لوحة التحليل المالي التفاعلية"),src:"Chat",u:"https://claude.ai/artifact/8znEtUhEF2oqxCLTX5XRbr",d:T("Arabic financial ratios dashboard with file upload.","داشبورد نسب مالية بالعربي برفع ملفات.")},
{t:T("Receipt Transcription — AI School","تفريغ الإيصالات — AI School"),src:"Chat",u:"https://claude.ai/artifact/DwzqeXDDX9bMfMdazfFqQj",d:T("Receipt reading and transcription tool.","أداة قراءة وتفريغ الإيصالات.")},
{t:T("Design System","نظام التصميم"),src:"Chat",u:"https://claude.ai/artifact/U2v9RtpeXDCTM2Nmt9T1pG",d:T("Brand design system workspace.","مساحة نظام تصميم البراند.")},
{t:T("Design System — earlier version","نظام التصميم — نسخة سابقة"),src:"Chat",u:"https://claude.ai/artifact/8CT8CDfxxdwiZkZBLnpg2F",d:T("First design system draft.","أول مسودة لنظام التصميم.")},
{t:T("Untitled draft — 30 Sep","مسودة بدون عنوان — 30 سبتمبر"),src:"Chat",u:"https://claude.ai/artifact/XuaNRhPHL1F3XBD3MvwnCp",d:T("Work in progress.","شغل جاري.")},
{t:T("Untitled draft — 27 Sep","مسودة بدون عنوان — 27 سبتمبر"),src:"Chat",u:"https://claude.ai/artifact/6ZEhnrrbBoEQNsBug63H1L",d:T("Work in progress.","شغل جاري.")},
{t:T("Claude Mastery platform (this site)","منصة Claude Mastery (الموقع ده)"),src:"Chat",u:"https://claude.ai/artifact/SWKveDA1ZfXuaeRLhm1mu5",d:T("This bilingual course platform.","منصة الكورس ثنائية اللغة دي.")}
];
const PORTFOLIO=[
[T("Finance dashboards","داشبوردات مالية"),T("Executive Finance Dashboard (EN/AR, RTL), CFO financial statement analyzer, Working Capital (DSO/DIO/DPO/CCC), FP&A KPI dashboard with red-flags engine and PDF export, TMG budget dashboard, gold price and currency converter dashboards for Egypt.","داشبورد مالي تنفيذي (عربي/إنجليزي، RTL)، محلل قوائم مالية للمدير المالي، رأس المال العامل (DSO/DIO/DPO/CCC)، داشبورد مؤشرات FP&A بمحرك إشارات حمرا وتصدير PDF، داشبورد موازنة طلعت مصطفى، وداشبوردات أسعار الدهب ومحوّل العملات لمصر.")],
[T("Courses & training","الكورسات والتدريب"),T("AI Finance Mastery (4 days, 59 slides, 72 prompts, 15 labs), Mini Diploma AI for Finance, CMA budgeting instructor tool, webinar platform with AI pioneers timeline and Egypt Sovereign AI infographic.","AI Finance Mastery (4 أيام، 59 شريحة، 72 برومبت، 15 معمل)، الدبلومة المصغرة AI for Finance، أداة مدرّب موازنات CMA، منصة ويبينار بخط زمني لرواد الـ AI وإنفوجرافيك الذكاء الاصطناعي السيادي في مصر.")],
[T("Research","البحث العلمي"),T("Doctoral research on financial engineering tools and FX hedging in Egyptian importers; Alexandria University conference paper on digital and green accounting (Egypt Vision 2030); papers on AI and the financial industry; generative AI in smart-contract auditing.","بحث الدكتوراه عن أدوات الهندسة المالية والتحوط من سعر الصرف لدى المستوردين المصريين؛ بحث مؤتمر جامعة الإسكندرية عن المحاسبة الرقمية والخضراء (رؤية مصر 2030)؛ أبحاث عن الـ AI والصناعة المالية؛ والذكاء التوليدي في مراجعة العقود الذكية.")],
[T("Presentations & analysis","العروض والتحليلات"),T("Bilingual decks on AI and the Impact Economy (Cairo University branding); investment analysis on Talaat Moustafa Group; World Cup 2026 Arabic dashboard with live data.","عروض ثنائية اللغة عن الـ AI واقتصاد الأثر (بهوية جامعة القاهرة)؛ تحليل استثماري لمجموعة طلعت مصطفى؛ داشبورد كأس العالم 2026 بالعربي ببيانات حية.")]
];
const MYSKILLS=[
{n:"academic-research-general",d:T("Bilingual academic research, any field, APA + MLA.","بحث أكاديمي ثنائي اللغة لأي مجال، APA و MLA.")},
{n:"academic-research-paper",d:T("Management & organizational-behaviour papers.","أوراق بحثية في الإدارة والسلوك التنظيمي.")},
{n:"youtube-script-writer",d:T("Long YouTube scripts in Egyptian Arabic.","سكريبتات يوتيوب طويلة بالعامية المصرية.")},
{n:"file-dashboard-analyzer",d:T("Any file → Arabic interactive dashboard.","أي ملف ← داشبورد عربي تفاعلي.")}
];
const GLOSS=[
["Adaptive thinking","التفكير التكيّفي","The model decides how much to reason; you tune it with effort.","الموديل بيقرر يفكر قد إيه، وإنت بتظبط بالـ Effort."],
["Agent","وكيل","An AI that plans and executes multi-step tasks with tools.","ذكاء اصطناعي بيخطط وينفّذ مهام متعددة الخطوات بأدوات."],
["Agent SDK","حزمة الوكلاء","Library to build your own agents on Claude.","مكتبة لبناء وكلاءك على Claude."],
["Artifact","مُخرَج تفاعلي","Standalone output beside the chat: doc, app, chart.","مخرج مستقل جنب الشات: مستند أو تطبيق أو رسم."],
["Batch API","المعالجة الدفعية","Bulk requests processed asynchronously at 50% cost.","طلبات بالجملة بتتنفذ بعدين بنص التكلفة."],
["Citations","الاستشهادات","Answers linked to exact source passages.","إجابات مربوطة بمقاطع المصدر بالظبط."],
["CLAUDE.md","ملف ذاكرة المشروع","Claude Code instructions loaded every session.","تعليمات Claude Code بتتحمّل كل جلسة."],
["Claude Design","Claude للتصميم","Canvas workspace for visuals and prototypes.","لوحة تصميم للبصريات والنماذج."],
["Claude Tag","Claude في Slack","@Claude as a teammate in Slack channels.","‎@Claude كزميل في قنوات Slack."],
["Code execution","تنفيذ الكود","A sandbox that runs code and creates files.","بيئة معزولة بتشغّل كود وتعمل ملفات."],
["Compaction","ضغط السياق","Summarizing older conversation to free context.","تلخيص المحادثة القديمة لتفضية السياق."],
["Computer use","استخدام الكمبيوتر","Claude operating apps on screen.","Claude بيشغّل البرامج على الشاشة."],
["Connector","موصِّل","An MCP integration to a tool or data source.","ربط MCP بأداة أو مصدر بيانات."],
["Context window","نافذة السياق","Maximum tokens Claude considers in one reply.","أقصى توكنز Claude بياخدها في الاعتبار في رد واحد."],
["Cowork","العمل الوكيلي","Claude's agentic mode for knowledge work.","وضع Claude الوكيلي لشغل المعرفة."],
["Dispatch","الإسناد عن بُعد","Send a task from your phone to desktop Cowork.","تبعت مهمة من الموبايل لـ Cowork على الكمبيوتر."],
["Effort","مستوى الجهد","Trades reasoning depth against speed and cost.","موازنة عمق التفكير مع السرعة والتكلفة."],
["Hook","خطّاف","Script that runs at a lifecycle event in Claude Code.","سكريبت بيشتغل عند حدث في Claude Code."],
["Incognito","المحادثة المتخفية","A chat not saved to history or memory.","محادثة مش بتتحفظ في السجل ولا الذاكرة."],
["MCP","بروتوكول سياق النموذج","Open standard to connect AI to tools and data.","معيار مفتوح لربط الذكاء الاصطناعي بالأدوات والبيانات."],
["Managed Agents","الوكلاء المُدارة","Hosted agent infrastructure on the Claude Platform.","بنية وكلاء مستضافة على منصة Claude."],
["Memory","الذاكرة","Context Claude keeps across chats.","سياق Claude بيحتفظ بيه بين المحادثات."],
["Plan mode","وضع التخطيط","Claude proposes before it edits.","Claude بيقترح قبل ما يعدّل."],
["Plugin","إضافة","Bundle of skills, connectors and commands for a role.","حزمة Skills و Connectors وأوامر لدور وظيفي."],
["Project","مشروع","Workspace with knowledge files and instructions.","مساحة عمل بملفات معرفة وتعليمات."],
["Prompt caching","التخزين المؤقت","Reusing prompt parts at a discount (API).","إعادة استخدام أجزاء البرومبت بخصم (API)."],
["Prompt injection","حقن الأوامر","Malicious instructions hidden in content Claude reads.","تعليمات خبيثة مستخبية في محتوى Claude بيقراه."],
["Research","البحث المعمّق","Multi-step cited research mode.","وضع بحث متعدد الخطوات بمصادر."],
["Skill","مهارة","A SKILL.md folder Claude loads when relevant.","فولدر SKILL.md بيتحمّل وقت الحاجة."],
["Structured outputs","المخرجات المهيكلة","JSON guaranteed to match a schema.","JSON مضمون يطابق الـ schema."],
["Subagent","وكيل فرعي","A specialized helper agent with its own context.","وكيل مساعد متخصص بسياق خاص بيه."],
["Token","توكن","Unit of text for limits and pricing.","وحدة النص للحدود والتسعير."],
["LLM","النموذج اللغوي الكبير","A model trained on large text to generate and reason.","نموذج اتدرب على نصوص ضخمة علشان يكتب ويفكر."],
["Hallucination","الهلوسة","Confident but incorrect output.","ناتج واثق بس غلط."],
["Grounding","الاستناد للمصدر","Constraining answers to given sources.","حصر الإجابات في المصادر المعطاة."],
["RAG","التوليد المعزز بالاسترجاع","Retrieve relevant text, then answer from it.","استرجاع النص المناسب وبعدين الإجابة منه."],
["Embedding","التمثيل المتجهي","Numeric vector representing meaning.","متجه أرقام بيمثل المعنى."],
["Few-shot","التعلم بأمثلة قليلة","Giving a few examples inside the prompt.","إعطاء أمثلة قليلة جوه البرومبت."],
["Chain of thought","سلسلة التفكير","Asking for step-by-step reasoning.","طلب تفكير خطوة بخطوة."],
["Prompt chaining","تسلسل البرومبتات","Splitting a job into sequential prompts.","تقسيم المهمة لبرومبتات متتالية."],
["Fine-tuning","الضبط الدقيق","Further training on your own data.","تدريب إضافي على بياناتك."],
["Tool use","استخدام الأدوات","The model calls functions you define.","الموديل بينادي دوال إنت معرّفها."],
["Temperature","درجة العشوائية","API setting controlling randomness.","إعداد في الـ API بيتحكم في العشوائية."],
["Knowledge cutoff","تاريخ قطع المعرفة","Date after which the model has no training data.","التاريخ اللي بعده مفيش بيانات تدريب."],
["Human in the loop","إنسان في الحلقة","A person approves key steps.","شخص بيوافق على الخطوات المهمة."],
["Responsible AI","الذكاء الاصطناعي المسؤول","Accountable, fair, private, transparent, supervised use.","استخدام مسؤول وعادل وخاص وشفاف وتحت إشراف."],
["UCP 600 / ISBP","القواعد الموحدة للاعتمادات","ICC rules and practice for documentary credits.","قواعد وممارسات غرفة التجارة الدولية للاعتمادات المستندية."]
];
