# English narration: scene -> lines (caption text; TTS normalisation is applied in the builder)
SCENES = [
 ("s1", ["The AI for Finance journey.",
         "A journey that started just last year."]),
 ("s2", ["When we launched the very first AI for Finance workshop in Egypt and the Middle East."]),
 ("s3", ["I'm Sara Salem.",
         "And since then, we have never treated AI as just another new tool,",
         "but as a real transformation in how finance professionals work, and how they think."]),
 ("s4", ["I designed and built the entire program from scratch,",
         "covering the full finance content with AI, the tools, and AI workflows,",
         "real-world cases, hands-on applications, and automation."]),
 ("s4b", ["Here, participants don't just learn to use ready-made tools or templates.",
          "They learn how to build the solution, the models, and the projects themselves, from start to finish.",
          "Because AI has already restructured every profession, including finance and economics."]),
 ("s5", ["How do you understand the data, and what lies behind the numbers?",
         "How do you do financial mapping?",
         "How do you define the right KPIs?",
         "How do you build a financial model?",
         "How do you connect your data?",
         "How do you use Excel with AI?",
         "How do you build a project, and an artifact?",
         "And how do you make AI a real part of your finance workflow?"]),
 ("s6", ["It's all about mindset.",
         "For me, the most important thing in the AI journey isn't learning a new tool.",
         "It's changing the way you think, and understanding the philosophy of AI.",
         "Because the human mind will always own the idea, the vision, and the creativity."]),
 ("s6b", ["AI is a powerful assistant that helps you execute your ideas faster, and more efficiently.",
          "And the beauty of technology is that you direct the AI, not the other way around.",
          "When we understand the language of technology, and how to work with it, we discover its potential, and see the magic of AI.",
          "AI is your assistant. You are still the decision-maker."]),
 ("s7", ["Context engineering. The most important lesson: context is everything.",
         "How to talk to AI.",
         "Because the quality of what you get from AI depends heavily on the quality of the context you give it."]),
 ("s8i", ["So, what will you learn in AI for Finance?",
          "The program covers an integrated set of financial skills and practical AI applications, from the fundamentals, all the way to building advanced solutions."]),
 ("s8", ["Generative AI for Finance: understanding generative AI, and how to apply it across finance and your daily work.",
         "Prompt Engineering for Finance: building professional prompts designed for financial problems and tasks.",
         "Financial Statement Analysis: analyzing statements, extracting key ratios, uncovering insights, and turning data into decision-ready information, with hands-on practice on FMVA.",
         "FP&A with AI: using AI for planning and analysis, forecasting, scenarios, and decision support.",
         "Treasury Management and Forecasting: managing cash position, banks, liquidity, actual cash flows, forecasts, exchange rates, suppliers and customers.",
         "Liquidity Management: analyzing and managing liquidity, forecasting cash needs, monitoring risk, and analyzing bank statements.",
         "Budget Preparation: preparing budgets in more than one way, and linking the budget to actual data.",
         "Cash Flow Forecasting: forecasting cash flows, analyzing trends, and building future scenarios."]),
 ("s8b", ["Financial Modeling: building financial models that link data, assumptions, and calculations using AI.",
          "Variance Analysis: actual versus budget versus forecast. Analyzing variances, understanding their causes, and reaching clear recommendations.",
          "Financial Reporting Automation: creating reports faster, and connecting data and processes through automation.",
          "Presentations and Executive Reports: turning financial analysis into professional reports that help management decide.",
          "Excel plus AI: connecting AI with Excel for analysis, modeling, reporting, and automation.",
          "Risk Management and Cost Reduction: recommendations to manage risk and cut costs, and building your own AI agent."]),
 ("s9", ["And from financial analysis, all the way to financial valuation, and valuing companies.",
         "It's an intensive, practical application of financial modeling, business intelligence, analysis, and valuation."]),
 ("s10", ["I use more than one LLM, and more than one skill.",
          "Because the AI world moves fast, we never rely on a single model.",
          "That makes learning more flexible, and applicable in any work environment.",
          "And you graduate able to build new projects, artifacts, and skills on your own."]),
 ("s11", ["What makes me happiest with every wave is seeing participants bring creative projects and ideas, and move from:",
          "What can I do with AI?",
          "To: I had an idea, and I built it with AI, and it saved me a huge amount of time and effort.",
          "That's where the real change, and the real impact, happen."]),
 ("s12", ["And the best part? They don't stop when the course ends.",
          "They stay with us in the AI Community, our AI family, sharing ideas, experiences, and everything new in AI."]),
 ("s13", ["AI for Finance. Eight sessions, three hours each, every Saturday and Wednesday.",
          "Online course. Practical learning. Real-world finance use cases.",
          "Multiple LLMs and AI tools. Projects and artifacts. Certificates.",
          "Book your seat now, with Sara Salem."]),
]
