#!/usr/bin/env node
/* Generates docs/DATA_MODEL.md and docs/RULES.md from the code (single source of truth). Usage: node tools/gen-docs.js */
'use strict';
const fs = require('fs'), path = require('path');
const S = require('../tests/load.js')(['js/core/i18n.js']);
const T = { s: 'text', n: 'number', d: 'date', b: 'yes/no' };
let md = '# SUMED P2P — Canonical data model\n\n_Generated by `node tools/gen-docs.js` from `js/data/schema.js`._\n\n' +
  'Every uploaded sheet is classified to one entity and its columns are mapped to the fields below (English or Arabic header synonyms; mapping is reviewable before loading). ' +
  'Fields marked **required** drive core controls — when missing they are reported in the Data Quality report and are **never filled in**. Every loaded row keeps its source lineage (`file · sheet · row`).\n\n';
md += '| Entity | Label (EN) | Label (AR) | Primary key | Fields |\n|---|---|---|---|---|\n' + Object.entries(S.schema).map(([k, d]) => `| \`${k}\` | ${d.label} | ${d.labelAr} | ${d.pk ? '`' + d.pk + '`' : '—'} | ${d.fields.length} |`).join('\n') + '\n\n';
for (const [k, d] of Object.entries(S.schema)) {
  md += `## ${d.label} — \`${k}\`\n\n${d.labelAr}\n\n| Field | Type | Required | Header synonyms (EN / AR) |\n|---|---|---|---|\n`;
  md += d.fields.map((f) => `| \`${f.key}\` | ${T[f.type]} | ${f.req ? '**required**' : ''} | ${f.syn.join(', ')} |`).join('\n') + '\n\n';
}
md += '## Derived (calculated) fields\n\nThe engine adds derived values prefixed with `_` (never written back to source): `_paid`, `_out` (outstanding = total − executed/reconciled payments unless the source provides it), `_outBase` (revalued at the latest FX rate on/before the as-of date), `_dpd` (days past due), `_fx`, `_totalBase`, `_debitBalance`, plus `_src` (lineage), `_issues` (parse problems), `_edits` (in-app changes, also in the audit trail) and `_derived` (explanations, e.g. supplier matched by name).\n';
fs.writeFileSync(path.join(__dirname, '..', 'docs', 'DATA_MODEL.md'), md);

const en = S.i18n.en;
const pick = (p) => Object.keys(en).filter((k) => k.startsWith(p)).map((k) => [k.slice(p.length), en[k]]);
let r = '# SUMED P2P — Rules, controls, statuses and KPI library\n\n_Generated by `node tools/gen-docs.js` from the engine dictionaries._ All thresholds referenced here are configurable in **Settings** and are **illustrative defaults, not SUMED policy**.\n\n';
r += '## Three-way match statuses (precedence order)\n\n' + S.engine.MATCH_ORDER.map((s, i) => `${i + 1}. **${s}** — ${en['m.' + s]}`).join('\n') + '\n\nPARTIALLY MATCHED is used when only header-level matching is possible (no line data). Tolerances: price %, quantity %, tax-rate percentage points and an absolute rounding tolerance.\n\n';
r += '## Duplicate detection levels\n\n- **EXACT DUPLICATE** — same supplier + same invoice number + same amount & currency, or identical file hash.\n- **HIGH-RISK DUPLICATE** — same supplier and same number after normalisation (prefixes, separators, leading zeros removed) with amount within tolerance; or same supplier & amount within the high-risk window with same PO / similar description / identical lines; or different supplier records with the same normalised number, amount and bank account. Escalated when both documents were paid.\n- **POSSIBLE DUPLICATE** — same supplier, similar amount within the window plus similar description or same PO; same number for a different supplier; identical line items.\n\nSignals: ' + pick('sig.').map(([k, v]) => `\`${k}\` ${v.replace(/\{0\}/g, 'n')}`).join(' · ') + '\n\n';
r += '## Fraud & anomaly rules\n\n| Rule | Reason template |\n|---|---|\n' + pick('rule.').filter(([k]) => !k.startsWith('dq_')).map(([k, v]) => `| \`${k}\` | ${v.replace(/\|/g, '/')} |`).join('\n') + '\n\n';
r += '## Recommended actions\n\n' + pick('act.').map(([k, v]) => `- \`${k}\` — ${v}`).join('\n') + '\n\n';
r += '## Supplier risk drivers (points add up to the score, capped at 100)\n\n' + pick('drv.').filter(([k]) => !k.endsWith('.short')).map(([k, v]) => `- \`${k}\` — ${v}`).join('\n') + '\n\nBands (default): MEDIUM ≥ 30, HIGH ≥ 55, CRITICAL ≥ 75. Evidence completeness = share of risk factors that could be evaluated from the uploaded data.\n\n';
r += '## Automated control tests\n\n| ID | Control | Domain |\n|---|---|---|\n' + pick('ct.').map(([k, v]) => `| ${k} | ${v} | ${en['dom.' + ({ SM: 'supplier', IN: 'invoice', PO: 'po', GR: 'grn', PY: 'payment', BK: 'bank', AP: 'approval', SD: 'sod', CT: 'contract', TX: 'tax', FR: 'fraud', AU: 'audit' })[k.slice(0, 2)]]} |`).join('\n') + '\n\nStatus: **PASS** (population tested, no exceptions) · **WARNING** / **FAIL** (exceptions; FAIL for key controls) · **NOT TESTED** (input data not provided — never assumed).\n\n';
r += '## Data-quality checks\n\n' + pick('dq.').filter(([k]) => /^[a-z]/.test(k) && !['affected', 'bySev', 'check', 'count', 'coverage', 'currencies', 'detail', 'entities', 'entity', 'issues', 'score', 'sub'].includes(k) && !k.startsWith('range')).map(([k, v]) => `- \`${k}\` — ${v.replace('{0}', 'field')}`).join('\n') + '\n\n';
r += '## Segregation-of-duties conflict pairs (configurable)\n\n' + S.defaultConfig().sod.conflicts.map(([a, b]) => `- ${en['duty.' + a]} ↔ ${en['duty.' + b]}`).join('\n') + '\n\n';
const SS = require('../tests/load.js')(['js/core/i18n.js']); SS.state.config.asOfDate = '2026-10-06'; SS.loadDemo(); const R = SS.engine.run();
r += '## KPI library (formula · unit)\n\n| KPI | Formula | Unit |\n|---|---|---|\n' + Object.values(R.kpis).map((k) => `| ${en['kpi.' + k.id] || k.label} | \`${(k.formula || '').replace(/\|/g, '/')}\` | ${k.unit || ''} |`).join('\n') + '\n';
fs.writeFileSync(path.join(__dirname, '..', 'docs', 'RULES.md'), r);
console.log('docs/DATA_MODEL.md and docs/RULES.md written');
