#!/usr/bin/env node
/* Generates SYNTHETIC sample upload files in samples/ from the demo generator (for testing the upload path).
 * Every file name starts with SAMPLE_SYNTHETIC_ and every row carries a "Data Note" column. Not SUMED data.
 * Usage: node tools/make-samples.js */
'use strict';
const fs = require('fs'), path = require('path');
const load = require('../tests/load.js');
const S = load(['js/core/i18n.js', 'js/reports.js']);
const out = path.join(__dirname, '..', 'samples');
fs.mkdirSync(out, { recursive: true });
const D = S.demo.generate('2026-10-06');
const NOTE = 'SYNTHETIC SAMPLE — NOT SUMED DATA';
const table = (ent) => {
  const def = S.schema[ent];
  const fields = def.fields.filter((f) => D[ent].some((r) => r[f.key] != null));
  const header = fields.map((f) => f.syn[0] || f.key).concat(['Data Note']);
  const fmt = (v, f) => (v == null ? '' : f.type === 'd' ? v.split('-').reverse().join('/') : f.type === 'b' ? (v ? 'Y' : 'N') : v);
  return [header, ...D[ent].map((r) => fields.map((f) => fmt(r[f.key], f)).concat([NOTE]))];
};
// CSVs (dates as DD/MM/YYYY like typical Egyptian exports)
const csvEnts = ['suppliers', 'invoices', 'invoiceLines', 'payments', 'bankTxns', 'bankAccounts', 'fxRates', 'taxCodes', 'users', 'bankChanges', 'supplierDocs', 'contracts', 'disputes', 'collections', 'otherOutflows', 'gl', 'evaluations'];
for (const e of csvEnts) fs.writeFileSync(path.join(out, `SAMPLE_SYNTHETIC_${S.schema[e].label.replace(/[^A-Za-z]+/g, '_')}.csv`), S.util.toCSV(table(e)));
// One Excel workbook with the procurement chain on separate sheets
S.reports.xlsxParts = true;
const parts = S.reports.xlsx(['prs', 'rfqs', 'pos', 'poLines', 'grns', 'grnLines', 'budgets'].map((e) => ({ name: S.schema[e].label, rows: table(e) })), false);
fs.writeFileSync(path.join(out, 'SAMPLE_SYNTHETIC_Procurement_Workbook.xlsx'), Buffer.concat(parts.map((p) => Buffer.from(p))));
// A minimal text-layer PDF invoice (hand-built PDF 1.4; Helvetica)
const lines = ['Alpha Marine Services (Demo)', 'SYNTHETIC SAMPLE - NOT SUMED DATA', 'TAX INVOICE', 'Invoice No: INV-SMPL-0042', 'Invoice Date: 15/09/2026', 'Due Date: 15/10/2026', 'PO No: PO-DEMO-00012',
  'Tug assistance (hour) 12 38000.00 456000.00', 'Subtotal: EGP 456,000.00', 'VAT (14%): 63,840.00', 'Grand Total: EGP 519,840.00', 'Payment Terms: Net 30'];
const content = 'BT /F1 12 Tf 60 780 Td 16 TL ' + lines.map((l) => `(${l.replace(/[()\\]/g, '\\$&')}) '`).join(' ') + ' ET';
const objs = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>', `<< /Length ${content.length} >>\nstream\n${content}\nendstream`, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
let pdf = '%PDF-1.4\n';
const offs = [];
objs.forEach((o, i) => { offs.push(pdf.length); pdf += `${i + 1} 0 obj\n${o}\nendobj\n`; });
const xref = pdf.length;
pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n` + offs.map((o) => String(o).padStart(10, '0') + ' 00000 n \n').join('') + `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
fs.writeFileSync(path.join(out, 'SAMPLE_SYNTHETIC_Invoice_INV-SMPL-0042.pdf'), pdf, 'latin1');
fs.writeFileSync(path.join(out, 'README.md'), `# Sample upload files — SYNTHETIC\n\nGenerated by \`node tools/make-samples.js\` from the demo generator. **These are not SUMED data.** Every file name starts with \`SAMPLE_SYNTHETIC_\` and every row carries a \`Data Note\` column.\n\nUse them to test **Upload & Validate**: drag all files onto the drop zone, review the detected classification and column mapping, then *Validate & load*. Dates are written DD/MM/YYYY (the default ambiguous-date order).\n\n- CSV files: supplier master, invoice register (+ lines), payment register, bank statement, bank accounts, FX rates, tax configuration, users, bank-change log, supplier documents, contracts, disputes, expected collections, other outflows, GL/AP summary, evaluations.\n- \`SAMPLE_SYNTHETIC_Procurement_Workbook.xlsx\`: PRs, RFQs, POs, PO lines, GRNs, GRN lines and budget on separate sheets.\n- \`SAMPLE_SYNTHETIC_Invoice_INV-SMPL-0042.pdf\`: a text-layer invoice for the OCR / extraction review screen.\n`);
console.log('Samples written to', out, fs.readdirSync(out).length, 'files');
