// Risk & control library (framework definitions — not company data). Owners are assigned by the CAE in the app.
import type { AuditArea, L } from './types';

export type RiskCategory = 'financial' | 'operational' | 'fraud' | 'compliance' | 'technology';

export interface RiskDef { id: string; category: RiskCategory; title: L; description: L; cause: L; impact: L; areas: AuditArea[] }

const l = (en: string, ar: string): L => ({ en, ar });

export const RISKS: RiskDef[] = [
  { id: 'R-FR-01', category: 'financial', title: l('Financial reporting misstatement', 'تحريف التقارير المالية'), description: l('Ledger, journals or balances are inaccurate, incomplete or manipulated.', 'عدم دقة أو اكتمال القيود والأرصدة أو التلاعب بها.'), cause: l('Manual journals, weak review, interface errors.', 'القيود اليدوية وضعف المراجعة وأخطاء الربط.'), impact: l('Misstated financial statements; loss of stakeholder confidence.', 'قوائم مالية محرفة وفقدان ثقة الأطراف.'), areas: ['gl', 'recon', 'fs'] },
  { id: 'R-FR-02', category: 'financial', title: l('Payables misstatement and unauthorized disbursement', 'تحريف الدائنين والصرف غير المصرح'), description: l('Invoices recorded or paid without valid support or approval.', 'تسجيل أو سداد فواتير بدون مستندات أو اعتماد.'), cause: l('Weak three-way match and payment controls.', 'ضعف المطابقة الثلاثية وضوابط السداد.'), impact: l('Financial loss and overstated liabilities/expenses.', 'خسارة مالية وتضخيم الالتزامات والمصروفات.'), areas: ['ap'] },
  { id: 'R-FN-01', category: 'financial', title: l('Liquidity and treasury risk', 'مخاطر السيولة والخزانة'), description: l('Insufficient or poorly controlled cash to meet obligations.', 'نقدية غير كافية أو ضعيفة الرقابة للوفاء بالالتزامات.'), cause: l('Debt maturities, weak forecasting, unreconciled bank balances.', 'استحقاقات الديون وضعف التوقعات وأرصدة بنكية غير مسواة.'), impact: l('Default risk, penalties, financing cost.', 'مخاطر التعثر والغرامات وتكلفة التمويل.'), areas: ['treasury', 'loans'] },
  { id: 'R-FN-02', category: 'financial', title: l('Credit risk', 'مخاطر الائتمان'), description: l('Customers fail to pay amounts due.', 'تعثر العملاء في سداد المستحقات.'), cause: l('Concentration, overdue balances, weak credit control.', 'التركز والمتأخرات وضعف الرقابة الائتمانية.'), impact: l('Impairment losses; cash shortfall.', 'خسائر اضمحلال وعجز نقدي.'), areas: ['ar'] },
  { id: 'R-FN-03', category: 'financial', title: l('Foreign-exchange risk', 'مخاطر أسعار الصرف'), description: l('Exposure to EGP movements on foreign-currency balances.', 'التعرض لتقلبات الجنيه على الأرصدة بالعملات الأجنبية.'), cause: l('Foreign-currency receivables, payables, cash and debt.', 'مديونيات ودائنيات ونقدية وقروض بعملات أجنبية.'), impact: l('FX losses; volatility in results.', 'خسائر فروق العملة وتقلب النتائج.'), areas: ['treasury'] },
  { id: 'R-FN-05', category: 'financial', title: l('Operating cost overruns', 'تجاوز التكاليف التشغيلية'), description: l('Operating spend exceeds approved budget.', 'تجاوز الإنفاق التشغيلي للموازنة المعتمدة.'), cause: l('Weak budget monitoring and commitment control.', 'ضعف متابعة الموازنة والرقابة على الالتزامات.'), impact: l('Reduced profitability.', 'انخفاض الربحية.'), areas: ['opex', 'budget'] },
  { id: 'R-FN-06', category: 'financial', title: l('CAPEX overruns and unauthorized capital spend', 'تجاوز النفقات الرأسمالية والإنفاق غير المصرح'), description: l('Capital projects exceed budget or proceed without approval.', 'تجاوز المشروعات الرأسمالية للموازنة أو تنفيذها دون اعتماد.'), cause: l('Scope changes, weak project governance.', 'تغيير النطاق وضعف حوكمة المشروعات.'), impact: l('Funding pressure; value destruction.', 'ضغط تمويلي وإهدار القيمة.'), areas: ['capex'] },
  { id: 'R-OP-01', category: 'operational', title: l('Pipeline operations dependency / business continuity', 'الاعتماد على تشغيل خطوط الأنابيب / استمرارية الأعمال'), description: l('Disruption of pipeline, terminal or pumping operations affects revenue and obligations.', 'تعطل الخطوط أو الموانئ أو محطات الضخ يؤثر على الإيرادات والالتزامات.'), cause: l('Asset failure, supply disruption, external events.', 'أعطال الأصول أو انقطاع التوريد أو أحداث خارجية.'), impact: l('Revenue loss; contractual penalties.', 'فقدان الإيرادات وغرامات تعاقدية.'), areas: ['fa', 'contracts'] },
  { id: 'R-OP-02', category: 'operational', title: l('Procurement risk', 'مخاطر المشتريات'), description: l('Purchases not approved, competitive or value-for-money.', 'مشتريات غير معتمدة أو غير تنافسية أو لا تحقق أفضل قيمة.'), cause: l('Workflow bypass, direct awards.', 'تجاوز دورة العمل والإسناد المباشر.'), impact: l('Overpayment; unauthorized commitments.', 'سداد زائد والتزامات غير مصرح بها.'), areas: ['procurement'] },
  { id: 'R-OP-03', category: 'operational', title: l('Vendor dependency', 'الاعتماد على الموردين'), description: l('Reliance on a small number of vendors.', 'الاعتماد على عدد محدود من الموردين.'), cause: l('Sole sourcing; specialised supply.', 'المصدر الوحيد والتوريد المتخصص.'), impact: l('Supply disruption; pricing power.', 'انقطاع التوريد وقوة تسعيرية للمورد.'), areas: ['ap', 'procurement'] },
  { id: 'R-OP-04', category: 'operational', title: l('Asset management', 'إدارة الأصول'), description: l('Fixed assets not safeguarded or accurately recorded.', 'عدم حماية الأصول الثابتة أو تسجيلها بدقة.'), cause: l('Incomplete register; no physical verification.', 'سجل غير مكتمل وعدم الجرد الفعلي.'), impact: l('Asset loss; misstated depreciation.', 'فقدان الأصول وتحريف الإهلاك.'), areas: ['fa', 'capex'] },
  { id: 'R-OP-05', category: 'operational', title: l('Inventory management', 'إدارة المخزون'), description: l('Spare parts and stores inaccurate, obsolete or misappropriated.', 'قطع الغيار والمخازن غير دقيقة أو متقادمة أو مختلسة.'), cause: l('Weak stores control; no counts.', 'ضعف الرقابة على المخازن وعدم الجرد.'), impact: l('Losses; valuation errors.', 'خسائر وأخطاء تقييم.'), areas: ['inventory'] },
  { id: 'R-FD-01', category: 'fraud', title: l('Duplicate / unauthorized payments', 'مدفوعات مكررة / غير مصرح بها'), description: l('Funds paid twice or without authorization.', 'سداد مبالغ مرتين أو دون تصريح.'), cause: l('Weak payment controls; collusion.', 'ضعف ضوابط السداد أو التواطؤ.'), impact: l('Direct cash loss.', 'خسارة نقدية مباشرة.'), areas: ['ap', 'treasury', 'gl'] },
  { id: 'R-FD-02', category: 'fraud', title: l('Ghost vendors', 'موردون وهميون'), description: l('Fictitious or conflicted vendors receive payments.', 'حصول موردين وهميين أو متعارضي المصالح على مدفوعات.'), cause: l('Weak vendor onboarding and master-data control.', 'ضعف تسجيل الموردين والرقابة على بياناتهم.'), impact: l('Misappropriation of funds.', 'اختلاس الأموال.'), areas: ['ap', 'fraud'] },
  { id: 'R-FD-03', category: 'fraud', title: l('Payroll fraud / ghost employees', 'احتيال الرواتب / موظفون وهميون'), description: l('Payments to non-existent, terminated or duplicated employees.', 'مدفوعات لموظفين غير موجودين أو منتهية خدمتهم أو مكررين.'), cause: l('HR–payroll disconnect; master-data manipulation.', 'انفصال الموارد البشرية عن الرواتب والتلاعب بالبيانات.'), impact: l('Payroll losses.', 'خسائر في الرواتب.'), areas: ['payroll'] },
  { id: 'R-FD-04', category: 'fraud', title: l('Procurement manipulation and approval avoidance', 'التلاعب في المشتريات وتجنب الاعتماد'), description: l('Splitting, threshold avoidance or price inflation.', 'التجزئة وتجنب الحدود وتضخيم الأسعار.'), cause: l('Approval limits applied per transaction only.', 'تطبيق حدود الاعتماد على المعاملة المنفردة فقط.'), impact: l('Overpayment; non-competitive awards.', 'سداد زائد وإسناد غير تنافسي.'), areas: ['procurement', 'ap'] },
  { id: 'R-FD-05', category: 'fraud', title: l('Master-data manipulation', 'التلاعب بالبيانات الرئيسية'), description: l('Unauthorized changes to vendor/employee bank details.', 'تعديلات غير مصرح بها في البيانات البنكية للموردين/الموظفين.'), cause: l('No independent verification of changes.', 'عدم التحقق المستقل من التعديلات.'), impact: l('Payment diversion.', 'تحويل المدفوعات.'), areas: ['ap', 'payroll'] },
  { id: 'R-CP-01', category: 'compliance', title: l('Tax compliance', 'الالتزام الضريبي'), description: l('Late, missing or inaccurate tax filings and payments.', 'إقرارات ومدفوعات ضريبية متأخرة أو مفقودة أو غير دقيقة.'), cause: l('Weak tax calendar and reconciliation.', 'ضعف التقويم الضريبي والمطابقة.'), impact: l('Penalties and interest (subject to legal confirmation).', 'غرامات وفوائد (رهنًا بالتأكيد القانوني).'), areas: ['tax'] },
  { id: 'R-CP-03', category: 'compliance', title: l('Contractual compliance', 'الالتزام التعاقدي'), description: l('Payments and purchases outside contract terms, scope or validity — by site.', 'مدفوعات ومشتريات خارج شروط العقد أو نطاقه أو مدته — حسب الموقع.'), cause: l('Weak contract lifecycle management.', 'ضعف إدارة دورة حياة العقود.'), impact: l('Overpayment; legal exposure.', 'سداد زائد وتعرض قانوني.'), areas: ['contracts', 'procurement'] },
  { id: 'R-CP-04', category: 'compliance', title: l('Related-party governance', 'حوكمة الأطراف ذات العلاقة'), description: l('Related-party transactions not approved or disclosed.', 'معاملات أطراف ذات علاقة غير معتمدة أو غير مفصح عنها.'), cause: l('Incomplete RP register.', 'سجل أطراف غير مكتمل.'), impact: l('Governance and disclosure deficiencies.', 'قصور في الحوكمة والإفصاح.'), areas: ['related'] },
  { id: 'R-IT-01', category: 'technology', title: l('Access control and segregation of duties', 'ضوابط الوصول والفصل بين المهام'), description: l('Users can create and approve transactions or have inappropriate access.', 'قدرة المستخدمين على إنشاء المعاملات واعتمادها أو امتلاك صلاحيات غير مناسبة.'), cause: l('Role design; periodic access reviews not performed.', 'تصميم الأدوار وعدم مراجعة الصلاحيات دوريًا.'), impact: l('Undetected errors or fraud.', 'أخطاء أو احتيال غير مكتشف.'), areas: ['gl', 'procurement'] },
  { id: 'R-IT-02', category: 'technology', title: l('Data integrity and system interfaces', 'سلامة البيانات وواجهات الأنظمة'), description: l('Data transferred between systems is incomplete or altered.', 'نقل بيانات غير مكتملة أو معدلة بين الأنظمة.'), cause: l('Interface failures; manual uploads.', 'أعطال الواجهات والتحميل اليدوي.'), impact: l('Unreliable reporting.', 'تقارير غير موثوقة.'), areas: ['recon'] },
];
export const RISK_BY_ID: Record<string, RiskDef> = Object.fromEntries(RISKS.map((r) => [r.id, r]));

export type ControlCategory =
  | 'Authorization' | 'Segregation of Duties' | 'Maker-checker' | 'Approval limits' | 'Three-way matching' | 'Bank reconciliation'
  | 'Account reconciliation' | 'Master-data controls' | 'Journal-entry controls' | 'Payment controls' | 'Vendor controls' | 'Customer controls'
  | 'Payroll controls' | 'Fixed asset controls' | 'Inventory controls' | 'Budget controls' | 'Tax controls' | 'Financial reporting controls'
  | 'IT controls' | 'Change management' | 'Data integrity' | 'Fraud controls' | 'Contract controls';

export interface ControlDef { id: string; category: ControlCategory; process: L; riskId: string; objective: L; description: L; frequency: L; evidence: L; procedure: L; automatedTest: boolean }

const C = (id: string, category: ControlCategory, process: [string, string], riskId: string, objective: [string, string], description: [string, string], frequency: [string, string], evidence: [string, string], procedure: [string, string], automatedTest = true): ControlDef =>
  ({ id, category, process: l(...process), riskId, objective: l(...objective), description: l(...description), frequency: l(...frequency), evidence: l(...evidence), procedure: l(...procedure), automatedTest });

export const CONTROLS: ControlDef[] = [
  C('C-JE-01', 'Journal-entry controls', ['Record to Report', 'التسجيل والتقارير'], 'R-FR-01', ['Journals are valid, timely and authorized', 'القيود سليمة وفي توقيتها ومعتمدة'], ['Review of non-routine, period-end and unusual journals', 'مراجعة القيود غير الروتينية وقيود نهاية الفترة وغير المعتادة'], ['Monthly', 'شهري'], ['Journal listing with reviewer sign-off', 'قائمة القيود مع توقيع المراجع'], ['Automated GL analytics (GL-02…GL-18) + vouching of exceptions', 'تحليلات آلية للأستاذ + مطابقة الاستثناءات']),
  C('C-JE-02', 'Data integrity', ['Record to Report', 'التسجيل والتقارير'], 'R-FR-01', ['Only balanced journals can be posted', 'لا يُرحل إلا القيد المتوازن'], ['ERP balance check at posting', 'فحص التوازن الآلي عند الترحيل'], ['Continuous', 'مستمر'], ['System configuration; journal data', 'إعدادات النظام وبيانات القيود'], ['Recompute Σ Dr − Σ Cr per journal (GL-01)', 'إعادة احتساب الفرق لكل قيد']),
  C('C-JE-03', 'Maker-checker', ['Record to Report', 'التسجيل والتقارير'], 'R-FR-01', ['Manual journals are independently approved', 'اعتماد مستقل للقيود اليدوية'], ['Workflow approval of manual journals before posting', 'اعتماد القيود اليدوية عبر دورة العمل قبل الترحيل'], ['Per transaction', 'لكل معاملة'], ['Approval status and approver', 'حالة الاعتماد والمعتمد'], ['Test approval status of manual journals (GL-08)', 'اختبار حالة اعتماد القيود اليدوية']),
  C('C-SD-01', 'Segregation of Duties', ['IT General Controls', 'الضوابط العامة لتقنية المعلومات'], 'R-IT-01', ['Incompatible duties are segregated', 'الفصل بين المهام المتعارضة'], ['Preparer ≠ approver enforced by ERP roles', 'المُعد ≠ المعتمد عبر أدوار النظام'], ['Continuous', 'مستمر'], ['User/approver fields; role matrix', 'حقول المستخدم/المعتمد ومصفوفة الأدوار'], ['Compare preparer vs approver (GL-13, PR-09)', 'مقارنة المُعد بالمعتمد']),
  C('C-RC-01', 'Bank reconciliation', ['Treasury', 'الخزانة'], 'R-FN-01', ['Bank balances agree to GL and differences are cleared', 'تطابق أرصدة البنوك مع الأستاذ وتسوية الفروق'], ['Monthly bank reconciliation prepared and reviewed', 'إعداد ومراجعة التسوية البنكية شهريًا'], ['Monthly', 'شهري'], ['Bank statements; reconciliations', 'كشوف البنوك والتسويات'], ['Automated bank–GL matching and ageing (REC-07, REC-08, TR-02)', 'مطابقة آلية للبنك والأستاذ وأعمار البنود']),
  C('C-RC-02', 'Account reconciliation', ['Record to Report', 'التسجيل والتقارير'], 'R-FR-01', ['Sub-ledgers agree to control accounts', 'تطابق الدفاتر المساعدة مع حسابات المراقبة'], ['Monthly control-account reconciliations', 'مطابقات شهرية لحسابات المراقبة'], ['Monthly', 'شهري'], ['Reconciliations with sign-off', 'المطابقات مع التوقيع'], ['Automated reconciliations (REC-01…REC-06, REC-10)', 'مطابقات آلية']),
  C('C-RC-03', 'Account reconciliation', ['Record to Report', 'التسجيل والتقارير'], 'R-FR-01', ['Intercompany balances agree', 'تطابق الأرصدة بين الشركات'], ['Monthly intercompany confirmation', 'مصادقة شهرية بين الشركات'], ['Monthly', 'شهري'], ['Confirmations', 'المصادقات'], ['Net intercompany balances (REC-11)', 'صافي الأرصدة بين الشركات']),
  C('C-AP-01', 'Payment controls', ['Procure to Pay', 'الشراء حتى السداد'], 'R-FR-02', ['Only valid invoices are recorded', 'تسجيل الفواتير السليمة فقط'], ['Invoice validation before posting', 'التحقق من الفاتورة قبل التسجيل'], ['Per transaction', 'لكل معاملة'], ['Invoice register', 'سجل الفواتير'], ['AP analytics (AP-05, AP-16)', 'تحليلات الدائنين']),
  C('C-AP-02', 'Fraud controls', ['Procure to Pay', 'الشراء حتى السداد'], 'R-FD-01', ['Duplicate invoices are prevented', 'منع الفواتير المكررة'], ['ERP duplicate-invoice check on vendor + invoice no. + amount', 'فحص التكرار الآلي على المورد ورقم الفاتورة والمبلغ'], ['Continuous', 'مستمر'], ['System configuration; invoice data', 'إعدادات النظام وبيانات الفواتير'], ['Duplicate invoice analytics (AP-01)', 'تحليل الفواتير المكررة']),
  C('C-AP-03', 'Three-way matching', ['Procure to Pay', 'الشراء حتى السداد'], 'R-FR-02', ['Invoices match PO and goods receipt', 'مطابقة الفاتورة مع أمر الشراء وإذن الاستلام'], ['Three-way match before invoice approval', 'المطابقة الثلاثية قبل اعتماد الفاتورة'], ['Per transaction', 'لكل معاملة'], ['PO, GRN, invoice', 'أمر الشراء وإذن الاستلام والفاتورة'], ['Test PO/GRN presence (AP-02, AP-03)', 'اختبار وجود أمر الشراء وإذن الاستلام']),
  C('C-PY-01', 'Payment controls', ['Procure to Pay', 'الشراء حتى السداد'], 'R-FR-02', ['Payments are approved and timely', 'المدفوعات معتمدة وفي موعدها'], ['Payment approval per DoA; payment runs on due dates', 'اعتماد السداد وفق الصلاحيات ودورات السداد في المواعيد'], ['Per payment run', 'لكل دورة سداد'], ['Payment approvals', 'اعتمادات السداد'], ['AP-04, AP-07, AP-08, AP-15, AP-16', 'اختبارات المدفوعات']),
  C('C-PY-02', 'Payment controls', ['Treasury', 'الخزانة'], 'R-FD-01', ['Bank payments are authorized and unique', 'المدفوعات البنكية معتمدة وغير مكررة'], ['Dual authorization on e-banking; duplicate check', 'اعتماد مزدوج في البنك الإلكتروني وفحص التكرار'], ['Per payment', 'لكل دفعة'], ['E-banking logs', 'سجلات البنك الإلكتروني'], ['TR-01, TR-03, TR-04, TR-05', 'اختبارات الخزانة']),
  C('C-AU-01', 'Approval limits', ['Governance', 'الحوكمة'], 'R-FD-04', ['Transactions are approved at the correct DoA level', 'اعتماد المعاملات بالمستوى الصحيح من الصلاحيات'], ['DoA limits enforced, including cumulative thresholds', 'تطبيق حدود الصلاحيات بما فيها الحدود التراكمية'], ['Per transaction', 'لكل معاملة'], ['DoA matrix; approvals', 'جدول الصلاحيات والاعتمادات'], ['Threshold and split analytics (AP-06, AP-12, PR-02, PR-03)', 'تحليلات الحدود والتجزئة']),
  C('C-VM-01', 'Vendor controls', ['Procure to Pay', 'الشراء حتى السداد'], 'R-FD-02', ['Vendors are genuine, unique and independent', 'الموردون حقيقيون وفريدون ومستقلون'], ['Vendor onboarding due diligence; unique bank accounts', 'العناية الواجبة عند تسجيل الموردين وتفرد الحسابات البنكية'], ['Per vendor', 'لكل مورد'], ['Vendor master; onboarding file', 'بيانات الموردين وملف التسجيل'], ['AP-09, AP-10, AP-11, AP-13, AP-17', 'اختبارات الموردين']),
  C('C-VM-02', 'Master-data controls', ['Procure to Pay', 'الشراء حتى السداد'], 'R-FD-05', ['Vendor master changes are independently verified', 'التحقق المستقل من تعديلات بيانات الموردين'], ['Call-back verification and dual approval of bank changes', 'التحقق الهاتفي والاعتماد المزدوج لتعديل الحسابات'], ['Per change', 'لكل تعديل'], ['Change log', 'سجل التعديلات'], ['AP-14', 'اختبار التعديلات']),
  C('C-AR-01', 'Customer controls', ['Order to Cash', 'البيع حتى التحصيل'], 'R-FN-02', ['Receivables are valid and collected', 'المديونيات سليمة ومحصلة'], ['Ageing review and collection follow-up', 'مراجعة الأعمار ومتابعة التحصيل'], ['Monthly', 'شهري'], ['Ageing report', 'تقرير الأعمار'], ['AR-01, AR-04, AR-06', 'اختبارات المدينين']),
  C('C-AR-02', 'Authorization', ['Order to Cash', 'البيع حتى التحصيل'], 'R-FN-02', ['Credit notes and write-offs are authorized', 'اعتماد الإشعارات الدائنة والإعدامات'], ['Approval of credit notes/write-offs per DoA', 'اعتماد الإشعارات والإعدامات وفق الصلاحيات'], ['Per transaction', 'لكل معاملة'], ['Approvals', 'الاعتمادات'], ['AR-03', 'اختبار الإشعارات']),
  C('C-AR-03', 'Customer controls', ['Order to Cash', 'البيع حتى التحصيل'], 'R-FN-02', ['Credit terms are approved', 'اعتماد شروط الائتمان'], ['Credit committee approval of terms', 'اعتماد لجنة الائتمان للشروط'], ['Per customer', 'لكل عميل'], ['Credit file', 'ملف الائتمان'], ['AR-02, AR-05', 'اختبارات الائتمان']),
  C('C-TR-01', 'Payment controls', ['Treasury', 'الخزانة'], 'R-FN-01', ['Cash is safeguarded and liquidity monitored', 'حماية النقدية ومتابعة السيولة'], ['Daily cash position and overdraft monitoring', 'متابعة يومية لمركز النقدية والمكشوف'], ['Daily', 'يومي'], ['Cash reports', 'تقارير النقدية'], ['TR-07 and treasury analytics', 'تحليلات الخزانة']),
  C('C-TR-02', 'Account reconciliation', ['Treasury', 'الخزانة'], 'R-FN-01', ['Bank charges agree to tariffs', 'مطابقة الرسوم البنكية مع التعريفات'], ['Monthly bank-charge review', 'مراجعة شهرية للرسوم البنكية'], ['Monthly', 'شهري'], ['Tariff agreements', 'اتفاقيات التعريفة'], ['TR-06', 'اختبار الرسوم']),
  C('C-TR-03', 'Financial reporting controls', ['Treasury', 'الخزانة'], 'R-FN-01', ['Borrowings, interest and covenants are monitored', 'متابعة القروض والفوائد والتعهدات'], ['Quarterly covenant and maturity review', 'مراجعة ربع سنوية للتعهدات والاستحقاقات'], ['Quarterly', 'ربع سنوي'], ['Loan schedule; compliance certificates', 'جدول القروض وشهادات الالتزام'], ['LN-01, LN-02, LN-03, REC-06', 'اختبارات القروض']),
  C('C-FA-01', 'Fixed asset controls', ['Asset Management', 'إدارة الأصول'], 'R-OP-04', ['Asset register is complete and accurate', 'سجل الأصول كامل ودقيق'], ['Register maintenance and depreciation review', 'تحديث السجل ومراجعة الإهلاك'], ['Monthly', 'شهري'], ['FAR; depreciation run', 'سجل الأصول ودورة الإهلاك'], ['FA-01…FA-05, FA-08…FA-11, REC-04', 'اختبارات الأصول']),
  C('C-FA-02', 'Fixed asset controls', ['Asset Management', 'إدارة الأصول'], 'R-OP-04', ['Assets are physically safeguarded', 'الحماية المادية للأصول'], ['Assigned location/custodian; periodic physical verification', 'تحديد الموقع وأمين العهدة والجرد الدوري'], ['Annual', 'سنوي'], ['Count sheets', 'محاضر الجرد'], ['FA-06, FA-07', 'اختبارات الموقع والعهدة']),
  C('C-IN-01', 'Inventory controls', ['Inventory', 'المخزون'], 'R-OP-05', ['Inventory is accurate, valued and safeguarded', 'المخزون دقيق ومقيم ومحمي'], ['Cycle counts, adjustment approval, obsolescence review', 'جرد دوري واعتماد التسويات ومراجعة التقادم'], ['Quarterly', 'ربع سنوي'], ['Count results; adjustments', 'نتائج الجرد والتسويات'], ['IN-01…IN-08, REC-05', 'اختبارات المخزون']),
  C('C-PR-01', 'Authorization', ['Procurement', 'المشتريات'], 'R-OP-02', ['Purchase orders are approved before release', 'اعتماد أوامر الشراء قبل الإصدار'], ['Workflow approval per DoA', 'الاعتماد عبر دورة العمل وفق الصلاحيات'], ['Per transaction', 'لكل معاملة'], ['PO approvals', 'اعتمادات أوامر الشراء'], ['PR-01', 'اختبار الاعتماد']),
  C('C-PR-02', 'Fraud controls', ['Procurement', 'المشتريات'], 'R-FD-04', ['Purchasing is competitive and fairly priced', 'الشراء تنافسي وبأسعار عادلة'], ['Tendering rules; price benchmarking', 'قواعد المناقصات ومقارنة الأسعار'], ['Per award', 'لكل إسناد'], ['Tender files', 'ملفات المناقصات'], ['PR-04, PR-05, PR-06, PR-07', 'اختبارات المشتريات']),
  C('C-PR-03', 'Contract controls', ['Procurement', 'المشتريات'], 'R-CP-03', ['Purchases use valid contracts', 'تتم المشتريات بعقود سارية'], ['Contract register and PO–contract linkage', 'سجل العقود وربط أوامر الشراء بالعقود'], ['Per transaction', 'لكل معاملة'], ['Contract register', 'سجل العقود'], ['PR-08, CT-01…CT-03', 'اختبارات العقود']),
  C('C-ST-01', 'Contract controls', ['Site Payments & Contracts', 'مدفوعات وعقود المواقع'], 'R-CP-03', ['Payments and contracts are allocated to and controlled by the responsible site (HO, Ain Sokhna, Sidi Kerir, Dahshour)', 'تخصيص المدفوعات والعقود للموقع المسؤول ورقابتها (المركز الرئيسي، السخنة، سيدي كرير، دهشور)'], ['Site coding mandatory; payments only against valid site contracts', 'إلزامية ترميز الموقع والسداد فقط على عقود سارية للموقع'], ['Per transaction', 'لكل معاملة'], ['Invoice site coding; contract register by site', 'ترميز الموقع بالفواتير وسجل العقود حسب الموقع'], ['ST-01…ST-05', 'اختبارات المواقع']),
  C('C-PR-10', 'Payroll controls', ['Payroll', 'الرواتب'], 'R-FD-03', ['Only valid employees are paid correct amounts', 'صرف المبالغ الصحيحة للموظفين الفعليين فقط'], ['HR–payroll reconciliation; change approval', 'مطابقة الموارد البشرية والرواتب واعتماد التغييرات'], ['Monthly', 'شهري'], ['Payroll register; HR changes', 'سجل الرواتب وتغييرات الموارد البشرية'], ['PY-01…PY-08, REC-10', 'اختبارات الرواتب']),
  C('C-BU-01', 'Budget controls', ['Planning & Budgeting', 'التخطيط والموازنة'], 'R-FN-05', ['Spend stays within approved budget', 'بقاء الإنفاق ضمن الموازنة المعتمدة'], ['Budget vs actual review and commitment control', 'مراجعة الموازنة مقابل الفعلي والرقابة على الالتزامات'], ['Monthly', 'شهري'], ['Variance reports', 'تقارير الانحرافات'], ['BU-01, OX-01, CX-02', 'اختبارات الموازنة']),
  C('C-CX-01', 'Budget controls', ['Capital Projects', 'المشروعات الرأسمالية'], 'R-FN-06', ['Capital spend is approved and within budget', 'الإنفاق الرأسمالي معتمد وضمن الموازنة'], ['Project approval and cost monitoring', 'اعتماد المشروعات ومتابعة التكاليف'], ['Monthly', 'شهري'], ['Project reports', 'تقارير المشروعات'], ['CX-01, CX-02', 'اختبارات النفقات الرأسمالية']),
  C('C-TX-01', 'Tax controls', ['Tax', 'الضرائب'], 'R-CP-01', ['Tax is computed, filed and paid correctly and on time', 'احتساب الضرائب وتقديمها وسدادها بدقة وفي الموعد'], ['Tax calendar; tax-to-GL reconciliation', 'التقويم الضريبي ومطابقة الضرائب مع الأستاذ'], ['Monthly', 'شهري'], ['Returns; receipts; reconciliations', 'الإقرارات والإيصالات والمطابقات'], ['TX-01…TX-04, REC-09', 'اختبارات الضرائب']),
  C('C-RP-01', 'Authorization', ['Governance', 'الحوكمة'], 'R-CP-04', ['Related-party transactions are approved and disclosed', 'اعتماد معاملات الأطراف ذات العلاقة والإفصاح عنها'], ['RP register; board approval', 'سجل الأطراف واعتماد مجلس الإدارة'], ['Per transaction', 'لكل معاملة'], ['RP register; minutes', 'سجل الأطراف والمحاضر'], ['RP-01…RP-03', 'اختبارات الأطراف ذات العلاقة']),
  C('C-IT-01', 'IT controls', ['IT General Controls', 'الضوابط العامة لتقنية المعلومات'], 'R-IT-01', ['User access is appropriate', 'صلاحيات المستخدمين مناسبة'], ['Periodic user access review', 'مراجعة دورية لصلاحيات المستخدمين'], ['Quarterly', 'ربع سنوي'], ['Access review sign-off', 'توقيع مراجعة الصلاحيات'], ['Manual — upload access review evidence', 'يدوي — رفع أدلة مراجعة الصلاحيات'], false),
  C('C-IT-02', 'Change management', ['IT General Controls', 'الضوابط العامة لتقنية المعلومات'], 'R-IT-02', ['System changes are authorized and tested', 'التغييرات على الأنظمة معتمدة ومختبرة'], ['Change request, testing and approval', 'طلب التغيير والاختبار والاعتماد'], ['Per change', 'لكل تغيير'], ['Change tickets', 'تذاكر التغيير'], ['Manual — upload change log', 'يدوي — رفع سجل التغييرات'], false),
  C('C-IT-03', 'Data integrity', ['IT General Controls', 'الضوابط العامة لتقنية المعلومات'], 'R-IT-02', ['Interfaces transfer complete and accurate data', 'الواجهات تنقل بيانات كاملة ودقيقة'], ['Interface control totals', 'إجماليات رقابية للواجهات'], ['Daily', 'يومي'], ['Interface logs', 'سجلات الواجهات'], ['Data-quality engine + REC-01', 'محرك جودة البيانات']),
  C('C-FR-01', 'Financial reporting controls', ['Record to Report', 'التسجيل والتقارير'], 'R-FR-01', ['Financial statements are reviewed before issue', 'مراجعة القوائم المالية قبل الإصدار'], ['Analytical review of FS movements', 'مراجعة تحليلية لحركة القوائم'], ['Quarterly', 'ربع سنوي'], ['Review memo', 'مذكرة المراجعة'], ['Financial statement analytics', 'تحليلات القوائم المالية']),
];
export const CONTROL_BY_ID: Record<string, ControlDef> = Object.fromEntries(CONTROLS.map((c) => [c.id, c]));

export const AREAS: { id: AuditArea; label: L }[] = [
  { id: 'gl', label: l('General Ledger & Journals', 'دفتر الأستاذ والقيود') },
  { id: 'ap', label: l('Accounts Payable', 'الحسابات الدائنة') },
  { id: 'ar', label: l('Accounts Receivable', 'الحسابات المدينة') },
  { id: 'treasury', label: l('Treasury & Bank', 'الخزانة والبنوك') },
  { id: 'fa', label: l('Fixed Assets', 'الأصول الثابتة') },
  { id: 'inventory', label: l('Inventory', 'المخزون') },
  { id: 'procurement', label: l('Procurement', 'المشتريات') },
  { id: 'payroll', label: l('Payroll', 'الرواتب') },
  { id: 'capex', label: l('CAPEX', 'النفقات الرأسمالية') },
  { id: 'opex', label: l('OPEX', 'النفقات التشغيلية') },
  { id: 'tax', label: l('Tax', 'الضرائب') },
  { id: 'loans', label: l('Loans & Borrowings', 'القروض') },
  { id: 'contracts', label: l('Contracts & Sites', 'العقود والمواقع') },
  { id: 'related', label: l('Related Parties', 'الأطراف ذات العلاقة') },
  { id: 'recon', label: l('Reconciliations', 'المطابقات') },
];
export const AREA_LABEL: Record<string, L> = Object.fromEntries(AREAS.map((a) => [a.id, a.label]));
