/* SUMED P2P — management reports. Exports: Excel (.xlsx, generated natively — no library), CSV, PDF (browser print).
 * Every Excel export contains: Summary, KPIs (with lineage), report sections (cleaned/calculated data), Exceptions,
 * Calculations, Raw data and Source references. Demo exports are stamped DEMO / SYNTHETIC. */
(function (root) {
  'use strict';
  const S = (root.SUMED = root.SUMED || {});
  const U = S.util;
  const t = (...a) => S.t(...a);
  const esc = U.esc;
  const REP = (S.reports = {});

  /* ---------------- Minimal XLSX writer (ZIP "store" + OOXML) ---------------- */
  const CRC = (() => { const tbl = new Uint32Array(256); for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; tbl[n] = c >>> 0; } return tbl; })();
  const crc32 = (bytes) => { let c = 0xffffffff; for (let i = 0; i < bytes.length; i++) c = CRC[(c ^ bytes[i]) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; };
  const enc = (s) => new TextEncoder().encode(s);
  REP.zipParts = (files) => {
    const parts = [], central = [];
    let offset = 0;
    const u16 = (v) => [v & 0xff, (v >>> 8) & 0xff];
    const u32 = (v) => [v & 0xff, (v >>> 8) & 0xff, (v >>> 16) & 0xff, (v >>> 24) & 0xff];
    for (const f of files) {
      const name = enc(f.name), data = typeof f.data === 'string' ? enc(f.data) : f.data, crc = crc32(data);
      const local = [0x50, 0x4b, 0x03, 0x04, ...u16(20), ...u16(0x0800), ...u16(0), ...u16(0), ...u16(0x21), ...u32(crc), ...u32(data.length), ...u32(data.length), ...u16(name.length), ...u16(0)];
      parts.push(new Uint8Array(local), name, data);
      central.push(new Uint8Array([0x50, 0x4b, 0x01, 0x02, ...u16(20), ...u16(20), ...u16(0x0800), ...u16(0), ...u16(0), ...u16(0x21), ...u32(crc), ...u32(data.length), ...u32(data.length), ...u16(name.length), ...u16(0), ...u16(0), ...u16(0), ...u16(0), ...u32(0), ...u32(offset)]), name);
      offset += local.length + name.length + data.length;
    }
    const cdSize = central.reduce((a, b) => a + b.length, 0);
    const end = new Uint8Array([0x50, 0x4b, 0x05, 0x06, ...u16(0), ...u16(0), ...u16(files.length), ...u16(files.length), ...u32(cdSize), ...u32(offset), ...u16(0)]);
    return [...parts, ...central, end];
  };
  REP.zip = (files) => new Blob(REP.zipParts(files), { type: 'application/zip' });
  const xml = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c])).replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g, '');
  const colName = (i) => { let s = ''; i++; while (i > 0) { const m = (i - 1) % 26; s = String.fromCharCode(65 + m) + s; i = Math.floor((i - 1) / 26); } return s; };
  /** sheets: [{name, rows: [[cell]], header: true}] → Blob (.xlsx) */
  REP.xlsx = (sheets, rtl) => {
    const used = new Set();
    const names = sheets.map((s) => { let n = String(s.name).replace(/[\[\]:*?/\\]/g, ' ').slice(0, 31) || 'Sheet'; let k = 2; while (used.has(n)) n = n.slice(0, 28) + ' ' + k++; used.add(n); return n; });
    const sheetXml = (s) => {
      const rows = s.rows.map((r, ri) => `<row r="${ri + 1}">${r.map((v, ci) => {
        const ref = colName(ci) + (ri + 1);
        const st = ri === 0 && s.header !== false ? ' s="1"' : '';
        if (v == null || v === '') return `<c r="${ref}"${st}/>`;
        if (typeof v === 'number' && isFinite(v)) return `<c r="${ref}"${st}><v>${v}</v></c>`;
        return `<c r="${ref}" t="inlineStr"${st}><is><t xml:space="preserve">${xml(v)}</t></is></c>`;
      }).join('')}</row>`).join('');
      const widths = (s.rows[0] || []).map((_, ci) => Math.min(60, Math.max(8, ...s.rows.slice(0, 200).map((r) => String(r[ci] == null ? '' : r[ci]).length + 2))));
      return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"${rtl ? ' rightToLeft="1"' : ''}><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>${widths.length ? `<cols>${widths.map((w, i) => `<col min="${i + 1}" max="${i + 1}" width="${w}" customWidth="1"/>`).join('')}</cols>` : ''}<sheetData>${rows}</sheetData></worksheet>`;
    };
    const files = [
      { name: '[Content_Types].xml', data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_, i) => `<Override PartName="/xl/worksheets/sheet${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>` },
      { name: '_rels/.rels', data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>` },
      { name: 'xl/workbook.xml', data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${names.map((n, i) => `<sheet name="${xml(n)}" sheetId="${i + 1}" r:id="rId${i + 1}"/>`).join('')}</sheets></workbook>` },
      { name: 'xl/_rels/workbook.xml.rels', data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_, i) => `<Relationship Id="rId${i + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i + 1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>` },
      { name: 'xl/styles.xml', data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF0B3A5B"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>` },
      ...sheets.map((s, i) => ({ name: `xl/worksheets/sheet${i + 1}.xml`, data: sheetXml(s) })),
    ];
    return REP.xlsxParts ? REP.zipParts(files) : new Blob(REP.zipParts(files), { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  };

  /* ---------------- Report definitions ---------------- */
  const base = () => S.state.config.baseCurrency;
  const sup = (sid) => S.ui.supName(sid) || sid || '';
  const r2 = (v) => (v == null ? null : Math.round(v * 100) / 100);
  const NA = () => t('common.na', 'Not Available in Source Data');
  const invCols = () => [[t('f.invoiceNo', 'Invoice'), (i) => i.invoiceNo], [t('f.supplierId', 'Supplier'), (i) => sup(i.supplierId)], [t('f.invoiceDate', 'Invoice date'), (i) => i.invoiceDate], [t('f.dueDate', 'Due date'), (i) => i.dueDate], [t('f.poNo', 'PO'), (i) => i.poNo], [t('f.currency', 'Ccy'), (i) => i.currency], [t('f.total', 'Total'), (i) => i.total], [t('f.outstanding', 'Outstanding'), (i) => r2(i._out)], [t('inv.outBase', 'Outstanding ({ccy})', { ccy: base() }), (i) => r2(i._outBase)], [t('inv.dpd', 'Days past due'), (i) => i._dpd], [t('m.short', 'Match'), (i) => (S.R.match.get(i._key) || {}).status]];
  const payCols = () => [[t('f.paymentId', 'Payment'), (p) => p.paymentId], [t('f.supplierId', 'Supplier'), (p) => sup(p.supplierId)], [t('f.invoiceNo', 'Invoice'), (p) => p.invoiceNo], [t('f.paymentDate', 'Date'), (p) => p.paymentDate], [t('f.currency', 'Ccy'), (p) => p.currency], [t('f.net', 'Net'), (p) => p.net], [t('f.executionStatus', 'Status'), (p) => p.executionStatus], [t('f.reference', 'Reference'), (p) => p.reference], [t('f.batchId', 'Batch'), (p) => p.batchId]];
  const flagCols = () => [[t('common.severity', 'Severity'), (f) => f.severity], [t('rf.category', 'Category'), (f) => f.category], [t('rf.reason', 'Reason'), (f) => S.alertText(f)], [t('f.supplierId', 'Supplier'), (f) => sup(f.supplierId)], [t('rf.txn', 'Transaction'), (f) => f.txn], [t('f.amount', 'Amount (base)'), (f) => r2(f.amountBase)], [t('ev.action', 'Action'), (f) => t('act.' + f.action)], [t('ev.location', 'Evidence'), (f) => S.engine.sourceSummary(f.rows).map((s) => `${s.file}${s.sheet ? ' / ' + s.sheet : ''}${s.rows ? ' / rows ' + s.rows : ''}`).join('; ')]];

  REP.defs = () => {
    const R = S.R, D = S.state.data;
    const K = (ids) => ids;
    const flags = (pred) => R.redFlags.filter(pred);
    return [
      { id: 'exec', name: 'Management Executive Summary', kpis: K(['totalSpend', 'totalAP', 'overdueAP', 'paymentsDue', 'cashRequired', 'highRiskSuppliers', 'invoiceExceptions', 'duplicateRisk', 'fraudAlerts', 'controlFailures', 'potentialSavings', 'dpo']), sections: () => [{ title: t('nav.summary', 'Management Summary'), cols: [[t('sum.section', 'Section'), (x) => x.sec], [t('sum.statement', 'Statement'), (x) => x.text], [t('ev.location', 'Evidence'), (x) => S.engine.sourceSummary(x.rows).map((s) => s.file + (s.rows ? ' rows ' + s.rows : '')).join('; ')]], rows: S.views.buildSummary() }], findings: () => flags((f) => ['CRITICAL', 'HIGH'].includes(f.severity)).slice(0, 25), charts: ['spendTrend', 'aging', 'cash'] },
      { id: 'cfoSupplier', name: 'CFO Supplier Report', kpis: K(['supplierCount', 'activeSuppliers', 'criticalSuppliers', 'highRiskSuppliers', 'top5', 'avgRiskScore']), sections: () => [{ title: t('nav.suppliers', 'Suppliers'), cols: [['ID', (s) => s.supplierId], [t('f.name', 'Name'), (s) => s.name], [t('f.nameAr', 'Arabic name'), (s) => s.nameAr], [t('f.category', 'Category'), (s) => s.category], [t('common.status', 'Status'), (s) => s.approvedStatus], [t('sup.critical', 'Critical'), (s) => (s.critical ? 'Y' : '')], [t('sup.risk', 'Risk'), (s) => (R.risk.get(s.supplierId) || {}).score], [t('risk.rating', 'Rating'), (s) => (R.risk.get(s.supplierId) || {}).rating], [t('sup.spend', 'Spend 12m'), (s) => r2(S.views.supStats(s.supplierId).spend)], [t('sup.outstanding', 'Outstanding'), (s) => r2(S.views.supStats(s.supplierId).out)], ['IBAN (masked)', (s) => U.maskAccount(s.iban)]], rows: D.suppliers }], findings: () => flags((f) => f.category === 'SUPPLIER' || f.rule === 'sharedBankAccount') },
      { id: 'cfoPayment', name: 'CFO Payment Report', kpis: K(['payToday', 'paymentsDue', 'paymentsScheduled', 'paymentsExecuted', 'paymentRegisterTotal', 'onTimeRate', 'latePaymentRate']), sections: () => [{ title: t('pay.queue', 'Payment priority queue'), cols: [[t('pq.score', 'Priority'), (x) => x.score], [t('pq.rec', 'Recommendation'), (x) => x.rec], ...invCols().map(([l, f]) => [l, (x) => f(x.inv)]), [t('pq.blocks', 'Blocks'), (x) => x.blocks.join('; ')]], rows: R.priority }, { title: t('pay.register', 'Payment register'), cols: payCols(), rows: D.payments }], findings: () => flags((f) => f.category === 'PAYMENT' || f.category === 'BANK') },
      { id: 'aging', name: 'AP Aging Report', kpis: K(['totalAP', 'overdueAP', 'currentAP', 'avgPayDays', 'apConcentration', 'dpo']), sections: () => [{ title: t('ag.buckets', 'Aging buckets'), cols: [[t('ag.bucket', 'Bucket'), (b) => t('bk.' + b.id)], [t('ag.count', 'Invoices'), (b) => b.count], [t('f.amount', 'Amount') + ' ' + base(), (b) => r2(b.amount)]], rows: R.aging.buckets }, { title: t('ag.bySup', 'Aging by supplier ({c})', { c: base() }), cols: [[t('f.name', 'Supplier'), (r) => sup(r.supplierId)], ...S.engine.BUCKETS.map((b) => [t('bk.' + b.id), (r) => r2(r[b.id])]), [t('ag.total', 'Total'), (r) => r2(r.total)]], rows: R.aging.bySup }, { title: t('ag.open', 'Open invoices'), cols: invCols(), rows: R.aging.open, raw: true }], findings: () => flags((f) => f.rule === 'dq_fxMissing') },
      { id: 'perf', name: 'Supplier Performance Report', kpis: K([]), sections: () => [{ title: t('nav.performance', 'Performance'), cols: [[t('f.name', 'Supplier'), (s) => s.name], [t('perf.score', 'Score'), (s) => (R.perf.get(s.supplierId) || {}).score], [t('perf.band', 'Category'), (s) => (R.perf.get(s.supplierId) || {}).band], ...Object.keys(S.state.config.performance.weights).map((k) => [t('pm.' + k), (s) => (R.perf.get(s.supplierId) || { metrics: {} }).metrics[k]]), [t('perf.cov', 'Coverage %'), (s) => (R.perf.get(s.supplierId) || {}).coverage]], rows: D.suppliers }], findings: () => [] },
      { id: 'risk', name: 'Supplier Risk Report', kpis: K(['highRiskSuppliers', 'avgRiskScore']), sections: () => [{ title: t('risk.register', 'Supplier risk register'), cols: [[t('f.name', 'Supplier'), (s) => s.name], [t('risk.score', 'Score'), (s) => R.risk.get(s.supplierId).score], [t('risk.rating', 'Rating'), (s) => R.risk.get(s.supplierId).rating], [t('risk.drivers', 'Drivers'), (s) => R.risk.get(s.supplierId).drivers.map((d) => `+${d.points} ${S.driverText(d)}`).join(' | ')], [t('risk.compl', 'Evidence completeness %'), (s) => R.risk.get(s.supplierId).completeness]], rows: D.suppliers.slice().sort((a, b) => R.risk.get(b.supplierId).score - R.risk.get(a.supplierId).score) }], findings: () => flags((f) => ['SUPPLIER', 'COMPLIANCE'].includes(f.category)) },
      { id: 'spend', name: 'Spend Analysis Report', kpis: K(['totalSpend', 'contractSpend', 'nonPOSpend', 'offContractSpend', 'maverickSpend', 'emergencySpend', 'top5']), sections: () => [['bySupplier', 'supplier'], ['byCategory', 'category'], ['byDepartment', 'department'], ['byMonth', 'month']].map(([k, d]) => ({ title: t('spend.d.' + d, d), cols: [[t('spend.d.' + d, d), (x) => (d === 'supplier' ? sup(x.key) : x.key)], [t('f.amount', 'Amount') + ' ' + base(), (x) => r2(x.amount)], [t('spend.share', 'Share %'), (x) => r2(R.spend.total ? (x.amount / R.spend.total) * 100 : null)]], rows: R.spend[k] })), findings: () => [] },
      { id: 'payForecast', name: 'Payment Forecast Report', kpis: K(['paymentForecast30', 'cashRequired']), sections: () => [{ title: t('pf.title', 'Payment forecast'), cols: [[t('pf.horizon', 'Horizon'), (h) => t('pf.' + h.id, h.id)], [t('ftype.scheduled'), (h) => r2(h.byType.scheduled)], [t('ftype.approvedInvoice'), (h) => r2(h.byType.approvedInvoice)], [t('ftype.pendingInvoice'), (h) => r2(h.byType.pendingInvoice)], [t('ftype.poCommitment'), (h) => r2(h.byType.poCommitment)], ['Σ', (h) => r2(h.total)]], rows: R.payForecast.horizons }, { title: t('pf.items', 'Forecast items'), cols: [[t('f.date', 'Date'), (x) => x.date], [t('cal.kind', 'Type'), (x) => t('ftype.' + x.type)], [t('f.supplierId', 'Supplier'), (x) => sup(x.supplierId)], [t('f.category', 'Category'), (x) => x.category], [t('f.department', 'Department'), (x) => x.department], [t('f.currency', 'Ccy'), (x) => x.currency], [t('f.amount', 'Amount'), (x) => r2(x.amount)], [base(), (x) => r2(x.amountBase)], [t('tr.basis', 'Basis'), (x) => x.basis]], rows: R.items }], findings: () => [] },
      { id: 'cash', name: 'Cash Impact Report', kpis: K(['cashRequired']), sections: () => [{ title: t('tr.13w', '13-week cash forecast ({c})', { c: base() }), cols: [[t('tr.week', 'Week'), (w) => w.week], [t('tr.period', 'From'), (w) => w.from], [t('tr.to', 'To'), (w) => w.to], [t('tr.inflow', 'Collections'), (w) => r2(w.inflow)], [t('tr.outflow', 'Outflows'), (w) => r2(w.outflow)], [t('tr.closing', 'Closing'), (w) => r2(w.closing)]], rows: R.cash.weekly }, { title: t('tr.byCcy', 'By currency (local currency)'), cols: [[t('f.currency', 'Ccy'), (c) => c.currency], [t('tr.opening', 'Opening'), (c) => c.opening], [t('tr.lowestShort', 'Lowest'), (c) => (c.min ? r2(c.min.closing) : null)], [t('tr.minCash', 'Minimum cash'), (c) => c.minCash], [t('tr.belowMinDays', 'Days below minimum'), (c) => c.belowMinDays]], rows: Object.values(R.cash.currencies) }], findings: () => flags((f) => f.category === 'LIQUIDITY'), notes: () => R.cash.assumptions },
      { id: 'contracts', name: 'Contract Exposure Report', kpis: K(['contractExposure', 'contractCompliance', 'offContractSpend']), sections: () => [{ title: t('nav.contracts', 'Contracts'), cols: [[t('f.contractId', 'Contract'), (c) => c.c.contractId], [t('f.supplierId', 'Supplier'), (c) => sup(c.c.supplierId)], [t('f.endDate', 'End'), (c) => c.c.endDate], [t('f.currency', 'Ccy'), (c) => c.c.currency], [t('f.value', 'Value'), (c) => c.c.value], [t('con.used', 'Used'), (c) => c.used], [t('con.remaining', 'Remaining'), (c) => c.remainingValue], [t('con.util', 'Utilisation %'), (c) => c.util], [t('con.days', 'Days left'), (c) => c.remainingDays], [t('con.alerts', 'Alerts'), (c) => c.alerts.map((a) => t('ca.' + a)).join(', ')]], rows: R.contracts.list }], findings: () => flags((f) => f.category === 'CONTRACT') },
      { id: 'invExceptions', name: 'Invoice Exception Report', kpis: K(['invoiceExceptions', 'exceptionRate', 'threeWayRate']), sections: () => [{ title: t('nav.matching', 'Three-way matching'), cols: [...invCols(), [t('m.po', 'PO amount'), (i) => S.R.match.get(i._key).poAmount], [t('m.grnShort', 'GRN amount'), (i) => S.R.match.get(i._key).grnAmount], [t('m.variance', 'Variance'), (i) => S.R.match.get(i._key).variance], [t('m.variancePct', 'Variance %'), (i) => S.R.match.get(i._key).variancePct], [t('m.reasons', 'Reasons'), (i) => S.R.match.get(i._key).reasons.map((x) => S.ui.reason('mr.', x)).join('; ')]], rows: D.invoices.filter((i) => !['MATCHED', 'PARTIALLY MATCHED'].includes((R.match.get(i._key) || {}).status)), raw: true }], findings: () => [] },
      { id: 'duplicates', name: 'Duplicate Invoice Report', kpis: K(['duplicateRisk', 'duplicateRate']), sections: () => [{ title: t('dup.invoices', 'Duplicate invoices'), cols: [[t('dup.level', 'Flag'), (d) => d.level], [t('dup.first', 'Original'), (d) => d.aNo], [t('dup.second', 'Suspected'), (d) => d.bNo], [t('f.supplierId', 'Supplier'), (d) => sup(d.supplierId)], [t('f.currency', 'Ccy'), (d) => d.currency], [t('f.amount', 'Amount'), (d) => d.amount], [t('dup.why', 'Why'), (d) => d.reasons.map((x) => S.ui.reason('sig.', x)).join(', ')], [t('dup.paidBoth', 'Both paid'), (d) => (d.paidBoth ? 'Y' : '')]], rows: R.dupInv.list }, { title: t('dup.payments', 'Duplicate payments'), cols: [[t('dup.level', 'Flag'), (d) => d.level], [t('dup.first', 'Original'), (d) => d.aId], [t('dup.second', 'Suspected'), (d) => d.bId], [t('f.amount', 'Amount'), (d) => d.amount], [t('dup.why', 'Why'), (d) => d.reasons.map((x) => S.ui.reason('sig.', x)).join(', ')]], rows: R.dupPay }], findings: () => flags((f) => /duplicate/i.test(f.rule)) },
      { id: 'fraud', name: 'Fraud & Anomaly Report', kpis: K(['fraudAlerts']), sections: () => [{ title: t('nav.fraud', 'Red flags'), cols: flagCols(), rows: R.redFlags }], findings: () => flags((f) => f.severity === 'CRITICAL') },
      { id: 'controls', name: 'Internal Control Report', kpis: K(['controlFailures']), sections: () => [{ title: t('ctl.tests', 'Control tests'), cols: [['ID', (x) => x.id], [t('ctl.domain', 'Domain'), (x) => t('dom.' + x.domain)], [t('ctl.name', 'Test'), (x) => t('ct.' + x.id)], [t('rc.population', 'Population'), (x) => x.population], [t('rc.exceptions', 'Exceptions'), (x) => x.count], [t('common.status', 'Status'), (x) => x.status], [t('rc.note', 'Note'), (x) => x.note]], rows: R.controls.tests }], findings: () => flags((f) => f.category === 'CONTROL') },
      { id: 'sod', name: 'SoD Report', kpis: K([]), sections: () => [{ title: t('sod.users', 'User duty profile'), cols: [[t('sod.user', 'User'), (u) => u.user], [t('sod.role', 'Role'), (u) => u.role], [t('sod.duties', 'Duties'), (u) => Object.entries(u.counts).map(([d, n]) => `${t('duty.' + d)} (${n})`).join('; ')], [t('sod.txConf', 'Conflicts'), (u) => u.txConflicts.length], [t('common.severity', 'Severity'), (u) => u.severity]], rows: R.sod.users }, { title: t('sod.tx', 'Transaction conflicts'), cols: [[t('sod.user', 'User'), (x) => x.user], [t('sod.duties', 'Duties'), (x) => x.duties.map((d) => t('duty.' + d)).join(' + ')], [t('rf.txn', 'Transaction'), (x) => x.detail]], rows: R.sod.tx }], findings: () => [] },
      { id: 'audit', name: 'Audit Trail Report', kpis: K([]), sections: () => [{ title: t('nav.audit', 'Audit trail'), cols: [['#', (e) => e.seq], [t('aud.ts', 'Timestamp'), (e) => e.ts], [t('aud.user', 'User'), (e) => e.userId], [t('sod.role', 'Role'), (e) => e.role], [t('aud.action', 'Action'), (e) => e.action], [t('dq.entity', 'Entity'), (e) => e.entity], [t('aud.record', 'Record'), (e) => e.recordId], [t('aud.field', 'Field'), (e) => e.field], [t('aud.old', 'Old'), (e) => (e.oldValue == null ? '' : JSON.stringify(e.oldValue))], [t('aud.new', 'New'), (e) => (e.newValue == null ? '' : JSON.stringify(e.newValue))], [t('aud.reason', 'Reason'), (e) => e.reason], [t('aud.session', 'Session'), (e) => e.sessionId], ['prevHash', (e) => e.prevHash], ['hash', (e) => e.hash]], rows: S.state.audit }], findings: () => [] },
      { id: 'tax', name: 'Tax Report', kpis: K([]), sections: () => [{ title: t('tax.summary', 'Invoices: gross · tax · withholding · net'), cols: [[t('f.invoiceNo', 'Invoice'), (i) => i.invoiceNo], [t('f.supplierId', 'Supplier'), (i) => sup(i.supplierId)], [t('f.currency', 'Ccy'), (i) => i.currency], [t('f.subtotal', 'Subtotal'), (i) => i.subtotal], [t('f.tax', 'Tax'), (i) => i.tax], [t('tax.effRate', 'Effective rate %'), (i) => (i.subtotal ? r2((i.tax / i.subtotal) * 100) : null)], [t('f.wht', 'WHT'), (i) => i.wht], [t('f.total', 'Gross'), (i) => i.total], [t('tax.net', 'Net payable'), (i) => (i.total != null ? r2(i.total - (i.wht || 0)) : null)]], rows: D.invoices, raw: true }], findings: () => flags((f) => f.category === 'TAX') },
      { id: 'fx', name: 'FX Exposure Report', kpis: K([]), sections: () => [{ title: t('fx.rates', 'FX rates'), cols: [[t('f.currency', 'Ccy'), (r) => r.currency], [t('fx.date', 'Date'), (r) => r.date], [t('fx.rate', 'Rate'), (r) => r.rate], [t('fx.source', 'Source'), (r) => r.source]], rows: D.fxRates }, { title: t('tax.fx', 'Foreign-currency invoices'), cols: [[t('f.invoiceNo', 'Invoice'), (i) => i.invoiceNo], [t('f.currency', 'Ccy'), (i) => i.currency], [t('f.total', 'Total'), (i) => i.total], [t('fx.invRate', 'Rate (invoice date)'), (i) => (i._fx ? i._fx.rate : 'FX RATE NOT AVAILABLE')], [t('fx.base', 'Base amount'), (i) => r2(i._totalBase)], [t('f.outstanding', 'Outstanding'), (i) => r2(i._out)], [t('inv.outBase', 'Outstanding ({ccy})', { ccy: base() }), (i) => r2(i._outBase)]], rows: D.invoices.filter((i) => i.currency && i.currency !== base()) }], findings: () => flags((f) => f.rule === 'dq_fxMissing') },
      { id: 'procurement', name: 'Procurement Performance Report', kpis: K(['poCompliance', 'threeWayRate', 'nonPOSpend', 'maverickSpend', 'top5']), sections: () => [{ title: t('nav.pos', 'Purchase orders'), cols: [[t('f.poNo', 'PO'), (p) => p.poNo], [t('f.supplierId', 'Supplier'), (p) => sup(p.supplierId)], [t('f.poDate', 'Date'), (p) => p.poDate], [t('f.currency', 'Ccy'), (p) => p.currency], [t('f.total', 'Total'), (p) => p._total], [t('po.received', 'Received'), (p) => r2(S.views.poDerived(p).received)], [t('po.invoiced', 'Invoiced'), (p) => r2(S.views.poDerived(p).invoiced)], [t('po.paid', 'Paid'), (p) => r2(S.views.poDerived(p).paid)], [t('po.remaining', 'Remaining'), (p) => r2(S.views.poDerived(p).remaining)], [t('common.status', 'Status'), (p) => S.views.poDerived(p).derived]], rows: D.pos, raw: true }], findings: () => flags((f) => f.category === 'PROCUREMENT') },
      { id: 'wc', name: 'Working Capital Report', kpis: K(['dpo', 'avgPayDays', 'overdueAP', 'discountCapture', 'potentialSavings']), sections: () => [{ title: t('sav.opps', 'Opportunities'), cols: [[t('sav.opp', 'Opportunity'), (s) => t('sv.' + s.type)], [t('sav.current', 'Current'), (s) => r2(s.current)], [t('sav.saving', 'Saving'), (s) => r2(s.saving)], [t('sav.conf', 'Confidence'), (s) => s.confidence], [t('sav.method', 'Method'), (s) => s.method]], rows: R.savings }, { title: t('wc.early', 'Early payments without discount'), cols: [[t('f.paymentId', 'Payment'), (x) => x.p.paymentId], [t('wc.daysEarly', 'Days early'), (x) => x.days], [t('f.net', 'Net base'), (x) => r2(x.p._netBase)]], rows: R.wc.early }], findings: () => [] },
      { id: 'dq', name: 'Data Quality & Control Report', kpis: K([]), sections: () => [{ title: t('dq.issues', 'Validation findings'), cols: [[t('common.severity', 'Severity'), (i) => i.severity], [t('dq.check', 'Check'), (i) => S.ui.reason('dq.', i.check)], [t('dq.entity', 'Entity'), (i) => i.entity], [t('dq.count', 'Records'), (i) => i.count], [t('ev.location', 'Evidence'), (i) => S.engine.sourceSummary(i.rows).map((s) => `${s.file}${s.rows ? ' rows ' + s.rows : ''}`).join('; ')]], rows: R.dq.issues }, { title: t('dq.entities', 'Records by entity'), cols: [[t('dq.entity', 'Entity'), (x) => x[0]], [t('dq.count', 'Records'), (x) => x[1]]], rows: Object.entries(R.dq.summary.byEntity) }], findings: () => [] },
    ];
  };

  REP.build = (id) => {
    const def = REP.defs().find((d) => d.id === id);
    if (!def) return null;
    return { def, title: t('rep.' + id, def.name), sections: def.sections(), findings: def.findings ? def.findings() : [], kpis: def.kpis.map((k) => S.R.kpis[k]).filter(Boolean), notes: def.notes ? def.notes() : [] };
  };

  const stamp = () => (S.state.mode === 'demo' ? '_DEMO_SYNTHETIC' : '');
  const fileBase = (id) => `SUMED_${id}_${S.R.asOf}${stamp()}`;

  REP.excel = (id) => {
    const b = REP.build(id);
    const demo = S.state.mode === 'demo';
    const sheets = [];
    sheets.push({ name: t('rep.sh.summary', 'Summary'), header: false, rows: [[b.title], [t('rep.org', 'SUMED — Arab Petroleum Pipelines Company · Alexandria, Egypt')], [t('rep.asOf', 'As of'), S.R.asOf], [t('rep.generated', 'Generated'), new Date().toISOString(), S.state.session.userId], [t('rep.baseCcy', 'Base currency'), base()], demo ? ['DEMO / SYNTHETIC DATA — not SUMED data'] : [t('rep.live', 'Source: uploaded files (see Source references)')], [], ...b.notes.map((n) => ['ASSUMPTION', n])] });
    if (b.kpis.length) sheets.push({ name: 'KPIs', rows: [[t('rep.kpi', 'KPI'), t('rep.value', 'Value'), t('rep.unit', 'Unit'), t('rep.kind', 'Kind'), t('lin.calc', 'Calculation'), t('lin.source', 'Source'), t('rep.unavailable', 'Unavailable reason')], ...b.kpis.map((k) => [t('kpi.' + k.id, k.label), k.value, k.unit, k.kind, k.formula, k.sources.map((s) => `${s.file}${s.sheet ? ' / ' + s.sheet : ''}${s.rows ? ' / rows ' + s.rows : ''}`).join('; '), k.unavailable])] });
    const allRows = [];
    for (const s of b.sections) {
      sheets.push({ name: s.title, rows: [s.cols.map((c) => c[0]).concat([t('ev.file', 'Source file'), t('ev.sheet', 'Sheet'), t('ev.row', 'Row')]), ...s.rows.map((r) => { const rec = r && r._src ? r : r && r.inv && r.inv._src ? r.inv : r && r.c && r.c._src ? r.c : r && r.p && r.p._src ? r.p : null; if (rec) allRows.push(rec); return s.cols.map((c) => { try { const v = c[1](r); return v == null ? '' : v; } catch (e) { return ''; } }).concat(rec ? [rec._src.file, rec._src.sheet, rec._src.row] : ['', '', '']); })] });
      if (s.raw) {
        const recs = s.rows.filter((r) => r && r._raw);
        const keys = U.uniq(recs.flatMap((r) => Object.keys(r._raw)));
        if (keys.length) sheets.push({ name: 'Raw — ' + s.title, rows: [keys.concat(['file', 'sheet', 'row']), ...recs.map((r) => keys.map((k) => (r._raw[k] instanceof Date ? r._raw[k].toISOString() : r._raw[k] == null ? '' : r._raw[k])).concat([r._src.file, r._src.sheet, r._src.row]))] });
      }
    }
    if (b.findings.length) sheets.push({ name: t('rep.sh.exceptions', 'Exceptions'), rows: [flagCols().map((c) => c[0]), ...b.findings.map((f) => flagCols().map((c) => c[1](f)))] });
    sheets.push({ name: t('rep.sh.calc', 'Calculations'), rows: [[t('rep.kpi', 'KPI'), t('lin.calc', 'Formula'), t('rep.inputs', 'Inputs'), t('rep.assumptions', 'Assumptions'), t('lin.excluded', 'Excluded')], ...Object.values(S.R.kpis).map((k) => [t('kpi.' + k.id, k.label), k.formula, k.inputs.map((i) => `${i.label}=${i.value}`).join('; '), k.assumptions.join('; '), k.excluded.map((e) => `${e.reason} (${e.count})`).join('; ')])] });
    const srcs = S.engine.sourceSummary(allRows.concat(b.findings.flatMap((f) => f.rows || [])));
    sheets.push({ name: t('rep.sh.sources', 'Source references'), rows: [[t('ev.file', 'File'), t('ev.sheet', 'Sheet'), t('ev.rows', 'Rows'), t('ev.page', 'Pages'), t('dq.count', 'Records'), 'DEMO'], ...srcs.map((s) => [s.file, s.sheet, s.rows, s.pages, s.count, s.demo ? 'DEMO / SYNTHETIC' : ''])] });
    U.download(fileBase(id) + '.xlsx', REP.xlsx(sheets, S.isAr()));
    S.audit('report.export', 'report', id, { newValue: 'xlsx' });
  };

  REP.csv = (id) => {
    const b = REP.build(id);
    const s = b.sections[0];
    const rows = [s.cols.map((c) => c[0]), ...s.rows.map((r) => s.cols.map((c) => { try { return c[1](r); } catch (e) { return ''; } }))];
    if (S.state.mode === 'demo') rows.unshift(['DEMO / SYNTHETIC DATA — not SUMED data']);
    U.download(fileBase(id) + '.csv', U.toCSV(rows), 'text/csv;charset=utf-8');
    S.audit('report.export', 'report', id, { newValue: 'csv' });
  };

  REP.pdf = (id) => {
    const b = REP.build(id);
    const demo = S.state.mode === 'demo';
    const R = S.R, C = S.chart;
    const charts = {
      spendTrend: () => C.bars(R.spend.byMonth.map((m) => ({ label: m.key, value: m.amount }))),
      aging: () => C.bars(R.aging.buckets.map((x) => ({ label: t('bk.' + x.id), value: x.amount }))),
      cash: () => C.line(R.cash.weekly.map((w) => 'W' + w.week), [{ name: t('tr.projected', 'Projected cash'), values: R.cash.weekly.map((w) => w.closing) }], { threshold: { value: R.cash.consolidated.minCash, label: t('tr.minCash', 'Minimum cash') } }),
    };
    const kv = (k) => (k.value == null ? NA() : k.unit === '%' ? S.fmt.pct(k.value) : k.unit === 'count' ? S.fmt.num(k.value) : k.unit === 'days' ? S.fmt.days(k.value) : S.fmt.money(k.value, k.unit, { compact: true }));
    const summaryItems = id === 'exec' ? S.views.buildSummary() : [];
    const css = Array.from(document.styleSheets).map((ss) => { try { return Array.from(ss.cssRules).map((r) => r.cssText).join('\n'); } catch (e) { return ''; } }).join('\n');
    const html = `<!doctype html><html lang="${S.lang()}" dir="${S.isAr() ? 'rtl' : 'ltr'}" data-theme="light"><head><meta charset="utf-8"><title>${esc(b.title)}</title><style>${css}
      body{background:#fff;color:#111;padding:24px;font-size:11px} .print-h{border-bottom:3px solid #0b3a5b;margin-bottom:12px} .wm{position:fixed;top:40%;left:10%;font-size:64px;opacity:.07;transform:rotate(-25deg);pointer-events:none} table{width:100%;border-collapse:collapse} th,td{border-bottom:1px solid #ddd;padding:3px 5px;text-align:start} .pg{page-break-inside:avoid;margin:12px 0} @page{margin:14mm}</style></head><body>
      ${demo ? '<div class="wm">DEMO / SYNTHETIC</div>' : ''}
      <header class="print-h"><h1>${esc(b.title)}</h1><p>${esc(t('rep.org', 'SUMED — Arab Petroleum Pipelines Company · Alexandria, Egypt'))} · ${esc(t('rep.asOf', 'As of'))} ${esc(S.fmt.date(R.asOf))} · ${esc(t('rep.generated', 'Generated'))} ${esc(S.fmt.ts(new Date().toISOString()))} · ${esc(S.state.session.userId)}${demo ? ' · <b>DEMO / SYNTHETIC DATA — not SUMED data</b>' : ''}</p></header>
      <section class="pg"><h2>${esc(t('rep.execSummary', 'Executive summary'))}</h2>${summaryItems.length ? `<ol>${summaryItems.slice(0, 30).map((x) => `<li>${esc(x.text)} <span class="muted">[${esc(S.engine.sourceSummary(x.rows).map((s) => s.file + (s.rows ? ' r' + s.rows : '')).join('; ').slice(0, 160))}]</span></li>`).join('')}</ol>` : `<p>${esc(t('rep.execGeneric', '{n} findings · {k} KPIs · data as of {d}.', { n: b.findings.length, k: b.kpis.length, d: S.fmt.date(R.asOf) }))}</p>`}</section>
      ${b.kpis.length ? `<section class="pg"><h2>KPIs</h2><table><thead><tr><th>${esc(t('rep.kpi', 'KPI'))}</th><th>${esc(t('rep.value', 'Value'))}</th><th>${esc(t('lin.calc', 'Calculation'))}</th><th>${esc(t('lin.source', 'Source'))}</th></tr></thead><tbody>${b.kpis.map((k) => `<tr><td>${esc(t('kpi.' + k.id, k.label))}</td><td><b>${esc(kv(k))}</b> <small>${esc(t('kind.' + k.kind))}</small>${k.unavailable ? `<div class="na">${esc(k.unavailable)}</div>` : ''}</td><td><code>${esc(k.formula || '')}</code></td><td class="small">${esc(k.sources.map((s) => `${s.file}${s.rows ? ' · rows ' + s.rows : ''}`).join('; ').slice(0, 220))}</td></tr>`).join('')}</tbody></table></section>` : ''}
      ${(b.def.charts || []).map((c) => `<section class="pg"><h3>${esc(t('ch.' + c, c))}</h3>${charts[c]()}</section>`).join('')}
      ${b.findings.length ? `<section class="pg"><h2>${esc(t('rep.findings', 'Findings & red flags'))}</h2><table><thead><tr>${flagCols().map((c) => `<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${b.findings.slice(0, 80).map((f) => `<tr>${flagCols().map((c) => `<td>${esc(c[1](f) == null ? '' : c[1](f))}</td>`).join('')}</tr>`).join('')}</tbody></table></section>` : ''}
      ${b.sections.map((s) => `<section class="pg"><h2>${esc(s.title)}</h2><table><thead><tr>${s.cols.map((c) => `<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${s.rows.slice(0, 150).map((r) => `<tr>${s.cols.map((c) => { let v; try { v = c[1](r); } catch (e) { v = ''; } return `<td>${esc(typeof v === 'number' ? S.fmt.num(v, Math.abs(v) < 100 && v % 1 ? 2 : 0) : v == null ? '' : v)}</td>`; }).join('')}</tr>`).join('')}</tbody></table>${s.rows.length > 150 ? `<p class="muted">${esc(t('rep.truncated', 'First 150 of {n} rows — full detail in the Excel export.', { n: s.rows.length }))}</p>` : ''}</section>`).join('')}
      ${b.notes.length ? `<section class="pg"><h2>${esc(t('tr.assumptions', 'Assumptions'))}</h2><ul>${b.notes.map((n) => `<li>${esc(n)}</li>`).join('')}</ul></section>` : ''}
      <section class="pg"><h2>${esc(t('rep.recs', 'Recommendations'))}</h2><ul>${S.R.insights.slice(0, 8).map((i) => `<li><b>${esc(S.insightText(i, 'o'))}</b> — ${esc(S.insightText(i, 'a'))}</li>`).join('')}</ul></section>
      <section class="pg"><h2>${esc(t('rep.evidence', 'Evidence references'))}</h2><ul>${S.engine.sourceSummary(b.findings.flatMap((f) => f.rows || []).concat(b.kpis.flatMap((k) => (k.rows || []).map((x) => S.R.index.get(x.key)).filter(Boolean)))).map((s) => `<li>${esc(s.file)}${s.sheet ? ' · ' + esc(s.sheet) : ''}${s.rows ? ' · rows ' + esc(s.rows) : ''} (${s.count})</li>`).join('')}</ul></section>
      <script>setTimeout(function(){window.print()},400)<\/script></body></html>`;
    const w = window.open('', '_blank');
    if (!w) { S.ui.toast(t('rep.popup', 'Allow pop-ups to generate the PDF.'), 'error'); return; }
    w.document.write(html); w.document.close();
    S.audit('report.export', 'report', id, { newValue: 'pdf' });
  };
})(typeof window !== 'undefined' ? window : globalThis);
